### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in

type.h, resolveFunction.cpp,
spec/ranges.rst, technotes/gpu.rst
ErrorWriter.h, scope-types.h
resolution-error-classes-list.cpp
scope-queries.cpp,
ChapelBase.chpl, ChapelSyncvar.chpl
Regex.chpl, IO.chpl
gpu-rocm.c

### CODE REVIEW

**Comment by cassella** [comment]
@mppf Please review, particularly:

`scope-queries.cpp` - I'm guessing "rerepresent" was just supposed to be "represent", though don't know enough about what's going on to be sure something isn't being re-represented.

and

`resolution-error-classes-list.cpp` - I changed `BorrowedIdsWithIter` to `BorrowedIdsWithName` since that's the only thing that starts with `BorrowedIds`; I don't know if that makes sense in context.


I only spot-checked a few random tests.

**Review by mppf — APPROVED** [review]
Looks good. I've started a testing run.

**Comment by mppf** [comment]
@cassella -- there was one failure in the testing run

> [Error matching program output for deprecated/IO/mmapParenless]


Please include an update to this test's .good file in this PR (since you fixed a spelling error in the deprecation message).

**Comment by cassella** [comment]
Ugh, sorry about that.  I don't know how I missed that.  :-/

Updated with the .good file fix into the same commit that fixes the typo, and force-pushed.

**Pull request merged**
