### PR TITLE
Add tests for 21651: internal errors continue/breaking to labeled loop outside coforall or on statement

### PR DESCRIPTION
**Pull request by cassella**
These were futures, but have been fixed in the meantime by #21664.

### CODE REVIEW

**Comment by cassella** [comment]
@bradcray since this is related to #21635 / #21528?

Now that I actually look at the chronologically first of those PR's PR comment, I don't know why this has different behavior than `test/parallel/begin/deitz/test_control_flow.chpl`.

**Comment by DanilaFe** [comment]
Seems like https://github.com/chapel-lang/chapel/pull/21664 should fix the bug in #21651.
<details>
<summary>Test cases and their output</summary>

```Chapel
label outerer for qq in 1..3 do {
  coforall loc in Locales[0..0] do on loc {
    coforall tid in 0..<1 {
      var j = 0;
      label outer while j < 10 {
	var i = 1;
	do {
	  writeln((i, j));
	  if i == 3 then
	    break outerer;
	  i += 1;
	  j += 1;
	} while (i < 100);
      }
    }
  }
}
```
Produces
```
bad1.chpl:1: In module 'bad1':
bad1.chpl:10: error: 'break' to label 'outerer' outside of a 'coforall' statement is not allowed
bad1.chpl:3: note: cannot 'break' out of a 'coforall' statement
```

```Chapel
label outerer for qq in 1..3 do {
  on Locales[0] {
    var i = 1;
    do {
      writeln(i);
      if i == 3 then
	continue outerer;
      i += 1;
    } while (i < 100);
  }
}
```
Produces:
```
bad2.chpl:1: In module 'bad2':
bad2.chpl:8: error: 'continue' to label 'outerer' outside of an 'on' statement is not allowed
bad2.chpl:3: note: cannot 'continue' out of an 'on' statement
```

```Chapel
label outerer for qq in 1..3 do {
  coforall loc in Locales[0..0] do on loc {
    coforall tid in 0..<1 {
      var j = 0;
      label outer while j < 10 {
        var i = 1;
        do {
          writeln((i, j));
          if i == 3 then
            continue outerer;
          i += 1;
          j += 1;
        } while (i < 100);
      }
    }
  }
}
```
Produces:
```
bad3.chpl:1: In module 'bad3':
bad3.chpl:10: error: 'continue' to label 'outerer' outside of a 'coforall' statement is not allowed
bad3.chpl:3: note: cannot 'continue' out of a 'coforall' statement
```

And
```Chapel
label outerer for qq in 1..3 do {
  on Locales[0] {
    var i = 1;
    do {
      writeln(i);
      if i == 3 then
        continue outerer;
      i += 1;
    } while (i < 100);
  }
}
```
Produces
```
bad4.chpl:1: In module 'bad4':
bad4.chpl:8: error: 'continue' to label 'outerer' outside of an 'on' statement is not allowed
bad4.chpl:3: note: cannot 'continue' out of an 'on' statement
```
</details>

If that's not asking too much, perhaps instead of futures these cases can be added as regular tests to guard against regressions?

**Comment by cassella** [comment]
Thanks!  I updated the PR to add them as regular tests.

**Comment by DanilaFe** [comment]
Tested this and everything looks good -- going to merge.

**Pull request merged**
