### PR TITLE
Remove ChapelEnv module

### PR DESCRIPTION
**Pull request by bradcray**
Since we introduced ChplConfig in Chapel 1.26.0 and deprecated the
contents of ChapelEnv, I'm removing the ChapelEnv module here and
updating tests that relate to it.

### CODE REVIEW

**Comment by bradcray** [comment]
Question for my reviewer:  Does it seem reasonable to simply remove this rather than deprecating the `ChapelEnv` symbol and module itself given that the previous release deprecated all of its contents?  Originally I was thinking "yes" because we don't actually name the Chapel module on the standard modules page, calling it "Chapel Environment Variables" instead.  But after putting this PR together, I realized that if you click through to the page, it does document it.  I convinced myself that this is still reasonable (people won't typically refer to the module name since it's auto-used, etc.) but could be convinced that I'm wrong.

**Comment by bradcray** [comment]
(also, note that the number of modules counted as dead was written here under the assumption that #19815 will be merged first... though I realize that I'll still need to resolve conflicts, so didn't really save myself work...).

**Review by lydia-duncan — APPROVED** [review]
Looks good to me!

**Comment by bradcray** [comment]
Thanks for taking a look Ben!

We didn't deprecate the module before because it's auto-used, so every program would get the deprecation warning.  For auto-used modules, the best practice (that I've come up with) is to deprecate all of the contents of the module instead, which is what I did for 1.26.0.

If we were to deprecate it in this release, I think that we would:
* make it no longer be auto-used
* deprecate the module itself this time
* I'd leave the symbols it contains where they are, and would either remove the deprecation warnings on them or not (not sure).  The benefit of removing would be that it would simplify the code that we're carrying forward and might reduce redundant deprecation warnings (i.e., they'd just get one for ChapelEnv, and not for each symbol within it anymore, since that would be implied).  The benefit of keeping them would be that it'd reduce the chances that something slipped past us.

That approach would be similar to what I did for the VectorizingIterator module deprecation in #19815, which was similar to this case because it was auto-used.  There, I chose not to simply remove the module because we're still relying on it for some tests, and `foreach` can't yet do everything that `vectorizeOnly()` can do (such as shadow variables and expressions).  So there, I view the deprecation as a statement of future intent rather than something we're ready to act on today.  Here, the only reason to delay that I can think of would be if someone were relying on the `ChapelEnv` name in some way.  But I can't come up with compelling ways in which they'd use it which wouldn't have already led to a deprecation warning for the symbols within it in 1.26.0.

**Review by bmcdonald3 — APPROVED** [review]
Thanks for the explanation. It sounds like quite a bit of extra work to deprecate the module rather than just delete it now, which I know isn't a particularly good reason to do something, but, like you, I can't come up with any reason why anyone would be relying on the `ChplEnv` name.

Good to remove to me 👍

**Pull request merged**
