### PR TITLE
correct numTasks in parallel List these()

### LINKED ISSUE #21264: reduction over a list with 33+ elements divides by zero.
### Summary of Problem

A reduction over a `list` with more than 32 elements results in a divide by zero error.
Smaller lists work.  I haven't done an exhaustive search past length 33, but the ones I've tried have all hit the error.

### Steps to Reproduce

**Source Code:**

```chapel
use IO, List;

var spotList: list(3*int);

/*
while readf("%i,%i,%i\n", spot(0), spot(1), spot(2)) {
  spotList.append(spot);
}
*/
config var limit = 2866;
for i in 1..limit do spotList.append((0,0,0));

var dims: 3*(2*int);

forall i in 0..2 with (ref dims, const ref spotList) do
  dims[i] = minmax reduce([s in spotList] s[i]);

/*
 // Also divides by zero
dims[0](0) = min reduce([s in spotList] s[0]);
*/

writeln(dims);
```

**Execution command:**

```
fortytwo@enodia:~/src/aoc/2022$ for i in `seq 1 66`; do echo -n $i:\ ; ./divby0 -nl1 --limit $i; done
1: ((0, 0), (0, 0), (0, 0))
2: ((0, 0), (0, 0), (0, 0))
3: ((0, 0), (0, 0), (0, 0))
4: ((0, 0), (0, 0), (0, 0))
...
30: ((0, 0), (0, 0), (0, 0))
31: ((0, 0), (0, 0), (0, 0))
32: ((0, 0), (0, 0), (0, 0))
33: divby0.chpl:16: error: halt reached - Attempt to divide by zero
34: divby0.chpl:16: error: halt reached - Attempt to divide by zero
35: divby0.chpl:16: error: halt reached - Attempt to divide by zero
...
63: divby0.chpl:16: error: halt reached - Attempt to divide by zero
64: divby0.chpl:16: error: halt reached - Attempt to divide by zero
65: divby0.chpl:16: error: halt reached - Attempt to divide by zero
66: divby0.chpl:16: error: halt reached - Attempt to divide by zero
```

**Associated Future Test(s):**

None yet

### Configuration Information

```
chpl version 1.29.0.9c39a837f2
  built with LLVM version 14.0.0

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: none
CHPL_LLVM: system
CHPL_AUX_FILESYS: none

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

Ubuntu clang version 14.0.0-1ubuntu1
```

### PR DESCRIPTION
**Pull request by cassella**
The leader iterator has this pattern to divide the list into chunks:

```chapel
    iter these(param tag) ref where tag == iterKind.leader {
      const osz = _size;
      const minChunkSize = 32;
      const hasOneChunk = osz <= minChunkSize;
      const numTasks = if hasOneChunk then 1 else dataParTasksPerLocale;
      const chunkSize = floor(osz / numTasks):int;
```

But the default value of dataParTasksPerLocale is 0, which means to use here.maxTaskPar, as e.g. iterators in Sort.chpl do.  When numTasks is thus set to 0, the calculation of chunkSize divides by zero.

Update the leader iterator to use here.maxTaskPar when dataParTasksPerLocale is 0.

Also update the standalone iterator similarly -- it hardcodes here.maxTaskPar without checking dataParTasksPerLocale.  The user should be able to use this setting to override here.maxTaskPar, so set it up that way.

There was already a listTheseParLF.chpl test set up to test the leader/follower iterators.  I increased its default list size to be large enough to require this calculation, and also removed the .notest file.

resolves #21264

### CODE REVIEW

**Comment by cassella** [comment]
@dlongnecke-cray 

I verified that on main, listThesePartLF hit the same divide by zero error as in #21264 when run with the `testIters` value I set in this PR.

#13877 added the listTheseParLF test and the .notest file -- is there a reason this test shouldn't be used?

Testing is still underway.  All I'm testing is `test/library/standard/List`.

**Comment by cassella** [comment]
... and remove tabs...

**Comment by mppf** [comment]
@cassella - could you also add a test showing a reduction over a `list` like in #21264 that also checks the result of the reduction? Thanks.

**Comment by cassella** [comment]
@mppf Done.

**Comment by bradcray** [comment]
Thanks Paul!  Gotta love it when people fix their own bugs before I've even seen that an issue was opened.  :)

**Pull request merged**
