### PR TITLE
Add test of +reducing a set

### PR DESCRIPTION
**Pull request by cassella**
Add test of +reducing a set

### CODE REVIEW

**Comment by cassella** [comment]
I noticed that this just worked, but didn't see a test of it (at least in test/library/standard/Set), so here's one to lock it in.

@dlongnecke-cray @bmcdonald3 I think the two of you have done the most recent work on Set.

**Comment by cassella** [comment]
@dlongnecke-cray , @bmcdonald3 , could one of you review?

**Comment by bmcdonald3** [comment]
Yes, sorry we missed this! I've got it on my list and will take a look today. Thanks Paul!

**Review by bmcdonald3 — APPROVED** [review]
Looks good to me and testing came back clean; thanks for the contribution!

**Pull request merged**
