### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in

clangUtil.cpp (and test files), resolution-types.h,
Resolver.cpp, call-init-deinit.cpp, copy-elision.cpp,
GPU.chpl, IO.chpl, frontend/README

### CODE REVIEW

**Comment by cassella** [comment]
@mppf, could you review the clangUtil.cpp and test changes?
(I haven't been able to rerun the test since I don't have a working system LLVM right now.)

(I haven't tracked down the provenance of the other typos yet.)

I think the IO.chpl one is the only one that impacts the docs, though the clangUtil.cpp one can show up in disassembly output.

**Review by mppf — APPROVED** [review]
These changes look good to me, but I'd like to merge it after the 1.29 release. We'll just need to run testing before doing so.

**Comment by cassella** [comment]
Merged to resolve conflict, and updated with a few new fixes

 
- [ ] @DanilaFe frontend/README
- [ ] @jeremiah-corrado  IO.chpl
- [ ] @mppf call-init-deinit.cpp, copy-elision.cpp, resolution-types.h, Resolver.cpp, clangUtil.cpp, print-asm*
- [ ] @stonea GPU.chpl

**Review by mppf — APPROVED** [review]

**Comment by mppf** [comment]
I've run full local testing on this and will merge it. The items that remained to be reviewed are trivial and I have reviewed them.

**Pull request merged**
