### PR TITLE
Add regexdna-redux.chpl to the release and submitted directories.

### PR DESCRIPTION
**Pull request by lydia-duncan**
The Computer Language Benchmarks Game has recently undergone some changes with
regards to the regexdna benchmark, resulting in the updating and migrating of
many implementations to the new form.  This saves a copy of the updated version
to our submitted and release directories, so that we can track that in addition
to our original version.

Note that the new benchmark has slightly different expected output than the
original, leading to differences in the .good and .perfkeys files.  Other than
the obvious update to the .chpl file, all other support files were copied
verbatim from the original.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@chapel-lang/perf-team - for your consideration.  This passed a local sanity check, I'm verifying I didn't forget any files

**Comment by ronawho** [comment]
Think there's a README in the submitted dir that should be updated

**Comment by lydia-duncan** [comment]
Ah, dur.  And probably one in the release directory as well.

**Comment by bradcray** [comment]
Also a Makefile in the release directory I think?

**Comment by lydia-duncan** [comment]
Huh.  I was worried the link to the old regex dna in the submitted README wouldn't work anymore, but it looks like it does for now.

**Comment by lydia-duncan** [comment]
Thanks @bradcray and @ronawho!  Good to go?

**Comment by ronawho** [comment]
Looks good to me 

Are we planning to retire the non-redux version?

**Pull request merged**
