### PR TITLE
Consider the deprecated keyword as an alternative to compilerWarning().

### PR DESCRIPTION
**Pull request by gbtitus**
Update deprecation documentation for new, handy keyword!

### CODE REVIEW

**Comment by lydia-duncan** [comment]
If my memory serves, we weren't planning on documenting the `deprecated` keyword for now because we only implemented it this way because attributes aren't going to be online for a while.

**Comment by gbtitus** [comment]
> ... we weren't planning on documenting the `deprecated` keyword for now ...

Even for ourselves? The file I'm modifying here isn't released as far as I know and doesn't appear in the online doc tree. At least, "deprecate" in the search box on https://chapel-lang.org/docs/master/index.html doesn't list it. I only encountered it by accident, when I grep'ped the test subdir for "deprecate".

**Comment by gbtitus** [comment]
I'll have a go at softening the recommendation to express when/why `deprecated` might be better, while also noting that it may not be there forever.

**Comment by gbtitus** [comment]
@lydia-duncan does this look better?

**Review by lydia-duncan — APPROVED** [review]
Awesome, thanks!  And thanks for spotting it!

**Pull request merged**
