### PR TITLE
Remove `save-sphinx.doc` skipif condition

### PR DESCRIPTION
**Pull request by awallace-cray**
Looks like it is safe to remove this `save-sphinx.doc` skipif condition, after PR #4413.
 
This is a followup to the comment in `save-sphinx.doc.skipif`:

    # FIXME: (Un)skip this test in nightly chapel testing environment 
    # -- (thomasvandoren, 2015-03-10)

**Note:** This PR depends on the Python version update in #4413 and should not be merged until that PR is merged.

(Having said that, `save-sphinx.doc` may also work in the testing environment, even without the PR; I did not try it.)

### CODE REVIEW

**Comment by awallace-cray** [comment]
This trivial change should be okay, now that PR #4413 is merged.

**Comment by awallace-cray** [comment]
@ben-albrecht or @lydia-duncan would you review? Thanks!

**Comment by ben-albrecht** [comment]
Just some clarifications:

What exactly was this `skipif` doing before? Is it simply checking if `chpldoc` is built? What about #4413 removed the requirement for this file?

**Comment by awallace-cray** [comment]
Answers: 

The only thing the skipif really did was to skip the test if running on those particular machines. 

The part about skipping if chpldoc wasn't available, that's default- you get that, even without the skipif file. I checked. 

#4413 had nothing to do with this, as far as I know.  Basically, I noticed this skipif file when I was testing #4413. I checked to see if the test would work now, on those machines, without the skipif, because I was curious. I just didn't make sure the test would work without the skipif etc, without #4413 as well.

**Comment by ben-albrecht** [comment]
Ah, OK. That makes the reference to #4413 in the PR description confusing. 

Anywho, I think this is good to merge.

**Pull request merged**
