### PR TITLE
Simplified synchronization of C and C++ compilation modes

### PR DESCRIPTION
**Pull request by dmk42**
This change greatly simplifies the logic for choosing the compilation mode for gcc, and uses the exact same logic to determine the compilation mode for clang.

This is motivated by the need to accomplish two things:
1. Ensure that at least C99 is used at all times, for use in various parts of the code.
2. Ensure that at least C11 and at least C++11 are enabled together when that would be appropriate for use by the CHPL_ATOMICS=cstdlib option.

### CODE REVIEW

**Comment by gbtitus** [comment]
This looks good.  Do we need to do similarly for Makefile.cray-prgenv-gnu, or do we have minimum gcc version number guarantees there?  Anything for the other non-gnu, non-clang compilers?

**Comment by dmk42** [comment]
Makefile.cray-prgenv-gnu does an include of Makefile.gnu, so we are covered there.

Because of your comment, I took a look at Makefile.intel and found that it could also use the exact same method, so I added it there.  When using the Intel compiler, the code uses GNU extensions, so I had to say \-\-std=gnu99 and \-\-std=gnu++11 instead of c99 and c++11.  Our copy of the Intel compiler does not yet support standard atomics, but Intel's latest compiler does, so we'll be ready if/when we switch to that.

I changed the clang and gcc Makefiles to use gnu99 and gnu++11 as well, just so that the clang, gcc, and intel Makefiles could have exactly the same text for that part.  They had used gnu99 before the first time I touched them anyway.

The PGI compiler cannot use the same method, but they can't do standard atomics anyway, and PGI seems pretty stagnant, so it isn't a big deal for that to remain as it is.

The Cray compiler cannot use the same method, but it does not support standard atomics currently.  Once the Cray compiler fully supports C11, it would be good to take another look at that Makefile to see how we can enable standard atomics for that.

I don't have access to the Pathscale or IBM compilers, but I don't think it's important for us to enable standard atomics on those right now anyway.

After the changes, I retested, so I think we're ready to go.

**Comment by gbtitus** [comment]
All seems well -- 👍 .

**Comment by dmk42** [comment]
Thanks!  I'll wait a little while to see if travis-ci gets unstuck, and then merge regardless.

**Pull request merged**
