### PR TITLE
Remove the deprecated Assert module

### PR DESCRIPTION
**Pull request by e-kayrakli**
The Assert module was deprecated in Chapel 1.23, where we moved its contents to
Builtins module.

#### Test status
- [x] make docs
- [x] standard

### CODE REVIEW

**Comment by bradcray** [comment]
Help my aging memory:  In Michael's module review, he was pushing back against having a Builtins module.  In that world, what was he proposing happen to assert?  To merge it into whatever module things like exit() and halt() compilerError() and such were defined?  (just want to make sure we don't remove Assert only to re-add it later).

**Comment by e-kayrakli** [comment]
> Help my aging memory: In Michael's module review, he was pushing back against having a Builtins module. In that world, what was he proposing happen to assert? To merge it into whatever module things like exit() and halt() compilerError() and such were defined? (just want to make sure we don't remove Assert only to re-add it later).

I though about the same thing and went through the relevant issue quickly: https://github.com/chapel-lang/chapel/issues/16808

I think the general trend is to create a module that encompass more than assert. And I haven't seen anybody suggesting we should have an Assert module only for Asserts.

It also feels like we actually asked users to stop using Assert a release ago, so if we change our minds and bring the Assert module back, it will be sort of like re-adding to the users.

All that being said, I can postpone merging this after the release. I don't think it is huge amount of code that is a maintainability pain on us.

**Comment by bradcray** [comment]
Since our memories match, I don't have a problem proceeding with this (and like getting rid of deprecation warnings when possible; particularly since it eliminates that category in the documentation?).  The PR looks good to me.

**Comment by e-kayrakli** [comment]
Yep it eliminates that section from the docs. This passed standard paratest, merging.

**Pull request merged**
