### PR TITLE
Add support for rectangular domains over unbounded ranges

### PR DESCRIPTION
**Pull request by daviditen**
This adds support for domains with unbounded ranges. It updates a few domain creation methods to include a param `boundedType: BoundedRangeType` argument and adds the same as a field of `DefaultRectangularDom`. It also changes a few range arguments to be generic on this field.

I wanted this to include the ability to slice a rectangular array with an unbounded range, but that ran into a few problems. In a few cases it introduced memory leaks. It also broke a test linking sliced arrays through their domain, e.g.

``` chapel
var D = {1..10};
var A: [D] int;
ref rA = A[D];
D = {11..20};
rA[11] = 1; // out of bounds after enabling unbounded slicing
```

There were more test updates required than I anticipated. Most were .good updates to add the new domain field in error messages or tests that print domain types. A few had their own rectangular domain types and needed updates to match the signature of `dsiNewRectangularDom`.

### CODE REVIEW

**Comment by cassella** [comment]
I think this requires all dimensions of the domain to have the same boundedness?  Issue #10595 (which I think this is a response to) has the example `const PosRows = {1.., ..};`.  Will that be supported in a future PR?

**Comment by daviditen** [comment]
Yes, this PR requires the boundedness of all dimensions to match. To support different bounded types in different dimensions would probably require the `boundedType` param in `DefaultRectangularDom` to be a `rank*BoundedRangeType` tuple.

**Comment by bradcray** [comment]
@daviditen: What's the status of this PR?

**Comment by daviditen** [comment]
We decided against doing this because it added a new param field to domains, changing the type of every domain.

**Pull request closed without merging**
