### PR TITLE
Make tests output in sorted order for associative domains

### PR DESCRIPTION
**Pull request by aconsroe-hpe**
Tests that output information using associative domains are dependent on the implementation of the hashtable for their ordering. This can make for some noisy diffs when changes are made to the underlying hashtable implementation.

This was mentioned in Cray/chapel-private#2649 and motivated in reviewing #18818

I was curious what the change would necessitate and by the time I was done investigating, I was already 90% of the way there so I went ahead and made the changes.

There may be other tests that need fixing but have not identified them yet.

* [x] paratest

### CODE REVIEW

**Comment by aconsroe-hpe** [comment]
@bradcray this touches a bunch of tests under a `bradc` dir -- I copy pasted my changes throughout as it didn't feel too egregious given `foo` was duplicated. But if you'd prefer a cleanup with a `use`, I could see that too.

@bmcdonald3 does this look good?

**Review by bmcdonald3 — APPROVED** [review]
Looks good to me, thanks for doing this!

**Comment by bradcray** [comment]
This seems fine to me, thanks for cleaning up my laziness, Andrew!

The one slight pause that I had when looking at this (which I don't think should hold up this PR in any way) is that I feel as though there have been some discussions/questions about whether `sorted()` should be supported on associative domains by default given that it drags in the entire Sort module (I believe), and is an example of our "everything compiles the world" issue.  So longer-term, it wouldn't surprise me if we deprecated the .sorted() method or moved it to the `Sort` module as a tertiary method or the like.  But again, that doesn't suggest doing something different here for now (there are definitely other tests that use the iterator), seeing its use just reminded me of this mildly unsettling open question.

**Comment by bradcray** [comment]
@aconsroe-hpe : Not directly related to this effort, but since you've touched the `Dataframes` start/sketch module, would you mind `git` moving that out of `test/library/standard` (which was aspirational and optimistic at the time) and into `test/library/draft` (which I think didn't exist at that time?)

**Comment by aconsroe-hpe** [comment]
Moved the dir @bradcray

**Pull request merged**
