### PR TITLE
update chips/Makefile and .gitignore for docs reorg

### PR DESCRIPTION
**Pull request by cassella**
chips/Makefile: update for docs reorg
.gitignore: update chips for docs reorg

### CODE REVIEW

**Comment by cassella** [comment]
I tested only by running `make` in doc/developer/chips

**Comment by lydia-duncan** [comment]
Note for future reference: naming your branch the same as a path in the repository makes it tricky to checkout and test locally.

**Comment by lydia-duncan** [comment]
Otherwise, this looks good to me (and I verified that make in the chips directory worked)

**Comment by cassella** [comment]
LOL, oops, sorry.   I didn't think of that!

**Pull request merged**
