### PR TITLE
Deprecate SystemError.fromSyserr in favor of a standalone fromSyserr function

### PR DESCRIPTION
**Pull request by daviditen**
Add deprecation messages for SystemError.fromSyserr and add a stand alone
version.

Update modules and a test to not use the deprecated version.

Add a test/deprecated test.

Closes
https://github.com/Cray/chapel-private/issues/3398

Signed-off-by: David Iten <daviditen@users.noreply.github.com>

### CODE REVIEW

**Comment by daviditen** [comment]
That's a good point. The `syserr` that these functions are named for is actually the one in their first arguments (not `SystemError`), but it's not very clear what it's creating out of it now that it's not tied to `SystemError`. Maybe `SystemErrorFrom`?

**Comment by jeremiah-corrado** [comment]
Yeah, I think that sounds good! And then the fact that its *from* a `syserr` is reflected in the function header anyway.

**Comment by jeremiah-corrado** [comment]
Sorry, I should have asked earlier, but should the 'S' be lowercase? Or is it better to leave it uppercase to match the type name?

**Comment by daviditen** [comment]
This PR was replaced with #20469.

**Pull request closed without merging**
