### PR TITLE
Lexer linefeed

### PR DESCRIPTION
**Pull request by mppf**
As suggested by Damian McGuckin on chapel-users, treat form feed
characters ('\f') as whitespace.

### CODE REVIEW

**Comment by mppf** [comment]
passed full local testing

**Comment by bradcray** [comment]
I would guess that formfeed characters should affect the linecount, but am not sure how they ought to...  I mentioned this to Damian in a follow-up post to my original suggestion that this would be the place to add it but don't think we came to any resolution.  This may have been part of the reason that we shied away from supporting less well-understood (by us) forms of whitespace at the beginning of time.  See the processNewLine() case above this whitespace case -- should it be added there instead?  Or should it be considered to add multiple lines to the current line number?

**Comment by mppf** [comment]
@bradcray, form feed characters should not afftect the line count. I created an example file which contained a form feed character and verified that with vim and emacs and nano, the form feed does not create a new line. (in C code, it is used as a section dividing marker in some styles). Therefore, I think that the current code is correct.
I've added a test with a form feed in it. The Chapel compiler reports an error on line 5. If you open formfeed.chpl with your favorite editor and go to line 5, you are on the line with the error. So we're doing the right thing.

**Comment by mppf** [comment]
@bradcray given all of that, is this patch OK with you?

**Comment by bradcray** [comment]
Cool, thanks for the additional reassurance.  Yeah, I think this is good to go.  Thanks for running with it.

**Pull request merged**
