### PR TITLE
Convert other perf test chameneos variants over to managed classes

### PR DESCRIPTION
**Pull request by bradcray**
This converts other performance test copies of chameneos over to use owned chameneos and borrowed meeting places.

TODO:
- [x] see how other chameneos rewrites fared
- [x] memleaks verification
- [x] performance correctness testing

### CODE REVIEW

**Comment by bradcray** [comment]
Saving this until after the release because none of these are included in the release and none will give us the ability to gather new historical release-over-release data (all rely on new features).

**Comment by bradcray** [comment]
@ronawho, @lydia-duncan : Any concerns about the changes made here to your chameneos variations?  (this makes them more like what we've done with the release versions by taking better advantage of managed classes).

**Comment by lydia-duncan** [comment]
No issues here!

**Comment by bradcray** [comment]
As expected, it doesn't look like there were any major perf changes here that were outside the noise, though Elliot's variation did hit a new local minimum:

https://chapel-lang.org/perf/chapcs/?startdate=2018/08/31&enddate=2018/09/19&graphs=chameneosreduxshootoutbenchmarkn6000000

**Pull request merged**
