### PR TITLE
USR_WARN for enabling optimizations along with --incremental

### PR DESCRIPTION
**Pull request by kushalsingh007**
* Switched to enabling warning for -O instead of --fast only.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@bradcray - that's what you said, right?

**Comment by bradcray** [comment]
Yep!

And from my perspective, we could either leave the ccflags check here in (on the argument that it's a common case to look for) or out (on the argument that each C compiler may have other optimization flags that we couldn't be aware of, or might not even use -O to turn on optimizations -- though I'm not aware of any exceptions).  I don't feel strongly either way.

Nit-picking (if you didn't think I was doing that already): In testing, I was surprised that this warning is printed out in codegen rather than at the end of the driver/command-line parsing phase.  Specifically, I was surprised by the delay that occurred before printing the warning out, and it seems like we should know all of the information to print it much sooner.  Could the code be moved to the end of postprocess_args(), for example?

**Comment by lydia-duncan** [comment]
I don't see why not.  Kushal?

**Comment by kushalsingh007** [comment]
Sure. I'll do that first thing in the morning

**Comment by lydia-duncan** [comment]
Passed std and std + --fast.  Initial results with std + --incremental show that we've probably got a couple more tests to add to the system-wide prediff.  I'll email you the full list when it completes

**Comment by kushalsingh007** [comment]
I kept the cc-flags warning for now , but I moved it the relevant code to ```driver.cpp``` now.

**Comment by lydia-duncan** [comment]
With updates to the prediff, this now passes all testing.  Merging

**Pull request merged**
