### PR TITLE
Add a "vectorizeOnly" iterator to allow vectorization without task creation

### PR DESCRIPTION
**Pull request by ronawho**
Add a vectorize only wrapper iterator and supporting code required to implement
it. This vectorizeOnly iterator wraps and vectorizes other iterators. It takes
one or more iterables (an iterator or class/record with a these() iterator) and
yields the same elements as the wrapped iterables.

This iterator exists to provide a way to vectorize loops without invoking a
parallel iterator with the goal of avoiding task creation for loops with small
trip counts or where task creation isn't desirable.

Data parallel operations in Chapel such as forall loops are order independent.
However, a forall is implemented in terms of either leader/follower or
standalone iterators which typically create tasks. The vectorizeOnly iterator
exists to allow vectorization of order independent loops without task creation
by invoking the serial version of the wrapped iterable(s). By using this
wrapper iterator a user is asserting that the loop is order independent (and
thus a candidate for vectorization) similar to using a forall loop.

When invoked from a serial for-loop, this iterator will simply mark users'
iterator(s) as order independent. When invoked from a parallel forall-loop this
iterator will implicitly be order independent because of the semantics of a
forall, and additionally it will invoke the serial iterator instead of the
parallel iterator. For instance:

  ```chapel
  forall i in vectorizeOnly(1..10) do;
  for    i in vectorizeOnly(1..10) do;
  ```

will both effectively generate:

  ```c
  CHPL_PRAGMA_IVDEP
  for (i=1; i<=10; i+=1) {}
  ```

The vectorizeOnly automatically handles zippering, so the "zip" keyword is not
needed. To vectorize:

  ```chapel
  for (i, j) in zip(1..10, 1..10) do;
  ```

simply write:

  ```chapel
  for (i, j) in vectorizeOnly(1..10, 1..10) do;
  ```

Currently, the zip keyword is still allowed so you could write code like:

  ```chapel
  for    (i, j) in zip(vectorizeOnly(1..10, 1..10)) do;
  for    (i, j) in zip(vectorizeOnly(1..10), vectorizeOnly(1..10)) do;
  forall (i, j) in zip(vectorizeOnly(1..10, 1..10)) do;
  forall (i, j) in zip(vectorizeOnly(1..10), vectorizeOnly(1..10)) do;
  ```

For the serial case: no vectorization will occur unless all of the iterands use
the vectorizeOnly iter, but the program will execute correctly. For the
parallel case, bad things will happen if not all the iterands use the
vectorizeOnly iter because it'll be trying to zipper parallel and serial
iterators.

The main reason zipering is allowed is because users might write there own
wrappers or iterators that call the vectorizeOnly iterator and then zipper
their iterators. That said, the vectorizeOnly iterator can only be parallel
zippered with other vectorizeOnly iterators and if serial zippered all iterands
must be vectorizable or the final one will not be.

There's also no easy way to prohibit zippering without compiler involvement.
For the leader/follower case you could easily put a warning or error in the
leader and follower iterators but I'm not sure how to do the same thing for
serial zippering without compiler involvement.

TODO:
- Move vectorizeOnly from ChapelIteratorSupport to a standard module w/ chpldoc
- Add a vectorization primer for vectorizeOnly and implicit vectorization of
  data parallel operations
- Create a better story for preventing zippering

This work is broken up into 3 logical commits (each commit message has more
info and code detail):
 - Add isRefIterType() to identify ref iterators for the purpose of determining
   the ref-ness of the wrapper iterator based on what it is wrapping.
 - Add ability to explicitly mark iterators as vectorizable to provide a way to
   vectorize the serial vectorizeOnly wrapper.
 - Add the vectorizeOnly iterator.

### CODE REVIEW

**Comment by ronawho** [comment]
@vasslitvinov and @daviditen could you review?

The PR is broken up into 3 logical commits and it's probably easiest to review each commit individually

**Comment by ronawho** [comment]
I'm also curious if you have ideas on how to prevent an iterator from being zippered and if you have any ideas on how to make writing "wrapper" iterators easier without having to write a ref, val, and tuple version for each iterKind

**Comment by bradcray** [comment]
Yay!

Regarding the question about preventing an iterator from being zippered:  Recall that one proposed aspect of leader-follower 2.0 is to add the capability to define leader-follower iterators for the serial zippered case rather than using the current implementation (the reasons for this are symmetry with the parallel case and to permit user-defined types to be "infinite" and thereby serve as followers to finite things, much like unbounded ranges are -- though as a special case in the compiler -- today).  In such a world, it seems like you could add the warning/error to both the serial and parallel leaders.

Some of the wording of the commit message seems odd to me.  For example:

* "or serialize parallel iterators. It takes one or more iterable as arguments and simply invokes a for loop over its arguments." -- the mention of "serialize parallel iterators" seems overly simplistic to me.  It isn't serializing them necessarily (executing one iteration at a time), it's merely squashing task parallelism.  Right?  Similarly "simply invokes a for loop" seems to oversimplify that it signals back-end vectorization in the same way as the --vectorize flag.  The description in paragraph 3 seems clearer.

* "When invoked from a serial for loop, this iterator will simply mark users'
iterator(s) as order independent." This paragraph and the code that follows it seems similarly confusing to me.  If the first sentence tied into the --vectorize flag, that seems like it would help.

* "will both effectively become: for i in 1..10 do; // where the for loop is order independent" -- here, since for loops are not order independent, I think that writing it as Chapel code (rather than, say, the generated C code) is confusing since the concept can't be expressed as Chapel code.

In terms of taste, my intuition would be:

* to not support the for + vecIter() form -- to me it seems confusing to have a serial iterator that can lead to out-of-order execution or that implies order independence.  But perhaps you came up with a rationale that isn't apparent to me.

* I'd probably simply name this 'vectorize()' because it seems more readable and easier to remember than 'vecIter()' (and I don't see any strong potential for naming conflicts).  But since I've been out of the office, maybe I missed a discussion on this.

Again, yay!

**Comment by ronawho** [comment]
>Regarding the question about preventing an iterator from being zippered: Recall
>that one proposed aspect of leader-follower 2.0 is to add the capability to
>define leader-follower iterators for the serial zippered case rather than using
>the current implementation (the reasons for this are symmetry with the parallel
>case and to permit user-defined types to be "infinite" and thereby serve as
>followers to finite things, much like unbounded ranges are -- though as a
>special case in the compiler -- today). In such a world, it seems like you
>could add the warning/error to both the serial and parallel leaders.

Does this mean that you think it's not worthwhile to explore a way to prevent
zippering now? I hacked something together that complains for zippering serial
iterators by using a pragma on the iterator. I don't how much more it would
take to get it working for parallel iterators as well, but if you don't think
it's worth exploring until l/f 2.0, I can drop this.

>Some of the wording of the commit message seems odd to me. For example:

>"or serialize parallel iterators. It takes one or more iterable as arguments
>and simply invokes a for loop over its arguments." -- the mention of "serialize
>parallel iterators" seems overly simplistic to me. It isn't serializing them
>necessarily (executing one iteration at a time), it's merely squashing task
>parallelism. Right? Similarly "simply invokes a for loop" seems to oversimplify
>that it signals back-end vectorization in the same way as the --vectorize flag.
>The description in paragraph 3 seems clearer.

Yeah, you're right. Serialize is overly simplistic and misleading since it's
really squashing task parallelism rather than serializing.

>"When invoked from a serial for loop, this iterator will simply mark users'
>iterator(s) as order independent." This paragraph and the code that follows it
>seems similarly confusing to me. If the first sentence tied into the
>--vectorize flag, that seems like it would help.

>"will both effectively become: for i in 1..10 do; // where the for loop is
>order independent" -- here, since for loops are not order independent, I think
>that writing it as Chapel code (rather than, say, the generated C code) is
>confusing since the concept can't be expressed as Chapel code.

>In terms of taste, my intuition would be:

>to not support the for + vecIter() form -- to me it seems confusing to have a
>serial iterator that can lead to out-of-order execution or that implies order
>independence. But perhaps you came up with a rationale that isn't apparent to
>me.

I'm ok dropping this if you feel strongly about it, but I think it's really
confusing to have a "vectorize" iterator that doesn't do anything when invoked
from a "for" loop. To me it seems that by using this iterator a user is
explicitly saying their iterator is order independent and can be vectorized so
why wouldn't we? That said, I might feel less strongly about this if we could
issue a `compileWarning` for the serial case.

>I'd probably simply name this 'vectorize()' because it seems more readable and
>easier to remember than 'vecIter()' (and I don't see any strong potential for
>naming conflicts). But since I've been out of the office, maybe I missed a
>discussion on this.

I'm fine changing the name, but I'm not sure I think "vectorize" is much
better. Especially if we get rid of the "for+vecIter()" form, then it's really
just a task squashing iterator. i.e. the vectorization comes from the forall
loop and has nothing to do with the iterator then. I think I started out with
vecOnlyIter but thought that was too long. I think I prefer "vectorize" to
"vecIter" but I'd really like something that conveys task squashing, but I
can't think of a concise name for that.

I'll take a look through the PR and source comments to remove "serialize" and
try to better express the intent.

**Comment by bradcray** [comment]
> Does this mean that you think it's not worthwhile to explore a way to prevent
> zippering now? I hacked something together that complains for zippering serial
> iterators by using a pragma on the iterator. I don't how much more it would
> take to get it working for parallel iterators as well, but if you don't think
> it's worth exploring until l/f 2.0, I can drop this.

I wasn't suggesting doing any additional work in this regard at present.  Just offering up a potential longer-term solution for the question you asked (if I understood it properly).

> I'm ok dropping this if you feel strongly about it, but I think it's really
> confusing to have a "vectorize" iterator that doesn't do anything when invoked
> from a "for" loop. To me it seems that by using this iterator a user is
> explicitly saying their iterator is order independent and can be vectorized so
> why wouldn't we? That said, I might feel less strongly about this if we could
> issue a `compileWarning` for the serial case.

Maybe this is me being forgetful.  In thinking about what my ideal case would be it would be to have the serial case issue a compilerWarning() saying something like "The preferred Chapel style for vecIter() is to use a forall loop" (and maybe a config param to squash this warning).  But is the issue that we can't put a compilerWarning() there because we resolve the serial iterator in resolving parallel iterators as well?

> I'm fine changing the name, but I'm not sure I think "vectorize" is much
> better. Especially if we get rid of the "for+vecIter()" form, then it's really
> just a task squashing iterator. i.e. the vectorization comes from the forall  
> loop and has nothing to do with the iterator then. I think I started out with
> vecOnlyIter but thought that was too long. I think I prefer "vectorize" to
> "vecIter" but I'd really like something that conveys task squashing, but I
> can't think of a concise name for that.

That's an interesting point (that the vectorization is coming from the forall nature rather than the iterator's definition) which was lost on me.  

Given that, I agree that a more accurate description of what the iterator is doing would be something like 'noNewTasks()' or 'singleTaskOnly()' or 'noTaskPar()'.  Note that if we went with one of these names, then the serial case should definitely become a no-op, I think rather than implying order independence.

From a readability standpoint, my intuition was that seeing something like 'forall i in vectorize(1..n)' seems more self-descriptive than 'forall i in noNewTasks(1..n)'.  But, on the other hand, it might also suggest to a newbie that if I don't use the vectorize() iterator, I won't get vectorization...  and it'd be a shame if people wrote the vectorize form of the loop above if n was large...  So that suggests to me that maybe both 'vectorize' and 'vecIter' are similarly misleading and that something like 'vectorizeOnly' or 'vecOnly' would be better names.  And I think I'd rather see loops like 'forall i in vectorizeOnly(1..8)' than 'forall i in noTaskPar(1..8)'?

Assuming that we're only debating names here, maybe the thing to do is to commit what you've got and then wrestle with the naming in the larger group?

**Comment by ronawho** [comment]
>> Does this mean that you think it's not worthwhile to explore a way to prevent
>> zippering now? I hacked something together that complains for zippering
>> serial iterators by using a pragma on the iterator. I don't how much more it
>> would take to get it working for parallel iterators as well, but if you don't
>> think it's worth exploring until l/f 2.0, I can drop this.
>
>I wasn't suggesting doing any additional work in this regard at present.  Just
>offering up a potential longer-term solution for the question you asked (if I
>understood it properly).

Ah ok, let me re-phrase then. I was originally wondering if vass/david had
ideas on how to prevent zippering. After asking, I took a quick look at what it
would take to implement such a check and currently I have it working for serial
iterators but not parallel iterators. I'm wondering if you think it's
worthwhile to take another couple hours and see if I can get it working for the
parallel iterator case too or if I should wait for l/f 2.0 and just leave a
comment in the source code for now. Left to my own devices I would continue to
implement this if I think I could do it in under a day, but am happy to give up
on that if you don't think it's worthwhile.


>> I'm ok dropping this if you feel strongly about it, but I think it's really
>> confusing to have a "vectorize" iterator that doesn't do anything when
>> invoked from a "for" loop. To me it seems that by using this iterator a user
>> is explicitly saying their iterator is order independent and can be
>> vectorized so why wouldn't we? That said, I might feel less strongly about
>> this if we could issue a `compileWarning` for the serial case.
>
>Maybe this is me being forgetful.  In thinking about what my ideal case would
>be it would be to have the serial case issue a compilerWarning() saying
>something like "The preferred Chapel style for vecIter() is to use a forall
>loop" (and maybe a config param to squash this warning).  But is the issue that
>we can't put a compilerWarning() there because we resolve the serial iterator
>in resolving parallel iterators as well?

Yeah, I agree that would probably be ideal and you're correct that the reason
we don't do that now is because we always resolve the serial case.

Note that this patch currently relies on the implication that all parallel
iterators have a serial versions so if we stopped always resolving the serial
case, we'd need to have some other way to check that a serial version was
available.

>> I'm fine changing the name, but I'm not sure I think "vectorize" is much
>> better. Especially if we get rid of the "for+vecIter()" form, then it's
>> really just a task squashing iterator. i.e. the vectorization comes from the
>> forall  loop and has nothing to do with the iterator then. I think I started
>> out with vecOnlyIter but thought that was too long. I think I prefer
>> "vectorize" to "vecIter" but I'd really like something that conveys task
>> squashing, but I can't think of a concise name for that.
>
>That's an interesting point (that the vectorization is coming from the forall
>nature rather than the iterator's definition) which was lost on me.
>
>Given that, I agree that a more accurate description of what the iterator is
>doing would be something like 'noNewTasks()' or 'singleTaskOnly()' or
>'noTaskPar()'.  Note that if we went with one of these names, then the serial
>case should definitely become a no-op, I think rather than implying order
>independence.

Yeah, I 100% agree if we change the name to something like this the serial
case should be a no-op. If we use something like "vectorize" it seems like it
should vectorize the serial case. I'm not sure what "vectorizeOnly" would
imply. I guess that the serial case would be a no-op.

>From a readability standpoint, my intuition was that seeing something like
>'forall i in vectorize(1..n)' seems more self-descriptive than 'forall i in
>noNewTasks(1..n)'.  But, on the other hand, it might also suggest to a newbie
>that if I don't use the vectorize() iterator, I won't get vectorization...  and
>it'd be a shame if people wrote the vectorize form of the loop above if n was
>large...  So that suggests to me that maybe both 'vectorize' and 'vecIter' are
>similarly misleading and that something like 'vectorizeOnly' or 'vecOnly' would
>be better names.  And I think I'd rather see loops like 'forall i in
>vectorizeOnly(1..8)' than 'forall i in noTaskPar(1..8)'?

Yeah, I had the same concern about what "vectorize" would imply to newbies but
agree that it feels better than noTaskPar or something. I like vectorizeOnly or
vecOnly. Not sure if I have a preference.

>Assuming that we're only debating names here, maybe the thing to do is to
>commit what you've got and then wrestle with the naming in the larger group?

Ok, sounds good to me. While writing this patch I also realized there should
probably a primer about vectorization. Mike also made an off-hand comment today
about when I'm going to demo our vectorization capabilities so I agree it's
good to get buy in and more exposure.

**Comment by bradcray** [comment]
> ...I took a quick look at what it
> would take to implement such a check and currently I have it working for serial
> iterators but not parallel iterators. I'm wondering if you think it's
> worthwhile to take another couple hours and see if I can get it working for the
> parallel iterator case too or if I should wait for l/f 2.0 and just leave a
> comment in the source code for now. Left to my own devices I would continue to
> implement this if I think I could do it in under a day, but am happy to give up
> on that if you don't think it's worthwhile.

I could go either way.  I'd be OK with this going out with the warning that if used in a zippered context, the wheels may fall off the car.  I view the "serial leader-follower work" as the converse of the "standalone parallel iterator work" that @daviditen did recently, and am curious, given his familiarity with that section of the code, what level of effort he thinks it would take to implement it.  I think it could be a nice next step for LF 2.0.  If your pragma-based solution is easy to get working, though, I wouldn't have a problem with that going in, either with this PR, or as a separate clean-up.

Sounds like we're in synch on naming and implications for the serial case.  I like vectorizeOnly() at present.  My ideal solution would still be to generate a warning in the serial case, but since we can't do that (yet), I'm fine with having it simply vectorize.  Maybe that's another question for @daviditen or @vasslitvinov: Do either of you know what the level of effort would be to have the resolution of parallel iterations not rely on the serial iterator to determine the yielded type?  It feels like a crutch, and undesirable (in that I think one would like to be able to write a parallel iterator that had no serial counterpart).

**Comment by vasslitvinov** [comment]
Regarding the level of effort to not depend on serial iterators: I propose we do that within Mike's upcoming reimplementation of IR+resolution. Either way I expect this to be on the order of a couple of engineer-weeks.

**Pull request merged**
