### PR TITLE
Necessary normalize change to .init calls

### PR DESCRIPTION
**Pull request by lydia-duncan**
Constructors and initializers are different from other methods - they don't take
in the _mt token.  Normally we don't have calls to instance.constructor(),
so normalize's applyGetterTransform doesn't cause problems, but with the new
initializer story we rely on the presence of this.init() and super.init() calls.
Additionally, initializers now take in their memory to initialize as the final
"meme" argument (to help distinguish between inits of records which have similar
field set up), and ordinary method calls have the instance of the type to
operate on in the first argument.  Thus two adjustments need to occur (and could
occur at the same time): 1) .init() calls should not be given the _mt actual
and 2) the first actual should be made into an actual for "meme".

With this minor modification, three of my futures now pass, and many more of
them are now only encountering problems with super.init() calls when super ==
object.  Retire the .future files on the passing tests.

- [x] std testing

### CODE REVIEW

**Comment by vasslitvinov** [comment]
Maybe we should rename the 'meme' to 'chpl_this', if it is still there. Otherwise we have room for latent name-conflict/confusion issues.

**Comment by lydia-duncan** [comment]
There's already a "this" argument though, so I think that would breed more confusion as to why they have been separated.

**Comment by vasslitvinov** [comment]
Then why do you also pass 'meme' ?

**Comment by lydia-duncan** [comment]
They don't exist in the same argument list.  "This" is always used for methods, while "meme" is only used for constructors.  We have to use something other than the normal "this" for constructors because checkNormalized looks for any access of "this" in the argument list to ensure that we don't try to access a field before it has been initialized

**Comment by vasslitvinov** [comment]
While there, could you make sense of the comment:

  // Note:
  //   call(call or )( indicates partial

right above your changes, and either delete it or clarify?

**Comment by vasslitvinov** [comment]
OK, then rename 'meme' to 'chpl_meme'. Or, really, to any name that is guaranteed not to conflict with a user name.

**Comment by lydia-duncan** [comment]
Yeah, I don't understand what that means.  My guess is that it refers to the code on lines 909-912 which seems to be unrelated to what I'm working on.

May I ignore your request?  I feel like there's enough other code I'm having to juggle and understand in my head right now just to actually implement this feature :(

**Comment by vasslitvinov** [comment]
Let's leave alone the "partial" comment, then. We'd need to look at 9ad79ca4 (in 2006) to make sense of it.

**Comment by lydia-duncan** [comment]
Oh yikes, that's a long time ago.

For those following along, Vass clarified offline that he meant for the "meme" renaming to be a general desire rather than one that should be addressed in the current PR.  I'll get back to it as I wrap up the initializers work, but since that's a ways off, I'll make a note for myself for now.

**Pull request merged**
