### PR TITLE
 Replace the secrets with environment secrets

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
Added git-hub Environments secrets and updated the workflow to use the environments secrets instead of actions secret.

### CODE REVIEW

**Comment by riftEmber** [comment]
What's the reason for using these secrets instead?

**Comment by bhavanijayakumaran** [comment]
> What's the reason for using these secrets instead?

Git hub action to retrieve secrets follow this hierarchy Environment -> Repository ->Organization
So tried with Environment secret.

I am still puzzled how both Env and Repo secrets added to my forked repository works fine on the workflow runs but the secret values are null for main repository.

**Comment by bhavanijayakumaran** [comment]
> > What's the reason for using these secrets instead?
> 
> Git hub action to retrieve secrets follow this hierarchy Environment -> Repository ->Organization So tried with Environment secret.
> 
> I am still puzzled how both Env and Repo secrets added to my forked repository works fine on the workflow runs but the secret values are null for main repository.

Since forked repository does not have access to secrets in main repository I created the same set of secrets in forked repository.

**Comment by bhavanijayakumaran** [comment]
After looking further looks like the workflow that runs on Merge from fork to main does not have access to secrets in main(and does not use the secrets defined in fork)

From a thread
when you are opening pull requests IN the forked repo, then action will not get secrets, but actually when you are opening PR FROM the forked repo to the main one, actions still won't have access to them

**Comment by bhavanijayakumaran** [comment]
Found this work around. Going to try this:
Improvements for public repository forks


In order to solve this, we’ve added a new pull_request_target event, which behaves in an almost identical way to the pull_request event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request.

**Pull request closed without merging**
