### PR TITLE
Sparse Matrix-vector multiplication

### PR DESCRIPTION
**Pull request by wongalvis14**
Adding sparse matrix-vector dot product, it supports distributed arrays as well

### CODE REVIEW

**Comment by wongalvis14** [comment]
Also `_csrmatvecMult` does not support distributed arrays as `dimIter` does not work on distributed CSR, maybe we can call `_sparsematvecMult(A,B)` for distributed CSR as well? Though it may not get optimal performance tailored for CSR

**Comment by e-kayrakli** [comment]
Before going into the details of the implementation, I am not sure whether that supports common distributed arrays. I can see that this can produce correct results if the sparse matrix is row-wise distributed (in that case I don't see the need for the `rowResults` temporary)

But what if the array is 2D block-decomposed, which is the default and common case. I think there is logic and synchronization issues. Assume a 4-locale distribution of the matrix. LOCALE1's `rowResult` will have domain 0..N/2-1, however, the values computed by LOCALE1 should go to the latter half of the resulting vector (N/2..N-1 or something). Am I missing something?

Even with that fixed multiple locales can try to write to same indices of Y simultaneously, causing a race condition. Is that right?

@wongalvis14 -- could you clarify these?

**Comment by wongalvis14** [comment]
@e-kayrakli I've tested with mostly block sparse matrices, the values in rowResult [0..N/2-1] should go into Y[0..N/2-1]

In fact yes, there could be a race condition, I can either put a lock around that statement or move the for-loop out of the coforall in locales

**Comment by e-kayrakli** [comment]
I don't know what I was thinking, the logic is fine.

But the race condition is obvious. Both of your suggestions should make it race-free but very unscalable. I think that would be a good first step to establish correctness, but for performance reasons I think we should do better than that (not necessariliy perfect).

One thing that you can is to reduce the synchronization. You can use `A.domain.dist.targetLocales()` to get an idea of how the 2D array is distributed across locales. For example for an 8 locale setup the array will be distributed like:
```
L0 L1
L2 L3
L4 L5
L6 L7
```

Now, L0 and L1 share the row and causing the race condition that we currently have. So what we can do is to write a loop of length 2 (for L0 and L1) where in the first iteration L0 commits the first half of its results to the vector and L1 commits the second half. In the second iteration it is going to be vice versa. Between iterations all locales synchronize (ideally only those in the same rows should synchronize) I believe this way all the locales do some work simultaneously and do not synchronize too much.

Note that I may be overcomplicating things and there may be easier solutions. But  this was one of the things that I could think of. Feel free to propose anything else that you feel might be better for some reason.

**Comment by e-kayrakli** [comment]
To elaborate more on the suggestion above:

(Assume divisibility for the sake of clarity)

- First you need to determine the number of rows per synchronization. That is how many rows a locale can update before needing synchronization. That one is easy: 
```
var numRowsPerSynch = A.domain.dim(1)/A.domain.dist.targetLocales().size
``` 
(number of rows divided by number of locales that this array is distributed across)

- Then create a lock array for locking those row blocks. 

```
var locks$: [A.domain.dim(1) by numRowsPerSynch] sync bool
```

I used a strided range as the domain of the array, so that the first index of the row block can be used to index into the locks array for simplicity

- Figure out how many locales are neighbors within a row of the distribution:

```
var numLocsInRow = A.domain.dist.targetLocales().domain.dim(2)
```

- Each locale computes where they are in this neighborhood. For example L5 in the above example is the second locale in that row:

```
var myPosInRow = A.domain.dim(2).size/(A.localSubdomain().dim(2).high+1)-1  //zero-based
```

- Then, the operation:

```
for iter in 0..#numLocsInRow {
   //calculate start offset
  var curStart = (low_i+((myPosInRow+iter)*numRowsPerSynch))%A.localSubdomain().dim(1).size;
  var curEnd = curStart+numRowsPerSynch-1;
  locks$[curStart] = true;
  for curStart..curEnd do  //stuff
  locks$[curStart];
}
```

Another option is to use the AllLocalesBarrier and make all the locales synchronize between row blocks. It is not ideal, however, all of them will probably have similar amount of work to do, so there won't be too much idling. See https://chapel-lang.org/docs/modules/packages/AllLocalesBarriers.html

One drawback of this option is that if the user created an array that doesn't distribute the data to all locales but instead only a subset, then you'd be synchronizing locales that don't have anything to do with the array data.

**Comment by e-kayrakli** [comment]
We have decided to shelve this PR for now in an offline discussion. Closing

**Pull request closed without merging**
