### PR TITLE
Add a future to track the type of iterable expressions in multiple contexts

### PR DESCRIPTION
**Pull request by lydia-duncan**
I rediscovered that the type of an iterable expression is different when it is
saved into a local variable versus when it is passed as an argument to a
function.  This future tracks that difference, and poses the question of
whether the types should match and what it should be if they do.

This issue is tracked in #6330

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@bradcray - I changed the code you gave me so that the .bad file wouldn't rely on the "_ir__iterator_for_loopexpr3" output, which seemed like something that could change depending on compiler AST reshuffling.  I verified that `==` would give me the right thing for strings.  Thoughts?

**Comment by bradcray** [comment]
Looks OK to me.

**Comment by bradcray** [comment]
(BTW, to the question raised in the future, I strongly believe we should not expand iterators into arrays upon passing them into functions... I believe that doing so would cause the compiler to insert array temps in places where we wouldn't want them.  So that would suggest either permitting variable declarations to capture iterator expressions or having the cases continue to behave differently).

**Comment by bradcray** [comment]
(Oh, also, I don't think you "discovered" this -- we implemented the language this way very intentionally.  :)  ).

**Comment by lydia-duncan** [comment]
So I am Christopher Columbus?

**Comment by bradcray** [comment]
Hopefully less controversial than him...

**Pull request merged**
