### PR TITLE
Re-enable hpl.hpcc2012 testing

### PR DESCRIPTION
**Pull request by bradcray**
It seems that the fixes to the align operator fixed this test?  Re-enable
it to regain gasnet testing and performance testing.  If it continues to
generate thrash in the future, this PR could be reversed, or we could
decide to take it off life support.  I'm curious whether it will go back
to being as stable as it was before, though.

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho, want to be my friend?

**Comment by ronawho** [comment]
looks good to me

**Comment by bradcray** [comment]
I didn't see that you'd reviewed this last night, and am scared to merge it today since I'll be flying tomorrow.  :S

**Comment by ronawho** [comment]
I can check in if you want to try to merge this sooner rather than later, but I also don't mind just waiting a few days

**Comment by bradcray** [comment]
I think I'll merge now just to keep my number of open PRs low (and since next week won't be much better), and will try to take a look tomorrow before heading to the airport.  But thanks for any back-up.

**Pull request merged**
