### PR TITLE
Add generated code guide and make check for the plugin

### PR DESCRIPTION
**Pull request by Aniket21mathur**
@lydia-duncan @mppf please have a look!

### CODE REVIEW

**Comment by mppf** [comment]
The Makefile changes look good to me but I'd like to wait until Monday to merge them. The location of the generated code guide looks good and I believe it was already reviewed by @lydia-duncan in https://github.com/Aniket21mathur/Chapel-protobuf/pull/30 .

**Comment by Aniket21mathur** [comment]
Yes, @lydia-duncan reviewed the code guide.

Can you please add the GSoC protobuf label to the pr?

**Comment by Aniket21mathur** [comment]
I have updated the guide in 336c30c.

**Comment by Aniket21mathur** [comment]
@mppf updated this pr as well!

**Pull request merged**
