### PR TITLE
Fixed Issue #17513

### LINKED ISSUE #17513: _lu() assumes that the domain for the array it is provided will also be zero based
### Summary of Problem

The _lu() helper function by default assumes all the arrays provided to it are 0 based.

### Steps to Reproduce

**Source Code:**

```chapel
use LinearAlgebra;
var dom = {1..2,1..2};
var arr : [dom] real = 1;
var x = lu(arr);
writeln(x(0));
```
since here indices of ```arr``` is 1 based and not 0, it gives a run-time error ```index out of bounds```

### PR DESCRIPTION
**Pull request by vrockz747**
Fixes #17513
_lu() now returns the result, irrespective of whether the index of the given array is 0-based or 1-based.
The solution can be extended for any indexed array, but since there is highly unlikely for the array to be indexed other than 1 or 0, 
that part is omitted.

### CODE REVIEW

**Comment by vrockz747** [comment]
Please review this PR @bradcray

**Comment by bradcray** [comment]
@vrockz747 : I'm a little short on time at the moment and not particularly familiar with this code.  Tagging @ben-albrecht and @e-kayrakli who have done some work around here in the past it looks like to see whether one of them has time.

**Comment by CaptainSharf** [comment]
Hi @vrockz747 , @bradcray ,
Since the issue of ambiguity in 0-based and 1-based indexing (including strided and negatively strided domais) persists throughout the LA module, maybe we ought to look for a general solution to this problem instead of fixing it for a specific procedure?

There's some other problems with the native `lu` implementation which I think are worth looking into, including unstable factoring  and zero pivoting. Since other procedures like `solve` depend on the `lu` factoring, it becomes essential to have a correct native implementation for the `lu` factoring.

Let me know what you think!

**Comment by vrockz747** [comment]
Hey @CaptainSharf, I quite don't know about all the problems associated with ```lu``` implementation in LA-module, I just came across the index one, so I gave the bug some time.
Are we having a merge conflict here? if so, how do you say we work it out?
Tagging @ben-albrecht and @e-kayrakli for suggestions.

**Comment by CaptainSharf** [comment]
Hi @vrockz747 ,
Thanks for your effort! I merely wanted to suggest that apart from the issue you identified there are a few other problems with the native LU. Also that we might want to come up with a generic solution to the problem you identified regarding indexing. Please feel free to reach out to me in the gitter channel!

**Comment by damianmoz** [comment]
@vrockz747 mentioned
>_lu() now returns the result, irrespective of whether the index of the given array is 0-based or 1-based. The solution can be extended for any indexed array, but since there is highly unlikely for the array to be indexed other than 1 or 0, that part is omitted.

I see from the patch, that you changed **lu()** rather than **_lu()** where you correctly noted that the original problem exists.

If I can suggest, any change really needs to use base-neutral indexing. This approach can not only handle  0-based nor 1-based but you get the extension to any consistent base for free. With **solve_tril()** also suffering from only allowing 0-based indexing in 1.24.0, its replacement could be
```chapel
// Solve  l*y = b using factor 'l' computed by luDecompose where 'b'
// must have been reordered according to the partial pivoting strategy
// Base-neutral but consistent indexing is assumed. 'l' is stored in
// the lower triangle of 'a' and normally has implicit diagonals = 1.0
// (this really belongs in BLARIC but it will have to wait for now)

inline proc luSolveLower(a : [?aD] ?R, b : [?bD] R, unitDiagonal = true)
{
    const (_, columns) = aD.dims();
    const (rows, ) = bD.dims();
    var error = laError.None;

    if columns != rows || rows.stride != 1 then
    {
        error = laError.RangeFlaw;
    }
    else
    {
        const last = rows.last;
        const allButLastRow = rows.first .. last - 1;

        for k in allButLastRow do // forward elimination
        {
            const rowsBelow = k + 1 .. last;
            const t = if unitDiagonal then b[k] else b[k] / a[k, k]; 

            b[rowsBelow] += t * a[rowsBelow, k]; // vectorize this!
        }
    }
    return error;
}
```
This is less lines of code than an base neutral **_lu()**, but still shows the base-neutral approach to indexing. Note that the above is limited to having 'b' as a 1D-array  It also assumes the definition of
```chapel
enum laError
{
    ZeroData,   // a zero occurred where it may/will cause problems
    TinyData,   // a tiny number occurred where it should not have
    HugeData,   // a huge number occurred where it should not have
    LogicFlaw,  // internal logic (often convergence) failure
    RangeFlaw,  // a mismatrch was seen with/in an input dimension range
    InputFlaw,  // a problem was seen with/in the input data
    OtherFlaw,  // any other error condition, i.e. miscellaneous ones
    None        // NO error exists
};
```
You can ignore those BLARIC comments for now.

Base-neutral indexing is a more general solution. You can extend the approach seen at the start of the above routine to the LU decomposition routine **_lu()**. The luDecompose() mentioned in those comments can be wrapped in its 10-line own version of **_lu()**  needs a bit more testing before I release it into the wild. Where are there guidelines on how to do Unit Test routines for Chapel library routines?

And as @CaptainSharf mentions, this general approach really needs to be done throughout the whole LinearAlgebra module. Before embarking on the task of reprogramming routines as base-neutral, the list of affected routinesl needs to be ascertained. A piecemeal approach does not give you the bigger picture which you really need for something like this.

I do assume a unit-stride and avoid negatively strode domains as I think that a routine that needs either of those features does not belong in a general Linear Algebra library. Others may have quite different opinions. I find that trying to cater for those unusual features adds unnecessary complexity and will probably cause lots of nasty cache misses.

In line with the more general approach advocated by @CaptainSharf,  extending LU decomposition to handle non-square matrices is probably a useful option. LAPACK has done this for the last 20+ years. It also simplifies some of the base-neutral code. It is then a small extra step to further extend indexing to handle a sub-matrix of a much larger matrix, a situation that occurs in the blocked LU decomposition. But I do not have a current Chapel implementation of either of those so I am relying on memory as to the level of complexity and I could be wrong. Also, there is a need to consider the question of whether you allow argument to a given routine to have inconsistent bases? I would suggest not because it complicates the error checking badly and the main body of the code slightly. That said, I would highly recommend it for more basic routines such as a matrix multiplication and cross products and maybe even a Kronecker product at a stretch..

On the LU decomposition, @CaptainSharf mentions that there are several other aspects that need investigation. Zero-pivoting can be easily handled today by a return notification variable or a thrown exception (an alternative that I advise against). But if Chapel wants to persist with the existing interface, I think that the latter is the only practical solution (but I could be wrong). Unstable factoring can be better handled by Scaled Partial Pivoting although I note that even the latest LAPACK still sticks with conventional Partial Pivoting. I think that this feature is more like an enhancement but some people swear by the scaled variant.

My above solution is a bit slow. Instead of
```chapel
b[rowsBelow] += t * a[rowsBelow, k]
```
one can use an unrolled **for** loop which would be encapsulated in its own routine in an ideal world. The above code of mine is written assuming that Chapel vectorisation is just around the corner.

**Comment by CaptainSharf** [comment]
Hi @damianmoz ,
Thanks for your detailed analysis regarding the details of this problem as well as possible solutions to resolve it! I had raised this PR #16979, which introduces the LAPACK version of `LU` factorization which might address 2 of the problems we face right now (LU for square and rectangular matrices and zero pivoting). It'd be helpful if you could please let me know your thought on that.

Thanks

**Comment by damianmoz** [comment]
Non-native Chapel is nowhere on my radar so please excuse me for not considering your modifications which rely on LAPACK.

The following provides most of what is needed to provide base-neutral indexing within **_lu()**. It addresses the issue of a zero pivot. But it needs tweaking because it stores the LAPACK pivot strategy in the pivot vector (which is in-place friendly but not what**_lu()** needs as it is currently written). It also needs modification to handle a non-square 2D array but that is an enhancement to **_lu()** and can wait. This routine only handles arrays with unit-stride because I have never seen the need for handling a non unit-stride (or negative stride) in a standard library but maybe my experience is too limited. It avoids cache hostile operations on columns of a row-major Chapel array. I have included it inline because anything else in too hard to read and quote. It uses the _laError_ **enum** quoted earlier.

I hope I get this cut and paste right. If I get it wrong, I can edit it again.
```chapel
// Return an error state (and any relevant row) in the function value

proc luDecompose(a : [?aD] ?Real, p : [?pD] ?Int)
{
    param zero = 0:Real;
    const (aRows, aColumns) = aD.dims();
    const (pRows, ) = pD.dims();
    const first = pRows.first, last = pRows.last;
    const columns = first .. last;
    var error = laError.None, issue = (first - 1):Int;

    if pRows != columns || aRows != columns || aColumns != columns then
    {
        error = laError.RangeFlaw;
    }
    else for c in columns do
    {
        // Elements of this column from the diagonal down are partial
        // pivot candidates. Select the largest of these as the pivot
        // and remember the row number for subsequent permutations

        var ppc = a[c .., c];
        const (_, r) = maxloc reduce zip(abs(ppc), c ..);
        const pivot = ppc[r];

        if pivot != zero then // matrix will likely not be singular
        {
            if c != r then // swap the rows and mirror the same in the copy
            {
                a[r, ..] <=> a[c, ..]; ppc[r] <=> ppc[c];
            }
            if c < last then // update parts of 'l', 'u' and 'a'
            {
                // define the post-Diagonal range of the Pivoting Row and
                // the post-Diagonal range of the Pivoting Column as well as
                // references to the slices of 'a' that those ranges imply.
                // Note that a copy of the post-Diagonal Pivoting Column
                // already exists within the 'ppc' array.

                const rowsBelow = c + 1 .. last, columnsAfter = c + 1 .. last;
                ref _ppr = a[c, columnsAfter], _ppc = ppc[rowsBelow];

                // Scaling 'ppc' produces the c'th column of factor L (which
                // then needs to be copied back inside the matrix 'a')

                vmDiv(_ppc, -pivot); a[rowsBelow, c] = _ppc;

                // update the trailing sub-matrix of 'a' by adding to it the
                // outer product of those post-Diagonal column and row slices

                vmAug(a[rowsBelow, columnsAfter], _ppc, _ppr);

                // a[c, columnsAfter] is now implicitly the reduced 'u'
            }
        }
        else if error == laError.None then // save the offending column
        {
            error = laError.ZeroData;
            issue = r:Int;
        }
        p[c] = r:Int; // remember the pivot index
    }
    return (error, issue);
}
```
Two potentially vectorizable operations are pulled from the decomposition and shown in the next few lines. These are base-neutral but rigorously domain consistent. They are simplifications of routines from another library.
```chapel
// Accumulate Outer Product of two vectors with a matrix

inline proc vmAug(ref z : [?zD] ?R, const ref x : [] R, const ref y : [] R)
{
    [(r, c) in zD] z[r, c] += x[r] * y[c];
}

// Scale a vector

inline proc vmDiv(ref x : [?xD] ?R, const t : R)
{
    x /= t;
}
```
If this approach is felt worth pursuing for LinearAlgebra, I can post the routines **luPermute()** and **luSolveUpper()** which allows you replace the insides of **lu()**, **solve()**, **solve_tril()** and **solve_triu()** so that they handle base-neutral (but consistent) indexing. Note that **luPermute()** uses the LAPACK pivot strategy so will need tweaking. If I get some guidance on how to construct unit tests in a standard manner, I can provide my unit tests too.

I have solutions to the non-square matrix issue but am time-constrained at the moment to document it properly so that will have to wait.

**Pull request closed without merging**
