### PR TITLE
An initial attempt to build an MPI module

### PR DESCRIPTION
**Pull request by npadmana**
@bradcray -- as discussed, here is a pull request for an initial version of an MPI module. It's currently flagged as a NOTEST...

Some comments --
1. Assumes that CHPL_TARGET_COMPILER=mpi (which requires rebuilding Chapel). I found a number of warnings during this build, which I could squash with CHPL_TARGET_ARCH=none.
2. This is meant to be complete MPI-1. There are a few missing routines -- these all involve passing C handlers (and function pointers).
3. The examples are from the LLNL MPI tutorial. One of these builds a user-defined type using routines that are now deprecated, so the test produces a number of deprecation warnings. We probably should fix these.
4. I started to document the module, but there are a bunch of typesetting issues that I haven't had a chance to track down.

### CODE REVIEW

**Comment by mppf** [comment]
Hi @npadmana - I havn't looked at this in great detail but I have some initial feedback.
 * CHPL_TARGET_COMPILER=mpi seems like maybe not a great name, since in practice you're patch is assuming it's GCC. What if we made it CHPL_TARGET_COMPILER=mpi-gcc or something like that? (mpi-gnu would also be fine with me)
 * It looks like you copied the Makefile.gnu into Makefile.mpi. In this case, I think it would be better to include Makefile.gnu. See Makefile.cray-prgenv-gnu for an example.
 * While I'm OK with adding a CHPL_TARGET_COMPILER=mpi-gcc, I don't think it's always necessary for using MPI and in fact I would generally prefer other methods of finding the relevant MPI headers and libraries. In particular, when GASNet is configured with MPI, the Chapel program should already link with the relevant libraries at least. Then the only question is how to find the MPI headers and we might be able to use CPATH/C_INCLUDE_PATH or assume they are in a standard place like /usr/include.
 * If you're adding MPI bindings, you presumably think it's useful to sometimes use explicit communication in a Chapel program. I'd be interested in discussing further other ways to do that. In particular, a more 1-sided strategy (GET/PUT) might be simpler and also be easy to implement with the existing Chapel runtime. How much of your needs met by MPI could be met by explicit GET and PUT? What if we had OpenSHMEM bindings for example? I think it's great to give Chapel programmers options, but I'd expect a 1-sided strategy to fit in better with the language.

**Comment by bradcray** [comment]
Michael, I agree with some, but not all of your comments.  Bullet 3 specifically is the main one I disagree with (assuming I'm not missing something -- I haven't reviewed the patch).  While you're certainly right that 'mpicc' isn't a requirement for using MPI, it is a common path.  But more importantly, this Makefile isn't saying "to use MPI.chpl, you must use 'mpicc'; rather, it's saying "if you set CHPL_TARGET_COMPILER to 'mpicc' then we'll use 'mpicc' which I think is exactly right.

The theme about avoiding the assumption that mpicc is wrapping gcc is a good one, though I'd also be OK with taking this patch as-is and refactoring the compiler Makefiles further later.  Probably the principled approach would be to have an Makefile.mpi that sets mpicc as the compiler (and the like) but says little, and nothing non-portable about the flags to pass it.  Then to have Makefile.mpi-gnu, Makefile.mpi-intel, etc. to avoid confusion.  We'll also need to update documentation, but I'd either expect us to do that or to give really clear guidance to Nikhil if he's willing to do it.

I believe that having two-sided messaging is a valuable library package, even if one-sided communication is a better thematic fit for Chapel, simply because the number of one-sided programmers is significantly lower than the number of two-sided programmers.  Moreover, I think one-sided programming in an explicitly SPMD programming model (what Nikhil is providing here -- i.e., create single-locale programs and use mpirun to launch them) doesn't really fit the Chapel model because we don't have a co-array model or something equivalent.  If we took the proposed add-on step of permitting a multi-locale Chapel program to call into MPI, that's the context where I'd expect one-sided to make more sense (but I'd still support two-sided there as well because I don't see the downside).

**Comment by npadmana** [comment]
Hi @mppf, @bradcray -- on the issue of Makefiles (easier), I can see arguments both ways in terms of naming/having an mpi target compiler. I'm happy to replace the current Makefile.mpi with something built/copied from the cray-prgenv example -- and rename appropriately if that's what we want to do.  I don't think I could (easily) extend it to handling the multiple-compiler case, although I agree with Michael that this is a bad design assumption.

**Comment by npadmana** [comment]
On the broader question that Michael raises in point 3, it may be worth thinking about the motivation behind something like this. As Brad points out, the primary mode I was thinking of this in is a simple SPMD mode, with Chapel running single locale and the N processes communicating via MPI (a MPI+Chapel alternative to MPI+OpenMP etc). 

In no particular order, here are some reasons why this might be worth considering (apologies for the length) -- 

1. Interfacing with parallel libraries that are built against MPI -- I suspect (with no real proof!) that some number of users are writing codes where the complicated and optimized parts are in packaged libraries, that more likely than not, assume MPI for the distributed parts. I'm thinking of FFTW, PETSc, Scalapack, and the like In all those cases, a Chapel user would have to call some basic MPI initialization routines. Furthermore, the workflows in all these cases are written assuming SPMD and MPI -- it's just a much lower potential barrier to calling known MPI routines than figuring out the best way to do it in Chapel. 

2. Trivial parallel programs -- some number of problems are really embarrassingly parallel with minimal communication. The last time I tried these (which I'll admit was a few versions back) in Chapel, there was a performance penalty for doing this in Chapel (i.e. single locale codes ran slower multi-locale, even with minimal/no communication). An MPI module can get someone up and running quickly, using idioms they're already quite familiar with --- and not pay a performance penalty (which you *really* don't want to pay on simple programs!).

3. Familiarity -- I'd argue that more people are familiar with basic MPI communication idioms. I, for one, would not want to write an AlltoAll using GET/PUT (I could do it, but I suspect I'd do it in a stupid way that would just be slower than the MPI version).

4. As to why MPI and not OpenSHMEM -- simply that I think MPI is just more broadly used/ taught/ supported etc. Again, reduces the barrier to adopting Chapel. (Personal observation --- I've never used OpenSHMEM. While I'm  sure I could figure it out, I suspect expediency would win and I would just wrap the three MPI commands I needed, instead of trying to figure it out. Which, in effect, is how this started for me.)

An extension of this idea would be to develop an MPI+Gasnet story, since that would let users more gradually switch communication patterns when opportunities arise. This is certainly possible on Gasnet-over-MPI, but it'd be great to see how it plays when Gasnet is using a different backend.

A fair question is whether or not this should be part of the Chapel distribution. I can't answer that question -- but I do see arguments both ways. I think, given the absence, of a curated external module library, it might make sense to be part of Chapel. Plus, it's actually low-level and generic enough that it again feels like it should be in Chapel. 

I guess, as my final argument, I'll add that I think MPI isn't going to disappear, or even wane in popularity, anytime soon -- it's just a little too entrenched. It's probably good strategy for Chapel to play nice with it. :-)

**Comment by mppf** [comment]
Thanks @npadmana for the discussion. I think it will be really useful to have this rationale recorded here in this pull request. It's my personal belief that we should investigate deeper integration with MPI or OpenSHMEM or both in order to enable multi-resolution programming for communication optimization. I think what you have here is a reasonable 1st step. But for such ideas to make sense to me, we need to have Chapel locale == MPI rank. Future work.

About the Makefiles - I'd personally favor building Makefile.mpi-gnu for now and then letting others work on making a portable Makefile.mpi (or filling in in the other common compilers). If you are comfortable with changing to a strategy inspired by Makefile.cray-prgenv-gnu - that would help a lot. It might seem like this Makefile.mpi is getting too much scrutiny - but in the current form it's the only piece of this PR that would be in a release. The rest can be a more prototype quality in test/ with NOTEST - at least for now.

**Comment by bradcray** [comment]
I like the "Makefile.mpi-gnu for now" approach as well (where it defines the mpi compiler symbols and then includes Makefile.gnu for the stuff that's common).  I'd really like to see MPI.chpl go into modules/packages/ as well -- either in this PR or shortly after once we get some testing up and running and the documentation building (not that every routine needs to be documented -- I think we can refer to the MPI documentation as we do for other packages).  I don't see any reason that we wouldn't want to include it in the 1.14 release (and to get it onto master and into users' hands ASAP).  I.e., I think we should consider this to be building toward a released package, not an experiment relegated to test/.

**Comment by npadmana** [comment]
Quick updates --
1. Makefile.mpi --> Makefile.mpi-gnu and this is now a simple include.
2. The README now includes some motivation behind this module.

On the longer term question of deeper integration between Chapel and MPI (i.e. running Chapel in multilocale mode), I'll note that GASNet and MPI are supposed to play well together, even for non-MPI conduits. The only restriction is that one needs to make sure that MPI and GASNet communications don't overlap. Doing this would require exposing access to gasnet_notify() and gasnet_wait(), or some equivalent barrier. But I think that may be all that is required for GASNet.....

The GASNet documentation also notes that while every effort is made to have GASNet nodes map to MPI ranks, but that is not guaranteed. Although the MPI module could actually build that mapping. In fact, the current version has a worldRank module level variable, that could be promoted to an [numLocales] array filled at initialization.

**Comment by mppf** [comment]
@npadmana - I'd be comfortable merging the Makefile.mpi-gnu now.
The other changes could be merged now (and reviewed as part of moving them to modules/packages) or you could get feedback on them now. Let me know your preference.

One basic question is that much of this PR is files in test/users/npadmana/mpi/c_bindings_1.1.
I see you have a Python script to make the Chapel extern declarations, right? What's going on with the .html files? (Should they be checked in, or are they an intermediate build step?)

Thanks!

**Comment by npadmana** [comment]
I'm fine with either approach --- either merge and then review/move, or review and then merge. What's easiest?

Ah - the html files. Those are actually grabs of the MPI 1 standard, from which I pulled the function prototypes from (which are the *.h files). It's nice having them around as "documentation", but they certainly shouldn't be part of anything that is released.

**Comment by bradcray** [comment]
At a glance: We should probably steer away from putting the html files into the repo as well since they're someone else's IP (and we'd technically have to get such cases reviewed by our lawyers before incorporating them I'd guess).

**Comment by npadmana** [comment]
I'd be fine with creating a new pull request that doesn't include the c_bindings_1.1 directory.....

**Comment by mppf** [comment]
@npadmana - I think it would be valuable to commit the Python script you wrote. The other parts (html, h files) I'd leave out but perhaps write in a README how to get them.

If you want advice about how to proceed - I'd make 2 separate PRS;
 * one PR that is just the Makefile.mpi-gnu change
 * one PR that puts the MPI module into modules/packages, adds your test, possibly your .py file, but not the HTML files

I'll give you a detailed review on the MPI module before we merge the new PR.

**Comment by npadmana** [comment]
@mppf -- I think PR #3798 implements the second of your bullet points on refactoring this PR. If we're happy with that, then I think this can be safely closed.

**Pull request closed without merging**
