### PR TITLE
Closes #21206: Fix bigint right shift

### LINKED ISSUE #21206: bug with right shift on `bigint`
### Summary of Problem

When right shifting a `bigint`, I seem to always get `0` as the result. I think this is because `c` is double defined, so the changes never make it to the one in the outer scope
https://github.com/chapel-lang/chapel/blob/da619d9d8b252056704dd73e0608d2f7f794947f/modules/standard/BigInteger.chpl#L1310-L1315

### Steps to Reproduce

**Source Code:**

```chapel
use BigInteger;
writeln(4:bigint>>1);
```

**Compile command:**

```
chpl PlayingAround.chpl -o playing
```

**Execution command:**

```
./playing
```

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.28.0
  built with LLVM version 14.0.6
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: none
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
Homebrew clang version 14.0.6
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm@14/bin
```

### PR DESCRIPTION
**Pull request by pierce314159**
This PR (closes #21206) fixes a bug in bigint right shift by removing an extra var declaration

### CODE REVIEW

**Review by mppf — COMMENTED** [review]
This looks good to me but we'll need to wait for code freeze to end & run testing on it before merging it.

**Comment by bmcdonald3** [comment]
I've got myself down to test/merge this after the release. Thanks for the contribution Pierce!

**Comment by bmcdonald3** [comment]
There was just one failure coming from a test that was actually a bug that this fixed 🎉.

I've opened https://github.com/pierce314159/chapel/pull/1 to put that fix into this PR (at least, I think that's how we do that).

**Comment by pierce314159** [comment]
> There was just one failure coming from a test that was actually a bug that this fixed 🎉.
> 
> I've opened [pierce314159#1](https://github.com/pierce314159/chapel/pull/1) to put that fix into this PR (at least, I think that's how we do that).

Awesome! Thanks @bmcdonald3! I merged your PR in my fork

**Comment by bmcdonald3** [comment]
Thanks for the contribution Pierce!

**Pull request merged**
