### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in

convert-uast.cpp, resolution-queries.cpp, scope-queries.cpp,
GPU.chpl, IO.chpl,
gpu-cuda.c, topo-hwloc.c

### CODE REVIEW

**Comment by cassella** [comment]
Please review:

- [ ] @dlongnecke-cray - scope-queries.cpp
- [ ] @jeremiah-corrado - IO.chpl
- [ ] @jhh67 - topo-hwloc.c
- [ ] @mppf - convert-uast.cpp, resolution-queries.cpp
- [ ] @stonea - GPU.chpl, gpu-cuda.c

The string "overscribed" does not appear in any test output.  I didn't run any tests.

**Review by mppf — APPROVED** [review]
Looks good to me, but needs a test run

**Comment by cassella** [comment]
@jhh67 Could you take a look at the topo-hwloc.c change?

I still haven't tested since I can't do a paratest, and the last time I tried a full start_test on my laptop it took over 20 hours.

**Comment by jeremiah-corrado** [comment]
I'll run a paratest

**Comment by jeremiah-corrado** [comment]
Passed!
```
[Summary: #Successes = 14177 | #Failures = 0 | #Futures = 0]
```

**Review by jhh67 — APPROVED** [review]
topo-hwloc.c looks good.

**Pull request merged**
