### PR TITLE
Stop generating serialization code for GPU binary

### PR DESCRIPTION
**Pull request by e-kayrakli**
Resolves https://github.com/chapel-lang/chapel/issues/21975
Resolves https://github.com/chapel-lang/chapel/issues/20276

We don't need to codegen serialization table for the GPU LLVM module. This PR addresses that. This is similar to the change in https://github.com/chapel-lang/chapel/pull/19857/files#diff-b6e4e1973139083c652228fd456a4ae16147b14703fa011a03c243be9e1e2200R1968

Test:
- [x] local gpu/native
- [x] gasnet gpu/native

### CODE REVIEW

**Comment by bradcray** [comment]
Which form of serialization are you referring to here?  Cross-locale serialize/deserialize, or something else?  What does this table represent?

**Comment by e-kayrakli** [comment]
I am referring to the serialization table the compiler generates to support broadcasting global constants. I believe it stores the constants' addresses, on which locales other than locale 0 deserialize the data into. The 2nd part of codegen which generates the GPU code shouldn't do any of this. At least not today.

**Review by stonea — APPROVED** [review]
I see your comment at <https://github.com/chapel-lang/chapel/pull/21982#discussion_r1151275130> and it looks like ultimately this stuff gets used in `ChapelSerializedBroadcast.chpl` to "deeply broadcast global consts".

So, as I understand it, this gets used as part of copying the values of global constants in the user's code to all locales. I assume the idea is we don't want to duplicate whatever processing is used to assign those global const on all locales (maybe for efficiency reasons or maybe for correctness?). @benharsh, I see you have your fingerprints on `ChapelSerializedBroadcast.chpl` can you confirm if my understanding here is correct?

As far a GPU support goes I don't suppose this would be an issue if we fail to broadcast to the GPUs themselves since if that global gets used from within a GPU kernel like this:

```chpl
const globalConst = nonIdempotentFunction(); // will only get called once, value broadcasted

on Locales[1] {
  on here.gpus {
    foreach i in 0..<N {
      use(globalConst); // Use within GPU kernel
    }
  }
}
```

`globalConst` would get passed to the kernel as argument (the same as we do for any other variable).

I also don't suppose this would be an issue if the global const were for an array either.

**Comment by bradcray** [comment]
> I believe it's a matter of correctness that we don't duplicate the initialization expression on each locale. In particular, I believe we define module-scope variables to be initialized on Locale0.

I think that's correct.  Specifically, if we had declarations like:

```chapel
const x = computeRandomNumber();
const y = readHugeFile();
const z = computeExpensiveComputation();
```

we'd want to guarantee that all locales had the same result (e.g., computed the same random number) and that the computation wasn't done redundantly (e.g., everyone didn't bottleneck the file system by trying to read the file simultaneously).

Arguably, if the compiler could prove to itself that a module-scope const initializer was sufficiently pure / cheap / side-effect free, it could arguably optimize the initialization without the user being any the wiser.

**Pull request merged**
