### PR TITLE
Chapel Docs Reorg

### PR DESCRIPTION
**Pull request by ben-albrecht**
As Chapel documentation continues to grow, this growth demands greater efficiencies in all areas of its operation. One of the ways we've stepped up to meet these demands, is by merging the Chapel documentation hierarchy into a single directory `doc/`.

Please be aware of these changes, as they may impact you upon merging.
- `doc/sphinx` is now merged with `doc/release`, which both now live under `doc/`
  - There is no longer a distinction between the paths for docs in the release tarball and paths for the git repository. The `gen_release` script strips out the irrelevant sphinx-configuration / index files from `doc/`
  - There is now less of a distinction between the paths for docs in the `doc/` directory and the paths on the website, [chapel.cray.com/docs/master](chapel.cray.com/docs/master)
  - We no longer symlink files between these directories
  - All references to `doc/sphinx` and `doc/release` have been updated to `doc/`
  - Any skeleton directories that contain primarily generated documentation, e.g. `doc/modules`, will live in `meta/` to be copied in upon build, e.g. `cp -f .modules/* modules/`
    - This is to avoid clutter for the user browsing documentation in from the command line
- `doc/sphinx/build` is now generated as `build/doc`
- scripts for building docs now live in `doc/util`
- Makefiles for building docs now live in `doc/`
- developer docs continue to live in `doc/developer` and can be easily included into the built html documentation, once formatted over to restructured text

View the new docs layout [here](https://github.com/ben-albrecht/chapel/tree/docs-reorg/doc)

_Testing_

-  [X] `make docs`
- [x] `doc/ make docs`
- [ ] `doc/ make man-chapel`
- [x] `gen_release` tarball
- [x] test on system that requires the venv for sphinx

### CODE REVIEW

**Comment by bradcray** [comment]
Two quick thoughts:

1) I'm curious whether the new approach does any better than the old at not being sensitive to directories being removed/renamed in its clean/clobber/build steps?  It seems like a way to deal with this in the old world might've been to push all auto-gen'd directories down a level and then remove the parent directory which would blow away its contents whatever they were.

2) I'm not so crazy about the use of lots of .dotDirectories and am not sure I understand the rationale for it as described in the PR.  Who are we trying to insulate, and in what context are we trying to protect them?  Could we instead push all this stuff down one directory and call it something like gen/ or autogen/ or devel/ or something that would be neither invisible nor unclear?  (This might also help with #1?)

**Comment by ben-albrecht** [comment]
This PR doesn't do anything to address the fragility of the clean build step for the docs.

I think this problem is annoying enough to address, but probably in a future PR. Utilizing `git clean` within the `doc/Makefile` clobber target might be appealing as a dev-only git-only feature. Tucking generated files into a subdirectory may mitigate the issue for certain cases, but won't eliminate it entirely.

The dot directories are hiding directories that are empty aside from an `index.rst` from users that might browse the docs in the github repository in their terminal. It might be confusing or even frustrating for users to find the near-empty directories sitting next to the actual documentation under `doc/`.

**Comment by ben-albrecht** [comment]
Since this branch goes stale very rapidly, I will only merge master into it again post-review

**Comment by benharsh** [comment]
Offline we discussed moving the dot-directories under a single folder. Otherwise, I think this looks good. I was able to build the docs on my mac successfully.

**Comment by ben-albrecht** [comment]
@benharsh Correct - the `meta/` migration occurred last commit. Also, the internal test infrastructure PRs are opened.

Going to run through my testing again, and then merge all the changes over the weekend or Monday.

**Pull request merged**
