### PR TITLE
Add PyYAML to our testing system requirements

### PR DESCRIPTION
**Pull request by ronawho**
Our annotations rely on PyYAML, so I'm adding it to the list of requirements.
Previously our perf testing machines happened to have PyYAML installed so we
didn't think to have it in our requirements. This will allow perf graph
annotations to be generated on any machine.

Since PyYAML should always be available, I added a warning to genGraphs if we
fail to import our annotate module (which would only happen if PyYAML isn't
available.)

### CODE REVIEW

**Comment by ronawho** [comment]
@Kyle-B mind taking a quick look?

Also, is there a way to get make to rebuild chpl-venv if the requirements file has changed?

**Comment by Kyle-B** [comment]
Looks good. We should be able to make `test-requirements.txt` a dependency of the Makefile job, I think it will still require you to do a top level `make test-venv` still though.

**Comment by ronawho** [comment]
How would you do that? (I'm a makefile noob)

**Comment by Kyle-B** [comment]
Can we merge this one now?

**Comment by ronawho** [comment]
Probably, but I'm going to wait till I'm clear of all the reporting stuff just in case anything goes wrong

**Comment by lydia-duncan** [comment]
We need PyYAML to run the create_graphs script for the report, fyi

**Pull request merged**
