### PR TITLE
Fix test of masonTest() that broke in PR #16098

### PR DESCRIPTION
**Pull request by bradcray**
This fixes changes to masonTest() that were introduced in PR #16098
when they assumed that 'args' was an array when the Launcher_test.chpl
test passes it a list.  Here, my fix was to use .indices rather than
.domain to query the argument's size; using an unbounded range to then
slice the list seems like it ought to be supported, yet is not (and
generates a not user-friendly error message), so I'm filing a future
against that as well.

### CODE REVIEW

**Comment by bradcray** [comment]
I'm going to merge this without review to avoid a breaking test tonight, but if @ankingcodes and @ben-albrecht could give it a post-merge review, I'd appreciate it.

**Comment by ben-albrecht** [comment]
@bradcray - Thanks for catching this and implementing a fix. I mistakenly only ran testing on `test/mason` for https://github.com/chapel-lang/chapel/pull/16098 when reviewing. 

This does make me wonder if the test(s) in `test/library/packages/UnitTest` should be updated, since all other mason entry functions expect an array rather than a list. The `args` is generally expected to be the `main(args: [])` passed down.

**Comment by bradcray** [comment]
That would be fine with me as well, though I'd probably change `masonTest()`'s formal to assert array-ness (e.g., `proc masonTest(args: [])`) if that's an implied intent/requirement.

**Comment by ben-albrecht** [comment]
> That would be fine with me as well, though I'd probably change masonTest()'s formal to assert array-ness (e.g., proc masonTest(args: [])) if that's an implied intent/requirement.

Yep, I think that's a no-brainer. I'll open a PR for this.

**Comment by ben-albrecht** [comment]
> That would be fine with me as well, though I'd probably change `masonTest()`'s formal to assert array-ness (e.g., `proc masonTest(args: [])`) if that's an implied intent/requirement.

I opened a PR for this here: https://github.com/chapel-lang/chapel/pull/16139

**Pull request merged**
