### PR TITLE
test: change decl from `ref` to `var` and add future for `ref` version

### PR DESCRIPTION
**Pull request by arezaii**
test: change decl from `ref` to `var` and add future for `ref` version

This PR updates the declaration of a variable in a test from `ref` to `var`.

When troubleshooting failing tests with the dyno parser, we discovered 
that this test declared a `ref` to the `vararg` formal, which is itself 
returned as a `ref`, so this should have produced a type or lifetime error
in the current compiler. However, it was compiling and running because
internally it was converting the `ref` to a `const val`. Redeclaring the 
variable as a `var` keeps tests passing. 

Captured the existing test as a future referring to issue 
https://github.com/chapel-lang/chapel/issues/19614.

TESTING:

- [x] paratest
- [x] paratest with `--dyno` (602 failures)

reviewed by @mppf - thanks!

Signed-off-by: arezaii <ahmad.rezaii@hpe.com>

### CODE REVIEW

**Comment by mppf** [comment]
> we discovered that this test declared a ref to the vararg formal, which is itself
passed as a ref, so this should have produced a type or lifetime error
in the current compiler

it should say

> which is itself is returned as a ref,

**Review by mppf — APPROVED** [review]
I think you should add a future next to it asking for an error message for the `ref` case. You can mark it `.noexec`.

**Comment by e-kayrakli** [comment]
Looking back at the PR that added this test (https://github.com/chapel-lang/chapel/pull/14089), I don't think we should make this change. Changing from ref to var would create a new copy of the tuple (right?) that changes the memory behavior of the test.

That being said, I am not seeing why the code in question is invalid either. The OP says that this should be error. If that's the case, I agree with Michael that I think the test should be futurized asking for an error message here. I am not sure if we need the `var` version in that scenario.

**Comment by mppf** [comment]
@e-kayrakli - the PR that added the test was addressing a bug report and added the test as an improved version of the bug report exemplar. But the bug report didn't have the `ref refToArg` business. I'd like to encourage @arezaii to split the test into two; where one can have the ref to var change and the other can be the test as-is, which perhaps should be an error.

Let's look at it:

``` chapel
proc bar(paths: myRec ...?n) {
  ref refToArg = paths;

  return refToArg;
}
```

I had been thinking that you can only take a `ref` to a value tuple (which would lead to other problems like returning a ref to a local temp). However that doesn't seem to be the case - the compiler seems to be making a tuple containing refs to each of the arguments. But, the arguments should be passed by default intent, which in the case of a record, is `const ref`. So you should not be able to get a mutable reference to a `const ref` argument.

When returning, since `bar` returns by value, it cannot return the referential tuple and so it has to copy the elements. If it is `var x = paths; return x;` then there is still a single copy of the tuple elements (it just occurs at that line rather than at the return). So the memory behavior is very similar.

**Comment by mppf** [comment]
Also @dlongnecke-cray  this has to do with "What does it mean to capture a tuple by `ref`" which you have been involved in.

See #15973 which is about the return case specifically but I would imagine capturing to a `ref` to be similar.

**Comment by e-kayrakli** [comment]
Thanks for the explanation Michael! I support the direction you're suggesting.

**Pull request merged**
