### PR TITLE
Retire 'jacobi-unoptimized' test

### PR DESCRIPTION
**Pull request by bradcray**
This removes the jacobi-unoptimized.chpl test, which is identical to
the jacobi.chpl test in the same directory except that it is compiled
with --baseline --inline.  We run the test suite nightly with the --baseline
flag and I think this test's choice of flags is largely historical, so I consider
it a bit of an odd duck and don't think it's worth preserving, as it doesn't
feel particularly well-motivated (i.e., should we test it with all combination
of flags that `--baseline` enables and disables as well?  Why this test
rather than all / other tests?)

The motivation for retiring this test at this time is that for LLVM
testing, it revealed an LLVM+baseline+inline-specific bug.  That bug
is arguably worthy of being addressed (see issue #13744), but it
doesn't seem to me that it should be a requirement to get a clean run
of the test system to be able to compile this test with `--baseline --llvm`.
If we care about that flag combination for some reason, we should test it
distinctly (but I don't think we do... at least any more or less than any other
flag combination).

### CODE REVIEW

**Comment by bradcray** [comment]
@mppf: Are you OK with this rationale / approach?
@lydia-duncan / @vasslitvinov : FYI

**Comment by mppf** [comment]
@bradcray  yes, sounds good. I think we need an issue though (public or private) to track that we know --llvm --baseline is not working.

**Comment by bradcray** [comment]
Oh wait, it appears to be not specific to `--llvm --baseline` but rather to `--llvm --baseline --inline` ("turn off all default optimizations except for inline")...  I still think retiring the test is the right thing to do (it seems odd to me to have a test specific to whether `--baseline + --inline` work, and I think this test is more a product of early history than anything), but it makes the issue I'll file at Michael's request more specific and less of a concern (to me at least).

**Comment by bradcray** [comment]
I've updated the description of this PR to reflect that new understanding and tuned my argument for removing the test accordingly.

**Pull request merged**
