### PR TITLE
Bump version number to 2.0.1

### PR DESCRIPTION
**Pull request by bradcray**
This bumps the version number to 2.0.1 and is intended for the 2.0 branch only.

### CODE REVIEW

**Comment by bradcray** [comment]
@arezaii : Looking for a check—am I correct that this should be all that's necessary to change the version number for `chpl` these days?

**Comment by arezaii** [comment]
Mostly. This will work to update the version in `chpl` and `chpldoc`, but there are a few helper files that you should consider:

- `test/compflags/bradc/printstuff/version.goodstart`
- `man/confchpldoc.rst`
- `man/confchpl.rst`
- `doc/rst/conf.py`
- `doc/rst/language/archivedSpecs.rst`
- `doc/rst/usingchapel/QUICKSTART.rst`
- `doc/rst/usingchapel/chplenv.rst`

I used https://github.com/chapel-lang/chapel/pull/24646 and the linked PRs in it for reference

**Comment by bradcray** [comment]
Thanks @arezaii!  I was thinking `test` didn't need to be updated since it wouldn't be in the release and had forgotten that so many of the docs were sensitive to all three version numbers.  I wonder whether we should chop some of those down to just `x.y` (not here, but back on `main` for the future) in the sense that the `man` pages shouldn't be super-sensitive to the patch version.  I'd be curious if you have thoughts about that.

**Comment by arezaii** [comment]
I would be fine with dropping the patch and just formatting the `man` pages with major.minor

**Comment by bradcray** [comment]
Thanks @arezaii — Would you have time to review this PR?

**Review by arezaii — APPROVED** [review]

**Pull request merged**
