### PR TITLE
reduce-with-for-in-par-iter test: Update references to other tests

### PR DESCRIPTION
**Pull request by cassella**
Update paths to two other tests referenced in this one.

### CODE REVIEW

**Comment by cassella** [comment]
@vasslitvinov This fixes the references to the paths.  But what this test says about them is:

```
Once this future is resolved, remove this test altogether
and uncomment the lines "writeln(+ reduce pariter2());"
in:
```

and this test is no longer a future as of 3971a3bb0e8, and the line referred to in those tests is still commented out.  So of course feel free to reject this PR in favor of your own advice.  :)

**Review by vasslitvinov — APPROVED** [review]

**Comment by vasslitvinov** [comment]
I should surely follow my own advice. We can merge this change meanwhile.

**Comment by cassella** [comment]
Hi @vasslitvinov, do you still want to merge this?

When I opened it, I just updated the paths instead of making the suggested changes because at a quick look at the named code, I thought "uncomment the line" might have actually meant "uncomment to replace the other `writeln(+ reduce` that's there"; or if both were to be present, to update the good file, and I didn't (and haven't) taken the time to read `pariter2()` to think about what the .good file should have for its reduction.

**Comment by vasslitvinov** [comment]
Superseded by #21374.

Thanks @cassella for drawing my attention to it!

**Pull request closed without merging**
