### PR TITLE
Fix sorting of arrays whose domains don't include their own .low due to alignment

### PR DESCRIPTION
**Pull request by cassella**
This continues the work @mppf started in #13175.

I was too confused by #13174 to keep using `domain.first` as in
#13175, so I switched all the sorts to start with `domain.alignedLow`
and increment by `abs(domain.stride)`.

Make more of the arrays in `test/library/packages/Sort/correctness`
larger in order to actually test quickSort and mergeSort on the
various stride and alignment cases.

Fix mergeSort and quickSort to handle strided arrays.

I ran only a non-performance run over test/library/packages/Sort.

TODOs

- [x] correctness.chpl creates mostly size-4 arrays to sort, and one size-20 with the comment "quickSort requires domain.size > 16".  But quickSort has two separate implementation functions - one for strideable arrays one one for nonstrideable.  correctness.chpl is testing only the latter.  I'm inclined to make all the arrays larger so that both versions of quicksort are tested.  Sound good?
- [x] I added a writeln() to each sort/array pair in correctness.chpl to make it easier to track down which test was hanging or halting in Random.chpl.  I can undo that if you'd like.
- [x] Try reunifying the `mergeSort` implementations with non-strided temporary arrays in `_Merge` to see if that regains performance.

### CODE REVIEW

**Comment by mppf** [comment]
@cassella - looks good at a quick look. "Yes/OK" is my answer to the questions asked in TODOs.

**Comment by bradcray** [comment]
I've noted on the chapel-btr channel that Paul should be added to the list of Cray employees to avoid the "cla required" tag.

**Comment by bradcray** [comment]
> I've noted on the chapel-btr channel that Paul should be added to the list of Cray employees to avoid the "cla required" tag.

I believe I've fixed this now (though I manually removed the tag here).  Give a shout if it happens again on subsequent PRs and I don't notice.

**Comment by cassella** [comment]
It turns out `mergeSort` also has a minimum size under which it dispatches to insertion sort.  Which I discovered because `mergeSort`, like `quickSort`, has problems with strides.

I've fixed that up in this commit, but I'm not sure if there are performance impacts to `mergeSort` that mean it oughta be `param`eterized by `stridable` like `quickSort` is.

I'm also not entirely sure that the slicing ranges in `mergeSort` and `quickSort` should need to be so explicitly specified, but I had to to make it work.

I meant to make all the test arrays larger, but haven't yet.

I haven't removed the added `writeln()` yet.

**Comment by cassella** [comment]
I ran the `test/library/packages/Sort/performance` test, comparing master to my branch.  Most of the sorts are about the same or a little faster(?) except heapsort (twice as slow) and mergesort (10x as slow).  I expected mergesort to possibly be a little slower due to having `+= stride` instead of `+= 1` (and having to compute `stride` in the first place) but not 10x slower.  Maybe my laptop's just not a good performance test environment?

Aside: Why are insertionsort, selectionsort, and bubblesort, in that order, by far the fastest, even on master?

**Comment by cassella** [comment]
In the correctness test, I increased all but two of the test arrays to 20 elements.  I left alone the first two,

```chapel
                // Testing A.eltType
                ([-4, -1, 2, 3], defaultComparator),
                (['Brad', 'anthony', 'ben', 'david'], defaultComparator),
```

The first because I couldn't figure out what it was supposed to be testing differently than the others, and the second because you'll have to hire more people with unique names first.  Also because leaving at least one smaller test keeps test coverage of the paths in merge and quick sort where they delegate immediately to insertionSort.

**Comment by cassella** [comment]
I restored the original `mergeSort` and its helpers with a `where !Dom.stridabe`, and the performance is back.  The heapsort performance came back by itself -- it was probably just a transient load issue, especially since the PR didn't modify heapsort at all.

I'm still surprised that the changes in 7a9dfd4 caused mergesort to get nearly 10x slower.  Is it because the arrays in `_Merge` are no longer non-strided?

**Comment by cassella** [comment]
> Is it because the arrays in _Merge are no longer non-strided?

If it is, it might be possible to get the performance back in a better way than I've done it.  I think those temporary arrays don't need to be strided, even if `Data` itself is.  Let alone when it's not.

**Comment by cassella** [comment]
That didn't seem to help.  I tried the following.
If performance improved, it wasn't by much.

```diff
--- a/modules/packages/Sort.chpl
+++ b/modules/packages/Sort.chpl
@@ -931,31 +931,33 @@ module MergeSort {
   private proc _Merge(Data: [?Dom] ?eltType, lo:int, mid:int, hi:int, comparator:?rec=defaultComparator) {
     const stride = if Dom.stridable then abs(Dom.stride) else 1;
     var a1max = mid;
-    var A1 = Data[lo..(a1max) by stride];
+    const a1size = (lo..a1max by stride).size;
+    var A1: [1..a1size] Data.eltType = Data[lo..(a1max) by stride];
     var a2max = hi;
-    var A2 = Data[mid..(a2max) by stride];
-    var a1 = lo;
-    var a2 = mid + stride;
+    const a2size = ((mid+stride)..a2max by stride).size;
+    var A2: [1..a2size] Data.eltType = Data[(mid+stride)..(a2max) by stride];
+    var a1 = 1;
+    var a2 = 1;
     var i = lo;
-    while ((a1 <= a1max) && (a2 <= a2max)) {
+    while ((a1 <= a1size) && (a2 <= a2size)) {
```

Plus making all increments of `a1` and `a1` by `1` instead of by
`stride`, and testing them against `a[12]size` instead of `a[12]max`.


But then further making the slices used to initialize the temp arrays non-strided when Dom is not stridable did it:

```chapel
    var A1: [1..a1size] Data.eltType = if Dom.stridable then Data[lo..(a1max) by stride] else Data[lo..(a1max)];
...
    var A2: [1..a2size] Data.eltType = if Dom.stridable then Data[(mid+stride)..(a2max) by stride] else Data[(mid+1)..(a2max)];
```

Slicing a non-strided array by a range `by 1` is that much worse than slicing by a non-strided range?

**Comment by cassella** [comment]
Last force-push tweaked a comment in `_Merge`.  I think this is done, but I can't update the labels myself.

My only reservation is that mergesort performance got so much worse when I naively used a `by n` range when `n` was 1 to slice a non-strided domain.  Intuitively, I didn't expect it to be that much worse.  But I worked around it in that last commit by special-casing non-strided domains and slicing them by a range without a `by` clause instead.   I don't understand why that's necessary, but worked around it.  Is that expected, or worth a separate issue?  I wasn't able to reproduce it in a few minutes with a simpler standalone test case.

**Comment by mppf** [comment]
This has passed full local testing.

**Comment by cassella** [comment]
The Sort correctness.chpl test will call Shuffle on each array, including the strided ones.

test/library/standard/Random/shuffle.chpl does directly test shuffling a strided array.  Should there be an oddly-aligned on there too?

**Comment by mppf** [comment]
> The Sort correctness.chpl test will call Shuffle on each array, including the strided ones.

Thanks for pointing it out!

> test/library/standard/Random/shuffle.chpl does directly test shuffling a strided array. Should there be an oddly-aligned on there too?

Yeah, that would be great.

**Comment by cassella** [comment]
I added that oddly-aligned test case to the Random/correctness.chpl test.

I used the same seed=10 as the previous case so that the output would have the same permutation as that case in the .good file.

**Pull request merged**
