### PR TITLE
Tidying up Zarr IO Module Documentation

### PR DESCRIPTION
**Pull request by brandon-neth**
Small PR to remove documentation of private helper methods and modules from the Zarr IO module. This will make the documentation for the module more comprehensible for users.

### CODE REVIEW

**Review by lydia-duncan — COMMENTED** [review]
Why not make most of these private instead of "nodoc"?  Do you want them to be able to be called outside of your module?

**Comment by brandon-neth** [comment]
> Why not make most of these private instead of "nodoc"? Do you want them to be able to be called outside of your module?

Good point! I'll decide which ones to make private and add doc strings for the others.

**Review by lydia-duncan — APPROVED** [review]
Looks good, thanks!

**Comment by brandon-neth** [comment]
Tested the module code on chapdl and the docs by visual inspection on my mac. Thanks Lydia for the reminder to include testing details with my PRs!

**Pull request merged**
