### PR TITLE
Build Docker image for multiple backends

### PR DESCRIPTION
**Pull request by riftEmber**
Adds support for using the C backend (in addition to currently-supported LLVM backend) in the Docker image.

This is accomplished by building Chapel with `CHPL_TARGET_COMPILER` having each value of `{gnu, llvm}`. The runtime and some third-party support code is rebuilt to accomplish this, mildly increasing the size and complexity of the image.

The `chpldoc`, `test-venv`, and `mason` targets are not rebuilt as I consider them unlikely to be behave differently with different target compilers.

Resolves https://github.com/chapel-lang/chapel/issues/21448.

Testing:
- [x] multi-arch Docker image build succeeds
- [x] native Docker image allows `chpl` to be successfully invoked with `--target-compiler={gnu,llvm}`
- [x] native-arch Docker image build is not significantly slower

### CODE REVIEW

**Comment by riftEmber** [comment]
Native-arch Docker build took over 3x as long on the build step, so I must be rebuilding something that isn't needed. Will look into this

**Review by bhavanijayakumaran — APPROVED** [review]
Looks good.

**Comment by bradcray** [comment]
@riftEmber : Thanks for your help with this!  Sorry for my ongoing docker ignorance, but:  With this effort is the new image with both back-ends currently live / available, or would we need to do more work to reach that point?

**Comment by riftEmber** [comment]
@bradcray It is not available anywhere yet -- to use this new functionality one would have to build an image from the updated Dockerfile. We can manually do this and publish to Dockerhub (which I think we might have been planning to do). Once we have our nice Jenkins job building these it would get updated on its own.

**Pull request merged**
