### PR TITLE
Add futures for 21292 regarding nested foralls and domain literals

### PR DESCRIPTION
**Pull request by cassella**
These are three of the variants noted in #21292.

I didn't submit .bad files because the bad output is variable.

They all relate to a forall loop containing a taken continue and a forall expression over a domain literal.

### CODE REVIEW

**Comment by cassella** [comment]
@vasslitvinov Here's another for you.

**Comment by vasslitvinov** [comment]
@cassella seems that these tests may non-deterministically produce the expected output. Is this the case? If so, this may create noise in our nightly testing, so how can this be prevented?

**Comment by vasslitvinov** [comment]
@cassella if these tests fail under Valgrind/ASAN, they can be set up following this pattern:

    test/memory/elliot/valgrind/I-fail-without-working-valgrind.chpl

See especially .prediff and .skipif.  You want the observed valgrind output, after the prediff, to go in .bad instead of .good.

**Comment by cassella** [comment]
Hi @vasslitvinov I added a skipif so the tests run only under valgrind, and another commit adding the .prediff and .bad files.  I'm not sure the prediff and bad files are helpful, or if they may  just be overspecifying the current behavior.  I made a separate commit for them so it can easily be removed from the branch.

**Pull request merged**
