### PR TITLE
Fix faulty dependency while building protoc-gen-chpl

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Add source and header files as dependencies for building protoc-gen-chpl.

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@mppf Please see if this fix the problem?

**Comment by mppf** [comment]
@Aniket21mathur - it helps, but if I change only a header file, it does not rebuild. Could we add a HEADERS variable similar to SOURCES but looking for .h files and add that as a dependency?

**Comment by Aniket21mathur** [comment]
> Could we add a HEADERS variable similar to SOURCES but looking for .h files and add that as a dependency?

Yes...did that in 5f5ae59

**Comment by mppf** [comment]
@Aniket21mathur - works for me. Could you add something more to the PR message please before I merge it? Thanks.

**Comment by Aniket21mathur** [comment]
> Could you add something more to the PR message please before I merge it? Thanks.

Updated! Sorry for that :sweat_smile:

**Pull request merged**
