### PR TITLE
Group and other permissions don't stay when you download.

### PR DESCRIPTION
**Pull request by lydia-duncan**
So update the viewMode test.  It was an arbitrary choice in the first place.
I'll make one that forces the check against all permissions later.

### CODE REVIEW

**Comment by thomasvandoren** [comment]
In general, I don’t think you can expect git to preserve file permissions (users can define whatever umask they want, and git will respect it). You might need to add a preexec or have the test call chmod().

**Comment by lydia-duncan** [comment]
I was going to do a preexec for the later tests.  I've got other tests that do something along those lines, I had just forgotten what permissions were put on the saved file by default.

**Comment by lydia-duncan** [comment]
*by default by git when it created the file.

**Comment by lydia-duncan** [comment]
So I guess I'll do that now to be certain.

**Pull request merged**
