### PR TITLE
Removed 1.28-Pre-release tags from chapel repo

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
Signed-off-by: bhavanijayakumaran <82669529+bhavanijayakumaran@users.noreply.github.com>

As part of Chapel 1.28.0 release process, removing pre-release tags and replacing with 1.28.0

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Looks like you've got some commits from other people on this branch.  Maybe you need to rebase from main?

**Review by lydia-duncan — APPROVED** [review]
This seems right to me otherwise (but I don't think it should get merged until when the release branch actually gets cut?)

**Comment by bhavanijayakumaran** [comment]
Lydia, these commits are showing up after I did a rebase merge with the main branch.
I got confused after seeing those commits here but the PR changes shows only 8 files so we are good(unless I am missing something).

**Comment by lydia-duncan** [comment]
I'm not sure what you mean by a rebase merge.  Is that different than just `git rebase main` on your working branch?  The branch has a merge commit on it at the end, which I wouldn't expect if the rebase went okay

**Comment by lydia-duncan** [comment]
To be clear, I'm not entirely certain how these extra commits turn up myself

**Comment by bhavanijayakumaran** [comment]
I did sync fork on the Git-UI and also git rebase in the command line(to add signoff for a commit).

**Review by tzinsky — APPROVED** [review]

**Comment by lydia-duncan** [comment]
Okay, I think in the future it's best to just stick to the command line for git commands

**Comment by bradcray** [comment]
It looks to me like this question got lost in the discussion about rebasing:

> but I don't think it should get merged until when the release branch actually gets cut?

But I think what happened here is correct:  We usually merge a PR like this just prior to the code freeze to get some testing on it before cutting the release branch to make sure that the version number is working as expected for the release (so yesterday's timing was perfect).  Then a complementary PR is made just before the thaw of `main` to make it the pre-release of the next release.

[Note that I haven't carefully reviewed this PR at all... just glanced at the diff to see if it was what I expected]

**Pull request merged**
