### PR TITLE
Blas level 1

### PR DESCRIPTION
**Pull request by marcoscleison**

### CODE REVIEW

**Comment by ian-bertolacci** [comment]
This is both a comment about this work, and also some other BLAS work done previously.
I think we should use more concrete typed methods instead of having a generic method with the query on the eltype that is then used in select statement to pick the actual method.

**Comment by marcoscleison** [comment]
Hi Ian, thank you for your comments. I do not have a final position about this. As new coming, I cannot make an statement about the overhead that type checking imposes. 
We are in early stage of the blas level 1. I think that we could to remain with blas function with generic type, as we are coding and add typed functions without type checking. The developer can choose easier generic function or typed function. 
I do not know if this suggestion can be a silly idea. That is why I will wait the orientation of more experienced developers.

**Comment by ian-bertolacci** [comment]
Marcos, that's quite alright. In fact, this style of function typing is probably fine for now as it is consistent with the existing BLAS code.
I think at some-point (probably after this pull request is merged) we should make the jump to more statically typed functions (I may be volunteering myself for this).

On thing I'd like to note is that, while these functions are generic (in the sense that we've declared them as such) they are _not_ generic in reality. This is a limitation of the underlying BLAS implementation (which is not generic period). I think that it is confusing to have generic BLAS functions that are not actually generic.

**Comment by ian-bertolacci** [comment]
I think that .vscode/.browse.VC.db and .vscode/.browse.VC.db-wal need to be removed from this. VisualStudio might need to be added to the .gitignore

**Comment by mppf** [comment]
Regarding Ian's comment on run-time type checking; wouldn't it be sufficient to replace those uses of halt with compilerError ?

**Comment by ben-albrecht** [comment]
This was discussed offline, but just for clarity: 

I think the next steps for this PR are to add some correctness tests, preferably in a similar style to the current [level 3 blas tests](https://github.com/chapel-lang/chapel/tree/master/test/modules/packages/blas).

**Comment by ben-albrecht** [comment]
@marcoscleison has given me permission to take this existing work, and add the documentation/tests, submitted as a new PR.

Will add reference here when that PR is opened: **#????**

**Pull request closed without merging**
