### PR TITLE
Minor syntactic change to get path right in "Build finished" message.

### PR DESCRIPTION
**Pull request by gbtitus**
Without this I get the message:
  Build finished. The HTML pages are in $CHPL_HOME/doc/sphinx//html.

### CODE REVIEW

**Comment by gbtitus** [comment]
@ben-albrecht , does this look okay to you?

**Comment by ben-albrecht** [comment]
I meant for the output to be:

`Build finished. The HTML pages are in $CHPL_HOME/doc/sphinx/html.`

since the full path output can be a bit verbose and unnecessary - the user is likely working within $CHPL_HOME already. Do you think printing the full path would be better?

Either way, the `/sphinx//html` needs to be fixed. Good catch.

**Comment by gbtitus** [comment]
I'll fiddle with it and get it to print $CHPL_HOME instead of the expansion thereof.

**Comment by gbtitus** [comment]
@ben-albrecht , I think I have it correct now -- take a look?

**Comment by ben-albrecht** [comment]
Looks excellent! :+1:

**Pull request merged**
