### PR TITLE
Remove calls to getUserInstantiationPoint

### PR DESCRIPTION
**Pull request by benharsh**
These calls are expensive and slow down compilation significantly.

Testing:
- [x] local + futures

### CODE REVIEW

**Comment by benharsh** [comment]
@bradcray , @mppf : This PR will resolve the performance regression from #14887 . I briefly tried to move the call closer to the relevant error message, but it seems that point is too late to get the required information. Is this an acceptable tradeoff?

**Comment by mppf** [comment]
I think we should merge this for now and come back later to the question of better error messages for the affected tests

**Comment by bradcray** [comment]
I'm definitely in favor of getting the compile-time back at the expense of slightly less helpful error messages.  Out of curiosity, does compiling with a `--print-callstack-on-error` help with these cases at all?  (I'm guessing not).

**Comment by benharsh** [comment]
Unfortunately ``-print-callstack-on-error`` does not seem to help. I'll go ahead and merge.

**Pull request merged**
