### PR TITLE
Reduce uses of Math by automatically included modules

### PR DESCRIPTION
**Pull request by lydia-duncan**
Brad pointed out that it was unfortunate for AutoMath to rely on Math for any
permanent symbol.  So move the main work of logBasePow2 to a `chpl_` prefixed
function in AutoMath and call that instead of logBasePow2 in AutoMath.  Also
move the main work of log1p similarly, though these functions will only live there until
the deprecated versions of log1p have been removed, and then their contents
will be migrated back to Math.

Brad also pointed out that ChapelRange was using the Math module still.  This
module relies on symbols that are in AutoMath now, so it should explicitly use
that module instead.  If we discover that symbols we want to move to Math are
used by ChapelRange, we probably should rethink making them not included by
default.

Updates the module initialization order tests for the new output

Passed a full paratest with futures

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@bradcray - pointing out that this doesn't stop AutoMath from relying on Math due to the deprecated versions calling the ones in the new location, as I brought up in [this comment](https://github.com/chapel-lang/chapel/pull/19849#discussion_r880947227).  But when those functions are removed, Math will stop being used by default.  Just figured I should bring it up in case there was a miscommunication :)

**Comment by bradcray** [comment]
Sorry, I'm not following...  Can you give an example?  It may be that I misunderstood what you were proposing in that comment.

**Comment by lydia-duncan** [comment]
Sure!  So this change makes it so that uses of `logBasePow2` from AutoMath now refer to a `chpl_` version that lives in that file, which `logBasePow2` also relies on (see this line: https://github.com/chapel-lang/chapel/pull/19885/files#diff-78b0ad5d42239df6fc0e85c266069c6ea8dc85a908e5d23c16d66422990ebce2R878)

However, there will still be uses of Math in AutoMath like the ones here so that accesses that relied on the symbols being included by default will generate a deprecation warning:
https://github.com/chapel-lang/chapel/blob/main/modules/standard/AutoMath.chpl#L787-L791

But again, those uses will go away when we remove the deprecation warnings

**Comment by bradcray** [comment]
> However, there will still be uses of Math in AutoMath like the ones here so that accesses that relied on the symbols being included by default will generate a deprecation warning:

I would've expected `Math.log1p` to be defined (for now) by calling into an `AutoMath.chpl_log1p` which `AutoMath.log1p` would also call to break that AutoMath->Math dependence.  Essentially, the same thing  you did for `log2`.  Then, once we deprecate `AutoMath.log1p`, we can move the guts of `chpl_log1p` back into `Math.log1p` for simplicity.

**Comment by lydia-duncan** [comment]
That's why I asked, thanks! :)

**Review by bmcdonald3 — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
