### PR TITLE
Remove deprecated array as set operations

### PR DESCRIPTION
**Pull request by daviditen**
Remove the array-as-set operations that were deprecated last release along with
the associated tests in the deprecated directory.

### CODE REVIEW

**Comment by daviditen** [comment]
Thanks!

**Comment by bradcray** [comment]
@daviditen : With a quick look, it seems to me that https://chapel-lang.org/docs/main/technotes/sets.html should've been retired with this PR, does that seem right?  Or does it still have value that I'm missing?

**Comment by daviditen** [comment]
Most of the file is still valid as it's talking about associative domain set operations which we still have. You're right that the last section which is about arrays should have been deleted though. It at least says that it's deprecated and shouldn't be used going forward.

**Comment by bradcray** [comment]
Ah, OK, I was reading way too fast then.  Would you mind deleting the deprecated stuff?  Thanks.

**Comment by daviditen** [comment]
Yes, I'll open a PR to remove it.

**Comment by daviditen** [comment]
https://github.com/chapel-lang/chapel/pull/18439 removes the wording about arrays.

**Comment by bradcray** [comment]
Thanks!

**Pull request merged**
