### PR TITLE
Refactor sparse bulk addition operations to comply new Sort module

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR changes some formal argument names and function calls, in dsiBulkAdd
and related functions.

isSorted -> isIndsSorted   (to avoid confusion/clashes with isSorted in Sort.chpl)
isUnique -> isIndsUnique (to conform with isIndsSorted)

### CODE REVIEW

**Comment by e-kayrakli** [comment]
@mppf -- and anyone who is interested, are you OK with new argument names?

**Comment by mppf** [comment]
@e-kayrakli - I like the old argument names better. Is there some specific code pattern that doesn't work? I generally don't think it's a problem if an argument has the same name as a function somewhere in the standard module.

**Comment by e-kayrakli** [comment]
@mppf yes. https://github.com/chapel-lang/chapel/pull/4007/files#diff-a0be501f0990849134d41079d80affd0R1517

**Comment by mppf** [comment]
That example doesn't require changing the names for the user-facing API - just renaming the argument to  proc __getActualInsertPts. Anyway, you should be able to use Sort.isSorted to indicate which version you want.

**Comment by e-kayrakli** [comment]
Both makes total sense, I should have thought more about it, I'll revert those back and only keep the calls to new functions in the Sort module(I'll probably do Sort.isSorted, to keep flag names consistent). I'll merge directly when I am done as it becomes something really small.

**Pull request merged**
