### PR TITLE
Fix some issues in chpl__serialViewIter

### PR DESCRIPTION
**Pull request by bradcray**
This addresses a few issues in this code that Engin pointed out in
https://github.com/Cray/chapel-private/issues/1904:

* It gets away from calling dom.chpl_intToIdx() because we don't
  want to have to provide this as a method on all non-DR domains

* Similarly, it changes away from using dom.intIdxType for similar
  reasons.

Most uses of these routines in this file are fine (I believe) because
they're calling the local DR version of the routines.  However, this
is a routine used across a lot of distinct domain map types, so it's
important that it use the standalone versions of the routines rather
than relying on the convenience methods.

Filed a test locking in Engin's original test and a second version of
it that I noticed would go down a different stridable path, revealing
new errors.

Resolves https://github.com/Cray/chapel-private/issues/1904

### CODE REVIEW

**Comment by bradcray** [comment]
@e-kayrakli : I still need to test this, but it seems to resolve https://github.com/Cray/chapel-private/issues/1904

**Review by e-kayrakli — APPROVED** [review]
Thanks!

**Comment by bradcray** [comment]
Just noting for myself that I've tested this for linux64 comm=none, gasnet, but am holding off on merging until LLVM testing quiets down (but @e-kayrakli, let me know if it'd be helpful to you to merge sooner).

**Comment by e-kayrakli** [comment]
No preference from me.

I'm only curious to see the optimization behavior with this PR for the code:

```chapel
use BlockDist;

var blockDom = newBlockDom(3..8);
var localArr: [1..10] int;

ref slice = localArr[blockDom];

forall i in slice.domain {        // I expect this to be a distributed loop
  slice[i] += 1;                  // but this shouldn't be a localAccess (?)
}

writeln(localArr);
```

Note that the test [`test/optimizations/autoLocalAccess/differentDistView.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/optimizations/autoLocalAccess/differentDistView.chpl) tests for a formerly-buggy behavior in the automatic local access optimization. But that test is for the opposite case: you have a distributed array that's sliced by a non-distributed domain. I believe https://github.com/chapel-lang/chapel/pull/17567 should have covered for this case, too.

I can test that on this PR. (In hindsight, this snippet would have been a good future)

**Pull request merged**
