### PR TITLE
Allow underscores in the number when casting from string to integral

### PR DESCRIPTION
**Pull request by daviditen**
In the string->int cast function in StringCasts.chpl clean up the string by
stripping leading and trailing whitespace, checking that it has only one word
and removing all underscores unless they're in the first position.

Add a test that ensures we can cast strings with underscores to all of the
integral types.  Add tests that ensure that a leading underscore is an error
and that having multiple words in the string is an error.  If we blindly
removed underscores from the whole string without checking for multiple
words first this last test wouldn't issue the expected error.

### CODE REVIEW

**Comment by ronawho** [comment]
Can you check the performance impact on test/types/string/cassella/cast-from-string.chpl? (and maybe add a some cases to that test that have underscores? 

This implementation adds stripping (which the runtime code was previously handling) and I think always creates 3 additional strings (str[1], str[2..], and the joined version of that.) If that has a noticeable performance impact I think we could wrap this logic inside a find for `_` so that we're not paying the performance hit except for cases that have underscores

**Comment by mppf** [comment]
@ronawho - do you know of tests that call this cast in a performance-sensitive way?

**Comment by ronawho** [comment]
> @ronawho - do you know of tests that call this cast in a performance-sensitive way?

test/types/string/cassella/cast-from-string.chpl, but that's a cast microbenchmark -- I don't think we have any real benchmarks that currently care about casting speed.

**Comment by dmk42** [comment]
I'd expect any performance sensitivity to be on importing large files of human-readable data.  In those cases, there probably won't be underscores in the numbers, so there wouldn't be any calls to the `replace()` method.

So, from what I can see, this won't cause performance degradation anyplace that matters.

**Comment by daviditen** [comment]
The performance impact on test/types/string/cassella/cast-from-string.chpl is pretty large, but putting the new code under a test if the string contains underscores mostly fixes it.

The int64 case went from ~1.7s on master to ~9.1s with this PR before my latest commit to ~1.8s with the newest commit.

**Comment by daviditen** [comment]
Thanks for looking @ronawho, @dmk42, @mppf.

**Pull request merged**
