### PR TITLE
Allow LLVM back end to work on 32-bit x86

### PR DESCRIPTION
**Pull request by dmk42**
When Clang tries to compile the Chapel runtime on 32-bit x86 with WARNINGS=1, it aborts because the keyword `register` is used in qthread.h, and that is deprecated in C++.  For 32-bit x86 as well as PowerPC, qthread.h uses the `register` keyword in its assembly-based code.

This change mirrors the following PR which has been submitted to Qthreads.
https://github.com/Qthreads/qthreads/pull/67
It deletes the `register` keyword in the Qthreads code, allowing it to compile with Clang, which also allows the LLVM back end to work on 32-bit x86.

### CODE REVIEW

**Comment by dmk42** [comment]
@gbtitus - Would you mind looking at this?  I don't know if it's possible to get rid of the register keyword in the long run; it looks like qthreads.h needs it and we'll have to live with it.

**Comment by gbtitus** [comment]
I would think that getting rid of the `register` storage class specifiers altogether shouldn't hurt anything, since as I understand it all they do is to hint to the compiler that the corresponding variables should be quick to access.  My print copy of C99 says: "The extent to which such suggestions are effective is implementation-defined."  And I'm pretty sure at least Cray CC ignores the `register` storage class entirely.  The situation might be different if any of the `register` declarations in `qthread.h` used the Gnu "extended 'asm' syntax", but it doesn't look like any of them do that.  They're just plain old local decls with the `register` storage class.

Having said all this, I'd also like to hear from @ronawho.

**Comment by dmk42** [comment]
From the point of view of the C standard, I agree.  However, the assembly stuff is a nonstandard extension and I had the impression that using the register storage class was part of the ABI for that.  If I'm wrong, then we can just have the Qthreads folks get rid of `register`.

**Comment by gbtitus** [comment]
Based on an admittedly fairly rapid perusal of the `info gcc` docs for the extended 'asm' feature, which I last used personally about 10 years ago, it appears that the `register` storage class specifiers would only have special effect if they were used with an actual register specifier, i.e. something along the lines of:

     register int *p1 asm ("r0") = ...;

But none of the decls with `register` storage class have that special `asm ("...")` syntax.

**Comment by dmk42** [comment]
That's good news.  If we can get the Qthreads folks to delete `register`, I can close this PR.

**Comment by dmk42** [comment]
BTW, apparently the meaning of `register` will change with C++17, which is why it's deprecated, so it's to their advantage to stop using it if they can.

**Comment by dmk42** [comment]
An alternate approach would be for us to delete the `register` keyword in qthread.h ourselves, so that the LLVM back end will work on 32-bit x86 while we wait for Qthreads to make the change.

**Comment by ronawho** [comment]
Any use of `register` that's not part of asm to implement register variables should be fair game to remove. Feel free to open an issue or a PR against qthreads (If you're going to PR I suggest removing all instances instead of those just in qthreads.h)

That said, we don't actually use any of the qthreads C++ code, so I'm fine with just silencing this warning since it shouldn't really impact us.

**Comment by dmk42** [comment]
I've submitted a PR to Qthreads:
https://github.com/Qthreads/qthreads/pull/67

It would be nice to have 32-bit support in time for the Chapel release.  Do either of you object if I merge this PR too?

**Comment by ronawho** [comment]
Works for me

**Comment by ronawho** [comment]
Alternatively we can just apply https://github.com/Qthreads/qthreads/pull/67 locally (we often have patches that aren't upstream yet.)

**Comment by dmk42** [comment]
@ronawho - I like that idea.  Is there a semi-automatic way to accomplish it or do I need to make the edits again locally?

**Comment by ronawho** [comment]
```
wget https://patch-diff.githubusercontent.com/raw/Qthreads/qthreads/pull/67.diff
git apply --directory=third-party/qthread/qthread-src/ 67.diff
# edit "Chapel modifications to Qthreads" in third-party/qthread/README
```

**Comment by dmk42** [comment]
Thanks!  I'm pushing the change.

**Pull request merged**
