### PR TITLE
Fix an overlapping memcpy in beautify.cpp

### PR DESCRIPTION
**Pull request by mppf**
When I was doing some debugging with the madness test, I
noticed that the #line numbers generated were wrong.

To reproduce:
  cd test/studies/madness/common/
  chpl test_mul.chpl --savec=tmp --cpp-lines
  view tmp/MRA.chpl - are the #lines using MRA.chpl or MRA.clpl?

I checked that build with:
  valgrind chpl test_mul.chpl  --savec=tmp --cpp-lines

which reported
  ... Source and destination overlap in strcpy ... beautify.cpp:218
So, I have replaced that strcpy with an equivalent memmove (when the
strings do not overlap). I verified that fixed the valgrind error and
that the #lines for MRA.chpl are no longer garbled.

### CODE REVIEW

**Comment by bradcray** [comment]
Good catch!  (particularly since the original issue was probably mine, though it looks like I may have inherited it from ZPL where it may or may not have been mine...).

Stylistically, I'd prefer not to keep the commented out old solution in the code, and to rely on the commit message combined with git blame for anyone who wants to know the history.  Otherwise, in the limit, all code that we rewrite will stick with us forever.

Is there a simple test we could add to prevent this from backsliding?  E.g., a short file with a short filename compiled with --savec -cpp-lines and a grep of the generated code?  (both Elliot and I have added such tests recently -- the main challenge was skipping the test for LLVM.  Mine was test/compflags/bradc/mungeUserIdents/ but you may go blind looking at my terrible Python...

**Comment by ronawho** [comment]
I've been wondering this for a while, but is there a reason we use a home grown beautifier?

It's clearly not a high priority item, which is why it always slips my mind. I'm guessing that there either weren't many when the project started, or it was just easy to use something form ZPL out of familiarity?

Before we stopped always beautifying the generated code, I was looking into alternatives (since beautify was slow) The most promising one I found was astyle (http://astyle.sourceforge.net/) 

It turns out that at least for a simple hello the two were about equal in terms of speed (astyle is fast for incremental formatting, but takes a little longer for the first formatting.)

With that in mind, I figured it wasn't worth bringing up since there didn't seem like much a benefit to changing, but I'm now wondering if we think there could be other latent bugs like this hidden in beautify.cpp?

**Comment by mppf** [comment]
Hmm.. I'm a little worried that integrating astyle will be difficult and/or there will be some special Chapel-specific things that beautify.cpp does that astyle wouldn't. My vote would be to leave beautify alone for the moment, until such time as it needs significant development effort (new features, design problems, refactoring) and then make a decision.

**Comment by mppf** [comment]
I added a bunch of tests, but note that only use_MRA and use_abc fail without this fix. But I don't see the problem on my Mac either, and how strcpy is implemented and will fail in cases like this is platform-dependent. So I have a bunch of tests.... Depending on the philosophy of the test system I could put fewer.

**Comment by bradcray** [comment]
I don't think there is any deep reason we use our own home-grown beautify.  It is something that was just brought over from ZPL without much thought put into it.  And for the most part, I've taken a "not broken/don't fix" attitude towards it given how few issues I think we've had with it (until now).  But I'm not philosophically opposed to switching either, just wouldn't consider it a priority without good motivation (better performance or plagued by instabilities).

**Comment by bradcray** [comment]
I haven't reviewed the tests, but also don't feel the need to unless you'd like me to.  I.e., I think this is good to merge.

**Comment by mppf** [comment]
Passed full (local) testing, merging

**Pull request merged**
