### PR TITLE
Remove deprecated range.stridable, range.boundedType, BoundedRangeType

### PR DESCRIPTION
**Pull request by vasslitvinov**
These features were deprecated in 1.31 as follows:

range.`boundedType` and `BoundedRangeType` &nbsp; issue: #17126 &nbsp; implementation: #22059

range.`stridable` &nbsp; issue: #17131 &nbsp; implementation: #22441, #22486, #22508

This PR removes support for these features, which was added in the above PRs, and adjusts modules and tests accordingly.

More range/domain deprecated feature removals are next steps.

Testing: standard and gasnet paratests; distribution robustness suite as tested nightly: block, cyclic, replicated.

### CODE REVIEW

**Review by jabraham17 — APPROVED** [review]
Looks good!

**Comment by mppf** [comment]
@vasslitvinov - I think this PR should have removed this compiler code? Do you know if there is a reason it did not?

https://github.com/chapel-lang/chapel/blob/476c51c87fb2b2f3e82f0c8f58654345f6769d64/frontend/lib/resolution/scope-queries.cpp#L2115-L2137 ?

**Comment by vasslitvinov** [comment]
Good catch, thanks! I will look into it.

**Comment by vasslitvinov** [comment]
Removed in #24996.

**Pull request merged**
