### PR TITLE
Fix Spack deps getting 'module purge'd from common-cray-cs.bash

### PR DESCRIPTION
**Pull request by riftEmber**
For our perf tests, after sourcing `common.bash`, `common-cray-cs.bash` wipes out all modules and loads new ones. This worked fine previously, but with the Spackification, `common.bash` sources `setup-chpl-deps.bash` which loads all our Spack dependences using the module system. Those are now getting purged shortly after being loaded.

Commit 3fb64c90463b68a9d1cefaa365bd180f9ac03cba provides the reason this `module purge` is necessary. In future we should probably change it to remove specifically the modules we are concerned about. For the moment, this PR re-loads all the base dependencies after the `module purge`. To make this possible, loading base dependencies is separated out from `common.bash` into its own `load-base-deps.bash` script, `source`d by `common.bash`.

[reviewer info placeholder]

Testing:
- [x] manual run of a test using this script succeeds

### CODE REVIEW

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/commit/3fb64c90463b68a9d1cefaa365bd180f9ac03cba has context for why this was added

**Comment by riftEmber** [comment]
@ronawho I see, thanks for the reference. In future we should probably more specifically unload just the unwanted modules, but for now I will find another place to put this `module purge`. Looks like putting it at the top of `common.bash` puts it before any of our explicit `module load`s, so that's what I'll go with.

**Comment by ronawho** [comment]
I'm not sure we want to purge on all platforms. Just on the Cray CS platforms

**Comment by riftEmber** [comment]
I will go for the safest solution of just re-loading our dependencies after the purge then, as I don't know what our module landscape looks like on different systems.

**Review by ronawho — APPROVED** [review]

**Pull request merged**
