### PR TITLE
Update LICENSE to describe when we use third-party/libfabric.

### PR DESCRIPTION
**Pull request by gbtitus**

### CODE REVIEW

**Comment by gbtitus** [comment]
@bradcray -- take a look?

**Comment by bradcray** [comment]
That looks good to me.  Unless... do we ever default to `CHPL_LIBFABRIC=libfabric`?

**Comment by gbtitus** [comment]
Actually, we do default to `CHPL_LIBFABRIC`, whenever `CHPL_COMM=ofi`.  Maybe I should just remove that 2nd clause?

**Comment by bradcray** [comment]
Or more accurately, maybe:

> only used when CHPL_COMM is 'ofi' and CHPL_LIBFABRIC is not 'system'?

**Comment by gbtitus** [comment]
Although, hmm, remember from yesterday's conversations that we don't document `CHPL_LIBFABRIC`?  Should we even mention its setting in `LICENSE`?

**Comment by bradcray** [comment]
Oh, I hadn't really thought about that.  If it's not user-facing then I think not mentioning it is fine.  Now I'm wondering though:  What caused us to make it not be user-facing (like jemalloc I guess) rather than not (like GMP, say)?

**Comment by gbtitus** [comment]
> What caused us to make it not be user-facing (like jemalloc I guess) rather than not (like GMP, say)?

@ronawho pointed out that the distinction between `system` and `libfabric` would never be meaningful or useful for regular users, and hardly ever even for developers.  I tend to agree.

**Comment by bradcray** [comment]
OK, thanks, let's not mention CHPL_LIBFABRIC here then.

**Comment by gbtitus** [comment]
OK to merge once that's changed?

**Comment by bradcray** [comment]
Yep, thanks!

**Pull request merged**
