### PR TITLE
Add CI to check for bad performance tests

### PR DESCRIPTION
**Pull request by jabraham17**
Adds a new CI check that runs some of the code in `start_test` that checks for bad performance test setup. Namely that there are no duplicates, that all `.graph` files and listed in a `*GRAPHFILES`, and that no `file` is listed in `*GRAPHFILES` that does not exist.

Resolves https://github.com/chapel-lang/chapel/issues/6422

[Reviewed by @e-kayrakli]

### CODE REVIEW

**Review by e-kayrakli — APPROVED** [review]
Looks good! FWIW, I haven't read the code line by line assuming that it is copy/paste. If you have specific places for me to look at let me know.

**Comment by jabraham17** [comment]
> Looks good! FWIW, I haven't read the code line by line assuming that it is copy/paste. If you have specific places for me to look at let me know.

It should be for the most part. The new parts are `get_perf_labels` and `for perflabel in  perflabels`, and of course the updates to change it use to function arguments rather than globals

**Comment by bradcray** [comment]
Wow, nice!  I have to admit to being paranoid about adding new perf tests for this reason, and traditionally relied on @ronawho to be my CI.  :)

**Comment by ronawho** [comment]
Yay!

**Pull request merged**
