### PR TITLE
Fix bugs in binary IO

### PR DESCRIPTION
**Pull request by bradcray**
This fixes two bugs that I ran into in doing binary IO recently:

* the first fixes an issue in which reading/writing a 0-length array using readBinary()/writeBinary() resulted in problems

* the second fixes an issue I hit when writing a test for the first issue that wrote/read to/from stdout/stdin in which it would complain that the reader/writer was on a different locale than the channel for a CHPL_COMM=none run.  The fix I used was to compare locale IDs rather than locale values, though I'm not sure why that worked and fear it might be because I'm relying on something defaulting to 0...

While here, I also added a future showing that the `_home` field of stdin/stdout/stderr is not as it should be (https://github.com/chapel-lang/chapel/issues/23844).

### CODE REVIEW

**Comment by bradcray** [comment]
@jeremiah-corrado / @benharsh / @DanilaFe : Would one or more of you review this, as people who have worked on `writeBinary()` recently?  I'm not looking for a rubber stamp, particularly w.r.t. the second bullet in the OP which is disconcerting to me, though I'm also not sure what more to do about it.

**Comment by benharsh** [comment]
The code changes look fine to me, but I'd like to understand the locale issue better. Do you have a reproducer?

**Comment by bradcray** [comment]
Yeah, the test committed in this PR was what motivated that change.  Let me know if it doesn't reproduce for you on `main`...

**Comment by benharsh** [comment]
The issue appears to be that ``here`` for ``stdout`` is the "dummy locale" we set up temporarily at the beginning of time. I'm guessing this involves the order in which the IO module and its globals are initialized. We can see that by creating our own stdout in ``main`` that the locales are different:

```chpl
var myStdout = (new file(1)).writer();
writeln(myStdout._home == stdout._home);
```

I'm not exactly sure what to do about this, though. In the meantime, I think this PR is good to go.

**Review by benharsh — APPROVED** [review]

**Comment by bradcray** [comment]
Thanks for the explanation, Ben.  I figured it had something to do with bootstrapping at program startup, but had forgotten we even had a dummy locale.  I may look briefly into what it would take to replace the dummy locale before switching to user code before proceeding with this PR, since that would be a more satisfying change.  If you already happen to know where the logic lives that decides to use the dummy locale before `Locale[0]` is set up, that could save me some time getting my head around things.

**Comment by bradcray** [comment]
Interestingly, if I change that conditional to:

```chapel
} else if data.locale != this.locale {
```

It also seems to work, and this feels more principled and appropriate.  But I suppose the downside of that is that if someone makes an explicit copy of a fileReader/fileWriter, they could end up on a different locale than the one where the fileReader/Writer lives.  Admittedly, that makes me wonder whether we should either disallow copies of fileReader/fileWriter types (to avoid this) or make them wrap classes such that all computations could be relative to the singleton/unique class rather than needing to have this somewhat funky `_home` field...

**Comment by benharsh** [comment]
I think we've occasionally brought up the idea of allowing advanced users to override ``.locale`` and provide their own value, where the reader/writer channels were among the primary use-cases.

**Comment by bradcray** [comment]
@benharsh : I'm giving up on fixing the dummy locale issue for now and have filed https://github.com/chapel-lang/chapel/issues/23844 to capture the issue and some of my failed attempts to get it working.  I added a simple, standalone future showing that `_home` field is incorrect in stdin/stdout/stderr (in support of that issue) as well as a second version of my original test that doesn't rely on stdin/stdout (I'd originally thought I'd back out my workaround because it seemed so lame, but scanning the code, I'm not seeing other such cases that would require similar updates or lead to similar bugs, so figured the fix—though unsatisfying—was better than letting the bug stand.

Let me know if you have any concerns with my proceeding with this.

**Review by benharsh — APPROVED** [review]

**Pull request merged**
