### PR TITLE
Deprecate setsockopt in favor of set* methods

### PR DESCRIPTION
**Pull request by lydia-duncan**
In #12356, we decided to deprecate setsockopt in favor of individual
setter methods on Sockets, similar to the individual getter methods.

This change adds a deprecation compiler warning to the two versions
of setsockopt, and updates the documentation of setsockopt, LINGER,
SUBSCRIBE, and UNSUBSCRIBE to note the deprecation and link to the
new alternative (as the constants are irrelevant when they are baked
into the method name).  It also adds setSubscribe and setUnsubscribe,
the only two replacement methods that were missing.

I copied the original "weather" test from the ZMQ directory to
test/deprecated (due to its reliance on `setsockopt(ZMQ.SUBSCRIBE...)`)
and altered the original to use `setSubscribe` instead.

Full std paratest with futures passed
- [x] double check documentation build

### CODE REVIEW

**Comment by lydia-duncan** [comment]
http://web.us.cray.com/~lydia/zmqDeprecate/modules/packages/ZMQ.html#ZMQ.SUBSCRIBE is the start of my updates to the documentation

**Comment by lydia-duncan** [comment]
Going back to that part of the conversation, it isn't quite clear to me what you're asking for.  I think I interpreted the original comment as "a way to get the socket from the Chapel class so the user can call an extern version of zmq_setsockopt they define with it", and that seems possible to me today?

**Comment by mppf** [comment]
>  I think I interpreted the original comment as "a way to get the socket from the Chapel class so the user can call an extern version of zmq_setsockopt they define with it", and that seems possible to me today, albeit more work?

Yes, that's all I'm asking. I'm not familiar enough with the ZMQ module right now to know if that's already done or if it would be counter to some other design idea in it etc.

**Comment by lydia-duncan** [comment]
It's currently possible due to not having private fields.  The user will require some knowledge of the implementation of our Socket record in order to do it - our Socket record has a field of type SocketClass, which stores the C ZMQ representation of the socket.

I think our intention is to make that field private once that is possible, so we'll need to expose another way for users to do what you're describing in that eventual future.  I'll leave a note on the field to this effect so we don't forget about it.

**Comment by lydia-duncan** [comment]
I made a note to track this concern here: #13502

**Pull request merged**
