### PR TITLE
Quiet cygwin regressions

### PR DESCRIPTION
**Pull request by ronawho**
Cygwin started having several sporadic failures with a patch that improved
sync/single cleanup (5fe4ff78cfb5.) The main change from that patch is that
sync/single variable are actually being destroyed. For fifo, this means that
the mutex and condition variables used to implement the syncs/singles are now
being destroyed. For some reason the destruction of the condition variables
resulted in these sporadic regressions.

In an attempt to quiet some of the cygwin failures, the condvar destruction was
wrapped with a mutex lock/unlock and each condvar destroy was preceded by a
broadcast. This seemed to help cygwin a bit, however according to the man page:

"
It is safe to destroy an initialised condition variable upon which no threads
are currently blocked. Attempting to destroy a condition variable upon which
other threads are currently blocked results in undefined behavior.
"

This means that no other threads should be using the condition variable. It is
a bug if they are, so we shouldn't need the broadcast since there shouldn't be
any blocked threads and the mutex lock and unlock aren't needed because no
others threads should be executing this code concurrently. Based on that
reasoning, this patch removes the lock/unlock as well as the broadcast.

Getting rid of that code does make the situation worse for cygwin (more
timeouts/sporadic failures.) For now we simply leak condition variables under
cygwin. This should resolve all the current sporadic failures. While we're no
longer destroying the condition variables, we are still destroying the mutex so
we're still in a better state than prior to 5fe4ff78cfb5. Note that all
non-cygwin platforms do destroy the condition variables as well.

It's been difficult to track down the root cause of this issue. Since cygwin
isn't a high priority platform and we have a release coming, this is merely
meant to serve as a stopgap solution to quiet nightly testing and to improve
the situation for the release. I'll put all notes in a JIRA story to be picked
up for next release.

### CODE REVIEW

**Comment by ronawho** [comment]
@lydia-duncan mind reviewing?

**Comment by lydia-duncan** [comment]
Looks good!  I'm guessing you mean to update the JIRA story for the cygwin timeouts instead of making a new one?  I think it'd be good to keep all the information in one place.  Thanks for looking into this!

**Comment by ronawho** [comment]
Yeah, I'll update the existing JIRA issue.

FYI this resolves all the existing 32 and 64 bit cygwin regressions except for test_cholesky_performance

**Comment by lydia-duncan** [comment]
Should we suppress that failure/bump the timeout so that it is reliable in this commit?

**Comment by ronawho** [comment]
I was just going to ask that

**Comment by ronawho** [comment]
I was going to at least bump the timeout to get a consistent failure. I don't have a preference between letting it fail nightly vs suppressing it. Do you?

**Comment by lydia-duncan** [comment]
Not particularly.  On the one hand, I strongly feel the issue isn't our fault so would be inclined to suppress it. On the other hand, we don't *know* that for sure, so maybe we shouldn't

Bumping the timeout seems like a good plan, and I think is fine for this merge

**Comment by ronawho** [comment]
Added suppression. The timeout isn't needed since the suppression will suppress both failure modes and I'm pretty sure won't cause any nightly noise. 

I'll update the remaining jira issues next

**Pull request merged**
