### PR TITLE
Update re2 build to propagate errors during unpack process.

### PR DESCRIPTION
**Pull request by thomasvandoren**
Update the unpack script to fail if any of its commands fail. For systems without
patch, this will mean re2 will not be built and the error message about missing
patch will be more visible to the user.

Previously, systems without patch installed (often the case on *EL) would print
the missing patch program message, but continue building re2. This resulted
in a successful re2 build that was missing the `file_strings.{h,cc}` files provided
by the patch. The runtime would then fail to compile re2-interface.cc because it
could not find `FilePiece`, which is provided by file_strings.h.

### CODE REVIEW

**Comment by thomasvandoren** [comment]
I verified `make check` works on a CentOS 6 system with and with out `patch` installed.

**Comment by bradcray** [comment]
Not directly related to the pull request, but somewhat related:  In recent discussions (I think with @benharsh?), I thought we were thinking that re2 had passed the threshold of being worthwhile to keep releasing in a packed and patched form -- that we've got enough mods against it (and others queued up waiting to be implemented) that we should store it in unpacked form.  Would doing so fix this issue in a different way?  Thanks.

**Comment by thomasvandoren** [comment]
@bradcray - Yes, that would also fix the issue. We could merge this now, and do the unpacking later if it's not already in the works.

**Comment by thomasvandoren** [comment]
@benharsh or @gbtitus - will you please review?

**Comment by benharsh** [comment]
Looks good, feel free to merge.

**Pull request merged**
