### PR TITLE
Update submitted knucleotide versions to work with Chapel 2.3

### PR DESCRIPTION
**Pull request by bradcray**
This updates our local snapshots of our submitted knucleotide codes to reflect recent changes to the (now stable) Sort module.

- [x] This is currently in draft form, waiting for the updated codes to be accepted to the CLBG site

### CODE REVIEW

**Comment by bradcray** [comment]
@lydia-duncan : Can you check that these are the versions we should submit to the CLBG to keep it working with Chapel 2.3?

**Review by lydia-duncan — APPROVED** [review]
Yup, that looks right to me!  I think you'll probably want to remove the `.notest`s I put on them as well

**Comment by bradcray** [comment]
Oh, of course!  🤦   Thanks!

**Comment by bradcray** [comment]
CLBG site has been updated to new versions, though it may take awhile before their tarball of all sources reflects them (so clbg-diff.py may show a difference until then).  Merging these now, though, to resume getting perf testing on them.

**Pull request merged**
