### PR TITLE
Make Private_FFTW a private module

### PR DESCRIPTION
**Pull request by lydia-duncan**
Since modules can now be private, make this module
private (as that was its intention, though the feature was
missing before).

### CODE REVIEW

**Comment by bradcray** [comment]
This looks good, thanks.  Can the pragma "no docs" be removed now, or is that still work that needs to be completed?

While you're working on this file, would you do me the favor of renaming Private_FFTW to FFTW_Checks?  The "Private" wasn't really something I necessarily wanted to have be part of the name, and it'd be nice to be more precise now that the language can assert the submodule is private.

**Comment by lydia-duncan** [comment]
The pragma "no docs" can't be removed just yet, that's a next step.  I'll rename the module.  Thanks!

**Comment by lydia-duncan** [comment]
I've renamed the module and replaced all instances of the old name with the new one.  Testing now.

**Comment by lydia-duncan** [comment]
@bradcray, nothing surprising still?

**Pull request merged**
