### PR TITLE
mason-external SKIPIF should not test a specific hostname

### PR DESCRIPTION
**Pull request by awallace-cray**
Instead of testing the hostname of the test machine, use
/etc/os-release to infer if the test machine is running a
CentOS-like Linux.

Throw in tests on CHPL_HOST_PLATFORM and _COMPILER for
good measure.

Related to issue #10833 

Also:
- .gitignore all Mason.lock files from test/mason on down;
- git rm the four Mason.lock files already checked-in.

- The SKIPIF should also make sure mason external has been setup on this machine.

### CODE REVIEW

**Comment by awallace-cray** [comment]
@ben-albrecht @spartee 
Not sure how restricted this SKIPIF test must be. This SKIPIF works (ie does not skip) when run on either of our Centos7 VMs. I have not tested this SKIPIF on any other kind of build slave. Comments? 

I would prefer not to have hostnames in SKIPIF tests, but won't let that stop me from putting up the Jenkins job.

**Comment by awallace-cray** [comment]
2018-08-24 06:54 - As above, this is just a bit of volunteer cleanup. Hope I got it right. 
- .gitignore all Mason.lock files from test/mason on down; 
- git rm the four Mason.lock files already checked-in.

**Comment by awallace-cray** [comment]
@spartee 
If and when you get a chance, does this SKIPIF make sense, and is there any reason not to get rid of those Mason.locks? 
Thanks again! 
/Tony

**Comment by Spartee** [comment]
@awallace-cray This looks good to me. SKIPIF makes sense. As long as this skips everything but the VM's which it looks like it does, then I think we are good.

**Comment by awallace-cray** [comment]
I'm going to take that as "approved" -:
Thanks.

**Pull request merged**
