### PR TITLE
Always squash C warnings, not just when we ask for "more" warnings

### PR DESCRIPTION
**Pull request by bradcray**
[designed with @ronawho and @daviditen ]

David and I recently realized that, surprisingly, certain tests
(exercises/Mandelbrot/mandelbrot.chpl was a good example when compiled
with clang before his PR #4132 yesterday) would generate C-based
warnings when compiled by default (chpl foo.cpl) but not when compiled
with C warnings turned on (chpl --cc-warnings foo.chpl). This seems
completely counterintuitive.  

It turns out that the reason is that we only throw certain -Wno* flags 
when --cc-warnings is requested, the historical rationale (presumably)
being  that we turn on a bunch of warnings with -Wall, but then there
are some we need to turn back off based on the code we generate.  
It may be that some of these warning flags have gotten turned on by
default in newer versions of compilers, or that we've become more
sensitive to them over time.

In any case, it doesn't seem good to get more warnings with
--no-cc-warnings than with --cc-warnings...  Nor to have users running
into warnings that our testing (which always throws --cc-warnings)
doesn't reveal.

To that end, this commit refactors our Makefiles so that compiler
flags that are used to squash warnings in the generated code are
separated out into their own Makefile variable
(SQUASH_WARN_GEN_CFLAGS) which is always added to the 'cc' command
line regardless of whether or not --cc-warnings is used (and after
WARN_GEN_CFLAGS so that it continues to override any warnings that are
turned on there).

### CODE REVIEW

**Comment by bradcray** [comment]
@daviditen : Do you have time to review this today?  I've done manual checking of the compiler lines for the four compilers whose Makefiles I changed under --cc-warnings and --no-cc-warnings and am doing a full test + futures now.

**Comment by daviditen** [comment]
@bradcray OK, I'll review it.

**Comment by daviditen** [comment]
I think you should also remove test/types/complex/diten/cplx_re_dot_type.compopts since the test no longer issues warnings either way, so is fine to run without it.

The rest looks good.

**Comment by bradcray** [comment]
OK, thanks!

**Comment by ronawho** [comment]
@bradcray https://github.com/chapel-lang/chapel/blob/master/make/compiler/Makefile.cray-prgenv-cray#L19 didn't use WARN_GEN_CFLAGS so it was easy to miss, but I think that should be converted to using SQUASH_WARN_GEN_CFLAGS as well.

**Comment by bradcray** [comment]
It seems to me that this change isn't strictly necessary because (a) these flags are thrown on every compile already and (b) I don't think they need to follow flags that are added by WARN_GEN_CFLAGS.  I could see an argument for moving them over to SQUASH_WARN_GEN_CFLAGS in that that variable describes what they're doing (squashing warnings), but I'd like to argue for sitting on that change for now (personally, at least) on the argument that it's not necessary and refactoring Makefiles is error-prone work that isn't as important as other things we're working on.

**Pull request merged**
