### PR TITLE
Improve --llvm compilation

### PR DESCRIPTION
**Pull request by mppf**
This PR improves the performance of code generated with the LLVM backend
and fixes one test that has historically failed with --llvm.

### Performance

I took a few minutes to experiment with the performance of the LLVM
backend, which Elliot had showed (quite some time ago) produced
significantly slower programs than the C backend for many simple tests,
such as 

     test/arrays/diten/time_array_vs_ddata.chpl

This PR makes a small change in order to improve the LLVM backend
performance.

It modifies the "link" step for --llvm compilation to pass the C
compilation optimization flags. This is important since the "link" step
for --llvm compilation is actually performing the code generation - the
input to that compilation call is all LLVM IR.

See the individual commit messages for a little more detail.

Future Work on LLVM Performance:
 * Address the suggestions here: http://llvm.org/releases/3.7.0/docs/Frontend/PerformanceTips.html
 * loop vectorization hints for forall/vectorizeOnly loops
 * improving type-based alias analysis metadata
   (use struct-path-aware TBAA)
 * indicating when a load is from a variable declared 'const'
   (see commit 6f0047ab7c90f456ab48f19ed59b58383a54e31f.
    This is tricky because during variable initialization, a
    const variable is mutable and could be read).
 * investigate enabling the Polly polyhedral optimizer
 * (for --llvm-wide-opt) change to struct wide pointers (vs. packed)

### Fixing a failing test

The test

    test/extern/kbrady/rename_extern_record.chpl

has historically failed when compiled with --llvm because of
three issues:
 1. it uses "struct stat" to name a C type, but the LLVM infrastructure
    did not know what to do with that
 2. during code generation, the type "stat" was colliding with the
    function "stat" and causing problems.
 3. during code generation, errors would occur if the last declaration
    describing a struct was a forward declaration, even if we previously
    encountered the full definition.

This PR fixes those problems my keeping track of both a type and a value
from the C AST we read.

Reviewed by @Kyle-B 
Passes release/examples extern/ferguson with --llvm

### CODE REVIEW

**Comment by mppf** [comment]
Passes test/extern/ferguson with and without LLVM. Before the extern changes, passed test/release/examples with --llvm.

**Comment by Kyle-B** [comment]
Looks good to me.

**Comment by ronawho** [comment]
@mppf just FYI Kyle and I added llvm perf testing so you can see the performance before and after this patch compared to regular perf testing:

http://chapel.sourceforge.net/perf/chapcs/llvm/

**Comment by mppf** [comment]
I'm going to wait to merge this until tomorrow morning, so we get one night of performance testing with LLVM and the new strings, but it's ready.

**Comment by mppf** [comment]
This patch provided some nice speedups. Note that we might not be generating TBAA metadata now - see the commented out call to codegenMetadata in symbol.cpp.

**Pull request merged**
