### PR TITLE
Updated chpldoc `usage` section to include `import`

### PR DESCRIPTION
**Pull request by souris-dev**
In order to include the `import` statement as well in the documentation for modules generated by chpldoc (issue #15327), I have made some modifications.
The import statement usage is shown in the generated docs in the following format:

``` chapel
import <Module name>.[symbol];
```
after the usual `use <Module name>` statement.
I found that only one file needs to be changed; please do tell me if other files need changes too (I am new to the code base).

### CODE REVIEW

**Comment by bradcray** [comment]
Hi @souris-dev — I suspect, but have not had the chance to verify yet, that the Travis failure above is because one or more of the tests in `test/chpldoc` are not working with your change, likely because they are sensitive to a specific output format, and that format has changed.  If that's right, we'll need to update the .good files to match the new output, but should get the output format reviewed before putting in too much effort there.  In the meantime, you should try running `util/start_test test/chpldoc` to see whether you see failures and understand how they will need to be updated once we're ready to lock in the new behavior.  Let me know if you have any questions.

**Comment by bradcray** [comment]
(I just checked out the branch and verified myself that those tests are failing for that reason... should be fairly easy to fix, though again, let's get the desired format right first and then update them).

Building the branch and docs and viewing them, I'm now thinking we should go even simpler with the import statement documentation.  Specifically, with a `use` statement in Chapel, it's possible to put things after the module name like `use M only foo;` or `use M except bar;` yet the module documentation has only had the simple form `use M;` (which is legal and reasonable).  Similarly, I think the section showing the import statement could say simply `import M;` since, as with `use`, more _could_ be added afterwards, yet nothing needs to be...  one could say `import M;` and then later `M.foo`.

Alternatively, I could imagine changing both of them to be of a more general form:

```chapel
use M[...];
```

and

```chapel
import M[...];
```

since either one could have nothing or something following it.  But I'm not sure that's really any clearer (someone truly naive in Chapel may think they needed to type the square brackets and dots), and I think anyone familiar with the language would be able to get from `use M;` or `import M;` to the more complex forms.

Going with either of these approaches also has the benefit of not needing to follow this section with the aside about what [symbol] is, which feels like it just puts off the actual interesting documentation for the module on every single module documentation page.

**Comment by souris-dev** [comment]
As you said, changing it to the general form `use M[...];` and `import M[...];` could make it confusing for someone really new to Chapel because of the square brackets and the dots.

The user can learn more about the extended versions of `use` and `import` if they want to by reading the appropriate primer or documentation page (for those keywords) by searching for them in case they need to learn more.

Hence, I think that keeping them both like this:
``` chapel
use M;
```
and
``` chapel
import M;
```
would be better.

Regarding the failure of the Travis build, I went up to the point of understanding that this was probably due to the test failing due to the need of the output to be in a specific format, but was unable to locate the test files properly that require updation. As you suggested, I'll try running `util/start_test test/chpldoc` and understand which ones need updation, and will ask for help if I need. Thanks!

**Comment by bradcray** [comment]
Sounds like we're in agreement, thanks!

**Comment by bradcray** [comment]
This is looking good to me, and I'm about to run a full test on it to ensure there are no surprises.  @lydia-duncan, any concerns?

Here's a screenshot of the current output:

Screen Shot 2020-04-06 at 11 44 47 AM

**Comment by lydia-duncan** [comment]
No concerns from me!

**Pull request merged**
