### PR TITLE
Switch perf playground to measure the impact of using RCU for privatization

### PR DESCRIPTION
**Pull request by ronawho**

### CODE REVIEW

**Comment by ronawho** [comment]
Yeah, it'll run your branch nightly and compare performance to master. It's single-locale only, so it won't test privatization overhead, but it will tell us if your code adds any significant overhead to task-spawning or other operations.

I can do multi-locale testing as well, but that's more manual. 

I was waiting for https://github.com/chapel-lang/chapel/pull/8182 to converge/settle-down before merging, but I can start testing tonight if you're ready.

**Comment by mppf** [comment]
@ronawho @LouisJenkinsCS - I think it'd be great to get it testing in the perf playground tonight. I havn't run a full local testing of it recently (though it did pass earlier and I think it's more likely an error would be discovered by the 10000 trials of test/distributions/privatization/runtime/ that I did... but you never know).

**Comment by mppf** [comment]
@LouisJenkinsCS - now that this PR is merged, we'll get performance graphs from each night. If you update your branch, the testing after that will reflect the change.

**Comment by ronawho** [comment]
Yeah, this just grabs whatever code is in your branch at ~11:45 PST and will test that against master.

**Comment by ronawho** [comment]
Results are up at https://chapel-lang.org/perf/chapcs/RCU-Privatization. There is only a single data point for your branch, but after tonight your branch will be represented with a dashed line, while master is solid. 

Unfortunately there are some non-trivial performance regressions, likely due to increased task-creation time:  https://chapel-lang.org/perf/chapcs/RCU-Privatization/?startdate=2018/01/30&enddate=2018/02/02&graphs=luleshrelease,minimdljsize10time,lcalsrawompshort,nasparallelbenchmarkscgtimingssizea,emptytaskspawntimings500000xmaxtaskpar,timetobuildtrees

All of these tests create a lot tasks (usually in a trial loop, not all at once.) I would start with "Empty Task Spawn Timings" which really just times something like:

```chpl
for 1..numTrials {
  coforall 1..here.maxTaskPar() {
    // do nothing, no-op
  } 
}
```

LCALS (especially the short problem size) is dominated by task spawning times. https://chapel-lang.org/releaseNotes/1.15/09-perf-opts.pdf details recent optimizations we did to task spawning and has more info on LCALS and the empty task-spawn test since they were what motivated the improvements.

**Comment by mppf** [comment]
start_test -performance does, and you can give it the path to the particular test you're interested in.

**Comment by ronawho** [comment]
This sort of "create tasks in a trial loop" is what LCALS does too (and improving LCALS was the motivation for adding the empty task spawn test)

https://github.com/chapel-lang/chapel/pull/4902 changed things so we would only put worker pthreads that are looking for new tasks to sleep after ~300,000 iterations through a loop. That's all inside qthreads-core though, so I don't think we'll want to make any mods or add any hooks there. 

Nothing immediately comes to mind for how you would cleanly get that sort of information, but I'll stew on it for a little

**Comment by ronawho** [comment]
>I already have a qthread_registerOnPark and qthread_registerOnUnpark hooks that are called, so I should be able to move the callbacks to being after spinning num_spins_before_condwait and if it works just add another environment variable to the Qthread library to allow fine-tuning.

The spinwaiting is inside qthreads-core though, not inside our qthreads shim, so you don't really have access to it.

>However, I'm gonna say that its messed up that a revolutionary language like Chapel has to bend over backwards for legacy applications written for another paradigm and memory model; it'd be like if C had to prove it had equivalent performance to assembly. I believe it'd be more efficient if our port of applications was less of an emulation of OMP and was more PGAS/Chapel appropriate.

I don't necessarily disagree, but fast task spawning speed is still important even for more idiomatic Chapel codes. Threre's also nothing about LCALS that's terribly un-idiomatic chapel. It uses direct array indexing, instead of iterating over arrays directly, but that doesn't change the task-spawning implications.

For spaces like ML/AI/whatever we don't have to be competitive with MPI/OpenMP, but the HPC space tends to care about performance above all else.

**Pull request merged**
