### PR TITLE
Draft spec changes for defer

### PR DESCRIPTION
**Pull request by mppf**
Spec changes to describe defer statements. Intended to merge after PR #6526.

Verified that new spec tests are passing.

Reviewed by @lydia-duncan - thanks!

- [x] full local testing

### CODE REVIEW

**Comment by mppf** [comment]
TODOs:
* describe what happens for iterators, loops
* "the in-scope defer and local variables" -> "the in-scope defer *statements" and *the* local variables ..
* don't talk about contents of a defer block
* get more review

**Comment by mppf** [comment]
@bradcray - would you be able to review these spec changes for defer? Thanks.

**Comment by bradcray** [comment]
Probably not this week.

**Comment by mppf** [comment]
@bradcray - a ping, hoping you can look at this spec change this week. thanks.

**Pull request merged**
