### PR TITLE
Documentation for Chapel on AWS EC2

### PR DESCRIPTION
**Pull request by ben-albrecht**
### Chapel on AWS EC2

Here is a step-by-step guide to launching Amazon Web Services (AWS) Elastic Compute Cloud (EC2) instances, configuring them for multilocale Chapel programs, and executing multilocale Chapel programs over them.

This also includes the option to use an pre-built Chapel-development Amazon Machine Image (AMI).

### In a future PR:

- Add link to actual AMI setup (when hosted)
- Copy AMI to other regions with links

### CODE REVIEW

**Comment by ronawho** [comment]
@bradcray if you time out looking at this, I'd be happy to review

**Comment by bradcray** [comment]
Have at it if you have time.  I can always give it a try later on.  I was as interested in using it to force myself to try AWS as anything.

**Comment by ronawho** [comment]
Looks good to me. I'm already familiar with running on AWS, so it's possible I missed things that somebody unfamiliar would have caught. 

Think this is good to be merged, and at some point @bradcray can offer additional feedback.

**Comment by bradcray** [comment]
I started to review this last night, but then didn't want to read the AWS user agreement (and felt that I should read it before using it for "work"), so gave up.

**Pull request merged**
