### PR TITLE
Python 3 support for build and test scripts

### PR DESCRIPTION
**Pull request by thomasvandoren**
* Upgrade virtualenv to latest version, which supports python 3.
* subprocess32 cannot be installed in python 3. Update makefile to only install for python 2.
* subprocess output is bytes() type in python 3. Convert output to utf-8 string before using when using python 3.
* print statement is removed in python 3, so use print function.
* execfile() no longer exists.
* file() no longer exists; use open() instead.
* dict .items() returns iterator now; convert to list before using.
* Octal ints must use 0o123 format in python 3, instead of 0123 form.
* xrange() no longer exists; use range() instead.

related issues: #8756, #8766

### CODE REVIEW

**Comment by thomasvandoren** [comment]
@ben-albrecht - will you please review?

**Comment by thomasvandoren** [comment]
Thanks @ben-albrecht ; this could definitely use more testing.

I only tested the default invocation of start_test in a few of the test/ directories on my mac (i.e. I didn't try with valgrind/perf/graph/etc configurations or run against the entire test/ tree).

**Comment by thomasvandoren** [comment]
@bradcray - do I need to sign a CLA? I can't remember whether or not I previously completed that...

**Comment by ben-albrecht** [comment]
> do I need to sign a CLA? I can't remember whether or not I previously completed that...

AFAIK, the one from 2015 is still good!

**Comment by bradcray** [comment]
Yeah, Ben's right that you're good.

**Comment by ben-albrecht** [comment]
Waiting on #9137, which is waiting on response from @thomasvandoren

**Comment by ronawho** [comment]
Generally speaking, this looks great to me. If you get a chance to rebase, that'd be awesome. 

Minor nits/questions (probably questions out of ignorance rather than anything else)
 - Do we need `from __future__ import print_function` for places where you're switching to use the print function?

 - I'm going to add some internal testing that will run the full suite with python3, but I'm wondering if we can add some travis testing too. I made some half-hearted attempts in https://github.com/chapel-lang/chapel/pull/10426 (tried out a bunch of different things with force-pushes, but I can't quite get that working.) I'll keep pushing on that but if you know how to do that off the top of your head let me know!

 - How did you find things to change? Were you just looking through the source and running tests, or is there some tool you were using?

 - Could you verify that the following work: 
   - `make check`
   - `make check-chpldoc`
   - `make docs`
   - `start_test test/release/examples/hello.chpl`

I will do testing on mac, linux64, and a cray as well for python2/3 once the conflicts are resolved. I'm flying out Friday night, so I won't be ale to keep an eye on testing over the weekend, but I'll be ready to do testing and merge anytime next week or later.

**Comment by ronawho** [comment]
Oh, and just FYI that we're still stuck supporting python 2.6 :(

CLE5 (based on sles11) still runs on XE's (with Titan and Blue Waters being 2 big/important systems still in service.) Most XC's are running CLE6 (based on sles12) so we at least get 2.7 there, but there are some sites on CLE5 for XC's too

**Comment by ronawho** [comment]
Hey @thomasvandoren do you have any interest in picking this back up, or would you like one of us to take it over?

**Comment by thomasvandoren** [comment]
I'm happy to have someone else take this over. Thanks!

**Comment by ronawho** [comment]
Are you sure? It'd be the perfect opportunity to stay in the current contributors for the 1.20 release ;)

More seriously, sounds good and thanks for getting us this far! I'll take it over and will hopefully have something by the end of next week.

Do you remember how you found what needed to change? Was this just running tests under python 3, or were you using some linter or other tool?

**Comment by thomasvandoren** [comment]
I would run start_test on incremental areas with python 3, identify an
issue, then try to find all the instances of that issue across the whole
codebase, rerun python 3, etc. I think that got start_test/sub_test in
pretty good shape.

My next step was going to be setting up a cluster with python 3 that could
run bigger sections of the tests in a shorter period of time.

Do we server(s) to run nightly or weekly testing against python 3?

If not, maybe we can figure that out sooner to help get this particular PR
over the line and to help ensure we have ongoing support for python 3.

**Comment by ronawho** [comment]
Closing in favor of https://github.com/chapel-lang/chapel/pull/11728 (I rebased, but your commits should still be attributed to you)

> Do we server(s) to run nightly or weekly testing against python 3?

> If not, maybe we can figure that out sooner to help get this particular PR over the line and to help ensure we have ongoing support for python 3.

Previously we only tested `make && make check` to verify that our core scripts were Python 3 compatible. With this we can extend what we test so https://github.com/chapel-lang/chapel/pull/11729 will run nightly with release/examples under Python 3. This will test start_test, chpldoc, and a majority of our python scripts.

Later (as part of https://github.com/chapel-lang/chapel/issues/7206) I'd also like to add a job that tests a matrix of python versions using pyenv or something.

**Pull request closed without merging**
