### PR TITLE
Update AUR packaging for 1.28.0

### PR DESCRIPTION
**Pull request by ghbrown**
This PR provides bumps to the packaging for Arch Linux's Arch User Repository.

Pretty standard change, the most important things is probably to look at the dependencies and see if anything should be added or subtracted.

Let me know if anything else is needed.

### CODE REVIEW

**Comment by mppf** [comment]
Thanks @ghbrown, this looks good to me. I compared the dependencies with the commands listed for Arch in https://chapel-lang.org/docs/usingchapel/prereqs.html#installation and it looks like the package has everything covered.

I think this is ready to merge but I'll wait to hear back from you before merging it.

**Comment by ghbrown** [comment]
Wow, it looks like the Linux install section has improved a lot. I haven't looked in a while but I seem to remember it having only a distribution or two, awesome!

Yes, I'm all good to merge, thanks.

**Comment by bradcray** [comment]
@ghbrown: A question about this series of PRs that I've been wondering about:  Is there any significant downside to having them lag the 1.28.0 release, not be included in the 1.28.0 tarball, not be part of the 1.28.0 tag?  Or, to put it another way, would there be benefit (to you, to users of the AUR package) in trying to get these PRs in just before a release is made rather than shortly after?  Thanks.

**Comment by ghbrown** [comment]
> A question about this series of PRs that I've been wondering about: Is there any significant downside to having them lag the 1.28.0 release, not be included in the 1.28.0 tarball, not be part of the 1.28.0 tag?

No real downsides that I know of besides the possible couple days that users will have to wait for me to update things if I'm off my game. Personally, I work off the package that tracks `main` (which only needs the version number updated for aesthetics).

>Or, to put it another way, would there be benefit (to you, to users of the AUR package) in trying to get these PRs in just before a release is made rather than shortly after?

I think that would be nice in theory, but since the package that tracks the fixed release needs checksums I'm not sure it would be possible (correct me if I'm wrong).

**Comment by mppf** [comment]
Of course these PRs aren't modifying actual AUR package (that is stored elsewhere) - we just have copies in this repo for reference/testing. If we wanted to, we could try to complete the AUR package update elsewhere at the same time as the release.

AFAIK, the checksum issue is also an issue for the Homebrew release formula we store in this repository (which is currently still pointing at 1.27, FWIW). But these checksums are for the tarball, which doesn't include these files, so it might be possible to get the 1.28 tag to have these updates, for example. (Actually, we could do that now, if we wanted).

**Comment by ghbrown** [comment]
> If we wanted to, we could try to complete the AUR package update elsewhere at the same time as the release.

I think you all had a packaging repo that was at least some sort of deprecated last time we talked about this. Is that the kind of thing you mean here?

> But these checksums are for the tarball, which doesn't include these files, so it might be possible to get the 1.28 tag to have these updates, for example.

Even if the checksum isn't dependent on itself (packaging not included in tarball), won't the checksum still need to be changed every time a release file is changed? I'm probably not understanding the workflow you all intend, but this sounds like it could be frustrating and would pin the AUR update to happen in a pretty tight window (just after all release files are finalized but before actual release). I'm sure you all are seeing a way around this, I'm just not sure what it is.

**Comment by mppf** [comment]
> I think you all had a packaging repo that was at least some sort of deprecated last time we talked about this. Is that the kind of thing you mean here?

I was talking about e.g. https://aur.archlinux.org/packages/chapel

> Even if the checksum isn't dependent on itself (packaging not included in tarball), won't the checksum still need to be changed every time a release file is changed? I'm probably not understanding the workflow you all intend, but this sounds like it could be frustrating and would pin the AUR update to happen in a pretty tight window (just after all release files are finalized but before actual release). I'm sure you all are seeing a way around this, I'm just not sure what it is.

That's right. It would either be a tight window or we would decide that we could update the git tag a while after the release for these (e.g., in theory, we could update it now).

**Comment by ghbrown** [comment]
Ah, I see. My habit for the last two releases has been to (as close as I can to the release date) update the repos on Arch's side, then copy the edited files to make a PR here right after. How would the timing on this change? I imagine I'd still need to wait for checksums and the tarball link to go live before I can update anything.

>It would either be a tight window or we would decide that we could update the git tag a while after the release for these (e.g., in theory, we could update it now).

Thanks for the clarification, I thought you were suggesting something much more complicated. I have no strong opinion on the tag, if it's easy enough to change I agree it makes more sense for these sort of PRs to be grouped with the version whose package they provide. I have no intuition for whether such a retroactive change would muck up historical record keeping, workflows on old releases (change the checksum if it's run by git tag), etc. so I'll defer to you.

**Comment by bradcray** [comment]
I'd prefer not to change the 1.28.0 release tag now (though I think Michael was just saying that as a hypothetical?) since it would introduce a difference between the tag and what's in the release tarball.  To me, it sounds like the two most likely things we'd do here are to continue on as we are, or to make this packaging part of our release process (which would probably mean us needing to take it over and adding it to our list of release tasks to not put Gabriel in the hot seat every three months?).  In posing the question, I'm also not at all insistent on making any changes here; I just wanted to be sensitive to the potential for there being unspoken concerns or gripes with the current approach.  Since it sounds like there aren't, sticking with the status quo may be the best way to go.  If this became a pain-point over time, we could look more seriously on doing more here ourselves.

One other reason I asked about this is that I'm curious about https://github.com/chapel-lang/chapel/issues/19542 as a replacement for the now-quite-stale TIO site, and I saw a mention of Arch in their instructions for contributing (though in the context of a Docker image, so maybe there's no relation to this packaging effort?  I'm honestly not sure, being still quite Docker-ignorant).  If we ended up getting onto that site, and having these things lined up at release time would streamline our ability to keep it up-to-date, that could be an additional incentive for us to do more here.

**Comment by ghbrown** [comment]
I think staying as we are is probably easiest for everyone. I may be a few days late on the version bump, but it's really not so cumbersome.

 can imagine you all would need to involve VMs, testing, etc. for packaging to what most of you probably consider a "random" Linux distribution. I think this puts you on the hook for too much unrelated stuff, and in my eyes packaging stuff like this is community/user territory (logistically).

As for ATO, I spot checked some of the other languages in ATO and it seems quite a few of them use `pacman` (the "official" (not community) package manager) but haven't seen any that use `yay` (the helper for getting user-packaged stuff ready for `pacman`). 
Perhaps this is motivation for us to get Chapel elevated out of the AUR, which is probably a good play for optics anyway. Obviously lots of `curl`.

Even if you don't want to use `pacman` (for example cause it introduces extra complexity for a simple setup) I've hardly found a Dockerfile longer than 15 lines at the worst, so doing the `curl; ./configure; make; install` approach puts you in good company with many other languages. Even knowing nothing about Docker, getting Chapel on ATO *looks* really simple, so I say you go for it.

**Comment by bradcray** [comment]
> I may be a few days late on the version bump

There's definitely no need to rush or worry about it for our sake—we definitely appreciate the community help here.  If something comes up that changes our feelings, that'll be a good sign that we should take it on.

Thanks for the notes on ATO.  I've added a link to them from #19542 for future reference.

**Pull request merged**
