### PR TITLE
Add standalone version of dynamic() iterator

### PR DESCRIPTION
**Pull request by bradcray**
While talking with Tiago about parallel iterators in Chapel, I'd hoped
to show him a standalone version of the dynamic iterator as a familiar
example, but it turned out that we didn't have one.  This PR adds one
for the range version of dynamic().  In the future, we should consider
adding them for the domain version as well as for the other iterators
in this module.

While here, I also updated atomic variables to use initialization expressions
now that they support them (yay!!)

### CODE REVIEW

**Comment by cassella** [comment]
Won't this have a problem with strided ranges, since it doesn't do the `densify()/unDensify()` that the leader/follower do?

Answering my own question,

```chapel
use DynamicIters;

var r = 0..100 by 10;

forall i in dynamic(r, chunkSize=5) { }
```

```
fortytwo@magrathea:~/src/chapel ((d42e32a...))$ chpl -sdebugDynamicIters=true foo.chpl
fortytwo@magrathea:~/src/chapel ((d42e32a...))$ ./foo -nl 1
Standalone dynamic Iterator. Working at tid 0 with range 0..0 by 100 yielded as 0..4 by 10
Standalone dynamic Iterator. Working at tid 1 with range 1..0 yielded as 5..9 by 10 align 0
Standalone dynamic Iterator. Working at tid 0 with range 100..100 by 100 yielded as 10..14 by 10
Standalone dynamic Iterator. Working at tid 1 with range 1..0$CHPL_HOME/modules/internal/ChapelRange.chpl:963: error: halt reached - invoking orderToIndex on an integer 20 that is larger than the range's number of indices 11
 yielded as 15..19 by 10 align 0
Standalone dynamic Iterator. Working at tid 1 with range 1..0 yielded as 25..29 by 10 align 0
```

(I was aiming at the aspect of yielding one or zero elements at a time despite chunkSize=5.)

Invoking the leader the same way looks right,

```
Parallel dynamic Iterator. Working at tid 1 with range 0..40 by 10 yielded as 0..4
Parallel dynamic Iterator. Working at tid 0 with range 50..90 by 10 yielded as 5..9
Follower received range (0..4) ; shifting to 0..40 by 10
Follower received range (5..9) ; shifting to 50..90 by 10
Parallel dynamic Iterator. Working at tid 1 with range 100..100 by 10 yielded as 10..10
Follower received range (10..10) ; shifting to 100..100 by 10
```

**Comment by bradcray** [comment]
Wow, good catch Paul, thanks!  Have you ever considered being a tax auditor?  :)

I'd assumed that existing tests would keep me honest, but it seems not.  I've added more of an acid test along with my PR.  Want to check my work?

**Comment by cassella** [comment]
That looks good.

What I didn't get to testing was a range with negative stride, which also has problems.  It starts at `low` and goes downhill from there.  The leader's `densify()` seems to take care of that case too.

#14617 and #14618 hit the existing leader iterator as well as this one.

**Comment by cassella** [comment]
On further thought, since this standalone iterator doesn't do the `densify()` step, I think (but haven't tested) that unlike the leader it would be vulnerable to #14618 even on a range like `max(int) - 160 .. max(int) - 50` with a chunk size of 100.

**Comment by bradcray** [comment]
I'm closing this for the time being in favor of @cassella's PR #14628.  After that's merged, I'll hope to come back to this.

**Comment by cassella** [comment]
@bradcray do you want to take this up again?

**Pull request closed without merging**
