### PR TITLE
Qthreads: Adjust Fences To Fix Perf Regression

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This is a backport of https://github.com/sandialabs/qthreads/pull/269 from the development version of qthreads. It should hopefully resolve any performance regressions.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
@jabraham17 please confirm that this fixes things on your end too. Thanks!

**Comment by jabraham17** [comment]
Thanks so much! I'll check it out shortly

While I am doing that, would you mind updating `third-party/qthread/README` to include details of this patch?

**Comment by bradcray** [comment]
@insertinterestingnamehere : W.r.t. Jade's request, if you look through the history of the README, you'll see that we typically add a little blurb when our snapshot of Qthreads includes a patch, like the bug fix one that I believe we had up until upgrading to 1.20.

**Comment by jabraham17** [comment]
Comparing against the [nightly perf results](https://chapel-lang.org/perf/chapcs/?startdate=2024/06/16&enddate=today&graphs=threadringshootoutbenchmarkn50000000,timetobuildtrees), this patch restores performance for the threadring benchmark

However, I cannot validate that "Time to build trees" improves with this patch. With or without the patch, I consistently get 7.9s for Array-of-struct, which matches the current results in the nightly graphs.

**Comment by insertinterestingnamehere** [comment]
Interesting. Thanks for checking. I'll dig into the second benchmark too and see if I can make some sense of what's going on there.

**Comment by bradcray** [comment]
Belatedly: Thanks for the investigation and fix here, Ian!

**Comment by insertinterestingnamehere** [comment]
Of course!

**Review by jabraham17 — APPROVED** [review]

**Comment by jabraham17** [comment]
Just noting for the git history...offline on slack we concluded the continued regression with "Time to build trees" was both not very important for Chapel and very hardware dependent (on some x86 machines it performed better, on some there was no difference)

**Pull request merged**
