### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in CHANGES.md, spec procedures.rst,
ErrorBase.h, error-classes-list.cpp, InitResolver.cpp, topo-hwloc.c,
IO.chpl,

### CODE REVIEW

**Comment by cassella** [comment]
Please review:

* -[ ] @bradcray procedures.rst, CHANGES.md
* -[ ] @DanilaFe  error-classes-list.cpp, ErrorBase.h
* -[ ] @dlongnecke-cray  InitResolver.cpp
* -[ ] @jeremiah-corrado  IO.chpl
* -[ ] @jhh67  topo-hwloc.c

**Comment by cassella** [comment]
Compiles, but I don't know how to test the `error-classes-list.cpp` change.

**Review by jhh67 — APPROVED** [review]

**Comment by DanilaFe** [comment]
Somehow I'm always in these typo PRs 😄 thanks for spotting these!

**Comment by bradcray** [comment]
> Somehow I'm always in these typo PRs

Me too, but in my case it's because I like to see if Paul's still paying attention.  ;)

**Comment by dlongnecke-cray** [comment]
Thanks!

**Comment by cassella** [comment]
All the reviewers have approved, so this is ready to be merged.

**Comment by cassella** [comment]
Anyone want to merge this?

**Comment by DanilaFe** [comment]
Taking a look at testing and merging :)

**Pull request merged**
