### PR TITLE
Upgrade bundled llvm to 10.0.1

### PR DESCRIPTION
**Pull request by ronawho**
Upgrade to llvm 10. I do not expect significant performance changes from
this upgrade (there are no real changes in the single node playground)

llvm 10 added some matrix intrinsics, which may be worth looking at
for our native linear algebra work: https://github.com/Cray/chapel-private/issues/1274

Release notes: https://releases.llvm.org/10.0.0/docs/ReleaseNotes.html

Closes https://github.com/Cray/chapel-private/issues/1271

### CODE REVIEW

**Comment by ronawho** [comment]
Testing:
 - [x] std comm=none paratest with `--llvm`
 - [x] performance playground with `--llvm`

@mppf the ABI change looks a little odd to me (`i32`-> `i321`), but the results are the same for C/Chapel

@e-kayrakli I had to make a small mod to PRK-PIC. Just an FYI in case there's a better fix or something we could pull in from upstream.

**Comment by mppf** [comment]
> @mppf the ABI change looks a little odd to me (i32-> i321), but the results are the same for C/Chapel

We probably should update something in `test/llvm/abi/x86-64/PREDIFF ` and that's almost certainly the cause of this oddness. Anyway nothing to worry about w.r.t. upgrading LLVM versions though.

**Comment by e-kayrakli** [comment]
I am not sure what you have changed in PIC is legal. I expect unsigned long long to have a higher max value than a double's max, and so that line is probably causing a different random distribution.

What is the cause of the change? You can't divide a float by an `unsigned long long`?

FWIW, That line hasn't change upstream and I don't have an obvious alternative to whatever the problem is. (I am not sure how much this concerns me either)

**Comment by ronawho** [comment]
> I am not sure what you have changed in PIC is legal. I expect unsigned long long to have a higher max value than a double's max, and so that line is probably causing a different random distribution.

Before it was just implicitly casted to a double, and now it's explicit. I don't think I changed behavior (It's doing `1.0 / ULLONG_MAX` so at some point `ULLONG_MAX` had to be cast to a double.

> What is the cause of the change? You can't divide a float by an unsigned long long?

This was the warning:

```
random_draw.c:170:36: error: implicit conversion from 'unsigned long long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]
const double   rand_div    = 1.0/ULLONG_MAX;
```

**Pull request merged**
