### PR TITLE
Remove chpldev_refToString

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR removes `chpldev_refToString`.

It had a leaky implementation (see #14056) and we don't seem to use it anywhere.

This also removes all the tests (that I could find via standard, gasnet paratests and grepping) 
that tests this feature.

Test:
- [x] standard with -futures 
- [x] gasnet with -futures

### CODE REVIEW

**Comment by e-kayrakli** [comment]
As @cassella also [pointed out](https://github.com/chapel-lang/chapel/pull/14056#issuecomment-529724107), this should reduce leaks coming from strings. Specifically, I expect ~300bytes of reduction in the nightly memleak testing.

**Comment by bradcray** [comment]
@e-kayrakli: This looks fine to me to merge today.  It looks to me (with a really quick look) like the primitive used to implement it could be removed from the compiler as well, but let's tackle that in a separate PR (it'd be great to jump on it before forgetting and just make it a post-release PR... should only take 10 minutes or so + testing).

**Comment by e-kayrakli** [comment]
@bradcray -- thanks will do

**Comment by e-kayrakli** [comment]
@bradcray -- Looking at the source a bit more did you really mean to remove these: https://github.com/chapel-lang/chapel/blob/master/modules/internal/CPtr.chpl#L277-L284

I thought these are alternatives to what `chpldev_refToString` provides, and they are valuable debugging tools?

**Comment by bradcray** [comment]
Ah, I think you're right.  My look was too quick and focused more on the compiler than the module code.  I incorrectly believed chpldev_refToString() was the only use of that primitive within module code.

**Pull request merged**
