### PR TITLE
Remove old commented out code in clone_parameterized_primitive_methods

### PR DESCRIPTION
**Pull request by lydia-duncan**
This code has been commented out since 2009.  I don't think we'll go back to
needing it.

I looked at removing the uncommented complex portion, but that seems to
still be needed.

Verified that hello.chpl still built and ran.  Since the code is commented out,
I don't think further testing is necessary.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@bradcray - good to go?  The code was commented out in [this commit](https://github.com/chapel-lang/chapel/commit/633bf1ad4d71ccbb1ea0e3d29afc43c60af66070) and it seems reasonable to believe we won't go back to it to me.

**Comment by bradcray** [comment]
Did you get any further information on what happens if the complex case is removed as well?

**Comment by lydia-duncan** [comment]
It looks as if that code is currently still needed to allow the .re and .im methods to apply to all sizes of complexes without having to write them individually by hand.

**Comment by bradcray** [comment]
all two of them?  :)  Do you happen to know where those methods are defined?

**Comment by lydia-duncan** [comment]
Looks like ChapelBase.chpl: 515 through 538.  That seems to be the only place in the modules where chpl_anycomplex is used.

**Comment by lydia-duncan** [comment]
At least, a quick grepmod didn't find any others

**Comment by lydia-duncan** [comment]
Want me to stamp those into separate functions in this PR?

**Comment by lydia-duncan** [comment]
Or should I make David do it? :p

**Comment by bradcray** [comment]
I mostly haven't had any time to look at or think about this PR this week.  My main gut reaction is that if the uncommented code is useful, the commented code for ints may be useful someday as well;  OTOH, if the commented out code isn't something we think we want or will need, then perhaps we should get rid of the complex one as well.  I do think it would be useful to have @daviditen in the loop given his recent work with complexes.

**Comment by bradcray** [comment]
PS...  I'm assume that "proc complex(?w).re { ... }" wouldn't work for some reason (?)

**Comment by lydia-duncan** [comment]
Hmm, I haven't tried.  I would guess that support was more recent

**Comment by lydia-duncan** [comment]
I'm getting a syntax error on the ? symbol for "proc complex(?w).re { ... }" and "proc complex(?).re { ... }"

**Comment by daviditen** [comment]
It looks like support for generic 'integral' 'this' arguments is happening somewhere else (I haven't gone looking for where), but generic 'complex' is not similarly supported there.  I think it's nice to have a generic 'complex', even if we haven't made it an official thing yet, so I wouldn't want to rip it out entirely.  If you can move the support over to wherever 'integral' is handled you could remove clone_parameterized_primitive_methods() and keep the similar functionality together.

**Comment by daviditen** [comment]
If we had Brad's suggested syntax for the generic complex(?w) it would be fine with me to remove chpl_anycomplex.

**Comment by lydia-duncan** [comment]
A grepcomp for integral and dtIntegral didn't yield anything that looked like a better strategy to follow within the compiler.  There's a couple of methods defined over the integral type in the standard module Types.chpl, but nothing that looked completely basic, and there wasn't any specific runtime file.

Since there doesn't seem to be a good place to move it, and the strategy to modify it is not readily apparent, I don't think anything else should be added to this PR today.  It sounds like we want to leave the commented out code in until the complex case can also be commented out.  Is that a fair interpretation?  If so, I'll close this pull request.

**Comment by daviditen** [comment]
I think the place where integral is handled is in function resolution, where it instantiates the generic.  I tried adding a case for dtAnyComplex formals and is_complex_type actuals to canInstantiate() and removing the handling in clone_parameterized_primitive_methods(), and that appears to work.  I haven't done full testing, but my little test I wrote to look at this PR passes.

**Comment by lydia-duncan** [comment]
Crud, you're right.  Just re-looked at the function resolution line I had dismissed earlier - I guess I was looking for more significant code since the implementation in clone_parameterized_primitive_methods was a few lines and the one in function resolution was just a boolean check.  My bad, thanks for double checking me!

You added a line like this, right:
`if (formalType == dtAnyComplex && (is_complex_type(actualType)))
  return true;`

I can do full testing over that.  Thanks again and sorry for not thinking as deeply about it.

**Comment by daviditen** [comment]
Yes, the code you show is what I tried (plus or minus a character here or there).

Thanks for taking care of testing and finishing off the mod.

**Comment by lydia-duncan** [comment]
No problem.  Do you think I should merge this tonight if it passes testing, or wait until I get back, since I won't be able to check on Saturday?

**Comment by daviditen** [comment]
It seems pretty safe assuming it passes normal testing, but I see no real harm in waiting either.  I don't have a strong preference about it.  If you merge it and something catastrophic happens I can volunteer to revert it on Monday.

**Comment by lydia-duncan** [comment]
It does seem pretty safe, but it's also pretty non-essential so I think I'll wait rather than risk dumping this on your shoulders.  Thanks for the help!

**Pull request merged**
