### PR TITLE
Update genGraphs to no longer rely on CHPL_HOME.

### PR DESCRIPTION
**Pull request by thomasvandoren**
It uses options.testdir to find ANNOTATIONS.yaml, which was the last remaining
bit that relied on CHPL_HOME.

### CODE REVIEW

**Comment by thomasvandoren** [comment]
@ronawho -- will you please review/comment?

**Comment by ronawho** [comment]
I think you're right that gengraphs shouldn't be using CHPL_HOME. 

What do you think of your previous suggestion to just use a cdn for dygraphs, instead of this patch? That "solves" this by removing the copying that required chpl_home. https://github.com/chapel-lang/chapel/pull/1781

**Comment by ronawho** [comment]
Then the only other place we're using CHPL_HOME is https://github.com/thomasvandoren/chapel/blob/chpl-home-deps/util/test/genGraphs#L942-L947 

And I think that can just be replaced with 
```python
        if options.annotation_file != None:
            annotation_file = options.annotation_file
        else:
            annotation_file = os.path.join(options.testdir, 'ANNOTATIONS.yaml')
```

**Comment by thomasvandoren** [comment]
That works for me! I can make the change.

**Comment by ronawho** [comment]
Looks good

**Pull request merged**
