### PR TITLE
Default to qthreads+hwloc with CCE

### PR DESCRIPTION
**Pull request by ronawho**
CCE 8.4 added support for gnu style inline assembly, which means we can now
build qthreads with it. This patch updates chplenv to default to qthreads if
we're using a new enough CCE (or if the module is being used since we know the
module is built with a new enough version of CCE.)

#2496 was an attempt to default to qthreads w/o hwloc for cce since hwloc
didn't build. However, hwloc is needed to get the best performance out of
qthreads. 792d4b37663ae5016075dab8f1b3ab0b5529a60c allows us to build hwloc
with CCE so we can now enable qthreads+hwloc and get better performance. For
stream-ep on a CRAY-XC this takes us from 65 GB/s with fifo to 74 GB/s.

### CODE REVIEW

**Comment by ronawho** [comment]
@gbtitus mind reviewing?

**Comment by gbtitus** [comment]
This looks good to merge.  Clarifying: you're not doing the 'hwloc_cv_c_compiler_vendor=cray' thing mentioned in the commit description for now, right? You're instead going to seek to have CCE do its detection better?

**Comment by ronawho** [comment]
Correct, I'm not doing the `hwloc_cv_c_compiler_vendor=cray` thing. I just mentioned it because I thought I had needed it when I was trying with 1.10.1 and I thought it could be useful in the future.

And I think this was just a typo on your part, but the detection is in hwloc, it has nothing to do with CCE.

**Comment by gbtitus** [comment]
Ah.  Not a typo, exactly, more like a read-o.  I read the description paragraph way too fast and thought it affected how CCE did its act-like-gnu vs don't-act-like-gnu decision.

**Pull request merged**
