### PR TITLE
Remove some features deprecated ≥two releases ago

### PR DESCRIPTION
**Pull request by vasslitvinov**
Remove the following deprecated features,
shown here with the date and PR of deprecation:

* formals `needles`, `patterns` in string|bytes.find() et al. [2/24 #19222]
* formal `dotnl` in regex.compile() [2/23 #17191]
* method list.`indexOf`() [1/20 #19059]
* class `BadRegexpError` [3/3 #19308]
* fields regexMatch.`offset`,`size` [3/07 #19365]
* string|bytes.`search`(),`split(pattern)` et al. [4/29 #19622]
* channel.`match`() and some channel methods with `ref error` [3/23 #17448]
* formal `i` in domain.contains() et al. [1/24 #19075]
* operators `|` `&` `^` on rectangular domains [1/30 #19103]
* methods domain.`isSuper`(),`isSubset`() [1/30 #19104]
* functions `isRectangularDom`|Arr() et al. [Oct'2021 #18534]

Notes on removing channel.`match`() et al.

* I retained this method and avoided deprecation warnings upon calling it:
  `proc _channel.search(re:regex(?)):regexMatch`

  For that, I converted a deprecated public method that it uses
  to a non-deprecated private one.

* I moved `test/deprecated/regexp-rechan.chpl`
  back to `test/regex/ferguson/rechan.chpl`
  as it contains functionality not tested otherwise.

  For that, I converted calls to match() to calls to search()
  prepending "^" to the pattern they are matching for.
  This is what we expect users to do to adjust their codes.

  This changed the ending channel offset in some cases.
  I noted this in #20864.

Testing: standard and gasnet paratests with futures.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Looks like make_doc failed because there were some references to now deleted symbols

**Review by lydia-duncan — COMMENTED** [review]
Looks good, I'll take a look when the doc changes are pushed just in case

**Review by lydia-duncan — APPROVED** [review]
Assuming it passes make docs now, this looks good to me!

**Comment by vasslitvinov** [comment]
Follow-up item: should `match` be replaced with `startsWith?`

**Comment by vasslitvinov** [comment]
> remove the need for the ^ you added to the test files, right?

Yes. However, adding tests with `^` turned out a good question about channel ending position with `search()`. So we should keep both testing with `^` and with `startsWith`. Perhaps also add testing with `endsWith`, depending on what we have now.

**Comment by lydia-duncan** [comment]
Agreed, yeah

**Pull request merged**
