### PR TITLE
 replace pull_request with pull_request_target

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**

### CODE REVIEW

**Comment by bhavanijayakumaran** [comment]
Replaced pull_request with pull_request_target to resolve the failure seen in git-actions email work flow to read secrets.
For more details 
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Review by riftEmber — CHANGES_REQUESTED** [review]
I'm concerned this would allow someone to exfiltrate our email secrets by creating a pull request modifying `email.yml` to print the secrets, then closing it. Is there anything preventing this or another reason it's not a concern?

**Comment by bhavanijayakumaran** [comment]
> I'm concerned this would allow someone to exfiltrate our email secrets by creating a pull request modifying `email.yml` to print the secrets, then closing it. Is there anything preventing this or another reason it's not a concern?

The secrets does not have a password saved in it but only app key token which will only authorize git-hub actions to use the email server.
App key cannot be used to login to do any malicious activity. And we have 2FA enabled on it so the app key cannot be used on another app.

**Comment by bhavanijayakumaran** [comment]
Also, its worth noting that app password can be used by only one user. Since we are already using it, it cannot be used by another app/account.

**Review by riftEmber — APPROVED** [review]

**Pull request merged**
