### PR TITLE
Enable ldflags to stack like ccflags

### PR DESCRIPTION
**Pull request by mppf**
If you specify multiple --ccflags options, e.g.

    --ccflags -O1 --ccflags -O3

the C compiler will get the combination of the flags, e.g.

    -O1 -O3

This feature is useful when some compiler arguments come from
a package (or a script giving arguments needed to use a library e.g.).
This pattern happens a lot with 3rd party software. llvm-config
is an example that comes to mind. Since the arguments stack, a
user of a library can also add flags, e.g.

    chpl `library-get-compflags.sh` --ccflags -fPIC

will append to - but not replace - any ccflags from the script.

Generally speaking, we expect that a C compiler will handle several
options for the same thing, where the last takes precedence, e.g.

     -O1 -O3

is really the same as

     -O3

This PR updates --ldflags to receive the same treatment, and cleans up
--ccflags and --ldflags support so that they use a std::string instead of
a fixed length C string. It adds a test to verify this behavior of
ldflags.

Passed full local testing.
Reviewed by @ben-albrecht.

### CODE REVIEW

**Comment by bradcray** [comment]
This is not a review, but I'm wondering whether we need to say anything on the man page to document that while most flags override when specified more than once, these ones stack?

**Comment by ben-albrecht** [comment]
This is a review. The changes look good to me overall, barring the few minor comments below:

I second comment by @bradcray - It would be more user-friendly to distinguish compiler flags that stack vs. those that don't, in the man page and maybe the `chpl --help` output too.

Also - not specific to this PR, but do we expect these flags to override or stack with existing `CHPL_CC_FLAGS` / `CHPL_LD_FLAGS`? I would expect the former, but am curious if this has been tested before.

:+1: on the C --> C++ refactoring

**Comment by mppf** [comment]
@ben-albrecht, they stack with CHPL_CC_FLAGS rather than overriding.

**Comment by ben-albrecht** [comment]
@mppf Thanks for checking. Whether or not we are happy with that behavior is something that can be discussed outside the scope of this PR. I think this is good to merge.

**Pull request merged**
