### PR TITLE
Change to / instead of . to separate build/install subdirs

### PR DESCRIPTION
**Pull request by mppf**
See email thread "error building Chapel" on chapel-developers from Nov 23, 2016. A user was having trouble building Chapel on a system using e-cryptfs which has a smaller than usual maximum filename length. This problem was encountered once before by another user.

This PR adjusts printchplenv to use '/' instead of '.' to separate the configuration-subdirectory for build/ bin/ and lib/. It makes minor adjustments to get compiler/Makefile working with this change. It adjusts runtime/Makefile.help to use printchplenv --simple to generate a chplconfig file next to libchpl.a.

## bin/

Before this change, there was a .built-for file like this:

      bin/darwin/.built-for-darwin.clang.wide-struct.llvm-none

The bin/ directory does not get a chplconfig file, but the portion of the configuration used for the compiler can be read either from the path to the built-for file or its contents. For example:

      bin/darwin/.built-for/darwin/clang/wide-struct/llvm-none/built-for

contains

      darwin/clang/wide-struct/llvm-none

## lib/

Before this change, the lib directory was organized like this (for example):

      lib/darwin.clang.arch-native.loc-flat.comm-none.tasks-fifo.tmr-generic.unwind-none.mem-cstdlib.atomics-intrinsics.gmp-none.hwloc-none.re-none.wide-struct.fs-none/
           libchpl.a
           libchplmalloc.a
           main.o

Now it is:

    lib/darwin/clang/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-intrinsics/gmp-none/hwloc-none/re-none/wide-struct/fs-none/
           chplconfig
           libchpl.a
           libchplmalloc.a
           main.o

## build/

Before this change, the build/ directory is (for example):

      build/
           compiler/
                   darwin.clang.wide-struct.llvm-none/
                        AST/
                            .o and .d files
                         ....

           runtime/
                   darwin.clang.arch-native.loc-flat.comm-none.tasks-fifo.tmr-generic.unwind-none.mem-cstdlib.atomics-intrinsics.gmp-none.hwloc-none.re-none.wide-struct.fs-none/
                        include/
                          chpl-env-gen.h
                        src/
                           ....

Now it is e.g.

      build/
           compiler/
                   darwin/clang/wide-struct/llvm-none/
                        AST/
                            .o and .d files
                         ....

           runtime/
                   darwin/clang/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-intrinsics/gmp-none/hwloc-none/re-none/wide-struct/fs-none/
                        include/
                          chpl-env-gen.h
                        src/
                           ....

## Rationale
   
Historically, I was an advocate for the dot-separated build directories on the theory that it is easy to see which configurations have been built. However, that is now arguably easier with the command:

     find lib -name chplconfig

since these chplconfig files can then be used to set up the environment variables to match.

Reviewed by @ben-albrecht.
Verified that a clean GASNet build still runs hellos.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Looks good.

**Comment by bradcray** [comment]
I read this hoping to understand what the new structure of the lib/ and build/ directories is.  Would it be possible to illustrate this in the PR as clearly as for the bin/ directory?

For the bin/ directory, I'm not understanding the role of the '.built-for' part of the bin/ hierarchy and generally prefer avoiding the use of .dotfiles when possible.  The repetition of 'darwin' in that path also seems unfortunate.  Can we not just drop a chplconfig file into the bin/ directory that specifies the aspects of the environment that are important for the compiler?

**Comment by mppf** [comment]
@bradcray - I've updated the PR message to hopefully be clearer. Regarding the .built-for file, I was trying to make a minimal change to the logic using that file. There is probably a better way to do it, but I'm just trying to make a minimal change here to address the / vs . issue. I'd like to leave re-doing the .built-for business to another PR. In particular, the repetition you noticed was there before.

**Comment by bradcray** [comment]
OK, I'd forgotten that the .builtfor feature existed before and was thinking it was new in this PR.

I'm guessing/hoping that the repeated 'build/compiler/' directory in the "after" explanation for the build/ directory is a typo?

**Comment by mppf** [comment]
@bradcray - yes that was a typo, now fixed

**Comment by ben-albrecht** [comment]
Still looks good to me.

**Comment by lydia-duncan** [comment]
Are there going to be .gitignore updates required for this change similar to the ones Vass fixed last time we did a rearrangement?

**Comment by mppf** [comment]
I don't think so but let me know if you see one. This should be ignored by ignoring build/ lib/ and bin/ already.

**Pull request merged**
