### PR TITLE
Enable a notest'd MPI test

### PR DESCRIPTION
**Pull request by lydia-duncan**
In looking for extern array examples, I ran across this test, which looked mostly
ready to go but was in a NOTEST directory (due to being submitted before we
had a test setting for it).  Since we didn't otherwise test the functionality in it,
I decided to see what it would take to get it up and running - the
answer was not much!  I copied the execenv and skipif from the multilocale
mpi tests we already run, added a numlocales file since the test doesn't want to
run in a single locale setting, and fixed the .prediff and .good.  With these changes,
the test runs well, so I added it to the gasnet mpi test suite.

The other tests in this directory don't have expected output, so I will save them
for another day.

Verified that the test runs in the appropriate settings, and that the skipif fires
correctly.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Also, FYI @npadmana

**Comment by ben-albrecht** [comment]
These changes seem straightforward to me.

Continuing my campaign of #5599, I'd advocate for moving these tests into `library/packages/MPI` rather than adding this directory to testing, unless there is a good reason not to.

**Comment by lydia-duncan** [comment]
I wasn't sure with a quick glance whether the others were better suited for the multilocale directory or the general one, and figured we would come back to the NOTEST ones faster if they were in a directory with other tests that actually ran (so I didn't want to move test_mpi away from them)

**Comment by lydia-duncan** [comment]
But @npadmana likely has better insight into that

**Comment by lydia-duncan** [comment]
Going to merge now, but Nikhil should feel free to take a look post-merge :)

**Comment by npadmana** [comment]
@lydia-duncan --- thanks for doing this; this looks great!

**Comment by npadmana** [comment]
@lydia-duncan , @ben-albrecht -- I finally got a chance to do a little archaeology to remind myself where this test came from. This was an initial test suite that I had put together for the MPI module. I had started to move some of these tests into ``test/library/packages/MPI/multilocale``, but had never fully finished that move. 

An issue we might run into with the test suite is that it uses blocking MPI calls which is not recommended with ``qthreads``. We've built some wrappers for some of these blocking calls, but not for all (which is probably why I never fully finished migrating all the tests).

I think these should be fine, but we may run into a deadlock (but again, we might not).  

If you'd like, you might want to file a bug report on migrating all of these tests into the official MPI testing repository and assign me to it. We can then fully deprecate this directory....

**Comment by npadmana** [comment]
Final comment -- I think we need to update the skipifs to enforce fifo tasks when using gasnet+mpi, which can deadlock. Just as an aside, I can cause a deadlock on my laptop with gasnet+mpi+qthreads.

**Comment by lydia-duncan** [comment]
#9608 handles this for the test I re-enabled, but not yet for the test/library ones.

**Pull request merged**
