### PR TITLE
Throw -Wno-pointer-sign

### PR DESCRIPTION
**Pull request by benharsh**
This patch adds -Wno-pointer-sign to list of flags used to compile the generated C code. Some codes working with pointers to c_chars have seen warnings concerning the sign of pointers to chars. A true fix to this problem probably involves compiler work to emit C type names instead of Chapel type names.

### CODE REVIEW

**Comment by bradcray** [comment]
Will this cause us problems when using slightly older versions of gcc? (that may not support the flag).

**Comment by mppf** [comment]
Ben, have you tried this on intel, clang, and GCC?

I agree with Brad's concern. I think our Makeflies actually get the verison number of GCC, so you could put it in an if...

I'd believe clang has always had this flag, but the intel compiler probably didn't always.

**Comment by benharsh** [comment]
GCC appears to have had this flag since major version 4. I added a test for this in Makefile.gnu.

I haven't been able to get my hands on many versions of the intel compiler, but it looks like it's been supported since at least 13.x.

**Comment by benharsh** [comment]
OK'd offline by @bradcray and @mppf. Future work should involve testing with older versions of clang and intel.

**Pull request merged**
