### PR TITLE
Remove FI_DELIVERY_COMPLETE in message-order-fence mode

### PR DESCRIPTION
**Pull request by jhh67**
The Cassini-1 NIC does not support `FI_DELIVERY_COMPLETE` and specifying it can cause hangs. See Cray/chapel-private#1661 and Cray/chapel-private#6677 for details.

Signed-off-by: John H. Hartman <jhh67@users.noreply.github.com>

### CODE REVIEW

**Review by jabraham17 — COMMENTED** [review]
If FI_DELIVERY_COMPLETE is not supported on Cassini, should it only be turned off for that provider? 

Also can you add links to the PR message for the documentation where you found that FI_DELIVERY_COMPLETE is not supported on Cassini?

**Comment by jabraham17** [comment]
> Also can you add links to the PR message for the documentation where you found that FI_DELIVERY_COMPLETE is not supported on Cassini?

Nevermind, I see the issue you linked has some information for that

**Comment by jhh67** [comment]
It should probably be turned off only for the `cxi` provider, and an alternative mechanism used to force visibility, but I don't want to make a more complicated change this close to the release. I'd prefer to just back it out for now, and fix it correctly after the release.

**Comment by jabraham17** [comment]
Thats fine by me, can you open an issue for it so it doesn't get forgotten?

**Review by jabraham17 — APPROVED** [review]

**Pull request merged**
