### PR TITLE
Upgrade jemalloc from 4.2.0 to 4.2.1

### PR DESCRIPTION
**Pull request by ronawho**
4.2.1 is a bug-fix release. The bug fixes that we care about are:

 - "Fix bootstrapping issues for configurations that require allocation during
    tsd initialization (e.g. --disable-tls)."
    * This is part of what caused us to revert cstdlib with pgi with #3950

 - "Fix Valgrind regressions in calloc() and chunk_alloc_wrapper()."
    * This caused us to revert to using cstdlib for valgrind testing with #3932

This should allow us to use jemalloc with valgrind testing and try out jemalloc
with the pgi compiler again.

For the changelog see: https://github.com/jemalloc/jemalloc/releases/tag/4.2.1

### CODE REVIEW

**Comment by ronawho** [comment]
@gbtitus I'm probably going to commit this tonight after testing finishes, but if you wouldn't mind giving it a quick review post-commit, I'd appreciate it.

**Comment by gbtitus** [comment]
Looks good (caveat that there's a fair amount of code here I don't understand, but given the testing I think that's okay).   👍

**Comment by ronawho** [comment]
It's just a third-party update, I don't think you need to understand the code changes (I certainly don't know what most of them do)

**Comment by ronawho** [comment]
Closing for now. 4.2.1 didn't actually solve all the valgrind issues. I opened a PR upstream to fix the remaining valgrind issues, so I'll probably just wait to go to 4.2.2. directly

**Comment by ronawho** [comment]
Replaced with https://github.com/chapel-lang/chapel/pull/4147. We're still just upgrading to 4.2.1 since 4.2.2 won't be out for a while, so I'll apply upstream changes to fix the remaining valgrind and pgi issues manually

**Pull request closed without merging**
