### PR TITLE
Allow log messages from skipif: ignore all but last line of output

### PR DESCRIPTION
**Pull request by stonea**
Previously, we would "fail" a skipif if there was any output other than "True"/"False"/0/1, however it would be nice to print logging output from one of these files (for example: an explanation of why a test was skipped).

This change modifies our processing of `.skipif` and `SKIPIF` files so we ignore all output from `stdout` except for the last line.

See: https://github.com/Cray/chapel-private/issues/6103

I've run this through paratests and everything passes.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
(not reviewing, but by "everything passes", did you verify that the number of skipped tests was the same versus on main?)

**Comment by stonea** [comment]
> (not reviewing, but by "everything passes", did you verify that the number of skipped tests was the same versus on main?)

Yep. If I grep the logs (for a paratest of `main` and a paratest of this PR) for "Skipping" (we produce a message with that word for each .skipif and SKIPIF) and diff they're the same.

**Review by mppf — APPROVED** [review]
Looks good to me

**Comment by bradcray** [comment]
Thanks for picking this up, Andy!

**Pull request merged**
