### PR TITLE
Fix a bug with missing period in writef("###.", 1) …

### PR DESCRIPTION
**Pull request by mppf**
The ###. format is supposed to show a period after the
number. It does for floating point arguments but a bug
prevented it from doing so with integral ones.

Also add a test for this case.

### CODE REVIEW

**Comment by bradcray** [comment]
I'm probably not going to have time to give this the review it deserves today, though the expected behavior in the test looks good.  I'd propose extending the test to verify that ###. with a floating point argument still behaved as expected and consider it good if it did.  And/or asking someone else to review.

**Comment by mppf** [comment]
Passed test/io/ferguson

**Comment by bradcray** [comment]
OK, and it looks like poundpound.chpl has the case I was wondering about.  So, treating the code as a black-box, I'm OK with this going in.

**Comment by mppf** [comment]
Passed full local testing

**Pull request merged**
