### PR TITLE
Include release dates and reboot dates in perf graph arrays.

### PR DESCRIPTION
**Pull request by thomasvandoren**
* Add releaseDate attributes to all objects in perf branchInfo array.

* Add rebootDates array and note about auto-generating them using [Datejs][0].

[0]: https://cdnjs.com/libraries/datejs

### CODE REVIEW

**Comment by bradcray** [comment]
The release dates look right to me based on comparing to CHANGES.  I didn't check anything else, hoping that @ronawho would.

There were a few cases (1.01 and 1.02 I think?) where the release date looks to be before the branch date which is odd...  In those cases, we could make the branch dates == the release dates, though I also don't see any significant downside to leaving them as-is (they're only off by about 1 day, so you'd only likely realize if you were browsing the file or had both enabled).

**Comment by thomasvandoren** [comment]
What do you think about the 1.1.1 release? Should it be included in the list?

It happened about 3 months after 1.1 and 3 months before 1.2.

**Comment by bradcray** [comment]
Yeah, I'd include 1.1.1 but not 1.1.2 (which was a module rebuild only, I believe).  Not sure why we passed this over in the original draft... Maybe oversight or believed 1.1.1. was a module-only build as well (?).

**Comment by thomasvandoren** [comment]
There isn't a release branch for 1.1.1. It looks like there were some minor changes over 1.1 that were in the open source 1.1.1 tarball release, but it was also a module rebuild.

@ronawho, will it be OK to have an object in branchInfo that doesn't have a branchDate attribute?

**Comment by ronawho** [comment]
Yeah that should be ok, we can update the line drawing routine to be a no-op if the date wasn't provided. Can you add a note above markReleaseDates so I don't forget this when I rewrite it?

**Comment by ronawho** [comment]
Patch looks good to me. 

I think I would skip the nodejs solution for calculating reboot dates. It seems nice and elegant, but also easy to get wrong without noticing. I think it'd be simpler to just grab the dates until the 1.13 release manually and add them to the array so we don't have to think about it for at least a year

**Comment by thomasvandoren** [comment]
I'm not sure I agree that's a good reason not to use Datejs. Working with dates is hard to get right and has lots of edge cases, but it's also easy to fat-finger manual date entry in the list or look at a calendar wrong (e.g. enter the second or fourth Saturday by accident).

**Pull request merged**
