### PR TITLE
Upgrade jemalloc from 4.0.4 to 4.1.0

### PR DESCRIPTION
**Pull request by ronawho**
4.1.0 is "is primarily about optimizations, but it also incorporates a lot of
portability-motivated refactoring and enhancements."

For the changelog see: https://github.com/jemalloc/jemalloc/releases/tag/4.1.0

In my testing I saw a slight improvement for things like miniMD, array-as-vec
operations, nbody, and some other benchmarks that improved with the original
jemalloc switch.

Binary Trees (a benchmark that really measures allocator speed) show a ~10%
performance improvement from this change.

### CODE REVIEW

**Comment by ronawho** [comment]
@gbtitus mind reviewing?

I did full std and gasnet-fast paratests. Perf testing has been going on for a few days and can be seen at: http://chapel.sourceforge.net/perf/chapcs/jemalloc/?suite=performancetracking

**Comment by ronawho** [comment]
Oh, and I'm probably going to wait to merge this until the weekend when things are quiet

**Comment by gbtitus** [comment]
The change seems fine, and not much performance impact either way.  So, okay to merge.  But didn't Binary Trees actually slow down slightly, or am I looking at the wrong part of the graph?

**Comment by ronawho** [comment]
No [binary trees] (http://chapel.sourceforge.net/perf/chapcs/jemalloc/?graphs=binarytreesshootoutbenchmarkn20) got faster. The labels aren't great, but "jemalloc" is jemalloc 4.1.0 and "default" is 4.0.4. (Oh and binary trees reports execution time, so lower is better)

**Comment by gbtitus** [comment]
Ah, I was looking at the graph line for 'binary-trees (jemalloc)' and the change from 3/8 to 3/9, where there was a slight slowdown (6% or so). Never mind!

**Pull request merged**
