### PR TITLE
PRK Sparse Distributed

### PR DESCRIPTION
**Pull request by ben-albrecht**
This PR adds a distributed Sparse PRK to the shared-memory Sparse PRK, and refactors the code.

- Added distributed implementation (fused with shared kernel)
- Switched to 1-based indexing
- Encapsulated non-kernel code in functions
- Encapsulated domain-definitions in functions (to hide `if distributed` logic)
- Added documentation
- Performance testing added

### Performance-impacting changes

- `temp` for storing partial sums.

### TODO

- [x] Change vector-update to use block-like communication pattern (#6682).
- [ ] Report performance delta of shared-memory test before/after this PR
- [ ] multilocale performance testing
    - 16 locales
- [x] cleanup / void distribution definitions

### Future work
- Further investigate if `vector` is large enough to warrant updates in parallel
   - Update with `vector += vectorDom;`?
- Capture performance delta of iterating over a sparse vs. indexing into it in a separate set of tests

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Made changes and attempted to capture remaining ideas from @chapel-lang/perf-team in PR message.

FYI - @e-kayrakli

**Comment by e-kayrakli** [comment]
The way `vector` is handled seems different than it is in MPI1 version of the reference implementations. *If* MPI version to be followed, then the vector needs to be block-distributed and local copies need to be created/updated every iteration corresponding to the MPI_Allgather.

**Comment by bradcray** [comment]
> If MPI version to be followed, then the vector needs to be block-distributed

(Based on heresay), I thought the MPI version used a 1D distribution of the matrix which required the input vector to be replicated everywhere (all processors need all elements) and the output vector to be block-distributed.

> If MPI version to be followed then... the local copies need to be created/updated every iteration

I agree with this and thought the plan was to check with the PRK team to see what the constraints were.

**Comment by ben-albrecht** [comment]
> I agree with this and thought the plan was to check with the PRK team to see what the constraints were.

That's still the plan.

>> If MPI version to be followed, then the vector needs to be block-distributed

>(Based on heresay), I thought the MPI version used a 1D distribution of the matrix which required the input vector to be replicated everywhere (all processors need all elements) and the output vector to be block-distributed.

After talking to @e-kayrakli offline, I have a better understanding of what the reference version is doing: The `vector` *is* block-distributed in the reference version, each locale gathers a local copy of the full `vector` at the start of the kernel loop, trading update iterations for communication, when compared to our implementation.

I'll wait to hear from PRK team before proceeding.

**Comment by e-kayrakli** [comment]
To elaborate more:

All the ranks allocate enough space to store the whole `vector` (a la ReplicatedDist), but then ranks only initialize (which I strongly believe is buggy in MPI1 implementation) and update their share of it (a la Block). After they update, they do an in-place Allgather on `vector` (a la whole array assignment minus local memcpy).

It gets a bit confusing if you want to find a 1:1 understanding of what it does. Well, it is C+MPI, so it is bound to be confusing...

**Comment by ben-albrecht** [comment]
Even though this is close to being finished, I'm going to close the PR until I can set aside the time to wrap it up and merge.

**Pull request closed without merging**
