### PR TITLE
Remove ROCm 4 support

### PR DESCRIPTION
**Pull request by jabraham17**
After this PR Chapel will no longer support ROCm 4. Users relying on ROCm 4 will need to upgrade to a newer version

Testing:
- [x] Ensure that proper errors are thrown when trying to use ROCm 4
- [x] `start_test test/gpu/native` with ROCm 6, to ensure nothing was broken

[Reviewed by @ShreyasKhandekar]

### CODE REVIEW

**Comment by ShreyasKhandekar** [comment]
I think for CPU-as-device mode, we just call the Sort module's `sort`. We can remove the `chpl_gpu_can_sort` logic if you are sure it can be removed as well.

`parallelRadixSort` can be left as a study. Perhaps we should move out outside of the module to help with compile times, but that can be done in a subsequent PR.

**Comment by jabraham17** [comment]
What I am proposing is that we refactor `gpuSort` to use `chpl_gpu_can_sort` to decide whether to call a cub/hip sort or to call a `Sort.sort`. Otherwise removing `fallBackRadixSort` makes the logic in  `gpuSort` opaque (without digging into the internals of `chpl_gpu_can_sort` its hard to convince yourself that `gpuSort` will always "do something").

Maybe the simpler thing to do is just put a halt at the end of `gpuSort`, "if you get here somethings wrong"?

**Comment by jabraham17** [comment]
Yeah, `chpl_gpu_can_reduce` only returns false in the case that we are using cpu-as-device mode

I think I agree that this should be a follow up task, I will spin out an issue for cleaning up `chpl_gpu_can_reduce`, `chpl_gpu_can_sort`, and `fallBackRadixSort`

**Comment by e-kayrakli** [comment]
I mostly have a neutral-to-removal point of view. Note that `chpl_gpu_can_reduce` is also used in the runtime, but runtime already has the `GPU_RUNTIME_CPU` preprocessor constant for statically making those decisions that are currently based on `chpl_gpu_can_reduce`. Making decisions based on functions as opposed to macros are more appealing for code maintainability perspective, but I also see that they are a bit of an overkill.

**Comment by jabraham17** [comment]
>  Making decisions based on functions as opposed to macros are more appealing for code maintainability perspective, but I also see that they are a bit of an overkill.

Perhaps a best of both worlds here is to add a `chpl_gpu_is_real_gpu` and `chpl_gpu_impl_is_real_gpu`, which more directlty encodes the "new world" where all real gpus support reductions and sorting. And then that would replace the `CHPL_GPU==cpu` in the module code. The downside of course being that this no longer happens at compile time (`CHPL_GPU==cpu` in module code is param)

**Comment by e-kayrakli** [comment]
At a high level I personally don't have enough motivation for redesigning the interfaces here (though I know that I started it, and thanks for brainstorming further). This, to me, is a choice between removing code that feels like cruft in post-ROCm-4 world vs ignoring it until it becomes a problem. Gun to my head with the binary choice, I would remove it.

**Comment by jabraham17** [comment]
Given this, https://github.com/chapel-lang/chapel/pull/26090/commits/95db1edf412c5409683e617ea973f576cb801a8f removes `chpl_gpu_can_sort` and `chpl_gpu_can_reduce` entirely (along with `fallBackRadixSort`)

**Review by ShreyasKhandekar — APPROVED** [review]
Thanks for sticking with this and making these changes!

**Pull request merged**
