### PR TITLE
Unify read ahead/readahead spelling in CommDiagnostics.chpl and chpl-cache.c

### PR DESCRIPTION
**Pull request by cassella**
I tried to make the verb form 'read ahead' and use 'readahead' for the nouns/adjectives.

### CODE REVIEW

**Comment by cassella** [comment]
@thomasrolinger Does this seem like an improvement to you?  I may just be overthinking things.

**Comment by thomasrolinger** [comment]
@cassella looks good to me! Thanks for taking the time to consider it.

**Comment by cassella** [comment]
Thanks!  @mppf / @ronawho pinging you as reviewers / mergers of the code.

**Comment by mppf** [comment]
This is fine with me.

**Comment by ronawho** [comment]
Fine with me. @mppf I'll defer to you for merging.

**Pull request merged**
