### PR TITLE
Remove complex math function wrappers for LLVM 16+

### PR DESCRIPTION
**Pull request by jabraham17**
This PR removes the usage of clang complex math builtin wrappers. This was a workaround implemented in https://github.com/chapel-lang/chapel/pull/7070/ and https://github.com/chapel-lang/chapel/pull/11965 to achieve better performance with complex numbers. For some versions of LLVM, this difference is almost negligible. However, newer versions of LLVM (16+) can result in worse codegen because of these wrappers.

With LLVM 14 and 15, I observed a 2% slowdown (M1 Mac) when I just removed the wrappers. I consider this pretty negligible, but in the interest of not hurting performance this PR only removes the wrappers for LLVM 16+.

With LLVM 17, I observed a 30% improvement (M1 Mac) in the performance when I removed the wrappers. Without the wrappers, the performance is within 1-2% of previous LLVM versions using the wrappers.

Testing
- [x] paratest with LLVM 17
- [x] paratest with gasnet with LLVM 17

[Reviewed by @mppf]

### CODE REVIEW

**Review by mppf — APPROVED** [review]

**Comment by bradcray** [comment]
Oh wow!  Did this account for some of the perf slowdowns we were discussing briefly a week or two ago in the perf meeting?  (e.g., the complex version of mandelbrot?)

**Comment by jabraham17** [comment]
Yes, I expect that after this PR the regression seen in [`mandelbrot-complex`](https://chapel-lang.org/perf/chapcs/?startdate=2024/04/24&graphs=mandelbrotall) should go away.

**Comment by bradcray** [comment]
> With LLVM 14 and 15, I observed a 2% slowdown (M1 Mac) when I just removed the wrappers. I consider this pretty negligible, but in the interest of not hurting performance this PR only removes the wrappers for LLVM 16+.

FWIW, I'd definitely get behind removing the wrapping to keep the code simpler, as I don't think the performance difference you're quoting here is significant enough to warrant the complexity, particularly given that it's on older, unpreferred versions of LLVM.  I'm not advocating that this needs to be done now (not that I'd object to it), but at least wanted to note it in case someone finds their way back to this PR later, wondering if they can remove the wrappers.

**Comment by jabraham17** [comment]
I am fully onboard with just ripping the code out in general, this PR was just the more conservative approach.

**Pull request merged**
