### PR TITLE
SOME CHANGE IN README FILE

### PR DESCRIPTION
**Pull request by ravikr126**
some change in README

### CODE REVIEW

**Comment by e-kayrakli** [comment]
Hi @ravikr126 -- the changed file is an rst file and the changes you made will break the formatting. Why did you feel the need to make those changes?

**Comment by ravikr126** [comment]
> Hi @ravikr126 -- the changed file is an rst file and the changes you made will break the formatting. Why did you feel the need to make those changes?

Sorry I don't know how to contribute in open source. It my mistake.
I really want to contribute in open source but no one guide me .Please help me

**Comment by e-kayrakli** [comment]
To contribute Chapel check out:

  https://chapel-lang.org/contributing.html

The best way to communicate with the community (ask for help in day-to-day programming, discuss high-level project ideas) is our Gitter channel:

  https://gitter.im/chapel-lang/chapel

I am now closing this PR.

**Comment by ravikr126** [comment]
Thank you sir 😊

**Pull request closed without merging**
