### PR TITLE
Simplify version button for user experience; search engine optimization

### PR DESCRIPTION
**Pull request by bradcray**
While thinking and researching about how to have search engines stop pointing to our old versions of documents so much, I realized that a problem that our approach has taken is that all versions of the documentation point to all other versions and therefore no version stands out as being particularly more than anything else.  This happens because of the version button which points to all other versions of a document (when it exists).  But when you think of it, most people using the version button are likely to only want to jump to the latest version or the master version.  Geeks who really want to look at some other old version are probably very willing to hack URLs to get there.

So... this PR simplifies the version button to only include the latest and master versions in the hopes of driving more traffic to the latest version when search engines crawl the page.  While here, it also:

* adds a parenthetical to all old versions saying "(old version)" because it hasn't been clear that the color coding by itself has been sufficient
* puts the latest version above the master version
* changes the wording of the buttons slightly to include the word "version" and to describe the choices
* has the "latest" version point to the top-level documents rather than the version in the 1.17 subdirectory (say).

These changes seem to simplify both the script itself and the user experience.  Hopefully others will agree.

### CODE REVIEW

**Comment by bradcray** [comment]
@benharsh: Would you review?  Note that you can currently preview the experience live at chapel-lang.org for all versions other than the master version.

**Comment by bradcray** [comment]
Noting belatedly: I could skip adding the 1.17 and 1.18 choices to the menu when those versions are the ones currently being viewed.

**Comment by cassella** [comment]
In the description, you probably mean "... or the master version".

**Comment by ben-albrecht** [comment]
👍 on this change. In the longterm, I think it'd be valuable to re-introduce a way to access older versions beyond URL hacking, but that is certainly more harmful than helpful today.

> In the description, you probably mean "... or the master version".

Should have used `chplspell` @bradcray ! (fixed)

**Comment by bradcray** [comment]
@ben-albrecht : I was thinking of (eventually) adding some sort of "old documentation versions" link, perhaps unified with where we store old versions of the spec (i.e., generalize it to "archived documentation").  This would only provide one link back to each of the old versions, so should be much less harmful than a potential link per documentation page.

**Pull request merged**
