### PR TITLE
Add bug reports as future test cases

### PR DESCRIPTION
**Pull request by briangu**
Inner record constructor shouldn't need an outer param
Domain extraction syntax causes compiler failure
Count syntax doesn't preserve type
Const values are not locale agnostic (not replicated)

### CODE REVIEW

**Comment by mppf** [comment]
Hi @briangu, I'm happy to see this PR with bug reports, but we'd like it to work with the testing system. Can you add .good files containing the expected output for each test? E.g. domain_extraction.chpl does not create any output, so we should have an empty domain_extraction.good file.

**Comment by briangu** [comment]
sure, i'll add that.  I thought that if there was a .future, then a .good wasn't needed.

**Comment by mppf** [comment]
Hi @briangu, this pull request is still waiting for some .good files. Are you going to have a chance to add them? (otherwise... I could add them in another PR but I'd prefer it if you remain the author of the PR). Thanks.

**Comment by mppf** [comment]
Looks good, I'll merge it now. Thanks!

**Pull request merged**
