### PR TITLE
Backport Fix For Performance Regression in Qthreads 1.21

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This backports a performance fix to cover a regression from qthreads 1.21.
In particular it adds some platform-specialized assembly that controls processor behavior while busy waiting.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Corresponding patch upstream: https://github.com/sandialabs/qthreads/pull/309

**Review by jabraham17 — APPROVED** [review]
This patch looks good! If you can add this patch to `third-party/qthread/README` as well (like for https://github.com/chapel-lang/chapel/pull/25833) and add a PR message, I can get this merged to see how it affects nightly performance

**Comment by insertinterestingnamehere** [comment]
Sure, will do.

**Comment by insertinterestingnamehere** [comment]
Okay, I think I've added the necessary information now. Let me know if you need anything else. Thanks!

**Comment by insertinterestingnamehere** [comment]
Of course! I appreciate you letting me know something was wrong!

**Pull request merged**
