### PR TITLE
Fix a bug with the implementation of Treap's `kth` method

### PR DESCRIPTION
**Pull request by lydia-duncan**
The method was checking if the type of `AutoMath.e` was default initializable, not the element type used in the treap record.  I think this was a copy-paste error, other methods that perform this check actually have an argument named `e` that can be checked.

TODO:
- [x] test that demonstrated we were checking the wrong thing and now aren't any more

Passed a full paratest with futures

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@e-kayrakli - I was working on a PR to stop `e` from getting included by default in all programs and ran across this accidental usage.  Can you verify that the change I'm trying to make is correct?  I'm still planning on making a test of it, but figured I should double check before writing that so I make an accurate test

**Review by e-kayrakli — APPROVED** [review]
Ugh.. Thanks for fixing it.

**Comment by lydia-duncan** [comment]
Okay, Engin, I've added some tests.  I think the formatting for the error we generate is a little unfortunate and would be down for changing it while I'm here, but I suspect it's a problem for the errors for all the methods and updating all of them (and adding tests) seems like more than I'd like to take on right now.

**Review by e-kayrakli — APPROVED** [review]
I agree about the error message, but totally game with not fixing it here. Good to go!

**Pull request merged**
