### PR TITLE
Fix bug in parallel iteration over domains with non-natural alignment

### PR DESCRIPTION
**Pull request by bradcray**
Doru Popovici ‎sent me a buggy program today in which a parallel zippered iteration over an array/domain that had a non-natural alignment (such as the one in forallAlignedRange.chpl) did not generate the right indices.  It turned out that the follower for default rectangular domains (which is also used by arrays and everything that builds on defaultrectangular) completely ignored the alignment property of the domain's ranges which caused the error.

The fix is simply to replace the queries of .low/.high when translating the followThis argument into the follower's native coordinates with .alignedLow/.alignedHigh.

I was a little surprised that we didn't have any tests that ran afoul of this, but it turns out we did, it just had the wrong output in its .good file (at least, it seems that way to me... it's not a very simple test to understand).

### CODE REVIEW

**Comment by bradcray** [comment]
@vasslitvinov would be the most natural person to review this given his familiarity with the range code and the fact that it was his test whose output I had to update.

**Comment by vasslitvinov** [comment]
@bradcray is this a revenge? :) I am looking at it.

**Comment by bradcray** [comment]
Cool, thanks!

**Comment by vasslitvinov** [comment]
Looking at it, it feels like an acknowledgment of my foresight, not a revenge. :)

@bradcray I will email you some other test changes I'd like to go into this PR.

**Pull request merged**
