### PR TITLE
Stop heap allocating coforall index vars

### PR DESCRIPTION
**Pull request by mppf**
Removes logic in findHeapVarsAndRefs to heap allocate coforall index
variables. Instead, include coforall index variables in
insertAutoCopyDestroyForTaskArg.

Before this PR, programs yielding a domain to a coforall would leak the
domain. After this PR, the domain is freed.

     functions/deitz/iterators/test_coforall_iterator_yields_domains

is an example program that leaks less memory after this PR.

Additionally, this PR should remove 1 heap allocation per iteration of
every coforall loop.

Passed full local testing.
Passed test/release/examples with GASNet everything + fifo.
Passed test/release/examples with GASNet fast + qthreads.

Reviewed by @benharsh and @ronawho.

### CODE REVIEW

**Comment by mppf** [comment]
Failures in GASNet fast:
[Error matching program output for functions/deitz/iterators/test_coforall_iterator_yields_domains]
[Error matching program output for studies/hpcc/STREAMS/bradc/stream-block1dpar]
[Error matching program output for studies/hpcc/STREAMS/bradc/stream-block1dpar-arr]

**Comment by mppf** [comment]
Passed full local testing.

**Comment by mppf** [comment]
Verified that the failures I observed earlier with GASNet-fast are resolved.

**Comment by ronawho** [comment]
Looks good to me. I'm not 100% clear on the history of this code, but I think it's safe to stop heap allocating coforall index vars now that we support out of segments gets/puts

**Comment by benharsh** [comment]
This looks good to me as well, thanks Michael!

**Pull request merged**
