### PR TITLE
Implement a primitive for 'static variables'.

### PR DESCRIPTION
**Pull request by DanilaFe**
This was requested last week. The use case was initializing a lookup table: it should only be initialized once per function call, but logically it makes the most sense to make the variable be declared in function scope, and only initialize it when the function is first called (similar to C++ static variables). This PR implements this, by creating a primitive that extracts an expression into a "static variable", in actuality declared in module scope to survive past calls to the function.

A variable is "uninitialized at first" by creating a class-based container, and initializing a pointer to it to null. If the static variable's value is needed, the container is allocated and the pointer is properly set.

Runtime type information is unsupported because building an RTTI value potentially requires access to variables only visible inside the function, and not at the function's module scope. In my example, I use `c_array` due to its similarity to plain Chapel arrays, but lack of RTTI.

Example code:

```Chapel
use CTypes;

proc computeExpensiveTable(seed1: real, seed2: real) : c_array(real, 10000) {
    writeln("Computing an expensive table!");
    var toReturn: c_array(real, 10000);

    toReturn[0] = seed1;
    toReturn[1] = seed2;
    for i in 2..<10000 {
        toReturn[i] = toReturn[i-1] + toReturn[i-2];
    }

    return toReturn;
}

proc getNthElement(x: int): real {
    @functionStatic
    ref table = computeExpensiveTable(1, 1);
    return table[x];
}

writeln(getNthElement(0));
writeln(getNthElement(1));
writeln(getNthElement(2));
writeln(getNthElement(100));
writeln(getNthElement(101));
writeln(getNthElement(102));
```

Prints:

```
Computing an expensive table!
1.0
1.0
2.0
5.73148e+20
9.27373e+20
1.50052e+21
```

Reviewed by @benharsh -- thanks!

## Testing
- [x] paratest

### CODE REVIEW

**Comment by bradcray** [comment]
While I'm appreciative of this first step, I want to note that I'll continue to feel uneasy about it until we have a clear, scalable multi-locale story for it (since I don't think we can really claim victory until we do).

I'm curious whether this feature works in the case of a generic procedure as requested in https://github.com/chapel-lang/chapel/issues/12281, giving each instantiation its own local static.  I'm optimistically guessing "yes, it probably does" (and if that's the case, that means this PR offers benefits beyond the proposed workaround of using a module-scope variable for the static state).  If it does, adding a test (like the one in the issue's OP) to lock it in would be ideal.

In terms of code organization, I'd probably make this a package module until such time as we're ready to embrace it as a first-class language construct since adding it as an internal module that's not used anywhere yet will just increase compile-time for all programs, require updates to tests that track module initialization order, etc.

**Comment by DanilaFe** [comment]
> In terms of code organization, I'd probably make this a package module until such time as we're ready to embrace it as a first-class language construct since adding it as an internal module that's not used anywhere yet will just increase compile-time for all programs, require updates to tests that track module initialization order, etc.

Does this approach work despite the fact that there's a primitive (and compiler logic) that uses the new module?

**Comment by bradcray** [comment]
As far as I know it should?  The only reason I can think of that it might not would be if primitive calls within package modules resulted in warnings, where unstable warnings are probably the most likely scenario (but since the feature itself is unstable, that seems not so bad).

**Comment by bradcray** [comment]
> I'm curious whether this feature works in the case of a generic procedure as requested in https://github.com/chapel-lang/chapel/issues/12281, giving each instantiation its own local static. I'm optimistically guessing "yes, it probably does"

My curiosity got the better of me, so I tried the generic function case, but sadly it didn't work.  If I made the routine with the static non-generic, it worked.  Given the implementation strategy, I'd be curious how much it would take to get this working—based on my loose understanding of the approach, it seems like it ought to be fairly tractable(?).

```chapel
proc newInt() {
  var x: int;
  return x;
}

proc doIt(x: ?t) {
  ref xx = __primitive("static function var", newInt());
  xx += x;
  writeln("In ", t:string, ", version, xx is: ", xx);
}

var a: int(32) = 5;
var b: int(64) = 2;

doIt(a);
doIt(a);
doIt(b);
doIt(b);
doIt(a);
doIt(b);
```

**Comment by DanilaFe** [comment]
> I'd be curious how much it would take to get this working—based on my loose understanding of the approach, it seems like it ought to be fairly tractable(?).

Not much, it was an oversight on my part :) 

```diff
diff --git a/compiler/resolution/functionResolution.cpp b/compiler/resolution/functionResolution.cpp
index 437b20a573..0347842622 100644
--- a/compiler/resolution/functionResolution.cpp
+++ b/compiler/resolution/functionResolution.cpp
@@ -11359,6 +11359,8 @@ static void checkSpeciallyNamedMethods() {
 static void postResolveLiftStaticVars() {
   forv_Vec(CallExpr, call, gCallExprs) {
     if (call->isPrimitive(PRIM_STATIC_FUNCTION_VAR_WRAPPER)) {
+      if (!call->inTree()) continue;
+
       auto wrapperSym = toSymExpr(call->get(1))->symbol();
       auto initDummySym = toSymExpr(call->get(2))->symbol();
 
```

**Comment by bradcray** [comment]
Awesome!!!

**Pull request merged**
