### PR TITLE
Rename revcomp 8 to 9

### PR DESCRIPTION
**Pull request by bradcray**
For some reason, the CLBG site renamed our revcomp 8 version to 9, so this updates our version to reflect that and minimize confusion going forward.  That said, there is still the potential for some confusion because I didn't want to rename all our existing .dat files, nor to lose historical data, so I'm still using `revcomp8-submitted.dat` as the name of the data file even though the other files are all named revcomp9.*.  The key in the graph tries to not to this slightly by calling the version `(9, was 8)`

### CODE REVIEW

**Review by jabraham17 — APPROVED** [review]
The diff itself looks good to me, but I think you are going to need to update the backing perf data. Specifically renaming `revcomp8-submitted.dat` -> `revcomp9-submitted.dat`, otherwise the data is going to appear missing

**Comment by bradcray** [comment]
Oh shoot, that's true, huh?  Do you know whether that can be done via the github interface to avoid a full clone of the perf repo?

And to make sure I've got my facts straight: Failure to do so wouldn't break anything, we'd just lose the historical data, right?

**Comment by jabraham17** [comment]
>  Oh shoot, that's true, huh? Do you know whether that can be done via the github interface to avoid a full clone of the perf repo?

You probably need a full clone 😞 

> And to make sure I've got my facts straight: Failure to do so wouldn't break anything, we'd just lose the historical data, right?

I'm pretty sure we will just lose the historical data.....

**Comment by bradcray** [comment]
Looks like it is possible to rename files within the github web interface, but given the number of such .dat files across the repo, I'm not that keen on doing it.

I think probably the most expedient way to proceed here would be to retain the names of the .dat files, but do the other renamings, which seems like it should work fine.  Any thoughts on that?

**Comment by jabraham17** [comment]
While I think that will work for now, it will make things more confusing in the future

**Comment by bradcray** [comment]
Yeah, though people probably rarely dig through the .dat files manually…  And we can put a comment into the place that names the .dat file to at least provide breadcrumbs for why it's that way.

The only other alternative I'm considering right now is to not do the renaming at all, but I think that'd be more confusing for the more common actions of browsing the perf graphs, comparing to the CLBG versions, etc.

**Comment by bradcray** [comment]
@jabraham17 : With a new release, I'm reminded of this PR.  I just pushed a commit that keeps the .dat file as is, but updates the graph label to indicate the historical numbering of 8.  Thoughts?  (I don't think it's worth anyone's time—yours, mine, or others on the team to rename all the existing .dat files)

**Review by jabraham17 — APPROVED** [review]

**Pull request merged**
