### PR TITLE
Remove type select

### PR DESCRIPTION
**Pull request by sbillig**
Per the discussion on chapel-developers, type select is redundant.

`type select` is now a USR_FATAL error. I changed `type select x` to `select x.type` in the tests and the NewString module (i.e. I changed every instance of `type select` in the repo). I also removed the `type select` section from the chapel spec.

I ran the full test suite (on linux64); everything looks good.

There's a good chance that not everyone has seen the proposal yet, but it's probably safe to assume there won't be any opposition at this point. On the off chance that `type select` is deemed crucial, I'll revert these (fairly trivial) changes.

### CODE REVIEW

**Comment by sbillig** [comment]
It looks like Travis is failing on the smokeTest because the copyright year (2014) doesn't match the current year.

**Comment by thomasvandoren** [comment]
@sbillig -- I'm looking into the copyright year issue. Sorry for the inconvenience!

**Comment by thomasvandoren** [comment]
@sbillig -- Merging master should fix the copyright check.

**Comment by sbillig** [comment]
It did, thanks @thomasvandoren

**Comment by bradcray** [comment]
Hi Sean --  This generally looks good to me, thanks very much for taking it on!  

Two short questions:
1) What level of testing did you perform on it?
2) I assume the spec built without errors?  (I ask because there's a check that verifies that the syntax productions don't have any orphans or dangling references...)

And one slightly longer one:

3) I found myself wondering whether text should be added to the spec indicating that 'select' statements could take type expressions, equating it to conditionals on type expressions, imagining that the two things should be handled in the same place, but then (in a super-quick scan) couldn't find/remember where that would be.  Did you see any indications that this exists?  The closest I could find was the bit in the conditional section about param expressions (which is also thematically related).

If you did find a logical area to drop such text, would you do so?  If not, would you add an item to spec/TODO for both of these items?  Towards the bottom of the (poorly structured and sprawling) file, there's a capture of a longstanding idea to refactor all of the language concepts that are related to compile-time computation (of which both of these qualify) into a Chapter of its own -- but I believe we've never taken that on.

Thanks again!

**Comment by sbillig** [comment]
> 1) What level of testing did you perform on it?

I ran the full test suite, all is well there. I just committed a test covering the parse error, and one more on `select .type` in a type function.

> 2) I assume the spec built without errors?

It did.

> 3) [... spec ...]

I agree, it should be in there somewhere. As far as I can tell, there's no mention of conditionals on type expressions. I was considering adding a section covering this stuff to the chapter on Types, but a chapter on compile-time machinery is a good spot for it. I've added it to spec/TODO for now.

**Comment by bradcray** [comment]
Great, thanks Sean.  Sorry that I haven't had time to check myself:  Are the other items you removed from spec/TODO (in Expressions) things that you noted were already done?

**Comment by sbillig** [comment]
> Are the other items you removed from spec/TODO (in Expressions) things that you noted were already done?

Sorry, I should have mentioned that. They are; just doing a bit of cleanup.

**Comment by bradcray** [comment]
Thanks Sean.  I'll plan to merge later today or tomorrow as time permits.

**Comment by bradcray** [comment]
Deprecate 'type select x' in favor of 'select x.type'

[implemented by Sean Billig who is the "I" in the following]

Per the discussion on chapel-developers, type select is redundant.  

[Editor's note: See for example:
* [Chapel-developers] Type select on unions: http://sourceforge.net/p/chapel/mailman/message/33156198/
* [Chapel-developers] RFC: Removing the `type select` statement: http://sourceforge.net/p/chapel/mailman/message/33168499/
]

`type select` is now a USR_FATAL error. I changed `type select x` to `select x.type` in the tests and the NewString module (i.e. I changed every instance of `type select` in the repo). I also removed the `type select` section from the chapel spec.

I ran the full test suite (on linux64); everything looks good.

There's a good chance that not everyone has seen the proposal yet, but it's probably safe to assume there won't be any opposition at this point. On the off chance that `type select` is deemed crucial, I'll revert these (fairly trivial) changes.

**Comment by bradcray** [comment]
Hi @sbillig -- I ran into the parser rule for the deprecated 'type select' syntax today and wanted to see whether you'd like the fun of pulling out that support for the 1.12 release?  If not, I'm happy to take it or find someone else to.

**Pull request merged**
