### PR TITLE
Remove the mdBlk multi-ddata field for arrays.

### PR DESCRIPTION
**Pull request by gbtitus**
mdBlk is the ratio between the strides at the mdParDim'th dimension for
a reindexed alias and an original array.  We need it so we can compute
block and offset-within-block for multi-ddata using the reindexed
alias's indices when the blocking is in terms of the original's indices.
But with the arrival of the array views feature this ratio is no longer
needed for arrays themselves; it's only needed for array views.  Here,
remove it from the array descriptor, and also remove it from array
address calculations.

This makes 5-10% improvements in several of the 'LCALS (raw, long)'
performance results for linux64.

### CODE REVIEW

**Comment by gbtitus** [comment]
@benharsh, would you review this one, please?  Single-locale testing has already passed; multi-locale testing is in progress now.

**Comment by ben-albrecht** [comment]
@gbtitus 

>This makes 5-10% improvements in several of the 'LCALS (raw, long)'
performance results for linux64.

I'm having a hard time observing this claim in the [nightly perf-graphs](http://chapel.sourceforge.net/perf/chapcs/?startdate=2017/04/15&enddate=2017/04/26&graphs=lcalsrawshort,lcalsrawmedium,lcalsrawlong,lcalsrawompshort,lcalsrawompmedium,lcalsrawomplong), though it might just be lost in the noise... should we see this in a specific sub-lcal (e.g. `hydro_2d`)?

I checked [another machine](http://chapel.sourceforge.net/perf/chap04/?startdate=2017/04/15&enddate=2017/04/26&graphs=lcalsrawshort,lcalsrawmedium,lcalsrawlong,lcalsrawompshort,lcalsrawompmedium,lcalsrawomplong) as well.

**Comment by ben-albrecht** [comment]
That said, we did observe mostly positive performance deltas on several other tests: [link](http://chapel.sourceforge.net/perf/chapcs/?startdate=2017/04/15&enddate=2017/04/27&graphs=binarytreesshootoutbenchmarkn21,regexdnashootoutbenchmark,regexdnareduxshootoutbenchmark,nasparallelbenchmarkscgtimingssizea,arrayvsddataserialaccesses,emptytaskspawntimings500000xmaxtaskpar,stringtemporarycopies,searchesovernstrings)

I'm not aware of any other changes that went in on this day that would have affected performance.

**Comment by gbtitus** [comment]
This was a change to multi-ddata metadata in the array descriptor and as such would only affect locModel=numa.  See [here](http://chapel.sourceforge.net/perf/chapcs/numa/?startdate=2017/04/14&enddate=2017/04/27&configs=default,numa&graphs=lcalsrawlong).

**Pull request merged**
