### PR TITLE
Add a new environment variable to pass `--gpus-per-node` to slurm

### PR DESCRIPTION
**Pull request by e-kayrakli**
`--gpus-per-node` or the like are required to be able to use GPU nodes on some systems. I noticed this requirement on Perlmutter. However, we don't have the ability to pass that flag through the launcher executable we generate. This PR adds `CHPL_LAUNCHER_GPUS_PER_NODE` environment flag to add that ability.

### CODE REVIEW

**Review by jhh67 — APPROVED** [review]

**Comment by bradcray** [comment]
If using 2 co-locales on a node with 4 GPUs, would I set this environment variable to 4 (the number per node) or 2 (the number per co-locale/process)?

And: Should/could this feature be documented somewhere, like the GPU tech note?  (realizing that it's not alone in the category of undocumented launcher environment variables—https://github.com/chapel-lang/chapel/issues/20777).

**Comment by e-kayrakli** [comment]
> If using 2 co-locales on a node with 4 GPUs, would I set this environment variable to 4

I want to say 4 as this is just something we pass to slurm directly without us doing anything with the number. But that's a good point/question.

**Comment by bradcray** [comment]
@e-kayrakli : A curiosity while writing up CHANGES.md.  How does `--gpus-per-node` interact with co-locales?  (say I have nodes with 4 GPUs each and am running two co-locales per node?)

**Comment by jhh67** [comment]
`--gpus-per-node` is a `slurm` argument that specifies the "the  number  of GPUs required for the job on each node included in the job's resource allocation".  It prevents `slurm` from choosing nodes that have fewer than that number of GPUs. Once the Chapel job is running any co-locales will divvy up the GPUs on their node.

**Comment by bradcray** [comment]
OK, so in my example, I'd use '4' then, it sounds like?  (which is what I would've guessed, just wanted to make sure I had the right mental model).

**Comment by jhh67** [comment]
Yes, you would use '4' in your example.

**Pull request merged**
