### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in
scope-types.h, EnumType.cpp, chpldoc.cpp, symbol.h, convert-uast.cpp,
ChapelArray.chpl, ChapelRange.chpl, BigInteger, IO.chpl, ranges primer.

### CODE REVIEW

**Comment by cassella** [comment]
I don't know who to tag since I don't think any of these are ambiguous.

**Comment by lydia-duncan** [comment]
Tag the people that introduced the typos, even if it's obvious it was just a mistake.

**Comment by cassella** [comment]
Pings for typoe fix checks:

@bradcray - ranges primer, ChapelRange.chpl
@mppf - IO.chpl, convert-uast.cpp, symbol.h, scope-types.h
@jeremiah-corrado  - BigInt
@e-kayrakli  - ChapelArray
@arezaii - chpldoc.cpp
@DanilaFe - EnumType.cpp

**Comment by cassella** [comment]
In another issue @bradcray wrote

>  I'm sure Paul is still fixing spellchecking errors that I've introduced and that the CI hasn't caught me on

Indeed, two range-related ones here awaiting your review.  :)

**Comment by bradcray** [comment]
I finally got caught up enough to look at this.  My fixes look good (thanks Paul!), which is six thumbs-up.  So I think this is good to merge now?  Please confirm or tell me "no, not yet."

**Comment by cassella** [comment]
@bradcray I didn't have anything else in mind.

**Pull request merged**
