### PR TITLE
Fixing a segfault in the glob() iterator when it's a follower

### PR DESCRIPTION
**Pull request by bradcray**
[reviewed and code reviewed by @ronawho]

Due to an off-by-one error, the glob() iterator would sometimes
segfault when asked to be follow the range 0..0.  Specifically,
I was forgetting to take the 0-shifting of the followThis range
into account and so would think that it was OK to follow 0..0
(a 1-element range) when there were 0 matches on the glob() call.
This would then cause us to request the initial match, but there
weren't any, so a segfault would occur.  This would happen
nondeterministically when the number of tasks was greater than
10 when following the range 1..10 depending on whether the task
that owned 0..0 executed before or after another task that
would complain that there were not enough iterations.

While here, I updated the error message slightly to give more
information.

This is a second attempt at this issue -- the first was at
PR #2516

### CODE REVIEW

**Comment by bradcray** [comment]
Hi @ronawho -- trying this again from scratch to keep the changes more minimal, particularly in the testing system.  Clearly I should go eat lunch earlier and more often.

**Comment by ronawho** [comment]
Looks good! I doubt they'll be any, but I'll keep an eye for any regressions tomorrow. 

Oh, don't you want to revert https://github.com/chapel-lang/chapel/pull/2348?

Also feel free to update and close: https://chapel.atlassian.net/browse/CHAPEL-85

FYI: you could have reset your local branch, added this commit and force pushed to the old branch/pull request.

**Comment by bradcray** [comment]
Dur, yes.  (r: #2348).  Sigh...  I used to do so much better under pressure... (I  think?)

**Comment by ronawho** [comment]
:+1:

**Pull request merged**
