### PR TITLE
Demonstration: table support for HDF5

### PR DESCRIPTION
**Pull request by npadmana**
This demonstrates a prototype version for tables using HDF5. Currently, this is rather minimal -- providing simple routines to create and append to tables, and to read a subset of columns of a table.

The underlying record can have basic integer and real numeric types, as well as `c_array` types.

I've currently marked this directory NOTEST, since the current HDF5 module requires MPI (and I'm not sure the best way to set that up).

This addresses #14550.

### CODE REVIEW

**Comment by npadmana** [comment]
Thanks for looking this over. I'll add some documentation as soon as I can and will update the PR accordingly.

**Comment by ronawho** [comment]
Hey @npadmana, just checking in while trying to lower our open PR count. Do you mind either: 
 - adding docs
 - closing until there's time to add docs
 - asking us to merge as-is and docs can be added later

**Comment by ronawho** [comment]
(I'd also be in favor of moving these tests to `test/library/packages/HDF5/{htable, or whatever}` so that we have a single directory with hdf5 tests, instead of having to search when we want to run tests.)

**Comment by npadmana** [comment]
@ronawho, @daviditen -- I (finally!) just pushed over some documentation for this. Unfortunately, I had also rebased this branch, so the list of changes looks horrible. So I might just go ahead and create a new branch for this, with a more limited list of changes. Once I do this, I'll go ahead and close this....

**Comment by npadmana** [comment]
Closing in favor of  #14873.

**Pull request closed without merging**
