### PR TITLE
Add study: label propagation for tweets

### PR DESCRIPTION
**Pull request by mppf**
Label Propagation for Community Detection

see CUG’15 paper: Implementing a social-network analytics pipeline using
Spark on Urika XA

Computation consists of these steps:
* Read in gzip files storing JSON-encoded tweets
* Find pairs of Twitter users that @mention each other
* Construct a graph from such users
* Run a label propagation algorithm on that graph
* Output the community structure resulting from label propagation

New test passes.
Reviewed by @ben-albrecht.

### CODE REVIEW

**Comment by mppf** [comment]
@ben-albrecht, would you review this?

**Comment by ben-albrecht** [comment]
I think it would be valuable to include a concise README for this project, consisting of basically your PR message and some links to the actual paper / talk:

[paper](https://cug.org/proceedings/cug2015_proceedings/includes/files/pap158.pdf)
[talk](https://cug.org/proceedings/cug2015_proceedings/includes/files/pap158-file2.pdf)

**Comment by mppf** [comment]
I already had a README. I'll add the links to it.

**Comment by ben-albrecht** [comment]
(1) Add links to paper / talk in README (didn't catch the existing README earlier)
(2) Test ability of program to parse gzipped JSON files
(3) Test ability of program to parse JSON files with dummy fields that occur in real tweets

**Pull request merged**
