### PR TITLE
Create an `implementation` subdirectory in doc/rst/developer

### PR DESCRIPTION
**Pull request by vasslitvinov**
Organize a few notes in doc/rst/developer into a directory
with the common theme of "implementation details".

We could split it into "compiler implementation" and "runtime implementation",
however right now we do not need it.

While there, remove `internal-errors.rst`, as it does not seem valuable.

Discussed within the group.

### CODE REVIEW

**Comment by bradcray** [comment]
`internal` seems like a strange/ambiguous name to me (e.g., it suggests to me that it's internal to the organization).  `implementation/` or `impl/` seem more natural to me for a directory that's about implementation details (I think that's the common theme?).

**Comment by vasslitvinov** [comment]
@bradcray good suggestion, thank you. However - for your consideration:

I miswrote the directory name in the title - it should be `internals` (plural). How does this affect your thinking?

**Comment by bradcray** [comment]
`internals` still doesn't suggest `implementation` to me.  It makes me think of my guts and organs.

**Comment by vasslitvinov** [comment]
I changed the name to `implementation`, as Brad proposed.

**Pull request merged**
