### PR TITLE
Launchers should run "sbatch --version" without a temp. "command" file.

### PR DESCRIPTION
**Pull request by awallace-cray**
Using a temporary "command" file to execute "sbatch --version" was
unnecessary, and vulnerable to a variety of problems.

This changes the three launchers which did that to now run
"sbatch --version" directly, using popen().

   runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c
   runtime/src/launch/slurm-gasnetrun_ibv/launch-slurm-gasnetrun_ibv.c
   runtime/src/launch/slurm-srun/launch-slurm-srun.c

### CODE REVIEW

**Comment by ronawho** [comment]
Looking at what other launchers do (pbs-aprun/launch-pbs-aprun.c::determineQsubVersion()) I think we should be using `chpl_run_utility1K()` instead of manually doing popens

**Comment by awallace-cray** [comment]
Successfully tested the change in launch-slurm-srun.c, on a Cray with Slurm.

Tried to test the change in launch-slurm-gasnetrun_ibv.c, on a linux cluster w Slurm and Infiniband. Did not succeed - the launcher didn't seem to work, and I could not convince myself I was even getting the correct launcher, despite using the right config settings.

**Comment by awallace-cray** [comment]
I'm out of time for this.

**Comment by gbtitus** [comment]
I upvoted @ronawho recommendation to use `chpl_run_utility1K()` instead of manual `popen()`.

**Comment by awallace-cray** [comment]
Now I really have to stop.
The changes in launch-slurm-srun.c were successfully tested.
The changes in launch-slurm-gasnetrun_ibv.c were compiled, but Slurm / Infiniband and/or the launcher just would not work unless -N 1 and assigned node == the current node I was logged into.
The changes in launch-pbs-gasnetrun_ibv.c were not compiled.

**Comment by awallace-cray** [comment]
The changes in launch-slurm-gasnetrun_ibv.c have been successfully tested.
The changes in launch-pbs-gasnetrun_ibv.c were not compiled or tested, as I can't think of a machine here to test them on.

**Pull request closed without merging**
