### PR TITLE
Adjust error message format in multi-locale library codegen to be more useful

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
This is a small PR that adjusts the format of error messages in multi-locale library codegen so that they provide more useful information.

Currently, multi-locale libraries fail to compile due to an unsupported type. After implementing this quick adjustment, the new error message reveals...

```
$CHPL_HOME/modules/standard/IO.chpl:941: error: Multi-locale libraries do not support return type: syserr
```

Testing:

- [ ] `interop/C/multilocale` on `darwin` when `CHPL_COMM=gasnet`
- [ ] `interop/python/multilocale` on `darwin` when `CHPL_COMM=gasnet`

### CODE REVIEW

**Comment by lydia-duncan** [comment]
I'm assuming you've run test/interop/C/multilocale and test/interop/python/multilocale on OSx with this change?

**Comment by dlongnecke-cray** [comment]
I haven't. There's a bit of a chicken and the egg problem here. I updated the error messages in the compiler (this PR) so I could figure out why the tests were breaking (#13394). 

If you'd like, I can merge that fix first and then pull it into this branch.

**Comment by lydia-duncan** [comment]
You could always check out a version of master from before the change and see what this change does on that branch, just as a sanity check.

**Comment by dlongnecke-cray** [comment]
That sounds like a good idea, thanks!

**Comment by lydia-duncan** [comment]
I'd otherwise be in favor of merging this so it doesn't stay open, but recognizing that if there are failures because of it, they'll be spread across this branch and the fix branch.

**Comment by dlongnecke-cray** [comment]
Alternatively, why don't I just close this PR and integrate these changes into the fix branch?

**Comment by lydia-duncan** [comment]
Either way works

**Comment by dlongnecke-cray** [comment]
Closed in favor of #13403.

**Pull request closed without merging**
