### PR TITLE
Add a proposed array-of-T to T cast

### PR DESCRIPTION
**Pull request by bradcray**
This implements the idea proposed in https://github.com/chapel-lang/chapel/issues/23371 to support a general cast from array-of-T to T such that one can write this no-op style cast without having to define a T-to-T cast, which seems a bit silly.  The implementation uses an `in` intent such that if the array being cast is dead, it can be stolen.

### CODE REVIEW

**Comment by bradcray** [comment]
Interestingly, this breaks mason because it contains a cast from array-of-string to string, in which it wants the cast to stringify the array.  So probably we make an exception for that case?

**Comment by mppf** [comment]
> Interestingly, this breaks mason because it contains a cast from array-of-string to string, in which it wants the cast to stringify the array. So probably we make an exception for that case?

Looking back at [the stringify discussion](https://github.com/chapel-lang/chapel/issues/19893#issuecomment-1508627220) it looks to me like we chose to deprecate the universal cast to string. I see that for a record but with a quick experiment I don't see a warning for casting an array to a string.

Anyway, my own expectation is that we would:
 * deprecate the array-to-string cast for now (as a generalization of the decision in #19893)
 * adjust mason to use `"%?".format"` to do this operation
 * add an overload here for the cast of array-of-string to string to give an error with a hint to use `"%?".format"`

**Comment by bradcray** [comment]
> add an overload here for the cast of array-of-string to string to give an error with a hint to use "%?".format"

Note that, in the context of this PR and the issue that proposed it, the interpretation of casting an array-of-string to string would be that it's a logical no-op (i.e., it's a promoted identity cast operation).

I could imagine adding that hint for array-of-non-string to string casts, though?  Or making it a temporary compilerWarning for array-of-string to string saying that the behavior had changed.

**Review by dlongnecke-cray — COMMENTED** [review]
Looks good to me.

**Pull request merged**
