### PR TITLE
In comm=ofi, allow for providers that lack scalable endpoints.

### LINKED ISSUE #11180: spike: comm=ofi: what to do about the hobbled 'verbs' provider?
One of the questions asked after a recent demo of the ofi mockup had to do with the state of libfabric/ofi support on InfiniBand-based systems such as our chapcs cluster.  I answered that the ofi `verbs` provider is "famously hobbled" compared to a number of other providers.  ("Famously" because it is easy to find people griping about this on the internet.)  The question for this issue is what to do about the verbs provider's limitations.

See `man fi_verbs` for details about the verbs provider anywhere there is a libfabric install on an InfiniBand-based system, for example chapcs.  The following are some high points, though, compared to the sockets (TCP/IP), gni (Cray Gemini/Aries), psm (Intel PSM 1.x for Intel TrueScale Fabric), and psm2 (PSM 2.x interface for Intel Omni-Path Fabric) fabrics:
- Support for RMA (direct `PUT`/`GET`) is limited and requires application support for progress on the receive side, thus is not entirely one-sided.  The other providers all support RMA fully.
- There is full support for AM-style message send/receive but not for so-called multi-receive, in which a single receive operation can specify a buffer in which multiple messages will be laid down one after another, each with its own completion queue (CQ) event, and the receiver will be informed when the buffer is used up so that it can supply another one.  Instead, the receiver must do a receive operation for every incoming message, individually.  The other providers all support multi-receive.
- An "endpoint" in libfabric can be thought of as a addressable portal to network communication capabilities, and a "context" as a transmit or receive engine associated with an endpoint.  A "scalable endpoint" is an endpoint that can support multiple transmit or receive contexts which operate independently.  To manage concurrency and improve performance (higher rates and/or greater bandwidth) in multi-threaded programs one can either use multiple endpoints or a scalable endpoint with multiple contexts, but the coding style is different for these two approaches and the former uses more network addresses.  The sockets, gni, and psm2 providers support scalable endpoints but the psm and verbs providers do not.
- The verbs provider has more limitations on which libfabric memory registration models it supports, and places more requirements on applications, than do the sockets or gni providers or, seemingly, the psm and psm2 providers (though the latter 2 man pages don't mention memory registration, so it's a hard to be confident about this in regard to them).  While both sockets and gni have flaws that prevent production use (performance for sockets, thread scalability for gni) our hope has been that going forward the providers would get easier to work with in terms of memory registration.  The verbs provider seems a step backward in this respect.

As mentioned during the demo, the libfabric interface is such that at execution time, there is an initial back-and-forth negotiation regarding what capabilities the application wants or needs and what the provider can supply.  The result is that decisions with performance and even functional implications that might have been made at design time end up instead being made in the code, at execution time.  This has some performance effect, but more importantly the resulting branchiness just makes the code more complicated.  The number of limitations in the verbs provider's capabilities will maxmize this effect, since for performance we will still want to use the capabilities it is missing with providers that do supply them.

The extreme solution would be to code two separate ofi-based comm layers, one for the verbs provider and one for everything else.  Hopefully there is a less-extreme approach that will satisfy the functional requirements but not produce a tangle in the code.  The first step should be to take a more-detailed look at the verbs provider's limitations, how each would affect the comm layer code, and how each could be best be dealt with.

### PR DESCRIPTION
**Pull request by gbtitus**
The ofi comm layer was written to use a single scalable transmit
endpoint per node and multiple transmit contexts, ideally enough for
each worker thread and the AM handler to have its own.  Unfortunately,
the verbs provider, or more specifically the RxD utility provider used
to support RDM with the verbs provider, does not support scalable
endpoints.

Here, add support for multiple transmit endpoints, ideally enough for
each worker thread and the AM handler to have its own.  The decision to
use a scalable endpoint or multiple regular endpoints is based simply on
the provider's reported capabilities, not on its name.  If the provider
says it can support more than one context per endpoint then the comm
layer uses scalable endpoint, otherwise it uses regular endpoints.

The transmit context table is restructured slightly to support this.
When the scalable model is use the scalable endpoint is outside the
transmit context table and the table contains transmit contexts as it
always has.  When the multi-endpoint model is in use the scalable
endpoint outside the table is unused and the transmit "contexts" in the
table are actually endpoints.  Each endpoint needs an address vector, so
there is a similar arrangement with the AVs: when the scalable model is
in use the single AV is stored in the first transmit context table entry
and the other table entries just alias that.  When the multi-endpoint
model is in use each endpoint has its own AV.

The verbs provider seems not to support completion counters as indicated
by `ofi_info->domain_attr->cntr_cnt==0`.  We have been using completion
counters for lower overhead for the AM handler's RMA and AMOs, but the
progress-handling code in the provider actually segfaults if endpoints
do not have completion queues.  Thus here, use counters when `cntr_cnt`
indicates that the provider can support them, and otherwise use CQs.

Lastly, work around two idiosyncracies in the RxD utility provider which
supplies RDM support to the verbs provider.  First, set the address
vector attribute 'count' value to the number of transmit endpoints.  RxD
internal code seems to be storing private addresses for each transmitter
alongside the AV, and the number of such private addresses is limited by
the 'count' attribute value.  Thus we need this to be as large as the
number of transmit endpoints.  Second, supply a dummy 'buf' operand
argument for the `fi_fetch_atomic()` `FI_ATOMIC_READ` operation.  The man
page says that buf is ignored for this operation and may be NULL, but
the RxD provider expects it to be non-NULL and segfaults otherwise.

With these changes made, the ofi comm layer now passes full testing when
using the verbs provider, with just a few test-specific failures which
also fail with the sockets provider.

While here, switch from using separate address vectors for the AM and
RMA/AMO target node addresses to using a single vector containing
address pairs.  This made it easier to adapt the AV support to the
many-endpoints model.

While here, upgrade the progress hinting.  Until now we've forced use of
automatic or manual progress based on the name of the provider.  That's
dumb.  Here, default to "unspecified" and let the provider tell us which
progress model it prefers.  That done, allow forcing the choice one way
or another using an environment variable, but only when debug support is
enabled.

This resolves #11180.

### CODE REVIEW

**Comment by gbtitus** [comment]
This will be easier to review commit-by-commit.

**Comment by ronawho** [comment]
High level questions/notes:
 - Should we always use regular/non-scalable endpoints? Are there performance advantages to using scalable endpoints that we want to use them if they're availble?
 - Can/should we open issues against libfabric for cases where things don't match the man pages or where there was surprising behavior?
 - Does it make sense to still force auto progress for configs where we know manual progress won't perform well? If sockets changed their default to manual progress in some future release, wouldn't that be bad for us?

**Comment by gbtitus** [comment]
> * Should we always use regular/non-scalable endpoints? Are there performance advantages to using scalable endpoints that we want to use them if they're availble?

My general sense from talking to folks is that when a provider provides scalable endpoints, that is the performance-preferred thing to use.  So we should try to use that and only drop back to multiple regular endpoints if scalable is not supported.


> * Can/should we open issues against libfabric for cases where things don't match the man pages or where there was surprising behavior?

Yes.  And for example Sean Hefty (Intel/libfabric), after a conversation between us on [libfabric-users](libfabric-users@lists.openfabrics.org), is currently updating the `fi_atomic(3)` man page to clarify how to achieve coherence when multiple 'actors' (NIC and CPU, e.g.) perform atomic ops on the same location.  I do need to file an issue against the RxD provider for `fi_fetch_atomic(FI_ATOMIC_READ)` needing a non-`NULL` operand parameter despite the man page saying that can be `NULL`.


> * Does it make sense to still force auto progress for configs where we know manual progress won't perform well? If sockets changed their default to manual progress in some future release, wouldn't that be bad for us?

I don't think we're forcing either progress model any more (as of this PR), except with a debug comm layer build when the user sets the optional environment variable.  We're hinting with `FI_PROGRESS_UNSPEC` and taking whatever the provider returns.  Note that `fi_getinfo()` is documented as returning fabrics in order from most-preferred to least-preferred, when it returns more than one, and the expectation is that this also implies highest-performing to lowest-performing.  Can you say give more detail about 'configs where we know manual progress won't perform well', i.e., under what conditions we would want to overrule the provider's judgement on this?

**Comment by ronawho** [comment]
>> * Should we always use regular/non-scalable endpoints? Are there performance advantages to using scalable endpoints that we want to use them if they're availble?

> My general sense from talking to folks is that when a provider provides scalable endpoints, that is the performance-preferred thing to use. So we should try to use that and only drop back to multiple regular endpoints if scalable is not supported.

Cool, thanks

>> * Can/should we open issues against libfabric for cases where things don't match the man pages or where there was surprising behavior?

> Yes. And for example Sean Hefty (Intel/libfabric), after a conversation between us on [libfabric-users](libfabric-users@lists.openfabrics.org), is currently updating the `fi_atomic(3)` man page to clarify how to achieve coherence when multiple 'actors' (NIC and CPU, e.g.) perform atomic ops on the same location. I do need to file an issue against the RxD provider for `fi_fetch_atomic(FI_ATOMIC_READ)` needing a non-`NULL` operand parameter despite the man page saying that can be `NULL`.

Great, thanks

>> * Does it make sense to still force auto progress for configs where we know manual progress won't perform well? If sockets changed their default to manual progress in some future release, wouldn't that be bad for us?

> I don't think we're forcing either progress model any more (as of this PR), except with a debug comm layer build when the user sets the optional environment variable. We're hinting with `FI_PROGRESS_UNSPEC` and taking whatever the provider returns. Note that `fi_getinfo()` is documented as returning fabrics in order from most-preferred to least-preferred, when it returns more than one, and the expectation is that this also implies highest-performing to lowest-performing. Can you say give more detail about 'configs where we know manual progress won't perform well', i.e., under what conditions we would want to overrule the provider's judgement on this?

Yeah, you're right. I was originally thinking we were forcing auto progress for the sockets provider, but that's not true.

**Pull request merged**
