### PR TITLE
Improve memcpy fix vs empty arrays

### PR DESCRIPTION
**Pull request by mppf**
The earlier memcpy fix did not detect the cause of
memcpy with src==dst at the array assignment
level. The problem was occurring with default-inited
arrays. Note that overlapping memcpys might still
need to be handled in the distributions when array
aliasing or slicing is going on, but those details
depend on the distribution.

Also check for zero-length copies before
doing the GET in doiBulkTransfer. This is
really just extra security.

I've verified that this passes full local testing and that
the comms counts do not change before/after
this patch with GASNET.

### CODE REVIEW

**Comment by mppf** [comment]
@bradcray, can you review this one?

**Comment by bradcray** [comment]
I only just got far enough out of triage and into the morning's mail to see this and need to eat lunch, so if you want to have someone else pick it up in order to try and get it in before you leave today, that'd be fine with me.  I still have a lot I need to do before the end of the day even after lunch...

**Comment by mppf** [comment]
@bradcray no worries this one is small and can wait for you

**Comment by ronawho** [comment]
You're clearly welcome to wait for Brad to get a chance to look at this, but it looks good to me.

**Pull request merged**
