### PR TITLE
regex ctest sub_test: Update chpl_re2.py path and usage

### PR DESCRIPTION
**Pull request by cassella**
test/rexgex/ferguson/ctests/sub_test still calls util/chplenv/chpl_regex.py, though this script was replaced in 8f3e6f8a458b with chpl_re2.py with different calling conventions.  Update it.

### CODE REVIEW

**Comment by cassella** [comment]
@mppf @leekillough I update the `sub_test` as I think is in keeping with the change to `chpl_re2.py`, but I don't seem to have an environment built that won't skip the test, so I haven't tested it.

**Comment by mppf** [comment]
This is fine with me but we should make sure the C tests can run somewhere before merging. From looking at the skipif, I would expect `CHPL_RE2=bundled` would be sufficient to run it.

**Comment by cassella** [comment]
Ok, that's this part of the ctests/sub_test:

```
DEFS=`$CHPL_HOME/util/config/compileline --includes-and-defines`
...
echo $DEFS | grep atomics/intrinsics
if [ $? -eq 0 ]
then
  echo "[Working on $DIR with atomics/intrinsics]"
else
  echo "[Skipping directory $DIR without atomics/intrinsics]"
  exit
fi
```

Indeed, when I run that command it doesn't mention `atomics/intrinsics`, though it does have

`-I/home/fortytwo/src/chapel/runtime/include/atomics/cstdlib`

**Comment by mppf** [comment]
AFAIK, the test was just trying to skip CHPL_ATOMICS=locking and cstdlib did not exist yet. Does it work for you if you adjust it to allow cstdlib?

**Comment by cassella** [comment]
Nope, it still skips due to 

```
[Skipping directory regex/ferguson/ctests without gcc or clang]
```

If I set `CHPL_LLVM=none` to use gcc, it does run the test, but hits a bunch of C errors:


```
/home/fortytwo/src/chapel/runtime/src/qio/qio.c: In function ‘const qio_err_s* _qio_channel_init(qio_channel_t*, qio_chtype_t)’:
/home/fortytwo/src/chapel/runtime/src/qio/qio.c:1336:9: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘qio_channel_t’ {aka ‘struct qio_channel_s’} with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
 1336 |   memset(ch, 0, sizeof(qio_channel_t));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/fortytwo/src/chapel/runtime/src/qio/qio.c:39:
/home/fortytwo/src/chapel/runtime/include/qio/qio.h:619:16: note: ‘qio_channel_t’ {aka ‘struct qio_channel_s’} declared here
  619 | typedef struct qio_channel_s {
      |                ^~~~~~~~~~~~~
/home/fortytwo/src/chapel/runtime/src/qio/qbuffer.c: In function ‘const qio_err_s* qbuffer_init(qbuffer_t*)’:
/home/fortytwo/src/chapel/runtime/src/qio/qbuffer.c:303:9: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘qbuffer_t’ {aka ‘struct qbuffer_s’} with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
  303 |   memset(buf, 0, sizeof(qbuffer_t));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/fortytwo/src/chapel/runtime/src/qio/qbuffer.c:27:
/home/fortytwo/src/chapel/runtime/include/qio/qbuffer.h:212:16: note: ‘qbuffer_t’ {aka ‘struct qbuffer_s’} declared here
  212 | typedef struct qbuffer_s {
      |                ^~~~~~~~~
cc1plus: fatal error: /home/fortytwo/src/chapel/runtime/src/qio/regex/re2/re2-interface.cc: No such file or directory
```

```
regex_channel_test.cc: In function ‘void check_channel(qio_hint_t, qio_hint_t, char, char, int, int, base_test_case*)’:
regex_channel_test.cc:256:27: error: too few arguments to function ‘const qio_err_s* qio_channel_create(qio_channel_t**, qio_file_t*, qio_hint_t, int, int, int64_t, int64_t, qio_style_t*, int64_t)’
  256 |   err = qio_channel_create(&writing, f, ch_hints, 0, 1, start, ch_end, NULL);
      |         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from regex_channel_test.cc:1:
/home/fortytwo/src/chapel/runtime/include/qio/qio.h:779:8: note: declared here
  779 | qioerr qio_channel_create(qio_channel_t** ch_out, qio_file_t* file, qio_hint_t hints, int readable, int writeable, int64_t start, int64_t end, qio_style_t* style, int64_t bufIoMax);
      |        ^~~~~~~~~~~~~~~~~~
regex_channel_test.cc:293:27: error: too few arguments to function ‘const qio_err_s* qio_channel_create(qio_channel_t**, qio_file_t*, qio_hint_t, int, int, int64_t, int64_t, qio_style_t*, int64_t)’
  293 |   err = qio_channel_create(&reading, f, ch_hints, 1, 0, test_start, ch_end, NULL);
      |         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from regex_channel_test.cc:1:
/home/fortytwo/src/chapel/runtime/include/qio/qio.h:779:8: note: declared here
  779 | qioerr qio_channel_create(qio_channel_t** ch_out, qio_file_t* file, qio_hint_t hints, int readable, int writeable, int64_t start, int64_t end, qio_style_t* style, int64_t bufIoMax);
      |        ^~~~~~~~~~~~~~~~~~
/home/fortytwo/src/chapel/runtime/src/qio/qio.c: In function ‘const qio_err_s* _qio_channel_init(qio_channel_t*, qio_chtype_t)’:
/home/fortytwo/src/chapel/runtime/src/qio/qio.c:1336:9: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘qio_channel_t’ {aka ‘struct qio_channel_s’} with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
 1336 |   memset(ch, 0, sizeof(qio_channel_t));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/fortytwo/src/chapel/runtime/src/qio/qio.c:39:
/home/fortytwo/src/chapel/runtime/include/qio/qio.h:619:16: note: ‘qio_channel_t’ {aka ‘struct qio_channel_s’} declared here
  619 | typedef struct qio_channel_s {
      |                ^~~~~~~~~~~~~
/home/fortytwo/src/chapel/runtime/src/qio/qbuffer.c: In function ‘const qio_err_s* qbuffer_init(qbuffer_t*)’:
/home/fortytwo/src/chapel/runtime/src/qio/qbuffer.c:303:9: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘qbuffer_t’ {aka ‘struct qbuffer_s’} with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
  303 |   memset(buf, 0, sizeof(qbuffer_t));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/fortytwo/src/chapel/runtime/src/qio/qbuffer.c:27:
/home/fortytwo/src/chapel/runtime/include/qio/qbuffer.h:212:16: note: ‘qbuffer_t’ {aka ‘struct qbuffer_s’} declared here
  212 | typedef struct qbuffer_s {
      |                ^~~~~~~~~
cc1plus: fatal error: /home/fortytwo/src/chapel/runtime/src/qio/regex/re2/re2-interface.cc: No such file or directory
```

Which looks like something beyond the scope of what I was trying to fix...


I can update the PR so sub_test accepts either `atomics/intrinsics` or `atomics/cstdlib`?  Though that would lead to the test failing, so if fixing the rest of the test isn't easy (I haven't tried to figure out what the error actually is), I can also turn it into a .bad-less future?

**Comment by mppf** [comment]
@cassella - could you make this PR include additional commits so that it tries to compile the test but then fails? Then I could cherry-pick those into a different PR to fix the remaining issues.

**Comment by cassella** [comment]
@mppf Sure, I can do that tonight.  Should it run on either intrinsics or cstdlib, or just one due to the objective of only running in one configuration?

Is there a reason the checks for regex and atomics are in the `sub_test` rather than in the SKIPIF?  I think that would be more straightforward.

(And why split the skip conditions between `ctests.skipif` and `ctests/SKIPIF`?)

**Comment by mppf** [comment]
Focusing on cstdlib would be fine. I don't have a particular answer for why sub_test vs skipif etc. It might be that some of them are ignored when there is a sub_test script.

**Comment by cassella** [comment]
Ok, pushed.

I added a check that if  chpl_re2.py returns an error sub_test will also exit with an error so it's caught as a test failure, rather than looking like a skip due to not having the right regex setting.

I thought about also adding that sort of check to the other chplenv scripts called here, but opted against making that many changes for this effort.

The `regex_test.cpp` actually passes, since this sub_test doesn't check for compiler warnings.  Only `regex_channel_test.cpp` hits an actual error.

**Pull request closed without merging**
