### PR TITLE
Have non-flat locale models force wide pointers by default

### PR DESCRIPTION
**Pull request by bradcray**
Like last week's PR #3137, the compiler has long been hardcoded such that only the locale model named 'numa' needs to force wide pointers.  This PR reverses the sense of that logic, saying that locale models other than 'flat' should force wide pointers by default.  As with last week's work, the assumption is that most locale models will not be flat by default.  And, as with last week, we'd ultimately like to make this a property that the locale model can assert, but that's a larger effort than we can take on now.

### CODE REVIEW

**Comment by bradcray** [comment]
[On email, I asked @benharsh, @ronawho, @gbtitus if they had any reservations.]

**Comment by gbtitus** [comment]
No reservations -- this looks fine to me.  As far as testing goes, I think it would be adequate to test just comm=none and a single tasking layer (pick your favorite) with both flat and numa locale models.  The code itself is independent of anything other than locale model name, after all.

**Comment by ronawho** [comment]
ditto what greg said (I'd also be fine with just `make check` for flat and numa, but am not opposed to a full paratest)

**Comment by bradcray** [comment]
This passed testing, but then I thought "Why don't I look at some generated code and verify that it's doing what I think it should?" only to find that it wasn't what I expected.  I'm not sure if that means that I no longer have a good grasp on what will be wide or not, or whether it means that I got my strcmp logic wrong again.  I'm looping @benharsh back in as the wide pointer master.

Here's my test code:

    class C {
      var y: int;
    }

    var x: int;
    var myC = new C(y=2);

    on Locales[(here.id + 1)%numLocales] do {
      x += 1;
      myC.y += 1;
    }

What I see in the generated code is that myC is a chpl____wide_C which is as I'd expect/hope.  But x is a mere int64_t that's referred to directly (as opposed to through a ref or argument) within the on function.  Is this surprising?

Checking master, it seems consistent with what's there, so I feel confident my change preserves the current behavior, I guess I'm just surprised by the current behavior.

**Comment by vasslitvinov** [comment]
Referring to 'x' as a mere int64_t should produce correct result under NUMA I think. However, 'x.locale' would not produce an appropriate result, i.e, not have the subdomain info? I am curious.

**Comment by bradcray** [comment]
I'm not saying it wouldn't work -- it clearly would.  It just surprises me that given the forceWidePointers() logic, we wouldn't widen 'int' cases in the presence of on-clauses but we do widen class references.  I'd think it'd be more like both or neither (and would expect it to be both, given the code).  Perhaps if there was some optimization that tried (and succeeded) in differentiating between network-level-locale on-clauses and sublocale-level on-clauses, but I don't think we have that (and would still expect it to treat the two cases similarly).

**Comment by bradcray** [comment]
Capturing some offline discussion/investigation that @benharsh and I have had about this for future reference:

* it definitely seems wrong/inconsistent that scalar types and classes are handled inconsistently with numa + --local compilation as noted above (an 'int' crossing an on-clause in --local + numa mode is not widened while a class is).
  - the cause for this would appear to be related to the fact that the scalar type is a global and not moved to the heap for local compilation, independently of the locale model choice (in a flat + gasnet compile, it is moved to the heap (more on that below) and this causes width to be inserted for it).  By contrast, since the C variable is a ref by nature, it is widened.
  - to that end, Ben suggests that a good unification to do in the compiler would be to go through looking for cases that cue off of flocal and have them use some query like requireWideReferences() / forceWidePtrsForLocal()
  - we're also noting that while the immediate way to make these consistent in the current compiler would be to have 'x' be treated widely as well, since we're trying to move away from storing wide pointers for local numa data, the longer-term way to treat them uniformly might be to have C not be widened in this case.

* we also noted that the behavior is different depending on whether the scalar variable is a module-scope or local variable.
  - Specifically, we seem to always move global scalar variables onto the heap when doing --no-local compilations (even when needHeapVars() returns false) which results in them being accessed through the communication/wide reference mechanism even for completely local accesses.  As an example, consider the following simple program:

        var x: int;
        x += 1;

  When compiling in gasnet-everything, 'x' is put onto the heap and all the normal comm unwrapping code/calls are inserted to increment it even though it's clearly being referred to on the same locale.  By contrast, if x is a local variable:

      proc main() {
        var x = 1;
        x += 1;
     }

  x is left on the stack, incremented directly and a wide reference to it is created only if/when it crosses into an on-clause.  For consistency and simplicity in the implementation (and a slight boost in generated code simplicity and execution-time overhead for locale 0 accesses to global data), it seems we should treat the global case more like the local.

* we also noted that needHeapVars() is called O(#functions) times during compilation whereas nothing about its definition will differ from one invocation to the next.  So we could save compilation / strcmp time by caching the result once and reusing it.

**Pull request merged**
