### PR TITLE
Dense matrix inverse

### PR DESCRIPTION
**Pull request by wongalvis14**
Computes dense matrix inverse, currently only supports 2D square matrices

### CODE REVIEW

**Comment by wongalvis14** [comment]
Sparse does not work because of assignment within the procedure without adding the indices first

**Comment by e-kayrakli** [comment]
@wongalvis14 -- I didn't see anything jumped at me right away on this one. But could you add some tests for this one? Ideally something with a large-ish matrix. You can generate something and use some other tool (numpy, wolfram alpha etc) create the correct output and check against it. I will give a more in-depth review once there is a test case.

**Comment by wongalvis14** [comment]
I did some performance test on the swap operation, it appears that the `<=>` operator is slightly faster.

**Comment by npadmana** [comment]
Similar to my comment in #13516, here's a test case that fails catastrophically for the Chapel-only version but correctly works for the LAPACK version (I tested with MKL).

```chapel
use LinearAlgebra;

var A = Matrix([1.0e-20,1.0],
               [1.0,1.0]);
writeln("A=\n",A);
var (invA,info) = inv(A);
writeln(info);
writeln("A^-1=\n",invA);
writeln("A.A^-1=\n",dot(A,invA));
```

Compiling the native Chapel version ---
```
23:33 test$ chpl -sblasImpl=off -slapackImpl=off inv1.chpl
23:37 test$ ./inv1 
A=
1e-20 1.0
1.0 1.0
1
A^-1=
0.0 1.0
1.0 -1e-20
A.A^-1=
1.0 0.0
1.0 1.0
```
Note that eg. the last matrix should have been the identity, but instead has 1 on the 2,1 elt. I'll also note that the original matrix has a non-zero determinant and is well conditioned; it's just set up to cause trouble with a simple algorithm.

The LAPACK version has no trouble --
```
23:37 test$ chpl -sblasImpl=mkl -slapackImpl=mkl inv1.chpl ${MKL_CHPL_INCLUDE} ${MKL_CHPL_LINK} 
23:38 test$ ./inv1 
A=
1e-20 1.0
1.0 1.0
0
A^-1=
-1.0 1.0
1.0 -1e-20
A.A^-1=
1.0 0.0
0.0 1.0
```

**Comment by npadmana** [comment]
On a trivial note, it looks like `info` has opposite meanings in the LAPACK/Chapel branches (good=0 for LAPACK, good=1 for Chapel).

**Comment by wongalvis14** [comment]
Yes, I've noticed the difference in `info`, I was thinking true/false but then realized it carries more information than that in LAPACK or other libraries. 

I'll have to switch to another inverse algorithm. While on the other hand there's another route to do LU then invert the P,L,U matrices.

**Comment by wongalvis14** [comment]
@npadmana I think it might be more numerically stable to invert with LU factorization. Unfortunately I haven't dealt much with numerical stability in a high-level language before, do you have any insights on what could fix the numerical instability in this algorithm?

**Comment by npadmana** [comment]
@wongalvis14 -- I don't have any real insights about matrix inversion. It looks like most packages do LU and then use that.

http://www.netlib.org/lapack/lawnspdf/lawn27.pdf

**Comment by wongalvis14** [comment]
Now that we have a more numerical stable LU. I'm thinking we can have both direct inverse and LU-factorization inverse, by default we can use the more stable one (i.e. LU), users can choose with a argument like `direct=false`. We can add a note highlighting the difference.

What do you think?

**Comment by npadmana** [comment]
I'm tempted to say that we do the `LU` route only (as we add other factorizations, we can put those in too). My suspicion is that the other algorithm is just too numerically unstable. I'll note that the matrix I sent was not pathological in any way.

Is your concern that the current `LU` is too slow? First, if anyone has a LAPACK implementation, you could switch to that implementation. And I suspect we can speed up `LU` as well....

**Comment by wongalvis14** [comment]
So closing this PR, and after `LU` is finalized, there'll be a new `inverse` that incorporates `LU`. And I agree `LU` can be much better in terms of speed and memory, it'll also be the "entry point" for sparse matrices to a lot of these routines.

**Pull request closed without merging**
