### PR TITLE
Prefix jemalloc symbols with chpl_je_

### PR DESCRIPTION
**Pull request by dmk42**
To avoid a conflict with the memkind library, which uses its own copy of jemalloc, this change prefixes our jemalloc symbols with chpl_je_ .

The jemalloc documentation recommends using --with-private-namespace to avoid naming collisions when jemalloc is built statically (which we do).

Note that the private namespace gets je_ prepended to it automatically, so although the Makefile appears to be asking for just chpl_ for internal names, it ends up chpl_je_ .

This is a prerequisite for #5555 .

### CODE REVIEW

**Comment by gbtitus** [comment]
This looks great to me; don't know if @ronawho wants to look also.

**Comment by ronawho** [comment]
👍 I'm happy with this. I think it's worth doing a std and gasnet-fast (shared heap) paratest. 

I'd also include in the PR message that we should have been throwing `--with-private-namespace` since jemalloc was first added (My bad!). Maybe something along the lines of:

"jemalloc recommends using --with-private-namespace to avoid naming collisions when jemalloc is built statically (which we do), so we should have been using it since jemalloc support was originally added."

**Comment by dmk42** [comment]
Thanks.  I added the sentence you recommended but left off the last part, as I am so not interested in assigning blame.  I am testing with gasnet-fast now, and will run a standard test before merging.

**Comment by ronawho** [comment]
Sounds good. It was my fault/bug so I had no problem taking the blame for it :)

**Comment by bradcray** [comment]
@dmk42, @ronawho, @gbt: Are you still online?  I'm getting build failures of the following form (on Mac).  If I feel confident it's not a personal problem and don't hear from you guys before bed, I may revert this to avoid testing noise tonight:

````
In file included from comm-none.c:25:
In file included from ../../../include/chpl-mem.h:60:
../../../include/mem/jemalloc/chpl-mem-impl.h:33:10: error: implicit declaration
      of function 'chpl_je_calloc' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  return chpl_je_calloc(n,size);
         ^
../../../include/mem/jemalloc/chpl-mem-impl.h:33:10: error: incompatible integer
      to pointer conversion returning 'int' from a function with result type
      'void *' [-Werror,-Wint-conversion]
  return chpl_je_calloc(n,size);
         ^~~~~~~~~~~~~~~~~~~~~~
../../../include/mem/jemalloc/chpl-mem-impl.h:37:10: error: implicit declaration
      of function 'chpl_je_malloc' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  return chpl_je_malloc(size);
         ^
../../../include/mem/jemalloc/chpl-mem-impl.h:37:10: note: did you mean
      'chpl_je_calloc'?
../../../include/mem/jemalloc/chpl-mem-impl.h:33:10: note: 'chpl_je_calloc'
      declared here
  return chpl_je_calloc(n,size);
         ^
../../../include/mem/jemalloc/chpl-mem-impl.h:37:10: error: incompatible integer
      to pointer conversion returning 'int' from a function with result type
      'void *' [-Werror,-Wint-conversion]
  return chpl_je_malloc(size);
         ^~~~~~~~~~~~~~~~~~~~
../../../include/mem/jemalloc/chpl-mem-impl.h:43:8: error: implicit declaration
      of function 'chpl_je_posix_memalign' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  rc = chpl_je_posix_memalign(&ret, boundary, size);
       ^
../../../include/mem/jemalloc/chpl-mem-impl.h:43:8: note: did you mean
      'chpl_posix_memalign'?
../../../include/chpl-mem.h:48:5: note: 'chpl_posix_memalign' declared here
int chpl_posix_memalign(void** ptr, size_t alignment, size_t size);
    ^
In file included from comm-none.c:25:
In file included from ../../../include/chpl-mem.h:60:
../../../include/mem/jemalloc/chpl-mem-impl.h:49:10: error: implicit declaration
      of function 'chpl_je_realloc' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  return chpl_je_realloc(ptr, size);
         ^
../../../include/mem/jemalloc/chpl-mem-impl.h:49:10: error: incompatible integer
      to pointer conversion returning 'int' from a function with result type
      'void *' [-Werror,-Wint-conversion]
  return chpl_je_realloc(ptr, size);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/mem/jemalloc/chpl-mem-impl.h:53:3: error: implicit declaration
      of function 'chpl_je_free' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  chpl_je_free(ptr);
  ^
../../../include/mem/jemalloc/chpl-mem-impl.h:53:3: note: did you mean
      'chpl_free'?
../../../include/mem/jemalloc/chpl-mem-impl.h:52:20: note: 'chpl_free' declared
      here
static inline void chpl_free(void* ptr) {
                   ^
../../../include/mem/jemalloc/chpl-mem-impl.h:58:10: error: implicit declaration
      of function 'chpl_je_nallocx' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  return chpl_je_nallocx(minSize, MALLOCX_NO_FLAGS);
         ^
````

**Comment by ronawho** [comment]
@bradcray try clobbering jemalloc and rebuilding

**Pull request merged**
