### PR TITLE
Add a use of the IO module to the Random modules to enable calls to <~>

### PR DESCRIPTION
**Pull request by lydia-duncan**
The writeThis methods in the Random module were getting away with calls to <~>,
probably due to uses of the IO module at the points where it is called.
Unfortunately, a user encountered a situation where such a use was not
available, causing the writeThis to fail to resolve. This adds a use of the IO
module at the scopes with the writeThis functions, to avoid this issue in the
future.

Passed a full std paratest with futures

----
Signed-off-by: Lydia Duncan <lydia-duncan@users.noreply.github.com>

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@bradcray - care to review?

**Comment by bradcray** [comment]
This looks like a job for @mppf or @vasslitvinov to me (where I don't hesitate about the changes themselves so much as the "probably due to...".  I also think we should create a test that reproduces the original user issue (which would also help understand why the change is necessary and what it suggests).

**Review by mppf — APPROVED** [review]

**Comment by lydia-duncan** [comment]
In trying to determine a small reproducer, I discovered a small typo that I think is what caused the problem to be discovered:
a generic function with a writeln and string format call in it was accidentally called with a first class function as one of the arguments passed to the formatting.
```chapel
...
// The function
        proc debug(moduleName, routineName, lineNumber, msg: string) throws {
            if level == LogLevel.DEBUG  {
                writeln("[%s] %s Line %i DEBUG [Chapel] %s".format(moduleName, 
                    routineName, lineNumber, msg));
                stdout.flush();
            }
        }
...
// The call - it should be getRoutineName() instead
logger.debug(getModuleName(),getRoutineName,getLineNumber(),
                 "%s %s %s %s %s : %s".format(cmd,op,dtype2str(dtype),value,aname,rname));
```
Note that this generic function is not called near the code that used the Random module.  It appears that the random module's writeThis was being considered as one of the candidate functions?

**Comment by vasslitvinov** [comment]
>  It appears that the random module's writeThis was being considered as one of the candidate functions?

Just being a candidate function should not cause errors in its body. Right?

**Comment by vasslitvinov** [comment]
See also #16844 for more `use IO` additions and POI reliance.

**Comment by lydia-duncan** [comment]
> I also think we should create a test that reproduces the original user issue (which would also help understand why the change is necessary and what it suggests).

@bradcray - I've added a reproducer in the most recent commit, though there are likely things I can do to make it even simpler (I want to get back to my remaining sprint task, but I think this is concerning and think we should investigate it soon - I'm happy to do that as part of my next sprint cycle)

**Comment by lydia-duncan** [comment]
> Just being a candidate function should not cause errors in its body. Right?

I would think so, but I'm still confused why it's even being considered in the first place, since it shouldn't be visible.  This is a weird situation

**Pull request merged**
