### PR TITLE
GPU technote updates for 1.33

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR includes several adjustments to the GPU technote:

- Drops support for CUDA 10.x: we never really did anything special for it in the past. It did work but in an inefficient way. With 12 out, 10 feels pretty old.
- Removes warnings about ROCm deprecation warnings (Resolved via https://github.com/chapel-lang/chapel/pull/23972)
- Drops references to `assertOnGpu()` function that was deprecated.
- Adds a subsection about "Reductions and Scans"
- Improves d2d communication section

### CODE REVIEW

**Comment by e-kayrakli** [comment]
> Drops references to assertOnGpu() function that was deprecated.

@DanilaFe, any qualms about this? We can keep the deprecated function in the GPU module, but I don't feel the need to highlight it in the technote.

> Adds a subsection about "Reductions and Scans"

@ShreyasKhandekar, do you have any comments about this? This section is in https://github.com/chapel-lang/chapel/pull/24023/files#diff-0701fd6e5731a2b94e6183605fb0951649c739c08c5c22e8ffc949a24ce1caccR362

> Improves d2d communication section

@stonea, does what I have sound right to you? I did run with this in the past, but you also have some context and it'd be good to check that I am making sense. https://github.com/chapel-lang/chapel/pull/24023/files#diff-0701fd6e5731a2b94e6183605fb0951649c739c08c5c22e8ffc949a24ce1caccR402

**Review by stonea — APPROVED** [review]
Looks accurate to me.

Run spell check on it if you didn't before.

**Review by ShreyasKhandekar — APPROVED** [review]
Looks good to me

**Review by DanilaFe — APPROVED** [review]
No qualms :)

**Pull request merged**
