### PR TITLE
Formatted I/O bug

### PR DESCRIPTION
**Pull request by npadmana**
A test case for a bug in formatted I/O where the code inserts in NULLs...

### CODE REVIEW

**Comment by mppf** [comment]
This test case needs to be updated so that we get "Clean match against .bad file" when running with start_test -futures .
@npadmana, I've emailed you with a suggested fix. Thanks!

**Comment by npadmana** [comment]
@mppf : I've merged in your changes. Let me know if this works for you.

**Comment by mppf** [comment]
Yep, looks good, I'll merge it once Jenkins reports it's OK. Thanks!
BTW, the fix for this actual bug is in PR #2082, which is undergoing testing...

**Comment by npadmana** [comment]
Wonderful, thanks!

**Pull request merged**
