### PR TITLE
Update chpldoc dependencies

### PR DESCRIPTION
**Pull request by mppf**
This PR goes along with
https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/37 It
updates the sphinx version used for chpldoc / rst documentation
rendering.  Note that since the chpldoc-requirements.txt file listed the
sphinxcontrib-chapeldomain requirement as
sphinxcontrib-chapeldomain>=0.0.10, updating the pip package will break
`make docs` for people using the 1.20 release.

In order to reduce the dependency on another source package, this PR
includes a local copy of sphinxcontrib-chapeldomain in
third-party/chpl-venv/sphinxcontrib-chapeldomain. This strategy has the
side effect of allowing this package to be included and used in Chapel
releases.

Future Work:
 * (in a future release) consider updating the pip package for
   sphinxcontrib-chapeldomain (doing so now would break chpldoc for 1.20
   and earlier)
 * update pygments lexer and remove workarounds for problems there -- see
   #14623

Reviewed by @lydia-duncan and @ben-albrecht - thanks!

- [x] spec tests pass

### CODE REVIEW

**Comment by mppf** [comment]
Now a failure to lex with pygments is creating a Sphinx warning-as-error (this wasn't previously the case). We'll need to do one of:
 * use a generic block (not highlighted) for the problematic regions
 * update Pygments lexer
 * disable the warning-as-error for these somehow

**Comment by ben-albrecht** [comment]
> use a generic block (not highlighted) for the problematic regions

I vote for this option for this PR, and we can get those updates into the Pygments lexer eventually.

**Comment by ben-albrecht** [comment]
> use a generic block (not highlighted) for the problematic regions

I vote for this option for this PR, and we can get those updates into the Pygments lexer eventually.

**Comment by ben-albrecht** [comment]
Continuing a discussion @mppf and I had offline:

> update Pygments lexer

Unfortunately, there's a pretty large turn-around time for getting changes into the Pygments repository. It would be nice if we could rely on a Chapel pygments lexer that was tied to the chapel repo, similar to what we're doing with sphinxcontrib-chapeldomain. However, unlike the sphinxcontrib, having Chapel in the main pygments repo could be useful to others, so we should continue to promote changes upstream over time.

Here's a starting point on including a custom lexer in a sphinx project:

https://stackoverflow.com/questions/16469869/custom-syntax-highlighting-with-sphinx

**Pull request merged**
