### PR TITLE
Workaround to fix `list` test failures on `COMM=gasnet` or `--no-local`

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
This PR fixes the `list` test failures that are occurring on `COMM=gasnet` or `COMM=none` with the `--no-local` flag. 

It adds a new argument to `_ddata_allocate` called `initElts`, and only performs initialization of elements when `initElts` is `true` (it is `true` by default). The calls to `c_calloc` within the `list` implementation are replaced with `_ddata_allocate`.

Testing:

- [x] `ALL` on `linux64` when `CHPL_COMM=none`

---

**(Not part of PR message).**

As for the bug itself, I'm not quite sure how to explain it other than it _seems_ to be caused by casting the result of a `c_calloc` to a `_ddata`.

The bug itself was not what I expected.

It looks like calls to `c_malloc` and company do not return the correct amount of memory for wide pointers on multi-locale modes. 

This problem is well illustrated here https://github.com/chapel-lang/chapel/pull/13238#issuecomment-501407128.

### CODE REVIEW

**Comment by cassella** [comment]
Ooh, inexplicable problems are fun!

Is there a pattern to the non-nil values that show up in every other append?

**Comment by dlongnecke-cray** [comment]
Hey @casella, so I definitely knew from the outset that it has something to do with an improper cast to a wide pointer. Earlier this morning @ronawho recalled that it might have something to do with https://github.com/chapel-lang/chapel/pull/11908. IE, `c_malloc` and friends might only be allocating space for narrow pointers.

Even knowing that, I still can't conjure up an explanation for the patterns in the buggy code, other than  it being something like "the memory for the second segment (of integers) is allocated _adjacent_ to the end of the segment array".

**Comment by cassella** [comment]
Bingo,

```
Appending 1
mBA allocated 16 * 8 at t: 0x7ffff0002730
dd_sizeof_element 8
mA allocated 8 at t: 0x7ffff00027c0
0x7ffff00027c0 nil nil nil nil nil nil nil 0x55 nil nil nil nil 0x25 0x7ffff0000078 0x25
Appending 2
0x7ffff00027c0 nil nil nil nil nil nil nil 0x55 0x2 nil nil nil 0x25 0x7ffff0000078 0x25
Appending 3
0x7ffff00027c0 nil nil nil nil nil nil nil 0x55 0x2 nil nil nil 0x25 0x7ffff0000078 0x25
Appending 4
0x7ffff00027c0 nil nil nil nil nil nil nil 0x55 0x2 0x4 nil nil 0x25 0x7ffff0000078 0x25
Appending 5
0x7ffff00027c0 nil nil nil nil nil nil nil 0x55 0x2 0x4 nil nil 0x25 0x7ffff0000078 0x25
Appending 6
0x7ffff00027c0 nil nil nil nil nil nil nil 0x55 0x2 0x4 0x6 nil 0x25 0x7ffff0000078 0x25
Appending 7
0x7ffff00027c0 nil nil nil nil nil nil nil 0x55 0x2 0x4 0x6 nil 0x25 0x7ffff0000078 0x25
Appending 8
0x7ffff00027c0 nil nil nil nil nil nil nil 0x55 0x2 0x4 0x6 0x8 0x25 0x7ffff0000078 0x25
```

```
(gdb) x /32xg 0x7ffff0002730
0x7ffff0002730: 0x0404042500000000      0x0000000000000000
0x7ffff0002740: 0x0404042500000000      0x0000000000000000
0x7ffff0002750: 0x0000000000000000      0x0000000000000000
0x7ffff0002760: 0x0000000000000000      0x0000000000000000
0x7ffff0002770: 0x0000000000000000      0x0000000000000000
0x7ffff0002780: 0x0000000000000000      0x0000000000000000
0x7ffff0002790: 0x0000000000000000      0x0000000000000000
0x7ffff00027a0: 0x0000000000000000      0x0000000000000000
0x7ffff00027b0: 0x0000000000000000      0x0000000000000055
0x7ffff00027c0: 0x0000000000000000      0x0000000000000002
0x7ffff00027d0: 0x0000000000000003      0x0000000000000004
0x7ffff00027e0: 0x0000000000000005      0x0000000000000006
0x7ffff00027f0: 0x0000000000000007      0x0000000000000008
0x7ffff0002800: 0x0000000000000000      0x0000000000000025
0x7ffff0002810: 0x00007ffff0002820      0x00007ffff0000078
0x7ffff0002820: 0x0000000000000000      0x0000000000000025
```
But that's 32 8-byte values, out of the 16 allocated to the segment array.

**Comment by dlongnecke-cray** [comment]
Awesome!

Can't believe you got a visualization on that so quickly. 

Looks like using `_ddata_allocate` is the right way to go.

**Pull request merged**
