### PR TITLE
Adding notest file to skip cublas wrapper tests

### PR DESCRIPTION
**Pull request by slnguyen**
---
Signed-off-by: Sarah Nguyen <slnguyen@users.noreply.github.com>

### CODE REVIEW

**Comment by bradcray** [comment]
@slnguyen: What are the requirements for running this test somewhere?   I'm wondering specifically whether we could potentially `.skipif` it to run it on at least one platform rather than never running it anywhere?

**Comment by slnguyen** [comment]
I think we should be able to add a `.skipif`, the test depends setting a path to a cuda library in the `compopts` file.

**Comment by bradcray** [comment]
So, practically speaking, what would it take for us to start getting some nightly testing on this in one or more of our configurations, to avoid bit-rot?

**Comment by slnguyen** [comment]
I'll need to figure out what systems, if any, have a cuda lib installed and the path to it so I can set the path in the compopts file. Then I'll make a skipif file that says if the cuda lib is not in the path, skip the tests.

**Comment by e-kayrakli** [comment]
Probably this'll require some BTR work so that we can run on the nodes with GPUs on them:

We either:
- Rejigger some of our jobs to use nodes with GPUs on them but those GPUs will be unused except for these tests.
- Create a new job that only runs this (and potentially some other forthcoming GPU-based tests) on GPU nodes.

**Comment by bradcray** [comment]
As a starting point, I'd even be up for making sure it compiled yet did not run if that simplifies things and improves confidence that the bits don't rot.

**Pull request merged**
