### PR TITLE
String max-min rotation added

### PR DESCRIPTION
**Pull request by Deeksha96**
This pull request is in reference to the issue #8271 
Please have a look and suggest any changes required.

### CODE REVIEW

**Comment by Deeksha96** [comment]
@mppf Please review this PR. 
We are considering applying for Rgsoc these summers and are quite new to contributing to chapel. We were facing a few problems about how to test the new module that we added to this PR locally. It would be great if you could guide us in that direction.

**Comment by mppf** [comment]
hi @Deeksha96 - I can provide some feedback but I'm not so sure that it makes sense to add these to Chapel releases. I.e. I think they'd make more sense in your own GitHub repo, at least until somebody convinces me otherwise.

Even so, I'd be happy to have these added to the `tests/` directory.

Regarding testing, basically you'll want to create a .chpl file that does `use StringAlgorithms;` and calls the new functions. I like to write tests that use `assert` to check that they got the right answer and this is a good way to start. Once you have such a program, say `testStringAlgorithms.chpl`, you can add an empty .good file next to it, say `testStringAlgorithms.good`, and then you should be able to `start_test testStringAlgorithms.chpl` and see it reported as passing.

Test system docs here: https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst and https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst#creating-a-simple-test might be a good place to start.

**Comment by mppf** [comment]
hi @Deeksha96 - thanks for adding a test! I think it will require discussion in order to know if StringAlgorithms can go into modules/packages (this directory is bundled with releases) so I'd propose you take the following two next steps:
 1. Adjust this PR to add the new module somewhere inside of test/. E.g. just move modules/packages/StringAlgorithms.chpl and your new test into test/users/Deeksha96/StringAlgorithms.chpl for now. This will allow this PR to merge without solving the other issue.
 2. Create a new GitHub issue - or use the existing issue #8271 - to ask whether or not it makes sense for these functions to be included in Chapel releases - or if they should just go in the test system & possibly be a Mason package.

Also in order for the PR to merge, we'll need a contributor agreement - see https://github.com/chapel-lang/chapel/tree/master/doc/rst/developer/contributorAgreements/

**Comment by mppf** [comment]
Also - regarding the should it be in Chapel installations question - on such questions it often helps to know if other languages have similar support included in the language distribution or as a separate package? It would help if you are able to answer that question for some other languages (hopefully including Python and one or two others).

**Comment by Deeksha96** [comment]
Hi @mppf, I have made the required changes. I have also mailed the contributor agreement.

**Comment by mppf** [comment]
We've got the contributor agreement, thanks.

**Comment by verma-varsha** [comment]
@mppf I'm not getting you. Don't we already have a testStringAlgorithms.good file?

**Comment by mppf** [comment]
Right, you can 
`touch StringAlgorithms.notest`
and the test command should start passing.

The start_test script thinks anything ending in .chpl is a "test". The issue is with StringAlgorithms.chpl in this case.

**Pull request merged**
