### PR TITLE
fixed missing close paren

### PR DESCRIPTION
**Pull request by MrMormon**
:)

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Nice catch, although I think the period should follow the closed parenthesis. 

That is, `[1]).` instead of `[1].)`

**Comment by MrMormon** [comment]
The sentence starts inside '(' and the previous sentence was already closed.

**Comment by ben-albrecht** [comment]
Sorry I meant to say remove the preceding period as well.


`... resulting in exceedingly long and impenetrable error messages (C++-template libraries have become infamous for this problem [1]).`

**Comment by MrMormon** [comment]
Please see https://github.com/chapel-lang/chapel/pull/3129 for my fix.

**Pull request closed without merging**
