### PR TITLE
Move PRIM_NEW handling to resolution

### PR DESCRIPTION
**Pull request by mppf**
This is to fix code such as

      proc createClassInstance(type X) where isClassType(X) {
         var x = new X();
         return x;
      }
      var foo = createClassInstance(Foo);

In my initial investigated, I identified call_constructor_for_class in
normalize.cpp as doing some transformations that can't possibly be done
before function resolution - at least for a generic case like the above.

Then, I discovered that functionResolution.cpp already has a resolveNew
function to handle PRIM_NEW.  So, I moved the logic finding the name of
the constructor to call from call_constructor_for_class  in normalize to
resolveNew in function resolution.

One problem came up: since resolution resolves expressions in postorder,
the CallExpr within the PRIM_NEW was getting resolved first and not
getting special treatment.

Therefore, I adjusted call_constructor_for_class to rewrite PRIM_NEW to
not use a nested call - instead, PRIM_NEW now uses a different style
after normalization than before.

Before normalization:

      PRIM_NEW (CallExpr SomeType args ...)

After normalization

      PRIM_NEW SomeType args...

I felt that adjusting normalize in this way was better than further
complicating the basic call resolution logic in functionResolution.cpp,
but certainly another approach could have worked.

One wrinkle is that function resolution calls normalize on
already-normalized code, so normalize has to be ready
to handle such things.

### Future Work

I expect that type constructor calls will eventually need similar
treatment but did not attempt it in this PR. (And, I don't
have a bug report for that functionality in hand).

Also I expected the test

      test/types/type_variables/nelson/dependentTypeOverClasses.chpl
to pass after this PR but it does not.

### Testing & Review

Passed full local testing.
Checked Hello World and types/type_variables/nelson/dependentTypeArgument.chpl
 * with --llvm
 * with --baseline
 * with --baseline --verify
 * with --verify
 * with GASNet

Retires 6 futures.

Reviewed by @lydia-duncan - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
I'm still testing this PR.

**Comment by mppf** [comment]
There were 33 failures, including:
[Error matching compiler output for release/examples/programs/genericStack]
[Error matching program output for users/ferguson/nested/classclass]

**Comment by mppf** [comment]
That last fix repared 25/33 of the failures. I'll look into the remaining 5.

**Comment by mppf** [comment]
Current versions only fails two tests:
[Error matching compiler output for classes/diten/multipledestructor]
[Error matching compiler output for functions/bradc/resolveGeneric]

These are both error message change that I believe are acceptable.

**Comment by mppf** [comment]
Futures testing revealed 6 passing futures.
I would expect this test to work but it doesn't:
 dependentTypeOverClasses.chpl

Futures testing revealed 667 .bad file mismatches. I need to investigate those before merging this PR.

**Comment by lydia-duncan** [comment]
Looking at your list of testing configurations, I'd be curious about the behavior of the bug test in the configurations you checked "Hello, world" in.

**Comment by lydia-duncan** [comment]
Looks good!

**Pull request merged**
