### PR TITLE
Warn for fields declared with generic declared type

### PR DESCRIPTION
**Pull request by mppf**
This PR implements a warning for fields with a declared type that is generic and does not include a `?` argument.

For example

``` chapel
record R {
  var a: MyGenericRecord(?); // OK
  var b: MyGenericRecord; // warning
  var c: integral; // warning
  var d: MyClass; // warning (generic management)
  var e: owned MyClass; // ok (assuming MyClass has no generic fields)
}
```

This is intended to address issue #19120.

For now, this does not issue the warning for internal/standard modules. I think that's sufficient for evaluating the idea since we can adjust internal/standard modules as needed.

Passes full local testing.

This PR is a draft only in order to stimulate discussion on the language design.

### CODE REVIEW

**Comment by bradcray** [comment]
I'm less a fan of this change than of #21410.  Specifically, for the example given:

* for `b`, if `MyGenericRecord` were a fully-defaulted generic type, I think it should be OK.  If it were not, I think it should (need to be) be written `MyGenericRecord(?)` as proposed in my comments on #21410 
* I don't see `c` as inherently problematic, personally and don't see rewriting it as `type t: integral; var c: t;` to be a productivity win
* for `d`, I'd be happier with the warning if we could write something like `? MyClass` or `?mgmt MyClass`, at which point I might also want to require it to be written that way.  Specifically, I don't think writing it as `type t: MyClass;  `var d: t;` is a net productivity win

I'd also be more OK if this were an opt-in warning (in which case I realize most users who'd benefit from it would not know about it until they asked us for help and we suggested it—so too late to be useful...) or was only printed out in the event of other errors occurring.

**Comment by bradcray** [comment]
I forgot to copy this one over from the meeting chat earlier:  I'm also not a fan of this PR because I don't like the idea of treating fields and non-fields differently in this respect.  I understand that there's a concern that generic fields are more troublesome/infectious because they (may inadvertently) make the class or record itself generic, but the asymmetry still bothers me.

For example, it's unsatisfying to me that:

```chapel
class  C {
}

record R {
  var myC: C;

  proc init() {
    this.myC = new owned C();
  }
}

var myR = new R();
writeln(myR);
```

would generate a warning, while:

```chapel
class  C {
}

var myC: C;

myC = new owned C();
```

does not.

**Comment by mppf** [comment]
Would generating a warning in the variable case help?

What about making the warning focus on the genericity of the record? E.g., it could say "record R is generic in a potentially surprising way since it is only generic due to 'myC' being generic but that might be surprising because 'myC' has a declared type". IMO, that changes the focus from "You can't do that with a field but you can with variable" to "There are only certain reasonable ways to create a generic class/record".

**Comment by bradcray** [comment]
> Would generating a warning in the variable case help?

It would help in terms of keeping the two cases more consistent, but wouldn't particularly make me a bigger fan of the change (and might make me even less of a fan).  Specifically, I feel as though most warnings that we have today give me the reaction "that's a good point; I should rewrite the code in thus-and-such a way because of that warning."  The example we discussed with a mix of file-scope code and explicit `module` declarations being a good example of that—though I understand the language and what's happening there, I like that warning because I think it points out a style that I agree is poor and better addressed by, say, putting an explicit module declaration into the file as well.

In contrast, this warning, to me, feels more informational ("Hey, did you know that this is generic?") rather than a sign that something is sub-par about the code.  Or, put another way, I think my reaction would be "Yeah, I know that's generic, but I'm not interested in restructuring my code because I'm benefitting from leveraging Chapel's productivity features w.r.t. genericity here, and don't really want to give that up to make the warning go away.  Contrasting this with cases like warnings/errors requiring `var r: R;` to be rewritten as `var r: R(?);` for a not-fully-defaulted generic to make the genericity more evident, that's a case that makes me think "Yeah, that's a good practice, I should make that change to improve the code."

It's that lack of desire to rewrite my code in a way that would make the warning go away that makes me think of this more as a "compiler reporting" flag.  I.e., "flag generic fields for me" as a form of communicating to me about my code and how you see it rather than suggesting something needs to be fixed/changed about it.  And I'm open to that, but would want it off by default, whereas I think it'd only be useful in protecting users from surprises if it were on by default.  A compromise might be to have a "--new-chapel-user` mode that was on by default and controlled a number of pedagogical things like this (maybe long vs. short warnings as well), and which it would be expected that experienced developers would opt out of at some point, assuming that could be done easily (e.g., it wasn't too impactful to require them to set an env. var. in their .bashrc or chplconfig file).  But I can see an argument that surprise generics may catch experienced users by surprise as well.

The other big concern I have with this warning is the one I started expressing on https://github.com/chapel-lang/chapel/issues/21456:  That a generic field seems increasingly to me to not guarantee that the type is generic—the type may be using the genericity as a shorthand/convenience, but the initializers might always set it to a specific type.  And making the genericity of the type visible/obvious via a type constructor/initializer (and/or need for one) feels like a more principled way of exposing that in the code to an end-user to me.  (I'm way behind on #21456, so there may be great ideas springing up there that I just haven't seen yet).

**Comment by bradcray** [comment]
w.r.t.

> What about making the warning focus on the genericity of the record? E.g., it could say "record R is generic in a potentially surprising way since it is only generic due to 'myC' being generic but that might be surprising because 'myC' has a declared type". IMO, that changes the focus from "You can't do that with a field but you can with variable" to "There are only certain reasonable ways to create a generic class/record".

I think my feeling in the previous comment doesn't change much:  I agree it would help address my symmetry concern.  But I'm not convinced that I'd want to change my code to address the warning, nor that my code would be better/improved if I were to rework it until the warnings went away.  So it would remain a warning that I wouldn't be particularly happy we had rather than one that would make me think "yes, good point, let me address that."

And I still worry that in the same way that:

```chapel
var c: C;
...
c = new shared C(int);
```

isn't really creating a generic variable `c`, that:

```chapel
record R {
  var c: C;
  proc init() {
    this.c = new shared C(int);
  }
}
```

isn't really creating a generic record `R`.  And the things I believe I'd need to do to make the warning go away seem like net negatives on the code clarity and quality, so I remain reluctant to have the warning on by default.

**Comment by mppf** [comment]
Closing this PR. It served its purpose. I'll be looking at doing slightly different things in other PRs.

**Pull request closed without merging**
