### PR TITLE
Add an array checkpointer that is parallel across locales

### PR DESCRIPTION
**Pull request by daviditen**
This is parallel across locales, but not within each locale.  It should work for any array that
implements the DSI.

It writes the arrays elements to a file with each locale writing the elements it owns into
a single block in the file.

### CODE REVIEW

**Comment by bradcray** [comment]
@daviditen: I take it this should get the post-release tag?

**Comment by daviditen** [comment]
I added the post-release tag.

**Comment by bradcray** [comment]
This came up in discussions today.  What remains to be done to merge it?

**Comment by daviditen** [comment]
I think it can be merged in this test form today.

**Comment by daviditen** [comment]
Thanks!

**Comment by daviditen** [comment]
Add an array checkpointer that is parallel across locales

[Reviewed by @dlongnecke-cray]

This is parallel across locales, but not within each locale. It should work for any array that
implements the DSI.

It writes the arrays elements to a file with each locale writing the elements it owns into
a single block in the file.

**Pull request merged**
