### PR TITLE
Contributors list for Chapel 1.19

### PR DESCRIPTION
**Pull request by bradcray**
This is an update to the CONTRIBUTORS list to call out those developers who contributed to the code, documentation, and files that will appear in the 1.19 release.

### CODE REVIEW

**Comment by bradcray** [comment]
@chapel-lang/chapel-contributors : Did I forget anyone?  Get anything else wrong?
@KING-SID  @namanchikara : Would you verify that I spelled your names correctly?

**Comment by KING-SID** [comment]
@bradcray Perfect on my end!

**Comment by ben-albrecht** [comment]
As of this morning, + @AnubhavUjjawal: Anubhav Ujjawal, individual contributor

**Comment by bradcray** [comment]
Great, thanks @ben-albrecht and @AnubhavUjjawal , I've updated it (but please double-check me).

**Comment by ben-albrecht** [comment]
As of today, + @krishnadey30, Krishna Kumar Dey, individual contributor

**Pull request merged**
