### PR TITLE
update copyright to include 2023

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
To address the issue https://github.com/Cray/chapel-private/issues/4109.

Updating copyrights in the files in all the folders excluding the folders "third-party" and "test".

Commands used:
git grep -l 'Copyright 2020-2022'  -- ':!third-party/**' ':!test/**' | xargs sed -i '' -e 's/Copyright 2020-2022/Copyright 2020-2023/g'

git grep -l 'Copyright 2021-2022'  -- ':!third-party/**' ':!test/**' | xargs sed -i '' -e 's/Copyright 2021-2022/Copyright 2021-2023/g'

git grep -l 'Copyright  2022'  -- ':!third-party/**' ':!test/**' | xargs sed -i '' -e 's/Copyright 2022/Copyright 2022-2023/g'

Included the files :doc/rst/conf.py
 util/test/checkCopyrights.bash

Signed-off-by: bhavanijayakumaran <82669529+bhavanijayakumaran@users.noreply.github.com>

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Let's reference the original PR in this PR message and its merge message, so that we don't lose any reminders about weird files for next year

**Review by lydia-duncan — APPROVED** [review]
Other than the comment about referencing the old PR, I think this is good to go!  It looks like you're including the same number of files and I did a spot check on some of the problem ones from the original PR.

**Comment by bhavanijayakumaran** [comment]
> Other than the comment about referencing the old PR, I think this is good to go! It looks like you're including the same number of files and I did a spot check on some of the problem ones from the original PR.

Thanks @lydia-duncan

**Comment by bradcray** [comment]
Doing a quick post-merge sanity check on this, I noticed the following file: `util/build_configs/cray-internal/chapel.modulefile.lua.template`.  I'm not that familiar with its purpose (and didn't go looking into it), but from the name, my guess is that it's involved in creating the Lua-based module for Cray systems, so should probably be updated.  Tagging @ronawho and @jhh67 as Greg's successors (though this is not necessarily something that was probably handed off explicitly).

**Comment by ronawho** [comment]
Yes, `util/build_configs/cray-internal/chapel.modulefile.lua.template` is a template for the lua-based modulefile. The copyright just looks to be a lua comment and not something that ends up in the generated module. I think it could just be removed (the tcl version doesn't have one)

**Pull request merged**
