### PR TITLE
Add some error checking to jemalloc shim and do some minor cleanup

### PR DESCRIPTION
**Pull request by ronawho**
Add error checking to all the appropriate je_* calls. Doing so caused me to
realize I was using `unsigned` for the number of arenas instead of `size_t`. I
think I was using an old man page when I did that, so I updated all references
to the man page to include the version number.

This also removes a duplicate "initialization" of arena 0

### CODE REVIEW

**Comment by ronawho** [comment]
@gbtitus mind reviewing? It's a pretty small change, but it might be easier to review commit by commit

**Comment by ronawho** [comment]
actually, hold on a sec. I just caught a mistake. Will push a fix in a minute

**Comment by ronawho** [comment]
Pushed fix, good to review whenever you're ready

**Comment by gbtitus** [comment]
Looks good, modulo that one comment on a line.

**Pull request merged**
