### PR TITLE
Add annotation for Arkouda fillrandom

### PR DESCRIPTION
**Pull request by bmcdonald3**

### CODE REVIEW

**Comment by bradcray** [comment]
It continues to be intriguing to me that generating a random PCG array in Arkouda became competitive with creating an array of 1's, which seemed surprising.  Asking @mppf: Is PCG *that* efficient?

Graphs:
https://chapel-lang.org/perf/arkouda/16-node-cs-hdr/?startdate=2022/07/08&enddate=2022/07/21&graphs=arraycreationperformance
https://chapel-lang.org/perf/arkouda/16-node-xc/?startdate=2022/07/08&enddate=2022/07/21&graphs=arraycreationperformance

**Comment by mppf** [comment]
@bradcray - if the thing limiting performance is memory bandwidth, then I could believe that PCG code to generate 32-bit ints isn't slow enough to negatively impact performance. Nonetheless it would be reasonable to double-check that Arkouda is actually getting reasonably varying array elements out of the fillRandom.

**Comment by bradcray** [comment]
> it would be reasonable to double-check that Arkouda is actually getting reasonably varying array elements out of the fillRandom.

I know the Arkouda team did some validation of the random spread in their switchover to bounded fillRandom().  I don't think that we've done any such testing with our performance test, though.

**Comment by bradcray** [comment]
I think @ronawho was out when this result came in, so I wanted to make sure he'd seen it.  I also want to assert that while it probably seems otherwise, I'm not deeply concerned about it.

**Comment by ronawho** [comment]
Thanks for the heads up.

This improvement makes sense to me. The old code was effectively doing:

```chpl
fillRandom(a);
const a2 = a:uint
a = (a2 % aMax-aMin):t + aMin:t;
```

And the new code is just doing:

```chpl
fillRandom(a, aMin, aMax);
```

So we've gotten rid of an array creation and a second pass over the array and that second pass included a mod. Assuming the rng generation is only a few cycles I would expect it to be about as fast as filling with ones. I agree it's almost certainly memory bandwidth bound so removing extra arrays and passes over the array will have the biggest impact.

On 128-core Rome on [16-node-cs-hdr](https://chapel-lang.org/perf/arkouda/16-node-cs-hdr/?startdate=2022/03/11&enddate=2022/08/08&graphs=arraycreationperformance) filling with ones and random values takes the same time and 128 cores oversaturates memory bandwidth so a few extra cycles won't be noticeable.

On 48-core CLX on [16-node-xc](https://chapel-lang.org/perf/arkouda/16-node-xc/?startdate=2022/03/11&enddate=2022/08/08&graphs=arraycreationperformance) filling with random values still lags a bit. This tracks with other bandwidth bound codes where the higher core count on Rome drives memory hard enough that a few extra operations per iteration don't matter, but the impact is more visible at lower core counts (I saw this same behavior with scans in https://github.com/chapel-lang/chapel/pull/19999 where getting narrow pointers helps with fewer cores, but has no impact on 128-core rome.)

**Pull request merged**
