### PR TITLE
Add 'vector' type as package

### PR DESCRIPTION
**Pull request by benharsh**
This PR adds a 'vector' type as a package. It supports the same functionality as the vector ops on arrays. There are a number of design topics that we may want to discuss before merging:

- name of the type: some have proposed 'list', but we already have that (as a linked list)
- method names
- error handling
- parallel safety

### CODE REVIEW

**Comment by benharsh** [comment]
@mppf : want to review?

@bradcray , @ben-albrecht : do you two still prefer the name 'list' for this type? If so, do you have an idea about what we should do with the existing 'list' type?

**Comment by mppf** [comment]
>     * does it move elements on growing (I want the answer to be no, for parallel safety reasons, as we discussed)

Another question is - does it have the capability to move elements at all?

If it can't move elements at all, we can't have:
 * `pop(i)`
 * `remove(i)`
 * `insert(i, elt)`

I think it'd be reasonable to go either way on this. I think it's really important `append` does not invalidate references to the elements, but we could live with having such a reference and then doing a `remove` earlier being a user error IMO.

**Comment by mppf** [comment]
> In my mind the key methods available here are:
>  * element access
>  * element iteration
>  * push on the back / append
>  * pop from the back
>  * clear all elements

I'd like to add this one, which isn't in the PR yet:
  * clear all but the first n elements (aka "resize")

Here is what I think the method names should be:
 * `this(i)` element access
 * `these` element iteration
 * `append` push on the back / append
 * `expand` push on the back / append in bulk
 * `pop` pop from the back
 * `popMany` / `contract` / `multiPop` / something ? pop from the back in bulk
 * `clear` clear all elements
 * `clear(i)` clears all but the first i elements (I'd be also ok with `resize`)

**Comment by bradcray** [comment]
Of the pre-merge design discussions @benharsh asks about in the PR message, I think all deserve discussion (e.g., as issues and/or in a deep-dive), but that probably only the name of the module and type need to be decided on before merging (and even those could arguably be postponed briefly).

On that question, I prefer `list` for the type and `List` for the module over `vector`/`Vector` (and apologize for not having remembered this earlier), but think that this choice should also be run past the team.  I don't have a strong opinion about what the current list type should be renamed to, though I'm definitely open to `linkedList` and `LinkedList`.  I'd also be open to making it something that's intended for internal use only (and which will hopefully eventually be retired in its internal uses) as I think that's the main reason it exists today (?).

As far as naming methods, I generally think that following Python's lead (over C++'s) would be preferable, and in particular would like to get away from underscores in the method names.  (I'm guessing that much of the current design is based on what we've supported for the array-as-vec work?)

I have no strong opinion on parallel safety or error handling at present, though I may eventually (and wouldn't hold up putting a first draft in over those questions).  Ditto the questions related to whether to use arrays for the implementation or not, to have references be guaranteed to be accurate across resizings, etc.

**Comment by bradcray** [comment]
Discussing more with @benharsh offline and thinking specifically about the transition path from array-as-vec to the ultimate `list` type we want (and particularly the timing w.r.t. the release), I'm currently thinking that the best path forward might be to support a `vector` type for this release, solely for the sake of getting peoples' weight off of array-as-vec and onto a library-based type; but with the intention that, ultimately, we'd hope all `vector` uses would convert to the (to be designed and implemented) `list` and/or `deque` types.  If possible, I'd like to discuss tomorrow during OH with @benharsh, @mppf, and @ben-albrecht.

**Comment by benharsh** [comment]
Closing this for now - this code will probably return as a 'deque' after some further design discussion.

**Comment by benharsh** [comment]
Some new issues: #12411 and #12412

**Pull request closed without merging**
