### PR TITLE
Enable bulk-transfer for BlockDist by default

### LINKED ISSUE #11298: BlockDist to DefaultRectangular assignment not triggering bulk comm
Figure out why assignment from BlockDist to DefaultRectangular is not triggering bulk comm and why it's creating parallelism on a machine that already has numCores/here.maxTaskPar tasks running. 

I'm a little sparse on details at the moment, but for context this is from https://github.com/StanfordLegion/task-bench/commit/c05970df9c064ad5e6165714066b2c7c01502900. Here we were expecting the assignment to trigger bulk communication, but it didn't. It also created additional tasks (when `here.maxTaskPar` tasks are already running), which significantly degraded performance of the rest of the application. So far as I know all of our parallel iterators will check how busy the node is and not create additional tasks if we're already using `here.maxTaskPar` tasks, so that part was especially confusing to me.

### PR DESCRIPTION
**Pull request by benharsh**
This PR enables the bulk-transfer optimization for BlockDist by default, which supports transfers to/from Block and DefaultRectangular arrays. This PR also enables support for bulk-transfers involving rank changes.

#### Implementation Simplification

The various bulk-transfer methods used to rely on the 'bulkCommConvertCoordinate' function to help translate indices from one domain to another, and then creates a domain from the low/high endpoints.

This PR creates a new DSIUtil function "bulkCommTranslateDomain" to replace this functionality and encapsulate the crufty range-to-domain logic. This domain-translation function leverages some pre-existing helper functions: densify, unDensify, and the new 'bulkCommComputeActiveDims' (formerly 'computeActiveDims' in DefaultRectangular.chpl). The first two functions help translate a slice of a domain into the space of another domain. The last function comes into play when a rank-change occurs, and identifies which dimensions need to be translated.

This PR introduces a helper iterator, 'activeTargetLocales', which when given a domain will yield indices in 'targetLocDom' that own chunks of the given domain. This iterator is used to reduce the number of on-statements.

The implementation of "Block = Block" formerly used some complicated iterators ('dropDims' and 'ConsecutiveChunksD') to find compatible chunks between differently-distributed Block arrays. These iterators can now be replaced by a combination of 'activeTargetLocales' and 'bulkCommTranslateDomain', which can easily identify and translate chunks of domains that can be bulk-transferred.

#### Optimizations

This PR does some manual privatization within coforall-on statements to avoid unnecessary GETs for metadata. This optimization relies on the privatization implementation privatizing on every locale.

#### Testing

There are a number of pre-existing tests for Block's bulk-transfer implementation under ``optimizations/bulkcomm/{alberto,asenjo}``. These tests are unchanged by this PR, but I have observed that some of the examples in these tests do not run because of mistakes in creating slices of matching sizes. I have created a pair of tests that check some common cases:
1) blockToBlock: This test checks bulk-transfers between block-distributed arrays where the distributions do and do not match, and for 1/2/3-dimensional arrays. The individual transfers attempt to test a combination of dense/strided arrays with dense/strided slices, slices representing a single element, dense slices over the middle of the array, and a simple rank change.
2) toFromDR: This test checks a similar set of transfers, but between a Block array and a DefaultRectangular array instead of Block arrays with potentially-different targetLocales.

While testing I observed that the 'assignReindex.chpl' test was incorrectly assigning between arrays whose domains' size did not match, formerly hidden by throwing ``--fast``. This PR updates the test in two ways:
1) Uses a reindex that isn't the same as the original domain (unnecessary, but seems better)
2) Slices the reindex to the correct size.

Note that this results in *increased* communication counts due to the extra slice.

#### Miscellaneous

The GASNet communication layer has been updated to only increment counts for strided GETs and PUTs when communication actually occurs. Formerly the layer would increment for entirely local operations.

Open questions:
- Should we have a config param to disable this optimization in case of bugs?

Resolves #11298

Testing:
- [x] local + futures
- [x] gasnet + futures
- [x] DistType.{block,cyclic,replicated}

### CODE REVIEW

**Comment by benharsh** [comment]
Reviewer: Do you want to see more testing? A lot of the implementation relies on the domain-translation helper function, but otherwise relies on DefaultRectangular-to-DefaultRectangular transfers (which seems stable). The DefaultRectangular stuff tests against more kinds of domains, but Block stuff takes a lot longer to compile+run, FWIW.

**Comment by benharsh** [comment]
Some performance results for ``optimizations/bulkcomm/block/exchange.chpl``:
|     | master GETs  | PR GETs  | master on-stmts  | PR on-stmts  |
|---|---|---|---|---|
| elegant  | 122k  | 1637  |  615  | 520  |
| destLocal  | 121k  | 809  | 270  |  270 |
|  bothLocal | 93  | 93  | 13  | 13  |

**Comment by benharsh** [comment]
I added a config-param at @bradcray 's suggestion, and added a test to make sure it works. @vasslitvinov : does it look good to you?

**Comment by vasslitvinov** [comment]
@benharsh - sure, a param is fine.

**Pull request merged**
