### PR TITLE
Make use of 'use <enum>' in meteor

### PR DESCRIPTION
**Pull request by bradcray**
This was one of the few tests in release/examples that really felt
unwieldy to have to refer to an enum's name every time we wanted
to reference it.  As a result of Lydia's recent work, we now don't
need to.  As part of this change, I also made the enum have a more
descriptive name since I believe 'D' was chosen in part to avoid the
overhead of typing it every time...

I scanned the rest of release/examples to see if there were other
cases that would benefit from this type of cleanup, but thought
the other cases weren't bad as-is.  Outside of release/examples,
there are many cases that could benefit from this, but addressing
those more lazily seems like the right thing to do.

### CODE REVIEW

**Comment by bradcray** [comment]
This PR may be of interest to anyone on the perf team:  @lydia-duncan , @ronawho , @benharsh, @ben-albrecht, ...

**Comment by lydia-duncan** [comment]
Not to go too out of hand, but maybe the meteor change should be reflected to the studies/shootout/meteor implementations?  I wouldn't push for a larger expansion of this PR, but it'd be a shame for those versions to end up too out of sync

**Comment by lydia-duncan** [comment]
Looks nice otherwise!

**Comment by ben-albrecht** [comment]
Looks great to me. I didn't see any other examples that need this change either. :+1: to [Lydia's other comment](https://github.com/chapel-lang/chapel/pull/3385#issuecomment-190472169) as well.

**Comment by bradcray** [comment]
That's a good point...

**Comment by bradcray** [comment]
Updated to apply same change in studies versions...

**Comment by lydia-duncan** [comment]
:sparkles: (assuming you ran them)

**Pull request merged**
