### PR TITLE
Replace ":throws: Error:" with ":throws Error: "

### PR DESCRIPTION
**Pull request by cassella**
This seems to be the form chpldoc is expecting that all the other modules but these use consistently, and formats the `Error` specially in the docs.

### CODE REVIEW

**Comment by cassella** [comment]
I've looked over some of the resulting docs, which look like improvements to me.

TODO: look over the remaining changed docs, and go through the git log to find a vic^H^Holunteer.

**Comment by cassella** [comment]
I'm not sure the first few ArgumentParser formatting changes is an improvement; there's now a newline between `ArgumentError` and the description; I guess because the description is multiline?

@arezaii , you added those; what do you think?

**Comment by arezaii** [comment]
I agree those look odd - let me see if I can determine why. It seems to have something to do with the list of items I'm trying to include as reasons for the error.

**Comment by arezaii** [comment]
Looked at this for a bit, no obvious answer - it may require some adjustment to our [sphinxcontrib-chapeldomain](https://github.com/chapel-lang/sphinxcontrib-chapeldomain) package to customize the behavior. I think the best thing to do for now would be to update those items with lists after them to include backticks e.g., ```:throws: `ArgumentError` in any of the following conditions:```, which will apply *some* formatting, and just update the others until we have time to look at it further.

**Comment by cassella** [comment]
I redid the ArgumentParser change to use `:throws:`  and backticks around `ArgumentError` everywhere, so that the module's doc would have consistent formatting throughout.

I opened #22251 to cover the extra line break.

**Review by arezaii — APPROVED** [review]
Thanks for catching and correcting these differences @cassella!
I looked at the generated artifact from the CI check and the docs LGTM.

**Comment by cassella** [comment]
I should point out that I didn't test anything besides `make docs`.

**Pull request merged**
