### PR TITLE
Stop stack allocating due to begin

### PR DESCRIPTION
**Pull request by bradcray**
While working on 1.12 release note slides today describing the decision to not keep variables alive after their lexical scope due to references within begins, I found myself wondering whether we still move such variables to the heap (we do) and how hard it would be to stop that (a 5-minute fix (TM)).  For a program like the following, for example, the variable 'xyz' was heap allocated before and is now stack allocated with this change.

    var flag$, flag2$: sync bool;
    {
      var xyz: int;
    
      begin with(ref xyz) {
        xyz = 123;
        writeln("xyz is: ", xyz);
        flag2$ = true;
        flag$;  // block until flag is set
        writeln("xyz is: ", xyz);
      }
      flag2$;  // block until flag2 is set
      writeln("xyz is: ", xyz);
    }
    flag$ = true;

Testing this turned up two variables that relied on the old semantics.  I made minor mods to these programs to make them work deterministically under the new semantics.

### CODE REVIEW

**Comment by bradcray** [comment]
It's passed linux64 (which is how the two test updates were found) and has passed gasnet-fast testing on test/release, test/multilocale, and test/parallel.

**Comment by noakesmichael** [comment]
I am not very good at judging gasnet testing but I am OK with that if you're OK with that.

Regards,

Mike

**Comment by bradcray** [comment]
Hi @noakesmichael -- Ready for re-review (note that I did not re-test other than my small sample program).  I'm noting that the test for non-blocking case could be another case that could be removed under the new semantics, but I'm saving that for another PR because it's more speculative and will require more testing.

**Comment by noakesmichael** [comment]
Looks good to me.  Don't stay up too late.

**Comment by ronawho** [comment]
Sorry, being nosy since this is code I recently looked at:

I think there's a few top level comments that probably need to be updated (deleted?):

https://github.com/bradcray/chapel/blob/noStackAllocBecauseOfBegin/compiler/passes/parallel.cpp#L58

https://github.com/bradcray/chapel/blob/noStackAllocBecauseOfBegin/compiler/passes/parallel.cpp#L71-L75

Also, really minor but your title says 'stop **stack** allocating'

**Comment by ronawho** [comment]
Also, nice change :+1: 

I *think* this change means that you can also remove a bunch of confusing and potential expensive code from `freeHeapAllocatedVars()` that prevents freeing heap allocated vars that might be used in a `begin`

I'm pretty sure all of the following is now unnecessary:

https://github.com/bradcray/chapel/blob/noStackAllocBecauseOfBegin/compiler/passes/parallel.cpp#L552-L568

https://github.com/bradcray/chapel/blob/noStackAllocBecauseOfBegin/compiler/passes/parallel.cpp#L598-L623

Should be another pretty satisfying commit. Also, I don't mean to suggest that should be part of this PR, just wanted to point it out

**Comment by bradcray** [comment]
Thanks for the deeper look Elliot.  Since I've already got a pending improvement in progress and am short on coding/testing time this week, I'm going to take your suggestions as TODOs in that pull request.

**Comment by bradcray** [comment]
@ronawho: I believe in my latest PR I addressed your first round of feedback above.  Branch predicting, I don't think that I'm going to have time to consider tackling your second this week (the satisfying code simplification), primarily because of lack of familiarity with that code and the safety of it not being clear to me (and not having the time to get to that level).  If you need a break from slides and want to grab it, please do.

**Comment by ronawho** [comment]
Are you sure you want to give me an excuse to not work on slides? :)

I'll let you know if I start working on it, but will leave it up for grabs in the meantime.

**Comment by bradcray** [comment]
Well, I suspect you're further on your slides than I am...  after all, it was working on my first slide that caused me to start developing these patches.  :)

**Pull request merged**
