### PR TITLE
Switch from using optparse to argparse in gengraphs

### PR DESCRIPTION
**Pull request by ronawho**
optparse is deprecated. More importantly I want to use the nargs capability for
graphs with multiple configurations and that's only available with argparse

### CODE REVIEW

**Comment by ronawho** [comment]
@Kyle-B mind reviewing? Should be an easy one

**Comment by thomasvandoren** [comment]
FYI argparse was not added until python 2.7, so we'll need to update the perf jobs to install the argparse package. We already install the PyYAML package for the perf jobs, so it will be easy.

**Comment by ronawho** [comment]
interesting. Do you know how we get away with syncPerfGraphs.py and spliceDat using argparse?

**Comment by Kyle-B** [comment]
We do use 2.6 as the baseline for all of our python scripts currently, but I think our test machines already have the argparse package installed at the system level.

**Comment by thomasvandoren** [comment]
It looks like we already install argparse in the virtualenv that perf tests run in, too. Sorry for the diversion!

**Comment by ronawho** [comment]
Kyle had a good point that using argparse in gengraphs would require anybody doing performance runs on their local machine (say to investigate a perf regression) to have 2.7 installed if this went in. I'm gonna close this PR and continue to use optparse

**Pull request closed without merging**
