### PR TITLE
Work around a bug in orderedSet

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR works around a bug in OrderedSet.

Resolves https://github.com/chapel-lang/chapel/issues/18656

The bug in question is captured in
https://github.com/chapel-lang/chapel/issues/18656#issuecomment-955055822.

The solution for the bug is to make the internal treap field use `?` for the
generic comparator field. Doing that caused some issue in `&` and `&=` operators
because now, that field is generic to the compiler, and it cannot split-init
with these operators' implementations. The solution for that is explicit
initialization.

Then that posed the question "if I am &'ing two orderedSets, how do we determine
the comparator of the resulting orderedSet?" For now, we use the first operand's
comparator.

Test:
- [x] library/packages/OrderedSet
- [x] standard

### CODE REVIEW

**Comment by e-kayrakli** [comment]
@rapiz1 @krishnadey30 @cassella -- Changes here are trivial, but I made an arbitrary design decision about the comparator of the result of an `&`. I wonder if it sounds awful to any of you.

**Comment by rapiz1** [comment]
I wonder if it would be better if we always use the comparator from `lhs`. e.g. In both A&=B and A&B, we use A.  Using the defaultCmp if type not matched doesn't come to my mind first if I see A&B. If we do this way, a note on the operator can be added.

**Comment by cassella** [comment]
For comparison, `A|B` uses's `A`'s.  (Since it starts by setting `result = A`.)

`-` however always uses `DefaultComparator` even if `A` and `B` have the same. comparator  Oops.

`^` uses `A`'s, but I don't see how.  It's split init where the two sides of the non-param `if` return different types (if `a` and `b` are different types).

**Comment by e-kayrakli** [comment]
OK. I took the first operand's comparator. Feels more natural as that's what happens in &=, which is arguably obvious. Thanks for the input! I am running a full paratest just in case, will merge afterwards.

**Comment by e-kayrakli** [comment]
For the record:

The bug report: https://github.com/chapel-lang/chapel/issues/18664
Related design question: https://github.com/chapel-lang/chapel/issues/18665

**Comment by bradcray** [comment]
Thanks for jumping on this, Engin!

**Pull request merged**
