### PR TITLE
Report message size under verbose communication

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR adds message size to the verbose communication output for non-strided cases. The message size is appended to the current verbose comm output as `, N bytes`

~Currently work-in-progress. TODO:~

- [x] Add message size for ugni
- [x] Confirm we don't need to modify anything for ofi
- [x] Confirm `%zu` is portable enough for printing `size_t` variables
- [x] Any test changes?

### CODE REVIEW

**Comment by ronawho** [comment]
Hey Engin, @mppf and/or @gbtitus are probably the right people to look at this, but we're in bug-fix/doc freeze now so it'll probably be a little while before we get around to looking at it.

**Comment by gbtitus** [comment]
I'll take it.  What's here looks like a good start.  Some other things:
- In addition to the 2 alternatives you listed you might also consider just ", %zu bytes" for the phrasing.  But I think this is programmer's choice, or burden, take your pick.  :-)
- Yes, comm=ugni needs doing and also yes, comm=ofi does not; the latter is not yet far enough along.  I'll take care of that one.
- The `%zu` format should be exactly right for `size_t` values.
- There probably are some test changes but they should be easy to find.  Check the docs hierarchy also, these messages might be listed there as well.  (Being lazy, I did not look myself.)

**Comment by e-kayrakli** [comment]
Last batch of commits 
- changes the phrasing as suggested by @gbtitus 
- adds the message size on ugni
- adds the message size on CommDiagnostics.chpl documentation

For nightlies:
`grep -Rinl verbosecomm test` shows

```
test/performance/sungeun/multilocale/locale.chpl
test/performance/sungeun/multilocale/locale.id.chpl
test/performance/sungeun/multilocale/syncsingle.chpl
test/parallel/taskPar/sungeun/endCountTest.chpl
test/multilocale/deitz/needMultiLocales/test_frag_main.chpl
test/multilocale/deitz/needMultiLocales/diagnostics/test_private_broadcast_large.chpl
test/multilocale/deitz/needMultiLocales/diagnostics/test_private_broadcast_small.chpl
test/optimizations/sungeun/RADOpt/access.chpl
test/optimizations/rafa/2dAgTest.chpl
test/optimizations/rafa/AgTest.chpl
test/extern/diten/externfaston.chpl
test/distributions/robust/arithmetic/performance/multilocale/assignReindex.chpl
test/distributions/robust/arithmetic/performance/multilocale/alloc.chpl
test/distributions/robust/arithmetic/performance/multilocale/alloc_all.chpl
test/distributions/robust/arithmetic/performance/multilocale/assignSlice.chpl
```
None of which seems to use verbose communication in nightly testing.

I used a simple test that does
```chapel
use CommDiagnostics;
var a = 0;

startVerboseComm();
on Locales[1] {
  a = 1;
}
stopVerboseComm();
writeln(a);
```
which I can add. But I am not sure whether it is necessary.

@gbtitus - I think for now I am done and waiting next round of feedback from you. It'd be great if you can run a full test with at least gasnet.

**Comment by gbtitus** [comment]
This looks great but sure enough, we do not test this feature!  Would you mind adding your little feature test shown above, say in a new `test/multilocale/e-kayrakli/needMultiLocales/` directory?  It could look a lot like what's in `test/multilocale/gbt/needMultiLocales/`, but I think the only files you'll need are:
```
verboseComm.chpl
verboseComm.good
NUMLOCALES
SKIPIF
```

**Comment by e-kayrakli** [comment]
@gbtitus sure I will add the test.

**Comment by e-kayrakli** [comment]
@gbtitus -- test added.

I also updated the PR message to note that this doesn't add the message size for strided communication. I believe I can do that in a subsequent PR, but I am not sure whether that information is as useful as it is for non-strided cases.

**Comment by gbtitus** [comment]
Apologies, @e-kayrakli , without thinking (because I was working on something else pressing) I merged a recent PR that conflicts with part of this, as shown by the github warning now present.  Basically it moved the check for whether we should do verbose comm reporting or comm diags into common code, but as such it affected the same areas your change does.  Would you mind adjusting this PR to remove that conflict?

**Comment by e-kayrakli** [comment]
@gbtitus - I fixed the conflicts.

Also noticed that in your refactor PR that conflicted with this, you haven't updated verbose comm calls coming from `chpl-cache.c`. Most likely you are aware of that but anyways...

**Comment by gbtitus** [comment]
Full testing with comm=gasnet passes, merging ...

**Pull request merged**
