### PR TITLE
Update getCurrentTime() to return (hours, minutes, seconds)

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Fixes https://github.com/chapel-lang/chapel/issues/14571

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@BryantLam @ben-albrecht @bradcray  I have made some changes, please have a look. 

I will add tests once the changes are approved.

Also by looking at the source code, it seems like `getCurrentTime` is used in a lot of `test` files as well as some modules, I will proceed with the changes required in those modules and files, once the new structure of the function is finalized. :smile: 

Thanks!

**Comment by Aniket21mathur** [comment]
@ben-albrecht that's my bad, I was not aware of that, though thanks for correcting :smile:.

Sure, I will do some work around and will post my observations on the issue comments.

**Comment by bradcray** [comment]
Also, for future reference, not that any change to this routine would also need to change any / all tests that call it so that they continue working.

**Comment by Aniket21mathur** [comment]
We have some discussion about the design on the issue thread and it would be great if we continue the discussion there. I am closing this pull request for now, until we have a finalized design :-)

**Pull request closed without merging**
