### PR TITLE
feature(Version): draft a single type for param/non-param

### PR DESCRIPTION
**Pull request by arezaii**
This PR implements a draft of the changes proposed 
in https://github.com/chapel-lang/chapel/issues/19201#issuecomment-1205572405.

Signed-off-by: arezaii <ahmad.rezaii@hpe.com>

### CODE REVIEW

**Comment by arezaii** [comment]
Trying to refactor `mason` to use this directly led to some issues, mostly due to the 
fields of `sourceVersion` being `const` rather than `var`. 

I don't think it is strictly necessary to keep these fields as `const`, and if not, I will try changing them to `var` and see how that affects the `mason` use case.

**Comment by bradcray** [comment]
@arezaii : I'm curious, having implemented and tried to use this, whether you feel more positive about it than the previous, two type approach, or not.

I'm guessing you didn't do this simply to reduce work / minimize diffs, but I'm imagining we'd rename the record to simply `version` since this makes it more general-purpose (and I think a big part of the name `sourceVersion` was to indicate that it was a version you'd want to embed statically into your source due to its param nature).

> Trying to refactor mason to use this directly led to some issues, mostly due to the
fields of sourceVersion being const rather than var.

Can you give some examples of why this caused problems for mason?  E.g., does mason create versions and then try to go poke other numbers into them, or was it something else?

The rest of this is a bit academic, though I'd be curious for your reactions:

The diff was larger than I had hoped, which I see is because we had to create
param-returning and non-param-returning versions of most of the key
operators like casts and comparators, is that right?

This reminds me of a feature we kick around every so often but have not yet
committed to, which is a way to say something like:

* `param(true)` == `param`
* `param(false)` == `const`

such that you could say something like:

```chapel
proc foo(param(?p1) arg1, param(?p2) arg2) param(p1 && p2) { ... }
```

or:

```chapel
proc foo(param(?) arg1, param(?) arg2) param(isParam(arg1) && isParam(arg2)) { ... }
```

Seems like such a feature would've helped here?  Or are there other important differences that I'm glancing past too quickly?

Am I correct that the main (only?) testing changes were to add cases that test the new non-param version?

**Comment by arezaii** [comment]
> Am I correct that the main (only?) testing changes were to add cases that test the new non-param version?

I did add test cases for the new version, and also cases where the new and old versions were compared to each other, with old and new taking turns as the LHS or the RHS of the operator.


> Can you give some examples of why this caused problems for mason? E.g., does mason create versions and then try to go poke other numbers into them, or was it something else?

Basically there are patterns where mason wants to create an empty, or known value return object, then update it conditionally with values, and return either the updated object or the known value object. 

There is also a pattern of creating a known value object, then searching for a suitable lower version number and updating the last known highest version along the way. 

Both of these patterns could probably be expressed another way, but at least trying to do a basic replacement of the existing mason `VersionInfo` with the `const` fields in `sourceVersion` was not successful. 

I got to a point where I could either get creative about refactoring those algorithms, or I ask why these fields need to be `const` in the first place. My thought is that we already provide a very (most?) restrictive `sourceVersion` with the `param` fields, so rather than just a slightly less restrictive variant with `const` fields, we could provide a sort-of least restrictive variant (obviously not _least_ as the fields aren't totally generic, etc.)

**Comment by bradcray** [comment]
I'm definitely open to making the non-param `version` have modifiable fields.  I think the reason I was hoping `const` would be sufficient was that it would only require "reader" versions of the paren-less methods where now I think we'll need reader/writer overloads (which I think will depend on `ref` return intent overloading which is a feature I'm not crazy about and keep hoping we'll ditch).  But I agree that once the param-ness is off, a record that stores variable fields is much more flexible and general-purpose, so preferable.

**Comment by arezaii** [comment]
Changing the fields to `var` made this a little better. I didn't add writer methods as we don't update individual fields at a time, we just want to be able to swap out one object for another.

One remaining pain point is that if I want to create a `sourceVersion` with known values and later replace it with a different version. In this case, the typical use would be something like:
```
proc getVersion(otherVer: sourceVersion) {
  var ret = createVersion(-1,-1,-1);
  if (someCondition) {
    ret = otherVer;
  }
  return ret;
}
```

In this case, the `ret` variable gets instantiated with `param` fields, so it can't be updated by assignment later. 

The work-around I've put into the `mason` prototype is to declare some `const` variables and use those to build the version, like so:

```
proc getVersion(otherVer: sourceVersion) {
  const negOne = -1;
  var ret = createVersion(negOne, negOne, negOne);
  if (someCondition) {
    ret = otherVer;
  }
  return ret;
}
```

This is not terribly convenient and I'd like to explore if we should/how we could offer a way to create a non-param `sourceVersion` when the values are known at compile time.

**Comment by bradcray** [comment]
> as we don't update individual fields at a time

When you say "we" here, are you meaning "mason doesn't want to do this" or "nobody would ever want to do this" or "maybe we as the type designers don't want to permit people to do this"?

> One remaining pain point is that if I want to create a sourceVersion with known values and later replace it with a different version.

Hmm, that's an interesting challenge.  For the specific patterns you show here, I almost wonder whether we should support:

```chapel
proc getVersion(otherVer: sourceVersion) {
  var ret: version;  // defaults to a non-param implementation with sentinel values like (-1, -1, -1, "")
  if (someCondition) {
    ret = otherVer;  // permit assignment to it
  }
  return ret;
}
```

but, granted, that could be considered too specific to this pattern.  Out of curiosity, what does the failure mode look like if you do:

```chapel
proc getVersion(otherVer: sourceVersion) {
  var ret = createVersion(-1,-1,-1);
  if (someCondition) {
    ret = otherVer;
  }
  return ret;
}
```

on your branch?

**Comment by arezaii** [comment]
> When you say "we" here, are you meaning "mason doesn't want to do this" or "nobody would ever want to do this" or "maybe we as the type designers don't want to permit people to do this"?

I mean the former, mason doesn't do this, but I believe that in the most flexible model we would allow users to do it.

> Hmm, that's an interesting challenge. For the specific patterns you show here, I almost wonder whether we should support 
```chapel
proc getVersion(otherVer: sourceVersion) {
  var ret: version;  // defaults to a non-param implementation with sentinel values like (-1, -1, -1, "")
  if (someCondition) {
    ret = otherVer;  // permit assignment to it
  }
  return ret;
}
```

I think this would solve our specific problem, but I don't really like it for a general purpose solution. From the user perspective, I just want to assign between two `sourceVersion`s and the inability to do it is frustrating. I'm not sure if having one foot in the `param` space is going to allow the kind of flexibility I would want from a built-in type for this purpose.

> Out of curiosity, what does the failure mode look like if you do:
```chapel
proc getVersion(otherVer: sourceVersion) {
  var ret = createVersion(-1,-1,-1);
  if (someCondition) {
    ret = otherVer;
  }
  return ret;
}
```


In this case we get a compiler error:
```
error: Cannot assign to sourceVersion(true,-1,-1,-1,\"\") from sourceVersion(true,0,2,1,\"\")
```

Which I had been justifying because both `ret` and `otherVar` are `param`, and assuming that assignment would therefore be problematic.

**Comment by arezaii** [comment]
Closing this since we merged a two-type solution with #19300

**Pull request closed without merging**
