### PR TITLE
Initial support for redistributing block distributions

### PR DESCRIPTION
**Pull request by bradcray**
This adds initial support for redistributing block distributions.  It currently does not do anything to preserve array values, so is really only safe/sane if the domains declared over the distribution are empty, or if the user does not care about preserving the array data.

[An improvement to this would require having the distribution track the domains declared over it (once again) so that it could redistribute the domains and their arrays (and/or at least check to see whether the domains were empty / there were no arrays to issue a warning if they weren't).  Elliot reminds me that distributions used to track their domain, but using an implementation that was quite heavyweight, and so retired in the name of performance.  Our hope and expectation would be that using a doubly-linked list to store the domains as we currently are for arrays would give similar tracking and be sufficient cheap as to be worth enabling, but I'm leaving that for future work here].

Two ways of redistributing are possible:
* assigning the block distribution a new block distribution value.  In the current implementation, this requires the two block distributions to have identical `targetLocales` arrays, in the sense of being over the same index set and having the same locale value present at any given index
* calling `.redistribute()` on the Block array directly, passing it a new bounding box, which will change the current distribution

In both cases, the implementation approach I took was to leave all of the previous `LocBlock` class instances in-place and to just swap out their contents—specifically their `myChunk` field.  This is a pretty different approach than that taken by the previous (and seemingly unused) approach of assigning block distributions, which freed all the old classes and reallocated new ones, and it should be much more efficient as a result.

Supporting changes included:
* changing the `myChunk` field of the `LocBlock` class from `const` to `var` to support modifications
* adding a new `Block.redistribute()` method that is both available to the user (via forwarding) and the workhorse for assignments between Block distributions
* replacing `Block.dsiAssign()` to check that the `targetLocales` array is the same between source and destination, and to just call `Block.redistribute()` if they are
* adding a test that exercises both forms of redistribution as well as two tests that check for the "same locales array" condition and resulting error

While here, I:
* fixed a bug in `BlockArr.dsiDisplayRepresentation()` that led to nil pointer dereferences if the RAD cache was not populated
* revamped the `dsiLocalSubdomain()` routine to return the locally stored subdomain of the block distribution when called on the local locale and only falling back to the "compute the local subdomain from scratch" routine in the event that a different locale was being queried (which is less common, but done to avoid communication)
* fixed a double application of class memory management routines in DefaultRectangular.chpl

TODO:
- [x] Add an unstable warning
- [x] Consider adding a .redistribute() method form
- [x] Move tests into test directory

### CODE REVIEW

**Comment by bradcray** [comment]
@benharsh, @e-kayrakli, @stonea, @ronawho, or @bmcdonald3 : Would one of you be up for reviewing this?  I can give an interactive tour if anyone's feeling rusty on the block distribution's internals or would like to learn about them.

**Comment by bmcdonald3** [comment]
I can take a look at this today, I've been poking around block lately due to the array API work (but we will see if I still need an interactive tour).

**Review by bmcdonald3 — COMMENTED** [review]
> This is a pretty different approach than that taken by the previous (and seemingly unused) approach of assigning block distributions, which freed all the old classes and reallocated new ones, and it should be much more efficient as a result.

Am I understanding correctly that the old approach allowed the `targetLocales` of the new and old domains to differ and the limitation that the target locales arrays need to match is new with this PR?

That is the only downside I've come up with seeing this implementation in that now the locales arrays have to match, but I think getting rid of the need to allocate all the new class instances is a very fair tradeoff, given that seems very unlikely to want the target locales of an array in a program to change.

One other question is: what is the motivation for this? I vaguely remember a request coming from a user requesting this, but I can't recall what was motivating that request.

**Review by bmcdonald3 — APPROVED** [review]
Thanks for the explanations, this looks good to me 👍

**Pull request merged**
