### PR TITLE
Fix qio valgrind

### PR DESCRIPTION
**Pull request by mppf**

### CODE REVIEW

**Comment by mppf** [comment]
* test/io/ferguson/ctests passes
* valgrind testing for io_test.valgrind.test.c and io_bits_test.valgrind.test.c pass
* I'm going to run a full local test run "just in case"

**Comment by hildeth** [comment]
In qio_test.c, it is not clear why the two calls to check_channel were removed.
Looks good otherwise.
My tweaks to qio_formatted.c are not directly related to this, so I will send them under separate cover.

**Comment by mppf** [comment]
Those two calls were calls I put in to get failing cases (on cygwin) to fail first for debugging. Sometimes I forget to remove such things before committing.

**Comment by hildeth** [comment]
OK, thanks.  You may commit when ready.

________________________________

**Comment by mppf** [comment]
Full local test passed.

**Pull request merged**
