### PR TITLE
Fix internal error when returning a generic type by ref

### LINKED ISSUE #22686: Return a generic type by `ref` causes internal error
### Summary of Problem

Compiling the following program causes an internal error.
```chapel
record R {
  type t;
  var x: t;
}
var val: R(?);

proc foo() ref {
  return val;
}
var a = foo();
writeln(a);
```
If I change `foo()` to return by value (removing `ref`), I correctly get an error `could not determine the concrete type for the generic return type 'R'`. But the code above gives the following internal error.

```
test3.chpl:8: internal error: invalid attempt to get reference type [AST/primitive.cpp:238]
```

I would expect that this code to give the same error message as returning by value.

### Steps to Reproduce

**Source Code:**
See above

**Compile command:**
`chpl test.chpl`

### Configuration Information

- Output of `chpl --version`: chpl version 1.32.0 pre-release (0400cad5a6)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: fifo
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: none
CHPL_RE2: bundled
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
  -  LLVM version 15.0.7 
  - Apple clang version 13.1.6 (clang-1316.0.21.2.5)

### PR DESCRIPTION
**Pull request by jabraham17**
Fixes an internal error that occurs when a generic type was returned from a function by ref. This should be an error, but the compiler threw an internal error.

## Summary of changes
- add a check for generic types to `returnInfoRef`
- Tweak .bad file for #22011
  - I don't think I can resolve this future, but it no longer throws an internal error 
 - Tweak .bad file for `test/types/records/generic/record-generic-class-not-generic.chpl` 
- adds `test/functions/byref/returnGenericRecordByRef.chpl`

## Testing
- paratest
- paratest + gasnet

[Reviewed by @dlongnecke-cray]
resolves #22686

### CODE REVIEW

**Comment by cassella** [comment]
I think the error message you get when the uninitialized-and-still-generic variable is referenced in a function is more useful to the user than this one, e.g.,

```chapel
record R {
  type t;
  var x: t;
}
var val: R(?);

proc foo() {
  writeln(val, ": ", val.type:string);
}

foo();
val = new R(int);
```

```
foo.chpl:1: In module 'foo':
foo.chpl:5: error: cannot default-initialize a variable with generic type
foo.chpl:5: note: 'val' has generic type 'R'
foo.chpl:5: note: cannot find initialization point to split-init this variable
foo.chpl:8: note: 'val' is used here before it is initialized
```

since that's pointing out that the compiler doesn't have a concrete type for `val` at this point.  The error message in this PR is about the return type of the function; but nothing the user does to help the compiler figure out the return type of the function is going to allow `val` to be returned as it is.  Right?  The problem the user has to fix is getting `val` a concrete type.

**Comment by jabraham17** [comment]
Revisiting this..

> The error message in this PR is about the return type of the function; but nothing the user does to help the compiler figure out the return type of the function is going to allow val to be returned as it is. Right? The problem the user has to fix is getting val a concrete type.

To make this code work, the user either needs to provide a concrete type for `val` or provide a concrete return type like `foo() ref: R(int)`. If they do the former, it compiles correctly. If they do the latter, they get an error like
```
returnGenericRecordByRef.chpl:10: error: Initializing a reference with another type
returnGenericRecordByRef.chpl:9: note: Reference has type R(int(64))
returnGenericRecordByRef.chpl:10: note: Initializing with type R
```
This error message should guide users to the fact that their types do not match and to then either give a concrete type for `val`. I think this could be improved by the error message using `type R(?)` instead of just `type R`, but I think that is beyond the scope of this PR.

**Comment by bradcray** [comment]
@jabraham17 : Just stumbled across this and wasn't clear where it stands.  Is it just waiting on a reviewer?  (and, at this point, probably a rebase + retest?)

**Comment by jabraham17** [comment]
> Just stumbled across this and wasn't clear where it stands. Is it just waiting on a reviewer? (and, at this point, probably a rebase + retest?)

I rebased and retested earlier this week and was going to ping someone for a reviewer, and forgot. I would love to get this off my backburner

**Review by dlongnecke-cray — APPROVED** [review]
LGTM

**Pull request merged**
