### PR TITLE
Add support for complex to tuple conversion

### PR DESCRIPTION
**Pull request by rahulghangas**
Fix for feature request in #15993

### CODE REVIEW

**Comment by rahulghangas** [comment]
@mppf

**Comment by mppf** [comment]
@rahulghangas - thanks for having a look at this! 

In order to help compilation speed, could you do these two related things? These steps will help to improve compile times.

1. Adjust the two _cast calls immediately before the one you added to not use a where clause.
For example, change `inline proc _cast(type t, x: (?,?)) where t == complex(64)` into `inline proc _cast(type t:complex(64), x: (?,?))`. I would also think that we should add a `where` clause constraint that the tuple components are numeric and not already complex. It would be good to add tests doing something like `(1+2i, 0): complex`, ("a", "b"): complex`, and `(myRecord, myRecord):complex`.
2. Apply the same technique to the new _cast you are adding. Make two concrete versions, one for complex(64) and one for complex(128), and specify the type that they can cast to. For example `inline proc _cast(type t:(real(64),real(64)), x: complex(128))` and then also a similar routine for real(32) and complex(64).

Besides all of that, we'll need to wait a little while for people to have a chance to offer feedback on issue #15993. There could be some reason (that I don't know of yet) that we don't want this support. However if you are able to make the adjustments to the previous _cast call, we can merge that change either way.

**Comment by e-kayrakli** [comment]
@rahulghangas -- will you be able to make progress on this soon?

**Comment by bradcray** [comment]
I'm going to close this PR given that it seems like #15993 didn't come to a firm conclusion, the need to make more code changes before merging, the lack of tests of the new capability, and the amount of time it's been open.  That's not to say we couldn't kick the discussion back into gear again and see this to conclusion, but I don't see a strong need to at the moment, the issue is lacking a strong developer champion, and I'm trying to clean up PRs going into the new year.

**Pull request closed without merging**
