### PR TITLE
Add chpl_mem_goodAllocSize to the runtime memory interface

### PR DESCRIPTION
**Pull request by Kyle-B**
chpl_mem_goodAllocSize queries the allocator to ask for a good size to
allocate that is of at least a minimum size. This is useful to minimize
the memory wasted while expanding vectors or other buffers.

### CODE REVIEW

**Comment by gbtitus** [comment]
I don't seen any problems, but in an ideal world we would be able to test it for all memory layers. Can you make <test>.{cstdlib,dlmalloc,tcmalloc}.good files and then mv the right one to <test>.good in a <test>.prediff file?
No need for me to look at it again if you do this ...

**Comment by mppf** [comment]
Although the standard C library doesn't have a malloc_good_size function, looking at the glibc implementation, it has a minimum allocated size of 32 bytes (on 64-bit platforms) and the alloc size should be a multiple of 8 (that makes sense because of alignment restrictions). Finally, for sizes >= 512 bytes, the go into logarithmic-sized bins, so allocating a power of 2 bytes (minus 8 for the allocator overhead word) probably makes sense. Then, for allocations larger than 128KiB, the implementation (by default) uses mmap, so now we'd need to round up by system page size (and leave 8 bytes for the allocator overhead word).

You could also try to guess these parameters by calling malloc_usable_size on a sample allocation...

I think these properties are probably pretty generally applicable to other allocators..l. So, we could have something like

int min_size = 32;
int align = 8;
int overhead = 8;
int max_small = 512; // 1 bin per aligned small size
int max_medium = 128*1024; // 1 bin per medium size
// if size > max_medium, it's probably handled with mmap..

then do the following:
* round size up to align
* size = max(size, min_size)
* if size <= max_small return size
* if size <= max_medium round size up to power of 2 - overhead
* else round size up to heap page size - overhead


I think *at least* having a minimum allocation size of 32 or 64 bytes would be a good thing to do when we dont have malloc_good_size.

**Comment by Kyle-B** [comment]
I'm a little leery of trying to guess what the cstdlib `malloc` is going to do. OSX's small allocation size is 16 bytes for example, and I can easily see that all of the other variables (overhead, max_small, ...) could change with each stdlib implementation and platform (32 vs 64 bit).

**Comment by mppf** [comment]
Yep, I agree. I do think that a default of > 1 would probably be a good idea.
What about making chpl_mem_goodAllocSize do something like this program only once, and squirrel away the output in a static/global:

#include <malloc.h>

int main(int argc, char** argv)
{
  void* buf = malloc(1);
  size_t got = malloc_usable_size(buf);
  printf("1 byte allocation gives %i bytes of space\n", got);
  free(buf);
  return 0;
}
$ ./a.out
1 byte allocation gives 24 bytes of space

That way, we could at least compute the minimum size, which I believe is the biggest concern here...

**Pull request merged**
