### PR TITLE
Fix bug with returning the result of ternary expressions

### PR DESCRIPTION
**Pull request by lydia-duncan**
Damian noticed that returning a string via a ternary expression resulted in
stack corruption.  It turns out that this was because the compiler pass
callDestructors is fragile - it is incomplete in its detection of variables that
don't need to be cleaned up at the end of their scope, and this incompleteness
resulted in inserting clean up for a variable that was still needed.

The pass itself makes a number of assumptions that are incorrect.  In
particular, it assumes:
- we can detect variables used to populate return variables by walking the AST
  backwards from the provided refStmt argument (we can only do that if refStmt
  is the last statement in the body)
- that each variable is only assigned into once (not true when the assignment
  occurs in a conditional)
- that there will only be one variable that we need to skip inserting
  deinitialization for in a particular scope (there could potentially be
  multiple)

We expect that implementing this pass correctly will be much easier in dyno.
Michael already has a start at it.  Therefore, it is okay to do a quick fix for
now, as long as we remember just how much is wrong with the pass today.

The quick fix in question is avoiding the insertion of cleanup for temporaries
marked with the flag `FLAG_IF_EXPR_RESULT`.  This allows the test in question to
pass without breaking the test cases that already worked.

Updated an existing test for the new behavior

Adds eight tests locking in the fix and demonstrating additional work:
- the case that motivated the bug report in the first place
- using a cast (which did not fail before)
- using an explicit temporary variable (which did not fail before)
- using a lot of const ref local variables (which leaked memory before and continues to leak the same amount of memory)
- using a lot of const local variables
- using a lot of const local variables and only a const ref temporary for the empty string
- a test using the ternary expression style without returning it, to validate that the memory isn't leaked for var locals (failed with memory issues before this change)
- a test using the ternary expression style without returning it when the local variable is a const ref (which failed before this change and now only leaks memory)

Thanks for the test cases, Jade and Michael!

Testing:
- [x] full standard paratest with futures
- quick valgrind check of:
  - [x] hello.chpl
  - [x] deinit-points.chpl
  - [x] new tests
- [x] memleaks testing for the new tests and deinit-points.chpl

### CODE REVIEW

**Review by mppf — COMMENTED** [review]
Could you add a few variants of the test?

``` chapel
proc positive(z : string) {
  const ref em = '';
  const ref sq = '~';
  const ref sp = ' ';
  const ref pl = '+';
  const ref vr = z;
  return if vr == sq then sp else (if vr == pl then vr else em);
}

const s = positive('+');
writeln(s);
```

Note that this one leaks memory with this PR.

Also these versions that work OK with this PR as-written.

``` chapel
proc positive(z : string) {
  const em = '';
  const sq = '~';
  const sp = ' ';
  const pl = '+';
  const vr = z;
  return if vr == sq then sp else (if vr == pl then vr else em);
}

const s = positive('+');
writeln(s);
```

``` chapel
proc positive(z : string) {
  const ref em = '';
  const sq = '~';
  const sp = ' ';
  const pl = '+';
  const vr = z;
  return if vr == sq then sp else (if vr == pl then vr else em);
}

const s = positive('+');
writeln(s);
```

**Comment by lydia-duncan** [comment]
It looks like the memory leak with the first test is the same as on main and is not resolved with the alternate strategy that focuses on temporaries that are copied into return variables.  The alternate strategy also does not help with the `ternaryPlain.chpl` test or its `const ref` counterpart (which makes sense given that those tests do not return the result of the if-expression) - those tests fail today on main without the original implementation for this PR.

So the status is as follows:

|  | if-expr flag | better following of copies into return variables | main |
| ------ | ------------ | --------------------- | --- |
| motivating test (ternaryReturn.chpl) | works | works | fails |
| lots of local const refs (Michael's first alternative) | runs, but leaks memory | runs, but leaks memory | runs, but leaks memory |
| ternaryPlain (no return) | works | fails | fails |
| ternaryPlainRef (no return) | works, but leaks memory | fails | fails |

The situation seems most improved in the initial implementation, but obviously there is still work to do

**Comment by mppf** [comment]
@ShreyasKhandekar - the issue fixed here looks similar to the issue you worked around in https://github.com/Bears-R-Us/arkouda/pull/3386 . (Note that this PR was later reverted).

**Comment by ShreyasKhandekar** [comment]
Thanks for pinging me on this @mppf! I saw this PR when it was due to be reverted. I think this is very relevant to the bug I worked around and will be following this.

**Pull request merged**
