### PR TITLE
Fixed 17457

### LINKED ISSUE #17457: `List.indexOf()` should return -1 on an empty list
Currently, when calling `.indexOf()` on an empty list:

```chapel
use List;
var l: list(int);
l.indexOf(3);
```

the program halts:

```
$CHPL_HOME/modules/standard/List.chpl:1307: error: halt reached - Start index for "list.indexOf" out of bounds: 0
```

it would be preferable behavior for it to return `-1` as in other `.indexOf()` error cases.

### PR DESCRIPTION
**Pull request by piyush0411**
Signed-off-by: piyush0411 <piyush04111999@gmail.com>

Fixes #17457 

Tested with the following input.
```
use List;
var l: list(int);
writeln(l.indexOf(3));
```
The output comes out to be `-1`, as required.

### CODE REVIEW

**Comment by piyush0411** [comment]
@bradcray Please have a look.

**Comment by bradcray** [comment]
@piyush0411 : Thanks for jumping on this.  Would you add a test to `test/library/standard/List/indexOf/` locking in this new behavior?  (let me know if you haven't written a Chapel test before... I'm losing track of who's done what lately).

I think you've cast too wide of a net, though:  Try running `start_test test/library/standard/list/indexOf/` to see whether I'm right (I didn't build your branch to check myself).

**Comment by piyush0411** [comment]
@bradcray - I have added the test for the feature.
The `listindexOfEmptyList.good` is an empty file. I was thinking of printing something like `An Empty List` or some error message for this case like it is done for `boundchecking` part. Let me know what you think of this.

**Comment by piyush0411** [comment]
@bradcray - I understood your comment a bit late.
I think the following implementation would be a better way to solve the issue.
```
proc const indexOf(x: eltType, start: int=0, end: int=-1): int {
      param error = -1;
      
      if _size == 0 then
        return error;

      if boundsChecking {
        const msg = " index for \"list.indexOf\" out of bounds: ";

        if end >= 0 && !_withinBounds(end) then
          boundsCheckHalt("End" + msg + end:string);

        if !_withinBounds(start) then
          boundsCheckHalt("Start" + msg + start:string);
      }
        
      if end >= 0 && end < start then
        return error;

      var result = error;

      on this {
        _enter();

        const stop = if end < 0 then _size-1 else end;

        for i in start..stop do
          if x == _getRef(i) {
            result = i;
            break;
          }

        _leave();
      }

      return result;
    }
```
I have tested it with the same test I added before and the results are okay.
Please have a look to this.

**Comment by bradcray** [comment]
@piyush0411 : That looks better, thanks, and I've verified that it passes the testing in that directory.  I'll run a full parallel test just to be safe and merge assuming it passes (which is what I expect).  Thanks!

**Comment by bradcray** [comment]
Testing came back clean, as expected.  Merging now.

**Comment by bradcray** [comment]
Thanks again!

**Pull request merged**
