### PR TITLE
Add halt to spawn() for CHPL_COMM=ugni

### PR DESCRIPTION
**Pull request by ronawho**
fork doesn't currently work with ugni when memory is registered with the NIC
and it will result in a segfault. Until we resolve that issue, this adds a halt
and nice error message to tell users what went wrong so they aren't just hit
with an unexplained segfault.

Note that the runtime spawn code will use vfork over fork when stdin, stdout,
stderr=FORWARD so we don't halt in that case. Additionally memory isn't
registered with the NIC when numLocales == 1, so we don't halt then either.

See JIRA issue 113 for more info: chapel.atlassian.net/browse/CHAPEL-113

### CODE REVIEW

**Comment by ronawho** [comment]
@gbtitus and @mppf look ok? 

I didn't actually test it yet, doing that now.

**Comment by mppf** [comment]
Elliot - you could also narrow it down to code using pipes (one of stdin/stdout/stderr != FORWARD). Other than that, looks OK to me if it tests.

**Comment by mppf** [comment]
(re my previous comment - code using the default stdin/stdout/stderr = FORWARD uses vfork and has no problem with ugni right now)

**Comment by ronawho** [comment]
Ah ok, I wasn't sure if we had any way to detect if fork vs vfork was going to be used. Alright, I'll test that out and make the change if it looks good

**Comment by gbtitus** [comment]
The change itself looks good to me.

You should refer to GNI_CDM_MODE_FORK_NOCOPY instead of just FORK_NOCOPY in the description, though. The latter might misdirect the curious toward the fork(2) documentation, while the former will hopefully send them correctly toward the uGNI docs.

**Comment by ronawho** [comment]
updated to only `halt()` for `numLocales > 1` and if `stdin, stdout, stderr != FOWARD`

I also made a JIRA issue for this that I'm going to populate with some of our discussion so far

**Comment by gbtitus** [comment]
Nice.  Like the big comment, too.  If you made the jira issue first you could put the link in the comment ...

Good to go in any case.

**Pull request merged**
