### PR TITLE
Add stubs for unordered PUT support

### PR DESCRIPTION
**Pull request by ronawho**
Add the interface required to support unordered PUTs (but still map to
ordered PUTs.) Buffering and using chained transactions will come in the
next PR, but the implementation is a little tricky so I wanted to split
out the API and the implementation into separate PRs.

This also adds an extra test for unorderedCopy that will fail pretty
miserably if unordered PUT is implemented wrong. It tests that we
correctly copy when the src is stack allocated and checks that we can do
consecutive copies of different types.

### CODE REVIEW

**Comment by ronawho** [comment]
I'm going to merge since @gbtitus gave this is a pre PR review, but I'd appreciate a look at the compiler code from @mppf and a followup sanity check on the runtime API from @gbtitus.

**Comment by mppf** [comment]
Compiler change LGTM

**Comment by gbtitus** [comment]
👍

**Comment by bradcray** [comment]
@ronawho: While looking for another file, I happened to notice that this PR added `test/runtime/configMatters/comm/unordered/unorderedCopyLoop.numLocales` (note the capital-L in the `numlocales` file).  Wanted to point it out in case it hasn't been testing what you'd hoped all this time.

**Pull request merged**
