### PR TITLE
Bug fix and cleanup for leader/standalone iter marking during resolution

### PR DESCRIPTION
**Pull request by ronawho**
Cleans up how leader and standalone iterators are marked for inlining during
function resolution and fixes a bug where a pristine copy of the standalone
iterator (required for forall intents) was not being stashed.

Adds helper routines that check if a function is a specific type of iterator
(leader, standalone, follower.) These functions are then used to find leader
and standalone iterators and mark them for inlining. This separates the logic
of checking if a fn is a particular iterator from whatever you want to do with
the iterator.

This also moves the standalone marking up with the leader marking.

This is a peeled off commit from my vectorize-follower-loops patch (which also
adds and uses an isFollowerIterator function())

During review Vass noticed that we should also be stashing a pristine copy of
the standalone iterator.

A better description from Vass:
"
With the introduction of standalone iterators, the forall intent
machinery has been extended to apply to them, too. Standalone iterators
are treated much like leader iterators for forall intents. (The function
names and comments in implementForallIntents.cpp are still heavy in
leader-follower terminology - for historical reasons.)

This change fixes an omission in the above - we need to "stash pristine
copies" of standalone iterators just like we do leader iterators. The
omission has not caused us trouble yet perhaps because we have not used
standalone iterators in some ways that we have leaders.

### CODE REVIEW

**Comment by ronawho** [comment]
@daviditen and @vasslitvinov can you review this?

I'm mostly looking for confirmation that it's ok to move the standalone inlining marking earlier, and that the assert that leaders have been marked isn't necessary. I did a full paratest so I think this is safe, but I didn't see a clear indication of why things were the way they were in commit log.

Also would you prefer isLeaderIterator(), isFollowerIterator, and isStandaloneIterator() to be methods on FnSymbol instead of static functions here? There are no other places in the compiler that would use them (at least that I found) but it's a little cleaner IMO. If you think it'd be nice, I can make that change for this patch, rather than leaving the TODO in there.

**Comment by vasslitvinov** [comment]
This looks good to me. I suggest leaving isLeaderIterator et al. as standalone functions, and rephrasing the comment from "TODO...should" to "could".

Please make the following change however: invoke stashPristineCopyOfLeaderIter() in the standalone case as well.

**Comment by daviditen** [comment]
I agree with Vass about leaving isLeaderIterator and isStandaloneIterator as a standalone functions in resolution.  As they are currently written they only work during functionResolution.  Prior to resolution the paramMap is empty and after resolution param and type formals are removed.

After you address Vass's comment about stashPristineCopyOfLeaderIter, I think this looks good.

**Comment by vasslitvinov** [comment]
Aside: I think these isLeaderIterator() et al. should work after scopeResolve until resolution.
(This does not affect any conclusions.)

**Comment by ronawho** [comment]
ah good point about when they will work during compilation. I agree leaving them as static functions here is best for now and I'll update the comment. 

Stashing pristine standalone iters is being committed separately as https://github.com/chapel-lang/chapel/pull/1450 (since this commit is labeled as cleanup only.)

**Pull request merged**
