### PR TITLE
Demonstration for HDF5 Tables

### PR DESCRIPTION
**Pull request by npadmana**
Fixes #14551 by removing the noise from commits from rebasing.

### CODE REVIEW

**Comment by npadmana** [comment]
@daviditen, @ronawho  -- for your reviewing pleasure.

**Comment by ben-albrecht** [comment]
@daviditen - are you able to review this?

**Comment by daviditen** [comment]
Sorry for the delay on getting this reviewed.

It looks great overall.  There are a few things that will need to be updated to work with 1.22/master. A few places need to be updated to be 0-based instead of 1-based, and `array.numElements` is deprecated in favor of `array.size`.  I think I can just update them post merge.

I'll plan to merge and do those updates on Monday.

**Comment by npadmana** [comment]
@daviditen -- thanks! Yes, I'm still getting used to the Great Index Shift of 2020. :-)

**Comment by ronawho** [comment]
I'd be in favor of moving these tests to test/library/packages/HDF5/{htable, or whatever} so that we have a single directory with hdf5 tests.

**Pull request merged**
