### PR TITLE
Move LCALS from test/studies/lcals to release/examples/benchmarks/lcals

### PR DESCRIPTION
**Pull request by daviditen**
Moved LCALS into the release/examples/benchmarks directory.  Added README
and Makefile to match the style of other released benchmarks.  Updated
existing benchmarks README to mention LCALS. Updated the new location for
LCALS in the GRAPHFILES file.

### CODE REVIEW

**Comment by ronawho** [comment]
looks good to me! @benharsh since you just added something to the release dir can you double check that no other files need to be updated?

**Comment by benharsh** [comment]
I think the only thing might be a missing entry in release/examples/benchmarks/Makefile

**Comment by bradcray** [comment]
Just in case @daviditen's nervous about it -- I think it's fine to add this after feature freeze...  (though earlier is better than later so we can deal with any testing output).

**Comment by daviditen** [comment]
Thanks @ronawho, @benharsh, @bradcray.

I fixed the Makefile that @benharsh mentioned.

**Pull request merged**
