### PR TITLE
Deprecate c_nil and is_c_nil in favor of just nil

### PR DESCRIPTION
**Pull request by riftEmber**
Deprecates `c_nil` and `is_c_nil()` in favor of just using `nil` and `==` comparison with `nil`.

`is_c_nil()` had behavior of coercing its argument to a `c_void_ptr` before comparison, which `==` does not. The coercion behavior is likely not desirable for `==`, but it means that in some cases the types of `extern` declared pointer variables has to be more fleshed out to be compared with `nil`.

Resolves https://github.com/Cray/chapel-private/issues/4870.

[reviewer info]

Testing:
- [x] paratest
- [x] gasnet paratest

### CODE REVIEW

**Comment by bradcray** [comment]
> It does not work for checking if an extern pointer type is null

What's an example that runs into this?  (I can think of a few ways one might come up with an extern pointer type)

**Comment by riftEmber** [comment]
@bradcray https://github.com/chapel-lang/chapel/blob/main/test/extern/bradc/externNull.chpl is the best example in tests; it has extern C code that typedefs a struct pointer, then checks if a null pointer of that type `is_c_nil`. This occurs in the IO and FileSystem modules as well; at https://github.com/chapel-lang/chapel/blob/main/modules/standard/FileSystem.chpl#L1114, we check if a `DIRptr` (which is an extern type coming from the runtime) `!is_c_nil`.

One option is to just do `__primitive("cast", c_void_ptr, x) == c_nil` like `is_c_nil` does in the few cases it's needed in modules, which is what I've done on this branch so far, but I feel it would be better to have a user-facing solution to this.

**Comment by bradcray** [comment]
Given that example, it seems as though `sPtr` has a type in the compiler even though it's undeclared (maybe dtOpaque?) and that we should be able to create an overload that compares opaque types to `nil`?  (or, less attractive, we could make an overload that compares anything to `nil` as long as that thing is not a primitive type, a record, a class, an array, a domain, a range, a sync, an atomic...)

**Comment by riftEmber** [comment]
That makes sense to me. I tried creating an overload of `==` that compares `opaque` to `_nilType`, but it didn't resolve. According to the error message the type of the argument is `sPtr`, not `opaque`.

This still seems like a promising path though, I'll try to figure out if there's some way I could support this in the compiler by detecting the type is an opaque extern type.

**Comment by bradcray** [comment]
> That makes sense to me. I tried creating an overload of == that compares opaque to _nilType, but it didn't resolve. According to the error message the type of the argument is sPtr, not opaque.

Did you create the overload using something like `operator ==(lhs: opaque, rhs:_nilType)` (say)?  I wonder whether we don't do much smart with `opaque` in any situations other than external declarations...  One other thing to try, though, is whether `type sPtr;` really is being considered opaque (vs. say `dtUnknown`).  Changing the declaration to `type sPtr = opaque;` might be an interesting way to test that.

If that still doesn't help, I'd probably dig into the compiler a bit to see how the compiler represents it (where using `--log=` may be a way to answer that question from the command-line?)

**Comment by bradcray** [comment]
All the above said, I also wonder whether, even if we can get this to work, we shouldn't be assuming that any untyped extern type is comparable to nil—e.g., maybe it's just a struct that the user was particularly lazy about declaring?  In which case, I'd also wonder whether an error is the correct behavior here, and `type sType = c_void_ptr;` or `type sType = c_ptr(opaque);` would be more appropriate things to require the user to type in order to get comparisons to `nil` in Chapel.

It seems like there should be a path forward here in any case, where it's just a question of how heroic we need and want to be.

**Comment by riftEmber** [comment]
> Did you create the overload using something like operator ==(lhs: opaque, rhs:_nilType) (say)?

Yes, that's what I tried that it didn't resolve to. I can't say I understand how `opaque` is used very well.

> One other thing to try, though, is whether type sPtr; really is being considered opaque (vs. say dtUnknown)

I was surprised that the type was just called `sPtr` by the compiler, but [this spec section](https://chapel-lang.org/docs/technotes/extern.html?highlight=extern#declaring-external-c-types) says "Effectively, such a declaration defines a new primitive type in Chapel.", so maybe it won't be labeled as anything except an `sPtr` type. I do want to investigate this more in the compiler.

> I'd also wonder whether an error is the correct behavior here, and type sType = c_void_ptr; or type sType = c_ptr(opaque); would be more appropriate things to require the user to type in order to get comparisons to nil in Chapel.

That seems plausible to me as well. Hm...

**Comment by bradcray** [comment]
I'd forgotten about that spec language, which makes sense to me now that you've quoted it.  I think, based on that, we should not try to get the "undescribed external type alias" case to support comparisons to `nil` and should look at requiring the user to describe it as being a c_ptr of some type to get that behavior (which your last comment suggests you may look into next?).

**Comment by riftEmber** [comment]
I was planning to look into how these types are representing in the compiler first to see if it would be feasible to support an `== nil` for them. Then after that I was going to look at requiring users to declare the types as `c_ptr`s or similar. I see those two options as mutually exclusive and hadn't personally settled on which one would be preferable. I'll take your preference for the second route into account, and maybe look into it first.

**Comment by riftEmber** [comment]
Tried the `type sType = c_ptr(opaque);` route. It seemed to work for the most part, but unfortunately with the C backend we run into mismatched type issues from the IO module. These are visible in the `make_check_llvm_none` CI run.

In IO we have `extern type qio_channel_ptr_t = c_ptr(opaque);`, and `qio_channel_ptr_t` is used as a formal in extern declarations of some IO procs from the runtime. These extern declarations (where c_ptr(opaque) turns into void**) as well as the actual IO code (where we are using the real `qio_channel_t*` from the runtime C) both make it into our C code that is getting compiled, leading to conflicting definitions.

Here's what the error looks like on my system:
```
In file included from tmp/_main.c:2:
tmp/chpl__header.h:2780:8: error: conflicting types for 'chpl_qio_setup_plugin_channel'
syserr chpl_qio_setup_plugin_channel(c_void_ptr file,
       ^
/Users/rift/chapel/runtime/include/qio/qio_plugin_api.h:33:8: note: previous declaration is here
syserr chpl_qio_setup_plugin_channel(void* file, void** plugin_ch, int64_t start, int64_t end, qio_channel_t* qio_ch);
       ^
In file included from tmp/_main.c:61:
tmp/IO.c:426:8: error: conflicting types for 'chpl_qio_setup_plugin_channel'
syserr chpl_qio_setup_plugin_channel(c_void_ptr file,
       ^
/Users/rift/chapel/runtime/include/qio/qio_plugin_api.h:33:8: note: previous declaration is here
syserr chpl_qio_setup_plugin_channel(void* file, void** plugin_ch, int64_t start, int64_t end, qio_channel_t* qio_ch);
       ^
2 errors generated.
make: *** [tmp/_main.o] Error 1
```

Sure enough, there was a spec warning about this I didn't see, under [this section](https://chapel-lang.org/docs/primers/interopWithC.html#using-c-code-in-chapel):
> If you do not care about the type for a certain variable or argument, you can use the opaque keyword to indicate to the compiler that you do not know about the type. Such a variable will not be much use except for the ability to pass it to different routines which accept the same underlying type. (Be careful here as it may lead to unmatched types.)

I don't think there's a good way to get around this; the error seems correct. I think to fix it we would need to not use the extern-declared `qio_channel_ptr_t` as a formal in extern procs, and instead use another version that was not set to `c_ptr(opaque)`. But that would defeat most of the purpose of the extern declaration.

**Comment by bradcray** [comment]
What about making the IO declarations into:

```chapel
extern record qio_channel_t { }
extern type qio_channel_ptr_t = c_ptr(qio_channel_t);
```

since these would be more accurate declarations for these types anyway.

Or, less pristine, but does `extern type qio_channel_ptr_t = c_ptr(void);` (or I guess `c_void_ptr` for the time being) improve things relative to `c_ptr(opaque)`?  (which I suggested, but feel less good about than either of the above options anyway).

**Comment by riftEmber** [comment]
Looks like it's working, seems like this might be the way to go! Thanks for all the advice @bradcray.

**Comment by bradcray** [comment]
> it would mean increased expectations for our users if that had to be done everywhere they wanted to check if an extern pointer type was nil, but maybe that's what we want.

I think it is.  Specifically, saying `extern type foo;` doesn't really tell us anything about the type as well, including whether it's a pointer or not.  So I don't think it's appropriate to expect it to support comparisons to `nil` or `42` or anything specific without being given more information about it.

**Comment by riftEmber** [comment]
Good idea, I've just added a brief mention of it.

**Pull request merged**
