### PR TITLE
Add sign extension for srem on i8 and i16 values 

### LINKED ISSUE #22250: Printing ranges displays different behavior using writeln and writef
### Summary of Problem

When printing a range with alignment or stride that border the min/max of a integer width, `writeln` and `writef` behave differently and print the range with different values on M1 MacBooks. The issue does not occur on Intel MacBooks or regular x86 machines.

This problem was made more prevalent with #22225, but exists in prior versions of Chapel

### Steps to Reproduce

excerpt from `test/types/range/minMaxStrides.chpl`

Although the first writef should be equivalent to the send writef+writeln, they are different.

```
config var percentT=true;
proc test(type t) {
  type ST = int(Types.numBits(t));
  type UT = uint(Types.numBits(t));
  writeln("Testing signed ", ST:string, " and unsigned ", UT:string);

  for by_ in (Types.min(ST), Types.max(ST), Types.max(ST):UT) {
    for align_ in (Types.min(ST), Types.max(ST), Types.max(UT)) {
      var r = (0:align_.type)..(100:align_.type) by by_ align align_;
      if percentT then 
        writef("by_=%12n:%-10s; align_=%12n:%-10s; range=%t\n",  by_, by_.type:string, align_, align_.type:string, r);
      else { 
        writef("by_=%12n:%-10s; align_=%12n:%-10s; range=",  by_, by_.type:string, align_, align_.type:string);
        writeln(r);
      }
    }
  }
}

test(int(8));
```

**Compile command:**
`chpl test.chpl`

**Execution command:**
`./test` produces 
```
Testing signed int(8) and unsigned uint(8)
by_=        -128:int(8)    ; align_=        -128:int(8)    ; range=0..100 by -128 align 0
by_=        -128:int(8)    ; align_=         127:int(8)    ; range=0..100 by -128 align 0
by_=        -128:int(8)    ; align_=         255:uint(8)   ; range=0..100 by -128 align 1
by_=         127:int(8)    ; align_=        -128:int(8)    ; range=0..100 by 127 align 1
by_=         127:int(8)    ; align_=         127:int(8)    ; range=0..100 by 127
by_=         127:int(8)    ; align_=         255:uint(8)   ; range=0..100 by 127 align 1
by_=         127:uint(8)   ; align_=        -128:int(8)    ; range=0..100 by 127 align 1
by_=         127:uint(8)   ; align_=         127:int(8)    ; range=0..100 by 127
by_=         127:uint(8)   ; align_=         255:uint(8)   ; range=0..100 by 127 align 1
```

`./test --percentT=false` produces
```
Testing signed int(8) and unsigned uint(8)
by_=        -128:int(8)    ; align_=        -128:int(8)    ; range=0..100 by -128 align 0
by_=        -128:int(8)    ; align_=         127:int(8)    ; range=0..100 by -128 align 127
by_=        -128:int(8)    ; align_=         255:uint(8)   ; range=0..100 by -128 align 127
by_=         127:int(8)    ; align_=        -128:int(8)    ; range=0..100 by 127 align 126
by_=         127:int(8)    ; align_=         127:int(8)    ; range=0..100 by 127
by_=         127:int(8)    ; align_=         255:uint(8)   ; range=0..100 by 127 align 1
by_=         127:uint(8)   ; align_=        -128:int(8)    ; range=0..100 by 127 align 126
by_=         127:uint(8)   ; align_=         127:int(8)    ; range=0..100 by 127
by_=         127:uint(8)   ; align_=         255:uint(8)   ; range=0..100 by 127 align 1
```

#### In Chapel 1.30.0

`./test` produces 
```
Testing signed int(8) and unsigned uint(8)
by_=        -128:int(8)    ; align_=        -128:int(8)    ; range=0..100 by -128 align 1
by_=        -128:int(8)    ; align_=         127:int(8)    ; range=0..100 by -128 align 1
by_=        -128:int(8)    ; align_=         255:uint(8)   ; range=0..100 by -128(null):64: error: halt reached - casting int(8) less than 0 to uint(8)
```

`./test --percentT=false` produces
```
Testing signed int(8) and unsigned uint(8)
by_=        -128:int(8)    ; align_=        -128:int(8)    ; range=0..100 by -128 align 0
by_=        -128:int(8)    ; align_=         127:int(8)    ; range=0..100 by -128 align 127
by_=        -128:int(8)    ; align_=         255:uint(8)   ; range=0..100 by -128test.chpl:22: error: halt reached - casting int(8) less than 0 to uint(8)
```

#### Printing `_alignment`

In trying to debug this issue with @vasslitvinov, we tried printing out `r._alignment` in the format string as well. Replacing the loop body with:

```chapel
if percentT then 
  writef("by_=%12n:%-10s; align_=%12n:%-10s; r._alignment=%12n; range=%t\n",  by_, by_.type:string, align_, align_.type:string, r._alignment, r);
else { 
  writef("by_=%12n:%-10s; align_=%12n:%-10s; r._alignment=%12n; range=",  by_, by_.type:string, align_, align_.type:string, r._alignment);
  writeln(r);
}
```

Now the output looks like:
`./test` produces 
```
Testing signed int(8) and unsigned uint(8)
by_=        -128:int(8)    ; align_=        -128:int(8)    ; r._alignment=           0; range=0..100 by 0 align $CHPL_HOME/modules/internal/ChapelRange.chpl:3079: error: halt reached - Attempt to compute a modulus by zero
```

`./test --percentT=false` produces
```
Testing signed int(8) and unsigned uint(8)
by_=        -128:int(8)    ; align_=        -128:int(8)    ; r._alignment=           0; range=0..100 by -128 align 0
by_=        -128:int(8)    ; align_=         127:int(8)    ; r._alignment=         127; range=0..100 by -128 align 127
by_=        -128:int(8)    ; align_=         255:uint(8)   ; r._alignment=         127; range=0..100 by -128 align 127
by_=         127:int(8)    ; align_=        -128:int(8)    ; r._alignment=         126; range=0..100 by 127 align 126
by_=         127:int(8)    ; align_=         127:int(8)    ; r._alignment=           0; range=0..100 by 127
by_=         127:int(8)    ; align_=         255:uint(8)   ; r._alignment=           1; range=0..100 by 127 align 1
by_=         127:uint(8)   ; align_=        -128:int(8)    ; r._alignment=         126; range=0..100 by 127 align 126
by_=         127:uint(8)   ; align_=         127:int(8)    ; r._alignment=           0; range=0..100 by 127
by_=         127:uint(8)   ; align_=         255:uint(8)   ; r._alignment=           1; range=0..100 by 127 align 1
```

#### Printing `_alignment` in Chapel 1.30

Just to be consistent, running the above example in 1.30 as well
`./test` produces 
```
Testing signed int(8) and unsigned uint(8)
by_=        -128:int(8)    ; align_=        -128:int(8)    ; r._alignment=        -128; range=0..100 by -128 align 0
by_=        -128:int(8)    ; align_=         127:int(8)    ; r._alignment=         127; range=0..100 by -128 align 127
by_=        -128:int(8)    ; align_=         255:uint(8)   ; r._alignment=         255; range=0..100 by -128test.chpl:22: error: halt reached - casting int(8) less than 0 to uint(8)
```

`./test --percentT=false` produces
```
Testing signed int(8) and unsigned uint(8)
by_=        -128:int(8)    ; align_=        -128:int(8)    ; r._alignment=        -128; range=0..100
by_=        -128:int(8)    ; align_=         127:int(8)    ; r._alignment=         127; range=0..100
by_=        -128:int(8)    ; align_=         255:uint(8)   ; r._alignment=         255; range=0..100
by_=         127:int(8)    ; align_=        -128:int(8)    ; r._alignment=        -128; range=0..100
by_=         127:int(8)    ; align_=         127:int(8)    ; r._alignment=         127; range=0..100
by_=         127:int(8)    ; align_=         255:uint(8)   ; r._alignment=         255; range=0..100
by_=         127:uint(8)   ; align_=        -128:int(8)    ; r._alignment=        -128; range=0..100
by_=         127:uint(8)   ; align_=         127:int(8)    ; r._alignment=         127; range=0..100
by_=         127:uint(8)   ; align_=         255:uint(8)   ; r._alignment=         255; range=0..100
```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.31.0 pre-release (18be08a1a5)
  built with LLVM version 14.0.6
  available LLVM targets: amdgcn, r600, nvptx64, nvptx, aarch64_32, aarch64_be, aarch64, arm64_32, arm64, x86-64, x86
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: fifo
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: none
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Tagging @benharsh in this

### PR DESCRIPTION
**Pull request by jabraham17**
Adjusts the code generation with the LLVM backend for `srem` for i8 and i16 values. These will now `sext` to the next bit size up (i16 and i32, respectively) before doing the operations, and then `trunc` to the original size. This matches semantics seen in C.

This resolves an issue seen in our nightly testing

## Summary of changes
- adjust codegen of `mod` for LLVM
- add signed min check for `chpl__mod`, which could also insert poison values.

## New tests
- test of `%` on integer boundaries (`test/types/integral/modAtBoundaries.chpl`)

## testing
- paratest with futures
- paratest + gasnet

---

[Reviewed by @]

resolves #22250

### CODE REVIEW

**Review by mppf — COMMENTED** [review]
The codegen change looks good. Were you able to establish why clang extends these to a larger size, but doesn't do it for int64_t?

I'm not sure about the `chpl__mod` change in that mod with a negative modulus is not always defined to be the same as mod with the absolute value. I'm not quite sure what the requirements of ranges are in this area but I'm asking you to try to double-check that this is the right behavior.

**Comment by jabraham17** [comment]
> Were you able to establish why clang extends these to a larger size, but doesn't do it for int64_t

I could not find a compelling reason why. Which does make me hesitant to add this.

> in that mod with a negative modulus is not always defined to be the same as mod with the absolute value

I will check with Vass on this, but this should have no effect other than avoiding the LLVM poison checker in optimized code. 

I have a theory I am going to test. The above changes are independent of each other, codgen changes and `chpl__mod` changes. I test both changes together and the codegen changes standalone, but not the `chpl__mod` changes standalone. If that solves it the bug, then no need to mess with the codegen.

**Comment by mppf** [comment]
> > Were you able to establish why clang extends these to a larger size, but doesn't do it for int64_t

> I could not find a compelling reason why. Which does make me hesitant to add this.

I'd like to see the clang compiler code that does it so we can check if `git blame` will answer the question for us.

A quick look at the C standard does not indicate to me that this is required.

**Comment by jabraham17** [comment]
> I'd like to see the clang compiler code that does it

I was looking for this earlier and came to the conclusion it isn't added, just not removed. It seems that clang inserts casts for integral binary operators to 32 bits in the AST. Comparing to addition, adding two chars with `-O0` generates IR which sign extends the i8 to i32 and then truncates back to i32. The modulo case with `-O0` does the same thing. Only when optimization is applied does the sign extension for add get removed and the sign extension for srem get reduced to i16.

I am still hunting for the exact piece of code in llvm to either dig through the git blame or hopefully find a helpful comment

View of Assembly, Clang AST, and LLVM IR: https://godbolt.org/z/Wd1ceYWbx

**Comment by mppf** [comment]
Yeah, the thing that seems weird to me is that clang doesn't end up with the sign extending for `int32_t` but it does for `int16_t`.

**Comment by jabraham17** [comment]
It appears this is the commit that adds the optimization, it only runs at `-O2` or `-O3`.

https://github.com/llvm/llvm-project/commit/b289dc530632613edb3eb067895c1981cb77ccd0

**Comment by mppf** [comment]
I think this is the review of it: https://reviews.llvm.org/D44102

Anyway what this means to me is that maybe we were supposed to be doing these in a larger numeric width and then it gets optimized? Is that what clang is doing? Why is clang doing it in a larger numeric width?

**Comment by mppf** [comment]
Right but that has

>  If the types are the same, that type is the common type. 

Wouldn't that imply the operation is done on 8-bit ints if it starts with two 8-bit ints?

**Comment by jabraham17** [comment]
Yes, but the line just before is

> Otherwise, both operands are integers. Both operands undergo integer promotions (see below); then, after integer promotion, one of the following cases applies:
If the types are the same, that type is the common type.

So both operands are first promoted to `int`, then because they are both the same type that is the common type.

The spec is honestly more clear than cppreference. from C99 6.3.1.8 
> Otherwise, the integer promotions are performed on both operands. Then the following rules are applied to the promoted operands:
If both operands have the same type, then no further conversion is needed.
...

**Comment by mppf** [comment]
Right, but I was looking at the spec. They define an "integer" as something of any integer width. So nothing about this indicates to me that they go to `int` first.

**Comment by jabraham17** [comment]
In 6.3.1.1p2 it says
> If an int can represent all values of the original type, the value is converted to an int; otherwise, it is converted to an unsigned int. These are called the integer promotions.48) All other types are unchanged by the integer promotions.

**Comment by jabraham17** [comment]
I ended up resolving the issue with #22281 instead, which just contains the `abs` changes. This was sufficient to solve the original bug.

I spun out the discussion on LLVM vs C differences into its own issue here  #22288

**Pull request closed without merging**
