### PR TITLE
Clang included fixes

### PR DESCRIPTION
**Pull request by mppf**
Continuing PR #1539, Thomas and Greg requested that I change the
name of the new target, and Thomas pointed out that I incorrectly
put a dash to allow make to continue if there was a build error.

### CODE REVIEW

**Comment by mppf** [comment]
@gbtitus  and/or @thomasvandoren does this look OK?

**Comment by gbtitus** [comment]
Yep, looks ok to me. (please wait for @thomasvandoren to confirm)

**Comment by thomasvandoren** [comment]
The name change looks good. Thanks for that!

What happens when the clang-included runtime fails to build? I think it halts the make process with this change. What are the ramifications for calling chpl --llvm when the clang-included runtime failed to build?

The make process halting means our cray module build will break, since at least one configuration has issues (platform=cray-xc, target_compiler=cray-prgenv-cray, comm=gasnet, substrate=aries, tasks=fifo). I can think of three options for addressing that, since now is not a great time to break the module:

1. Find and fix the configurations that are broken in the cray module. This is a bit daunting since we build so many configurations in the module.
2. Update chpl --llvm to fail gracefully when the clang-included runtime is not available. I'm not entirely sure what this means, but I think we would want to allow the clang-included runtime build to fail silently (add the hyphen back in). Then the compiler or generated C makefiles could check for the appropriate gen directory/files before building.
3. Backing out the clang-included support until the release branch is cut.
4. ?

**Comment by thomasvandoren** [comment]
I'm ok with this going in as is. I'd like to discuss the build issues further, though. Thanks!

**Comment by mppf** [comment]
Let's chat on chat :)

**Comment by mppf** [comment]
The module build problems will happen currently with any configuration with CHPL_LLVM=llvm. This change just makes the 'if using LLVM' check and resulting runtime build fail on error; if LLVM is not enabled it will still do nothing.

**Pull request merged**
