### PR TITLE
Add tests and futures looking at I/O on class hierarchies

### PR DESCRIPTION
**Pull request by bradcray**
In the performance meeting yesterday, during some discussions about I/O and class hierarchies, we talked about some surprises which led me to write some tests, which led to some additional surprises.  The theme of the main tests here is "What kind of compiler-generated writeThis() routines are generated (or not) in a class hierarchy, particularly when some classes have supplied their own writeThis() overloads?"  The tests seem to indicate inconsistent behavior in which sometimes a completely distinct compiler-generated routine is called, and in some cases it seems not to be.

The tests are as follows:

* classIOinHierarchy-default.chpl: what happens when no user overrides are supplied?  (works as I'd currently expect)
* halt-in-parent-class-io.chpl: seems to indicate that the compiler generates a routine for the child class that has no bearing on the parent class; this surprises me, as I'd expect the child to just inherit the parent class method (or, if not, for the compiler-generated routine to call into the parent-class routine)
* classIOinHierarchy-override.chpl: what happens if we define a writeThis() on the middle class of a 3-class hierarchy?  this test's behavior is really puzzling to me, and seems inconsistent both with itself and the previous tests
* classToString.chpl: this is mostly unrelated to the above, but is a prototype of a library routine we could supply that generates a string representing a class expression's type.

### CODE REVIEW

**Comment by bradcray** [comment]
@chapel-lang/perf-team : Here are some tests related to our discussion yesterday about `writeThis()` on class hierarchies.  Things are even more surprising than I'd expected in that I can't explain some of our current behaviors.

**Comment by bradcray** [comment]
Without looking for it, I just happened to stumble across #7118 which is related.

**Comment by bradcray** [comment]
@dlongnecke-cray / @mppf: I'd be curious whether you had any insights as to what's going on in `classIOinHierarchy-override.chpl` and whether you see any reasons not to merge this PR.  #7118 makes me think it's not necessarily surprising that these tests don't work as I'd expect, though the inconsistency still seems surprising to me, esp. since I don't have a working theory as to why things are behaving as they are.

**Comment by mppf** [comment]
Could you link #7118 in the .future?

I think the problems are these:
 1. The compiler isn't thinking about inheritance when creating the default writeThis (or not creating it)
 2. Generated writeThis for child classes also print out parent fields

**Comment by bradcray** [comment]
> I think the problems are these:

That's what I was expecting, but I don't think that those points explain the "static type C, dynamic type D" case in test/classes/io/classIOinHierarchy-override.bad nor the apparent discrepancy between the "static type C, dynamic type E" case in that test compared to halt-in-parent-class-io.chpl.  (Not that we have to answer those questions before merging this PR... but I didn't even have a working theory).

**Comment by mppf** [comment]
> I don't think that those points explain the "static type C, dynamic type D" case in test/classes/io/classIOinHierarchy-override.bad

Maybe there is a bug with virtual dispatch? Or maybe the method signatures don't match for some reason? I am not seeing FLAG_METHOD_OVERRIDES on D.writeThis, even though it should be overriding the compiler-generated C.writeThis. Adding the `override` keyword gives an error. Somehow the compiler is not recognizing this as an overridden method.

**Comment by bradcray** [comment]
> Adding the override keyword gives an error. 

I had variants of the test that did/did not throw and did/did not use override and thought about filing them, but saw the error you noted for the override versions and similar behavior whether or not `throws` was used, so ended up unconvinced that they would add much value beyond this single one as a placeholder (and figured that any fix for this test would likely explore what was / wasn't required for those other choices at the same time).

I wonder if the irregularity is due to some sort of interaction between readWriteThis() and writeThis() that the compiler misses...  yet it still seems like even the behavior of the single test in isolation is problematic (e.g., compare the static type C / dynamic type D case with the static type D / dynamic type D case...  this suggests to me that beyond any virtual dispatch / overloading issues, the static type is having more of an impact on the outcome than it should.

**Comment by dlongnecke-cray** [comment]
I honestly have no clue. Every time I think I see a pattern I get to the bottom of the list and get so confused I start over again.

**Comment by bradcray** [comment]
Thanks for taking a look.  We can dig into this later... was just curious whether I was missing something obvious.

**Pull request merged**
