### PR TITLE
Move extra empty locales from ChapelDistribution to LocaleModels where missing

### PR DESCRIPTION
**Pull request by lydia-duncan**
ChapelDistribution defined `chpl_emptyLocaleSpace` and `chpl_emptyLocales`,
but these constants were also defined in the LocaleModel for flat and apu.  Having
them in ChapelDistribution led to a circular dependency resolution error when I
tried to make the default use of ChapelStandard private.

This PR removes them from ChapelDistribution and inserts them into the
LocaleModels that didn't already have a definition (numa and knl).  I verified that
removing them without moving them to numa's LocaleModel caused failures for
hello world (so adding them there was necessary and that it would be immediately
visible if a problem occurred).

Testing:
- [x] full paratest with futures for flat
- [x] full gasnet paratest with futures for flat
- [x] test/release/examples/benchmarks/shootout for numa

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@gbtitus - care to review?  And should I double check KNL or do we want to let nightly handle it?

**Comment by lydia-duncan** [comment]
I did not.  I kinda assumed it being defined in some LocaleModels and not others was the result of code motion rather than something especially intentional.

**Comment by gbtitus** [comment]
Possibly.  But `git blame` shows a 2013 date for the lines in `flat` and a 2017 date for the ones in `ChapelDistribution`, so the former had been there for 4 years (ish) by the time the need for the latter arose.  I guess it's also possible the latter addition was just in what looked like the right spot but wasn't.  Seems all right to let the nightlies point out any flaws, given that you've done full testing on flat.

**Comment by mppf** [comment]
> Did you talk to @mppf about what the order-of-resolution issue was that led to these being put into ChapelDistribution?

I don't remember... if removing the workaround for a compiler issue works, let's do it.

**Pull request merged**
