### PR TITLE
Annotate switch of gen compiler to gcc 5.1

### PR DESCRIPTION
**Pull request by bradcray**
This seems to have caused a performance degradation for some stream and RA timings

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho, @benharsh, @lydia-duncan  -- want to double-check my syntax?

**Comment by benharsh** [comment]
I'm unsure of whether or not multiple configs are allowed, but it looks good otherwise.

**Comment by bradcray** [comment]
The comment at the top suggested it was, but I must admit I didn't test...

**Comment by benharsh** [comment]
Oops! I hadn't noticed that comment, feel free to merge.

**Comment by bradcray** [comment]
This switch seems to have caused a performance degradation for some stream and RA timings -- noting it for 1- and 16-node KNC runs.

**Pull request merged**
