### PR TITLE
Clean code by reusing existing stripdirectories() function

### LINKED ISSUE #8759: Code cleanup: use `stripDirectories()` in computing executableFilename
In PR #8733, @cassella notes that the code I wrote re-implemented existing logic to strip
a filename down to its basename:

> FWIW, compiler/utils/file.cpp already has a stripdirectories()
> that returns a newly-allocated string containing just the basename,
> however long it is.

and that the code could be refactored to avoid this duplication.

### PR DESCRIPTION
**Pull request by krishnadey30**
This PR solves the following issue https://github.com/chapel-lang/chapel/issues/8759 .

The PR update the `compiler/codegen/codegen.cpp` file and use the function `stripdirectories()` defined in `compiler/util/files.cpp`. It also updated the `compiler/include/files.h` to have the defination of `stripdirectories()`.

Resolves #8759.

### CODE REVIEW

**Comment by krishnadey30** [comment]
@ben-albrecht @bradcray  Please have a look at it.

**Comment by bradcray** [comment]
Hi Krishna — Thanks for taking this on.  I'm going to mark it as "post-release" since we're trying to minimize the number of code changes that go in today and this is a change that shouldn't affect a user's experience.

**Comment by krishnadey30** [comment]
Thanks @bradcray Sir

**Comment by ben-albrecht** [comment]
@bradcray - would you like to look at this?

**Comment by bradcray** [comment]
Hi Krishna — Sorry for the delay here, the 1.19 release and post-release activities have been keeping me slammed lately.  I just reviewed the code and it looks good; I'm running a test run on it not to make sure there aren't any surprises or breakages.

**Comment by bradcray** [comment]
Looks clean, thanks again!

**Comment by krishnadey30** [comment]
Thanks @bradcray sir

**Pull request merged**
