### PR TITLE
Specifying one variable multiple times in a with clause should be an error

### PR DESCRIPTION
**Pull request by cassella**
Specifying one variable multiple times in a with clause should be an error.

### CODE REVIEW

**Comment by cassella** [comment]
This time the problem is there are too many variables, and they all do have the same name.

**Comment by lydia-duncan** [comment]
I would recommend putting this future in a directory you own instead of under Vass's (unless you specifically ran it by Vass first).  Right now, if someone comes across it later, they'll go to Vass first and he might not have the context to answer questions about why it was written in a certain way (if that even ends up being an issue).

Otherwise this looks good.  I will merge it once you make that update.  Thanks!

**Comment by cassella** [comment]
I had run it by Vass, who said either way is fine.  But updating the mod is also appealing as I've since thought of a funnier variable name...

**Comment by cassella** [comment]
Rewrote history to relocate the test, as the intermediate state wasn't interesting.

I also retested the future with today's forall intents change -- the output still matches the .bad file.  (I left this PR's branch based where it was yesterday.)

**Comment by lydia-duncan** [comment]
Awesome, thanks Paul!  I verified that I also get a clean match against the .bad file

**Pull request merged**
