### PR TITLE
Remove the numa locale model technote

### PR DESCRIPTION
**Pull request by ronawho**
Technically it as a "locale model" technote, but it really only touched
on numa. The technote was woefully out of date and we've deprecated the
numa locale model so I don't see any reason to keep the doc.

### CODE REVIEW

**Review by jeremiah-corrado — APPROVED** [review]
This kind of makes me wish the version dropdown on the public docs allowed you to go back to previous releases. (Someone out there using an older version of chapel with the numa locale model might still want to look at this, but I agree it's not needed in the 1.28 docs)

**Comment by ronawho** [comment]
Huh, I thought the dropdown has the latest release, pre-release (main), and the past release. But looks like it doesn't have the past release anymore. @bradcray would probably know more about why (and it's possible my memory is wrong.)

FWIW you can hack the URL to get to older releases still. e.g. https://chapel-lang.org/docs/1.26/index.html

**Comment by bradcray** [comment]
> I thought the dropdown has the latest release, pre-release (main), and the past release.

It does if you're looking at a page that's an older release, but we don't provide this option by default when looking at the current or main versions of the docs (and haven't, at least since we stabilized on the current approach).

We could consider adding a "one version back" option if we thought we should.  The main reason to potentially not (other than the effort to add it) to would be that pointing to fewer out of date things makes them less likely to be included in Google searches (where we've had problems in the past where Google gets stuck on ancient versions of docs... and even today it's not perfect, but has been better since we reduced the number of links to old docs).

**Comment by ronawho** [comment]
I don't personally see a need to add the previous version, but had it in my head that it was so I was surprised when I went to look.

**Pull request merged**
