### PR TITLE
DefaultRectangular CMO global switch

### PR DESCRIPTION
**Pull request by daviditen**
Added the config param defaultStorageOrder to DefaultRectangular. It can
be set to ArrayStorageOrder.RMO or ArrayStorageOrder.CMO, and controls the
storage order for all Default Rectangular arrays.

I tried also making iteration over arrays/domains match the storage order by
adding new 'these_help' iterators, but that caused too many problems in tests.
The added iterators are currently commented out.  See issue #11377.

Added a test that verifies that RMO and CMO both result in the right memory
order.

Added 5 .skipif files for tests that depend on RMO order or don't like the
compile command line changed.

### CODE REVIEW

**Comment by daviditen** [comment]
Passed a default Linux64 paratest.
Passed a Linux64 paratest with "-compopts -sdefaultStorageOrder=ArrayStorageOrder.CMO".

**Comment by lydia-duncan** [comment]
Meta note: have you opened an issue to track the iterators thing you mention in your PR message?  That would be good to do and link to in the comment

**Comment by lydia-duncan** [comment]
I don't think I understand enough about the implementation to give this a good review, sorry :(

**Comment by daviditen** [comment]
> Meta note: have you opened an issue to track the iterators thing you mention in your PR message? That would be good to do and link to in the comment

Opened issue #11377 and updated the main comment above.  Thanks.

**Comment by daviditen** [comment]
Thanks!

**Pull request merged**
