### PR TITLE
Make sure c_arrays of POD types are POD

### PR DESCRIPTION
**Pull request by e-kayrakli**
Reverts https://github.com/chapel-lang/chapel/pull/22670 and adds a more principled solution.

The PR above made `c_array` of POD types suitable for bulk transfer, but that was only part of the story. We also have to make sure that they avoid `forall` that inits `c_array`s elements. To address that, this PR just makes sure that `c_array`s of POD types are also POD.

Also, it adjusts a multilocale test that did not have the all the files it needed to run correctly.

I used `CHPL_DEVELOPER` to test the PR above which strangely has the correct behavior. However, `start_test` overrides `CHPL_DEVELOPER` and I didn't check its output and accepted as the good file. So, in that PR, the good file of the relevant test had a CUDA error by mistake.

Test:
- [x] failing GPU test passes
- [x] standard
- [x] gasnet

### CODE REVIEW

**Comment by e-kayrakli** [comment]
@benharsh -- I forgot to merge this yesterday.

Do you have any qualms about generalizing the POD-check here?

**Review by benharsh — APPROVED** [review]
I _think_ the ``isPODType`` change is fine here, especially if testing keeps passing. Technically I guess I'd prefer to do that check in the compiler to avoid instantiating ``isSubtype`` against ``c_array`, since in the compiler we can just check the flag. Let's keep an eye out to see if this impacts compilation time at all.

**Comment by e-kayrakli** [comment]
While I don't see any noticeable change in the first day after this change (https://chapel-lang.org/perf/comp-default/?startdate=2023/06/29&enddate=2023/07/13&graphs=all), https://github.com/chapel-lang/chapel/issues/22519#issuecomment-1633813115 is a case where taking @benharsh's approach would have solved the issue.

I am inclined to think that https://github.com/chapel-lang/chapel/blob/main/compiler/resolution/functionResolution.cpp#L11987-L11991 is where a special-casing should occur, but I don't understand that part very well. i.e. how's an array record POD? I can see this as a special-casing, but what if the array elements aren't POD?

While where we are seems to be an improvement, it is not perfect. Though, I am not too motivated to pursue this any further with quick fixes. I am considering creating a wider issue for bulk transfer compatibility of types where we can talk about POD-ness checks.

**Comment by e-kayrakli** [comment]
https://github.com/chapel-lang/chapel/issues/22743 is the wider issue that I talked about above.

I want to resolve that and not pursue any more bandaids. I will keep monitoring the compiler performance for a while, though.

**Pull request merged**
