### PR TITLE
Dramatically improve task creation speed

### PR DESCRIPTION
**Pull request by ronawho**
Improve task creation times by using a hybrid spin/condwait scheme for qthreads
nemesis scheduler. While digging into LCALS performance we discovered a large
portion of our overhead compared to OpenMP is in task creation. This improves
the performance of a task startup microbenchmark from 21s to 7s compared to
3.2s for an OpenMP variant. While we're still off from OpenMP, this is a vast
improvement, and I have a good lead on the remaining sources of overhead. With
additional work, we should be able to get close if not on par with OpenMP task
creation times.

Details of this commit:

qthreads --enable-condwait-queue controls whether idle workers spinwait or do a
condwait while looking for new tasks. Pure spinwaiting kills single threaded
performance because idle threads pound the cpu nonstop, but pure condwait (our
previous default) increases task startup.

Since neither pure spinwaiting nor pure condwaiting work, this implements a
simple hybrid spin/condwait approach where we spin QT_SPINCOUNT (default
300,000) iterations before doing a condwait.

Initially I thought this approach was too naive, but it's actually very similar
to what gnus omp implementation does (and is also where the 300,000 spins comes
from.)

This has a dramatic performance improvement for several benchmarks:

  - 3X speedup on task startup microbenchmark
  - 2.5 speedup for LCALS and Lulesh
  - 50% speedup for HPL, NAS CG, and NAS FT
  - 25% speedup for MiniMD and SSCA#2
  - minor improvements for other benchmarks

I only saw one minor regression (10% perf loss) for the serial synch_p2p PRK,
but considering the other improvements, this seems acceptable.

This hybrid scheme still needs to be applied to other schedulers, and needs to
be contributed upstream, but given it's impact it's worth adding it now.

### CODE REVIEW

**Comment by ronawho** [comment]
@daviditen mind reviewing? This is similar to what you saw before, but changed back to a while loop for clarity, and changed the name of the env var. 

I'd also appreciate if you could check through the perf results to make sure I didn't miss any regressions: http://chapel.sourceforge.net/perf/chapcs/taskSpawn/?startdate=2016/11/18&enddate=2016/11/24&graphs=all

@gbtitus just FYI. I'm probably going to merge this before you get back, but I figured you'd want to know about it.

**Comment by ben-albrecht** [comment]
@ronawho I wouldn't worry about the synch_p2p regression at all. The current implementation is not comparable to the reference version.

**Comment by daviditen** [comment]
I looked through the perf graphs you linked and it looks like any losses except for synch_p2p are small and possibly in the noise.

Do you understand what q->frustration is for?  It looks like it is used to do a spin then condwait operation, with a spin limit of 1000.  Would it be the same as this PR to use that and change the limit to 300,000?  Looking at QTHREAD_CONDWAIT_BLOCKING_QUEUE, it doesn't do the SPINLOCK_BODY() on that branch though.

This change looks good assuming that using q->frustration is not the right way to go.

**Comment by ronawho** [comment]
I had tried just increasing the frustration level, but it's slower because frustration is incremented atomically. Also it doesn't do SPINLOCK_BODY, which basically turns into a pause instruction which tells the processor that it's in a spinloop, which allows it to optimize for a spinloop and go into a lower power mode. 

I plan to look at removing frustration altogether, but for now I left it because it prevents a call to condwait_signal in the enque code, which I was worried could be expensive.

**Comment by daviditen** [comment]
OK, got it.  Thanks.

**Comment by ronawho** [comment]
Just FYI I'll probably merge on Friday since it should be quiet for a few days before and after then.

**Pull request merged**
