### PR TITLE
Pre-release prep. Chapel 1.18.0: bump spec vers+date, rebuild pdf

### PR DESCRIPTION
**Pull request by awallace-cray**
Chapel spec rebuild for 1.18.0

### CODE REVIEW

**Comment by awallace-cray** [comment]
@vasslitvinov for sanity ck of latest text change
@bradcray for timing and content
Thanks!

**Comment by bradcray** [comment]
@ronawho and @benharsh were finding problems with the index being updated when they built yesterday.  Could one of you check whether this version dodged that problem?

**Comment by ronawho** [comment]
Index numbers look right to me

**Comment by bradcray** [comment]
Date and version number bump look right to me.  I think @vasslitvinov committed the last spec changes, so may want to make sure they showed up here.

**Pull request merged**
