### PR TITLE
Futures related to 'new C()' as a default argument value

### PR DESCRIPTION
**Pull request by bradcray**
This PR files two futures:

* default-arg-new-leaks.chpl: demonstrates that using a default argument value of `new C()` results in memory leaks due to the class never being freed
* default-arg-typeless.chpl: demonstrates that setting a default argument value of `new C()` doesn't support passing an actual argument of `new C()` into the routine which seems surprising.

### CODE REVIEW

**Comment by cassella** [comment]
writeln() to the rescue,

```chapel
class C {
  var x: int;
}

proc bar(c = new C()) {
  writeln(c.type:string);
  writeln(c);
}

writeln("Default bar");
bar();

writeln("Supplied unmanaged C");
bar(new unmanaged C());
```

```
Default bar
unmanaged C
{x = 0}
Supplied unmanaged C
unmanaged C
{x = 0}
```
Well, maybe "rescue" is a little strong.  

I don't see an issue to attach this comment to.

**Comment by bradcray** [comment]
See issue #12638.

This explains what the compiler thinks the formal argument type is, but there's no reason to believe it should be `unmanaged C` is there?

**Comment by bradcray** [comment]
(tagging @mppf on this conversation since he's the expert)

**Comment by cassella** [comment]
I don't have any insight into why that's what it thinks, but given that that's what it thinks it explains why there's a leak, and why the call doesn't resolve with `new (borrowed) C()`.

(Oh, oops, I saw the issue number in the email update to the other issue this morning, but forgot about it here (and didn't see one in the .futures.))

**Pull request merged**
