### PR TITLE
Add Random.choiceIndex()

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Version of Random.choice() that chooses from indices rather than array elements

Fixes https://github.com/chapel-lang/chapel/issues/14865

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
Did a clone of Random.choice and made the necessary changes. Tested those changes by using the code provided by @ty1027 (with some modifications):

```
use Random;

var rng = new owned RandomStream( eltType= real, seed= 200 );
//var rng = new owned RandomStream( eltType= int, seed= 200 );   // this also works but not sure about details...

var arr = ["a", "b", "c"];

var n = 20;

writeln();
for i in 1..2 do writeln( rng.choiceIndex( arr ) );

writeln();
for i in 1..2 do writeln( rng.choiceIndex( arr, size= 3 ) );

writeln();
for i in 1..2 do writeln( rng.choiceIndex( arr, size= 3, replace= false ) );

```
Which gives:

```

3
2

2 1 3
1 2 1

1 3 2
1 3 2
```
Now working on adding tests. Thanks!

**Comment by bradcray** [comment]
Though I requested this change, I'd guess that @ben-albrecht would be a more appropriate reviewer since he implemented the original choice() support in PR #12027.  Ben, are you up for that?  (no rush on my behalf).

**Comment by ben-albrecht** [comment]
>  Ben, are you up for that? 

Sure thing.

I have some clarifying questions over in https://github.com/chapel-lang/chapel/issues/14865#issuecomment-584726726 before reviewing.

**Comment by Aniket21mathur** [comment]
@ben-albrecht sorry for the delay. I was involved in my university exams. I will start working on this from today.

**Comment by Aniket21mathur** [comment]
Replaced by #15154

**Pull request closed without merging**
