### PR TITLE
Add iterator to upper/lower triangular matrix

### PR DESCRIPTION
**Pull request by baocvcv**
Hi, I implemented a simple iterator for upper/lower triangular matrices (from #5753) based on my understanding. I also added a simple test. Not sure if I understood the request accurately. Could you please take a look at it? @ben-albrecht 
it's my first time trying to contribute to Chapel, or any open source projects. Please let me know if I did anything wrong or inappropriate. Many thanks.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Hi @baocvcv - thanks for your contribution. I think we first need to determine the design for this feature before I can review a proposed implementation. Check out [contributor info docs](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst) if you have not already, which will guide you through how to "claim" a task, and how to propose a design for a task that is not well defined such as this one.

I think your implementation is on the right track, but am not sure about a few things myself yet:

- what is the driving use-case for these iterators and does it solve them? 
  - @npadmana do you have any thoughts on this? (I can't recall if it was you who proposed this or not)
- should these support parallel iterators?
- is this the right naming scheme for these iterators?

**Comment by baocvcv** [comment]
Thank you @ben-albrecht ! I will make sure to create a design issue when introducing anything new. Is it fine to discuss this feature under this issue or shall I open a new one?

**Comment by ben-albrecht** [comment]
A new issue would be preferable, in case we end up needing to close this PR and open a new one.

**Comment by ben-albrecht** [comment]
> what is the driving use-case for these iterators and does it solve them? 

One idea here is that this could be used to populate a sparse array with only the lower or upper triangular values.

**Comment by ben-albrecht** [comment]
@baocvcv - do you want to open a new issue and close this PR for now?

**Comment by ben-albrecht** [comment]
@baocvcv - I'm going to close this draft PR. We can continue discussion when you open an issue on this feature.

**Pull request closed without merging**
