### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in

chpl-init.c chpl-gpu.c qio_style.h
IO.chpl GPU.chpl BigInteger.chpl YAML.chpl
StringCasts.chpl ChapelRange.chpl ChapelDomain.chpl
primers/arrays.chpl
return-type-inference.cpp parsing-queries.cpp PragmaList.h BoolType.h
arrays.rst, procedures.rst, gpu.rst
preFold.cpp interfaceResolution.cpp functionResolution.cpp
normalize.cpp loopInvariantCodeMotion.cpp

### CODE REVIEW

**Comment by cassella** [comment]
I only spot-tested `test/ranges/strided`

@jeremiah-corrado, the most impactful change is yours in modules/standard/IO.chpl (I presume it was supposed to match the others.)

Two other changes were to code:

modules/internal/ChapelRange.chpl

frontend/include/chpl/uast/PragmaList.h (The changed strings don't appear anywhere in test/)

**Review by jeremiah-corrado — APPROVED** [review]
Library changes look good to me, thanks!

I'll run a paratest on this branch and put results here.

**Comment by jeremiah-corrado** [comment]
Paratest came back clean!

It doesn't look like the pragma that was adjusted is used anywhere. @mppf, could you double check that change is okay as the pragma author before I merge.

**Comment by mppf** [comment]
@jeremiah-corrado - those pragmas are only used internally by the compiler with the uppercase name, so it is fine to adjust the other name as is done here.

**Pull request merged**
