### PR TITLE
Make madness tests less sensitive to minor floating point precision differences

### PR DESCRIPTION
**Pull request by ronawho**
Make madness tests less sensitive to minor floating point precision differences

This is a logical extension of #754.

The madness tests print out floating point values, which are captured in the
.good files. Unfortunately, some of the values are extremely close to zero, or
extremely large (~2 quadrillion), which means minor differences across
configurations can cause the output to differ slightly.

#754 quieted some of the madness tests for cases where values were very close
to zero by truncating the values to 0.0. Unfortunately, it only applied the
truncation for tests that happened to be failing on cygwin, instead of updating
all the madness tests. To quiet any remaining floating point precision issues
this PR:

 - applies truncation to all the madness tests uniformly
 - updates truncation so truncate extremely large reals to the nearest 10

Prior to this fix, 11 of the madness tests failed on:
 - chapcs* with --fast
 - linux32 with --denormalize
 - probably a bunch of other configurations

### CODE REVIEW

**Comment by ronawho** [comment]
Passes full std testing and `start_test test/studies/madness` for linux32 w/ denormalize, chapcs* w/ --fast, and on osx w/ std config

**Comment by ronawho** [comment]
@vasslitvinov mind reviewing since it looks like you reviewed #754?

**Comment by ronawho** [comment]
@e-kayrakli and @benharsh just FYI, this is the first of the changes to allow `--denormalize` to pass without regressions on linux32. It's been pretty slow going, but hopefully I can get the others fixed tonight as well

**Comment by vasslitvinov** [comment]
Looks good to me.

**Pull request merged**
