### PR TITLE
Fix an out-of-bounds array access in the lexer

### PR DESCRIPTION
**Pull request by daviditen**
If the `--comment-style` flag is not used, then `fDocsCommentLabel` is an empty
string with length=0. Make sure it is not zero-length before indexing into it
with `len - d` with `d` positive.

Regenerated flex-chapel.cpp and flex-chapel.h after making the above change.

### CODE REVIEW

**Comment by daviditen** [comment]
Passed a full default paratest on Linux64.

**Comment by lydia-duncan** [comment]
This looks reasonable to me.  I'm surprised this wasn't caught earlier, though.  Would you mind adding a test case that failed before but works now?

**Comment by daviditen** [comment]
Thanks Lydia!

I discovered this by building the compiler with address sanitation with clang, then compiling release/examples/hello.chpl. I don't currently have a test that fails because of it without address sanitation enabled, but essentially everything fails with it.

**Comment by lydia-duncan** [comment]
Ah, okay!  Good to go, then!

**Pull request merged**
