### PR TITLE
Deprecated file.localesForRegion in I/O module

### PR DESCRIPTION
**Pull request by vwang0101**
Signed-off-by: Vivian Wang <vwang0101@gmail.com>

For [issue #20274](https://github.com/chapel-lang/chapel/issues/20274)

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Interesting, not sure why that thinks that's an incorrect sign off.  Is it the same email address you use for your Github profile?

**Comment by vwang0101** [comment]
> Interesting, not sure why that thinks that's an incorrect sign off. Is it the same email address you use for your Github profile?

Ah I see the error message now -- I had amended by signoff to my first and last name, instead of my username, but it seems like that it was expecting my username.

**Comment by lydia-duncan** [comment]
Ah, okay, well hopefully that's a straight-forward fix

**Comment by lydia-duncan** [comment]
I'm running full testing on the branch now regardless :)

**Comment by vwang0101** [comment]
> I'm running full testing on the branch now regardless :)

Let me know when testing is done, and I'll force push my commit with the correct(🤞) sign off :)

**Comment by lydia-duncan** [comment]
It should be fine to push at any point, I've already checked it out locally

**Comment by lydia-duncan** [comment]
New test worked as expected, longer testing got interrupted by a machine disconnect.  I'm going to migrate home and restart the longer testing there (so it'll probably be a few hours)

**Comment by lydia-duncan** [comment]
Testing passed!  Thanks :)

**Pull request merged**
