### PR TITLE
Add halt wrappers for use in initializers and iterators

### PR DESCRIPTION
**Pull request by ronawho**
Error handling isn't supported for initializers or iterators today. These halt
wrappers are intended to mark such cases so that we can more easily
find/identify them in the future.

See https://github.com/chapel-lang/chapel/issues/7134 and https://github.com/chapel-lang/chapel/issues/8793 for more info

### CODE REVIEW

**Comment by mppf** [comment]
Are you intending to add calls to these in the compiled code in this PR?

**Comment by ronawho** [comment]
Not in this PR, but in PRs that I'll be opening today and monday

**Comment by mppf** [comment]
This PR seems OK to me then. I'd consider prefixing the new routines with `chpl_` though.

**Comment by ronawho** [comment]
Hmm, that's a good point. I'd like to keep the names relatively short/clean, since I plan on adding other wrappers for misc things like:
 
 - pureVirtualMethodHalt
 - unreachableCodeHalt

and wrappers for execution time halts: 
 - nilCheckHalt
 - boundsCheckHalt
 - formalDomainCheckHalt
 - localCheckHalt
 - safeCastCheckHalt
 - divByZeroCheckHalt

Thoughts on moving these wrappers into a new not-included-by-default module named ChapelHaltWrappers or something instead of prefixing with chpl_?

**Comment by mppf** [comment]
> Thoughts on moving these wrappers into a new not-included-by-default module named ChapelHaltWrappers or something instead of prefixing with chpl_?

My thought is simply "+1".

**Pull request merged**
