### PR TITLE
Refactor the var declaration statement in the parser

### PR DESCRIPTION
**Pull request by bradcray**
This performs a refactoring on the parser rule that handles
vars, consts, params, refs, and const refs in order to reduce
the amount of repeated code.  It does this by moving the
choice of keywords into a new rule that converts the keywords
into the appropriate flag (if any) or flags.  This replaces
the parser-level variables that were used for this purpose
previously.

As part of this change, I made `buildVarDecls()` take the
flags as a pointer in order to have the set of flags escape
the scope in which it was declared.  This also supported
cleaning up another call to the routine that didn't want to
actually send in any flags.

The motivation for this change is to simplify the implementation
of permitting `extern` var declarations to rename themselves
as in issue #6601.  But it's a nice cleanup independent of that
issue.

TODO:
- [x] I need to check in the flex-/bison-generated files once this passes review

### CODE REVIEW

**Comment by bradcray** [comment]
Travis can't be expected to pass until I check in the flex-/bison-generated files.

**Comment by bradcray** [comment]
I don't have experience looking for memory leaks in the compiler.  Do you have a suggested approach to take?  Are you worried specifically about the flags being leaked, or something else more general?

**Comment by bradcray** [comment]
I see a bit more memory being leaked on my branch than on master (~500-600 bytes out of 1,787,918 bytes), but both branches also show wiggle from run to run on the order of a few hundred bytes, so I don't know whether this is a real concern or not.

I feel pretty confident that the flags will not be leaked by construction, unless you're seeing something to be worried about that I'm not.  Specifically, they're only allocated in buildVarDeclFlags(), which is only called by the parser in the new var_decl_type rule, which is only used in the var_decl_type rule, where it's always passed into the buildVarDecls() call, where it's always deleted if non-NULL.  The only other call to buildVarDecls() in externCResolve.cpp now sends in NULL.

**Comment by mppf** [comment]
Right, you might know that the parser never does this, but I worry it might execute the semantic actions for nonterminals that didn't end up in the parse tree. But anyway thanks for looking.

**Comment by bradcray** [comment]
If that were the case, we'd have much bigger problems, wouldn't we?  (any action that created a new VarSymbol or new Expr or whatever would potentially leak it?).  It's been a long time since I've had a compilers course, but my intuition is that LR parsers wouldn't run actions speculatively by construction.

**Comment by mppf** [comment]
Actually we wouldn't have much bigger problems, because we run a kind of garbage collection on the AST nodes (that's what gBlockStmts or whatever is about).

**Comment by mppf** [comment]
I had thought that might be the reason why we were storing flags in "dummy" AST nodes. E.g. linkage_spec nonterminal.

**Comment by bradcray** [comment]
Oh, good point about the GC.  Though I don't think parser speculation is the reason that we have the global lists or the garbage collection.  I think that just relates to our laziness in writing the compiler in the early days (wanting to unplug subtrees from pointers without worrying about whether we should delete them or not).  We used to use BoehmGC, but then ended up converting over to this homegrown approach instead.

**Pull request merged**
