### PR TITLE
added code of conduct

### PR DESCRIPTION
**Pull request by jivthesh**

### CODE REVIEW

**Comment by bradcray** [comment]
@jivthesh: can you provide more context for this PR?

**Comment by jivthesh** [comment]
@bradcray https://www.contributor-covenant.org/version/1/4/code-of-conduct/

**Comment by bradcray** [comment]
I'm still not clear on your motivation or process for submitting the PR.  Can you clarify?

**Comment by jivthesh** [comment]
@bradcray https://www.contributor-covenant.org/version/1/4/code-of-conduct/
i have added coc from this

**Comment by lydia-duncan** [comment]
@jivthesh - I think Brad's question is more about why.  We are definitely missing a code of conduct and that is something that should be rectified so we're grateful for the effort, though there are considerations to be taken into account w.r.t. the parent company of most of our core team members.  Are you a Chapel user that noticed this was missing and were looking for a way to contribute?  Are you more focused on making sure codes of conduct are used more widely in general?  Would you be volunteering to help enforce this?  Brad may have other questions as well

**Comment by jivthesh** [comment]
@lydia-duncan i an not a chapel user .yes i can volunteer to help

**Comment by cassella** [comment]
There's previous discussion of a code of conduct in #8276.

**Comment by ben-albrecht** [comment]
I'm going to close this due to inactivity / being blocked by #8276.

@jivthesh - If you'd like to continue this effort, I think the next steps are to help move the the discussion in #8276 forward towards a consensus on which Code of Conduct we will adopt.

**Pull request closed without merging**
