### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in

stringutil.cpp, cg-expr.cpp, main/driver.cpp, resolution/wrappers.cpp
comm-ofi.c, qio/sys.c
StandardModuleStyle.rst, Interfaces.md
BigInteger.chpl, Path.chpl,
DateTime.chpl and test/deprecated/strptime.good,

### CODE REVIEW

**Comment by cassella** [comment]
I didn't know what to do with `compiler/parser/parser.cpp:370`, so I left it alone:

```
        // throwr error will concatenated messages
```

**Comment by lydia-duncan** [comment]
Looks like @king-11 added that line in #17559.  Lakshya, do you remember what you were trying to say there?

**Comment by king-11** [comment]
😅 ahh as I remember it should be _"throw error with concatenated message"_

**Comment by cassella** [comment]
> sweat_smile ahh as I remember it should be _"throw error with concatenated message"_

Ah, thanks @king-11 .  I can update my PR this evening, unless you'd like to fix it yourself?

**Comment by king-11** [comment]
No, I think it's better if you can include it in this PR only 😃.

**Comment by cassella** [comment]
Ok, updated.

I also meant to mention that I ran the datetime deprecation test with the .good file change (and started typing it as "datetype" every time I typed it, including in this sentence) and it still passes.

**Review by lydia-duncan — APPROVED** [review]
This all looks fine, I'll just run a paratest to be certain

**Pull request merged**
