### PR TITLE
Adding a seperate entry for locating README.devel in "What's next" section

### PR DESCRIPTION
**Pull request by kushalsingh007**
- Allows a developer to directory locate the file map

### CODE REVIEW

**Comment by bradcray** [comment]
Sorry, I wasn't on chat when this was being discussed, but I think this approach is problematic.  Specifically, README.devel isn't included in the release (and README.rst is), so I think this will result in a "dangling link" of sorts.

Based on feedback from @ben-albrecht, I've been plotting a refactoring of READMEs such that the current README.rst is oriented toward the GitHub context (where developers are more likely to be) while much of the content of the current REAMDE.rst is changed into a QUICKSTART.rst (or something equivalent).  I think this is tricky enough to get right (and get people happy with) that it should be developed internally.

A related project might be to look at cases where the current developer tree differs from the release tree and figure out a plan for making them not differ.  E.g., could the developer tree have a symbolic link to test/release/examples called examples/ to avoid this confusion and not require README.devel to translate between the two?  (I recall we've had some troubles with symbolic links on some platforms, but if our test system and code base didn't rely on them working and they were just for end-users....?)

**Comment by kushalsingh007** [comment]
I think then I'll close this PR. But I am not sure about the last part that you mentioned about symbolic links not working on some platforms. Could you elaborate a bit more on that part ?

**Comment by bradcray** [comment]
Hi @kushalsingh007: I wasn't trying to be intentionally vague, but simply don't remember what the issue was -- something related to a Java implementation of git or something like that.  Let me check with the team and see if anyone else remembers.

**Comment by bradcray** [comment]
Having looked into this a bit, it appears that certain versions of jgit/Java did not support symlinks, such that when a repo was checked out, the symlinks would not be preserved.  We had a few tests that relied on symlinks and broke in our nightly testing when we had to use a jgit/Java client of a certain vintage. This is the reason we've avoided symlinks in parts of our code that are crucial for our internal testing/validation suite.  But, if we were adding symlinks simply to better unify the developer experience with the user one and did not rely on those links for testing (i.e., avoiding them as we already do today), that seems like it could be acceptable.

**Comment by kushalsingh007** [comment]
Oh, Now I get it. Thanks

**Pull request closed without merging**
