### PR TITLE
Contributors list for Chapel 1.16

### PR DESCRIPTION
**Pull request by bradcray**

### CODE REVIEW

**Comment by bradcray** [comment]
This is a first cut at the contributors list for 1.16, reflecting those who I believe contributed code/changes that will appear in the release download.

@chapel-lang/core-contributors : Please make sure any external PRs you reviewed are reflected in the list.

New contributors, please make sure I spelled and alphabetized your name correctly and got your affiliation right ( @Spartee , @s-geronimoanderson , @mlchu , @sergeyklay , @LouisJenkinsCS , @krishnakeshav , @coodie , @barrymoo , @saru95 )

**Comment by lydia-duncan** [comment]
How does the update to the GSOC link impact those that were contributors in the previous iteration?

**Comment by bradcray** [comment]
> How does the update to the GSOC link impact those that were contributors in the previous iteration?

I'm not sure how to answer this question.  Do you want me to ask them?

**Comment by bradcray** [comment]
Hi @LouisJenkinsCS -- There is one named @chapel-lang/chapel-contributors but we're apparently not very good at keeping it up-to-date.  I've just added you to it (and am happy to add anyone else we've overlooked who's submitted a CLA).

**Comment by lydia-duncan** [comment]
> >    How does the update to the GSOC link impact those that were contributors in the previous iteration?

>  I'm not sure how to answer this question. Do you want me to ask them?

Sorry, let me clarify.  It looks like the old link points to our org page for 2016 (and lists the projects Andrea and Kushal worked on) and the new link only lists the projects for 2017.  If someone actually follows the link it would be confusing to not see something for everyone listed as GSOC - I would prefer to see a separate link for GSOC 2016 and GSOC 2017 since it doesn't look like there will be an overarching group page for our org that links to both.

**Comment by saru95** [comment]
@bradcray is it possible for me to be added as well to @chapel-lang/chapel-contributors ?

**Comment by bradcray** [comment]
@saru95 : Done

**Pull request merged**
