### PR TITLE
Add 'inline' on .borrow()

### PR DESCRIPTION
**Pull request by vasslitvinov**
This removes 'proc type borrow()'. It is not used and would not work even if it were, because it accesses a field on 'this'. Also touches up a couple of comments.

### CODE REVIEW

**Review by jabraham17 — COMMENTED** [review]
The `inline` changes look good to me, but there are 3 other changes to comments that look unrelated. Are these intentional?

**Comment by vasslitvinov** [comment]
@jabraham17 the other changes are too small for a PR of their own, so I folded them into this PR. Those other changes are "trivial" and do not need to be reviewed.

**Review by jabraham17 — APPROVED** [review]

**Comment by mppf** [comment]
@vasslitvinov -- seems worth updating the title, since this PR (as merged) does not add inline on .borrow.

**Comment by bradcray** [comment]
This change came up in a deep-dive yesterday, and I just came across it today when writing up status.  The following gives me pause:

> It is not used

"It is not used" — presumably you mean "by our testing system and modules"?  (yet we don't really know whether it's used in the field or not)

> and would not work even if it were, because it accesses a field on 'this'

It was asserted yesterday that it had worked in recent releases, and I was able to write this test that seemed to work:

https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3rZJzEouLFZwVqmu5SioLUhVKFGwVNPLL81JTFJw19ZLyi4ryyzU0rbnKizJLUnPyNEqsikuKMvPSNa0hJkANghkIAA

In asking these questions, I'm not necessarily championing preserving this routine.  But it seems like it should've been deprecated rather than just removed outright.  I also don't remember any discussion about whether it should be removed, which I'd consider our standard practice.

**Comment by vasslitvinov** [comment]
I very obviously overlooked that. Suggestions for what to do here?

**Comment by bradcray** [comment]
Reinstate it and start a design discussion about whether to deprecate, mark unstable, or preserve?

**Comment by vasslitvinov** [comment]
The borrow() type method is back and available for design discussions.

**Comment by vasslitvinov** [comment]
@mppf - I am not involved in the design of the owned type, so somebody else needs to "own" this.

**Comment by jabraham17** [comment]
I can take ownership of this. I will spin off a separate design issue for it

**Comment by jabraham17** [comment]
Discussion can continue here #22273

**Pull request merged**
