### PR TITLE
In cullOverReferences a reference is required for an explicit ref var

### PR DESCRIPTION
**Pull request by daviditen**
If the symbol a ContextCall is being moved to is an explicit ref variable
(FLAG_REF_VAR) then the reference is necessary, so the value function should
not be used.

Removed three .futures.

Tested on standard linux64.

### CODE REVIEW

**Comment by mppf** [comment]
+1

**Comment by daviditen** [comment]
Thanks!

**Comment by vasslitvinov** [comment]
If it does the trick, it's fine by me.

Please spot-check under gasnet before merging, just in case.

**Comment by daviditen** [comment]
I did a gasnet spot check on release/examples.  All passed.

**Pull request merged**
