### PR TITLE
Array views: slices only

### PR DESCRIPTION
**Pull request by bradcray**
This is a work-in-progress...

### CODE REVIEW

**Comment by bradcray** [comment]
test/release/examples failures:

Slice out of bounds
--------------------
* benchmarks/miniMD/miniMD.chpl (compopts: 1, w/out StencilDist):
   - in neighbor.chpl, in line:
 
          Pos[d][1..Count[d]] += P

    Count[d] is 9 while Pos[d].domain is {1..6}


Use of => operator with a slice array view
------------------------------------------
* benchmarks/miniMD/miniMD.chpl (compopts: 2, w/ StencilDist):
   - use of => operator in StencilArr.dsiNoFluffView() causes problems due to slice array view

Trying to reindex a slice
------------------------
* primers/slices.chpl
* spec/Arrays/reindexing.chpl

Can't resolve dsiSlice() in Cyclic distribution
--------------------------------------------
(this is due to bulk transfer being on by default, similar to what I used a halt() to get around in BlockDist.chpl):
* benchmarks/hpcc/fft.chpl
* primers/distributions.chpl

**Comment by bradcray** [comment]
Failures in test/arrays:

chpl_serialReadWriteRectangular unresolved
------------------------------------------
[Error matching compiler output for arrays/bradc/paulslice2]
[Error matching compiler output for arrays/bradc/stridedArrayArg]
[Error matching compiler output for arrays/bradc/localSlices/localslice]
[Error matching compiler output for arrays/bradc/localSlices/localslice2D]
[Error matching compiler output for arrays/bradc/localSlices/localsliceOOB]
[Error matching compiler output for arrays/bradc/localSlices/localsliceOOB2]
[Error matching compiler output for arrays/bradc/localSlices/nonlocalslice]
[Error matching compiler output for arrays/bradc/reindex/reindex]
[Error matching compiler output for arrays/bradc/slices/sliceArray]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride]
[Error matching compiler output for arrays/deitz/part6/test_big_stride]
[Error matching compiler output for arrays/vass/slices-with-negative-strides-1]

attempt to calll dsiReindex()
-----------------------------
[Error matching compiler output for arrays/bradc/slices/reindexIndTypeMismatch]
[Error matching compiler output for arrays/bradc/slices/reindexIndTypeMismatch2D]
[Error matching compiler output for arrays/deitz/part1/test_array_arg8]
[Error matching compiler output for arrays/deitz/part1/test_array_arg9]
[Error matching compiler output for arrays/deitz/part2/test_array_reindex_aliases]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride2]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride3]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride4]
[Error matching compiler output for arrays/deitz/part4/test_alias4]
[Error matching compiler output for arrays/dinan/reindex]
[Error matching compiler output for arrays/diten/arrayAliasing]
[Error matching compiler output for arrays/diten/arrayAliasing2D]
[Error matching compiler output for arrays/elliot/removeInnerMultOpt/removeInnerMult]
[Error matching compiler output for arrays/elliot/removeInnerMultOpt/stridedReindexRequiresInnerMult]

CyclicDist tries to call dsiSlice()
-----------------------------------
[Error matching compiler output for arrays/deitz/test_remote_cyclic_slicing]

unresolved 'init' call
----------------------
[Error matching compiler output for arrays/deitz/part4/test_array_alias_field]
[Error matching compiler output for arrays/ferguson/semantic-examples/9-array-alias-field2]

unresolved 'ranges' call
------------------------
[Error matching compiler output for arrays/diten/strideBlock]

new leaks
---------
[Error matching program output for arrays/ferguson/semantic-examples/4-init-slice]

**Comment by benharsh** [comment]
Regarding the "unresolved 'ranges' call" issue, it looks like we shouldn't be calling ``chpl_serialReadWriteRectangular`` with a BlockDom. Perhaps we should update the 'dsiSerialWrite' interface to accept a domain?

**Comment by bradcray** [comment]
Failures in test/arrays:

These tests try to reindex a slice (e.g., A[2..n-1].reindex[0..n-3]  or var A: [1..n] => B[0..n-1])
--------------------------------------------------------------------------------------------
[Error matching compiler output for arrays/bradc/slices/reindexIndTypeMismatch]
[Error matching compiler output for arrays/bradc/slices/reindexIndTypeMismatch2D]
[Error matching compiler output for arrays/deitz/part1/test_array_arg8]
[Error matching compiler output for arrays/deitz/part1/test_array_arg9]
[Error matching compiler output for arrays/deitz/part2/test_array_reindex_aliases]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride2]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride3]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride4]
[Error matching compiler output for arrays/deitz/part4/test_alias4]
[Error matching compiler output for arrays/dinan/reindex]
[Error matching compiler output for arrays/diten/arrayAliasing]
[Error matching compiler output for arrays/diten/arrayAliasing2D]
[Error matching compiler output for arrays/elliot/removeInnerMultOpt/removeInnerMult]
[Error matching compiler output for arrays/elliot/removeInnerMultOpt/stridedReindexRequiresInnerMult]

These tests use a => in a constructor to alias an array to a slice
---------------------------------------------------------------
[Error matching compiler output for arrays/deitz/part4/test_array_alias_field]
[Error matching compiler output for arrays/ferguson/semantic-examples/9-array-alias-field2]

unresolved 'ranges' call
------------------------
[Error matching compiler output for arrays/diten/strideBlock]

new leaks
---------
[Error matching program output for arrays/ferguson/semantic-examples/4-init-slice]

**Comment by bradcray** [comment]
Need a look
=========

new memory leaks
----------------
[Error matching program output for arrays/ferguson/semantic-examples/4-init-slice]
[Error matching program output for memory/sungeun/refCount/arrays]
[Error matching program output for memory/sungeun/refCount/arraysAndDomains]

index out of bounds
-------------------
[Error matching program output for distributions/bharshbarg/stencil/localReads]

missing dsiHasSingleLocalSubdomain()
------------------------------------
[Error matching compiler output for distributions/bharshbarg/stencil/slice]

array assignment error
----------------------
[Error matching compiler output for distributions/vass/testReplicatedVar2]

array swap error
----------------
[Error matching compiler output for functions/diten/refIntents]

missing adjustBlkOffStr...
--------------------------
[Error matching compiler output for optimizations/bulkcomm/bharshbarg/misc]
[Error matching compiler output for optimizations/bulkcomm/bharshbarg/rankChange]
[Error matching compiler output for optimizations/bulkcomm/bharshbarg/stridedAssignDR]

new module throws output off
----------------------------
[Error matching compiler output for optimizations/deadCodeElimination/elliot/countDeadModules]

bulk transfer didn't happen (bharsh)
------------------------------------
[Error matching program output for optimizations/sungeun/bulk_transfer/assign]

no dsiNoFluffView
-----------------
[Error matching compiler output for release/examples/benchmarks/miniMD/miniMD (compopts: 2)]

missing file (?!)
-----------------
[Error matching compiler output for studies/amr/advection/amr/AMR_AdvectionCTU_driver]

no dsiRankChange
----------------
[Error matching compiler output for studies/cholesky/jglewis/test_cholesky]
[Error matching compiler output for studies/cholesky/jglewis/test_dataflow_cholesky]
[Error matching compiler output for studies/cholesky/jglewis/version2/dataflow/test_dataflow_cholesky]
[Error matching compiler output for studies/cholesky/jglewis/version2/standard_cholesky/test_standard_cholesky]
[Error matching compiler output for studies/hpcc/HPL/marybeth/HPL]
[Error matching compiler output for studies/lu/marybeth/blockLU]
[Error matching compiler output for studies/matrixlib/testBlockLU]
[Error matching compiler output for users/jglewis/cholesky_version_1/test_cholesky]

missing Vector.init()
---------------------
[Error matching compiler output for users/shetag/tensor]


Punting on for now -- needs other array view types
======================================

Calls reindex on a slice
------------------------
[Error matching compiler output for arrays/bradc/slices/reindexIndTypeMismatch]
[Error matching compiler output for arrays/bradc/slices/reindexIndTypeMismatch2D]
[Error matching compiler output for arrays/deitz/part1/test_array_arg8]
[Error matching compiler output for arrays/deitz/part1/test_array_arg9]
[Error matching compiler output for arrays/deitz/part2/test_array_reindex_aliases]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride2]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride3]
[Error matching compiler output for arrays/deitz/part3/test_slice_stride4]
[Error matching compiler output for arrays/deitz/part4/test_alias4]
[Error matching compiler output for arrays/deitz/part6/test_big_stride]
[Error matching compiler output for arrays/dinan/reindex]
[Error matching compiler output for arrays/diten/arrayAliasing]
[Error matching compiler output for arrays/diten/arrayAliasing2D]
[Error matching compiler output for arrays/elliot/removeInnerMultOpt/removeInnerMult]
[Error matching compiler output for arrays/elliot/removeInnerMultOpt/stridedReindexRequiresInnerMult]
[Error matching compiler output for distributions/robust/arithmetic/composite/test_composite1]
[Error matching compiler output for distributions/robust/arithmetic/composite/test_composite2]
[Error matching compiler output for distributions/robust/arithmetic/reindexing/test_array_alias2]
[Error matching compiler output for distributions/robust/arithmetic/reindexing/test_strided_reindex2]
[Error matching compiler output for modules/standard/LinearAlgebraJama/TestMatrix]
[Error matching compiler output for release/examples/primers/slices]
[Error matching compiler output for release/examples/spec/Arrays/reindexing]
[Error matching compiler output for studies/hpcc/HPL/stonea/errors/writelnCausesError]
[Error matching compiler output for studies/hpcc/HPL/vass/hpl.hpcc2012]
[Error matching compiler output for studies/madness/aniruddha/madchap/mytests/par-compress/test_compress]
[Error matching compiler output for studies/madness/aniruddha/madchap/mytests/par-reconstruct/test_reconstruct]
[Error matching compiler output for studies/madness/aniruddha/madchap/mytests/par-refine/test_refine]
[Error matching compiler output for studies/madness/aniruddha/madchap/test_diff]
[Error matching compiler output for studies/madness/aniruddha/madchap/test_gaxpy]
[Error matching compiler output for studies/madness/aniruddha/madchap/test_likepy]
[Error matching compiler output for studies/madness/aniruddha/madchap/test_mul]
[Error matching compiler output for studies/madness/aniruddha/madchap/test_showboxes]
[Error matching compiler output for studies/madness/common/test_diff]
[Error matching compiler output for studies/madness/common/test_gaxpy]
[Error matching compiler output for studies/madness/common/test_likepy]
[Error matching compiler output for studies/madness/common/test_mul]
[Error matching compiler output for studies/madness/common/test_showboxes]
[Error matching compiler output for users/bugzilla/bug794133/bug794133]

Uses => in a constructor on an array slice trying to store into an array
------------------------------------------------------------------------
[Error matching compiler output for arrays/deitz/part4/test_array_alias_field]
[Error matching compiler output for arrays/ferguson/semantic-examples/9-array-alias-field2]

**Comment by bradcray** [comment]
@benharsh : I'm looking at this case:  "missing dsiHasSingleLocalSubdom"

**Comment by benharsh** [comment]
I'll be looking at the "index out of bounds" (localReads) and no dsiNoFluffView errors.

**Comment by bradcray** [comment]
Moved the ball forward on that one, but now it falls into the no dsiFluffView category as well...  just pushed some simple commits to reflect that.

**Comment by benharsh** [comment]
Part of the 'localReads' problem is a local-block violation inside StencilDist.

We create an ArrayViewSlice with the "_value" method, which returns the local privatized copy class. If that slice is used on another locale, it will still be pointing to the remove "arr" class. I think we're going to need a 'pid' field to take advantage of slices of privatized arrays.

**Comment by benharsh** [comment]
I'm tempted to punt on the strided transfer fixes until we know more about the RankChangeView, as it complicates the calculations. What do you think? In the meantime, I'm working on a PR that should handle bulk transfers between simple array slices.

**Comment by bradcray** [comment]
Capturing some of what we just said out loud:  Punting on strided transfer fixes is fine with me.  Will be curious about the bulk transfer perf relative to more manual approaches...  Thanks for taking on the privatization improvements... I forgot that they don't come "for free" anymore (i.e., that _instance/_value won't magically transform into a pid).

**Comment by bradcray** [comment]
Here are the gasnet failures I got on a recent run over the release/ mutilocale/ and distributions/ directories:


access of remote data in local block
------------------------------------
[Error matching program output for distributions/robust/arithmetic/kernels/jacobi]
[Error matching program output for distributions/robust/arithmetic/kernels/hpl]
[Error matching program output for distributions/robust/arithmetic/modules/test_module_Norm]
[Error matching program output for distributions/robust/arithmetic/modules/test_module_Sort]
[Error (possible JIRA 154) matching program output for distributions/robust/arithmetic/reindexing/test_array_alias1]
[Error matching program output for distributions/robust/arithmetic/slicing/test_array_slicing1]
[Error (possible JIRA 154) matching program output for distributions/robust/arithmetic/slicing/test_array_slicing2]
[Error matching program output for distributions/robust/arithmetic/slicing/test_array_slicing3]

segfault
--------
[Error matching program output for distributions/robust/arithmetic/performance/multilocale/assignSlice]
[Error matching program output for distributions/robust/arithmetic/performance/multilocale/reduceSlice]

bad I/O
-------
[Error matching compiler output for distributions/robust/arithmetic/slicing/test_strided_slice1]

default rect / array view mismatch
----------------------------------
[Error matching program output for distributions/vass/wrapper_nl4_testReplicatedDist1]
[Error matching compiler output for distributions/vass/wrapper_nl4_testReplicatedVar2]

Same issues as on --local testing
----------------------------------
[Error matching compiler output for release/examples/spec/Arrays/reindexing]
[Error matching compiler output for release/examples/benchmarks/miniMD/miniMD (compopts: 2)]
[Error matching compiler output for release/examples/primers/slices]
[Error matching compiler output for distributions/bharshbarg/stencil/slice]
[Error matching program output for distributions/bharshbarg/stencil/localReads]
[Error matching compiler output for distributions/robust/arithmetic/composite/test_composite1]
[Error matching compiler output for distributions/robust/arithmetic/composite/test_composite2]
[Error matching compiler output for distributions/robust/arithmetic/reindexing/test_array_alias2]
[Error matching compiler output for distributions/robust/arithmetic/reindexing/test_strided_reindex2]
[Error matching compiler output for distributions/vass/testReplicatedVar2]

**Pull request closed without merging**
