### PR TITLE
Warn for formals that are generic but don't include `(?)`

### PR DESCRIPTION
**Pull request by mppf**
This Draft PR adds a warning for several of the following cases. 

``` chapel
record R { type t; }
proc a(arg: R) { }    // warning asking this to be written as 'arg: R(?)'
proc b(arg: R(?)) { } // OK
a(new R(int));
b(new R(int));

proc getGenericType() type {
  return R(?);
}
proc c(arg: getGenericType()) { }    // warning
proc d(arg: getGenericType()(?)) { } // OK
c(new R(int));
d(new R(int));
```

For https://github.com/Cray/chapel-private/issues/5229 / https://github.com/Cray/chapel-private/issues/4736#issuecomment-1666320252

This draft PR reflects changes to get test/release/examples/primers working but has not run through full comm=none testing yet.

Future Work:
 * warn for return types that are generic but don't include the `(?)`
 * address problems with `domain(?)` as a formal or return type
 * check if the warning is avoided for nested type queries / types with nested `?` OK

### CODE REVIEW

**Comment by bradcray** [comment]
For those interested, I'm taking a look of the impact of this PR on our test system.  Looks like 741 failures after taking care of mason, so a long, long tail to sort through.

**Comment by bradcray** [comment]
A few cases that have caught my eye so far:
* This does trigger for `D: domain`, which the OP suggested to me was still future work.  But maybe @mppf was thinking of future work beyond requiring `D: domain(?)` (?)
* I think this triggers for array formals of the form:  `A: [D]` (with no element type—not sure whether that's good/intentional, or whether we caught something we didn't mean to.  I haven't experimented with this yet
* It triggers for `_tuple`, which is perhaps appropriate given that this is an internal type and internal; but I could also imagine special-casing it in the warning since it's internal (so who cares other than us)

**Comment by bradcray** [comment]
My (temporary?) adoption of this branch lives here:  https://github.com/bradcray/chapel/tree/blc-warn-generic-formal

**Comment by bradcray** [comment]
Currently failing tests on my branch:

`owned class` and friends
--------------------------
* classes/delete-free/generic-classes-management.chpl
* classes/nilability/nilability-owned-and-borrowed.chpl
* library/packages/SortedSet/general/types/testNilableBorrowed.chpl

`this.type` and `something.type`
----------------------------------
* classes/ferguson/forwarding/d-thistype.chpl
* classes/initializers/initequals/generics.chpl
* classes/initializers/initequals/vector.chpl
* demo/review_060130/history_accumulator.chpl
* demo/review_060130/jacobi2.chpl
* deprecated/CyclicTest.chpl

false-positive for a fully instantiated generic w/ generic management type
(probably need to replicate my more complex logic in normalize.cpp to the FnSymbol.cpp checks)
--------------------------------------------------------------------------
* functions/ferguson/query/query-class-management-nilability-combinations.chpl
* functions/generic/arg-type-is-a-call.chpl
* release/examples/benchmarks/lcals/LCALSMain

??? warns about something already updated ??? (first few could be specific to interfaces, but third seems not?)
---------------------------------------------------------------------------------------------------------------
* constrained-generics/basic/generic/with-assoc-types-1.chpl
* constrained-generics/basic/generic/with-assoc-types-3.chpl
* functions/resolution/error-expected-param-missing2.chpl



TODO:
- [ ] out arguments are currently being skipped; can't support `(?)`
- [ ] `shared GenericClass`, `owned GenericClass` are not generating warnings as they should

**Comment by bradcray** [comment]
I've opened a draft PR for my branch:  https://github.com/chapel-lang/chapel/pull/23183 and will move subsequent comments and updates there (though I'm about to disappear for the weekend, so don't expect to do more with it until Tuesday if someone else wants to pick up the effort.

**Comment by mppf** [comment]
Closing in favor of #23291.

**Pull request closed without merging**
