### PR TITLE
Move all CommDiagnostics info into chpldocs and remove the technote.

### PR DESCRIPTION
**Pull request by gbtitus**
doc/release/technotes/README.comm-diagnostics contained some information
(notably example programs and output) not in the CommDiagnostics.chpl
chpldocing.  Move that into CommDiagnostics chpldocs, and delete the
technote.  While here, I also did some rephrasing in the first paragraph
of the module-level chpldoc entry.

In addition, I moved the start of the module-level chpldoc to the next
line below the comment opener, and reduced the indentation throughout
that entry by 1 space.  This seemed to resolve a problem I was having
with the first line of the documentation being taken as a synopsis,
though I was making other changes at the same time and I may be mistaken
in this.  In any case, this indentation change hides the content changes
I made.  To see those, you'll need a diff command with a -b option.

### CODE REVIEW

**Comment by ronawho** [comment]
Did you remove the reference to the technote that's in doc/release/README?

**Comment by ronawho** [comment]
Didn't do a very thorough review, but taking a quick look through the html output, it looks good to me.

**Comment by ronawho** [comment]
looks like there's also a reference to `README.comm-diagnostics` in `technotes/README.local
`

**Comment by gbtitus** [comment]
I'll remove the references to the technotes/README.comm-diagnostics file. Are we replacing these with anything? Some kind of ref to the chpldocs?

**Comment by gbtitus** [comment]
Maybe I should say something like "the chpldoc documentation for the CommDiagnostics standard module" in technotes/README.local.

**Comment by ronawho** [comment]
check out https://github.com/chapel-lang/chapel/commit/29c6860492da7b2591b3f8e5ce9e7021dd52d6b8

**Comment by ronawho** [comment]
I would say just remove the line in the main README, but add a link from README.local

**Comment by gbtitus** [comment]
Ah, thanks!

**Comment by ronawho** [comment]
I did notice that in other places (the spec, the CHANGES files) we use 'latest' instead of 'master'. I'm not sure who's right (if anyone.) I don't think you have to change anything, but might be something ask somebody more knowledgable than me.

**Pull request merged**
