### PR TITLE
Rename some .cpp files to avoid duplicate .cpp names

### PR DESCRIPTION
**Pull request by mppf**
PR #4880 created some .cpp files with duplicate names while moving code around to make the directory structure easier to reason about. However, these duplicate file names are annoying to deal with in some development setups. So, this PR renames the files in compiler/codegen/ with duplicate names to begin with `cg-`; e.g. now we will have `compiler/AST/stmt.cpp` and `compiler/codegen/cg-stmt.cpp`.

Reviewed by @bradcray - thanks!

- [x] full local testing

### CODE REVIEW

**Comment by bradcray** [comment]
These are the renamings I would've proposed, so I'm completely in favor of this change.  However, like all changes that'll affect other devs, I think there should be a "design" mail sent around letting people fight back against this if they prefer the current names.

**Comment by mstrout** [comment]
cg makes me think conjugate gradient.  I suggest gen- for the prefix in the codegen/ directory.

**Comment by mppf** [comment]
works for me

**Comment by bradcray** [comment]
I actually prefer `cg` (it's where my head intuitively went as well).  Specifically, we tend to refer to that pass of the compiler as "codegen", the directory is called "codegen" and "cg" is a natural abbreviation for it.  Honestly, before Michael filed this PR, if someone had asked me how I would eliminate the duplication I would've done the exact same thing.

**Comment by mstrout** [comment]
I don't see the conceptual overloads on CG as a blocking issue for using cg-* in this context.

**Review by bradcray — APPROVED** [review]

**Comment by bradcray** [comment]
@mppf: Did you receive any pushback on this, or did it just fall off the cart at some point?

**Comment by mppf** [comment]
@bradcray - I put it off while other more meaningful changes to these files were getting merged (since this PR is easier to redo, if necessary). I can get back to it now though.

**Pull request merged**
