### PR TITLE
Fixed vim syntax highlighting for domain literals

### PR DESCRIPTION
**Pull request by dtjong**
#11509 I'm not sure if this breaks any other highlighting, but it seemed to solve the issue for me.

### CODE REVIEW

**Comment by daviditen** [comment]
If I'm understanding what that line is for, it's meant to highlight curly braces inside of parenthesis as errors:

e.g. it marks the syntax error with the curly brace here in red, but that doesn't happen anymore after this change:
`writeln("Hello, } );`

It may be worth losing that error matching in order to un-break highlighting for domain literals and lambdas in these contexts, but it's not 100% a slam-dunk.

**Comment by ben-albrecht** [comment]
> It may be worth losing that error matching in order to un-break highlighting for domain literals and lambdas in these contexts, but it's not 100% a slam-dunk.

I agree. Upon merging this, I think we should open an issue to track the new syntax highlighting issue so that it can be revisited in the future.

**Comment by daviditen** [comment]
People on the team seem generally happy with this change even though it loses a little functionality, so I'm going to go ahead and merge it.  Thanks @dtjong!

**Comment by daviditen** [comment]
I opened issue #12831 about wanting to highlight errors with curly braces.

**Pull request merged**
