### PR TITLE
chplspell dictionary updates

### PR DESCRIPTION
**Pull request by cassella**
Update the chplspell dictionary files.

Also exclude compiler/next from chplspell  for now.  It's under heavy development, so contributing typo fixes is likely to just contribute unnecessary merge conflicts for the developers.

### CODE REVIEW

**Review by lydia-duncan — APPROVED** [review]
Looks good.  Would a reminder that chplspell is turned off for compiler/next be helpful for you, or are you just tracking it yourself somewhere?

**Comment by cassella** [comment]
I was just planning on remembering it.  :)

My long-term expectation is that as it becomes ready, everything in `compiler/next` will be promoted out of `next/`, and that that would be a reasonable time to start spell-checking it, and it'll just work.  Plus, such a move would invalidate the filenames that the per-file dictionaries use as their association with a particular file.

Though I guess I'm only assuming that the plan isn't to leave it in `compiler/next` as its permanent home.

FWIW, it can still be spellchecked manually with `chplspell compiler/next` -- explicitly naming a directory ignores its entry in the `$FILTEROUT` list.

**Comment by lydia-duncan** [comment]
I believe it'll live in compiler/next for a while after all the new nodes get added, but @mppf or @dlongnecke-cray would know better than I

**Comment by mppf** [comment]
I do expect we'll move it out of `compiler/next` eventually but when we do we'll be rearranging a lot of the other files in `compiler/`. And I expect we are probably going to have `compiler/next` for the next year or so.

**Comment by cassella** [comment]
> And I expect we are probably going to have `compiler/next` for the next year or so.

Will the code be used in the production compiler while it's in the next dir?  My motivation for spell checking is primarily to catch anything a user would see, e.g. an error message generated in the compiler or anything that ends up in documentation from code comments or docs themselves.  If `compiler/next` is being developed off to the side and won't actually be used by end users until it's moved out, I could just leave it alone until then.

**Comment by mppf** [comment]
I'd expect it not to be used in 1.25 (except when using an experimental flag) and that it some part of it will be used for all compiles in 1.26.

**Pull request merged**
