### PR TITLE
Limit filename length for proper functioning

### LINKED ISSUE #8758: Generate user-facing errors for long filenames
On PR #8733, @cassella writes:

> if I echo `'writeln("Hello");' > $(perl -e 'print "a"x250').chpl,`
> that file can't be compiled because the compiler
> `can't create /tmp/chpl-fortytwo-26146.deleteme/aaa...aaa.tmp.o: File name too long`
> .tmp.o is one byte longer than .chpl.

As I understand it, this points out that our current Makefiles don't ensure that they always use filenames <= the OS max filename length and could be a problem for users who prefer using truly long filenames.  On a rainy day, we could fix this.

[edit: In PR #12770, an initial attempt was made at this, but it seemed to be non-portable based on the back-end compiler used—and more specifically, the lengths of the intermediate filenames it created]

### PR DESCRIPTION
**Pull request by dgarvit**
Fixes #8758.

### CODE REVIEW

**Comment by dgarvit** [comment]
On running:
```
$ echo 'writeln("Hello");' > $(perl -e 'print "a"x250').chpl
$ chpl aaa<TAB>.chpl
```
image

**Comment by bradcray** [comment]
Hi @dgarvit: Thanks for tackling this.  Unfortunately, I'm still getting failures for long filenames:

```
$ echo 'writeln("Hello");' > $(perl -e 'print "a"x247').chpl
$ chpl aaa*.chpl
ld: can't open output file for writing '/var/folders/69/jbk0y4q95lq8xhhwpqgwf_rh000bxs/T//chpl-bradc-29161.deleteme/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tmp.ld_GNZitr', errno=63 for architecture x86_64
```

**Comment by dgarvit** [comment]
This is strange... The snippet you posted seems to be working well on my system.
image

**Comment by dgarvit** [comment]
Seems like the building procedure is not the same in the 2 scenarios mentioned in this thread. I am using the `setchplenv.bash` to build the chapel program, which happens to work well. Are you using a different environment?

**Comment by bradcray** [comment]
Interesting.  I think you must be correct that it depends on the back-end tools used.

My settings are:

```
$ printchplenv --all --anonymize
CHPL_HOST_PLATFORM: darwin
CHPL_HOST_COMPILER: clang
CHPL_HOST_ARCH: x86_64
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
CHPL_LIB_PIC: none
```

and the output when compiling with `--print-commands` is:

```
$ chpl aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.chpl --print-commands
clang    -fno-strict-overflow -I/Users/bradc/chapel/third-party/qthread/install/darwin-x86_64-native-clang-none-flat-jemalloc-hwloc/include -I/Users/bradc/chapel/third-party/hwloc/install/darwin-x86_64-native-clang-none-flat/include      -DCHPL_JEMALLOC_PREFIX=chpl_je_ -DCHPL_HAS_GMP -DCHPL_DO_UNWIND -I/Users/bradc/chapel/modules/standard -I/Users/bradc/chapel/modules/packages  -Wall -Werror -Wpointer-arith -Wwrite-strings -Wno-strict-aliasing -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wmissing-format-attribute -Wno-unused -Wno-uninitialized -Wno-pointer-sign -Wno-tautological-compare   -c -o /var/folders/69/jbk0y4q95lq8xhhwpqgwf_rh000bxs/T//chpl-bradc-35989.deleteme/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tmp.o -I/Users/bradc/chapel/third-party/qthread/install/darwin-x86_64-native-clang-none-flat-jemalloc-hwloc/include -I. -I/Users/bradc/chapel/runtime/include/localeModels/flat -I/Users/bradc/chapel/runtime/include/localeModels -I/Users/bradc/chapel/runtime/include/comm/none -I/Users/bradc/chapel/runtime/include/comm -I/Users/bradc/chapel/runtime/include/tasks/qthreads -I/Users/bradc/chapel/runtime/include/threads/none -I/Users/bradc/chapel/runtime/include -I/Users/bradc/chapel/runtime/include/qio -I/Users/bradc/chapel/runtime/include/atomics/cstdlib -I/Users/bradc/chapel/runtime/include/mem/jemalloc -I/Users/bradc/chapel/third-party/utf8-decoder -I/Users/bradc/chapel/runtime//../build/runtime/darwin/clang/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-system/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/include  -I/Users/bradc/chapel/third-party/jemalloc/install/darwin-x86_64-native-clang-none/include -I/Users/bradc/chapel/third-party/gmp/install/darwin-x86_64-native-clang-none/include -I/Users/bradc/chapel/third-party/hwloc/install/darwin-x86_64-native-clang-none-flat/include /var/folders/69/jbk0y4q95lq8xhhwpqgwf_rh000bxs/T//chpl-bradc-35989.deleteme/_main.c 
clang++  -L/Users/bradc/chapel/third-party/qthread/install/darwin-x86_64-native-clang-none-flat-jemalloc-hwloc/lib -Wl,-rpath,/Users/bradc/chapel/third-party/qthread/install/darwin-x86_64-native-clang-none-flat-jemalloc-hwloc/lib -L/Users/bradc/chapel/third-party/jemalloc/install/darwin-x86_64-native-clang-none/lib -Wl,-rpath,/Users/bradc/chapel/third-party/jemalloc/install/darwin-x86_64-native-clang-none/lib -L/Users/bradc/chapel/third-party/gmp/install/darwin-x86_64-native-clang-none/lib -Wl,-rpath,/Users/bradc/chapel/third-party/gmp/install/darwin-x86_64-native-clang-none/lib -L/Users/bradc/chapel/third-party/hwloc/install/darwin-x86_64-native-clang-none-flat/lib -Wl,-rpath,/Users/bradc/chapel/third-party/hwloc/install/darwin-x86_64-native-clang-none-flat/lib -L/Users/bradc/chapel/third-party/re2/install/darwin-x86_64-native-clang-none/lib -Wl,-rpath,/Users/bradc/chapel/third-party/re2/install/darwin-x86_64-native-clang-none/lib   -o /var/folders/69/jbk0y4q95lq8xhhwpqgwf_rh000bxs/T//chpl-bradc-35989.deleteme/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tmp -L/Users/bradc/chapel/lib/darwin/clang/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-system/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none /var/folders/69/jbk0y4q95lq8xhhwpqgwf_rh000bxs/T//chpl-bradc-35989.deleteme/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tmp.o  /Users/bradc/chapel/lib/darwin/clang/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-system/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/main.o  -lchpl  -lm -lgmp -ljemalloc -lchpl -lqthread -L/Users/bradc/chapel/third-party/hwloc/install/darwin-x86_64-native-clang-none-flat/lib -lhwloc -lm -lre2 -lpthread 
ld: can't open output file for writing '/var/folders/69/jbk0y4q95lq8xhhwpqgwf_rh000bxs/T//chpl-bradc-35989.deleteme/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tmp.ld_6kNUWi', errno=63 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/var/folders/69/jbk0y4q95lq8xhhwpqgwf_rh000bxs/T//chpl-bradc-35989.deleteme/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tmp] Error 1
error: compiling generated source
```

**Comment by daviditen** [comment]
It would be nice to move this error earlier in the compile cycle.  We know the file names as early as parsing, so why wait until codegen to error out?  I think the error should be moved up to before the file is parsed.  On a long compile this could save a lot of frustration.

**Comment by dgarvit** [comment]
@bradcray so what we basically need to know is the maximum length of the extension possible.

**Comment by bradcray** [comment]
I don't have any insight into how to make this airtight short of doing some Google research (e.g., "what is the longest extension a compiler / linker may want to add to my filename?").  I also don't think there's great harm in being slightly conservative in filename length (i.e., I don't think it'll be the case that people frequently want to have filenames longer than 40 characters).  That said, the closer we could get to the actual limit, the better.

**Comment by bradcray** [comment]
I'm going to close this PR since it didn't work for me and hasn't continued to receive attention.  Would be happy to see someone pick it up and run with it more, but I also don't think it's holding anything important up.

**Pull request closed without merging**
