### PR TITLE
Repair dangling file references

### PR DESCRIPTION
**Pull request by cassella**
Update assorted files that were referring to old or incorrect file paths.

### CODE REVIEW

**Comment by cassella** [comment]
Requesting reviews from:

- [ ] @bradcray test/domains/bradc/domainEquality.future
- [ ] @dlongnecke-cray doc/rst/meta/compiler-internals-doxygen/base.rst
- [ ] @dlongnecke-cray modules/internal/DefaultRectangular.chpl
- [ ] @lydia-duncan test/classes/initializers/compilerGenerated/fieldDefinedGlobalArray{,Modified}.chpl
- [ ] @lydia-duncan compiler/resolution/resolveFunction.cpp as the mover of SSCA2
- [ ] @mppf test/classes/figueroa/BogusDestructors.chpl (as remover of the referenced other test)
- [ ] @mstrout or @bmcdonald3 doc/rst/developer/bestPractices/buildingdocs.rst
- [ ] @rapiz1 or @e-kayrakli modules/packages/SortedMap.chpl
- [ ] @ronawho util/devel/check_paths since you previously had input on it
- [ ] @ShreyasKhandekar test/io/readLine/readLine.chpl
- [ ] @vasslitvinov four test files with /vass/ in path
- [ ] @vasslitvinov test/classes/delete-free-lifetimes/tuple-vararg-in-lt-clause.chpl

**Comment by lydia-duncan** [comment]
I also grabbed the SortedMap and readLine changes, since Engin is out and Yujia/Shreyas might not see the pings (and don't have merge permissions)

**Review by dlongnecke-cray — APPROVED** [review]
My changes look good, thanks Paul!

**Comment by cassella** [comment]
All the changes have been approved.  Does anyone want to merge it?

**Pull request merged**
