### PR TITLE
Change language_level to default

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Fixes https://github.com/chapel-lang/chapel/issues/11587.

@lydia-duncan please review.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
What versions of Cython have the new default value?

**Comment by Aniket21mathur** [comment]
> What versions of Cython have the new default value?

Based on [this](https://stackoverflow.com/questions/57415446/what-are-differences-between-cythons-language-level-3-and-3str) query of StackOverflow, Cython 3.0 will include the `3str` language_level as default, and according to [PyPI](https://pypi.org/project/Cython/) the latest version of Cython is `0.29.14`. 

So I think we should wait till `3.0` is released.

But currently, we have the `language_level` is set to `3` should we change it to `3str`?

Thanks!

**Comment by lydia-duncan** [comment]
That doesn't seem necessary.  We've always been using Python3 for our Cython builds and the language_level 3 setting has been working, it sounds like the 3str default is for codes that were originally written for Python2.  So we should still wait until Cython 3 comes out

**Comment by Aniket21mathur** [comment]
> That doesn't seem necessary. We've always been using Python3 for our Cython builds and the language_level 3 setting has been working, it sounds like the 3str default is for codes that were originally written for Python2. So we should still wait until Cython 3 comes out

Agreed. Let's wait for Cython 3 :smile: .

Should we keep this pull request open or close it?

**Comment by lydia-duncan** [comment]
I'm going to close this for now, but we can reopen, rebase and merge if you're still active by the time Cython 3 comes around :)

**Pull request closed without merging**
