### PR TITLE
Recursive iterator futures for #18218 and #18236

### PR DESCRIPTION
**Pull request by cassella**
Add futures for two recursive iterator issues:

#18236: compiler segfault on suspect recursive iterator
#18218, internal error, loop over findfiles() calls throwing function

For the second, I was unable to reproduce this error writing my own
recursive iterator in place of findfiles().

I was concerned that a change to these iterators in the FileSystem
module might inadvertantly change the behavior of this test.  So I
added snapshots of findfiles and walkdirs() to the test for it to
call.

### CODE REVIEW

**Comment by cassella** [comment]
The `test/functions/iterators/recursive` directory passes with `--futures`.

**Comment by ronawho** [comment]
`--futures` testing looks good to me. Seems a bit unfortunate to add a copy of the module, but it doesn't bother me personally. @bradcray I think you originally wrote findFiles -- you ok with the module cloning?

**Comment by bradcray** [comment]
Rather than cloning the whole module, could we just clone findFiles and the couple of helpers it relies upon?

**Comment by cassella** [comment]
When I tried that, the internal error went away.

I'm trying again putting the whole cloned FileSystem module into the test, and trimming away.  It seems to be going better.

**Comment by bradcray** [comment]
Ah sorry, I just saw a mail where I think you were saying that, but I didn't connect it to this PR.  I don't know that it's worth a lot of time to whittle it down if it's challenging, so feel free to stop when it becomes non-trivial.

**Comment by cassella** [comment]
It "just worked" this time, even though I'm pretty sure this is what I had tried the first time.

I force pushed to avoid putting that extra copy of FileSystem into the history.

**Comment by ronawho** [comment]
Hmm, do you remember what behavior you saw before when it didn't "just work" -- any chance the compiler behavior is non-deterministic and failures are sporadic?

**Comment by cassella** [comment]
The first time I tried dropping copies of just these two iterators into the test program, the test program compiled and ran successfully.  I've run it as of this commit a few dozen times and it hit the error every time.  I assume I just did something wrong that first time and went right for the big hammer.

**Comment by ronawho** [comment]
Looks good to me and also failed as expected reliability for me for a couple of runs.

**Comment by ronawho** [comment]
inadvertantly -> inadvertently in the PR description? (Might be the first and only time I'll ever catch a Paul spelling mistake :) )

**Comment by bradcray** [comment]
> Might be the first and only time I'll ever catch a Paul spelling mistake

I recently edited one of Paul's OP's to fix a spelling mistake.  Apparently, take his scripts away, and he's just a mortal like the rest of us!

**Pull request merged**
