### PR TITLE
Close an EndCount leak in throwing foralls

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR closes a leak with foralls whose body throw error(s).

Resolves https://github.com/chapel-lang/chapel/issues/12511

@mppf summarized the problem under that issue:

> We had defer blocks for the EndCount to make sure it is deleted. But these are
> processed (and changed to delete calls at the end of a block) in
> callDestructors. Then, lowerIterators lowers the ForallStmt into a more
> complex structure and no longer calls the delete if the body of the forall
> threw an error. I believe that this is only a problem now that ForallStmts get
> lowered later.

With this PR, `lowerIterators` now finds any `endCountFree` calls that show up
between the error's goto and the associated label, and creates a copy of that
`endCountFree` right before the goto.

#### Test Status

- [x] asan --memLeaks `errhandling/forall`
- [x] quickstart asan
- [x] standard
- [x] gasnet

### CODE REVIEW

**Comment by e-kayrakli** [comment]
@mppf and/or @vasslitvinov -- I wonder what you think about this one. Is it too specific? It may be a bit too workaround-y but the implementation is clean and minimal, IMO.

**Review by vasslitvinov — APPROVED** [review]
Sounds good to me.

Do we need a designated test that would leak without this fix?

I did not follow all the logic, however if the testing passes, that's fine. My only concern is ensuring that there will be just one _endCountFree call. Maybe if there are multiple, instead of failing an assert, silently do nothing with the subsequent ones?

**Comment by e-kayrakli** [comment]
> Do we need a designated test that would leak without this fix?

One of the tests that leaked before this is pretty characteristic, in that, it tests whether you can throw from a forall body. I can write an even simpler version, but I think it captures the nature of the leak:
https://github.com/chapel-lang/chapel/blob/master/test/errhandling/parallel/forall-throws.chpl#L42

>Maybe if there are multiple, instead of failing an assert, silently do nothing with the subsequent ones?

I *think* there can't be multiple. But I see your point. If I am wrong, we can trigger an assertion for a user. And I guess it is better if their (unexpected?) code leaks then fails. I'll change that.

**Comment by mppf** [comment]
> I think there can't be multiple. But I see your point. If I am wrong, we can trigger an assertion for a user. And I guess it is better if their (unexpected?) code leaks then fails. I'll change that.

I don't think it's a big deal but I'd rather have it fail to compile than leak.

**Comment by e-kayrakli** [comment]
I was thinking of a scenario where someone has code generating multiple endCountFrees (somehow??), and then getting Chapel 1.24 to only have their previously working code fail.

I am being cautious because I don't think I understand this part too well to say that having two `endCountFree`s between those two locations can never happen with valid user code. If I could say that, I'd be more in favor of assertion.

**Comment by mppf** [comment]
Should we make it warn+leak in that event, then?

**Comment by e-kayrakli** [comment]
That's interesting. I'll do that.

**Comment by vasslitvinov** [comment]
> make it warn+leak in that event

Sounds good, thanks Engin.

**Comment by e-kayrakli** [comment]
passed another standard test with futures. merging.

**Pull request merged**
