### PR TITLE
Fix string / int comparison in computePerfStats

### PR DESCRIPTION
**Pull request by bradcray**
[all real work done by @ronawho; I just did the typing and testing]

This fixes a Python2->3 incompatibility in `computePerfStats` which makes running performance tests using Python 3 work better.

Note for posterity: There is still a remaining issue that makes mandelbrot shootout tests fail under Python 3 due to reading arbitrary bytes as a string, some of which aren't legal UTF-8.  I believe that this should be changed to read raw bytes, but don't know how to do that.

### CODE REVIEW

**Comment by bradcray** [comment]
Would someone on @chapel-lang/perf-team who's Python-savvy check to see whether this makes sense (and whether it's surprising that nobody else has seemingly had this problem?)

**Comment by ronawho** [comment]
I believe @mppf ran into this a week or 2 ago and he mentioned that this type of fix messed up other programs. I told him I would look into it, but have not gotten around to it. 

(this is a python3 incompatibility btw)

**Comment by bradcray** [comment]
Huh, OK... "Messed up other programs" in the sense of "If I ran performance testing, I'd see some failures due to this change?"

**Comment by ronawho** [comment]
Yeah, other perf tests were failing. If I had to guess, I would suspect benchmarks that do negative searches such as fasta.

**Comment by bradcray** [comment]
I'll do some more testing.

**Comment by ronawho** [comment]
FYI -- https://stackoverflow.com/questions/2384078/why-is-0-true-in-python-2

I suspect this is just a latent bug exposed by the python3 incompatibility. Without looking too carefully I would guess this should just be `num_real = int(num) - 1` -- always subtract 1 from the index, not just when it's a positive value (which is what we were getting before since `num >= 1` was always true in py2)

**Comment by bradcray** [comment]
Do you know whether @mppf's failures were with Python 2 or Python 3?

**Comment by ronawho** [comment]
Python 3 (he was trying to resolve the same python3 incompatibly)

**Comment by mppf** [comment]
@bradcray - I was running into failures with performance testing in the shootout directory with my fix, so if that's working for you, you got further than me.

**Comment by bradcray** [comment]
If I run this with `start_test -performance` on my Mac using Python 3, the only failures I get are also present on master, and I think reflect a Python 2 vs. 3 / UTF-8 strings vs. bytes incompatibility.

```
Traceback (most recent call last):
  File "/Users/bradc/chapel/util/test/computePerfStats", line 306, in <module>
    main()
  File "/Users/bradc/chapel/util/test/computePerfStats", line 32, in main
    valid_output = validate_output(verify_keys, args.test_output_file)
  File "/Users/bradc/chapel/util/test/computePerfStats", line 92, in validate_output
    test_output_raw = file.read()
  File "/Users/bradc/chapel/third-party/chpl-venv/install/darwin-x86_64/py3.6/chpl-virtualenv/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1515: invalid start byte
```

Since these are independent of the fix of this PR, I'm not going to worry about them for now unless someone speaks up before I merge.  Meanwhile, I'm testing `start_test -performance` on linux (using Python 2 I think) to make sure things also look clean there.

**Comment by bradcray** [comment]
This seems to be working on linux, so I'm going to merge once the existing perf tests quiet down a bit, to not get tangled up into the diagnosis there.

**Pull request merged**
