### PR TITLE
Adjustments for comm=ofi full testing

### LINKED ISSUE #11942: spike: diagnose and fix comm=ofi testing failures
A preliminary full testing run with comm=ofi and the makeshift `mpirun4ofi` launcher on our chapcs cluster covered the first 292 of our test suites before the slurm job allocation it was running in timed out.  It produced 2444 passes and 26 failures.  Separately, a run of the `multilocale` suite produced 144 passes and 15 failures.

A run of the `multilocale` suite with comm=ofi on a Cray XC system produces 15-20 failures depending on circumstances (provider gni vs. sockets, which tasking layer, etc.).

In this spike I will diagnose and fix as many of these failures as I can, and also extend the full testing coverage to more suites.

### PR DESCRIPTION
**Pull request by gbtitus**
This makes adjustments so that a number of tests that failed in initial
comm=ofi testing now pass.  As a beneficial side effect, many of these
same tests now also pass with comm=ugni.

For much of testing history, comm==gasnet or !=gasnet has served as a
proxy for distinguishing between multi-locale and single-locale testing,
because although we also had comm=ugni, that came along much later and
we never have done very extensive nightly testing on it.  With the
advent of the ofi comm layer, however, it's now preferable that we
distinguish between single- and multi-locale testing via comm==none vs
comm!=none.  This changes 6 tests:

    test/optimizations/sungeun/RADOpt/access1d
    test/optimizations/sungeun/RADOpt/access2d
    test/optimizations/sungeun/RADOpt/access3d
    test/types/records/sungeun/ctorWithOnFn
    test/types/string/StringImpl/memLeaks/assign
    test/types/string/StringImpl/memLeaks/coforall

Testing with comm=ofi produced a number of differences in comm diags
which, in the end, had to do with network atomics support in the comm
layers.  The existing .good files matched the output for comm=gasnet but
not comm=ofi.  It turned out that the mismatches were from executeOnFast
operations used by comm=gasnet, where comm=ofi used network AMOs.  It
also turned out, happily, that comm=ugni produced the same output as
comm=ofi.  This pointed out the solution, which distinguishes between
the .good output for networkAtomics==none and networkAtomics!=none.
This changes 23 tests:

    test/distributions/bharshbarg/promotedComms
    test/distributions/robust/arithmetic/performance/multilocale/alloc
    test/distributions/robust/arithmetic/performance/multilocale/alloc_all
    test/distributions/robust/arithmetic/performance/multilocale/assign
    test/distributions/robust/arithmetic/performance/multilocale/assignAlias
    test/distributions/robust/arithmetic/performance/multilocale/assignReindex
    test/distributions/robust/arithmetic/performance/multilocale/assignSlice
    test/distributions/robust/arithmetic/performance/multilocale/reduce
    test/distributions/robust/arithmetic/performance/multilocale/reduceAlias
    test/distributions/robust/arithmetic/performance/multilocale/reduceSlice
    test/multilocale/deitz/needMultiLocales/dist/test_private_space
    test/multilocale/deitz/needMultiLocales/raCommCheck
    test/multilocale/deitz/needMultiLocales/raCommCheckLCG
    test/multilocale/deitz/needMultiLocales/streamCommCheck
    test/optimizations/remoteValueForwarding/serialization/domains
    test/parallel/taskPar/sungeun/barrier/commDiags
    test/performance/sungeun/multilocale/atomics
    test/performance/sungeun/multilocale/syncsingle
    test/studies/hpcc/CommDiags/ra_commDiags
    test/studies/hpcc/CommDiags/stream-ep_commDiags
    test/studies/hpcc/CommDiags/stream_commDiags
    test/types/type_variables/ferguson/ispod
    test/users/vass/isX/isX.byBlankArgs-compWarns

In support of the above, the testing system now has to be able to
compare to networkAtomics-specific .good files.  This changes these
scripts:

    util/start_test
    util/test/sub_test
    test/distributions/robust/arithmetic/PREDIFF

Two tests that create their own expected output for comm diags have to
adjust that based on whether or not we have network atomics:

    test/performance/ferguson/array-assign-block
    test/performance/ferguson/cyclic-id-queries

These two tests needed support for the mpirun4ofi launcher and the ofi
comm layer in their 'verbose' output:

    test/multilocale/numLocales/bradc/testVFlag
    test/multilocale/numLocales/bradc/testVerboseFlag

A test that checked for dead code elimination of unused modules needed
to check for the NetworkAtomics module not being remove, for comm layers
which cause it to be used:

    test/optimizations/deadCodeElimination/elliot/countDeadModules.comm-ofi

One test's output is supposed to match that of the printchplenv utility.
That only prints the substrate when comm=gasnet, so the test needed to
do the same:

    test/chplenv/printchplenv/printchplenv

We were skipping the minimal-modules test directory for comm=gasnet, but
it's actually comm!=none that breaks with minimal modules.  Update the
SKIPIF:

    test/compflags/bradc/minimalModules/SKIPIF

On linux64 platforms the static_dynamic linking test produces linker
errors for its static modes when libmpi is needed, because that is only
available as a shared object.  Skip it in those configurations.

    test/compflags/link/sungeun/static_dynamic

This resolves #11942.

### CODE REVIEW

**Comment by gbtitus** [comment]
This will be easiest to review commit-by-commit, by far.

**Comment by gbtitus** [comment]
> The only part that's a little confusing to me is that it looks like there's a commit that duplicates #12008. ...

Yes, I cherry-picked that one into the branch for this PR in order to use it during (re)testing.  I'll rebase to get rid of it.

**Comment by gbtitus** [comment]
I'm getting pretty close to ready to merge this.  @bradcray, did you want to take a look?

**Comment by bradcray** [comment]
Sorry to have been seemingly unresponsive to this.

**Pull request merged**
