### PR TITLE
Update to libfabric 1.12.1

### PR DESCRIPTION
**Pull request by jhh67**
Update the bundled libfabric to 1.12.1. This version causes a problem on chapcs because it will choose `verbs;ofi_rxm` as the provider which will fail for some reason. This pull request includes a change to `getBaseProviderHints` to determine whether or not the node is oversubscribed in addition to checking the `CHPL_RT_OVERSUBSCRIBED` environment variable.  If the node is oversubscribed then `FI_MR_ALLOCATED` is not set the hints and `verbs` is not chosen as the provider. Also, on my  mac this version sometimes chooses the touchbar as the NIC, which doesn't work. The workaround is to set `FI_TCP_IFACE` to a valid interface.

### CODE REVIEW

**Comment by ronawho** [comment]
> his pull request includes a change to getBaseProviderHints to determine whether or not the node is oversubscribed in addition to checking the CHPL_RT_OVERSUBSCRIBED environment variable. If the node is oversubscribed then FI_MR_ALLOCATED is not set the hints and verbs is not chosen as the provider.

Currently we expect to run a process per node when not oversubscribed, but we have discussed a mode where we'd run with a process per numa domain, so I'm not sure if we should assume oversubscription if there's more than 1 locale per node. I'm also wondering it makes sense to not set FI_MR_ALLOCATED when oversubscribed. I thought we now limited how much heap is used per locale when running oversubscribed, so shouldn't that allow us to still use FI_MR_ALLOCATED?

**Comment by ronawho** [comment]
Forgot that I wanted to cc @gbtitus on the last comment

**Comment by gbtitus** [comment]
I believe we're not throwing `FI_MR_ALLOCATED` into the hints when oversubscribed not because of any memory over-allocation issues, which as you say were dealt with separately. Rather, at least on our chapcs cluster when we put that in the hints and thereby select the 'verbs;ofi_rxm' provider, we get an error from libfabric that (based on `FI_LOG_LEVEL=warn` output) seems to have something to do with multiple processes trying to open the IB interface. So we're just not putting it in there as a stopgap, to prevent selecting the verbs provider. @jhh67 can you confirm that, and if so would you add a comment to that effect at that spot in comm-ofi.c? And also create an issue to figure out what's going on.

I agree we should be able to throw `FI_MR_ALLOCATED` on chapcs, but it seemed more important to get the upgrade done and tackle that separately afterward, especially since with our current libfabric 1.10.1 we've never been able to select the verbs provider no matter what we did.

**Review by ronawho — APPROVED** [review]

**Comment by gbtitus** [comment]
@ronawho I think even if we were to decide to run a process per NUMA node on purpose I'd still call that "oversubscribed" to as a way of saying that we want each process to limit its use of system resources to an appropriate share of its node. But that is different from our current sense of that word and I think we want to be able to continue to use the old sense for situations where we're running potentially lots of processes per node as a way to do multilocale testing on single-node systems. So we might need to come up with two distinct terms and go through the stack with a fine-toothed comb to decide which meaning of "oversubscribed" is intended in each place we use it.

**Comment by jhh67** [comment]
I'll add the comment and merge the PR, but note that the previous logic didn't put FI_MR_ALLOCATED in the hints if  CHPL_RT_OVERSUBSCRIBED was set. Based the comments by @ronawho it isn't clear why that was done so the overall logic of when FI_MR_ALLOCATED should be put in the hints should be revisited. Also from this discussion it seems like there should be two flavors of oversubscribed as @gbtitus notes.

**Comment by gbtitus** [comment]
Yeah, I think we're now in a situation where if `CHPL_RT_OVERSUBSCRIBED` is actually set (one kind of over-subscription) then we still probably don't want a fixed heap, whereas if we're just running with more than one locale per node but the env var isn't set (another kind) then we do want one. But for the moment we're still not doing even that, as an indirect way to avoid the IB address-related error that we get on chapcs.

**Pull request merged**
