### PR TITLE
Bugfix : CHPL_COMM_WORLD should be set even if numLocales==1

### PR DESCRIPTION
**Pull request by npadmana**
We were previously only setting CHPL_COMM_WORLD if the number of locales > 1, which would cause the program to crash if the user attempted to use it when the number of locales==1.

This bugfix now sets CHPL_COMM_WORLD to MPI_COMM_WORLD when numLocales==1, which is (happily) the desired behavior even when running single-locale Chapel + MPI.

@mppf -- could you review this? Thanks!

### CODE REVIEW

**Comment by mppf** [comment]
Hi @npadmana - looks good. Could you make a note in the PR message about what testing you've done? Other than that I think it's ready to merge.

**Comment by npadmana** [comment]
Added in an explicit test directory for this.

It's currently marked as NOTEST, but you can run the test with `bash testit.sh`. This exercises the cases I can think of (single-locale + multi-locale).

**Comment by mppf** [comment]
I was asking you to mention what configurations you've been able to run the adjusted MPI module with.

**Comment by npadmana** [comment]
Tested using CHPL_TARGET_COMPILER=mpi-gnu and MPICH in all cases; tests run with --

1. single-locale Chapel + MPI
   -- CHPL_COMM=none 

2. multi-locale Chapel + MPI
   -- CHPL_COMM=gasnet
       CHPL_COMM_SUBSTRATE=mpi
       CHPL_TASKS=fifo

Both cases are run with 1 & 4 ranks/locales.

The `testit.sh` script explicitly sets these (so documented there as well).

**Pull request merged**
