### PR TITLE
Minor adjustments to canParamCoerce

### PR DESCRIPTION
**Pull request by mppf**
This PR addresses two minor issues with canParamCoerce in the production compiler that I noticed while porting it over to compiler/next in #18660.

* Adds missing imag(32)->imag(64) implicit conversion. The spec clearly indicates that this conversion should be present but to date it only works for params. See also https://chapel-lang.org/docs/language/spec/conversions.html#implicit-numeric-and-bool-conversions

* Consider param string conversion to be a narrowing conversion. When working with a param string, the compiler can implicitly convert it in to c_string; and likewise for a param c_string into string. Since this relies on the actual argument being a param (i.e. it does not allow converting `var x:string` into a `c_string` implicitly), count it as a narrowing conversion. I expect this to become irrelevant when we deprecate `c_string`.

Reviewed by @e-kayrakli - thanks!

- [x] full local testing

### CODE REVIEW

**Comment by e-kayrakli** [comment]
What exactly is a "narrowing conversion"?

**Comment by mppf** [comment]
For example, we can implicitly convert `1` into `int(8)` even though `1` has type `int` and `int` can't normally implicitly convert into `int(8)`. We can convert `1` though because we know it fits. This is discussed in this part of the spec -- https://chapel-lang.org/docs/language/spec/conversions.html#implicit-compile-time-constant-conversions . The "param narrowing" conversions matter for choosing the best overload of a function as described here -- https://chapel-lang.org/docs/language/spec/procedures.html#determining-more-specific-functions .

**Review by e-kayrakli — APPROVED** [review]
I think the PR is good.

I am still a bit confused about the param conversion from c_string to string. Does that mean we already have been allowing the following?

```chapel
proc foo(param s: string) {

}

foo(c"\xff");  // non-UTF-8 data

**Comment by mppf** [comment]
@e-kayrakli - I see this

``` chapel
proc foo(in s: string) { }
foo(c"\xff");  // non-UTF-8 data
```

```
error: halt reached - Casting a non-UTF-8 c_string to string
```

``` chapel
proc foo(in s: string) {
  writeln(s);
}

param cstr = c"\xff";
param str = cstr:string;
foo(str);
```

```
error: Invalid string literal
```

So I don't think this causes UTF-8 validation issues today. (That said, I don't think it would be a big deal to allow only param string -> c_string conversions, since that's probably the common case here).

**Pull request merged**
