### PR TITLE
Updating the GSL demonstration....

### PR DESCRIPTION
**Pull request by npadmana**
This is an updated version of the GSL demonstration test, cleaned up significantly to use the new function pointer functionality (thanks!). 

The code can be compiled by hand (you need to have GSL installed), and correctly matches the .good file. However, there is a mismatch in pointer types that throws a GCC warning that gets promoted to an error, causing the test to fail.

### CODE REVIEW

**Comment by bradcray** [comment]
@mppf : Just tagging you on this so that you're aware of it -- you got dropped from the Cc:s on the email thread at some point...

**Comment by npadmana** [comment]
@bradcray, @mppf -- in case you don't want to wade into the GSL headers, I just added a simple standalone test that "fails" in the same way (i.e. fails when run with start_test, but the code is fine).

**Comment by mppf** [comment]
Hi @npadmana, I'd be comfortable merging this if you:
 * move  funcPtrType.chpl  to a different directory (since we don't want to have a SKIPIF skipping it if GSL is not present)
 * add a .future file for the new funcPtrType.chpl test

Thanks!

As for the funcPtrType bug itself, I could try to get the compiler to add casts in this case, but I think I'd rather just get c_fn_ptr to include more information about the types of arguments and return type.

**Comment by bradcray** [comment]
Hi NIkhil -- Thanks for providing this, and particularly the boiled down, non-GSL version.  I expanded upon it somewhat and was able to get it to compile and run properly with the flags:

--ccflags -Wno-incompatible-pointer-types --ccflags -Wno-error

This tells the C compiler not to complain about these pointer types ("it's a white lie") and to not turn warnings into errors.  Can you let me know whether this will work for you as a short-term workaround?

Long term, I think that in order to deal with this, we need to expand the compiler's ability to reason about an external function having specific argument types and a return type, but that's not something I'm personally going to get to very quickly (though it does arguably fit within this release's theme of improving support for first-class functions).  So I'm hoping that the current support with the ability to squash warnings might work for you for the time being.  Give a shout if not.

**Comment by bradcray** [comment]
(I should note that the workaround above is gnu-specific and that the flags are likely to have to change for other compilers).

**Comment by npadmana** [comment]
@mppf, @bradcray -- I've split out the funcPtrType test into its own future. 

The failing GSL test currently doesn't bother me (and I don't think it'll cause problems for your testing suite, since it has a SKIPIF). If you'd prefer, I'll make this a NOTEST....

**Pull request merged**
