### PR TITLE
Test cases showing + reduce on associative domain

### PR DESCRIPTION
**Pull request by mppf**
It seems to be an interesting usage pattern.

Discussed with @vasslitvinov.

### CODE REVIEW

**Comment by mppf** [comment]
@vasslitvinov - I'm wondering what you think about these - if you think they are reasonable programs using reductions - and if you think they could achieve OK performance.

**Comment by vasslitvinov** [comment]
Both codes are reasonable from user standpoint.

The one with + reduce intent is probably not how the user would write that particular program, however it should work i.e. it is a bug if it doesn't, and it can be a legitimate part of a more complicated program.

**Comment by mppf** [comment]
How would you expect a user to write that program?

**Comment by mppf** [comment]
(I mean a program that is computing a set in parallel)

**Comment by vasslitvinov** [comment]
Hm I see now. For now, yes your code is the way to go. Ideally at least one of the following should work:

D = [i in ...] .....

and

forall .... do D += ....;

**Comment by mppf** [comment]
I don't know how to make the D = [i in ] version work because the RHS isn't de-duplicated yet.
Re forall ... do D += ... , that version will take/release a lock on every iteration (vs once for each task).

**Comment by vasslitvinov** [comment]
Right, neither is acceptable now. My suggestions are in the "ideally" category.

**Pull request merged**
