### PR TITLE
Add test for try { return; } in a loop

### PR DESCRIPTION
**Pull request by cassella**
This is the test in #13739, which seems to have been fixed by #14814

### CODE REVIEW

**Comment by cassella** [comment]
FYI @mppf maybe?

I added this test to the one in `test/types/records/split-init` even though it contains no records, because: 1. This is the test modified by the PR that fixed the bug, and 2. I couldn't quickly find a split-init test outside `test/types/records`.  I can put it somewhere else if there's somewhere that would be better.

**Comment by bradcray** [comment]
I'm looking at this for the first time today while housecleaning.  I don't have an issue with adding this case here if @mppf doesn't, but it seems like more of a general error-handling test (due to the `try` block) than anything to do with split init to me...  I guess the argument is that if the cause of the bug was due to split init, maybe it belongs here (?).   Otherwise, I might put it somewhere under `test/errhandling` (maybe under `codePathCoverage`?)

**Comment by mppf** [comment]
This is fine with me - it might be reasonable to put the test in test/errhandling but it is also OK where it is because it is a sort of degenerate case.

**Comment by cassella** [comment]
Two votes for "eh"?

**Comment by mppf** [comment]
If you are looking for concrete guidance - put this in test/errhandling/misc/issue-13739.chpl since there is not any split-init in the test itself.

**Comment by cassella** [comment]
I moved the test.  I replaced the first commit with this one as the original commit didn't add anything useful to the history.

**Pull request merged**
