### PR TITLE
Add a developer `-j` `--parallel-make` flag to enable `make -j` for C back-end

### PR DESCRIPTION
**Pull request by bradcray**
This adds support for a developer flag for the C back-end:
'--parallel-make [val]' / '-j [val]' flag that causes 'make -j'
to be used when building the back-end C code.  Its values
are as follows:

* <= 0 indicates it is disabled
* \> 0 indicates to use `make -j <val>`

Throwing this flag enables `--incremental` by default
since we don't have much opportunity for parallelism
in the make step without throwing that flag.

At first, I made it so that it would be turned on by default
when not doing a `--fast` compile, but this turned out
to hurt performance for small programs like hello.chpl.
When it was turned on by default, I also had its value
default to numCores, but I removed this capability because
(a) we don't have the ability to have this flag take no
integer value currently, and I didn't want to lean on a sentinel
value like a negative number for this, and (b) it required
putting in a C++ query for the number of hardware cores
that I was worried might cause portability issues that I
didn't want to wrestle with this close to the feature freeze.
See the commits that make up this PR for that feature if
we want to return to it in the future.

It seems to me that the main way to reduce overheads to
turn it on by default would be to focus on #19418.

- [x] update bash completion test

### CODE REVIEW

**Comment by bradcray** [comment]
@e-kayrakli : For your consideration.  Once nightly testing is drained, I will be curious to compare the execution time of a paratest.chapcs with the C back-end on `main` vs. this vs. this + #19407

**Review by e-kayrakli — APPROVED** [review]
One thing that I don't know nor can figure out quickly: does existence of an `"I"` argument make it default to 0 without any arguments? I think so, inferring from your OP, but can't be sure. In other words, `chpl --parallel-make` ends up calling `make -j` without throwing in a `0` explicitly, right?

I think this is good. I am not too picky about the name as I don't think this will be used too much right off the bat, but I would prefer avoiding `make`. Some alternatives that I prefer over `--parallel-make`:

- `--parallel[ize]-backend`
- `--parallel[ize]-backend-compilation`
- `--parallel-compile`
- `--parallelize-compilation`

While dropping the `backend` implies that `chpl` itself is parallel, I am OK with it if want brevity. I don't think any of these are too long either, and there's always `-j`.

I feel like `make` in the name unnecessarily exposes the underlying technology. Not that we are hiding it...

**Comment by bradcray** [comment]
> One thing that I don't know nor can figure out quickly: does existence of an "I" argument make it default to 0 without any arguments? I think so, inferring from your OP, but can't be sure. In other words, chpl --parallel-make ends up calling make -j without throwing in a 0 explicitly, right?

That's the behavior, but it's not because of what the -I flag does, but rather due to:

https://github.com/chapel-lang/chapel/pull/19409/files#diff-ffe5ebc2db819ba98925774825649904b144fd964e3710504bcce6ac4d1a205bR1562-R1564

**Comment by e-kayrakli** [comment]
Ah, yeah, duh. Thanks!

**Comment by bradcray** [comment]
@e-kayrakli : How negatively do you feel about `--parallel-make` given that it's a developer flag.  Of your alternatives, I tend to like `parallelize-backend` best, but would just as soon not make a change given that it's not officially user-facing and probably won't be used by many (and the cool among us will use `-j` anyway :D ).

**Comment by bradcray** [comment]
(I asked the team about this PR and the name in a design email I just sent out).

**Comment by stonea** [comment]
Re: naming the flag to something like `--parallelize-backend`

To be pedantic I'd argue that "backend" isn't just the final build by our target compiler but also the final code generation pass(es) that lower to LLVM\C (and we're not parallelizing those passes).

**Comment by bradcray** [comment]
@e-kayrakli : Belatedly, wanted to let you know that I've significantly simplified the implementation and updated the OP to reflect the current state and evolution a bit, based on the perf meeting discussion and the hello.chpl timings.

**Review by e-kayrakli — APPROVED** [review]

**Comment by bradcray** [comment]
For future reference.  It seems I made a mistake and merged fd48ecd6daa4f2b40ad984cf8a5e5b6f1ead8d98 into this PR at some point accidentally, probably when testing to see how the two of them worked together.  I didn't notice this until I'd merged this and found that #19407 was merged as well upon merging this one.  Sorry for the sloppiness and any resulting confusion.

**Pull request merged**
