### PR TITLE
Improve chapel-py errors when python versions are mismatched

### PR DESCRIPTION
**Pull request by jabraham17**
This PR significantly improves the errors users get when they try and use a chapel-py based tool with mismatched python versions.

This PR splits the chpldeps install directory into general dependencies and python version specific dependencies. This allows the `run-in-venv-with-python-bindings` script to be able to easily distinguish python versions. This also allows builds for multiple python versions to live side-by-side, without needing to `make clobber`.

Resolves https://github.com/chapel-lang/chapel/issues/24892

Tested locally, switching between python3.11 and python3.12

[Reviewed by @mppf and @DanilaFe]

### CODE REVIEW

**Comment by jabraham17** [comment]
> What are "general dependencies" ? It looks like this PR only puts the chapel-py stuff in the directory with the python version. Aren't many of the other dependencies sensitive to Python version? I'm pretty sure there's some C code in many of them. So I'm not understanding how it is we would split these other dependencies between the two directories.

I think my wording here is poor and I will update the OP. By general dependencies I mean python dependencies for chpldoc and the test environment. 
We only have 3 version-specific dependencies: `PyYAML`,` MarkupSafe`, and `charset_normalizer`. `PyYAML` relies on `cython`, which doesn't seem to break between ABI versions. `MarkupSafe` has a python fallback for its C extension code. `charset_normalizer` is built as a "version-specific" dependency, but it has no C extension code,

The reason I did not put all dependencies in a version specific directory is its only needed for `chapel-py` based tools, I can build chapel with `python3.12` and then run `chpldoc` or `start_test` with `python3.11` just fine. But not `chplcheck` or `chpl-language-server`

> Perhaps it would mean that certain installation processes (such as the Cray module build) would need to build the chpl-venv app for different python versions.

Yes exactly, this is why other python dependencies are left as they are.

> If chapel-py is going to be the only thing in the versioned directory, IMO we should call it e.g. third-party/chpl-venv/install/chapel-py3.11/.

Right now, `chapel-py` (and its dependencies like pygls) are the only thing that need to go in its own venv. I can rename the folder `chapel-py311`

**Comment by jabraham17** [comment]
I like `chpl-frontend-py`.

This isn't really a user facing folder, but @DanilaFe do you have an opinion on the venv name?

**Comment by DanilaFe** [comment]
I'm happy with `chpl-frontend-py` as an internal `venv` folder, and it might even be a good name for the `chapel-py` project on the whole. `chapel-py` had always been my "spare time prototype" name and I don't much thought to such names. But that's a different question.

**Review by DanilaFe — APPROVED** [review]
Seems reasonable to me personally (pending @mppf's approval). This makes me worry that (e.g.) our homebrew installs will break as soon as homebrew updates Python (which it will do with little provocation). But that's an unrelated concern to this PR (this PR improves the error message if anything).

**Pull request merged**
