### PR TITLE
Add a sample performance test

### PR DESCRIPTION
**Pull request by lydia-duncan**
This adds a sample performance test, to reference from the TestSystem.rst
documentation updates

### CODE REVIEW

**Comment by bradcray** [comment]
I'm confused: Don't we already have one of these in Samples/Performance/foo.chpl?

https://chapel-lang.org/perf/chapcs/?suite=samplesbogus

**Comment by ronawho** [comment]
> I'm confused: Don't we already have one of these in Samples/Performance/foo.chpl?

Yeah, we do have an existing one. I suggested adding an even simpler example that is just straight Chapel performance test instead of a "How to compare performance against C" test.

**Comment by bradcray** [comment]
OK thanks.  I didn't get that from the PR message and couldn't remember enough about the previous to be able to compare.

**Comment by lydia-duncan** [comment]
Sorry about that.  Elliot wanted me to link to the PR as well, so I'm going to make the merge message more intricate but try to keep the PR simple and clutter free

**Pull request merged**
