### PR TITLE
Modular Exponentiation (Power in Modular Arithmetic)

### PR DESCRIPTION
**Pull request by aditmehta9**
If three numbers x, y and p are given, it computes (x^y) % p. It is very useful in competitive coding.

### CODE REVIEW

**Comment by aditmehta9** [comment]
2 test cases of travis-ci aren't passing I can't understand the reason please help me.

**Comment by aditmehta9** [comment]
I tried to make the function using simple loop and recursion both. Both time it failed the test cases of Travi-CI

**Comment by mppf** [comment]
We need to discuss whether or not it makes sense to add 'modularexp' to Math.chpl and creating a github issue would be an appropriate way to do that. I don't think this PR can move forward until the community gets on board with adding this as an included-by-default function.

Note that the Travis failures are coming from using tabs:

> Found tabs :-(
> modules/standard/Math.chpl:1075: { modules/standard/Math.chpl:1076: var y:int=0; modules/standard/Math.chpl:1077: if(n==0) modules/standard/Math.chpl:1078: { modules/standard/Math.chpl:1079: return 1; modules/standard/Math.chpl:1080: } modules/standard/Math.chpl:1081: else if(n%2==0) modules/standard/Math.chpl:1082: { modules/standard/Math.chpl:1083: y=modularexp(x,n/2,m); modules/standard/Math.chpl:1084: return (y*y)%m; modules/standard/Math.chpl:1085: } modules/standard/Math.chpl:1086: else modules/standard/Math.chpl:1087: { modules/standard/Math.chpl:1088: return ((x%m)*modularexp(x,n-1,m))%m; modules/standard/Math.chpl:1089: } modules/standard/Math.chpl:1090: }


Our project generally uses the convention of indenting with two spaces at a time.

**Comment by ben-albrecht** [comment]
Closing this due to inactivity. Happy to reopen if/when activity resumes.

**Pull request closed without merging**
