### PR TITLE
Mark `fileReader.assertEOF` unstable

### PR DESCRIPTION
**Pull request by jeremiah-corrado**
Per discussion summarized [here](https://github.com/chapel-lang/chapel/issues/19316) mark `assertEOF` unstable. Tests that use `assertEOF` are updated to check for EOF directly.

Resolves https://github.com/chapel-lang/chapel/issues/19316

- [x] paratest
- [x] inspected docs

### CODE REVIEW

**Review by riftEmber — CHANGES_REQUESTED** [review]
By my grep we also need to update `test/io/ferguson/asserteof.chpl`

**Comment by jeremiah-corrado** [comment]
I saw that one, but thought it would be okay to keep a test that's specific to the unstable symbol. Are you saying it should be deleted, or updated to not use assertEOF?

**Comment by riftEmber** [comment]
I was thinking updated to not use `assertEOF` just cause that's what the other tests do. But actually since it's specific to the unstable symbol, and your new test in `test/unstable` has the same purpose, what about merging them both into your new test?

**Comment by jeremiah-corrado** [comment]
Sounds good, I replaced the `unstable/` assertEof test with the older one since it's more exhaustive anyway.

**Review by riftEmber — APPROVED** [review]

**Pull request merged**
