### PR TITLE
Stringcache optimization and tooltips for main display

### PR DESCRIPTION
**Pull request by tomyhoi**
-- Add a string cache so that source file names are stored only once for unique names, saves space in the event list.
-- Add tooltips for the main display that shows the associated numeric value for the color of the locale.

### CODE REVIEW

**Comment by tomyhoi** [comment]
@gbtitus, @Kyle-B -- checkout these changes to the runtime.   Removing need for _BSD_SOURCE and _DEFAULT_SOURCE.

**Comment by gbtitus** [comment]
The runtime changes look great. I'd prefer to see those and the tool changes in separate PRs, though, as they're so unrelated.  But if that would be a hardship at this point then it's okay to do them together.

**Comment by tomyhoi** [comment]
I didn't think about separating them because that is the runtime to support the tool.  If it is a big deal, I can create a branch for the runtime changes and do that as a separate PR.

**Comment by gbtitus** [comment]
Yeah, understood that the runtime file is for support of the tool.  I mean unrelated in that the runtime change and the tool changes are achieving different aims. It would have been ok to bundle them, but I see you've already separated them.  Thanks!

**Pull request merged**
