### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in

driver.cpp, convert-uast.cpp, implementForallIntents.cpp,
lowerLoopContexts.cpp, resolution-types.h, Context.cpp,
parser-error-classes-list.cpp and a good file,
resolution-queries.cpp, post-parse-checks.cpp,
ChapelDomain.chpl, and primers/fileIO.chpl

### CODE REVIEW

**Comment by cassella** [comment]
For the changes to code / output strings, please review:

@DanilaFe (parser-error-classes-list.cpp, convert-uast.cpp)
@vasslitvinov (or @e-kayrakli ) (lowerLoopContexts.cpp)

I tested only the test with a modified .good file.

**Review by DanilaFe — COMMENTED** [review]
Changes I'm tagged on look good, thanks, Paul. I feel like I'm always in these 😛

**Review by vasslitvinov — COMMENTED** [review]
Good fixes! Looks good, I will merge.

**Comment by vasslitvinov** [comment]
Yes, please. Better yet, please replace my commit with yours or rebase it into yours.

**Comment by cassella** [comment]
Ok, done.  I rebased your commit into mine and added a Co-Authored-By to it.  :)

**Comment by vasslitvinov** [comment]
Thanks so much! Now just for the checks to pass.

**Pull request merged**
