### PR TITLE
Add chplvis build test

### PR DESCRIPTION
**Pull request by aconsroe-hpe**
Add chplvis nightly build

Partially addresses Cray/chapel-private#1994

Requires updating chapel-ci-config as well.

### CODE REVIEW

**Comment by aconsroe-hpe** [comment]
I double checked that a failed build will have non-zero exit status. Is that enough for jenkins to notice?

**Comment by ronawho** [comment]
> I double checked that a failed build will have non-zero exit status. Is that enough for jenkins to notice?

That's enough. For configs like this I _think_ we have historically skipped adding the cron file since it doesn't add much. See the c2chapel testing in chapel-ci-config for an example

**Comment by aconsroe-hpe** [comment]
Gotcha I see that now. Does it make a difference chapcs vs chapvm for this?

**Comment by ronawho** [comment]
Not really. I default to chapvm though and only use chapcs if it's something that needs extra CPU cycles (like heavily oversubscribed gasnet or valgrind testing)

**Comment by aconsroe-hpe** [comment]
Ahh yeah sorry I dropped the bit of context for my question: The c2chapel test is currently on chapcs, so I was leaning towards copying that for this test, but my other inclination was similar to yours and to use chapvm b/c it doesn't need the cycles.

**Comment by ronawho** [comment]
Oh, that's interesting. I have no idea why c2chapel testing is on chapcs. I suspect there is no good reason and it could just as easily (and maybe preferably) run on chapvm..

Looking at the history it appears that it was put on chapcs before chapvm machines existed, so it's probably just an oversight that we never moved it (though it doesn't take long to run, so maybe it doesn't matter)

**Comment by aconsroe-hpe** [comment]
Just noting that I intend to make a PR to chapel-ci-config once our Jenkins migration is sorted. Leaving this open until I get that done.

**Comment by aconsroe-hpe** [comment]
I've been sleeping on this @ronawho -- still looks good? I will prepare the change for Jenkins. Preference on which machine it runs on?

**Comment by aconsroe-hpe** [comment]
Gotcha; I guess I was following the example of `util/cron/test-c2chapel.bash` but I see that we don't actually call that from the jenkins definition.

Closing in favor of just a ci-config change

**Pull request closed without merging**
