### PR TITLE
Consider PRIM_GET_MEMBER_VALUE in freeHeapAllocatedVars

### PR DESCRIPTION
**Pull request by mppf**
This is a bug fix from string-as-rec. It adjust freeHeapAllocatedVars
which is checking if a heap variable could be passed to a begin
statement. It adjusts it to consider PRIM_GET_MEMBER_VALUE in addition to
PRIM_GET_MEMBER. The code has special cases for these operations because
use-def analysis does not consider a use of a field (the result of
PRIM_GET_MEMBER) as a use of the record/class as a whole.

Added a comment pointing out that PRIM_GET_SVEC_MEMBER_VALUE should
possibly also be handled in the future.

Passed full local testing.
Passed GASNet testing.

Reviewed by @benharsh - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
- [ ] full local testing
- [ ] full gasnet testing
- [ ] code review

**Comment by mppf** [comment]
Full GASNet tests pass (fifo)

**Comment by mppf** [comment]
Passes full local tests (qthreads, re2, etc)

**Comment by benharsh** [comment]
Looks good. Should PRIM_GET_SVEC_MEMBER_VALUE be here as well?

**Comment by mppf** [comment]
Hi @benharsh, probably. Would you like me to add it to this PR and re-run the testing? Or should we leave that to the future?

**Comment by benharsh** [comment]
I think this PR can go in as-is. A TODO comment might be helpful in the future (however far out that is).

**Comment by bradcray** [comment]
Just pattern-matching at a very high level, the references to "free heap allocated variables" and "begin statement" in this commit message make me wonder whether this pass is working hard to preserve the old "keep things alive past their lexical scope if referenced by a begin" semantics and whether it points to another place where we can simplify the compiler and generated code by moving things back onto the stack rather than moving them to the heap?

**Pull request merged**
