### PR TITLE
Encompassing only entire statements with preprocessor conditionals.

### PR DESCRIPTION
**Pull request by flaviommedeiros**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

- https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
- https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by ronawho** [comment]
Hi @flaviommedeiros 

These seem like nice changes to me! Both gasnet and massivethreads are third party packages, so ideally we'd like to see these changes made upstream. Then we could either apply this patch to the copies in our repo as well, or just get them the next time we upgrade versions.

gasnet is very much alive on [bitbucket] (https://bitbucket.org/berkeleylab/gasnet). Feel free to suggest these changes to the gasnet team directly, or if you prefer I'd be happy to ping them.

I'm not sure about massivethreads. @gbtitus do you know if there's still anybody developing massivethreads?

**Comment by gbtitus** [comment]
I don't know whether massivethreads is alive or not, but I do believe I've heard from @bradcray (mentioned in hopes he'll chime in) that their direction has changed such that Chapel isn't of major importance to them any more.

I would also say that although these are worthwhile changes I don't believe we should make them in our downloaded copies of these two third-party packages, because that will create a maintenance burden for Chapel.  (Each time we upgrade these packages we'll have to re-apply this change and any other similar ones.) The changes should be submitted to the upstream packages instead of to Chapel, which is just a client.

**Comment by bradcray** [comment]
I agree with the philosophy of applying changes to third-party packages in their originating setting whenever possible rather than in our tree.

**Comment by bradcray** [comment]
Based on the reasonably unanimous discussion above and lack of response, I'm going to close this PR to houseclean.

**Pull request closed without merging**
