### PR TITLE
remove non-init halts from Crypto module

### PR DESCRIPTION
**Pull request by psahabu**
Discussion after the merge of #8244 prompted a closer examination of the Crypto module. While it was not possible to remove halts from `init()` due to the present inability to throw from initializers, this PR locates all the other halts in the module and has them throw a new standard error type, `IllegalArgumentError`.

- [x] passes linux64+flat testing, with futures

### CODE REVIEW

**Comment by saru95** [comment]
The tests checking for `halts` should fail. The `.good` file for those will also have to be updated to reflect the error message. Something like this file - https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Crypto/saru/utils/buffer3.good

**Comment by psahabu** [comment]
@saru95 Right, once we can throw errors in initializers then these tests will need to be updated. Until then this is the most that can be done.

@mppf Will do.

**Comment by lydia-duncan** [comment]
My two cents: I might be tempted to have the IllegalArgumentError class store the name of the argument and the reason for it being illegal and then give a standardized message of "Argument <arg> was illegal because <reason>" or something along those lines.  It doesn't seem very distinguished from other error subclasses otherwise.

**Comment by psahabu** [comment]
@mppf what do you think of the changes to `IllegalArgumentError`?

**Comment by mppf** [comment]
@psahabu - look good to me!

**Pull request merged**
