### PR TITLE
Add argument name as default long option

### PR DESCRIPTION
**Pull request by arezaii**
This PR changes the default behavior of the argument parser's `addFlag` 
and `addOption` methods to use the `name` parameter as the long option, 
as described by cray/chapel-private#2388. 

Additionally, this PR changes the default value of the `flagInversion` 
parameter of `addFlag` to be `false` rather than `true`. This was changed to
more closely align with Swift's parser (the inspiration for the parameter) and
because the most common use case when implementing the parser in mason was for 
`flagInversion` to be `false`. 

A new test was added for default values (although the UnitTest framework
is causing a compilation error when `opts` are not set). The example code
was also updated to reflect the updates, along with all the places in mason
that previously set `flagInversion=false`.

TESTING:

After running `make cleanall` from `$CHPL_HOME`:

- [x] Can `make`
- [x] Can `make docs`
- [x] Can `make mason`
- [x] Can `make check`
- [x] Passing tests from `util/start_test test/mason/`

Reviewed by @mppf

Signed-off-by: Ahmad Rezaii ahmad.rezaii@hpe.com

### CODE REVIEW

**Review by mppf — APPROVED** [review]
This seems nice! I like the way that the Mason code doing arg parsing is simplified.

I have just one concern.

I wonder if it would be more intuitive for the name to include `--` in these cases. E.g. 

``` chapel
 var showFlag = parser.addFlag(name="--show", defaultValue=false);
 ```

would mean that it should handle the argument `--show`.

Would it be more obvious what this is doing in that case? Do you know of other parsing library precedence for this feature, either way?

**Comment by arezaii** [comment]
> Would it be more obvious what this is doing in that case? Do you know of other parsing library precedence for this feature, either way?

This is a good question and I'll try to answer it from the perspective of other libraries. TL;DR: Rust, Python, and Swift all have a concept of `name` that is independent of any `--` or `-` identifiers, although Python sort of blurs this line (typical 😃).

- Swift: 
    - For a simple argument without flags, the argument `name` is interpreted from the variable name, i.e
    ```swift
    @Argument() var highValue: Int
    ```
    names the argument `high-value` in the help message.

   - For options and flags, the default is to create a long flag from the variable name (similar to what is implemented in our 
     parser) and the user can provide an enum value to say "make both long and short options" or other combinations.
    ```swift
    @Flag(help: "Include a counter with each repetition.")
    var includeCounter = false
    
    @Option(name: .shortAndLong, help: "The number of times to repeat 'phrase'.")
    var count: Int?
    ```
   would generate the flag `--include-counter` and option `-c, --count <count>`


- Rust:
    - For all args, there is a `with_name` method that assigns the argument name, and a separate `long` and `short` method to 
      define long and short options respectively. 
      From the docs: 
      > The name will be used to get information about whether or not the argument was used at runtime, get values, set relationships with other args, etc..
      
- Python:
    - the `add_argument` method uses the first string field for either the name or the long and short options. If only a name is
      provided, the argument is assumed to be positional, if `-`s are present, the argument is assumed to be an option. In both
      cases, a `metavar` argument can be used to customize the `help` message output. If options are passed, then the leading 
      `-`s are stripped and the argument is accessed using the remaining characters, unless the `dest` argument is specified (which will take precedence) If that sounds confusing, it sort of is.

**Comment by mppf** [comment]
Sounds like we are following Swift, which is reasonable. I think it would be nice, if the name begins with `-` or `--`, for us not to add the `--` before it, but other than that I think this is good to go.

**Comment by arezaii** [comment]
> Sounds like we are following Swift, which is reasonable. I think it would be nice, if the name begins with `-` or `--`, for us not to add the `--` before it, but other than that I think this is good to go.

Tagging @bradcray in case there is any objection to allowing the user to specify either:
```chapel
 var showFlag = parser.addFlag(name="--show", defaultValue=false);
// or
 var showFlag = parser.addFlag(name="show", defaultValue=false);
```
To achieve the same result of having a flag `--show` as a parsable option.

**Comment by bradcray** [comment]
I'm fine with that approach personally—it seems sufficiently clear and attractively flexible for users coming from different perspectives.  (Like any design decision), I think it could be worth running past the team or community as a design question to get more eyes on it and to try and avoid adding something that we need to deprecate later.  

One thing unclear to me:  What do you anticipate happening if the user uses `"-show"` as the name?  Error/warning?  Does it end up supporting `-show` or `---show` or something else?

**Comment by arezaii** [comment]
> One thing unclear to me: What do you anticipate happening if the user uses `"-show"` as the name? Error/warning? Does it end up supporting `-show` or `---show` or something else?

It would end up with `-show` being the option. Right now there is no constraint/requirement that a single dash can only be followed by a single char, in part because `-nl` exists and from our initial vision of the argument parser handling all arguments, I didn't want to restrict it from being able to handle `-nl`.

It may be reasonable to restrict the pattern to single dash=single char, but I think that is a discussion for another PR.

**Comment by bradcray** [comment]
> It would end up with -show being the option.

That works for me, thanks.  Though it also sortof makes me think maybe we shouldn't support `"show"` rather than just `"-show"` or `"--show"` since it might seem arbitrary that we assume it to be a double-dash argument rather than a single-dash argument?  (or maybe someone would misunderstand and think that this was a way of creating a 0-dash argument?)  

Sorry if I'm contradicting my previous response.  If we were freezing today, I think I might require the name to have one or more dashes at the front of it, since we can always relax that later.  But if we start out relaxed, it may be painful to go back.  Of course, we're not freezing today, so we could also debate more here or bring in the broader team for opinions.

**Comment by mppf** [comment]
Having `name=show` turn into `--show` is reasonable and defensible IMO because it's common for multiple character arguments to start with double-dash. (Additionally, there is precedent for it in Swift, but there, they couldn't use `--bla` as the name because the name is coming from a variable name).

However, it would be totally fine with me to only infer the `opts=` part if the`name=` begins with a dash. I suppose I have a slight preference for that. However it's not quite clear to me how to do that, since now `opts` sometimes has a default but not others? Does it halt/throw in the case the `name=` does not start with a dash? Adding `--` in front of it in that case seems preferable IMO to halting or throwing.

Perhaps the default could just be whatever `name=` is, without ever modifying it at all. That would make the `name="--bla"` case typical but `name="bla"` is still easy to explain and understand, even if it's not quite what one wants in the common case. (And I'm not particularly worried that people coming from Swift will be confused b/c the code to add an argument looks so different). I like this strategy because it is the simplest of all and seems to assume less about what the user would want in terms of `-` vs `--` vs no dash.

Anyway my view is that as long as the default is understandable we will be OK here since all of this behavior can be easily overridden by providing an `opts=`.

**Comment by arezaii** [comment]
It may just be my preference because I wrote it that way originally, but I still prefer having `name` be a raw name, and `opts` being opts. Once we go down the path of "name can be anything you want", then it opens a bunch of other questions and, IMO, makes the library more confusing to use. I think the `name` field should be just that, I don't see much benefit from allowing dashes in the name TBH, because it means we are conflating the `name` with the `opts`. I think the previous behavior of using the `name` to _generate_, not _assign_, the long option is quite simple and efficient, and easily allows the developer to override the functionality by providing explicit `opts` values.

**Comment by mppf** [comment]
It's probably splitting hairs but in the context of argument parsing, I would consider something like `--show` to be an "argument name". Additionally the use of `name` in the library just needs to be unique so I don't see any problem with it possibly containing dashes.

**Comment by arezaii** [comment]
>  ...in the context of argument parsing, I would consider something like --show to be an "argument name"

You're not wrong and I don't have a strong argument for disallowing this behavior. If we go that route, it puts the usefulness of the `opts` parameter into question. I worry that leads down a path towards removing `opts` altogether and relying on the `name` field as a dual purpose parameter.

Reviewing the three parsers I surveyed, this behavior would be most similar to Python's ArgParse. In that case, the add_argument method [accepts one or more string values](https://docs.python.org/3/library/argparse.html#name-or-flags). If there is only one value and it doesn't start with a `-`, then the argument is assumed to be positional. If there are multiple values, or the leading char is a `-`, then the argument is assumed to be an option. We could do something similar, that would allow doing away with `opts` and relying only on the `name` field to describe the argument and it's flags/options.

With that change we could potentially do away with `addOption`, and maybe even `addFlag`. That puts us much closer to Python and further away from Rust and Swift, however there are some things I don't like as much about that approach, namely that the valid combination of parameters (and their values) to supply to `addArgument` changes based on the _values_ in the `name` field and the _type_ of `defaultValue` (a point of confusion when using Python's ArgParse in my experience), and it requires more handling in the `addArgument` method to evaluate the parameters.

**Comment by mppf** [comment]
I don't know about everybody else but I'm fairly happy with where this PR ended up & I view the "default opts based on name" thing as a minor issue. I don't think it justifies throwing away `opts` entirely, say.

**Comment by bradcray** [comment]
I have to admit that I've mostly lost the thread over the past 4-5 responses.  It feels to me like this might be a good topic for a deep-dive for the team, which could be an "introduction to the argparse module and design questions" to get more eyes on it and opinions back.  Since it's early days for the module and it's living in the packages directory for now, I don't feel particularly nervous about finding the perfect solution for 1.25 (though obviously, the less we have to change later, the better).  So, put another way, I don't feel like this discussion needs to hamstring this PR either as long as we're comfortable if we end up evolving it as more people do review and use the features (which I am, but I don't have much skin in the game).

**Comment by arezaii** [comment]
> ...as long as we're comfortable if we end up evolving it as more people do review and use the features...

I view the argument parser as an alpha product for release 1.25, so I expect there will be several changes as it gets more eyes/use cases. I'll merge this as is, with the understanding that it's up for change at some point in the future. 

> Since it's early days for the module and it's living in the packages directory for now...

I had not planned to move the parser to `modules/packages` prior to the release, but I have tested it and it's a very simple change to make so I can move forward with that in a new issue where we can debate about what to name it 🤣

**Comment by bradcray** [comment]
> I had not planned to move the parser to modules/packages prior to the release

I think that we should move it to modules/packages for the release (as we discussed on Slack yesterday).  I think it's a nice effort to highlight and start getting feedback on, and that it's better for mason to be using a package (even if it's one that's subject to change) rather than a one-off / mason-specific module.

**Comment by bradcray** [comment]
(and I think it simplifies / robustifies the "did the user use `ArgParse`? check that we were designing yesterday).

**Pull request merged**
