### PR TITLE
Fix the `tuple.indices` definition for 0-based tuple indexing.

### PR DESCRIPTION
**Pull request by gbtitus**
It looks like this was just a leftover from the 1-based days.

### CODE REVIEW

**Comment by bradcray** [comment]
Thanks Greg!  As part of reviewing, I scanned for other instances of "1" and "one" to see if I'd missed other spots in this file, but didn't see any.  Not sure how this one got away...

**Review by bradcray — APPROVED** [review]

**Comment by gbtitus** [comment]
Do we not save artifacts for the documentation CI check any more? I feel like there used to be a link I could click to see those, but just now for this PR I couldn't find it.

**Comment by bradcray** [comment]
We do, though it's hard to find.  I wouldn't have been able to answer this quickly if I hadn't done it for another PR today:
* click "Checks" tab above
* click "> CI" on left sidebar
* look to "Artifacs" at the bottom of the resulting page

**Comment by gbtitus** [comment]
Ah, there it all is. Thanks!

**Pull request merged**
