### PR TITLE
Update ranges/domains to remove deprecated behaviors w.r.t. low/high queries, sizeReturnsInt

### PR DESCRIPTION
**Pull request by bradcray**
This makes a few changes to ranges and domains to remove deprecated
behaviors and move us closer to 2.0 behavior:

* it removes the deprecated sizeReturnsInt config param
* it makes range low / high bounds return aligned bounds by default
  - deprecating the 'alignedBoundsByDefault' config param since it's no longer used
  - updating documentation to reflect the new behavior

Note that this preserves the alignedLow/alignedBounds queries on ranges
for now.  I'd imagined we would deprecate these now that they're
duplicates, but at least one user was potentially interested in
keeping them in order to have a more descriptive way of saying what
you wanted.  I'm not sure I agree with this, but it deserves more
discussion than we've given it, so I've opened #20606 for that
topic.

### CODE REVIEW

**Review by benharsh — APPROVED** [review]
This looks good to me.

Will a future PR change all the alignedLow/alignedHigh stuff in our internal/standard modules back to .low and .high?

**Comment by bradcray** [comment]
> Will a future PR change all the alignedLow/alignedHigh stuff in our internal/standard modules back to .low and .high?

That's a good question...  I'd be inclined to do that, but it might depend on how people feel about:

```
Note that this keeps the alignedLow/alignedBounds queries on ranges
for now. I'd imagined we would deprecate these now that they're
duplicates, but at least one user was potentially interested in
keeping them in order to have a more descriptive way of saying what
you wanted. I'm not sure I agree with this, but it deserves more
discussion than we've given it.
```

Specifically, if someone wanted to argue hard that it's better style to use the `.aligned` versions
(e.g., "it's less vague / more explicit"), that could suggest leaving them as-is.  (My preference
would still be to deprecate the aligned versions and that would be a natural time to rewrite the
uses of them as well).

How about if I open up an issue asking the question about deprecation vs. preserve as a next
step here?

**Comment by benharsh** [comment]
I agree that this warrants some discussion, so opening an issue sounds good to me.

**Comment by bradcray** [comment]
I opened https://github.com/chapel-lang/chapel/issues/20606 for this question.

**Pull request merged**
