### PR TITLE
Remove validation of ISx problem size

### PR DESCRIPTION
**Pull request by benharsh**
The refactoring from #3553 resulted in massive memory leaks, as we were previously exiting before allocating distributed arrays. Instead, remove the numTrials=0 execopts and rely on performance testing to track the problem size.

### CODE REVIEW

**Comment by gbtitus** [comment]
I took a fairly surface look, but this seems okay to me.

We still have the so-called 'exit(0)' problem, but these tests
will no longer demonstrate that, right?

**Comment by benharsh** [comment]
Right, I think we still want to investigate in more detail the nightly failures we were seeing. The refactoring I did to work around the exit() resulted in huge memory leaks for execopts 4-6, which this PR should fix by removing those execopts.

**Comment by bradcray** [comment]
Can we remove the "if numtrials == 0" conditional now too to make the code prettier?  (under the "Those who ask to run with 0 trials deserve what they get" clause?)

**Comment by bradcray** [comment]
I did not test, but this looks like what I'd expect!

**Pull request merged**
