### PR TITLE
Setting $CHPL_HOME in gen_release

### PR DESCRIPTION
**Pull request by ben-albrecht**
Module build failed last night - `make docs` depends on $CHPL_HOME to be set, which does not occur for the particular configuration of gen_release that the cray-module-build job runs.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
@bradcray @lydia-duncan @ronawho

**Comment by ronawho** [comment]
Looks good to me. Personally, I'd probably put this code in the else branch, but that might just be a style thing so there's no need to change it.

**Comment by lydia-duncan** [comment]
I agree

**Comment by ben-albrecht** [comment]
I concur

**Pull request merged**
