### PR TITLE
Analyze conditionals for nil checking

### LINKED ISSUE #13307: nil checking on error-handling
### Summary of Problem

Calling a method on a generic error within a catch block results in a nil-checking error.

### Steps to Reproduce

**Source Code:**

```chapel
proc hello() {
  try {
    writeln('hello');
  } catch e {
    writeln(e.message());
  }
}

hello();
```

```
nilCheck.chpl:1: In function 'hello':
nilCheck.chpl:5: error: attempt to dereference nil
nilCheck.chpl:2: note: this statement may be relevant
```

### Configuration Information

- Output of `chpl --version`: chpl version 1.20.0 pre-release (775dd4ff11)

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #13307, which is also part of #11918.

Next steps: analyze `if obj then ...`, `if obj==nil`, `if obj != nil`.
Also, when a symbol is known to be non-nil, we could eliminate `postfix!` calls on it.

The commit 93bf2a7 contains a draft check for `if obj then`. To use in production, it needs these changes:
* Add checks for FLAG_TEMP or isConstValWillNotChange(). If neither passes, the symbol could change potentially, so do not update AliasMap for it.
* Replace the "same location" check. Instead, traverse the def-use links back from the symbol tested in the conditional, through prim-casts, calls to _cast, and calls to borrow().

### CODE REVIEW

**Comment by vasslitvinov** [comment]
@mppf what do you think?

**Comment by vasslitvinov** [comment]
The condition guarding the update of "other symbols" in adjustMapForNilTest(), following the comment:
```chpl
// ...and for all other symbols that have the same "location".
```
i.e. `if (loc.location == oldAL.location)`, is not good. This is because it fires when both locations are NULL - that is, when no information is available for the other symbol and no information WAS available for the currently-determined symbol.

This misfires for this test:
```
test/errhandling/parallel/nested-coforall-throws.chpl
```

in this function:
```chpl
proc printErrors(errors: borrowed TaskErrors, depth:int)
{
  for e in errors {
    var g = e:borrowed TaskErrors?;
    if g {
      writeln(" "*depth, "TaskErrors");
      printErrors(g!, depth + 1);
    } else
      writeln(" "*depth, "err:", e.message());
  }
}
```
where `e` is considered NULL in the else-branch. If we disable updating "other symbols" whose location is unknown, then in the above test `g` is NOT considered non-NULL in the then-branch.

Tracing the AST from the actual argument of `_cond_test()` to the symbol we want to label as non-NULL (in the then-branch) or NULL (in the else-branch) is complicated due to various intermediate casts. For example, the above `var g = e:borrowed TaskErrors?; if g ...` is represented as:

```
58975           move( cast_tmp[958970] call( fn borrow[758516] e[181162] ) )
959102          move( coerce_tmp[959096] cast( type borrowed Error?[302464] cast_tmp[958970] ) )
544789          move( call_tmp[544786] call( fn _cast[827534] coerce_tmp[959096] ) )
399624          move( g[181063] call( fn chpl__initCopy[828219] call_tmp[544786] ) )
959212          move( coerce_tmp[959206] cast( type borrowed object?[302445] g[181063] ) )
544794          move( call_tmp[544791] call( fn _cond_test[9865] coerce_tmp[959206] ) )
181140          if call_tmp[544791]
```

So, we need a better way than what is currently implemented in this PR.

**Comment by mppf** [comment]
> i.e. if (loc.location == oldAL.location), is not good. 

Is this PR an improvement if you simply remove that section?

> Tracing the AST from the actual argument of _cond_test() to the symbol we want to label as non-NULL (in the then-branch) or NULL (in the else-branch) is complicated due to various intermediate casts.

There are pragmas that might help with this, if the operations causing confusion are from internal modules. In particular, these functions could be decorated with `pragma "nil from arg"` on the relevant argument (or with `pragma "nil from this"`). Then, your code here could check for this flag before assuming other temporary variables had the same nilability.

I think it'd be important to apply this to compiler temps only, and/or check that the copy and the original variable cannot be modified independently in a way that makes the checking wrong.

**Comment by vasslitvinov** [comment]
Passes linux64 -futures testing. @mppf would you review?

**Pull request merged**
