### PR TITLE
Update Dockerfile and README for Chapel Release 1.21.0: Release Branch Only

### PR DESCRIPTION
**Pull request by soohoonchoi**
Updated Docker file and README file to be consistent with the previous releases.
Updated version to 1.21.0 and kept references to current and 1 previous release.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
I think it's a good habit to link to the last release's update in PRs like this: #14135

Do we need to make any changes to  `util/dockerfiles/gasnet/Dockerfile` like we did last time?

**Comment by jhoole** [comment]
Seconding Ben's question about gasnet, otherwise looks good.

**Comment by soohoonchoi** [comment]
The `util/dockerfiles/gasnet/Dockerfile` didn't need update, since the master branch already had the correct line:

> FROM chapel/chapel:latest

**Comment by soohoonchoi** [comment]
Thanks for the pointer about linking the last release update.

**Pull request merged**
