### PR TITLE
Allow defining a method on a type alias or a paren-less fn

### LINKED ISSUE #11646: Cannot define new method on type alias
I want to define a method on a type alias, and have it effect the resolution for the aliased and aliasing types.
```chapel
proc int.m1() {
  writeln("m1 with ", this);
}

1.m1();
2.m1();

type int_v2 = int;

var i2: int_v2 = 11;
i2.m1();

// Defining a method on int_v2 does not work.
// --> error: cannot resolve base type for method 'm2'
proc int_v2.m2() {
  writeln("m2 with ", this);
}

// If it did work, I would now expect these to work:
1.m2();
2.m2();
i2.m2();
```

I don't know if there's additional complexity to consider with e.g.,
```chapel
class Container { type t; }
type StringContainer = Container(string);
proc StringContainer.method() {}
```

`chpl version 1.19.0 pre-release (78051d35)`

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #11646.

With this change, the receiver type in a method declaration
can be given by a type alias or a paren-less function,
for example:

    proc myTypeAlias.myMethod() {....}

Note that such a declaration is the same as if the aliasee is specified
as the receiver instead. For example:

    type myTypeAlias = int;
    proc myTypeAlias.myMethod() {}
    proc int.myMethod() {}
    5.myMethod(); // ambiguous, as both myMethod methods are applicable

While there, add a .future for #5979.

### CODE REVIEW

**Comment by vasslitvinov** [comment]
@benharsh @mppf do we want this? is there a relevant issue/issues?

**Comment by lydia-duncan** [comment]
When I've toyed with this idea in the past, it's been an open question to me whether the method should only be defined on the type alias or whether it should impact both the alias and the original type

**Comment by vasslitvinov** [comment]
One way to resolve this, perhaps, is to allow this form (A):
```chpl
proc (IDENT).METHOD() .....
```
where IDENT can be a type alias or a paren-less function call. Leaving this form (B):
```
proc IDENT.METHOD() ....
```
to require IDENT to be the original type name, not an alias, as it does today.

Right now the parser does not distinguish between the two syntaxes. However, (A) is perfectly legitimate because a type alias is a valid expression, and we do not (intend to) restrict what kinds of expressions can go within those parens.

Thoughts?

**Comment by benharsh** [comment]
I'm not opposed to allowing this. Is there a particular motivating example?

**Comment by vasslitvinov** [comment]
> Is there a particular motivating example?

I stumbled over this while changing the representation for `extern type` declarations, in support of #15807.

**Comment by mppf** [comment]
It would be fine with me

Regarding @lydia-duncan's comment

> When I've toyed with this idea in the past, it's been an open question to me whether the method should only be defined on the type alias or whether it should impact both the alias and the original type

I think the very term we use - *type alias* - indicates what should happen. The type alias is just another name for a type. If you want a different type with different methods, you have to use some other mechanism to create that new type.

**Comment by lydia-duncan** [comment]
> If you want a different type with different methods

The point is not necessarily *different* methods, but mostly shared with some additional ones.  Like, in this scenario you want the basis of the type being aliased, but you're giving it another name for a reason - it represents something different than the original type.  If all you care about is that it has a different name, sure but you can also accomplish that by a use/import with a rename, you don't need a full other symbol for that (and if you're making a separate one in the same scope, what's the point?)

**Comment by vasslitvinov** [comment]
Related: #11646

**Comment by lydia-duncan** [comment]
Here's an example: say you want to have a type called "age" to use in a record "Person".  It makes sense to use a `uint` for that, since people can't be under 0.  So you write: `type age = uint;`.  But then say you want to compare two ages in a way that sounds like what you'd say in conversation, say `isOlder` or something.  Sure you could have your clients use the uint's `>` operator, but if type aliases allowed you to define methods just on them as opposed to also on the base type, you could instead write:
```chapel
proc age.isOlder(other: age) {
  return this > other;
}
```
And have them call that instead.

**Comment by lydia-duncan** [comment]
The point of that example is:
1. All the functionality of the original type is valid
2. New functionality doesn't make sense on the old type

Additionally, the type itself is similar enough that one could argue other strategies would be unnecessarily burdensome.  Yes, you could make age a record instead, but if it's just going to have a single field, that's unnecessary extra effort.  In the case of a more complicated example, you'd have to do even more work to get the same functionality that was already provided

**Comment by lydia-duncan** [comment]
My response in the thread Vass links was basically “well, those are additional considerations but I still haven’t felt like I’ve given it enough thought”

Looking at the examples he gives, I’m not fully convinced it would be a bad thing to consider instances of the original type usable for the alias - `A -> B` does not imply `B -> A`, and what I’m proposing is almost an inheritance strategy without:
A. being limited only to types that inherit or
B. requiring the user to type as much as they would if it was a class.

In the case where you are trying to alias a class type and type aliases can define new methods, it makes sense to me to be aliasing a snapshot of the original type rather than allowing its whole hierarchy to be usable - when subclasses diverge, it very well could be that their new functionality is incompatible with other subclasses.

**Comment by lydia-duncan** [comment]
Another point - the type designator is used in three situations:
1. type fields
2. type arguments
3. type aliases

I think situation 3 is the least common usage of the type designator, with situation 1 being the most common.  (I'd be down to do an actual breakdown to back up that assertion but only if people think it's an interesting point.)  The cases where you want to utilize the other two spring more readily to mind than cases where type aliases today are useful.

My point is: this is a way of making it more useful.  The user's guide entry for type aliases is short, it doesn't show very many examples.  The three reasons for using a type alias that it lists there are still maintained by what I'm proposing.

**Comment by mppf** [comment]
> Here's an example:

I agree there are cases where it's most convenient to have a new type and it comes up especially for unit-like things. However I don't think we should use type aliases to do this. I think there should be some other mechanism if we want direct language support for it. (Or people can write records). I just don't think it's what type aliases are (and I don't think we should change them into something fundamentally different from what they are now).

> Another point - the type designator is used in three situations:

I think it's reasonable to expect that you can declare `type t = something;` and have it behave similarly in a variable or field context. The fact that declaring such type aliases as variables is not that common does not mean that the language design is wrong.

Anyway I think we should probably be debating "what is a type alias" on some other issue...

**Comment by vasslitvinov** [comment]
I moved the discussion to #15866 .

**Comment by vasslitvinov** [comment]
Now that we reached consensus in #15866, this is ready to go.

**Comment by vasslitvinov** [comment]
> the implicit this for fields in such methods does not work

Indeed - independently of this PR. I will add an issue and a future test. Or maybe we already have one?

**Pull request merged**
