### PR TITLE
Shared Memory Concurrent Map

### PR DESCRIPTION
**Pull request by dgarvit**
I along with @LouisJenkinsCS implemented [Interlocked Hash Table](https://ieeexplore.ieee.org/document/8091216) for Chapel. It is parallel-safe, and makes use of Local Epoch Manager for garbage collection.

The API structure is pretty straightforward:
* insert(key, value) - insert a key value pair
* find(key) - find the value corresponding to key, if it exists
* erase(key) - delete the key and its corresponding value from the map, if the pair exists

The data structure also provides both serial and concurrent iterators.

Following are the benchmarks, run on `int, int` key value pairs with 16M objects:

### Insert Benchmark
| **Tasks** | **Map (ns/op)**     | **ConcurrentMap (ns/op)** |
|-------|---------|---------------|
| 1     | 52.4464 | 215.189       |
| 2     | 69.6132 | 173.617       |
| 4     | 112.463 | 63.6296       |
| 8     | 237.355 | 33.4546       |
| 16    | 342.124 | 17.664        |
| 32    | 541.906 | 13.4449       |
| 44    | 728.897 | 8.12537       |

### Erase Benchmark
| **Tasks** | **Map (ns/op)** | **ConcurrentMap (ns/op)** |
|-------|-------------|-----------------------|
| 1     | 44.0258     | 105.445               |
| 2     | 133.91      | 53.9272               |
| 4     | 134.443     | 27.9017               |
| 8     | 157.813     | 14.8914               |
| 16    | 368.365     | 8.22508               |
| 32    | 564.483     | 5.26577               |
| 44    | 753.976     | 3.96938               |

### Find Benchmark
| **Tasks** | **Map (ns/op)** | **ConcurrentMap (ns/op)** |
|-----------|-----------------|---------------------------|
| 1         | 68.3497         | 212.212                   |
| 2         | 188.349         | 121.665                   |
| 4         | 191.634         | 64.1202                   |
| 8         | 265.542         | 33.6719                   |
| 16        | 387.145         | 18.6084                   |
| 32        | 580.853         | 9.98491                   |
| 44        | 677.513         | 7.35331                   |

### Intset Benchmark (80% find, 10% insert, 10% erase)
| **Tasks** | **Map (ns/op)** | **ConcurrentMap (ns/op)** |
|-----------|-----------------|---------------------------|
| 1         | 106.038         | 207.047                   |
| 2         | 165.431         | 126.87                    |
| 4         | 219.872         | 68.0732                   |
| 8         | 268.668         | 35.6337                   |
| 16        | 421.874         | 19.3164                   |
| 32        | 577.605         | 11.1499                   |
| 44        | 621.96          | 10.99                     |

### CODE REVIEW

**Comment by mppf** [comment]
I'm happy to see an efficient parallel hashtable!

I understand that this hashtable is designed for parallelism. But ignoring the parallelism part for a minute - what kind of hashtable is it? Is it doing open addressing, e.g.? Does it grow when enough elements are added?

Also, does this have the same API as the standard `map`? If not, could it?

@daviditen added the standard map module (in PR #13821) and we put a lot of effort into API review for that (in #13624).

**Comment by dgarvit** [comment]
As for API, it is not the same, but sure, I'll change it to match `Map`'s API.

**Comment by dgarvit** [comment]
Yes, the table grows - like a tree - when enough elements are added.

**Comment by mppf** [comment]
If there is a reference to an element while it is growing, will that reference become invalid?
I would like it not to do that - see #8339.

**Comment by dgarvit** [comment]
No, thats where EpochManager comes into play. The old node is `deferDelete`ed, while a new PList is added with each of its child nodes representing a bucket of elements.

**Comment by mppf** [comment]
@LouisJenkinsCS - from your picture, it looks like the map might never move elements?

> When an ElementList is filled up, it is replaced with a PointerList

Does the replaced PointerList just refer to the existing ElementList?

If the elements in these ElementLists are never moved in memory, you could allow `ref`s to elements without breaking anything AFAIK.

**Comment by bradcray** [comment]
@LouisJenkinsCS / @dgarvit: I was asked to catch up with this PR and help figure out what we should do with it.  What do you consider the next steps to be?  Thanks!

**Comment by bradcray** [comment]
> Actually @dgarvit do we have any test files for the concurrent map? I.E. for regression testing and for performance testing?

Yeah, that was the main thing I was noticing.  That even if the PR was ready to go in as-is, I don't think it'd be mergeable without tests exercising it.

**Comment by bradcray** [comment]
I'm going to close this PR due to inactivity because we're trying to keep the number of open PRs lower.  But that doesn't reflect disinterest.  I think we'd definitely like this capability, but I'm not sure how to get it into a mergeable state without becoming a pest or trying to take it on myself.

**Comment by dgarvit** [comment]
@bradcray I have created a new PR for this. Can you checkout #16704? I have updated the code for Chapel 1.23, adopted the standard map's API structure, and added some tests. @mppf informed me that exposing references is no more required for parallel/distributed maps, which I believe was the biggest hurdle with this PR earlier. Thanks!

**Comment by bradcray** [comment]
Great, thanks @dgarvit!  I don't know that I'm the most appropriate person to review #16704, but definitely appreciate your pushing further with the effort.  Tagging @dlongnecke-cray who's been working in related areas recently to make sure he's aware of #16704.

**Pull request closed without merging**
