### PR TITLE
Updated Ray Tracing Example

### PR DESCRIPTION
**Pull request by Maxrimus**
The raytracing example was out of date due to the recent change from 1-based arrays to 0-based arrays, causing problems with the scene tag. I fixed this by doing the following:
-Changed the starting file and all solution files to use 0-based array indexing
-Added a number of tests to solution-5 using scene files so that this should be caught in the future if something similar happens again

### CODE REVIEW

**Comment by Maxrimus** [comment]
All Tests Passing
Screen Shot 2021-02-05 at 3 48 56 PM

**Comment by bradcray** [comment]
Thanks for putting this together Joe.  Since `c-ray-5.chpl` and `c-ray-5a.chpl` are identical, I'd suggest removing `c-ray-5a.chpl` and moving `c-ray-5a.execopts` to `c-ray-5.execopts` adding one additional line to capture the current test:

```
                     # c-ray-5.good
```

This will have two benefits: (a) users working through the exercises won't wonder why there are two copies of the same solution if they refer to them; (b) it saves us a compile (which is slow).

**Comment by Maxrimus** [comment]
Brad, my recent commit should address the concerns you had.

**Comment by bradcray** [comment]
Looks good to me.  I think this is good to merge once the automated tests complete successfully.

**Comment by vasslitvinov** [comment]
@Maxrimus what is your sense why we haven't discovered the 0-vs-1 issue earlier?

**Comment by bradcray** [comment]
I didn't add any testing to cover this case, so the code paths in question were untested in our nightly runs.  I was surprised to find this, and am not sure why I didn't.  Probably sheer laziness or lack of time.

**Pull request merged**
