### PR TITLE
Make stdout, stderr ordering predictable in test output.

### PR DESCRIPTION
**Pull request by gbtitus**
We've been running tests with their stderr redirected to the same pipe
as their stdout.  As a result, for tests that produce some of both, such
as ones that test execution-time error messages, the order in which
these two are combined depends on a variety of things including libc and
launcher buffering settings and in some cases launcher pipe combining.
Here, arrange to produce stdout and stderr into separate pipes and
combine them into the test output file after the test completes, with
output from stdout preceding that from stderr.

This resolves several failures in chapcs comm=ofi full testing which
were caused by the mpirun4ofi launcher combining stdout and stderr in a
different way than did gasnet amudprun, whose output has become our
canonical "good" result).  errhandling/ferguson/throws-destroys is an
example of such a test; its .good file contains both stdout output from
the test and the stderr result of an error being thrown but not caught.

### CODE REVIEW

**Comment by ronawho** [comment]
Hmm, so this is a little weird in that if you manually run a test and diff the output it won't match the .good. But I suppose that was already possible depending on what launcher is being used.

**Comment by gbtitus** [comment]
> Hmm, so this is a little weird in that if you manually run a test and diff the output it won't match the .good. But I suppose that was already possible depending on what launcher is being used.

Yes, both those things are true.  That's already been an issue with comm=ugni and now ofi, though plain old different output was a more common problem.  Hopefully this change won't bother too many folks too often.

**Comment by gbtitus** [comment]
> Hmm, so this is a little weird in that if you manually run a test and diff the output it won't match the .good. But I suppose that was already possible depending on what launcher is being used.

Based on a simple `grep -w sort | wc -l` of all the `PREDIFF` and `.prediff` files, as many as 154 of the tests sort the output before comparing, and none of those will match the `.good` in a manual run either.  :-)

**Comment by gbtitus** [comment]
I think this one is done now, if you want to take a final look including the test changes.

**Comment by ronawho** [comment]
>> Hmm, so this is a little weird in that if you manually run a test and diff the output it won't match the .good. But I suppose that was already possible depending on what launcher is being used.

> Based on a simple grep -w sort | wc -l of all the PREDIFF and .prediff files, as many as 154 of the tests sort the output before comparing, and none of those will match the .good in a manual run either. :-)

Yeah, that's a good point.

**Pull request merged**
