### PR TITLE
Replace segfault due to applying 'override' to a non-method with an error

### LINKED ISSUE #19249: Internal Error: Segmentation Fault due to `override` on a nested function
When missing a bracket, which is really easy to do in very large code, there are circumstances where the compiler shows undefined behavior. In this case, it will result in a segmentation fault, ~~but in other cases I had false compiler errors due to, as mentioned, undefined behavior~~ (undefined behavior is likely well-defined behavior but confusing to understand due to misplaced brackets). This MWE reproduces the issue, but can easily show up in larger codes, as it showed up in mine.

```chpl
module M {
  class X {    
    proc Y() {
      if (true) {
        if (true) {
        } else {
      }
    }

    // Must be `override`!
    override proc Z() {}
  }
}
}
```

[TIO](https://tio.run/##bY2xDoMwDET3fMV1owPiS9hpJ9LEtEiugmLCgvLrpCSIdulZOsvvZJ156Yk4pbezgQktVgUY1iLosGKXyjZ5Z3CrriXOGgdUsw/0I/9ZBLHQF0R1eFlNgzbIjAehdwt5P1rqLyU6z6P4novza1T7pLSZgfVTUl1bWog/)

**Output:**

```
internal error: seg fault [util/misc.cpp:921]
```

### PR DESCRIPTION
**Pull request by bradcray**
As things stood, the compiler assumed that `override` would only
be applied to methods, which led to a segfault when it was not.
This replaces that segfault with a user-facing error message.

Resolves #19249

### CODE REVIEW

**Comment by bradcray** [comment]
@dlongnecke-cray : It looks like you were the last one to work in this part of the code (which is not to suggest that the bug was yours).  Would you mind reviewing it?

(I'm giving myself a 1, 1, 5 on the 7-point size/complexity/pride scales)

**Review by dlongnecke-cray — APPROVED** [review]
I'm not sure if we'd want to consider a place earlier than virtual dispatch to put this check (like maybe `checkParsed`? would that even be possible?), but I'm OK with putting it here.

**Comment by bradcray** [comment]
@dlongnecke-cray : Good idea, want to take another look?  (I left the later check in because I figure a duplicate check is preferable to a segfault if something slips past the first check—e.g., maybe I don't have all cases covered properly for some reason).

**Comment by dlongnecke-cray** [comment]
Awesome! Glad we can fail earlier in most (all?) cases.

**Pull request merged**
