### PR TITLE
Add tests showing problems with fully qualified 'new' expressions

### PR DESCRIPTION
**Pull request by bradcray**
Here, I'm adding four tests that all have the characteristic of using
fully-qualified new expressions: 'new moduleName.typeName()`.

The first two of these capture working and non-working cases that were
identified on issue #8555 but never captured as tests:

* qualifiedTypeAndNew.chpl   (doesn't work)
* qualifiedNew.chpl          (works)

The next two capture a different issue reported by Brian Rogoff in
which a module and type share the same name (filed as new issue
#8709):

* modTypeShareName.chpl (doesn't work)
* modTypeDiffName.chpl  (works)

### CODE REVIEW

**Comment by bradcray** [comment]
@lydia-duncan, @cassella, @bryantlam: In this PR, I'm filing a future against the problem Bryant identified in #8555 as well as a related one that showed up on email (and working variants of each).

**Comment by lydia-duncan** [comment]
Did you double check the working test cases against those used in the issues I referenced on #8555?

**Comment by bradcray** [comment]
No.  Do you mean from the perspective of "do we already have a test that covers this case?"

**Comment by lydia-duncan** [comment]
> Do you mean from the perspective of "do we already have a test that covers this case?"

Yeah.  Since a variant was fixed a while back, it seems reasonable that some tests for the specific cases that work already exist

**Comment by bradcray** [comment]
True.  I generally don't think it's worth a lot of developer time to try and determine whether tests for user-submitted bugs are pre-existing or not.  And as we all know, it doesn't take that much of a delta between two tests to make one work when another doesn't.  My filing of the working tests was only intended to provide a point of comparison for the .futures (and is also how I generated their .good files).

**Comment by lydia-duncan** [comment]
Agreed, and I'm not against having duplicate tests.  Was just pointing it out as a quick way to have maybe saved you some work since I had the link handy, but I think it is too late for that now so I don't think it's worth dwelling on further.

**Pull request merged**
