### PR TITLE
Improve _expBySquaring algorithm in LinearAlgebra

### PR DESCRIPTION
**Pull request by Aniket21mathur**
With respect to #5753

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@ben-albrecht please have a look thanks!

**Comment by Aniket21mathur** [comment]
| size  | power | master | Fix5753 |
| ------------- | ------------- | ------------- |------------- |
| 10  | 10  |4.1e-05|2.5e-05|
| 10  | 50  |3.2e-05|4.3e-05|
| 10  | 100|5.3e-05|4.2e-05|
| 50  | 10  |0.000847|0.001178|
| 50  | 50  |0.001266| 0.000953|
| 50  | 100|0.002236|0.000682|
| 100  | 10  |0.005843| 0.004011|
| 100  | 50  |0.010207|0.008127|
| 100  | 100  |0.006647|0.010991|
| 1000  | 10  |4.12296|4.58344|
| 1000  | 50  |5.22676|6.78985|
| 1000  | 100  |5.95839|7.52467|
| 2000  | 10  |24.9314|36.7869|

The master branch still seems to have better complexity, but conversion to iterative from recurssion should have reduced complexity, @ben-albrecht are there any other factors that are affecting the time taken?

**Comment by ben-albrecht** [comment]
There may be a bug in your implementation that needs to be addressed first -- I see this failure for:

```sh
start_test test/library/packages/LinearAlgebra/correctness/correctness.chpl
...
> Test Failed: matPow(A, 3)
> 36.0 72.0 108.0
> 36.0 72.0 108.0
> 36.0 72.0 108.0
> !=
> 3.62797e+08 7.25594e+08 1.08839e+09
> 3.62797e+08 7.25594e+08 1.08839e+09
> 3.62797e+08 7.25594e+08 1.08839e+09
> correctness.chpl:885: error: halt reached - Sparse arrays can't be zippered with anything other than their domains and sibling arrays (CS layout)
```

**Comment by ben-albrecht** [comment]
@Aniket21mathur - as one other sanity check, are you compiling with optimizations on, i.e. `--fast`? 

Also, are you using a version of BLAS or are you compiling without BLAS?

**Comment by Aniket21mathur** [comment]
> @Aniket21mathur - as one other sanity check, are you compiling with optimizations on, i.e. `--fast`?

yes, I am compiling with --fast.

> Also, are you using a version of BLAS or are you compiling without BLAS support (for `dot()`)?

Yes, I am using a version of Blas, compiling with

`chpl -lblas -llapack -llapacke --fast pwrTest.chpl`

**Comment by Aniket21mathur** [comment]
> Also, are you using a version of BLAS or are you compiling without BLAS support (for `dot()`)?

@ben-albrecht what difference this makes? As the tests, we are performing (as  indicated by you to be in test/library/packages/LinearAlgebra/correctness/correctness.chpl ) seems to be actually present in 
test/library/packages/LinearAlgebra/correctness/no-dependencies/correctness.chpl and are not dependent on BLAS/LAPACK.

**Comment by ben-albrecht** [comment]
> what difference this makes? 

@Aniket21mathur - it changes if using the third party BLAS library for matrix multiplication vs. the Chapel implementations.

> As the tests, we are performing (as indicated by you to be in test/library/packages/LinearAlgebra/correctness/correctness.chpl ) seems to be actually present in
test/library/packages/LinearAlgebra/correctness/no-dependencies/correctness.chpl and are not dependent on BLAS/LAPACK.

Right. Many LinearAlgebra functions can use a backend BLAS/LAPACK implementation or native Chapel implementation depending on the compiler flags passed. The `no-dependencies` subdirectory disables backend BLAS/LAPACK implementations.

**Comment by Aniket21mathur** [comment]
@ben-albrecht I did some workaround

The matrix for which the test is failing is 

```
1 2 3
1 2 3
1 2 3
```
Like I did in [this comment](https://github.com/chapel-lang/chapel/pull/15145#issuecomment-599342456), I manually compiled the test case for the above matrix with and without `BLAS/LAPACK `.

Code ->

```
use LinearAlgebra;


const v1 = [1,2,3];
var A = Matrix(v1,v1,v1, eltType=real);

var B3 = matPow(A, 3);
writeln(B3);

writeln();
const v3 = [36, 72, 108];
const A3 = Matrix(v3,v3,v3, eltType=real);
writeln(A3);
```
Without `BLAS/LAPACK ` -> `chpl  --set blasImpl=off --set lapackImpl=off test.chpl`

```
36.0 72.0 108.0
36.0 72.0 108.0
36.0 72.0 108.0

36.0 72.0 108.0
36.0 72.0 108.0
36.0 72.0 108.0
```
With `BLAS/LAPACK` -> `chpl -lblas -llapack -llapacke test.chpl`

```
36.0 72.0 108.0
36.0 72.0 108.0
36.0 72.0 108.0

36.0 72.0 108.0
36.0 72.0 108.0
36.0 72.0 108.0
```
Both of these cases seem to give the expected results.
The block of code for the failing test case is 

```
  {
    // Real domains
    var D = CSRDomain(3,3);
    for ii in 1..#3 do D += (ii,ii);

    var A = CSRMatrix(D, real);
    for ii in 1..#3 do A[ii,ii] = ii;
    var B = matPow(A, 3);
    for ii in 1..#3 do assertEqual(B[ii,ii],(ii**3),
                                   "Error in matPow with sparse matrices : real");
  }
```
I am not sure why I am not getting any error in my example, is there any difference between the input matrices to matPow in my example and the original test case?

Thanks!

**Comment by ben-albrecht** [comment]
@Aniket21mathur - thanks for investigating. I think the previous implementation supported both sparse and dense arrays, but the new algorithm does not support sparse arrays.

For this PR, you could do one of the following:

- Create a separate overload for sparse arrays only that still uses the old algorithm
- Get the algorithm working with sparse arrays (it's not yet clear to me how difficult that is)

Thanks!

**Comment by Aniket21mathur** [comment]
> but the new algorithm does not support sparse arrays.

@ben-albrecht any way to find out why this is happening exactly?

> For this PR, you could do one of the following:

**Comment by ben-albrecht** [comment]
> I think it will be better to go with the second way if somehow we can figure out how to do that. What do you say?

Given that we still need to iron out performance issues, I'd suggest the former option in order to keep this PR scope smaller:

> Create a separate overload for sparse arrays only that still uses the old algorithm

Adding sparse support would be a great follow-up PR.

**Comment by ben-albrecht** [comment]
@Aniket21mathur - I'd be interested in seeing this PR reach completion but am going to close for now until you have time to return to it.

**Comment by Aniket21mathur** [comment]
> @Aniket21mathur - I'd be interested in seeing this PR reach completion but am going to close for now until you have time to return to it.

Sure :)

**Pull request closed without merging**
