### PR TITLE
Add the disable flag to disable warning. 

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
Add a disable warning flag to disable Intel compiler compatibility warning message.

The warning is seen on this test run.

https://chapel-ci.us.cray.com/job/cray-module-performance-cray-xc-single-locale/CHPL_LAUNCHER=slurm-srun,COMMUNICATION=none,COMPILER=intel,LOCALE_MODEL=flat,label_exp=horizon/744/console

icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.

### CODE REVIEW

**Review by ronawho — COMMENTED** [review]
Does not seem to be sufficient to quiet the warnings:

```
chapel (bhavanijayakumaran-disable_diag) $ chpl examples/hello.chpl
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Copiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
```

**Comment by bhavanijayakumaran** [comment]
> Does not seem to be sufficient to quiet the warnings:
> 
> ```
> chapel (bhavanijayakumaran-disable_diag) $ chpl examples/hello.chpl
> icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
> icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
> icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Copiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
> icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
> ```

Looks like we need to add -wd to disable warning.
Looked at an example 
remark #177: variable 'x' was declared but never referenced
To disable warning #177, use the -wd option:

I will test it in horizon and will update the thread if the flag works.

**Comment by ronawho** [comment]
I haven't been following slack threads on this. Was this reviewed and does it quiet any of the warnings we're seeing?

**Comment by ronawho** [comment]
Offline discussed that this was an accidental merge. @bhavanijayakumaran can you revert this?

**Comment by bhavanijayakumaran** [comment]
Yes, I will revert this.

**Comment by bhavanijayakumaran** [comment]
@ronawho the Makefile.Intel in main does not have these changes
https://github.com/chapel-lang/chapel/blob/main/make/compiler/Makefile.intel.

The disable flags were removed  as part of another PR (upgrade upload-artifact to v3. changed-files to 34)

**Comment by ronawho** [comment]
> @ronawho the Makefile.Intel in main does not have these changes
https://github.com/chapel-lang/chapel/blob/main/make/compiler/Makefile.intel.

> The disable flags were removed as part of another PR (upgrade upload-artifact to v3. changed-files to 34)

Ok. We generally try to have PRs cover a single topic, so going forward I think we don't want to be mixing multiple changes into one PR (especially if the change isn't called out in title / PR description)

**Pull request merged**
