### PR TITLE
Replace most occurrences of regexp with regex, preserving case

### PR DESCRIPTION
**Pull request by leekillough**
This PR deprecates the `Regexp` module in favor of `Regex`.

It deprecates the `regexp` record type in favor of `regex`.

It deprecates the `reMatch` record type in favor of `regexMatch`.

It deprecates the `BadRegexpError` class type in favor of `BadRegexError`.

It adds the `fullMatch()` method for anchoring at the beginning and end.

It renames internal functions and types with `regex` instead of `regexp`, preserving case.

It does not change the `CHPL_REGEXP` variable, the `REGEXP`-associated `Makefile` variables, or the names of directories which contain `regexp`, because that would be too disruptive, and might affect builds on different platforms differently.

Fixes: https://github.com/chapel-lang/chapel/issues/17224 
Fixes: https://github.com/chapel-lang/chapel/issues/17222
Fixes: https://github.com/chapel-lang/chapel/issues/17216

This PR found https://github.com/chapel-lang/chapel/issues/17275, worked around with @mppf's [suggestion](https://github.com/chapel-lang/chapel/pull/17276#issuecomment-786881279) below. Without the workaround, the deprecated test case produces:
```
$CHPL_HOME/modules/standard/Regexp.chpl:23: warning: 'Regexp' module is deprecated; please use 'Regex' module instead.
test/deprecated/Regexp-module.chpl:4: warning: Regex: 'BadRegexpError' is deprecated; please use 'BadRegexError' instead
test/deprecated/Regexp-module.chpl:4: warning: Regex: 'BadRegexpError' is deprecated; please use 'BadRegexError' instead
test/deprecated/Regexp-module.chpl:7: warning: Regex: 'regexp' is deprecated; please use 'regex' instead
test/deprecated/Regexp-module.chpl:8: warning: Regex: 'reMatch' is deprecated; please use 'regexMatch' instead
internal error: seg fault [util/misc.cpp:889]
```
With the workaround for https://github.com/chapel-lang/chapel/issues/17275, the deprecation messages for `BadRegexpError` do not appear, but the test case compiles and runs okay.

### CODE REVIEW

**Comment by mppf** [comment]
We can untie this effort from #17275 if we deprecate `BadRegexpError` in a different way.

I think we could write
``` chapel
type BadRegexpError = BadRegexError;
```

(in which case, we don't deprecated BadRegexpError at all, but maybe that is OK given the other deprecations, maybe people will figure it out, or we could deprecate it later).

That's probably worth doing in the short term. #17275 does not look particularly trivial to fix but I haven't dug into it deeply.

**Review by mppf — APPROVED** [review]

**Comment by leekillough** [comment]
There was one memleak failure but I merged the fix from https://github.com/chapel-lang/chapel/pull/17345.

I'm squashing my commits and rerunning `paratest` before I merge.

**Comment by leekillough** [comment]
Apparently the changes related to #17345 and related were all done before the renaming done in this PR, so I am going to have to pick apart the source files and figure out the essential changes and rename them all from regexp to regex.

**Comment by bradcray** [comment]
Too late for this one, but in future PRs, don't forget to mention who reviewed the PR in the merge message so that it goes into the git repo's log and the merge mail.

**Pull request merged**
