### PR TITLE
reduce intents: different input/state/output types

### PR DESCRIPTION
**Pull request by vasslitvinov**
When specifying a reduce intent, allow specifying the input type
for the reduction operation. The output type is the type of the
outer variable. The shadow variable has the type of the accumulation
state, which is determined implicitly by the 'identity' method
of the ReduceScanOp subclass being used with the reduce intent.

See #4565 for detailed discussion.

The input type is specified as an argument to the reduction class
in the reduce intent, e.g.:

    forall ... with (MyReductionOp(int) reduce x) ....

I implemented this via explicit support in setupOneReduceIntent().
It builds a call to create a new instance of a reduction op class,
like MyReductionOp above. If the code passes an argument to the class,
then its eltType is taken to be that argument. Otherwise its eltType
is taken to be the type of the outer variable, as before.
If <1 or >1 argument, I report an error.

Also, I now avoid setting the shadow variable's type explicitly in
implementForallIntents.cpp / createShadowVars(). That way its type
is determined by the reduce op class and can differ from the outer
variable's type.

Added tests.

Added an example to reduceIntents.rst.
While there, fixed an omission of 'ref' arg intent in reduceIntents.rst.

### CODE REVIEW

**Comment by benharsh** [comment]
This looks reasonable enough to me. What testing have you done?

**Comment by vasslitvinov** [comment]
Full linux64 testing passes.

**Comment by mppf** [comment]
@vasslitvinov - What if, for example, I'd like my reduction to be generic on a type or param that is not the input type? (E.g. suppose the reduction takes in a param that is used to tune the computation, but does not affect input or output types). Did that work before? Does it work now?

**Comment by vasslitvinov** [comment]
@mppf - this neither worked before nor works now. One way to support your scenario is by allowing reductions and reduce intents on already created objects, e.g.:

const op = new MyReductionOp(.....);
writeln(op reduce SomeExpression);

This is a feature we would like to add in the future (and btw it should help us implement partial reductions).

**Pull request merged**
