### PR TITLE
Disable remote cache if address sanitizer is enabled

### PR DESCRIPTION
**Pull request by ronawho**
The cache reads whole cache lines at a time, even if only part of the
line is allocated. This is an intentional design choice, but it is
technically reading unallocated memory, which is one of the things ASan
catches. For now just disable the cache if asan is enabled. See
https://github.com/Cray/chapel-private/issues/933 for more info.

This also adds warnings if the cache was requested but can't be used.
This includes warning for Asan and if tasks can migrate threads, which
isn't support because the cache relies on thread local storage.

These warnings can be quieted by compiling with `--no-cache-remote`,
executing with `--quiet` (which is a big hammer), or by setting
`CHPL_RT_CACHE_QUIET=true`. Use `CHPL_RT_CACHE_QUIET=true` in our gasnet
ASan and numa configurations in prep for cache remote being enabled by
default

### CODE REVIEW

**Review by mppf — APPROVED** [review]
I think this is OK but I wonder if people will be confused why their communication behavior changes when using asan? Maybe we could fail with an error about it being an unsupported configuration instead?

**Comment by ronawho** [comment]
> I think this is OK but I wonder if people will be confused why their communication behavior changes when using asan? Maybe we could fail with an error about it being an unsupported configuration instead?

I considered this, but thought it'd be more annoying to get an error that tells you to recompile with `--no-cache-remote`. I can poll the group if you think it's worth getting some other opinions.

**Comment by e-kayrakli** [comment]
> I considered this, but thought it'd be more annoying to get an error that tells you to recompile with --no-cache-remote.

Won't this be a compile-time error?

**Comment by lydia-duncan** [comment]
I vote for an error

**Comment by e-kayrakli** [comment]
I'd be more in favor of an error if `--cache-remote` was an optional flag, but as we are making it on by default, I can see that it may be annoying, too. Brad's suggestion of disable-and-warn seems reasonable to me.

**Comment by ronawho** [comment]
>> I considered this, but thought it'd be more annoying to get an error that tells you to recompile with --no-cache-remote.

> Won't this be a compile-time error?

Yeah, we can probably make it a compile time error. 

> I'd be more in favor of an error if --cache-remote was an optional flag, but as we are making it on by default, I can see that it may be annoying, too. Brad's suggestion of disable-and-warn seems reasonable to me.

This was my thought too. An error would mean you'd always have to throw `--no-cache-remote` when using Asan, which seemed cumbersome (both for manual runs and for paratests). 

A warning would also mess up start_test/paratest, but maybe we can add some env var to quiet the warning?

**Comment by e-kayrakli** [comment]
> A warning would also mess up start_test/paratest, but maybe we can add some env var to quiet the warning?

Maybe we can make them throw `--no-cache-remote` under the covers, but generate a warning themselves, either in the beginning or at the end of the run. But I don't mind supressing the warning with an env flag either. I'd probably set that in my bashrc.

**Comment by mppf** [comment]
I'd lean towards making it a warning and just not running nightly testing in a configuration that triggers the warning (i.e. our testing config adds `--no-cache-remote` when doing muiltilocale asan testing).

**Comment by ronawho** [comment]
I added a warning if the cache is disabled because ASan is in use (I also added a warning if we disable it because tasks can migrate threads, which we used to do silently.) 

These warnings can be quieted through the normal means (compiling with `--no-cache-remote`, running with `--quiet`) and I also added a `CHPL_RT_CACHE_QUIET` env var to make it easier to quiet the warnings for nightly testing and dev paratests without having to remember to throw compiler flags or use `--quiet`, which is a big hammer.

**Review by mppf — APPROVED** [review]

**Pull request merged**
