### PR TITLE
Update README.chpldoc with info about documenting Chapel modules.

### PR DESCRIPTION
**Pull request by thomasvandoren**
Update README.chpldoc to describe modern chpldoc and info about writing
documentation, in particular for the standard modules.

Remove doc/developer/bestPractices/Documenting.rst and move the useful
information to README.chpldoc.

Updates include:

* Rename file README.chpldoc -> README.chpldoc**.rst**, and use markup
  within the file.
* Modernize instructions for building chpldoc and obtaining its prerequisites.
* Add info about building the documentation for the standard modules.
* Update info about generating documentation for ad-hoc Chapel modules.
* Add reStructuredText primer (from Documenting.rst).
* Add specific examples about documenting arguments, argument types,
  return values and types, and yield values and types.
* Add section about how chpldoc works (from Documenting.rst).
* Update future directions section to be current.

The best way to view the new README.chpldoc file is with github's rendering:

https://github.com/thomasvandoren/chapel/blob/chpldoc-readme/doc/release/technotes/README.chpldoc.rst

Once merged, that will become:

https://github.com/chapel-lang/chapel/blob/chpldoc-readme/doc/release/technotes/README.chpldoc.rst

The "Documenting Chapel code" section is intended for Chapel developers documenting the standard modules. See: 

https://github.com/thomasvandoren/chapel/blob/chpldoc-readme/doc/release/technotes/README.chpldoc.rst#documenting-chapel-code

### CODE REVIEW

**Comment by thomasvandoren** [comment]
@mppf -- will you please review?

**Comment by mppf** [comment]
This section needs fixing:

For the Chapel roles, if you prefix the content with ~, the link text will only be the last component of the target. For example, :meth:`~Random.RandomStream.fillRandom` will refer to Random.RandomStream.fillRandom but only display fillRandom as the link text.

I don't see :meth: anywhere. Is it a synonym for :proc? Could you add it to the list? Also we talked about :sym:. Does that work? Lastly I thought we decided that we didn't need the :chpl: part for these?

**Comment by mppf** [comment]
In the section Documenting argument, return, and yield values and types - I would really like to see a second note about leaving a space before/after the arguments/returns section since that was really difficult for me to figure out... I see it's mentioned above but I'd like it in both places.

**Comment by mppf** [comment]
I've finished looking at this. Once you take my comments into account - please go ahead! Thanks for fixing it up.

**Comment by thomasvandoren** [comment]
:meth: is a synonym for :proc: and :iter:, but I think we decided we want people using :proc: and :iter:. I removed :meth: from this documentation. Good catch!

I think :any: is what we want to use once Sphinx 1.3 is released (currently in beta 3 release). I can create an arbitrary role, like :sym:, but I'd just assume wait for :any: since the roles are not very strict today (i.e. I think most roles can cross-reference most symbols). 

Good catch on the arg/returns spacing note. I added it to the other section.

Thanks!

**Pull request merged**
