### PR TITLE
Update main_launcher.c and launch-slurm-srun.c in runtime/

### PR DESCRIPTION
**Pull request by noakesmichael**
A recent change in the lustre file system tickled 2 known file path truncation bugs; 1 in the installed
version of slurm and one in main_launcher.c.  Both bugs limit a path to char[256]. This bug is surfaced
on 1 test in 3 nightly configurations.

The slurm bug is related to the challenges of using getcwd() on modern Unix filesystems that
support very long paths.  If the Chapel host program is invoked with a relative path then we
will call srun/sbatch with a relative path to the node app.   Slurm sbatch/srun need a fully
qualified path and so invoke getcwd().  Unfortunately that function is poorly-defined and then
slurm uses it in an ineffective way.  I have not fully addressed the underlying problem but I've
updated the failure to be 4,096 rather than 256.

Once our portion of the slurm driver is generating a long path we tickled a trivial limit of char[256]
in main_launcher.c.  This limit is trivially addressed by using malloc().  BenH also pointed out a
second place that used a fixed buffer and that might see a fully-qualified path and so I also converted
that to use malloc().

The implementation of the C portion of the launchers is not entirely obvious esp. as functionality
is partitioned between runtime/src/main_launcher.c and then bodies of code that are specialized
for each launcher configuration.  Some of the code is pretty crusty and there were few comments.

It took me an unreasonably long time to figure out what was going on even for the cases I was
interested in.  I therefore elected to apply my learning to the codebase.  I performed a significant
amount of 'whitespace' cleanup, added comments, and *then* fixed the buffer bugs.  However this
means a naive git diff would simply flag everything as different.

And that what you'll see if you simply browse the 3 files with changes.  To help to manage this
I converted the PR in to an unreasonably large number of commits.  Most commits are prefixed
with the tag "Whitespace".  These are trivial changes to e.g. trim trailing whitespace, reformat
for 80 chars, standardize the syntax based on the prevalent convention, etc, etc.  In most cases
these changes could not have any impact on behavior.  In a few cases it would be possible to
alter behavior if one were clumsy, but there was no intent to alter behavior.  There's a painful
number of commits but they can be scanned very quickly or you can choose to "trust me".

A handful of commits are not tagged with whitespace.  These are the actual changes in
business logic to address the buffer issues.  Even these are broken in to several steps to
help make it more clear what is being changed.

This PR has been compiled on clang/darwin, gcc/linux64, and gcc/PrgEnv-gnu both with and
without CHPL_DEVELOPER set.

Basic testing was performed on clang/darwin/gasnet by creating an app in a test dir that had
a very long path,  and then on Jupiter by cloning a repository that is located at the bottom of
a very long path under /lus/scratch/.  For Jupiter I eventually ran all of release/examples with
both PrgEnvGnu and PrgEnvCray.

As a final sanity check I did a paratest in my standard repository on the chap?? boxes for
gasnet.  This does not test the slurm changes but it does help to exercise main_launcher.c

### CODE REVIEW

**Comment by ronawho** [comment]
Hey Mike,

Normally I'm in favor of your whitespace changes, but I think this is too much. If this was compiler code I might not object so much, but the runtime code has it's own style, and I think it'd be weird to have 3 files look pretty different with all the forward declarations and other style choices that have been made here. The number of commits making whitespace changes also makes me a little nervous since it'll make looking through the git history difficult.

It's possible that some of the commits actually do nice cleanups, but I gave up looking through them around commit 4 so maybe I didn't make it to those :)

**Comment by noakesmichael** [comment]
On Nov 29, 2016, at 7:53 AM, Elliot Ronaghan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Mike,

Normally I'm in favor of your whitespace changes, but I think this is too much. If this was compiler code I might not object so much, but the runtime code has it's own style, and I think it'd be weird to have 3 files look pretty different with all the forward declarations and other style choices that have been made here. The number of commits making whitespace changes also makes me a little nervous since it'll make looking through the git history difficult.


I understand the point you are making.  However it’s
clear that cleaning up legacy code issues is incompatible
with minimizing deltas for code-reviews / preserving git
history.



The interactions between main_launcher.c and the
specialized launchers, e.g. launch-slurm-srun.c, are
not readily apparent given the “callback structure”.
It was presumably manageable at first but grew a
little unwieldy over time as more options were needed
for the variety of launchers.  But there was never
time to refactor and there’s the constant “delta” problem.

On master there’s no particular organization within either
file and there are almost no comments.   And then there’s
lines that wrap beyond 80 chars, inconsistent syntax within
the file, etc, etc.

The files are small enough that it’s not too bad for someone
who is familiar with these files but it’s unnecessarily hard for
someone who is unfamiliar with the launcher to jump in and
fix something.  I’ll be back to zero on understanding these
files in just a handful of weeks.



I attempted to manage this conundrum by “showing my
work” through a large series of tiny commits.  But that
means it’s hard to look at such a large number of tweaks
esp. via the GIT delta interface.



I see three options

1) I can throw the “cleanup” away and then re-introduce only
the buffer fixes.  Of course I think this would be regrettable.

2) I can do 2 PRs; one with the “trivial” non-functional changes
and a second with the buffer fixes (in either order).  Though
even the fixes for the buffer bugs could be argued as being
“trivial”.

3) A reviewer could focus on those commits that are not tagged
with “whitespace” or “trivial”.


Mike





It's possible that some of the commits actually do nice cleanups, but I gave up looking through them around commit 4 so maybe I didn't make it to those :)

**Comment by daviditen** [comment]
I agree with @ronawho .  The "Whitespace" changes here are a bit out of control.  I think you should do either option 1 or option 2.  If you pick option 2, the "Whitespace" commits should be merged into a single commit with a good commit message, and it should have a review.

**Comment by gbtitus** [comment]
I agree with @ronawho and @daviditen as well.  I'm sympathetic to the need for a rewrite.  The launchers are perhaps our best example of "unowned" code : a variety of people have worked on them but many of those (including me) were not all that familiar with what was going on and there wasn't a strong-willed owner willing to act as enforcer, stylistically or otherwise.  Further, much of the launcher code was done before we had much in the way of reviews anyway.  So in a lot of ways they're a mess.  However, a point in favor of the current code is that later launchers, including this one, have generally been built by modifying copies of earlier ones.  Thus they tend to have a lot of code (including idiosyncracies of course) in common, so that working on or reading one launcher makes it easier to do the same with others. This change to the launcher main and one specific launcher will make them different from all the others and, as @ronawho mentioned, different also in some ways from the rest of the runtime.  So the overall effect is to introduce yet another coding style into a set of source files that already suffer from too many.  Until we're ready to embark on a complete rewrite of the launch mechanism (which is something we've discussed), I'd prefer we not do this.

(Having said all this, I should also note that I haven't looked at the non-structural changes yet, because I've been working on another, unrelated problem.  I'll try to get to those soon.)

**Comment by noakesmichael** [comment]
It is easy to acknowledge that this PR didn’t turn out as well as I hoped.


I continue to believe that a solid update is appropriate and but recognized
that this can be challenging to review given the limits of “git diff” etc.  I made
an attempt to break it in to a lot of small commits so that it was clear what
every change was but then ended up with an unreasonable number of
commits; as indicated in the PR message and the note that I sent to Greg.

I have a strong preference for option 2 over option 1 and agree that the
“cleanup” PR should be limited to a very small number of commits. I would
be inclined to do it after (a) fixing the buffer truncation bug (b) the other slurm
change that Tony has pointed out.  But I sense I may be alone in preferring
this path.


Thanks,

Mike







On Nov 29, 2016, at 10:34 AM, Greg Titus <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree with @ronawho<https://github.com/ronawho> and @daviditen<https://github.com/daviditen> as well. I'm sympathetic to the need for a rewrite. The launchers are perhaps our best example of "unowned" code : a variety of people have worked on them but many of those (including me) were not all that familiar with what was going on and there wasn't a strong-willed owner willing to act as enforcer, stylistically or otherwise. Further, much of the launcher code was done before we had much in the way of reviews anyway. So in a lot of ways they're a mess. However, a point in favor of the current code is that later launchers, including this one, have generally been built by modifying copies of earlier ones. Thus they tend to have a lot of code (including idiosyncracies of course) in common, so that working on or reading one launcher makes it easier to do the same with others. This change to the launcher main and one specific launcher will make them different from all the others and, as @ronawho<https://github.com/ronawho> mentioned, different also in some ways from the rest of the runtime. So the overall effect is to introduce yet another coding style into a set of source files that already suffer from too many. Until we're ready to embark on a complete rewrite of the launch mechanism (which is something we've discussed), I'd prefer we not do this.

(Having said all this, I should also note that I haven't looked at the non-structural changes yet, because I've been working on another, unrelated problem. I'll try to get to those soon.)

**Pull request closed without merging**
