### PR TITLE
Improve how we create string/bytes internally

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR mainly improves how we internally create strings and to some extent
bytes.

#15758 added a `cachedNumCodepoints` field in the string record to avoid
computing that value on-demand. However, it also opened a can of worms about how
we create strings. In general, that involved default initing a string and poking
its fields. So, although the main motivation for this PR is to make
`numCodepoint` management better, it has bunch of other changes that are related
to that to different extents.

More or less in the order of significance, this PR does the following.

- Strengthen our management of `cachedNumCodepoints`
  - Add the argument to all non-validating string factory functions to force the
    caller to pre-compute the value either by counting it, or doing something
    smart about it.
  - Update quite a few helpers to try to produce this value efficiently
  - Update `getView` to return a tuple that contains number of codepoints in the
    view, if it is something that's easily computable.
  - Add 2 `countNumCodepoints` overloads to check whether `cachedNumCodepoints`
    is correct with `boundsChecking`
  - Serialize/deserialize that field
- Make `c_string` to `string` assignment use appropriate factory functions
  instead of `reinitString`.
- Remove `reinitString` from `string` and `bytes` in favor of
  `reinitWithNewBuffer` and `reinitWithOwnedBuffer` in `BytesStringCommon`
- Change the strategy of creating string and bytes in functions in
  `BytesStringCommon` and few other similar ones.

<details>
<summary> Details about this strategy </summary>
  We used to do something like:

```chapel
var ret: string;
ret.isOwned = true;
ret.someOtherField = otherValue;
ret.yetAnotherField = 0;

// ..

return ret;
```

  This was too cumbersome and felt principally wrong to me. With this PR we
  compute what we need to compute to create new string's (1) buffer, (2)
  bufferSize, (3) bufferLength and (4) numCodepoints, and then call a factory
  function. I hope this'll help reduce the overhead of adding new fields to
  the string record.
</details>

- Fix a few bugs where the helpers attempted to return a `string` if the main
  argument in question was an empty `bytes`.
- Add an optimization to `getView` for the cases where the view we are trying to
  get is actually the full string
- Remove an internal cast to c_string to enable using explicit `bufferType` as
  an arg type in `bufferMemcpyLocal`
- Update string and bytes doc to render references to types as "string" and not
  as "String"
- Add tests

Test:
- [x] memleaks on string/bytes tests
- [x] ml-memleaks on string/bytes tests
- [x] valgrind on string/bytes tests
- [x] string performance is back where we want it to be (if not better)
- [x] full standard
- [x] full gasnet

### CODE REVIEW

**Comment by cassella** [comment]
The first line of the second paragraph of the PR description says

> added a cachedNumCodepoints field int the string record

One of 
  s/int/in/
  s/int/to/
  s/field int/int field to/
?

**Comment by e-kayrakli** [comment]
@cassella -- s/int/in :) Fixed, thanks!

**Comment by e-kayrakli** [comment]
This PR is ready to go in but there is one design-y aspect that I want to get a green light on.

@bradcray and/or @mppf -- With this PR, `numCodepoints` will count the number of codepoints everytime it is called and check it against the cached value with `boundsChecking`. It'll halt if the counts don't match. This check will not occur without `boundsChecking`. I was thinking this could be a good way to protect the integrity of the string metadata without incurring execution time costs. What do you think?

**Comment by bradcray** [comment]
I can live with that, though I'd also probably look forward to a future day in which numCodepoints requires an opt-in to do the check once the string implementation is not undergoing much flux and we have a great deal of confidence that it's correct.

**Comment by mppf** [comment]
The boundsChecking check is fine with me for now.

**Pull request merged**
