### PR TITLE
Do not give c_void_ptr FLAG_IGNORE_NOINIT

### PR DESCRIPTION
**Pull request by mppf**
I added FLAG_IGNORE_NOINIT to c_void_ptr in #2743, but that was probably
not a good idea. Generally I want c_void_ptr to be initialized, but
there's not really a problem with it not being initialized and then being
PRIM_MOVE'd into... so I don't think that type needs FLAG_IGNORE_NOINIT.

This patch removes FLAG_IGNORE_NOINIT from c_void_ptr. This resolves the
test regressions in test/modules/standard/LAPACK.

I also added a test with some functions using c_void_ptr arguments and
return types, since I was suprised that LAPACK was the only test showing
this error. These tests also fail without the fix in this PR.

### CODE REVIEW

**Comment by mppf** [comment]
Full local testing is underway.

**Comment by lydia-duncan** [comment]
I think it makes sense that c_void_ptr doesn't need FLAG_IGNORE_NOINIT - the patch looks good assuming it passes testing.  I might add some comments to the test to aid anyone looking at it later, but I wouldn't hold up the patch on it.

**Comment by mppf** [comment]
I need to fix the new test, it behaves differently on linux

**Comment by mppf** [comment]
But full tests pass

**Pull request merged**
