### PR TITLE
Fix a problem with dynamic dispatch in the parallel pass

### LINKED ISSUE #18580: Incorrect value from modified ref argument with --no-local
### Summary of Problem

For --no-local compilations the code from #16935 is getting incorrect results for the module-level variable getting passed to a virtual method. It appears that it is putting that variable on the heap and assigning its value to a non-reference temp which is then passed to the virtual method by reference. Something like:

```chapel
var ipos1 = heap(int);
var tmp = ipos1.value;
x!.ff(tmp);
writeln(ipos1);
```

### Steps to Reproduce
```
chpl --no-local test/optimizations/copyPropagation/cp-problem2-no-local.chpl
./cp-problem2-no-local
```

**Associated Future Test(s):**
test/optimizations/copyPropagation/cp-problem2-no-local.chpl

### Configuration Information
chpl version 1.26.0 pre-release
  built with LLVM version 11.1.0
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

### PR DESCRIPTION
**Pull request by daviditen**
When creating heap allocations during the parallel pass, a dynamically
dispatched method call should be handled the same as other function calls.
Add it to a branch that is handling resolved calls instead of handling it
alongside random primitive calls.

Removed the special future for this case that was only running with --no-local
configurations, and allow the other identical copy to run in both --local and
--no-local configurations.

Fixes #18580

Signed-off-by: David Iten <daviditen@users.noreply.github.com>

### CODE REVIEW

**Comment by daviditen** [comment]
Passed linux64 paratest
Passed linux64 paratest with --no-local

**Comment by daviditen** [comment]
I merged main into this branch and testing was clean again.

@e-kayrakli, would you mind reviewing?

**Review by e-kayrakli — APPROVED** [review]

**Comment by daviditen** [comment]
Thanks!

**Comment by bradcray** [comment]
Thanks for sticking with this, David!

**Pull request merged**
