### PR TITLE
Remove legacy GASNet-1 backend

### PR DESCRIPTION
**Pull request by bonachea**
The legacy GASNet-1 backend has been superseded by the new GASNet-EX backend,
which has been Chapel's default GASNet backend since 658ac15b5 (Chapel 2.1).

Both backends run over the same GASNet-EX implementation, so this is mostly
just about removing pointlessly duplicated Chapel runtime code, to improve
future maintainability.

Deliberately undocumented setting `CHPL_GASNET_VERSION` is also removed.

Partially reverts 2f4776efc08bf695237d7aa1ef18419e14f40196

Manually tested on Perlmutter (ofi conduit) and JLSE Cascade (ibv and udp conduits).

### CODE REVIEW

**Comment by bonachea** [comment]
CC: @PHHargrove @jhh67

**Review by PHHargrove — APPROVED** [review]
LGTM, @bonachea 
Thanks for this effort to help reduce future maintenance overhead.

**Comment by bonachea** [comment]
@jhh67 can you please review this PR?

CC: @bradcray

**Comment by jhh67** [comment]
I'll do it shortly. I'm currently in the process of removing the relevant jobs from our Jenkins server so they don't break.

**Review by jhh67 — APPROVED** [review]

**Pull request merged**
