### PR TITLE
Curl: Make the libcurl_easy_* API easier to use by adding setopt wrapper

### PR DESCRIPTION
**Pull request by cassella**
Being able to set options easily on the curl_easy object is all that's
needed to be able to implement the sample libcurl POST programs in
Chapel with the Curl module.  Add a curl_easy_setopt() wrapper that
uses the Chapel-to-C type manipulation that's done in the qio
channel-based code.

Add an example using it to the Curl module comment, and a test of
using the curl_easy_ interface to do a GET.

Add a compile-time check to setopt() for types that aren't valid for
any option.

Add a test of that check, and of a type mismatch that we can detect
only at run time.

Update a commented-out writeln for nilability, so that it'll compile
when uncommented.

Remove a few trailing spaces.

The first commit applies some fixes developed by hokiegeek2 in #18259.

[Reviewed and tested by @dlongnecke-cray.]

### CODE REVIEW

**Comment by cassella** [comment]
The code to use to issue a post has changed somewhat from the first PR (#18270) -- all the functions to call now have the same names as the libcurl `curl_easy_*` ones:

```chapel
    use SysCTypes, CPtr;

    proc null_write_callback(ptr: c_ptr(c_char), size: size_t, nmemb: size_t, userdata: c_void_ptr) {
      writeln("null_write called");
      return size * nmemb;
    }

    var curl = Curl.curl_easy_init();
    writeln("type is ", curl.type:string);
    Curl.curl_easy_setopt(curl, CURLOPT_URL, 'http://localhost:3000/posts');
    var args = new Curl.slist();
    args.append("Accept: application/json");
    args.append("Content-Type: application/json");
    Curl.curl_easy_setopt(curl, CURLOPT_HTTPHEADER, args);
    var jsonPayload = '{"foo": "from ChapelEasy"}';
    Curl.curl_easy_setopt(curl, CURLOPT_POSTFIELDS, jsonPayload);
    Curl.curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, 'POST');
    Curl.curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, c_ptrTo(null_write_callback):c_void_ptr);

    var ret = Curl.curl_easy_perform(curl);

    args.free();
    Curl.curl_easy_cleanup(curl);
```

**Comment by cassella** [comment]
I'd like to add a test of using the libcurl API to do a POST, but the python `http.server` used by the other curl tests doesn't support POSTs.  I developed the code using the test server @hokiegeek2 pointed at in his pr, https://www.npmjs.com/package/json-server .

That's installed via `npm`, and run with a starting `db.json`, allowing GETs and also allowing POST and PATCH requests to modify it.

Is that something we can do with the Chapel test system?

**Comment by cassella** [comment]
It turns out the POST request could be done with the module as-is, though it would require casting/converting the setopt option arguments from Chapel types to C types libcurl can handle, as the setopt function does.

I didn't realize it until I was developing this second PR because I saw all the `extern proc curl_easy_*` and thought they were there for `Curl.chpl`'s benefit, for it to use to implement the urlreader/writer.  I didn't realize they were available to users of the module, let alone that they were meant to be called externally.

I imagine the `curl_easy_getinfo()` function will need similar treatment to `setopt` for its generic `arg` argument, but I didn't take that on.

I'm a bit skeptical at the module not including the various `CURLOPT_*` values.  It has a comment 

```
Due to the large number of constants in the Curl interface, and the fact that
these constants vary for different versions of Curl, this module does not
provide extern declarations for all constants. However these are trivial to add
to your own programs. For example, the below example declares
``CURLOPT_VERBOSE`` as a ``CURLoption`` like this:

.. code-block:: chapel

  extern const CURLOPT_VERBOSE:CURLoption;
```

which is true, but doing this is tedious.  The large number isn't a problem.  I'm not sure about the "these constants vary for different versions of Curl", but presumably most of them have existed for long enough that "any reasonable" version of Curl would have them.  Certainly the ones `Curl.chpl` uses internally it's already relying on, and could make available to its users.

**Comment by hokiegeek2** [comment]
@cassella sorry, I was offline yesterday. Yep, POST and PATCH requests against the Kubernetes API work well for me.

**Comment by cassella** [comment]
Now that I look at this part more closely, I don't understand what it means to have an `extern proc` with a generic argument, as `curl_easy_setopt()` has, now as `c_curl_easy_setopt()`.  `setopt()` uses a few helper functions that accept an `arg` of a specific type, but then most of them just pass that `arg` as the generic argument to that extern proc.  So it seems like most of the cases in `setopt()` could just call the extern proc themselves?  Unless the idea is to run them all through helpers so that the caller doesn't need to know which cases need special handling?

left that in place, and it still works, but I don't understand what the intention there is.


I'll have limited time to work on this the next few weeks; feel free to make use of that "allow edits by maintainers" checkbox.

**Comment by bradcray** [comment]
> I don't understand what it means to have an extern proc with a generic argument

For a typical C routine, it typically means that the Chapel programmer is being lazy and taking advantage of the fact that Chapel has generics to avoid specifying the type.  If the result is a white lie that the code violates (e.g., it can't take a type that is passed to it) then the C compilation+linking step will complain (in the old compiler; I assume the LLVM compiler also complains, just in a different way).  In some cases—like a C macro, `sizeof()`, or `printf()`—the C behavior may seem sufficiently "generic" to Chapel that using a generic formal argument is reasonable.

**Comment by hokiegeek2** [comment]
@cassella another request...please add the following:

private extern const CURLOPT_FAILONERROR: CURLoption;

The reason I ask for this option is that it ensures that HTTP response codes of > 400 can be reported as errors if the following is specified (I am doing this in Arkouda):

Curl.easySetopt(curl, CURLOPT_FAILONERROR, 1);

I was getting 409 errors (attempting to post JSON which is already in Kubernetes) which were not being handled because if the request makes it through, the [CURLcode](https://curl.se/libcurl/c/libcurl-errors.html) response is zero:

image

With this in my Chapel code HTTP error codes are reported.

**Comment by cassella** [comment]
Hi @hokiegeek2 .  The Curl module doesn't define any of the `CURLOPT_` values for users.  (The ones it declares it declares with `private` as you suggested, so they're no available to users of the module.)  You can add that declaration to your program, like you should have to add the other `CURLOPT_` values you're using.

The module currently doesn't export `curl_easy_strerror()`, which it could.  I don't know if that should be part of this PR.

I don't know what the best way to use the `ERRORBUFFER` option from Chapel would be.  I'm pretty sure you can't pass a `string.c_str()` as the buffer for the library to modify.  Maybe an array of `int(8)` of the size mentioned in that option's help, or a `c_array`, that you then have to use one of the `createStringWith` functions from the String module on?

**Comment by bradcray** [comment]
> The module currently doesn't export curl_easy_strerror(), which it could. I don't know if that should be part of this PR.

I think let's fork that to a separate issue / effort rather than having this PR try to address all problems at once.

**Comment by hokiegeek2** [comment]
@cassella gotcha, okay, this is what I did. I put this in my Chapel fork:

image

Then I put this in my Arkouda code:

image

```
  var ret = Curl.easyPerform(curl);
  
  if ret == 0 {
      esLogger.debug(getModuleName(),getRoutineName(),getLineNumber(),
          "Successfully executed Http request with payload %s".format(payload));
  } else {
      esLogger.error(getModuleName(),getRoutineName(),getLineNumber(),
          "Error in executing Http request, return code: %i".format(ret));
      throw getErrorWithContext(getLineNumber(),getRoutineName(),getModuleName(),
          "Http request with payload %s returned error code %i".format(payload,ret),
          "ExternalSystemError");
  }
```

Now if a Http status code > 400 (in my case, 409 'cause the JSON object to be added is already present) is returned, the CURLcode of 22 is returned:

image

**Comment by hokiegeek2** [comment]
@bradcray okay, once this PR is settled I'll submit another PR w/ these changes

**Comment by cassella** [comment]
> I put this in my Chapel fork:

Did you also put that in your Arkouda program code?  Having that `private` declaration in `Curl.chpl` shouldn't be enough to let you reference it in your code.  The Curl module expects you to define in your code the `CURLOPT`s that you use.

**Comment by hokiegeek2** [comment]
Ah, good point, and indeed I did:

image

**Comment by dlongnecke-cray** [comment]
@cassella What's left to do here to move things forward? @hokiegeek2 Would you be up for doing a review of this to make sure it has the things you need?

If we're ready to review I'd be happy to help as well.

**Comment by bradcray** [comment]
I was chatting with Paul about this yesterday (as he's on vacation as of today), and he said that he considers it to be in our court for review + merge.  If we have feedback, we should implement it ourselves rather than waiting on him given his vacation and the release dates.  Can you do the review, David?

**Comment by dlongnecke-cray** [comment]
I don't comments on the code changes themselves as they seem straightforward enough to me, and also appear to include the fixes made in #18259.

I am building the docs and running tests now (most of the diffs are adding tutorials to the Curl module docs, very kind of Paul to do).

**Comment by hokiegeek2** [comment]
@dlongnecke-cray @cassella will be happy to review!

**Review by dlongnecke-cray — APPROVED** [review]
I generated the docs and ran the tests locally and things look good.

The test fails even though its output it generates looks the exact same as the `.good` file. A simple `mv` of the `.exec.out.tmp` to `.good` fixes the issue (this is something I run into occasionally and I'm still not sure why it happens. Different line endings, maybe?)

I'd rather just fix that as a followup than make edits to this branch.

**Comment by bradcray** [comment]
> I'd rather just fix that as a followup than make edits to this branch.

Assuming this is a pre-existing condition (e.g., happens for you on `main` as well), I agree.

> Different line endings, maybe?

That'd be my guess as well.  If you bring them both up in emacs, does either have `(DOS)` mode indicated?  (I guess it would need to be the `.tmp` file that did given  your description... and checking the `.good` files in that directory, none seem to be in DOS format.  OR does running `dos2unix` on the `.tmp` file similarly fix the issue?

**Comment by dlongnecke-cray** [comment]
Ah the problem is that the `curl` on my local machine spits out `dos` line endings to stdout...I just assumed that it wouldn't do that since I'm on a Mac. I just ran on linux and all the tests passed.

This makes sense because we would have noticed if a test was failing.

My mistake!

**Comment by bradcray** [comment]
> I just assumed that it wouldn't do that since I'm on a Mac.

Odd... I don't think I've ever had anything on my Mac generate DOS-terminated files (though I also haven't run curl).  Could that be the result of an environment setting or somesuch?

**Comment by dlongnecke-cray** [comment]
Hi @hokiegeek2, had a chance to review these changes yet? I was thinking about merging this PR today.

**Comment by hokiegeek2** [comment]
@dlongnecke-cray Whoops, sorry, was working on another project today, thanks for pushing this across the finish line!

**Pull request merged**
