### PR TITLE
Bump the spec's version+date and copy to release

### PR DESCRIPTION
**Pull request by bradcray**
[trivial, not reviewed]

### CODE REVIEW

**Comment by bradcray** [comment]
@vasslitvinov , @lydia-duncan , @mppf : If you guys could verify that the copy of the spec I put into doc/release has your recent/important spec changes in it, I'd appreciate the additional pairs of eyes.

**Comment by mppf** [comment]
Looks good to me, my recent changes look OK.

**Comment by lydia-duncan** [comment]
Mine's in and good as well!

**Comment by vasslitvinov** [comment]
Looks good to me too!

**Pull request merged**
