### PR TITLE
Workaround for overloading in qthreads

### PR DESCRIPTION
**Pull request by vasslitvinov**
This resolves the failure in the test `gpu/native/examples/releaseNotes/tasks/begin` in the configuration "gpu-xc-cuda.ugni", which uses the bundled LLVM 18 and CUDA 12 (not sure though). It is a workaround for the problem of handling C++ overloading while parsing the runtime headers during our LLVM codegen, see #25506. The above test failure was triggered by, unlikely caused by, the PR #25215.

### Details

[The change is a simple two-liner. Read on for the rationale.]

Prior to this change, qthreads headers defined two overloads of qthread_fill: `qthread_fill(const aligned_t *dest)` in qthread.h and `qthread_fill(syncvar *const dest)` in qthread.hpp. Calls from ChapelSyncvar.chpl intended to invoke the former instead invoked the latter. Given that qthread's `syncvar` is a virtual class due to the presence of a virtual destructor, class instances occupy two 8-byte words whereas in Chapel the `aligned_t` variables are assume to occupy only one 8-byte word. The incorrect `qthread_fill` accessed the second word, which is garbage memory. The failure mentioned above is the only symptom of this problem that we have seen.

This change simply hides some of qthread's C++ headers, which removes the incorrect overload of `qthread_fill`, when qthreads are parsed in the C++ mode. Therefore the calls from ChapelSyncvar.chpl invoke the intended overload now.

As a mismatch to the C++ trouble, when we build qthreads as part of building the Chapel tree, we compile its sources in C mode.

This solution was proposed by @mppf - thank you!

Testing:
* [x] standard and gasnet paratest with locale_model=flat
* [x] spot-checks in the configuration where we observed the failure

### CODE REVIEW

**Review by e-kayrakli — APPROVED** [review]
Certainly strange, but I am ok with this bandaid.

**Review by mppf — APPROVED** [review]
Looks good. Please add a note to third-party/qthread/README about the change. Otherwise we will probably drop it when upgrading qthreads.

**Comment by bradcray** [comment]
@vasslitvinov / @e-kayrakli / @mppf: Is there a change we could/should request from Qthreads to simplify this issue going forward?  They've been quite responsive to our issues recently…

**Comment by vasslitvinov** [comment]
@bradcray to me this is a very peculiar workaround for our own issue, I do not see how it can be relevant to Qthreads' general audience.

Perhaps repeating myself, I suggest that we make our codegen run Clang in C++ mode only for reading CUDA headers, then run Clang separately in C mode for everything else. This way we will not need anything from Qthreads and can back out this patch.

**Comment by mppf** [comment]
IMO it'd be reasonable for us to request the 1-line change to `qthread.h`. It is pretty trivial and I don't expect it would cause an issue even if we settle on a different approach to solve this problem.

**Comment by bradcray** [comment]
I'll ping the Qthreads team and see if we can get a read from them on this PR's topic.

**Comment by insertinterestingnamehere** [comment]
Do you have an example of how this is being called? In particular, is it being called with a pointer to const? This looks like it may just be a typo in our API, but I'm still confused as to why C++ is automatically converting the pointer type to preserve the const-ness so there may be more going on.

**Comment by insertinterestingnamehere** [comment]
Okay, I'm fairly sure we shouldn't have that virtual destructor there to begin with, but also the way the templated interface is done here is dubious. What overloads to you expect to have work for these kinds of wrappers? Just things like `qthread_fill(aligned_t *const)` and `qthread_fill(syncvar_t *const)`?

**Comment by insertinterestingnamehere** [comment]
Yah, I think there's a fair bit of cleanup needed for the qthreads C++ wrappers. I'm still baffled as to how `qthread_fill(syncvar *const dest)` could be picked up as a preferred overload when passed an `aligned_t *` though. C++ isn't supposed to allow pointer type casts like that to happen implicitly. If anything I'd expect the reverse to happen (something like `int*` or `syncvar_t*` getting implicitly converted to `aligned_t *const` instead) due to the way the qthreads C++ wrappers are currently written.

**Comment by mppf** [comment]
@insertinterestingnamehere - the issue we are working around here is that, within the Chapel compiler when compiling runtime and third-party code, it only handles C code, not C++. So the C++ overloads in qthreads were messing up the Chapel compiler. Certainly, one day we might have better C++ support, and handle the overloads correctly, but that is not currently being worked on.

So, in other words, we don't know of a problem with qthreads C++ wrappers as such; it's more that they are incompatible with the Chapel compiler in certain settings (in particular when compiling for GPUs where we compile the runtime as CUDA code which is a kind of C++).

The workaround was just to have a way to turn off the C++ wrappers.

**Comment by jabraham17** [comment]
FWIW, the reason `qthread_fill(syncvar *const dest)` was getting picked up and preferred over the `aligned_t*` overload has to do with how the Chapel compiler does its codegen, not how a C++ compiler works. The Chapel compiler is relying the C rules (no function overloading, everything gets the same name)

**Comment by insertinterestingnamehere** [comment]
Ooh, I think I get it now. Thanks for clarifying. For some reason I was thinking that a C++ compiler was involved at a step in the compilation process, but it sounds like the chapel compiler is actually getting info from the headers somehow and then linking to the wrong symbol based off of that. Yes, a compile-time switch is a fine way to deal with this. I think our C++ wrappers need simplification, but I'm not sure if simplification on the qthreads side of things will be enough to work around this issue.

**Comment by insertinterestingnamehere** [comment]
Alright, I did a pass removing a bunch of unused code from the qthreads C++ wrappers. That may be enough by itself to fix the issue with the wrong symbol getting picked up in Chapel. See https://github.com/sandialabs/qthreads/pull/263

**Comment by bradcray** [comment]
Thanks for taking a look at this issue and weighing in, Ian / @insertinterestingnamehere! 

@vasslitvinov is currently out on leave, but I'm hoping he can take a look at whether your PR improves things for us upon returning.

**Comment by insertinterestingnamehere** [comment]
Sounds great. No rush on my end. Thanks!

**Comment by insertinterestingnamehere** [comment]
Sounds great! No rush on my end. Including it whenever you next update your copy of qthreads makes sense. Thanks for confirming that the update works!

**Pull request merged**
