### PR TITLE
Fix another deletion size mismatch error

### PR DESCRIPTION
**Pull request by daviditen**
Fix an error with a size mismatch when deleting an array. This was causing
errors in a test on ugni platforms.

### CODE REVIEW

**Comment by daviditen** [comment]
Passed linux64 paratest.

**Comment by daviditen** [comment]
Thanks!

**Comment by bradcray** [comment]
Hi @daviditen, @ronawho: This seems to have caused a new leak in some cases:

https://chapel-lang.org/perf/chapcs/?startdate=2019/01/18&enddate=2019/08/12&graphs=memoryleaksforalltests,numberoftestswithleaks

**Comment by daviditen** [comment]
I'm looking into it. The first couple tests I see with new leaks are c-ray and duplicates-alt-assoc-reduce.

**Pull request merged**
