### PR TITLE
After much turmoil and angst, fix bug with internal documentation clean up

### PR DESCRIPTION
**Pull request by lydia-duncan**
Prior to this change, our fixInternalDocs script would remove functions and
variables with "chpl_", "_" and non-alphabet character starts, but it would fail
to remove any associated documentation comments, thus making it appear that the
symbol listed before the removed symbols had longer (and inaccurate)
documentation than was actually the case.  This change extends the removal to
also encompass the comments that followed the removed symbol.

Many thanks to Greg for the brainstorming and Ben A. for the actual awk command
structure.

Verified that the internal modules are not modified other than those I expect to be
modified due to this change (http://chapel.cray.com/docs/master/modules/internal/ChapelArray.html#ChapelArray.isArrayValue).  The String module does not have
this script applied to it.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Change looks good - since it's a semi-gross awk one-liner, I think it deserve a nice comment.

**Comment by lydia-duncan** [comment]
lol, fair enough

**Comment by lydia-duncan** [comment]
I was just so excited that it worked, ha ha

**Comment by lydia-duncan** [comment]
Oh, verified that this works on OSx and Linux

**Pull request merged**
