### PR TITLE
Incorporate `array_on_device` specific tests into other tests

### PR DESCRIPTION
**Pull request by e-kayrakli**
We used to have `array_on_device`-specific directories/tests back when there were significant issues with that mode. Alongside work that fixed those issues, most of those tests were removed. This PR removes the remaining tests.

`triadAsync` was a unique test that's testing the non-user-facing async comm interface. This PR puts that under `gpu/native/studies/shoc` and plots it alongside existing triad tests.

While there:

- tightens `on` statements in the existing triad implementations to make them match more closely
- reindents tests to have 2-space indentation

Test:
- [x] nvidia
- [x] nvidia+aod
- [x] amd
- [x] amd+aod

### CODE REVIEW

**Comment by e-kayrakli** [comment]
@ShreyasKhandekar -- I added you as a reviewer but jumping into the diff directly is probably not the best idea. You can start with https://github.com/chapel-lang/chapel/pull/23105/commits/93a4a904e45a8311f7bf8c3817c18862289013fa and go forward. Hiding whitespace in the diff helps. You can then look at the first PRs that you've skipped over, but they are just moving files and reindenting code.

**Comment by e-kayrakli** [comment]
... and I am aware of the annotation CI failure.

**Review by ShreyasKhandekar — APPROVED** [review]
Looks good to me. Do you think that removing `triad.chpl` can also go in this PR?
Thanks Engin!

**Comment by e-kayrakli** [comment]
@ShreyasKhandekar -- The PR has already sprawled a bit further than I initially intended. I drew the line here because I wanted us to think more about how to remove `triad.chpl` before we do that. There were some other things that I realized that we can improve. I recorded them in https://github.com/Cray/chapel-private/issues/5328

Thanks for the review! I'll merge it Monday. I am not planning to check-in over the weekend.

**Pull request merged**
