### PR TITLE
Make qthreads config-time check of hwloc linking configurable

### PR DESCRIPTION
**Pull request by jhh67**
`Qthreads` configuration contained a static list of sets of potential link-time arguments needed to link against `hwloc`. The `configure` script would iterate through this list until a set of arguments was successful. This was problematic because it required keeping the list up-to-date with respect to `hwloc` changes. This commit makes the check configurable as it is only beneficial to Chapel developers as any problems with linking against `hwloc` will be found when compiling an app. It's not worth the cost of maintaining the list nor the complexity of adding support for `pkg-config`.  The `--disable-hwloc-configure-checks` argument to `configure` turns off the `hwloc` link check. The link check also tests whether or not `hwloc` supports distance information. If the link check is disabled, `configure` assumes that `hwloc` supports distance information. This may be changed by passing `--disable-hwloc-has-distance` to `configure`.

Resolves https://github.com/Cray/chapel-private/issues/4387 and closes https://github.com/Cray/chapel-private/issues/4595.

### CODE REVIEW

**Comment by ronawho** [comment]
Instead of outright removing, I was imagining adding a configure flag like `--no-hwloc-configure-checks` or something to skip the check. That way it's something we could upstream to qthreads instead of having to maintain the patch ourselves.

**Review by ronawho — COMMENTED** [review]
Overall, looks good. Please add a note to the README. 

I also think we can/should remove the patch to look for libpci as well now.

**Comment by jhh67** [comment]
Will do on both suggestions.

**Review by ronawho — APPROVED** [review]
Looks good to me. Can you open an issue (or adapt https://github.com/Cray/chapel-private/issues/3832) to capture that we need to upstream our outstanding qthreads changes?

**Comment by jhh67** [comment]
I modified https://github.com/Cray/chapel-private/issues/3832.

**Pull request merged**
