### PR TITLE
Chpldoc output one file per module

### PR DESCRIPTION
**Pull request by lydia-duncan**
Change the output form for chpldoc from one generated file per source
file to one generated file per module.  Should clean up the output of
nested modules, and solve a bug where Sphinx associates functions
following a submodule definition to that submodule instead of the
parent module.

There will be chpldoc tests that should adjust, I haven't updated their
output yet.

Issue not yet addressed - currently, the strategy to link the submodules in
to the parent module ends up also bringing them into the sidebar at the top
level.  This is undesireable, we would like to only have them visible under
the parent module and in the module index.  Trying to fix this issue is why
I have saved the code as it is now, so that I have a rollback point.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@bradcray - here it is!

**Comment by bradcray** [comment]
Hi @lydia-duncan : Here's my proposed fix:

https://github.com/chapel-lang/chapel/commit/cb66e903f65cc6aa25b56f363cd44ca42f85b6db

**Comment by lydia-duncan** [comment]
Ugh, the merge messed with things.

**Comment by mppf** [comment]
This was replaced by PR #3551.

**Pull request closed without merging**
