### PR TITLE
Apply pragmas to all declarations in statement

### PR DESCRIPTION
**Pull request by bradcray**
Prior to this change, pragmas were only applied to the first symbol in a declaration
statement to which they were attached.  This isn't terribly surprising since we
primarily apply them to functions and functions are singleton declarations.  However,
this meant that if you had code like:

    pragma "foo"
    var a, b, c: int;

the pragma would only be applied to 'a' not to 'b' and 'c'.  With the introduction of
the 'nodoc' pragma, this becomes problematic because it means there's no way
to mark 'b' and 'c' as nodoc as well (since, syntactically, pragmas must precede
statements).

This commit changes that and applies the pragma to all symbols defined by the
statement by iterating over the DefExprs in the statement rather than simply
the first.

I've added a simple test to try and lock in this behavior (though again, that was
complicated by the small number of pragmas that make sense for variables
and are easily tested).  Specifically, I used the 'export' flag in its pragma form
and then grepped the generated source to make sure that these symbols
weren't marked as 'static' (as most Chapel global variables are).

### CODE REVIEW

**Comment by bradcray** [comment]
I think this is just an offshoot of my own rusty-ness with the compiler IR combined with pattern matching based on the reference to 'first' that was present in the code to begin with.  Can you remind me what the more representation-neutral means of iterating over a case like this is?

**Comment by bradcray** [comment]
I'm testing the revision above now, which uses for_alist as suggested (but moves the error case out of the loop compared to what you mailed).

**Comment by noakesmichael** [comment]
On Feb 11, 2015, at 5:12 PM, Brad Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm testing the revision above now, which uses for_alist as suggested (but moves the error case out of the loop compared to what you mailed).

—
Reply to this email directly or view it on GitHub<https://github.com/chapel-lang/chapel/pull/1292#issuecomment-73999535>.

I think you are saying that you perform the “is defExpr check” on the first element outside
of the loop and then assume all elements are defExprs if the first one is.  As far as I know
that should be reasonable given the way buildPragmaStmt is used today.

Mike

**Comment by bradcray** [comment]
No, that's not how I did it -- see the commit just before my previous comment for the code (or refresh the pull request).

**Comment by noakesmichael** [comment]
Sweet.  Sorry I didn’t realize that you had pushed the change you were testing.

Mike



On Feb 11, 2015, at 6:51 PM, Brad Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


No, that's not how I did it -- see the commit just before my previous comment for the code (or refresh the pull request).

**Pull request merged**
