### PR TITLE
Prediff out line nums in error message for indexHetTuple test

### PR DESCRIPTION
**Pull request by stonea**
To address failure seen here:

https://chapel.discourse.group/t/cron-fast/12791

### CODE REVIEW

**Comment by bradcray** [comment]
Thanks for taking care of this Andy.  I'm wondering whether we should just have the testing scripts always run this filter on .good/.bad files that contain internal/standard/package module line numbers (I think we already have some other similar "always on" filters like something that munges the internal error strings, and this seems similar (?)).

Tagging testmaster @ronawho to see what he thinks.

Or we could have our CI flag those files when someone tries to add them to the repo.

I know I'm guilty of this b/c most of the times I'm filing a future I'm trying to get it done as fast as possible (and don't anticipate it / think of it) rather than taking the lazy route of not filing anything at all.

**Comment by stonea** [comment]
> Thanks for taking care of this Andy. I'm wondering whether we should just have the testing scripts always run this filter on .good/.bad files that contain internal/standard/package module line numbers (I think we already have some other similar "always on" filters like something that munges the internal error strings, and this seems similar (?)).

It seems like we should.  Certainly we shouldn't rely on manually copying a `sed` command from `prediff` file to `prediff` file every time we make a test that might report a module error.

**Comment by ronawho** [comment]
Yeah, that seems reasonable. Please file an issue about this and throw the BTR label on.

**Comment by bradcray** [comment]
I filed https://github.com/chapel-lang/chapel/issues/19905 for this.

**Pull request merged**
