### PR TITLE
Fix the double deletion of an ignored return from chpl__autoDestroy().

### PR DESCRIPTION
**Pull request by hildeth**
The test
  performance/sungeun/multilocale/autoCopy.chpl
was written with the assumption that the return value from a call to
chpl__autoCopy would simply be ignored.

AMM does better: It tracks the ownership of the returned value, and if it is
not consumed in some way, arranges for it to be autodestroyed.  The main point
of this patch is to update the test, since an assumption on which it was based
is no longer valid.

To do this, the AMM implementation had to be updated to treat specially the RVV in a
function marked "return value is not owned".  Ownership of the RVV is
dropped on the floor if it happens to be owned at that point.

This test case is the only place in the module or test code where the "return
value is not owned" praga is used, so this change can be made with high
confidence.

It is interesting to note that comm traffic went down (by one fork each on
locales 0 and 3) as a result of AMM (not due to this change in particular).

### CODE REVIEW

**Comment by lydia-duncan** [comment]
If this is the only place where "return value is not owned" is applied to anything, why not remove it from flags_list as well?

**Comment by hildeth** [comment]
It is needed for this test.  It was not being used before now....

**Comment by lydia-duncan** [comment]
Ah sorry.  I guess what I meant in that case is if the test is doing something special that we don't think is a valid assumption after this change, why not remove the test?  Why make a pragma for something we don't really want to handle?

**Comment by hildeth** [comment]
Sung wanted to characterize the impact of autoCopy/autoDestroy calls on comm counts -- in isolation from other program elements.  It's fair to have a test like that in the test base.
The assumption that changed is whether an unnamed temporary will get cleaned up by the compiler: Didn't before; does now.  The general case is a function that returns a record by value.  Given:
```
   proc foo() : R { ... ; return r; }
   ...
   foo(); // leak memory or not?
```
The semantical question is whether we should leak memory at the call to foo() (because the coder failed to capture the return value of foo() in a variable.
AMM comes down on the side of "no leak".  The pragma is used to override AMM and not automatically destroy the unnamed temporary that actually captures the return value from the call to foo().

**Comment by lydia-duncan** [comment]
But if that arguably isn't the behavior we want, I don't see the point of adding a pragma that specifically does this behavior.  Isn't there some way to change the output to reflect our new expectations instead of adding a pragma that we don't want anyone to use and don't anticipate using again?

**Comment by hildeth** [comment]
The flag is used internally as part of the AMM implementation.  It is only that it is not used as a pragma anywhere in the module code.  I will update the comment to make this clear.

**Pull request merged**
