### PR TITLE
Update `sync`/`single` doc

### LINKED ISSUE #19152: Remove `foo$` style names in sync documentation
Now that implicit read/writes of syncs are deprecated (https://github.com/chapel-lang/chapel/pull/17287), it is no longer suggested to annotate syncs by appending `$` to their variable name. However, our documentation on syncs still uses this naming style:

- [sync primer](https://chapel-lang.org/docs/1.25/primers/syncsingle.html)
- [sync spec](https://chapel-lang.org/docs/1.25/language/spec/task-parallelism-and-synchronization.html?highlight=sync)

Should we update these to remove the `foo$` naming style of sync variables?

### LINKED ISSUE #20097: Update sync/single primer
I think https://chapel-lang.org/docs/main/primers/syncsingle.html needs to be updated with the types that are supported by syncs/singles now (I think we recently expanded that) and to remove the `$` suffix convention since I think we're moving away from that.

I believe it was already updated to get rid of the implicit read/write semantics, but I didn't look at the comments closely to see if any of them still talk about that feature.

### PR DESCRIPTION
**Pull request by Guillaume-Helbecque**
This PR updates the `sync`/`single` doc by: 
- removing the `$` convention that is no longer needed (since  #17287);
- adding the new types that are supported by `sync`/`single`.

To be consistent with these changes, the PR also removes all `$` characters in the code, related to `sync` or `single` variables names.

Resolves #19152 
Resolves #20097

### CODE REVIEW

**Comment by ronawho** [comment]
I know this is still a draft, but was excited to see the change so took a peek:
 - Note that github "auto close issue" syntax requires the closing prefix before each issue. e.g. "Resolves 19152 and resolves 20097."
 - Some commits are missing the DCO signoff.
 - There's a few test failures (most because there was a non-sync with the same base name or the variable name was `sync$`):
    ```
    [Error matching compiler output for expressions/noinit/usedWithSync]
    [Error matching compiler output for optimizations/remoteValueForwarding/bradc/testconstlocality]
    [Error matching compiler output for parallel/begin/deitz/test_coforall_sugar4]
    [Error matching compiler output for release/examples/primers/syncsingle]
    [Error matching compiler output for release/examples/spec/Task_Parallelism_and_Synchronization/cobeginAndEquivalent]
    [Error matching compiler output for studies/bale/toposort/toposort]
    [Error matching compiler output for studies/dijkstra/driverEdgeBtw]
    [Error matching compiler output for studies/shootout/chameneos-redux/hannah/chameneos-redux-v1]
    [Error matching compiler output for studies/ssca2/main/SSCA2_main (compopts: 1)]
    [Error matching compiler output for studies/ssca2/test-rmatalt/nondet]
    [Error compilation failed for studies/ssca2/test-rmatalt/reproduc (compopts: 1)]
    [Error matching program output for types/enum/bradc/dispatch/syncenum]
    ```

**Comment by Guillaume-Helbecque** [comment]
Thank you for the review, it helps! Unless I'm mistaken, all your comments have been fixed, except the test failure `[Error matching compiler output for release/examples/spec/Task_Parallelism_and_Synchronization/cobeginAndEquivalent]` because I didn't find the location of this test.

**Comment by Guillaume-Helbecque** [comment]
**Note:** Sometimes `var$` is used to denoted atomic variables. In my opinion, these `$` are out-of-scope of this PR. I think we could make a follow-up PR (related to https://github.com/chapel-lang/chapel/issues/19152#issuecomment-1677803463) to tackle these cases.

**Comment by ronawho** [comment]
> except the test failure [Error matching compiler output for release/examples/spec/Task_Parallelism_and_Synchronization/cobeginAndEquivalent] because I didn't find the location of this test.

Ah, we autogenerate tests from the spec. If you search the spec for `cobeginAndEquivalent` you should find it. You can generate the tests by running `make spectests` and then run the test like normal

**Comment by Guillaume-Helbecque** [comment]
I didn't know for `make spectests`, thanks!

I think the PR is ready for review now. I did my best to try to remove all the `$` related to `sync`/`single` variables, but maybe a handful of them slipped through the cracks.

**Comment by ronawho** [comment]
std and multi-locale testing came back clean for me. @bradcray spec wording changes good with you?

**Review by ronawho — APPROVED** [review]

**Comment by ronawho** [comment]
> I didn't check out the branch to see whether there were other $s missed.

It's not trivial to search for remaining tests since `$` is used for env vars in comments and for regexes, but with a quick search I mostly see tests with atomics and a few locks using the `$` as part of an identifier. But as https://github.com/chapel-lang/chapel/pull/22953#issuecomment-1680298657 notes, this PR is not updating those, just sync/single.

>  I also don't know whether the whitespace changes in the spec will affect how it's rendered (but would guess not).

Nah, no impact.

**Comment by ronawho** [comment]
@Guillaume-Helbecque thanks for the contribution! Our nightly testing is a bit noisy at the moment, but I'll plan to merge tomorrow or Friday.

**Pull request merged**
