### PR TITLE
[Shell][Z] Add command line autocompletion for Z shell

### PR DESCRIPTION
**Pull request by ayuagrawal**
Signed-off-by: Ayush Agrawal <ayuagrawal@yandex.com>

### CODE REVIEW

**Comment by ayuagrawal** [comment]
_chapel-zsh-completion file is not complete yet. I send this PR to just ask if it is good to have a handwritten completion option list as I can see for bash shell there is a [script](https://github.com/chapel-lang/chapel/blob/master/util/devel/gen-chpl-bash-completion.py) which autogenerates these options for chpl-completion.bash

**Comment by e-kayrakli** [comment]
I think it'd be nice to have better support for ZSH. But I also think that we should have it scripted. I'd be afraid that having something hand-written is a maintenance burden down the road. Further, if it gets outdated, it'd be more confusing than handful.

FWIW, It'd be nice to improve that script to generate auto-completion for ZSH instead of developing one from scratch.

Pinging @mppf and @daviditen who are the author and reviewer of the PR that added that script.

**Comment by daviditen** [comment]
I agree that having this scripted is pretty necessary and it would be great to have the same script for both bash and zsh. It would also be good to have a test that will fail when somebody adds or removes an option without updating zsh autocompletion.

See `$CHPL_HOME/test/chplenv/autocomplete/autocomplete.chpl` for the bash version of this test.

**Comment by ayuagrawal** [comment]
Thanks, @e-kayrakli and @daviditen, I fully agree that a handwritten script increases the maintenance burden. I will take some time to understand how flags for autocompletion are generated in chpl-completion.bash and will try to update gen-chpl-bash-completion.py for zsh.

**Comment by bradcray** [comment]
@ayuagrawal , @daviditen , @e-kayrakli : From the conversation above, it sounds like we're not moving forward with this specific PR and would require a different approach to merge this.  Does that match your understanding?  If so, can we close this PR?  (I'm housecleaning tonight).

**Comment by e-kayrakli** [comment]
That's my understanding. Given the silence in the last couple of days I am closing this.

@ayuagrawal -- Thanks for your interest in doing this, if you want to get back to it feel free to reopen this PR or create a new one linking to this.

**Pull request closed without merging**
