### PR TITLE
Application-level optimizations for the Coral Image Analysis code

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR patches the Coral Image Analysis GPU performance test to have some of the application level optimizations that I had developed in the past. https://github.com/Cray/chapel-private/issues/4827 has the detailed discussion on those optimizations. But the summary is:

(All performance results are with 8000x8000 input with windowSize 100. V100 was the GPU used)

1. Reduce block size to 64: The kernel is relatively large and requires a lot of registers. If you have a lot of threads within a block (threads in the same block share the same physical memory for registers and L1), you end up thrashing registers a lot. (~3.2x improvement over base)
2. Transpose input array: Without transposing the input, GPU threads read sequential data individually, which is intuitive for CPUs. But you want to coalesce memory accesses by making consecutive threads read consecutive data. Note that there's no thread divergence in GPUs, so if two neighbor threads read two cache lines, that's a stall. (~2.8x improvement over (1))
3. Param unroll inner loop: this loop is guaranteed to trip 5 times. There *may* be changes down the road, but the trip count is inherent to the application (known at compile time) and will surely remain in single digits. (~1.1x improvement over (2))
4. Use smaller indices for the mask: The mask is a 2D sparse domain. For any astronomically high but realistic window size, 16-bit should be enough. This reduces the memory usage by simply storing less data. Probably leads to better cache utilization. (~1.1x improvement over (3))

The test passes both correctness and performance testing on nvidia.

### CODE REVIEW

**Review by DanilaFe — APPROVED** [review]
If I'm doing my math right, that's roughly an order of magnitude compare to baseline! Very nice.

**Comment by bradcray** [comment]
Nice!  Are all of these optimizations GPU-specific, or do some benefit a CPU run of the code as well?  (or is this [version of the] code now GPU-specific?)

**Comment by e-kayrakli** [comment]
> or is this [version of the] code now GPU-specific?

Yeah. This is different than other code developed by Scott. His thinking was that this problem is not feasible to solve on CPUs with realistic data sizes. I do have the CPU version in a separate repo somewhere, but we don't have it checked in anywhere. Nor have I tried the optimizations there.

**Comment by bradcray** [comment]
Oh, I didn't realize the CPU version wasn't checked in anywhere...  That seems too bad...

**Comment by e-kayrakli** [comment]
Just to be sure, there are CPU-based codes of his that are very similar to this one merged with https://github.com/chapel-lang/chapel/pull/22464

**Comment by bradcray** [comment]
Ah, so trying again, I think you're saying:
* We have the original CPU-oriented versions of the algorithm checked in
* The GPU-oriented versions were developed to handle the case where the computational intensity got much higher and we don't have a CPU-oriented version of that (which I agree is appropriate)
* (and maybe) the optimizations you've implemented are specific to this second version and not applicable (or maybe just not as necessary for?) the original CPU version (?)

**Comment by e-kayrakli** [comment]
> We have the original CPU-oriented versions of the algorithm checked in

No. The CPU version of this application is not within our repo. I have them elsewhere, though.

> The GPU-oriented versions were developed to handle the case where the computational intensity got much higher and we don't have a CPU-oriented version of that (which I agree is appropriate)

Rrright, but probably "handle the case where the computational intensity got much higher" is better stated as "handle a different problem where the computational intensity got much higher". Maybe we're saying the same thing though... [Slide 28 here](https://chapel-lang.org/CHIUW/2023/BachmanSlides.pdf) is what this code is about.

image

I think the "Habitat diversity" is the code that was merged with https://github.com/chapel-lang/chapel/pull/22464. What we are looking at in this PR is "spectral diversity".

> (and maybe) the optimizations you've implemented are specific to this second version and not applicable (or maybe just not as necessary for?) the original CPU version (?)

Yes. Probably.

**Comment by bradcray** [comment]
Got it straight now, thanks for clarifying.

**Pull request merged**
