### PR TITLE
Update the expected output for these tests after fixing const varargs checking

### PR DESCRIPTION
**Pull request by lydia-duncan**
The change had resulted in less communication (yay!)

Checked a fresh version of the tests with the update

### CODE REVIEW

**Comment by bradcray** [comment]
Any insight into where/how/why the communication improved for these cases?

**Comment by lydia-duncan** [comment]
Nothing solid - I don't see uses of varargs in DefaultSparse.  But I did touch `writef`'s implementation and CommDiagnostics uses `writef`.  So maybe there was less communication back to locale 0 to provide information?  That's not a satisfying answer, though, and I would have expected it to have a broader impact if that were the case

**Comment by bradcray** [comment]
I also expect (and definitely hope) that the writef()s in CommDIagnostics are done outside of the portion where the comms are being measured (?).

Would it be easy to put some sort of print debug into the branch in the compiler you added/changed to see where it fires in the new world?

**Comment by lydia-duncan** [comment]
I'm seeing const varargs used with `chpl__buildDomainExpr` and array `this` methods.  But I would also have expected that to have a broader impact . . .

**Pull request merged**
