### PR TITLE
Propagate "serial OK" flag for forall stmts/loops

### PR DESCRIPTION
**Pull request by vasslitvinov**
Change the parser to set a new "serial OK" flag in ForallStmt:
 - `true` for `[]`-forms
 - `false` for `forall`-forms

This does not affect forall expressions.

This is a step towards #11819.

In the compiler, add the 'serialOK' argument to ForallStmt::build().
Propagate it to ForallStmt instances.

While there, enable zippered forall statements to omit index variables,
as in non-zippered cases. Just to make the grammar more symmetric.
The following syntax forms are now legal:

```chpl
forall zip(....) ....
[ zip(....) ] ....
```

#### While there

Various aesthetic changes:

* The 'zippered' formal of ForallStmt::build() is now mandatory.
  To avoid potential confusion with the 'serialOK' formal.

* Reformat surrounding pieces of chapel.ypp to align corresponding
  non-terminals and actual arguments in adjacent lines.

* Bring the boolean fields of ForallStmt class together
  in the class declaration, for the looks.

* Remove the 'zippered' argument from ForallStmt constructor.
  This is for uniformity with other boolean flags.

* Slightly reorganize the code affected by the above,
  again for the looks.

* [x] linux64 testing
* [x] gasnet testing
* [x] commit changes to parser-generated files

### CODE REVIEW

**Comment by vasslitvinov** [comment]
> why ForallStmt::build needs to wrap the result in a BlockStmt* ?

I imagine that's because the parser has the production
```
stmt: block_stmt | if_stmt | loop_stmt | .....
```
which requires converting all statements to the same representation. At dawn of time that was chosen to be a BlockStmt.

**Comment by bradcray** [comment]
Hi @vasslitvinov  —

From the description above, I was thinking that with this change a statement like:

```chapel
[i in iterable] i = 0.0;
```

would no longer generate errors like:

```
error: A standalone or leader iterator is not found for the iterable expression in this forall loop
```

but I seem to still be getting them.  Is this surprising, or did I misunderstand the implication of this change?  Thanks.

**Comment by vasslitvinov** [comment]
@bradcray - this works for me:
```chpl
var GLOB: int;
iter iterable() ref { yield GLOB; }
[i in iterable()] i = 5;
writeln(GLOB);
```

What is your code?

**Comment by bradcray** [comment]
OK, thanks.  It's deep in the module code, so I'll see if I can dig deeper into how it differs from yours and what it would take to make it standalone.

**Comment by vasslitvinov** [comment]
Maybe you are dealing with a forall-expression, not a statement?

**Comment by bradcray** [comment]
No, I caught that... it's definitely a statement.

**Comment by bradcray** [comment]
I haven't simplified it yet, but it looks to me as though the iterable expression may include zip()s...  Does that suggest anything?

**Comment by vasslitvinov** [comment]
I did not debug zips.

Zip-related situations may be similar to #12196.
Because a `minloc reduce` expression, under the covers, is a zippered ForallStmt.

**Pull request merged**
