### PR TITLE
Fix chpldoc bug when method defined outside of type

### PR DESCRIPTION
**Pull request by lydia-duncan**
Previously, when a method on a class or record was defined
outside of the type definition, it was printed both within the
class and at the module level.  We decided that the best behavior
was to match the source code as much as possible, so if a
method on a class or record was defined outside that type, it
should be printed at the module level rather than the class level.

In investigating this, I noticed that the compiler flag FLAG_METHOD
was not applied in a way that was consistent with its name: methods
that were defined outside of a class or record did not have this
flag attached to them (hence why I wasn't skipping them at the module
level).  Since there were some cases where we wanted to distinguish
between the two definition locations, we decided to replace those
uses of FLAG_METHOD with a new flag, FLAG_METHOD_PRIMARY,
and attach FLAG_METHOD to *all* methods.  While replacing, I noticed
a use of FLAG_METHOD which fell into the same trap I had, and by
expanding its application discovered and fixed an error that occurred
where check_nil was called against strings.

tested against std/ and baseline over examples/

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@noakesmichael, would you mind reviewing?

**Comment by lydia-duncan** [comment]
@noakesmichael, good to go?

**Comment by noakesmichael** [comment]
Thanks for putting those methods back. "Some other day" we might like to write "setters" methods
for poking the current flags in and really help with the abstraction.

I think this is good to go.  If I were being anal, which I do my best to be, I'd note that there's
one last accessor in wrappers.cpp. However I don't see that's it's essential to pick this up
immediately.

Thanks!

**Comment by lydia-duncan** [comment]
I think that's more a problem with the wrappers function in question: it's a whole list of "is this flag here? then put it in that one", so it made sense to me to leave it be.  Thanks for the review!

**Pull request merged**
