### PR TITLE
Move some method definitions into headers

### PR DESCRIPTION
**Pull request by aconsroe-hpe**
Move some method definitions into headers

These small method definitions are being moved into their header files
so that they are eligible for inlining, which most of these almost
certainly will.

This was motivated by seeing these methods commonly show up in the top
20 of profiling reports:

  * Symbol::hasFlag
  * CallExpr::isPrimitive
  * Expr::inTree
  * AList::get
  * Symbol::isRef

I used a bit of loose judgement to move some related functions if they
felt sufficiently small and/or similar to one of the above. I also
chose to keep the method definitions outside the class as it makes a
better diff.

I had to move the class definition for Expr into expr-class-def.h so
that the alist.h header can implement the ::get method. Expr contains
an AList so it also needs to know the full layout. Without major
changes to header structure, this was my solution.

I verified most of these actually do get inlined and saw a 3-5%
reduction in compiling hello, cg-sparse-timecomp, and arkouda.

Passes paratest

### CODE REVIEW

**Comment by aconsroe-hpe** [comment]
Getting this open for overall reaction and polling whether anyone has suggestions on a better way to get the alist and Expr headers sorted out. Since `::get` moved into the header, it needs a full definition of Expr so that it can access the `next` field, but Expr contains an AList by value so it needs the full definition of AList.

**Comment by mppf** [comment]
The approach here makes sense to me. Perhaps we could rename compiler/include/expr-class-def.h -> expr.h or Expr.h and maybe expr.h -> expressions.h.

**Comment by aconsroe-hpe** [comment]
I could get onboard with the second change, but note that renaming expr.h would touch 97 other files. The especially ugly part of this is that nowhere else should anyone do `#include "expr-class-def.h"` since it itself doesn't include necessary things (and if you do, then things get ugly). So thats why I didn't use a filename like `Expr.h`

**Comment by aconsroe-hpe** [comment]
Reworded comment. It was the formals that take AList by value that tripped me up, not the member `list` like I had originally said, so thanks for catching that!

**Review by vasslitvinov — APPROVED** [review]
With the new wording, it is good to go!

**Pull request merged**
