### PR TITLE
Make some readability improvements to the ugni fetching amo code

### PR DESCRIPTION
**Pull request by ronawho**
Rename some variables and rework some control flow paths to make this
code a little easier to follow for people who aren't already familiar
with the code. This is cleanup based on my experience with first
learning this code, but it's taken me a while to PR it.

### CODE REVIEW

**Comment by ronawho** [comment]
@gbtitus I have no problem with just closing this if you don't think it helps readability. These are mods I made when I was first learning the code that helped me understand it better, but they may just be personal coding style choices that aren't worth merging.

**Comment by ronawho** [comment]
If you like this sort of cleanup, I also thought about making the

```c
size == 4 ? *(uint32_t*) opnd1:  *(uint64_t*) opnd1
```

pattern into a CAST_AMO_OP macro or something

**Comment by ronawho** [comment]
> For the proposed CAST_AMO_OP I actually think there's value in having that code be explicit as it is now, so readers can see directly that we're putting 32-bit AMO operands into the low-order 32 bits of the POST descriptor operand as the hardware requires. (That is, memcpy(&post_desc.operand1, opnd1, 4) would not necessarily work, depending on endian-ness.) Note also that there are other places where we're sensitive to the AMO size but the coding is different, such as here.

That code is being changed in this PR :)

But still, you convinced me it's worth keeping explicit.

**Comment by gbtitus** [comment]
D'oh!!  That's embarrassing.  My only excuse is that I looked at the changes and then went and did a totally unrelated thing for a few minutes and then responded to your comment, and I guess the changes must have simply fallen out of my head in the meantime.

**Pull request merged**
