### PR TITLE
Ensure that munging is performed for some tests that require it.

### PR DESCRIPTION
**Pull request by hildeth**
A test-specific compopts files is supplied for test/users/vass/global-j1.chpl because it uses symbols that the C compilation environment also supplies.

The test  test/trivial/figueroa/UnmangledSymbols.chpl is intended to show that munging is working correctly, so it is skipped if munging is turned off.  The global-j1 case could alternatively  be handled using a skipif.

Regressions that turned up in the umask tests with munging turned off were addressed by adding "umask" and other names from the stat.h system include file to reservedSymbolNames (compiler/passes).

### CODE REVIEW

**Comment by lydia-duncan** [comment]
For the umask tests, which symbols are causing problems and how are you finding these symbols?  I didn't run into that when creating the tests

**Comment by hildeth** [comment]
Hi Lydia:

In changeMask.chpl, the name of the umask method in the generated code conflicts with the system definition in /usr/include/sys/stat.h (chap05).
In multiTask.chpl, it is the same problem.

I have CHPL_MUNGE_USER_IDENTS=0 set in my development environment, because it makes the generated code I am studying often a bit easier to grok.

THH
________________________________

**Comment by lydia-duncan** [comment]
FYI, you'd run into the same problem for the other three tests in that directory if you run with gasnet (because they're skipped except under COMM != none).

I'd really prefer not throwing an additional flag with these tests.  If you think it is something that a lot of people will run into, I'd prefer to add umask to the reserved symbols list, so special casing isn't needed with a relatively common function.  If it is something that only you will run into, please don't change that test on master.

**Comment by hildeth** [comment]
Hi Lydia:

Let's add umask to the set of reserved words, then.

I think that munging is intended to protect users of Chapel from environment words that Chapel *doesn't* know it needs, so that is probably the better solution anyway.  Thanks for pointing that out.

THH
________________________________

**Comment by lydia-duncan** [comment]
Thanks Tom, sorry it bit you.

**Comment by hildeth** [comment]
OK, the fix is in.
I designate you reviewer. :smiley_cat:

**Comment by lydia-duncan** [comment]
Heh.  Fair enough.  @vasslitvinov might be curious about his test.

The test that specifically checks against mangled symbols may want to skip if the no-munge flag is throw, or the user has set that environment variable of yours to a level where the test is no longer relevant.  It seems to me like its intention is to check the default level of munging, so taking either/both of those steps would honor its original purpose better than throwing the flag.

**Comment by lydia-duncan** [comment]
The umask portion looks fine.

**Comment by hildeth** [comment]
@vasslitvinov , how does the compopts file for global-j1 strike you?
In the UnmangledSymbols test (trivial/figueroa), the conflicts are with _real64 and int32_t.  To me, the conflicts seem like a deliberate attempt to conflict with symbols that might be in the environment, rather than ones that Chapel should necessarily know about.  

That means that turning on munging is the better way to approach this.  But I could also be convinced to add both type names to reservedSymbolNames after verifying that Chapel either uses or introduces them.

**Comment by lydia-duncan** [comment]
The test does strike me as a deliberate attempt to conflict with those symbols.  But because Chapel shouldn't know about them, it seems like a valid test.  If the test passes, it proves we aren't bleeding symbols that Chapel shouldn't know about.  Similarly, if we force the test to always throw the munge flag, we could miss a change to the default behavior that would have much greater consequences than just these two symbol names.  Hence my suggestion to skip the test if the environment or a flag deliberately sets the munging level too low for it.

**Comment by vasslitvinov** [comment]
Either way works for me.

**Comment by hildeth** [comment]
OK, now the UnmangledSymbols test is skipped with a skipif instead.
The problem was not cured by adding the offending symbols to the reservedSymbolNames file, which means that in the reservedSymbolNames mechanism by itself does not shield Chapel from abuse of the symbols it reserves for its own uses.
However, fixing that problem is beyond the scope of this patch.

**Comment by lydia-duncan** [comment]
Awesome, thanks!  This is good to go.

**Pull request merged**
