### PR TITLE
Minor LinearAlgebra test fixes

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR does the following:

- Adds `notest` files for `dot-perf` and `setdiag-sparse-test` because we don't necessarily want to track their performance nightly. They can still be used manually while working on relevant performance improvements.
- Modifies the header comment to specify that they are intended for manual usage
- Just in case, reduces the maximum size for performance testing for `setdiag-sparse-test` as it seems to timeout for our nightly testing system.

I confirmed that tests are skipped on XC.

### CODE REVIEW

**Comment by e-kayrakli** [comment]
@ben-albrecht -- do you have any problem with this?
@wongalvis14 -- fyi

**Comment by ben-albrecht** [comment]
@e-kayrakli - I wonder if we should revert this change before merging the upcoming dot changes..

**Comment by e-kayrakli** [comment]
@ben-albrecht -- you have a good memory, it took me a while to realize that this was my PR even :)

That test seems to be testing vector `dot` only?

**Comment by ben-albrecht** [comment]
> you have a good memory, it took me a while to realize that this was my PR even :)

I followed the git history on the notest file :)

> That test seems to be testing vector dot only?

Yeah, good point. We need to get a GEMM test merged then.

**Comment by e-kayrakli** [comment]
Yeah, that makes sense. I think this test can be trivially modified to be 2D. Most of the effort would be the perf testing support files. While we are doing that we can also control 1D vs 2D in a compopts file and start measuring vector dot performance, too.

As far as I can see from our chat logs etc, there wasn't a strong motivator for avoiding tracking this performance nightly. So, if we are adding all the files for 2D case, it is not much extra effort to track 1D, too. What do you think?

**Comment by ben-albrecht** [comment]
Agreed. We should also track BLAS vs native while we're at it, though BLAS only runs on Cray configs today - so we might have to split off a separate test for that (I wonder if we could utilize a symlink?)

**Comment by e-kayrakli** [comment]
.. or maybe a PRECOMP file or something that generates compopts for the test and tosses in a BLAS option if we are on a Cray?

**Comment by ben-albrecht** [comment]
Oh I like that idea, so we'd test native everywhere and only BLAS vs native on Crays.

**Pull request merged**
