### PR TITLE
Allow a pragma to apply to an argument

### PR DESCRIPTION
**Pull request by mppf**
This PR adjusts the parser to allow a pragma to apply to a formal argument.
This will be useful for some lifetime-checking prototype improvements.

- [x] full local testing

Reviewed by @lydia-duncan - thanks!

### CODE REVIEW

**Comment by lydia-duncan** [comment]
You could write a test using `pragma "no doc"` to lock this behavior in.  It would help me understand what you've done to verify the attachment works - I would be okay with a written list of what you checked as well, but I would prefer a test

**Comment by lydia-duncan** [comment]
Another pragma works as well, if a good one comes to mind.

**Comment by mppf** [comment]
@lydia-duncan - see commit 49d61c0 which adds a new test `test/parsing/ferguson/no-codegen-formal.chpl` that exercises the feature. Using "no doc" didn't work because chpldoc doesn't know to check it for arguments.

**Comment by lydia-duncan** [comment]
Okay, I think that works for me.  This seems ready to go, thanks!

**Pull request merged**
