### PR TITLE
Further reduce communication for BlockDist scans

### PR DESCRIPTION
**Pull request by ronawho**
In #19968, we improved scan scalability by significantly reducing the
amount of communication, leaving only 16 GETS and 3 PUTs on non-0
locales. This further improves that and gets us down to 6 GETs and 1
PUT. The GETs/PUTs are all coming from the result array creation
that's part of the scan, and the scan itself has no RDMA. So the scan
itself now has 0 GETs/PUTs and just 2 coforall+ons from locale 0 and a
remote-on back to locale 0 from each non-0 locale.

This results in a minor performance improvement taking a trivial sized
scan on 64 nodes of an InfiniBand system from 0.004s to 0.003s. This
was mostly motivated by wanting to understand where the comm was even
coming from, but the minor performance improvement is nice.

This is split up in 4 commits summarized below:

Reduce comm for storing prescan results
---
Previously, we would PUT our outputSync class and prescan result to
locale 0 and then do an implicit on-stmt as part of the sync to mark
that the prescan result is ready.

This modifies the code to make the on-stmt explicit and does the
outputSync and prescan assignment inside it. This removes the PUTs (and
the GETs to acquire DR metadata). The values are now sent as part of the
on-stmt bundle (which required making some things const to enable RVF.)

This reduces comm for just the scan (excluding the result array
creation) on non-0 locales from 10 GETs and 2 PUTs down to just 6 GETs

Reduce comm to get myLocArrDesc
---

Access through a privatized instance, which takes us from 6 GETs on
non-0 locales to 3 GETs (for the non-array creation part of scan.)

Inspired by similar logic in bulk transfer code.

Write output value with output ready sync
---

Instead of GET'ing the value after reading our sync, just set the value
while we're updating the sync. This updates the BoxedSync to keep a
value stored with it. It's not generally safe because it splits the
value reading/writing from the FEB manipulation, but it works for the
single reader/writer case here.

Note that I also switched from using `sync bool` to `sync int` because
we support native qthread sync vars for int and not bool. This shouldn't
matter too much, but seemed worthwhile while here. (See #7532 for
supporting more types for native sync vars.)

This reduces comm for the non-array creation part of scans from 3 GETs
on non-0 locales down to 2 (note that the 2 remaining GETs are because
our arrays in this coforall yield references that can't be RVF'd.)

I'll also note that I think we could use `single` here instead of `sync`
but I didn't do that because we don't support using qthreads for that.
And lastly you could use the sync for the storage too for result types
that are supported by syncs, but I don't expect any real performance
benefit from that, so I didn't think it was worthwhile to do now.

Use a value iterator wrapper to update output
---

Use a wrapper iterator to get values instead of references to the sync
and output values, which allows them to be RVF'd. This takes us from 2
GETs down to 0 on non-0 locales for the non-array creation part of scan.

Part of https://github.com/cray/chapel-private/issues/3505

### CODE REVIEW

**Comment by ronawho** [comment]
FYI @chapel-lang/perf-team since we talked about this last meeting. I wasn't planning to do this originally since the comm difference isn't very significant, but I ended up getting sucked in while trying to figure out how to use the local arrays (I wanted to do something like `this.myLocArr!` to get a narrow pointer, but that wasn't privatized so everybody was getting Locale 0's version of that leading to wrong results, which led me to discovering some of the current comm and it ended up being mostly straightforward to remove.)

The other slightly interesting part is that we talked about wanting coforall intents so that we could RVF the output value updates. It turns out I didn't end up needing that, I just needed to get a value instead of a ref to the array element in order to RVF. That's done with the `valIter`, which feels little clunky, but was effective.

**Comment by bradcray** [comment]
> we talked about wanting coforall intents so that we could RVF the output value updates.

I wasn't tracking most of last week's perf meeting very closely, but:  What types of coforall intents would be useful?  (coforalls do support intents, maybe just not all of them one might want...?)

**Comment by ronawho** [comment]
>> we talked about wanting coforall intents so that we could RVF the output value updates.

> I wasn't tracking most of last week's perf meeting very closely, but: What types of coforall intents would be useful? (coforalls do support intents, maybe just not all of them one might want...?)

I think we talked about something like:

```chpl
coforall (ready, locid) in zip(outputReady$, targetLocs.domain) with (var elem = elemPerLocale[locid]) do on ready {
  ready!.writeEF(elem);
}
```

**Comment by bradcray** [comment]
OK, and I think you're right that we don't have them.  And putting them within the loop would be "too late" in the sense of "running in the wrong place" and/or "not established at task creation time as desired" I take it?

**Comment by benharsh** [comment]
The changes here look good to me - those are some great comm count improvements.

I think in other contexts we may have discussed supporting intents for on-statements, which I think would be more appropriate here than creating a task-intent with the hope/knowledge that an optimization would fire. I'd personally rather be able to just tell the on-statement to copy something over:

```chpl
coforall (ready, locid) in zip(outputReady$, targetLocs.domain) do
on ready with (in elem = elemPerLocale[locid]) {
  ready!.writeEF(elem);
}
```

Or something to that effect. I think this sort of thing would also be clearer and more reliable from a general user's perspective.

**Comment by ronawho** [comment]
> OK, and I think you're right that we don't have them. And putting them within the loop would be "too late" in the sense of "running in the wrong place" and/or "not established at task creation time as desired" I take it?

Yeah.

```chpl
coforall (ready, locid) in zip(outputReady$, targetLocs.domain) do on ready {
  var elem = elemPerLocale[locid];
  ready!.writeEF(elem);
}
```

Would result in a GET instead of bundling with on-stmt bundle.

And Ben's suggestion of supporting on-intents resonates with me too. I couldn't remember if this discussion was about task-private vars for coforalls or intents on on-stmts, but it could have been either.

**Pull request merged**
