### PR TITLE
Move assert to standard modules

### PR DESCRIPTION
**Pull request by bradcray**
This commit moves the definition of assert() to the standard modules.

The original motivation for doing this was that, for some compilations, Chapel's
assert() was conflicting with that of the C routine in the generated code.
At present, all identifiers in the internal modules are not munged, but those in
the standard modules are, so moving it out to the standard modules should
ensure that it won't conflict.

That said, with further discussion with Mike, it wasn't clear why the reserved
Symbols list (which includes assert) wouldn't have protected Chapel's assert
from conflicting with C's.  Our current best guess is that a missing dependence
in the Makefiles was causing parallel makes (like those used by nightly) to
occasionally compile codegen.cpp before reservedSymbolNames.h was
completely generated, and that supplying that dependence in
https://github.com/chapel-lang/chapel/pull/1336 ought to fix the issue.

However, we've also discussed how the internal modules are too big, how
ChapelIO.chpl is a big of a grab-bag, etc.  So having already made and
tested this patch, it seemed like a worthwhile refactoring as well (and
provides additional assurance that assert() will be renamed if the above
theory is incorrect).

I added Assert.chpl to ChapelStandard.chpl (making it part of the "automatically
use'd" set of Chapel modules) right near ChapelIO.chpl such that anything
that was relying on it before will continue to do so.  Two tests needed to be
updated due to their sensitivity to which modules are initialized/parsed in what
order.

Also cleaned up an external prototype in the vicinity of these calls that was unused
and shouldn't be exposed at the module level, IMO.

### CODE REVIEW

**Comment by bradcray** [comment]
@noakesmichael , @thomasvandoren, or @Kyle-B would be the most likely candidates for reviewing this pull request due to their participation in some of the conversation around it.

**Comment by bradcray** [comment]
ChapelStandard does use standard modules, such as Math and Types (and, implicitly,
others like IO) in the name of "productivity" -- i.e., as a young C programmer I got
tired of always having to #include stdio.h and stdlib.h and math.h and -lm for things
that seemed like they should be part and parcel of the language (and the rest of the team
in the early days agreed with that philosophy), so there are a number of standard modules
that are "auto-used".  (and others that probably aren't intended to be, but currently are
due to sloppy placement of use clauses and transitive module use semantics in the
current implementation.

For purists who argue that nothing should be use'd without doing so explicitly, there's
long been postulated that we should have a --no-auto-uses compiler flag, or some
sort of module-level directive to not auto-use anything, or the equivalent, but nobody's
championed the concept enough to implement it (nor been bothered enough by the
status quo to bother with it).  And of course, there ought to be a way to 'use' a module
that's non-transitive (if that wouldn't break the semantics for generic instantiation, which
I think is why the current use clause is transitive by default).  And/or, we should do a better
job of only 'use'ing things in standard/internal modules at non-module scope.

Anyway, your question made me remember that there is a "standard modules" section
of ChapelStandard.chpl (I'd been using a small editor window in the original edit and
hadn't noticed/rememberd), so I've moved the use down to there and am re-running
testing to see what happens.  This will also give the others a chance to chime in if they
care to (I don't think I'll merge tonight in any case given that we have the codegen.cpp
dependence fix going in anyway).

**Comment by noakesmichael** [comment]
Personally I don’t have any issue with auto including a set of “standard modules” although
I understand the opposite point of view.

Perhaps incorrectly I think of internal/ as lower-level and more basic than standard/.  I wasn’t
sure if it was viewed as appropriate to have “upward” dependencies.  I was mildly intrigued
when I recognized that the module ChapelStandard is in internal/ and not in standard/ although
this hadn’t caused me any angst.  I hadn’t remembered that there were already some upward arcs.

I am not worried about these issues but at some point I should get a better sense of the
policies regarding partitioning modules between internal/ and standard/

Regards,

Mike




On Feb 17, 2015, at 9:00 PM, Brad Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


ChapelStandard does use standard modules, such as Math and Types (and, implicitly,
others like IO) in the name of "productivity" -- i.e., as a young C programmer I got
tired of always having to #include stdio.h and stdlib.h and math.h and -lm for things
that seemed like they should be part and parcel of the language (and the rest of the team
in the early days agreed with that philosophy), so there are a number of standard modules
that are "auto-used". (and others that probably aren't intended to be, but currently are
due to sloppy placement of use clauses and transitive module use semantics in the
current implementation.

For purists who argue that nothing should be use'd without doing so explicitly, there's
long been postulated that we should have a --no-auto-uses compiler flag, or some
sort of module-level directive to not auto-use anything, or the equivalent, but nobody's
championed the concept enough to implement it (nor been bothered enough by the
status quo to bother with it). And of course, there ought to be a way to 'use' a module
that's non-transitive (if that wouldn't break the semantics for generic instantiation, which
I think is why the current use clause is transitive by default). And/or, we should do a better
job of only 'use'ing things in standard/internal modules at non-module scope.

Anyway, your question made me remember that there is a "standard modules" section
of ChapelStandard.chpl (I'd been using a small editor window in the original edit and
hadn't noticed/rememberd), so I've moved the use down to there and am re-running
testing to see what happens. This will also give the others a chance to chime in if they
care to (I don't think I'll merge tonight in any case given that we have the codegen.cpp
dependence fix going in anyway).

**Comment by bradcray** [comment]
To get the counterargument in print here, it's basically "why are you polluting my namespace without me asking you to?"  But, obviously, I prefer the auto-inclusion of things whose lack hurts the usability of getting code written quickly, supporting a 1-line hello world, etc.

ChapelStandard is a bad name (suggests something more like stdlib).  It should probably really be called something like ChapelAutoModules.  And perhaps be split into the internal modules (which, if we've separated things well, should always be included because they define "the language") and the standard modules.  I think it's appropriate to think of the internal modules as being "more built-in", but that doesn't seem like it should preclude them from calling standard stuff as well.

This discussion reminds me that one other proposed way of dealing with the "override auto-inclusion" decision would be to have a StandardAutoModules.chpl file that uses the "automatic" standard modules and then provide a flag to permit one to specify such a module, where the default for the flag is to point to the file we provide.  If we took this approach, I think StandardAutoModules.chpl (or whatever we call it) should be in modules/standard rather than modules/internal.  Without the ability to override (and with it naming internal modules -- not having been split out yet), I think modules/internal is a reasonable place for it to stay.

**Pull request merged**
