### PR TITLE
Reword 'call actual argument' in resolution error messages and quote types

### PR DESCRIPTION
**Pull request by bradcray**
While working on #16936, I found that I kept tripping over the phrase "call actual argument" in our error messages where, to me, the phrase "actual argument" seems clearer and no less precise.  This PR changes that wording.  For such resolution errors, I also added single quotes around types to better set them off from the English text of the error message (which is how things have generally evolved over time).  Thus where an error might have previously said:

```
foo.chpl:7: note: because call actual argument #1 with type sync int(64)
```

this PR changes it to say:

```
foo.chpl:7: note: because actual argument #1 with type 'sync int(64)'
```

The PR does not make any attempt to more generally extend the practice of quoting types and code segments in error messages other than the ones generated by this specific code path.

### CODE REVIEW

**Comment by e-kayrakli** [comment]
@bradcray -- have you considered dropping `actual`, too? It should be pretty clear from the context, and I am not sure how much it adds to the error message to contrast actual vs formal. So maybe

```
foo.chpl:7: note: because argument #1 with type 'sync int(64)'
```

given that the next line says "is passed to the formal bla".

I am not necessarily advocating for it, especially after seeing the number of tests it impacts :)

**Comment by bradcray** [comment]
I agree that "actual" could probably be dropped without significant loss of clarity, but I prefer to preserve it since I think it sets up an actual vs. formal symmetry in the message that feels precise to me.

I also thought about whether we could just use "actual" rather than "actual argument", but I don't think resulting phrases like "actual #1" are very clear since "actual" doesn't really feel like a noun.  If anything, I'd probably change the phrasing in the subsequent lines to "formal argument" for additional symmetry.

**Comment by mppf** [comment]
> If anything, I'd probably change the phrasing in the subsequent lines to "formal argument" for additional symmetry.

This sounds good to me.

**Comment by bradcray** [comment]
> > If anything, I'd probably change the phrasing in the subsequent lines to "formal argument" for additional symmetry.
> 
> This sounds good to me.

I wasn't signing up to do it here.  :)  Unless you (or someone) wants to require it before moving forward with this PR.

**Comment by mppf** [comment]
> I wasn't signing up to do it here. :) Unless you (or someone) wants to require it before moving forward with this PR.

Nope, not a requirement.

**Pull request merged**
