### PR TITLE
Resolve 17 passing futures on string-as-rec branch

### PR DESCRIPTION
**Pull request by lydia-duncan**
functions/deitz/nested/test_nested_var_iterator3 failed due to copy propagation
not being able to follow references through record fields.  This now passes on
the string-as-rec branch.  Tom says:

"To support allowing iterators to update record types in general, I reduced the number of cases where the iterator record and class force reference arguments to be stored by value.  These are
  - variables marked with the FLAG_TEMP_IN_ITERATOR
  - variables whose base type is marked with FLAG_ITERATOR_RECORD
  - The _this member of an iterator method, unless the method's "this" intent includes "ref"."

variables/vass/ref-to-domains-arrays previously failed because when a ref to a
domain, array or slice was made, the reference count decrements were correct but
the increments weren't.  This now passes.  Tom says:

"Changes were made in several places to get the reference counts right."

I verified that some of the settings specified by the skipif also work, since it
was specified that their output was different than the base case.  Specifically,
I verified that no-local, valgrind, and comm=gasnet testing passed.  There are
other configurations skipped, but I think we'll be fine verifying those when
this change goes in.

types/tuple/sungeun/hetTupleWithArray and types/tuple/sungeun/homTupleOfArrays
were experiencing an erroneous free of the arrays which were not allocated to
begin with.  Tom says:

"Ensuring correct reference counts would also have had this effect."

functions/bradc/intents/test_construct_atomic_intent used to experience atomics
not passed to constructors by ref by default.  Tom says:

"On both branches, default intent --> const ref for records.  On string-as-rec
we now pass ref and const ref intents by ref."

types/records/bharshbarger/remoteBlankRecord used to experience a record being
shallow copied across locales so the "data" field was pointing back at the
original locale instead of the new one, and that access of a local variable from
a remote locale yielded the remote locale id instead of the local id.  Tom says:

"To get remote strings to print correctly, I ensured that references to records
are carried through a chain of calls (except for special cases and cases I have
missed).  In no-local and multilocale runs, only references carry locale
information, so only objects passed by reference will carry along that
information.  Test cases involving records-in-tuples are currently failing in
multilocale for this reason.  Tuples are returned by value, so locality of a
tuple return value is lost.  Some significant work will be required to correct
this."

I choose to leave the skipif in place, since the purpose of the test was to
verify remote behavior.

distributions/sungeun/misc/useDummyDist was failing with a function resolution
bug - it couldn't find the type specifier for a distribution when it should be
able to, and now it can.  Tom says:

"In many places, I added calls to getValueType(), to counteract the effect of
passing more objects by reference.  My guess is that somewhere the distribution
was getting passed by reference where the type matching should have been using
the base type."

users/holtbg/tupleOfTupleIteration used to fail assertions when iterating over a
tuple of tuples because the refType field of a type was expected to be filled,
but it didn't need to be because the type itself was already a reference.  Tom
says:

"Since I use ref types more extensively, I probably made some improvements in
passing."

multilocale/local/diten/test_local2 was made a future for the string-as-rec branch
when local blocks were disabled and Ben's fixes allowed it to pass again.  May or
may not fail on darwin?

types/string/sungeun/stringInBegin used to fail to update strings from within
begin statements

parallel/taskPar/taskIntents/21-capture-in-cobegin and
parallel/taskPar/taskIntents/31-capture-in-coforall used to experience the bytes
of a string changing when a global is updated in a cobegin but not the length.
May or may not fail on darwin?

types/string/sungeun/c_string/returnString used to experience functions
returning string literals having a return type of c_string instead of string.

associative/thomasvandoren/c_string-to-string used to experience an internal
error when adding a c_string_copy key to a domain

functions/diten/param_bool_to_string and functions/diten/param_int_to_string
both requested param strings

multilocale/diten/needMultiLocales/remoteString3 was experiencing problems with
remotely accessing strings.  I removed the skipif and segment fast version of
this test.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@mppf, none of these were the futures you were worried about, right?

**Comment by mppf** [comment]
@lydia-duncan, these 3 did not pass when I tried them (on my Mac) but you are un-futurizing here:
* test/multilocale/local/diten/test_local2.chpl
* test/parallel/taskPar/taskIntents/21-capture-in-cobegin.chpl
* test/parallel/taskPar/taskIntents/31-capture-in-coforall.chpl

The others in your list do not overlap my list.

**Comment by lydia-duncan** [comment]
Hmm.  That's weird.  I will avoid un-futurizing them.

@benharsh, you might want to look at test_local2.  The test was turned into a future when Tom turned off local blocks, so there may be something more that needs doing for the fix you made to them.

**Comment by mppf** [comment]
@lydia-duncan, I think you should unfuturize them because they're not futures on master, and I want to see failures if they are regressions vs. master. I'm planning to un-futurize all of the tests I mentioned in my email (but on Monday).

**Comment by lydia-duncan** [comment]
The only reason I looked at them at all was because they passed for linux64 testing.  Fun stuff.  Okay, I will merge then, but update the note to mention that we expect them to fail for darwin testing at this time.

**Comment by mppf** [comment]
(of course, I could have bungled my experiments somehow too...)

**Comment by lydia-duncan** [comment]
I had some fun times where I was testing a version of the compiler that I hadn't rebuilt for string-as-rec, but once I rebuilt, the futures passed as expected.  Is it possible that happened?

**Comment by lydia-duncan** [comment]
Also, as an fyi, I've still got other futures on my docket, but they required more updates than just "they check out, let them in".  We can coordinate on Monday, though

**Pull request merged**
