### PR TITLE
added wrapper for qio_decode_char_buf

### PR DESCRIPTION
**Pull request by parthsarthiprasad**
Working as example for  #15216
(wrapper function in BytesStringCommon.chpl).

 wrapper function 
```chapel
proc qio_decode(buf:c_string,
                buflen:ssize_t, 
                esc: bool ): (syserror,int(32),c_int)
```

### CODE REVIEW

**Comment by parthsarthiprasad** [comment]
@e-kayrakli check this out , For cla , Ill try to get it soon, ( getting a CLA certificate).

**Comment by e-kayrakli** [comment]
Thanks @parthsarthiprasad -- This is a good step towards the right direction. But I thing there are two more major steps in this refactor. I see one of them as a must, the other one as optional and can be left as a future work.

Must: There is still too much C level stuff happening in the String code. I really would like to just pass buffer, it's size and the index where the decode should start looking and that's it. I am not happy about seeing pointer arithmetic and casts to `c_string` or `ssize_t` in the String code, and I think this refactor should definitely address those as well.

Optional/maybe difficult: I don't like errors to be returned from functions where we can simply throw errors. Ideally, the refactored-out helper should throw a `DecodeError` and the callsite should be ready to catch it. And when it catches, it acts accordingly. But this change may require more significant changes and can (and possibly should) be a future work. 

Other style issues that you should handle before the next review:
- Remove commented code
- Remove white space after `(` in function calls
- Pay attention to other whitespace style in the module
- Make sure no line is longer than 80 characters. You can break functions like
```chapel
foo(arg1, arg2, arg3
    arg4, arg5);
```

It'd be also nice if you run some tests on this before the next review. See more about [invoking start_test here](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst#invoking-start-test). I am copy-pasting from another PR review of mine:

- Run `make test-venv` in Chapel root directory
- See if you can run `start_test` on master.
  Checkout master branch and not this branch. Then see if you can `start_test test/release/examples/hello.chpl` to see if the hello world test runs successfully.
- Now for your branch, I'd definitely test `test/types/string/kbrady` and `test/release/examples/primers`
- If both of those are successful, I'd be up for running the full testing suite on this. (It takes too long and we have parallel systems to run it quicker) I can let you know any other follow up issues.

**Comment by parthsarthiprasad** [comment]
There were multiple commits and rebasing and squashing them together gave this error here (of extra file)(sighs).
(Was trying to remove unnecessary commits)
 Ill try to fix that , If nothing can be done then I'd open a new PR. rest wrapper is passing the make check test I'd change this to throw exception according to 2nd part to throw Decode Error.

**Comment by e-kayrakli** [comment]
I think (and not so sure I understand what happened there) if you pull upstream master and then rebase on top of that they that extra commit should disappear. You can also try squashing everything in a single commit.

**Pull request closed without merging**
