### PR TITLE
FCFs: add a compatibility layer to preserve the old semantics

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
FCFs: add a compatibility layer to preserve the old semantics

Introduce a config param `legacyFirstClassFunctions` which is `true`
by default. When this flag is on, Chapel's FCFs will behave as
they did in 1.27 or prior.

A recent PR improved Chapel's FCF support by adding new features.
Its current implementation leans on a heavily modified version
of the code for legacy FCFs. The PR unintentionally broke Arkouda
by making named formals significant when constructing function types.

This suggested the need for some sort of compatibility layer until
the new semantics are finalized.

When the compatibility mode is _ON_, FCFs will behave in the
following ways:

- All formals will have the default-intent only
- All formals are considered anonymous
- All formals are named 'x1'..'xN'
- Any attempt to use the new function type constructor will result
  in a compilation error

Additionally, a helpful warning has been inserted that will notify
users that any formal intent besides the default will be discarded.

While here, add comments to the `firstClassFunctions.h` header
(soon to be the closures header) which explain what each of the
functions in the header do.

TESTING

- [ ] `linux64`, `standard`

Signed-off-by: David Longnecker <dlongnecke-cray@users.noreply.github.com>

### CODE REVIEW

**Comment by bradcray** [comment]
Is there any opportunity to have the uses of the old syntax use the old semantics and the uses of the new use the new, or are the underlying implementations too intertwined to support that easily/cleanly?  If they weren't, that seems attractive from the perspective of backwards-compatibility (since they'll be deprecated soon anyway) and having the new features act as we'd like them to.  But I imagine it may not be sufficiently easy to be worthwhile.

**Comment by bradcray** [comment]
(or: Could the default for this flag depend on whether the parser sees the old syntax or the new syntax?)

**Comment by dlongnecke-cray** [comment]
I think that even if the implementations are not already intertwined - they soon will be. I am working on an effort to add new IR for function types and that further overhauls the old implementation (turning it into the "closure" type). On that branch, unless the legacy flag is thrown, the type won't even print the same way as it does now, it'll print `closure(proc(x: int, y: int))`.

I could look into "uses of new syntax use new flag, uses of old use old flag", as a followup effort, but personally I think a global switch would be a bit more helpful for myself. It's much easier to sanitize mingling of old/new features when that just can't happen (e.g., what I would do is also disable the new function-expr syntax unless you opt into the new features).

My hope was that we'd do with the flag as we've done for some other features - when we're ready to release we can toggle it and deprecate, and then after a release or two we can just remove all the old stuff entirely.

**Comment by dlongnecke-cray** [comment]
I've absorbed this PR into a much larger effort to introduce function types to the language. I'm closing it because rebasing onto this would be more trouble than it's worth at this point.

**Pull request closed without merging**
