### PR TITLE
Add flag to keep going after error for printchplenv

### PR DESCRIPTION
**Pull request by jabraham17**
Adds a new flag, `--ignore-errors` to `printchplenv`. This flag avoids exiting the script when an error is hit and just continues to do its best. This allows users to still print out some of the results, to help diagnose issues when errors are hit

Inspired by https://github.com/chapel-lang/chapel/issues/24669

[Reviewed by @ShreyasKhandekar]

### CODE REVIEW

**Review by ShreyasKhandekar — APPROVED** [review]
There are a few control flow statements which assume that `error()` will cause the program to terminate.
An example is: https://github.com/chapel-lang/chapel/blob/e7db0d7a3d9961b05f39f2e69299468ea3ff3d56/util/chplenv/utils.py#L80C5-L84C73

In this case above, the second error would be meaningless to see when using `--continue` and might confuse some users. If we can change these to be `elif`s for such cases so only meaningful errors are shown that would be nice.

You don't have to exhaustively do that, just the ones you can find easily would be nice :)

**Comment by stonea** [comment]
I like the idea of this flag, I always find it annoying when I can't get `printchplenv` to tell me what my environment is.  If for some reason, something can't be determined due to error, it'd be great if there was some way to print that out like: `CHPL_GPU: <error>`

Somewhat echoing what Shreyas said: I guess I'd be concerned that in practice getting this to work might be difficult than just charging through the `error` function.  I want to say, it's likely there's places in our code where if something errors out it's likely to cascade (i.e. subsequent pieces of code might expect some value to have been set that won't be if there was an error which causes further errors, maybe of the type that doesn't enter the `error` function itself). Though it's hard to say: maybe in practice this isn't that much of a concern; without toying around with it or trying to understand all of our possible error paths, I'm unsure.

If we're unsure about it we could always add this as a hidden flag until we gain more confidence.

**Comment by jabraham17** [comment]
grepping through `util/chplenv` for calls to error, I see 52 calls. That seems tractable to look through and see other places where we can either set the environment variable to some error value, or handle the assumption that error exits.

**Comment by jabraham17** [comment]
I found a handful of cases that needed updating, but a lot of the places where `error` is called us when a user has set an environment variable to an unsupported value. For that case, I think its more useful to leave the value as-is so that users can see what they did wrong (instead of the unhelpful `SOME_ENV_VAR='error'`)

**Review by ShreyasKhandekar — APPROVED** [review]

**Pull request merged**
