### PR TITLE
Kill slurm job if any program instance exits unexpectedly with non-0 status.

### PR DESCRIPTION
**Pull request by gbtitus**

### CODE REVIEW

**Comment by gbtitus** [comment]
@ronawho , would you review this one please?

**Comment by ronawho** [comment]
I think we also have to add --kill-on-bad-exit for batch jobs. This only adds it for interactive jobs. We use batch mode w/ nightly testing (chpl_launchcmd sets this)

**Comment by ronawho** [comment]
Let me check if sbatch has an equivalent option, or if we have to add it to the srun in the batch job: https://github.com/gbtitus/chapel/blob/srun-kill-on-bad-exit/runtime/src/launch/slurm-srun/launch-slurm-srun.c#L302-L303

**Comment by ronawho** [comment]
Looks like it's not an sbatch option (which makes sense I guess): 

If you change the linked lines from 

```c
    fprintf(slurmFile, "srun %s %s ",
        chpl_get_real_binary_wrapper(), chpl_get_real_binary_name());
```

to 

```c
    fprintf(slurmFile, "srun --kill-on-bad-exit %s %s ",
        chpl_get_real_binary_wrapper(), chpl_get_real_binary_name());
```

you should be good to go

**Comment by ronawho** [comment]
:+1: 

FYI, I'm running steam-ep under chpl_launchcmd to make sure this gets rid of the timeouts.

**Pull request merged**
