### PR TITLE
Rename etc directory to highlight/

### PR DESCRIPTION
**Pull request by lydia-duncan**
We've been discussing doing this for a while, since the directory only contains
syntax highlighting support at this point.  Finally biting the bullet.  Any
references to these files, say in your .emacs file, will need to be updated
appropriately.

I also updated the documentation that referred to the old name, and updated
gen_release to find the new directory.  Tested the gen_release changes

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@bradcray or @ben-albrecht, care to review?

**Comment by bradcray** [comment]
This isn't a review, but DIRS and LICENSE (top-level) also look like they need updates?

**Comment by lydia-duncan** [comment]
Drat!  grepdocs and grep over utils/ wasn't sufficient!

**Comment by bradcray** [comment]
Bonus point for updating grepdocs to catch these files...

BTW, my comment probably wasn't clear, but I don't think I'll have time to do a more full review in short order (so someone else should) -- I just did a quick check to see if I could find other files that needed updating.

**Comment by lydia-duncan** [comment]
Wow, DIRS is seriously out of date

**Comment by bradcray** [comment]
I was surprised to see that file -- I can't recall its purpose for being and being separate from README.files...  Maybe check the logs to see if you can find a rationale for it?  Without one, we might consider retiring it if README.files seems to do the job.  I don't think DIRS goes into the release, right?

**Comment by lydia-duncan** [comment]
It shouldn't.  The one mention of it I can find (in README.devel) lists it as for developers and seriously out of date, possibly redundant.  I think I'll just remove it if no one objects.

**Comment by bradcray** [comment]
Checking the history, it seems I added it without much explanation.  I think I'd remove it, but in a separate PR to avoid muddying this one.  While there, it might be time to rename README.dirs to dirs.rst or something more modern if you're so inclined.

**Comment by lydia-duncan** [comment]
You mean README.files?

**Comment by bradcray** [comment]
Oops, yes.

**Comment by lydia-duncan** [comment]
I feel like a file named dirs.rst is less obvious to find than README.files.  I would blame that for why I'd never given DIRS much thought before.  So I think I'll leave README.files as is for now and maybe we can make that a sidebar discussion or something.

**Comment by ben-albrecht** [comment]
Looks good to me!

**Pull request merged**
