### PR TITLE
Improve LinearAlgebra.Matrix() for heterogeneous varargs arrays

### PR DESCRIPTION
**Pull request by bradcray**
In https://github.com/chapel-lang/chapel/issues/8196#issuecomment-1231012776
@ghbrown provided some compelling examples that did not compile today
even once we added better support for heterogeneous array literals as
requested in https://github.com/chapel-lang/chapel/issues/8196 and provided in https://github.com/chapel-lang/chapel/pull/20563.  This PR attempts to improve
the signatures and implementations of these routines to support more
general matrix specifications.

One downside of enabling this heterogeneity is that it turns a parallel loop that initializes
the matrix with the arrays representing the rows into a param loop.  That said, this only
happens if the arrays themselves are heterogeneous.  Which is to say, if you have a
bunch of heterogeneous arrays that mix ints/reals, but they all unify to "array of real",
you'll stay in the parallel loop case.

While here, I also noticed and fixed a case where we hadn't updated from 1-based
to 0-based indices for tuple indexing.  :%

### CODE REVIEW

**Comment by bradcray** [comment]
@benharsh: In the "no good deed goes unpunished" category, I'm wondering whether you would review this PR, as I think you reviewed the original PR from @ben-albrecht that introduced these `Matrix()` factory routines.  As noted in the OP, @ghbrown was running into brittleness with them (even after my recent "permit heterogeneous array literals" change) due to their signatures.  I've attempted to fix that here.  I must admit that I'm not confident that we won't have other problems with these overloads going forward, but this seems to be passing LinearAlgebra testing, as well as the cases that prompted the change, so I'm hoping to consider it a baby step forward while still acknowledging that the LinearAlgebra library could use a lot more work.

I'll note that I'm running a paratest on the branch while I write this, but am not expecting to find many instances of `Matrix` outside of the packages/linearalgebra test directory.  In any case, I'll plan to post a report on the testing on Monday (since I hope you won't see this until then at the earliest anyway).

**Review by benharsh — APPROVED** [review]
This looks good to me.

I think it would be nice if we could express this constraint in the function signatures with some sort of type expression. A few examples just to demonstrate what I'm talking about:
```chpl
Arrays : [1] // ambiguous with array literals though...
Arrays : [domain(1)]
proc Matrix(Arrays : [rank=?r] ...) where r == 1
```

**Comment by bradcray** [comment]
> I think it would be nice if we could express this constraint in the function signatures with some sort of type expression.

I agree, where your third variation is most appealing to me, though I might put a `:` before the `domain`, like:

```chapel
Arrays: [: domain(1)]
```

permitting variations like:  `[_: domain(1)]` or `[?D: domain(1)]`.

**Comment by ghbrown** [comment]
@bradcray
I had occasion to type in more matrices recently and found this edge case that seems to do the wrong thing (in my opinion):
```chapel
var M = Matrix([1,0],[0,2.0]);
writeln(M); // prints integer matrix, but should be real
```
I'm essentially on `main`, so I believe I should have this fix (I tested other cases that worked beautifully) and I don't think it's opt-in.

**Comment by ghbrown** [comment]
Thanks for the explanation, I was under the impression that it performed inter-array checks for most general types.

> So I think the question for you might be whether you agree that it would be better for the Matrix() construction operation to not cast all arrays to the first's element type, but to complain instead if the subsequent arrays were not compatible.

I believe I agree with this, especially since it prevents what I would consider the "dangerous" behavior we just hit upon and since (I hope) this change shouldn't break any of our test cases from #20563 that are now working.

**Comment by bradcray** [comment]
Aha, running testing on a version without the cast, I'm seeing why the cast was there.  I think it's for cases like this, say:

```chapel
    var M = Matrix([1,2,3],
                   [4,5,6],
                   [7,8,9],
                   eltType=int(8));
```

where, without the `eltType=int(8)`, the type would be inferred to `int(64)`.  And without the cast, the implementation balks because int(64) values aren't permitted to be assigned to int(8) elements without a cast.  So to me, that suggests doing something more involved than simply using a cast or not using one.  Would you mind filing a new issue for what you would want to have happen for your test program above:

```chapel
var M2 = Matrix([1,0.0],[0,2]);
writeln(M2);
```

**Comment by ghbrown** [comment]
@bradcray
You copied (I think in error?) your program which works as is. My understanding is you want an issue and feature request where the compiler does "dangerous" casts (like my original code).

Happy to file either way.

**Comment by bradcray** [comment]
Sorry to be unclear.  The program above works on `main` today, but doesn't work if we remove the cast that exists there today, and is what is causing your reals to be downcast to int.  Basically, imagine that within the routine there's s little loop that says:

```
for all elements e
  A[i] = e: eltType;
```

where, with the cast, we get the behavior you're seeing where `eltType` is inferred to be `int` since the initial array is an array of ints, but then your array of reals is downcast to int.  But without the cast, the code in my program doesn't work because the user passed in an eltType of int(8) and wanted their int(64) arrays to be downcast to that.  This suggests a fix might be to not downcast in the "inferred eltType" case, but to downcast in the "requested eltType" case (where a minor complication is that those two cases end up falling into the same code path today.

Anyway, I was suggesting that you file an issue with the example that you posted [last night](https://github.com/chapel-lang/chapel/pull/20718#issuecomment-1271035207) essentially requesting either (a) for the library to infer eltType based on the best type considering all arrays or (b) for the library to continue inferring eltType from the first array, but to give an error if subsequent arrays didn't conform to that with implicit conversions.  (mostly with the goal of capturing the desire outside of this PR where I won't think to look for it months from now).

**Comment by bradcray** [comment]
Whoops, I see now you already have in https://github.com/chapel-lang/chapel/issues/20797

**Comment by ghbrown** [comment]
I went ahead and made that PR while I had the time on Friday, so I didn't quite catch your response in time (though it was still helpful). Thankfully our thoughts were pretty much right in line (save for the fact that I didn't request the feature (a) since it seemed like a bigger ask).

**Pull request merged**
