### PR TITLE
Issue #17182: adding checksumming to mason

### PR DESCRIPTION
**Pull request by prashanth018**
1) Added capability to store a checksum for a mason package in its toml file.
Have sorted the file paths, and computed a single hash for the project and
stored it in toml.

### CODE REVIEW

**Comment by bradcray** [comment]
@prashanth018 : If you look into the logs above, you'll see that the source code contains TABs, which we check for and guard against (the reason being that different editors render them in different ways, whereas spaces are unambiguous).

**Comment by prashanth018** [comment]
@bradcray Sure :) I'll take care of that.

**Comment by ben-albrecht** [comment]
We (@mppf and I) are holding off diving into this PR for now since it is part of a potential GSoC 2021 project. This has been communicated with @prashanth018, but I'm writing here for any other observers. 

Also, I am converting the PR to a draft, because there are many design decisions assumed within the implementation that we will need to identify and discuss before doing a full code review.

**Comment by prashanth018** [comment]
@ben-albrecht I'm planning on show casing this PR in my GSoC proposal. Should drafting of this PR be of a concern for my proposal? Thanks :)

**Comment by ben-albrecht** [comment]
> Should drafting of this PR be of a concern for my proposal? Thanks :)

Nope, just trying to clean up our list of open PR.

**Comment by bradcray** [comment]
@ben-albrecht / @mppf / @prashanth018 : I'm cleaning house tonight and wanted to check in on this PR.  What's its status?

**Comment by mppf** [comment]
The status is that it needs to be reviewed. I'm not sure if we know who will do that, yet.

**Review by arezaii — CHANGES_REQUESTED** [review]
Great work @prashanth018! We appreciate your contributions to Mason. 
We have made comments for specific areas to be updated, as noted in the review. Several of these are small/minor in nature, but there are some which require more modification. Please feel free to ask any clarifying questions.

We would also request some additional tests to: 
- check that an existing hash is updated when a single file is modified and `mason run` or `mason update` is called
- check that a project with no hash gets a new hash on `mason build` or `mason update`

One piece of additional functionality we would like to implement is a checksum calculation in `mason publish`. If that is something you feel you can add at this time, please do, if not then no worries, it can be done in a later PR :)

**Comment by bradcray** [comment]
@prashanth018 / @arezaii : Checking in on this PR to see what we should do with it after this release.  @arezaii : Are you generally interested in seeing it proceed?  @prashanth018 : Would you prefer that we take over the suggested changes?

**Comment by arezaii** [comment]
I am interested in proceeding with this feature. We can make the changes prior to the next release, if @prashanth018 would prefer that, as well.

**Comment by prashanth018** [comment]
Hey @arezaii, Thanks for reviewing the PR. I have been busy with my GSoC with chapel. Sorry for the delayed response, I just came back from my vacation. I would appreciate it if you could give me some more time to address the review comments. Thanks.

**Comment by arezaii** [comment]
That is no problem @prashanth018. Take your time, let me know if you have any questions, and feel free to respond to my comments.

**Comment by arezaii** [comment]
I have opened up a new PR that incorporates most of the requested changes at https://github.com/chapel-lang/chapel/pull/18927. Future work on this feature should be carried out there or in a new branch.

**Pull request closed without merging**
