### PR TITLE
Fix some broken code in DistributedBag.clear()

### PR DESCRIPTION
**Pull request by bradcray**
DistributedBag.clear() went through some bit rot due to the
introduction of (a) nilable vs. non-nilable classes and (b) the
override keyword.  This fixes those issues, but makes me worry
what others might be lurking.

I also added a .future and related issue #17102 because the
error that was generated by the old `.clear()` method was
difficult to interpret (and seemed inaccurate on the surface).

### CODE REVIEW

**Comment by bradcray** [comment]
Remember kids, always test your code if you want it to keep working!

**Comment by bradcray** [comment]
@e-kayrakli: Would you have time to review this?  (Should be easy).  I liked your idea of opening up an issue around improving the nilability/non-nilability error message, but haven't gotten to that yet.

**Review by e-kayrakli — APPROVED** [review]
Looks good!

To elaborate more on the nilability issue for those who weren't following the gitter chat: The error message for this was completely unrelated (it was like compiler was seeing `segments` as a 0-arg call). I haven't looked much further to see whether it was only because the lack of postfix-! or `override`, but my guess is that it may be both.

**Comment by bradcray** [comment]
It was just the `!`.  I'll add a future to this to capture that pattern and error.

**Comment by bradcray** [comment]
Issue #17102 is the issue and I've added its future here.

**Pull request merged**
