### PR TITLE
GMP.chpl: fix a few bugs in the congruent family of functions

### PR DESCRIPTION
**Pull request by cassella**
extern proc mpz_conguent_p -> mpz_congruent_p
This matches the spelling used to call the function later in the file, in BigInt.congruent_p().

The library's mpz_congruent_2exp_p()'s third parameter is a unsigned long, so change the extern proc declaration to match.

BigInt.congruent2_exp_p() needs to pass c_.mpz, not c, to mpz_congruent_2exp_p.

Without these, a program using BigInt.congruent_p() and BigInt.congruent_2exp_p() fails to compile.  With these, it works.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Hi @cassella - would you mind adding a test of appropriately calling this function, since we obviously didn't have one before?

**Comment by cassella** [comment]
I did think about adding a test.  But this one function doesn't seem any more deserving of a test than the other 100+ extern procs in GMP.chpl.  At least, it doesn't now that there's no longer anything special about it.

I still have the test I used; it'd be no trouble at all to submit it as a one-off if that still seems worthwhile.

**Comment by lydia-duncan** [comment]
I would argue that the absence of tests for the other functions is not because they shouldn't be tested but because we were lazy and there are a lot of them.  It's definitely not within the scope of this PR to add a test of all of them, but since this case bit us and we didn't test it before, it'd be nice to have a test of it for the future.

**Comment by cassella** [comment]
So, adding it'll be no trouble.  I can't decide where to add it though.

I see a few tests of BigInt/gmp routines (fac_ui, add, add_ui, and a pair of constructors) in

  test/modules/standard/gmp/ferguson/gmp_test.chpl

I'm unsure of the etiquette of adding a new test to that directory, vs creating my own directory, vs putting it in the test/modules/standard/gmp directory directly.

**Comment by cassella** [comment]
Pffft, testing things.

**Comment by lydia-duncan** [comment]
These changes seem reasonable to me.  @mppf may know something I don't, though, so I'd like him to take a brief look at the changes from the second commit.  I'm running a full test run on what's here now.

**Comment by lydia-duncan** [comment]
Passed full testing

**Comment by mppf** [comment]
Fine with me.

**Pull request merged**
