### PR TITLE
Reorganize arg bundles in the runtime.

### LINKED ISSUE #12350: sizeof(chpl_comm_on_bundle_t) seems excessive
While implementing large AM support in comm=ofi I happened to see that in that configuration the `sizeof(chpl_comm_on_bundle_t)`, which is the arg bundle header, is 136 bytes.  That seems much larger than desirable, given that it's a fixed overhead beyond the actual on-stmt body function arguments.  There are some structural differences for comm=ofi on-stmt bundles that may make them a bit larger than those with other comm layers, but it seems likely we could reduce this significantly for all the layers with a little work.

### LINKED ISSUE #12364: optimize comm=ofi AM headers
The AM header structure for comm=ofi is far from optimal.  A couple of example flaws are:

- There is an `argSize` member in the `execOn` header.  But the size of the transfer is available from the CQ event that reports the arrival of the request in the inbound request buffer.  There is thus no need to transmit the size explicitly.
- There is a `pDone` member in the `execOn` header, to say where to put a 'done' indicator on the initiating node when the `execOn` body completes.  This is `NULL` for a nonblocking `execOn`.  For nonblocking `execOn` we should instead have a separate header type which doesn't transmit the NULL pointer. We have to do a switch-stmt on the operators in the arriving requests anyway, so it doesn't make sense to also transmit a `NULL` pointer and check that to decide if the `execOn` we're dealing with is nonblocking.

This is related to #12350.

### PR DESCRIPTION
**Pull request by gbtitus**
The bundled arguments for outlined tasking and on-stmt body functions
consist of a runtime-defined header struct, followed by the arguments
themselves.  There are distinct header struct types for tasking and
on-stmt arg bundles.

On-stmt, or "comm", bundle header structs have two uses.  They support
comm layers using Active Messages to invoke on-stmt function bodies on
remote nodes, of course, but they also support internal Active Messages
for support activities such as coordinating program shutdown and doing
GETs and PUTs that cannot use comm layer RMA features.  In comm=gasnet
the opcode, if you will, of an Active Message is delivered out-of-band
from the AM's contents.  But in comm=ugni and comm=ofi the underlying
communication library either doesn't have such support or we don't use
it, so the opcode has to be embedded in the AM message itself.  This
being so, it has to be in the same place in all AM messages, so that the
target-side AM handler can pick it out of the received message and
figure out how to proceed from there.

It used to be the case that the header struct for an on-stmt arg bundle
began with a member that was the header struct for a tasking arg bundle
and then followed that with some additional information.  Thus all arg
bundles, of either kind, effectively began with the tasking header.
This allowed tasking layers to find their information in either kind of
bundle, which is necessary because the tasking layer actually runs the
body functions of both tasking and on-stmts.  (All comm layers initiate
on-stmt body functions using the tasking layer on the target node.)  The
downside of this was that comm arg bundles for internal AM opcodes, as
opposed to actual on-stmts, were excessively large because they had a
task bundle header struct on the front that they didn't need.

Here, reorganize the arg bundle headers.  Put a small member encoding
the bundle header type first in both kinds of bundles, with room in the
encoding for a reasonable number of comm layer-specific internal AM
opcodes.  This allows identifying the type of the bundle just by looking
at this initial member.  Then, rearrange the contents of the comm header
so that the comm info comes first and the task header comes second.  Now
task arg bundles still consist of a tasking header struct followed by
the bundled arguments, and on-stmt arg bundles consist of a comm header
struct followed by a tasking bundle (tasking header + args).

While a fair amount of code changed here, there are really only a few
functional changes.

The tasking header is no longer necessarily the first thing in any
bundle.  Thus the code cannot simply type-pun an arg bundle pointer to
reach the tasking information.  Instead it has to identify the bundle
header type and then get at the tasking info using the correct one.

Ugni and ofi comm layer-specific internal AM messages are now smaller,
since they can consist of just the initial layer-specific header type
code plus only those members needed for the internal AM activity in
question.  This is not a big change; to a very rough approximation these
messages are now in the 40-80 byte range instead of the 150-200 byte
range, but it's still a marginal improvement.

While here, I also took the opportunity to greatly simplify how both
comm=ugni and ofi build and handle on-stmt arg bundles, in particular
the divergence between on-stmt arg bundles that fit in a maximum size AM
request and those that do not.

Also while here, I removed the special wrapper for the "main" task in
tasks=qthreads and replaced its use with the regular task wrapper, did
some runtime include file restructuring, and fixed up a few whitespace
flaws.

This resolves Cray/chapel-private#926 and resolves #12350 and
resolves #12364.

### CODE REVIEW

**Comment by gbtitus** [comment]
This will probably be easiest to review commit-by-commit.

**Comment by gbtitus** [comment]
> When the machine opens up in a few hours I'd like to do a coforall+on scalability run to sanity check performance.

Yeah, sounds good, and I'll wait for results on that.  I spot-checked performance and saw neither degradation nor much improvement except to ofi large coforall+on Remote Task Spawn Time (which has been terrible up until now), but it would be good to have a full run to make sure I didn't miss something.

**Comment by ronawho** [comment]
>> When the machine opens up in a few hours I'd like to do a coforall+on scalability run to sanity check performance.

> Yeah, sounds good, and I'll wait for results on that. I spot-checked performance and saw neither degradation nor much improvement except to ofi large coforall+on Remote Task Spawn Time (which has been terrible up until now), but it would be good to have a full run to make sure I didn't miss something.

Just to be clear -- I was only planning on running the coforall+on microbenchmarks at 512 nodes of an XC. I did not plan on doing a full perf run, I'm happy to leave that to nightly.

**Comment by gbtitus** [comment]
> Just to be clear -- I was only planning on running the coforall+on microbenchmarks at 512 nodes of an XC.

Ah, I misunderstood.  I think I'll go ahead and merge this, then.  I'm good with letting nightlies do the full perf run also.

**Comment by gbtitus** [comment]
Oops!  I'm going to need one more commit.  I've just discovered some flaws that only appear in `DEBUG=1` builds.

**Comment by ronawho** [comment]
coforall+on perf looks good. Minor improvements for empty and average bundle sizes

---

Time to do 100K coforall+ons on 512 nodes of an XC (ugni):

```chpl
var argBundle: bundleSize*int(8);
for 1..100_000 do
  coforall loc in Locales with (in argBundle) do on loc { }
```

| bundleSize  | before | after  |
| ----------: | -----: | -----: |
|    0        |  32.5s |  32.2s |
|  512        |  38.4s |  36.3s |
| 4096        | 123.5s | 123.5s |

Where at least as of late 2018 512 byte bundles were the average user bundle size.

**Pull request merged**
