### PR TITLE
isDefaultRectangular should return false for ArrayViews

### PR DESCRIPTION
**Pull request by benharsh**
@bradcray suggested that isDefaultRectangular shouldn't be returning
true for ArrayViews. This commit makes that change and implements a
helper function, chpl__isDROrDRView, which is used in a handful of
places for specialization of functions.

Testing:
- [x] full local
- [x] full gasnet
- [x] full numa

### CODE REVIEW

**Comment by benharsh** [comment]
pinging @bradcray and @ben-albrecht as they were involved in #5662

**Comment by bradcray** [comment]
The code delta looks good to me.  I think it's good to merge once it passes testing.  Sorry again for not picking up on this earlier...

**Comment by ben-albrecht** [comment]
Looks good!

**Comment by benharsh** [comment]
Heads up: I just launched gasnet testing and plan on merging this before the end of the day.

**Pull request merged**
