### PR TITLE
Allow chpl/chpldoc flags to be linked to individually

### PR DESCRIPTION
**Pull request by jabraham17**
Adds per flag links to the chpl and chpldoc man pages in the rendered HTML (e.g. https://chapel-lang.org/docs/main/usingchapel/man.html). This allows direct links for flags, instead of having to tell users to search through the docs.

Example: https://chapel-lang.org/docs/main/usingchapel/man.html#man-module-dir

Tested locally by building docs. Also compared the generated man pages `man chpl`/`man chpldoc` and made sure there was no visual change in those docs as well.

<details>

All updates where made with the following script

```python3
import re
r = re.compile(r'(?<!:\n\n)(?<=\n)\*\*(?:-., )?\\--(?:\[no-\])?(.*?)( <.*?)?\*\*(?=\n)')
for filename in ["man/chpldoc.rst", "man/chpl.rst"]:
    with open(filename, "r") as f:
        content = f.read()
        content = r.sub(lambda m: f".. _man-{m.group(1)}:\n\n{m.group(0)}", content)
    with open(filename, "w") as f:
        f.write(content)
```

</details>

Resolves https://github.com/chapel-lang/chapel/issues/24666

[Reviewed by @DanilaFe]

### CODE REVIEW

**Review by DanilaFe — APPROVED** [review]
I think the more principled approach might be to add a new RST directive like `:flag:`, and have that generate an HTML anchor + the `**-whatever ,...** ... ` structure. In the meantime, this seems fine.

**Comment by bradcray** [comment]
This is very exciting!  I almost want to go back through old CHANGES file entries about new flags and update them to include the hyperlinks (though I suppose they wouldn't work since we pin them to that release's version number...)

**Comment by bradcray** [comment]
I'd apparently never tried this feature until today and was thinking it wasn't working because I wasn't seeing little chain link icons next to the flags, as on other documentation pages (like module docs).  Re-reading the description, I'm seeing that it doesn't explicitly say that it does that, I'd just assumed it.  Is the implication that one has to guess at the anchor name using the flag name, or read the html sources to be certain?

(I don't intend this as a complete, just making sure I understand correctly since I didn't before).  Thanks!

**Comment by jabraham17** [comment]
>  Is the implication that one has to guess at the anchor name using the flag name, or read the html sources to be certain?

Yes the implication is that you either have to assume or know the anchor name.

We could make the little chain icons work by making all of these entries be rst headers, i.e.
```
**\--[no-]count-tokens**
~~~~~~~~~~~~~~~~~~~
```
But that would change how this renders with `man chpl`

**Pull request merged**
