### PR TITLE
Fix extra -O0 for PrgEnv-cray

### PR DESCRIPTION
**Pull request by mppf**
PR #1929 caused PrgEnv-cray compiles to always include -O0 (and possibly also -O3 if fast is used). @ronawho pointed out that the extra -O0 is having an impact on compilation.

This PR fixes the problem by adjusting Makefile.cray-prgenv-cray to put -O0 in NO_OPT_CFLAGS instead of adjusting CFLAGS directly.  Then, when runtime/etc/Makefile.include computes MAKE_COMP_GEN_CFLAGS, it adds in NO_OPT_CFLAGS if optimizations are disabled (and as before it adds in OPT_CFLAGS if optimizations are enabled).

Verified that PrgEnv-cray and PrgEnv-gnu behave as expected by manually inspecting --print-commands with all combinations of --fast and -g.
Passed full local testing.

Reviewed by @ronawho - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
@ronawho - have a look at this fix for the -O0 issue?

**Comment by ronawho** [comment]
Looks ok to me

**Comment by mppf** [comment]
OK. I hope to merge this tomorrow so that we can separate performance impact from the other changes I've already made today.

**Comment by ronawho** [comment]
Sounds good

**Pull request merged**
