### PR TITLE
Also set CHPL_LLVM=none in quickstart scripts

### PR DESCRIPTION
**Pull request by mppf**
I find I've been using quickstart/setchplenv.bash in order to
quickly get a Chapel up for example when I'm testing
on several different platforms. I find that every time I do that,
I also set CHPL_LLVM=none (since many of my chapel
source trees already have LLVM built, the default is
CHPL_LLVM=llvm). This patch updates the quickstart
scripts to also set CHPL_LLVM=none. I think that's consistent
with how they set CHPL_REGEXP=none or CHPL_COMM=none.

### CODE REVIEW

**Comment by mppf** [comment]
Should these scripts also set CHPL_LAUNCHER=none?

**Comment by mppf** [comment]
@thomasvandoren can you look at this? Thanks.

**Comment by thomasvandoren** [comment]
I think setting CHPL_LLVM=none makes sense, for the reasons you mentioned.

I discussed setting CHPL_LAUNCHER=none last week at lunch with @bradcray, and the consensus was that it should not be set. The cases where it does default to something other than none are limited and understood. Plus, the quickstart experience will probably be nicer with a launcher set (e.g. on a cray-x* system it's probably better to launch onto compute nodes than try to run on the [es]login node).

Will you also update the test/setchplenv/ tests? I think you just need to add an additional check here:

https://github.com/chapel-lang/chapel/blob/master/test/setchplenv/verify_setchplenv_scripts.py#L159

Thanks!

**Comment by thomasvandoren** [comment]
The patch itself looks good. If you take out CHPL_LAUNCHER and update the test, feel free to merge. I'm happy to discuss the launcher decision more, though.

**Pull request closed without merging**
