### PR TITLE
Fix date parsing in perf graphs

### PR DESCRIPTION
**Pull request by benharsh**
Use datejs third-party library to parse dates instead of native Date.parse

### CODE REVIEW

**Comment by benharsh** [comment]
Care to review, @ronawho ?

**Comment by ronawho** [comment]
Does this end up overriding the default Date.parse?

**Comment by benharsh** [comment]
Yes, so no perfgraph.js changes needed.

**Comment by ronawho** [comment]
Ok, fine by me. Could you send me links to chapcs/16-node so I can verify this fixes the issues I was seeing on the graphs?

**Comment by benharsh** [comment]
Offline Elliot suggested that we revert the 2.0 PR until things are more stable, and I agree.

**Pull request closed without merging**
