### PR TITLE
Remove the test errhandling/diten/tryExprOpen

### PR DESCRIPTION
**Pull request by vasslitvinov**
This test is a duplicate of `errhandling/diten/throwingMethodWithDefaultArg`
so removing it. tryExprOpen as-is does not pass because of a minor glitch.

tryExprOpen was a future for #13274. #13437 fixed that issue so now
both tryExprOpen and throwingMethodWithDefaultArg work correctly.

### CODE REVIEW

**Comment by vasslitvinov** [comment]
@daviditen please double-check me post-merge.

**Comment by daviditen** [comment]
@vasslitvinov Thanks for catching that this .future was going to start passing.

It is actually slightly different from throwingMethodWithDefaultArg in that this test is using a method with a default arg instead of a standalone function with a default arg. Please add the test back, it caught a problem that throwingMethodWithDefaultArg didn't.

**Comment by vasslitvinov** [comment]
@daviditen - sure, will do. Should it be reading an existing file or a non-existing file?

> it caught a problem that throwingMethodWithDefaultArg didn't

Has that problem been resolved?

**Comment by daviditen** [comment]
@vasslitvinov, actually, I take it back - you were right that it is a duplicate. You can leave it removed.

**Pull request merged**
