### PR TITLE
Remove tcmalloc source code and supporting infrastructure

### PR DESCRIPTION
**Pull request by ronawho**
This removes everything related to tcmalloc from our code base. We used to use
tcmalloc with ugni, but as of #3321 we use jemalloc.

I basically searched the repo for all things related to tcmalloc and removed
them except for mentions in the CHANGES and ANNOTATIONS files as well some
stuff in third-party dirs. I also double checked that this was more or less the
same as #3312, which removed dlmalloc support.

### CODE REVIEW

**Comment by ronawho** [comment]
@gbtitus, mind giving this a quick check.

I don't plan on merging it until we have more confidence in ugni+jemalloc, but I wanted to get the PR up so I wouldn't forget about it.

**Comment by gbtitus** [comment]
I checked the first commit and it looks fine modulo one line I commented on.  I didn't look at the second commit because it had too many files, but if it's just the third-party deletion I don't need to. This one is good to merge with the one minor change I pointed out.

**Comment by ronawho** [comment]
Updated the GASNet comment. You're right that the second commit is just removing the actual tcmalloc source code (`gperftools-2.2/`).

Testing looked pretty good last night. Hopefully we can get rid of this next week!

**Comment by ronawho** [comment]
Everything with jemalloc replacing tcmalloc has been looking really good, so I'm going to go ahead and merge this

**Pull request merged**
