### PR TITLE
Add buffer.copy{in,out} support for strings

### PR DESCRIPTION
**Pull request by nspark**
Request review by @mppf

### CODE REVIEW

**Comment by mppf** [comment]
This looks OK with me. It needs to be clear how the strings are encoded. In some ways, we have in the I/O system already many ways of encoding strings, and this change is using a particular one (8 bytes of length and then string data). I'm not sure to what extent it's important for buffer to support other encodings.

Generally, I have in mind to one day better unify channel and buffer. Even so, I think another way to do this change would be to create a channel that refers to the buffer in question. I'm not sure how easy or hard that would be, but each channel includes a buffer right now and so it doesn't seem too hard in principle.

**Comment by mppf** [comment]
Oh yeah, the other thing is that I expect that anywhere you'd use a buffer you could use a channel created with an openmem() file.

**Comment by nspark** [comment]
> It needs to be clear how the strings are encoded. [...]

Okay. I also realized that I forgot to update the documentation, which I'll push as another commit on this PR a little later. I'll update the docs to reflect that numeric types (existing) and strings (new) can be copied in and out of buffers, as well as noting how strings are encoded.

**Comment by nspark** [comment]
@mppf I think this one is good to go, at least from the feedback so far. Can you give it the final review and test?

**Comment by mppf** [comment]
Passed full local testing.

**Comment by mppf** [comment]
@nspark - I am ready to merge this if you are satisfied with it.

**Pull request merged**
