### PR TITLE
Updating parIters to improve work partitioning in computeChunk

### PR DESCRIPTION
**Pull request by rchinmay**
Updated ``computeChunk`` method. The ranges returned to each task differ by at most 1 in size. The explanation for this function is also modified to explain the logic implemented.

### CODE REVIEW

**Comment by rchinmay** [comment]
Resolves #16795
Without this, the ``computeChunk`` method did not support strided ranges and also the algorithm implemented previously does not divide the problemSize optimally to all the tasks. In the method implemented, the size of ranges assigned to each task would be optimal (in the case of equal weightage to every element of the range).
Thanks,
R.Chinmay

**Comment by bradcray** [comment]
Hi @rchinmay — Thanks again for taking on this improvement, and my apologies that it's taken me so long to get back to it after our winter shutdown.

My main comment here is that I think we should remove the overload for strided ranges, in part because I think there are a few changes that would be required to make it robust and correct; in part because without anything in the primer using the routine, it's code that will likely become stale over time; and in part because I worry that it will add unnecessary complexity or details to the primer on a topic that's arguably orthogonal to the question of the parallel iterators themselves (even the existing routine would be nice to omit from [the rendered version of the primer](https://chapel-lang.org/docs/primers/parIters.html), but we don't have a good way to do that at present.

Beyond that, I mostly have a few minor wording and formatting improvements.

Depending on your time and preference, I could either merge your PR as-is and then make those edits in a follow-up PR; or you could remove the strided overload here, I could merge and make my other edits as follow-ups; or I could add the proposed edits here as notes and have you implement them.  Any of these is fine with me, let me know if you have a preference.

Thanks again!

**Comment by rchinmay** [comment]
@bradcray Thanks for your valuable review. I understand that the strided overload part would be obselete and would need more work in the primer to accommodate these overloads. I will remove that part. I may not be fully available from next week (due to my exams). I will be available from February first week. So I think you can do the other required changes, if you need to complete it in this month. Otherwise I would be very happy to do those changes, but I cannot guarantee its completion in this month. 
Thanks, 
R. Chinmay

**Comment by bradcray** [comment]
Hi @rchinmay — There's no pressing need to merge this PR this month, but I think it'd be nice not to have it languish as an open PR when the changes are fairly minor, so I'll plan on merging your work and then doing subsequent edits to it.  Let me know if you want me to remove the strided overload as well as part of my effort.

**Comment by rchinmay** [comment]
@bradcray I have removed the Strided Overload part. If you want me to do any other changes here, you can tell me.
Thanks,
R. Chinmay

**Comment by bradcray** [comment]
Thanks!  I lost sight of this this week, but will try to get back to it next week.

**Comment by bradcray** [comment]
Thanks again for taking the time to contribute this improvement, @rchinmay!

**Comment by bradcray** [comment]
@rchinmay — As a follow-up to this, I've done a refresh of the parIters primer that has some minor tweaks to the code and text you provided, but also implements a longstanding change that I've wanted to see in which it teaches how to write a standalone parallel iterator prior to a zippered / leader-follower case.  There's no need to spend any time on this unless you're interested, but I wanted to make you aware of the proposed changes in case you were interested:  https://github.com/chapel-lang/chapel/pull/17020

**Comment by rchinmay** [comment]
@bradcray Thank you for the follow-up PR and improving my code and explanation. I agree on writing standalone before leader/follower iterator since it easier to understand and code. I have not seen the changes in explanation part in detail yet. I will look into them soon.
Thanks, 
R. Chinmay

**Pull request merged**
