### PR TITLE
Drop back from delivery_complete to the provider's default level.

### PR DESCRIPTION
**Pull request by gbtitus**
We have been specifying the `FI_DELIVERY_COMPLETE` completion level for
our reads, writes, atomics, and sends (AMs).  Here, drop back to the
provider's default level instead.  This is still `FI_DELIVERY_COMPLETE`,
effectively, for reads and fetching atomics.  That is, the completion is
event is not delivered until the requested data lands in local memory,
as documented in the `fi_cq(3)` man page.  But for writes, non-fetching
atomics, and sends it is whatever the provider believes will perform
best while still delivering the required libfabric semantics.

We're doing this for two reasons: it should or at least may perform
better, and at least one provider (the ofi_rxm utility provider used
with a variety of base providers including verbs) actually cannot do
delivery_complete and silently provides transmit_complete instead.  This
latter bug is known, but is not likely to to be fixed soon, so we have
to work around it.

Obviously we still have to adhere to the Chapel Memory Consistency Model
(MCM) even though as of this change we no longer know the relationship
between when we see the completion for a write or a send and when the
effects of that write or send are observable. We do so by requesting
read-after-write and send-after-write transaction ordering and also,
after each write, doing a dummy read from the same node in order to
effectively synthesize delivery_complete semantics on the writes.

This current solution, while functionally correct, is less than optimal
in two ways. First, for regular reads and writes, the MCM only requires
that a task see the results of its own reads and writes to the same
address occur in program order. This current solution instead forces
all reads and writes to be seen in program order, no matter what the
addresses are. In the future we expect to do something smarter for the
same-address case, perhaps implementing a write cache and satisfying
subsequent matching reads out of that.

The other improvement we expect to make in the future us to extend the
remote memory consistency support driven by the compiler-emitted and
module code and satisfied through the runtime's chpl-mem-consistency.h
to support not only remote caching, as it does today, but also comm
layer communication. This would allow us, for example, to do a release
fence between a sequence of regular stores, and an atomic operation or
an on-stmt executeOn operation. That is something that cannot be dealt
just within the comm layer itself: it can't handle the case in which a
regular store is followed by a CPU atomic op, because the comm layer is
not involved in the latter. But once we do have that, we can drop the
synthetic delivery_complete semantics for writes.

This resolves https://github.com/Cray/chapel-private/issues/766.

### CODE REVIEW

**Comment by gbtitus** [comment]
Reviewing this commit-by-commit will be best.  The 5th commit is the work proper, the rest are supporting.

**Comment by gbtitus** [comment]
@mppf @ronawho Am I assured that, independent of whether or not the user throws `--cache-remote` to the compiler, `chpl_rmem_consist_release()` and thus (as of this PR) `chpl_comm_release()` will be called (1) before any atomic op is done and (2) before any executeOn for an on-stmt is done?  The current code in this PR assumes that such calls will occur.  If they don't I'll need to add code to cover those cases.

**Comment by mppf** [comment]
@gbtitus - I'm pretty sure the chpl_rmem_consist_release calls etc are only added with `--cache-remote` right now.

**Comment by gbtitus** [comment]
Okay, somehow I came away from our conversation in https://github.com/Cray/chapel-private/issues/804 believing that these calls were made either way.  Thanks for the clarification.  I'll adjust this PR to compensate.  @ronawho, please belay your review until I give the go-ahead.

**Comment by mppf** [comment]
@gbtitus - if you are modifying the compiler - you should be able to adjust uses of fCacheRemote. E.g. createTaskFunctions adds fences to the atomics functions. There are also some module code places using CACHE_REMOTE that you presumably also need to modify. We could change these variables into something named like "comm layer needs fences".

**Comment by gbtitus** [comment]
I'm not planning to modify either the compiler or the module code, just the runtime.

**Comment by gbtitus** [comment]
@ronawho, you can probably take another look now.  I've updated the PR comment, to begin with.  And I've switched to the synthetic delivery_complete we talked about for PUTs.  I think it still would probably be easier to look at this commit-by-commit, but it might be closer to a wash between that and looking at it all-at-once now.  So, your choice.

**Comment by gbtitus** [comment]
If you haven't started looking at this again then this won't matter, but I just now force-pushed to this branch/PR, after rebasing to pick up your #15042.  The rebase didn't require that I make any explicit changes; it merged automagically.

**Comment by gbtitus** [comment]
(Planting an informational stake in the ground here, before leaving for the day.)

Currently `library/packages/Collection/CollectionNQueens` is hanging when built with `isDeque=true`.  The hang is intermittent/sporadic and scale-sensitive.  It hangs most of the time with `nQueens=8` and even down to as small as `nQueens=4`.  It doesn't seem to ever hang with `nQueens=3` or smaller.  With `nQueens` sizes large enough to cause hangs, running with fewer threads seems to make hangs less likely.  It never hangs with `isBag=true`.  It only hangs with the 'tcp;ofi_rxm' provider; if I specify a fixed heap size and thus enable the 'verbs;ofi_rxm' provider, it doesn't hang.  The problem doesn't seem to have to do with progress, because it occurs with forced 'auto' progress as well as the default 'manual' progress.

This seems to be peculiar to `CollectionNQueens`.  I haven't see any other tests behave this way.

I at first thought this might be due to something in the synthetic delivery_complete semantics embodied in the last 3 commits, but if I back up to to before those (8d02a74) it still hangs although perhaps less frequently.  That means the original version of this PR also had this problem, and I just got (un?)lucky when testing it.

**Comment by gbtitus** [comment]
Further followup -- it turns out that `CollectionNQueens` has been timing out/hanging since at least 2020-01-01, so it may be a hitherto unnoticed instance of the hangs we already know about, and in any case its behavior isn't due to the current PR.  I'm proceeding with verbs provider and performance testing.

@ronawho I think it would be okay to start your re-review at this point.

**Pull request merged**
