### PR TITLE
Add min/max timings to ISx now that intent-based min/max reductions are supported

### PR DESCRIPTION
**Pull request by bradcray**
Now that we have min/max reduce intents, I can enable the calculation and printing of min and max timing values in ISx.  For now I've just done one version to get @benharsh 's opinion.  @vasslitvinov may want to take a proud peek as well.

### CODE REVIEW

**Comment by benharsh** [comment]
Will this work with the existing perfkeys?

**Comment by vasslitvinov** [comment]
Coolio!

**Comment by bradcray** [comment]
Ben: Yes, since the perkeys takes the first thing following the key and I whitespace separated the min..max values, it seems to work fine as expected.  I think the formatting is a little awkward/dense, but was also a little wary of it filling a full screen if printing out the subtimers...

**Comment by benharsh** [comment]
Ok! Otherwise it looks good. :+1:

**Pull request merged**
