### PR TITLE
Let exported routines have `in s: string` arguments when not building libraries

### PR DESCRIPTION
**Pull request by bradcray**
We shouldn't complain about intents on export routines that are not
supported for a given library mode when we aren't building a library.  This
simple change permits string arguments in exported routines to have
`in` intent when no (single-locale C) library is being built.  This supports
the ability for someone like @astatide who is writing a Python library in
Chapel to compile it in normal mode without changing the code.

### CODE REVIEW

**Comment by bradcray** [comment]
@lydia-duncan, @dlongnecke-cray : For your consideration...

**Comment by dlongnecke-cray** [comment]
I would prefer to have the `fixupExports` pass be skipped entirely if we are not some sort of `--library` compile. 

All internal calls to exported routines will still resolve correctly regardless of whether or not the wrappers have been made or if we are `--library` or not.

As to why it is not like this already, I am bewildered...

**Comment by bradcray** [comment]
I'm not really familiar enough with the pass to know whether that makes sense or not, and don't have a lot of time right now to do it differently—mostly, I would like the new test I added here to pass.  What would you think about merging this as a baby step forward where we explore the bigger question on our next pass on improving support for various intents?

**Comment by dlongnecke-cray** [comment]
I've posted an alternative PR here https://github.com/chapel-lang/chapel/pull/14199 that skips fixups for exported user routines unless some form of `--library` has been used.

**Comment by lydia-duncan** [comment]
I agree with David's thinking.  I'll go review that PR now

**Comment by bradcray** [comment]
Closed in favor of #14199.

**Pull request closed without merging**
