### PR TITLE
Support valgrind testing on chpldoc tests (take 2).

### PR DESCRIPTION
**Pull request by thomasvandoren**
Previously, the chpldoc tests (i.e. those with .doc.chpl suffix) were using the
chpl compiler when running under valgrind due to an incorrect if/else block.
This led to invalid option errors, because chpl was called with chpldoc options
(e.g. --text-only).

Also (previously), sub_test was only using chpldoc when "compiling" the test, but
it was still passing chpl as the compiler to all the scripts (e.g. .prediff or PREEXEC).

Update sub_test to correctly wrap chpldoc compiler commands with valgrind and
set compiler variable for the rest of the test calls (e.g. so .prediff, PREXEC,
etc work). This requires compiler variable be reset at the beginning of each new
test to the original value. Add original_compiler variable that is set outside
the for loop and used to reset compiler with each iteration.

This change was originally attempted in #1628, but since it did not reset the
compiler variable with each iteration the change had to be backed out.

* [x] full test pass
* [x] Run `start_test -valgrind test/release/examples/primers/chpldoc.doc.chpl`
  and confirm it passes.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Do you want to handle the chpldoc test directory subtest changes in this pull request?

**Comment by thomasvandoren** [comment]
Does test/chpldoc/ need to change? I have another branch that changes tests in test/chpldoc/ to use .doc.chpl suffixes instead of special sub_test, but I was waiting until later for that change...

**Comment by lydia-duncan** [comment]
Ah, good point.  Sorry for the distraction!

**Comment by thomasvandoren** [comment]
Since testing is really critical this week, changes to sub_test often have unexpected effects on nightly testing, and the changes in the PR do not have a significant impact on the release, **I propose these changes wait to be merged until after the release/1.11 branch is cut**. @ronawho suggested this and I like the idea.

**Comment by thomasvandoren** [comment]
I reran the full test pass and valgrind testing on a few primers, just to be sure. Everything still passes...

**Pull request merged**
