### PR TITLE
Add map, filter, consume on _iteratorRecord

### PR DESCRIPTION
**Pull request by daviditen**
Add _iteratorRecord.map, filter, consume.  These allow using these functional
style operations on iterators. Additional operators like `foldl` / `foldr` are
likely to also be valuable additions in the future.

Added a test that uses them in several different contexts.

### CODE REVIEW

**Comment by daviditen** [comment]
Issue #9867.

**Comment by ronawho** [comment]
Can we put these into a package module instead of having them be in something so core?

**Comment by daviditen** [comment]
OK, good call.

**Comment by mppf** [comment]
Looks fine to me but my question is more about the API design. Have you taken a look at some other language's set of functions along these lines? I'd expect there to also be something called "reduce" or "fold".

**Comment by daviditen** [comment]
@mppf are you OK with merging this?

**Comment by daviditen** [comment]
OK, I added a sentence stating that.  Thanks!

**Pull request merged**
