### PR TITLE
feat: time since epoch unix function

### LINKED ISSUE #16733: Add datetime type method to get time since Unix epoch
We would like to deprecate `Time.getCurrentTime()` for `DateTime` functionality. However, there are 2 common use-cases of `getCurrentTime()` and one of them does not translate well to `DateTime`:

1. `getCurrentTime()` to get the hour, minute or seconds of the current time since midnight in local timezone. This required some additional effort on the user as pointed out in https://github.com/chapel-lang/chapel/issues/14571. `datetime.now()` should be much better for this use-case.

2. `getCurrentTime()` to get timestamps throughout a program for timing purposes. This is not recommended, because `getCurrentTime()` is time since midnight and the time could roll into the next day between time stamps. However, many codes use it for this purpose. One can translate their `getCurrentTime()` call to `(datetime.now() - datetime.now().replace(hour=0,minute=0,second=0,microsecond=0)).total_seconds()` in the DateTime module, but this is (1) much more verbose, and (2) still prone to the day roll-over issue.

To better support use-case (2), I propose we add a DateTime function (perhaps a datetime type method) that returns the time since Unix epoch:

```chpl
// a better name might exist...
var t = DateTime.timeSinceEpoch();
writeln(t); // 1605632958
```

This feature is already available in the DateTime internals, but simply needs to be exposed through a nice interface.

Eventually, we'd want a true monotonically increasing clock feature (https://github.com/chapel-lang/chapel/issues/7536). However, this will likely be a longer term effort.

### PR DESCRIPTION
**Pull request by king-11**
fixes #16733

Signed-off-by: Lakshya Singh <lakshay.singh1108@gmail.com>

### CODE REVIEW

**Comment by king-11** [comment]
@ben-albrecht @daviditen Please review

**Comment by daviditen** [comment]
There is some discussion happening internally about whether this should be a standalone function, a type method tied to the `datetime` type, or a method on a `datetime` object like in python.

Whichever way that discussion goes, we would like it to return a `real` instead of `int` and include the fractional second represented by `timedelta(1)`. I'd also prefer to change that variable's name to avoid confusion with the `timedelta` type defined in the `DateTime` module.

**Comment by king-11** [comment]
I made the changes for it to return ```real``` instead of just seconds also if there are any updates I will make new changes as needed.

**Review by daviditen — APPROVED** [review]
Thanks!

**Pull request merged**
