### PR TITLE
Modify use of the new ChapelStringLiterals module

### PR DESCRIPTION
**Pull request by lydia-duncan**
When I merged the string changes into my branch for adding the except keyword,
this line in symbol.cpp was causing me problems.  I determined that having
the compiler insert this use was unnecessary, so I removed its addition there
and added a use statement to ChapelBase (which was where it was getting
inserted).  This will avoid unnecessary fragility in my current branch to
otherwise fix the problem.

Modified the output of test/modules/sungeun/init/printModuleInitOrder,
as the additional use statement changed its output.

Tested over std/
(verified that the chpldoc failures I initially encountered were unrelated)

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@Kyle-B, would you mind giving this a review?

**Comment by Kyle-B** [comment]
I'm not a huge fan of adding a use of `ChapelStringLiterals` in the modules since it is entirely compiler generated. At the very least it needs a comment on why it is there. What kind of issue were you running into? These two methods should be practically identical.

**Comment by lydia-duncan** [comment]
It causes special cased handling of the module during scope resolve and function resolution, basically by having it be absent from the conglomeration of use statements that are traversed in certain cases.  While it makes sense to exempt the root module from this action, the string literal module does not need this special casing.  My clean up as a result of improving the way we handle use statements would then have to respond to why it is inserted in a different manner, adding back unnecessary complexity for no gain.

**Comment by Kyle-B** [comment]
So is there no way to add a "normal" module use in the compiler?

**Comment by lydia-duncan** [comment]
You can do it in the compiler, it just seemed prettier to have it an actual use statement - see the insertion of ChapelStandard uses to every module just three lines above your original change.  Also, I'll get merge conflicts on my branch, but it's only a couple of lines . . .

**Comment by lydia-duncan** [comment]
Closing in favor of #2994

**Pull request closed without merging**
