### PR TITLE
Distribution improvements for automatic localAccess

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR does several changes in distributions to increase the coverage of
`--auto-local-access`. The original PR (#15713) only supported Block
distrubution.

Change summary:
- Add `dsiLocalAccess` to `BlockCyclic` and `Cyclic`
- Have the following dists support automatic localAccess optimization
  - `BlockCyclic`
  - `Cyclic`
  - `Stencil`
  - `Hashed`
- Adjust tests under `optimizations/autoLocalAccess` to test new dists
  - This is currently only done with a single test to keep the testing time at bay

Test status:
- [x] standard `-sdefaultRectangularSupportsAutoLocalAccess`
- [x] gasnet `-sdefaultRectangularSupportsAutoLocalAccess`

### CODE REVIEW

**Comment by e-kayrakli** [comment]
Converting to draft because I have run only very minimal testing, and probably will not fix any potential errors today.

**Comment by e-kayrakli** [comment]
One question for this PR is that the heaviness of its testing. As it stands today, it'll run all tests with different distributions based on compopts. `paratest -dirs test/optimizations/autoLocalAccess` takes about 20 minutes, which I think is too long.

I am also trying to reduce the burden of rewriting the tests in a way that the distributions can be chosen based on execopts rather than compopts. Because the good files of tests use line numbers intentionally and making the chpl files grow larger will increase the maintenance cost.

One option that I can think of is to run only one test with all the distributions whereas the others are run only with Block.

**Comment by e-kayrakli** [comment]
I am currently running the basic test with different distributions and all the others with BlockDist only.

**Comment by ronawho** [comment]
Is there already a test that something like the following doesn't trigger the optimization for `blk`:

```chpl
var d = {1..100};
var cyc = newCyclicArr(d, int);
var blk = newBlockArr(d, int);
forall i in cyc.domain do 
  cyc[i] = blk[i];
```

**Comment by e-kayrakli** [comment]
https://github.com/chapel-lang/chapel/blob/master/test/optimizations/autoLocalAccess/allDynamicsFailStatic.chpl Explicitly checks different types and makes sure that we don't have a cloned loop for such cases

**Pull request merged**
