### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in ParserContextImpl.h, chpl.rst, and IO.chpl

### CODE REVIEW

**Comment by cassella** [comment]
Hi @arezaii , a few of these are yours; could you review?

These are only the typos that will appear in compiler output or documentation.

I only tested a few random tests, which passed.  I see the affected test in `frontend/test`, but I can't figure out what to type to make that run.

**Comment by arezaii** [comment]
Thanks for fixing these @cassella!

> I see the affected test in frontend/test, but I can't figure out what to type to make that run.

To run all the frontend tests, you can do `make test-dyno`. After, to run a specific test, you should be able to `cd build/frontend-test/`, then `cd` to the proper subdirectory and run `make <testName>`.

**Review by arezaii — APPROVED** [review]
Thanks for finding and fixing these typos @cassella!!

**Comment by cassella** [comment]
Ah, ok.  I had guessed a few variants of `make dyno-test` and `dyno-tests` and `dynotest`, etc, and tried in `.`, `frontend/` and `frontend/test`.

I got this from the build step
```
  9/105 Test   #9: testParseAttributes ..............   Passed    0.03 sec
```

but I can't find a make target to run it again from `build/frontend-test/parsing`:


```
fortytwo@enodia:~/src/chapel/build/frontend-test/parsing (typos2)$ make testParseAttributes
[ 96%] Built target ChplFrontend-obj
[ 96%] Built target git-sha-obj
[ 96%] Built target ChplFrontend
[100%] Built target tests-common
[100%] Built target testParseAttributes
fortytwo@enodia:~/src/chapel/build/frontend-test/parsing (typos2)$ make testParse
[ 96%] Built target ChplFrontend-obj
[ 96%] Built target git-sha-obj
[ 96%] Built target ChplFrontend
[100%] Built target tests-common
[100%] Built target testParse
```

If I execute `./testParseAttributes`, it runs and reports all the (I gather) intentional errors, but it's not clear from the output that it passed.  It does exit with a 0 return code.

**Comment by arezaii** [comment]
> It does exit with a 0 return code.

I think those tests expect an exit code of 0 to mean they passed, so that should be good

**Pull request merged**
