### PR TITLE
Bug: Add missing string casting bugs for different types

### PR DESCRIPTION
**Pull request by kushalsingh007**
- An extension of tests in test/users/ferguson/cast_to_int_ignore_whitespace.chpl
- However it makes a good check to test these, since the each of these cases get's handles separately.

### CODE REVIEW

**Comment by kushalsingh007** [comment]
@mppf : Here is the PR for the tests, have a look when you are free

**Comment by lydia-duncan** [comment]
Ah, if we wait to add them until after your fix goes in, we won't need to add the .bad and .future files.

**Comment by kushalsingh007** [comment]
I'll remove the one's from test/users/ferguson/cast_to_int_ignore_whitespace in the PR for the fix.
But yeah, I think I'll remove the one's for real here :)

**Comment by kushalsingh007** [comment]
@lydia-duncan : Done :)

**Comment by kushalsingh007** [comment]
@lydia-duncan : removed all the .bad and .future files

The only thing that bothers me is when I compile cast_to_complex_ignore_whitespace.chpl 
I get this strange error message ( I think it's a bug)
```
In file included from /var/folders/x4/ffjxdds947n34vtf5z6hq_jw0000gn/T//chpl-kushal-81313.deleteme/_main.c:41:
/var/folders/x4/ffjxdds947n34vtf5z6hq_jw0000gn/T//chpl-kushal-81313.deleteme/IO.c:1156:1: warning:
      ignoring return value of function declared with const attribute [-Wunused-value]
creal(x_chpl2);
^~~~~ ~~~~~~~
1 warning generated.
```
So do I add a .future file and a corresponding bad file ? (the output obtained is correct though when I run it with the new changes)?
In which file should I put this warning error that is being displayed ?

**Comment by kushalsingh007** [comment]
Apart from the compilation errors mentioned above .. All things have been taken care of :)

**Comment by lydia-duncan** [comment]
If you can get the compilation warning through other means, I'd definitely make a future for it, but if it doesn't turn up with your fix and you can't find any other way to make it happen, I wouldn't worry about it

**Pull request merged**
