### PR TITLE
Enable creating nilable shared from non-nilable owned

### LINKED ISSUE #13714: Bug: can't assign to nilable shared from non-nilable owned
The following code results in a compiler error whereas it shouldn't:
```chpl
var rhs = new owned MyClass();
var lhs: shared MyClass? = rhs;
```

Tests:
```
test/classes/errors/nilability-init-field-arg/init-field-arg-oknil-shared-from-nonnil-owned.chpl
test/classes/errors/nilability-init-field-dflt/init-field-dflt-oknil-shared-from-nonnil-owned.chpl
test/classes/errors/nilability-init-var/init-var-oknil-shared-from-nonnil-owned.chpl
```

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #13714.  Allows variables and fields like:
```chpl
var c: shared C? = new owned C();
```
Suggested by @benharsh. Enabled by #13904.

### CODE REVIEW

**Comment by mppf** [comment]
Huh, I would have expected this PR to be editing an `init=` based on the example.

**Comment by vasslitvinov** [comment]
> I would have expected this PR to be editing an init= based on the example.

Yes, that would be preferable. How do you suggest doing it?

**Comment by benharsh** [comment]
I was expecting a change to ``init=`` as well, but the corresponding ``init=`` for this pattern just forwards initialization to a ``this.init(...)`` call. That's OK with me.

**Comment by bradcray** [comment]
I'm not sure I understand what the line of code here means.  I allocate a new owned thing and then let multiple things share it?  How is this better than / different from `var c: shared C? = new shared C();`?

**Comment by mppf** [comment]
@bradcray - I think the idea is that we have already an `owned` thing and would like to convert it to a `shared` one (leaving the owned thing storing nothing/nil). This PR is about enabling that conversion (which we had previously) to work when the shared type is nilable but the owned type was not.

**Comment by bradcray** [comment]
Is the `owned` thing non-nilable?  Is the idea that we'll only do this when the owned thing is expiring?

**Comment by mppf** [comment]
> Is the owned thing non-nilable?

Yes

> Is the idea that we'll only do this when the owned thing is expiring?

I think that's a reasonable expectation, but we don't really know what we are going to do with the move-from-expiring-value case yet. (It's not an error now...)

**Comment by vasslitvinov** [comment]
> Is the idea that we'll only do this when the owned thing is expiring?

We also allow (nilable owned) <-- (non-nilable owned).

What Michael said.

**Comment by bradcray** [comment]
I feel confused.

**Comment by vasslitvinov** [comment]
To rephrase what I said, we have another case that is morally the same as the case that this PR enables. What we do in both these cases depends on the t.b.d. move-from-expiring-value  design. So this PR simply makes the two cases behave in the same way today.

**Comment by bradcray** [comment]
Offline, Michael confirmed my suspicion that we don't think that the current behavior is correct or defensible in the long-term, simply that it's where we are at present.  I wasn't getting any of that from the discussion above.

**Pull request merged**
