### PR TITLE
Retire submitted chameneos entries

### PR DESCRIPTION
**Pull request by benharsh**

### CODE REVIEW

**Comment by benharsh** [comment]
@bradcray : we recently discussed NOTEST-ing these tests. Should we use this as an opportunity to do so?

**Comment by benharsh** [comment]
@bradcray : Just added some commits that NOTEST the submitted chameneos, could you review?

**Comment by bradcray** [comment]
This looks fine to me, thanks.  I might have preserved the `.perf*` files as well to snapshot the configurations we were testing when the tests were retired, but would be fine with it going in either way.

Ultimately, we'll want to push the submitted meteor and thread-ring codes in here as well, but I understand that this PR is striving to address last night's perf testing failures.

**Comment by bradcray** [comment]
(BTW, I reviewed just by inspecting the diff, not by grepping the source tree or running testing to see whether anything was missed...).

**Pull request merged**
