### PR TITLE
initial import of matrixmarket serialization format for chapel

### PR DESCRIPTION
**Pull request by ct-clmsn**
module provides basic matrixmarket file serialization. this chapel implementation is inspired by gensim's implementation. matrixmarket format is supported by python (scipy.io) and matlab (for more information on this format: http://math.nist.gov/MatrixMarket/formats.html) matrixmarket format can help with language interoperability.

### CODE REVIEW

**Comment by ct-clmsn** [comment]
@vasslitvinov going to make a patch to this PR in a few days. Recently found some bugs in the existing implementation.

**Comment by vasslitvinov** [comment]
@ct-clmsn great to see the bugs fixed!

Here are a couple of other things that need to be adjusted:

* Provide a couple of tests for this code. I would expect at least (a) a test that reads a data file then writeln() the matrix and (b) a test that declares a matrix and initializes it e.g. using an array literal syntax then writes it to a file, with a .prediff comparing that against the expected. I will be happy to help set up the tests.

* Prepend the contents of the commit message to the comment right before the module declaration. That comment will become part of chpldoc for the module, so it should be written for the module users.

* Define destructors for MMWriter and MMReader classes and have them invoke close(). Define close() for MMReader. Have mm_read() destruct 'mr'. Remove "mv.close()" from mm_write() because that will be done as part of "delete mw".

* The above makes me wonder whether MMWriter and MMReader should be records instead of classes. Do you have any strong arguments in favor of classes or perhaps in favor of records?

* The statement "var toret = mr.read_file()" copies the array. We probably do not want that. Instead, either simply "return mr.read_file()", or have 'toret' be an alias: "var toret => mr.read_file()".

* Avoid lines longer than 79 columns whenever practical. In particular, wrap your module comment and the assert() call(s).

* Indend the contents of the module consistently. E.g. both class declarations and the functions outside the class should start at the same indentation level.

**Comment by vasslitvinov** [comment]
Two other adjustments, for close() both in MMWriter and in MMReader:

* In close(), also close the file descriptor 'fd'.

* In close(), do not invoke channel.flush(). That's because channel.close() does the same synchronization.

**Comment by vasslitvinov** [comment]
@ct-clmsn  - good changes. When you are overwriting 'fin' in read_header(), please close() the previous 'fin'.

Can you clarify your question about serial vs. parallel reads? I am unclear which reads you are talking about.

**Comment by ct-clmsn** [comment]
right now read_file has a serial loop to load rows from the file into the 2d array. should that loop be a forall (parallel read)?

**Comment by vasslitvinov** [comment]
I suggest to start with a serial loop, so we have a baseline implementation.
Of course feel free to implement parallel reads, too.

**Comment by ct-clmsn** [comment]
started working on a modified mmread that could support multiple reads using sys_mmap - hit a couple road blocks, expect an update soon (along with the other requested modifications - unit tests are next)

**Comment by mppf** [comment]
Hi @ct-clmsn, I havn't looked at this patch in detail but it seems to me that you shouldn't need to use sys_mmap in order to achieve parallel reads. For one thing, the file/channel distinction should allow you to leave a file open and have many parallel channels open at different positions. For another, there is a hint you can pass when opening a file to ask it nicely to please implement the I/O with mmap.

**Comment by ct-clmsn** [comment]
@mppf just saw your post about IO hints for memory mapping - after having made the previous commit...went back through the IO documentation and made what I *think* are the appropriate changes. Personal note - code looks *a lot* more readable right now. Left the previous version that leans on Sys module functions commented out - the version that uses sys_mmap styled functions - as a point of comparison for code review. IO performance has dramatically improved (currently processing 125 megabyte file is significantly faster than the sequential version).

@vasslitvinov codes updated with parallel processing in mind - going to have that promised unit test added into the testing directory very soon.

**Comment by ct-clmsn** [comment]
@mppf thanks for the tip to review the IO features - managed to boost performance significantly without having to jump through a bunch of ridiculous implementation hurdles!

**Comment by vasslitvinov** [comment]
@ct-clmsn great to hear, looking forward to your commit!

**Comment by vasslitvinov** [comment]
@ct-clmsn what is your timeline for getting this PR ready to merge?

**Comment by ct-clmsn** [comment]
@vasslitvinov planning to wrap it up in ~2 weeks. Had some issues with unit-testing last fall and it fell on to my backlog. Thanks for checking in!

**Comment by vasslitvinov** [comment]
@ct-clmsn we look forward to having it merged!

**Comment by azadcse** [comment]
Hi,
This is a great addition. I tried several matrices from the University of Florida sparse matrix collection. But, none of them was read successfully. For example, tried http://www.cise.ufl.edu/research/sparse/MM/Muite/Chebyshev1.tar.gz

Called: MatrixMarket.mmread("Chebyshev1.mtx");

I received this error: error: bad format: malformed number in channel.readf(fmt:string, ...) with path "Chebyshev1.mtx" offset 46

Is there an example that I can try?

Thanks

Ariful

**Comment by ct-clmsn** [comment]
@azadcse @vasslitvinov @mppf - will be making an update PR with test cases next week. apologies for this being the everlasting-PR!

**Comment by azadcse** [comment]
Thanks @ct-clmsn. 
I think the problem that I reported was related  comments in the matrix market file.
I changed the last few lines read_header() function, and it got rid of the error message.

// test for files that have a % beneath the matrix market format header
      var percentfound:string;
      var offset = fin._offset();
      fin.readline(percentfound);
      while(percentfound.startsWith("%"))
      {
        offset = fin._offset();
        fin.readline(percentfound);
      }

      // rewind channel by length of the last-read read string
      fin = fd.reader(start=offset, hints=IOHINT_SEQUENTIAL|IOHINT_CACHED);

**Comment by ct-clmsn** [comment]
@azadcse - yep. I wasn't expecting matrixmarket files to have several % lines after the header %. Went back and made several modifications. I still need to add Sparse storage support - everything is dense right now - the UF spMat data sets are a great way to put the module through it's paces. I'm about to added storage for complex matrices and getting sparse storage to work correctly. Should have something to put into a PR in a day or two.

**Comment by ct-clmsn** [comment]
@azadcs @mppf cleaned up the interfaces and got the code working on random sample files from the university of florida site.

**Comment by mppf** [comment]
hi @ct-clmsn - this PR seems to include some libhdfs3 changes, but I think those were already merged into master. I recommend creating a different PR that just has the matrix market files / commits. It might also work to merge your branch with master again. Either way, we need to get to a place where the "Files Changed" tab in github shows only the new code.

**Comment by ct-clmsn** [comment]
@mppf the libhdfs3 references are probably artifacts from last fall. *sigh* will make a separate branch against my fork and "redo" the PR. thanks for double checking.

**Comment by mppf** [comment]
Closing because this PR moved to #3997.

**Comment by vasslitvinov** [comment]
I am un-assigning myself in favor of Michael.

**Pull request closed without merging**
