### PR TITLE
RVF all block and cyclic arrays

### PR DESCRIPTION
**Pull request by bradcray**
Now that arrays are always RVF'd (#12985) and Block and Cyclic arrays have serialize/deserialize methods, it's a simple matter to always serialize/deserialize them.  This doesn't present a savings over what we've done on master recently, but I believe removes the need for special-case code in the compiler to handle these cases and to lean more on RVF and the remote serialization interfaces.

TODO:
- [ ] is there compiler code that could/should now be simplified?  (or would that need to wait until all privatized distributions are RVF'd?)
- [ ] resolve failures below due to thwarting fast-ons

### CODE REVIEW

**Comment by bradcray** [comment]
This currently fails for the following tests because they don't print out an optimized on-clause diagnostic message from the compiler that they used to.  I need to look into these to see whether anything is really lost or whether it's just that with the use of RVF, we don't trigger a code path that handled such cases manually before (?)

[Error matching program output for distributions/robust/arithmetic/optimizations/optimizeOnClauses_basic]
[Error matching program output for distributions/robust/arithmetic/optimizations/optimizeOnClauses_basic_record]
[Error matching program output for distributions/robust/arithmetic/optimizations/optimizeOnClauses_basic_tuple]
[Error matching program output for optimizations/sungeun/optimized-on/test_OptimizedOn_Block1]
[Error matching program output for optimizations/sungeun/optimized-on/test_OptimizedOn_Block2]
[Error matching program output for optimizations/sungeun/optimized-on/test_OptimizedOn_Block3]
[Error matching compiler output for optimizations/sungeun/optimized-on/test_OptimizedOn_RA]

**Comment by ronawho** [comment]
Taking a simplified version of `optimizeOnClauses_basic`:

```chpl
use BlockDist;

config const n1 = 100;
const Space1 = {1..n1};
var A1D = newBlockArr(Space1, int);

on Locales[numLocales-1] do {
  local {
    A1D[n1] = n1;
  }
}

writeln(A1D[n1]);
```

With this PR there is an autoDestroy for the deserialized type that is thwarting the fast-on (I think the auto-destroy will end up being a no-op, but it has an on-clause inside it that would be illegal to call in the AM handler.)

**Comment by bradcray** [comment]
Thanks for that analysis!

**Comment by bradcray** [comment]
Thinking out loud:  I've been wondering whether the `owned` field in arrays could be made into a `param` such that for cases like this where we know that a deserialized array is a temp/copy that doesn't own the original, we can statically not observe the on-clause within the destroys and not thwart RVF.

(Or, if `owned` can't be changed in this way for some reason, could/should we add a similar `param` (call it `knownUnowned`) that would be used when it was `true`, and where we'd fall back to `owned` when it was `false`?)

**Comment by bradcray** [comment]
Closing until I have time to get back to performance / slicing issues.

**Pull request closed without merging**
