### PR TITLE
Deprecate ItemWriter and no-doc ItemReader

### LINKED ISSUE #19318: I/O module: hide ItemReader and ItemWriter types and the methods that get them as implementation details
The records `ItemReader` and `ItemWriter` and the methods `channel.itemReader` and `channel.itemWriter` are used to support the implementation of `channel.lines`.  They do not seem to be used in their own right.  The I/O subteam proposes viewing these as implementation details and removing them from the IO documentation

### PR DESCRIPTION
**Pull request by benharsh**
Resolves #19318 

This PR deprecates the `ItemWriter` type because it is not used anywhere except for a single dedicated test (that this PR moves under the deprecated directory).

This PR also hides the implementation detail that is `ItemReader` in documentation.

- [x] make docs
- [x] full paratest

### CODE REVIEW

**Review by lydia-duncan — APPROVED** [review]
Looks good, thanks!

**Comment by benharsh** [comment]
Turning this into a draft for a moment while I deprecate ItemWriter rather than removing it outright.

**Review by lydia-duncan — APPROVED** [review]
Looks good to me, thanks Ben!

**Comment by bradcray** [comment]
I haven't really followed this effort, but am not immediately understanding why itemReader would not need to be deprecated as well?

**Comment by lydia-duncan** [comment]
It's used under the covers by channel.lines().  So we "no doc"ed it instead

**Comment by bradcray** [comment]
My concern is that it was documented in 1.26, but then suddenly disappears in the `main` documentation.  Not that I'm betting a ton of users are relying on it, but it seems like anything documented should be deprecated before disappearing?  W.r.t. the `channel.lines()` use, could both it and itemReader use an internal helper routine such that the deprecation warning would be applied to itemReader but not the internal routine or `channel.lines()`?  Or are we just placing a bet that nobody is using itemReader and that nobody will notice that it's gone away?

**Comment by lydia-duncan** [comment]
This is probably worth a broader group discussion, since I think we've had other symbols that we've decided were implementation details and just "no doc"ed instead of deprecating.  Ben, would you be up for starting that discussion, or shall I?

**Comment by benharsh** [comment]
I can open an issue to prompt discussion of the broader topic (no-doc-ing instead of deprecating).

@bradcray : I can work on splitting out the functionality into a new internal type for ItemReader and channel.lines to use.

**Comment by lydia-duncan** [comment]
I would consider them both in the same category, but since ItemWriter was disappearing entirely, that's why we decided to add the deprecation warning (since programs using ItemReader wouldn't break, they'd just start relying on something that is more officially an implementation detail)

**Comment by benharsh** [comment]
After a brief offline discussion, I'll be opening up a new PR that properly deprecates the ItemReader name, while preserving the internal type somehow (hopefully through a simple type alias).

**Pull request merged**
