### PR TITLE
Array concatenation function added

### PR DESCRIPTION
**Pull request by Deeksha96**
This pull request is in reference to the issue #8802 
I can't figure out the error type if dimensions of two arrays do not match, i.e `if(dimlist1 != dimlist2)`. Please review this PR and suggest the error type.

### CODE REVIEW

**Comment by Deeksha96** [comment]
@ben-albrecht  Now that the master is unfrozen, please review this PR as I will be engaged in my semester exams from next week.

**Comment by ben-albrecht** [comment]
Hi @Deeksha96 - thanks for the contribution.

Some quick high-level comments:

- Please add tests for this routine
- Please check spelling (you can use `chplspell` tool to automate this)
- Please keep coding style consistent with the rest of the module

I'll give more in-depth code review afterwards.

 I am not sure if this belongs in `LinearAlgebra` module or somewhere else yet, e.g. standard array interface.  I've added the design review tag until we figure this out.

**Comment by mppf** [comment]
Hi @Deeksha96 - you probably just need to install cblas.h, see issue #8848 where somebody ran into a similar issue.

E.g. on Ubuntu:
```
apt-get install libblas-dev
```

**Comment by ben-albrecht** [comment]
@Deeksha96 - I'm going to close this PR for now, but I am happy to reopen whenever you find a chance to revisit it.

**Pull request closed without merging**
