### PR TITLE
Reduce intents for miniMD

### PR DESCRIPTION
**Pull request by benharsh**
At the time miniMD was written reduce intents were not supported, so I used atomics to get better performance. This is no longer necessary now that + reduce is supported.

### CODE REVIEW

**Comment by benharsh** [comment]
@bradcray and @vasslitvinov might be interested in reviewing.

**Comment by bradcray** [comment]
Looks good to me.  This isn't a change, but a curiosity:  What happens when store is false?  Does the loop just become a no-op?

**Comment by benharsh** [comment]
I think the loop would still compute the force on each atom, which will then be used to move the atoms around the space. The 'store' variable ought to indicate when we need to preserve some of that information in order to compute things like temperature, energy, and pressure.

**Comment by bradcray** [comment]
OK, thanks!

**Pull request merged**
