### PR TITLE
Throttle compile-only tests when the execution limiter is enabled

### PR DESCRIPTION
**Pull request by ronawho**
PR #3928 added an execution limiter to limit how many chapel tests would execute concurrently. This enabled us to compile concurrently, but still only run one chapel executable at a time. Chapel executables can use the whole machine, so we want to avoid multiple executables from contenting with each other. For most tests that compile then execute we'll eventually just have a single executable running with no interference. However, if you have a lot of consecutive compile-only tests, the non-stop chpl compilations can also cause interference.

Avoid interference from normal consecutive compile-only tests (tests that don't generate an executable, but match expected output) by waiting for the last executing test to finish before going on.

Resolves Cray/chapel-private#4967

### CODE REVIEW

**Comment by ronawho** [comment]
Testing for this is running a slow-ish test alongside a long string of compile only tests:


```sh
export CHPL_TEST_LIMIT_RUNNING_EXECUTABLES=true
start_test test/studies/adventOfCode/2021/bradc/day4a.chpl --numtrials 100
```

```sh
export CHPL_TEST_LIMIT_RUNNING_EXECUTABLES=true
start_test test/classes/casts/generated-cast-tests/
```

Before:
```sh
[Executing program ./day4a  < day4.in]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 7.857 seconds]

# Other compile-only tests started mid-execution
[Executing program ./day4a  < day4.in]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 21.042 seconds]

[Executing program ./day4a  < day4.in]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 46.918 seconds]
```

Now:
```sh
[Executing program ./day4a  < day4.in]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 7.916 seconds]

# Other compile-only tests started mid-execution
[Executing program ./day4a  < day4.in]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 8.610 seconds]

[Executing program ./day4a  < day4.in]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 11.782 seconds]
```

**Comment by ronawho** [comment]
Doesn't seem to be any impact (run with this PR was a little faster, but almost certainly within normal variation)

```sh
chap-login: test (main) $ paratest
paratest took 6 minutes and 41 seconds

chap-login: test (throttle-compile-only-tests) $ paratest
paratest took 6 minutes and 39 seconds
```

**Comment by bradcray** [comment]
I'm wondering whether we should merge this on Elliot's behalf given that day4a is one of the noisiest aspects of testing currently (other than system issues).  I didn't realize it'd already been reviewed, or I would've proposed this Friday.

**Comment by bradcray** [comment]
Thanks for implementing this, Elliot!

**Pull request merged**
