### PR TITLE
Control numCodepoints caching with a config param

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR avoids an expensive check in string implementation, but adds a secret
back door to re-enable it.

This is what I propose we should do instead of #18399

This code was added in #15870 to tighten up the ways in which strings are
created. When we added number-of-codepoints caching in #15758, we have seen that
we've had to change how strings are created in many places in the standard
libraries. I think 15870 put us in a good place, but I still have some
uneasiness around caching number of codepoints and relying on that cached value.

But the current state of things is not ideal, either: we just halt with
`--boundsChecking` if there's a discrepancy. With no way for the user to escape
that, it is only marginally better than letting the wrong value survive.

So, this PR adds a no-doced `config param useCachedNumCodepoints = true` in the
string implementation. This way, even with `--boundsChecking` we don't count
number of codepoints each time we need that value, but we have a way of avoiding
using the cached value if we see any issue with caching.

Test:
- [x] types/string/cachedNumCodepoints
- [x] full standard
- [x] full gasnet

### CODE REVIEW

**Comment by bradcray** [comment]
This looks fine to me (other than the linebreak before `else` :D )

**Comment by e-kayrakli** [comment]
> other than the linebreak before else :D 

Ah, so you're the one who wrote all those funny `} else {`s in our code! :P

**Review by mppf — APPROVED** [review]

**Comment by mppf** [comment]
FWIW I think a reasonable alternative would be to make a config param to opt in to the check, but this approach is also OK with me.

**Comment by mppf** [comment]
@e-kayrakli - would you be able to remove the `-O` and custom timeout for the `readcsv` test in this PR?

**Comment by e-kayrakli** [comment]
> would you be able to remove the -O and custom timeout for the readcsv test in this PR?

Done.

I just fired a gasnet paratest just in case, will merge if it is clean (why wouldn't it be??).

**Pull request merged**
