### PR TITLE
Support left-rotate ("<<<") and right-rotate (">>>") operators

### PR DESCRIPTION
**Pull request by nspark**
This PR adds:

- left-rotate ("<<<") and right-rotate (">>>") operators to the Chapel language
- left/right-rotate operator support to the BitOps module
- a simple test of operator-based rotates using BitOps

Note too that:

- the flex/bison source changes are in e12db88
- the flex/bison generated files changes are in 1780ab8 

(I apologize in advance for hacking on the compiler.)

### CODE REVIEW

**Comment by nspark** [comment]
Apparently, this change has _really_ slowed down the compiler. For example, the compilation times from of `test/modules/standard/BitOps/*.chpl` of master (as of 1256f2e):

```
[Elapsed compilation time for "modules/standard/BitOps/clz" - 3.544 seconds]
[Elapsed compilation time for "modules/standard/BitOps/ctz" - 3.518 seconds]
[Elapsed compilation time for "modules/standard/BitOps/parity" - 3.520 seconds]
[Elapsed compilation time for "modules/standard/BitOps/popcount" - 3.549 seconds]
[Elapsed compilation time for "modules/standard/BitOps/rotl" - 4.361 seconds]
[Elapsed compilation time for "modules/standard/BitOps/rotr" - 4.362 seconds]
```

and of my branch (as of 50c8794):

```
[Elapsed compilation time for "modules/standard/BitOps/clz" - 6.739 seconds]
[Elapsed compilation time for "modules/standard/BitOps/ctz" - 6.842 seconds]
[Elapsed compilation time for "modules/standard/BitOps/parity" - 6.846 seconds]
[Elapsed compilation time for "modules/standard/BitOps/popcount" - 6.680 seconds]
[Elapsed compilation time for "modules/standard/BitOps/rotl" - 8.405 seconds]
[Elapsed compilation time for "modules/standard/BitOps/rotr" - 8.586 seconds]
```

Yikes.

**Comment by nspark** [comment]
Hmm. I have two full checkouts of master, both current as of 1256f2e. One is fast (reported above); the other is just as slow as the op-rotate branch.

**Comment by ben-albrecht** [comment]
@nspark I'm not sure what to make of your observations. There has not been any [compiler performance](http://chapel.sourceforge.net/perf/chapcs/?startdate=2016/04/05&enddate=2016/04/26&suite=compilerperformance) regressions on master lately.

Are you able to identify which of your commits is causing the regression?

**Comment by nspark** [comment]
@ben-albrecht: @noakesmichael pointed out in an off-GitHub message that one should expect performance differences between compilers built with CHPL_DEVELOPER set and unset. I think this (newbie compiler-hacking mistake) was the source of my timing differences.

**Comment by mppf** [comment]
This change looks good to me. Needs testing. Might need to check with other developers that we're OK adding <<< and >>> operators (I am).

**Comment by bradcray** [comment]
I keep forgetting this is here rather than cooking somewhere on a Nick branch.  A few notes:

* I think someone who wants to advocate for this (whether Nick or another internal developer) should propose it out to chapel-developers or chapel-users to see if anyone objects, citing precedent for the operators in other languages -- less because I anticipate real objections and just in the spirit of open-ness about core language changes.  Precedence (relative to other operators) might also be something to tackle in that thread (what it is, why that's right).  

* The documentation (spec, specifically I'm thinking) also looks like it needs to be updated to include the new operators.

* I haven't reviewed this at all closely or carefully, but it seems a little surprising to me that the operators are only defined in the BitOps module (which must be manually included, or at least is intended to work that way) rather than in ChapelBase.  I'm thinking we're making them part of the language rather than the library (in that there's compiler support for them).  Is there any reason we'd want no definitions of <<< and >>> by default?

* This one is just me thinking out loud:  Having gotten bitten by overly generic max/min operators recently, I also wonder whether the signatures here should be more of the x:int(?t), y: int(t) style that the + operators and such are defined using (though I haven't thought about that question enough to have any confidence in it... I guess maybe these are different because the operators are less symmetrical?  I'm noting that the << and >> operators take int(?t) or uint(?t) as the LHS arguement and 'integral' as the RHS argument, so perhaps this is just as good.

**Comment by nspark** [comment]
I'm not particularly committed to this PR right now (no pun intended), and would rather prioritize other Chapel projects. If I revisit this one in the future, I'll address @bradcray's feedback. I'm closing it for now.

**Pull request closed without merging**
