### PR TITLE
Support malloc,free,chpl_malloc,chpl_free in extern blocks

### PR DESCRIPTION
**Pull request by mppf**
A user request I had noted is support for malloc and friends in extern blocks.

Before this patch, use of malloc/free/etc
in an extern block generates an error (from chpl-mem-warning-macros.h).
This patch changes it to call the system allocator and adds
a test demonstrating how to call the Chapel allocator if that is
the desired functionality.

 - Creates runtime/include/chpl-mem-no-warning-macros.h
    which redirects malloc etc. to the runtime calls (e.g. chpl_malloc).
 - Includes chpl-mem-no-warning-macros.h at the top of the C
   files storing the extern blocks

I don't believe that it makes sense to replace malloc/free/etc
using #defines since that could lead to allocations and frees
across the 2 allocators. Instead, I think that the system
allocator should be replaced with the Chapel allocator
in such cases as I have demonstrated in PR #1755.

### CODE REVIEW

**Comment by mppf** [comment]
For after 1.11 release

**Comment by mppf** [comment]
We might like to do other things to override malloc in all of the libraries linked with our program. See
http://stackoverflow.com/questions/929893/how-can-i-override-malloc-calloc-free-etc-under-os-x ... and the Heap Layers project (on github). Also see glibc's malloc hooks and how the memusage program overrides mmap and mmap64 with LD_PRELOAD.

**Comment by hildeth** [comment]
The code looks good.

On the "should we be doing this" question:  I think this is OK.  Code that knows about Chapel's low-level memory allocation can call those macros directly.  Code that is ignorant of that should get what it asks for.  That is, a call to malloc really should go to the system allocator -- just as is implemented in this patch.

Others should feel free to chime in, though.

**Comment by mppf** [comment]
Tom - I think that the other "should we be doing this" issue with this patch is that it creates e test to say that #including "chpl-mem.h" and calling chpl_malloc and chpl_free is reasonable within C code.

**Comment by mppf** [comment]
Thanks for the review!

**Comment by mppf** [comment]
starting testing...

**Comment by mppf** [comment]
passed local testing

**Pull request merged**
