### PR TITLE
New ISx study version

### PR DESCRIPTION
**Pull request by benharsh**
This is a study version that should demonstrate better multi-locale performance when compared to the release version. Here are some of the modifications:
- use local blocks to squash wide pointer overhead
- serialize potentially-parallel things
- use local ranges instead of remote domains to avoid on-statements
- disables lazy RAD init for Block, which reduces comm counts

### CODE REVIEW

**Comment by benharsh** [comment]
@bradcray : Interested in reviewing?

The --no-bounds-checks flag is thrown to avoid local-block errors due to bounds checking with a remote domain.

**Comment by bradcray** [comment]
Interested, but realistically I shouldn't before the new year...  Maybe an opportunity to get someone else ramped up on ISx and its optimizations?

**Comment by benharsh** [comment]
Anyone on @chapel-lang/perf-team interested?

**Comment by lydia-duncan** [comment]
If this is still open on Tuesday, I will take a look, but I'm pretty swamped today

**Comment by lydia-duncan** [comment]
:+1:

**Pull request merged**
