### PR TITLE
Adds few UnitTest Launcher created  files to .gitignore

### PR DESCRIPTION
**Pull request by krishnadey30**
This PR adds these files to .gitignore and CLEANFILES:
- [x] test/library/packages/UnitTest/test_fail_real
- [x] test/library/packages/UnitTest/test_halt_real
- [x] test/library/packages/UnitTest/test_locales_real
- [x] test/library/packages/UnitTest/test_ok_real
- [x] test/library/packages/UnitTest/test_skip_real
- [x] test/library/packages/UnitTest/test_fail
- [x] test/library/packages/UnitTest/test_halt
- [x] test/library/packages/UnitTest/test_locales
- [x] test/library/packages/UnitTest/test_ok
- [x] test/library/packages/UnitTest/test_skip

### CODE REVIEW

**Comment by krishnadey30** [comment]
I think we have to but how to we find those executables? I don't find a regular expression for the non_real executable.

**Comment by ben-albrecht** [comment]
>  I don't find a regular expression for the non_real executable.

We may have to list them out manually for now.

**Comment by krishnadey30** [comment]
I have added the non-real executable as well.

**Comment by lydia-duncan** [comment]
> why don't we have to clean the non-_real executable when COMM==none?

`start_test` removes executables with the same name as .chpl files when cleaning the directory before a run.  It also removes `_real`s in the same manner.  So even though `test_skip.chpl` has a `.notest`, it still gets cleaned up with a `start_test -cleanonly` run, even without this change.

**Comment by lydia-duncan** [comment]
Good point, I'll close it!

**Pull request closed without merging**
