### PR TITLE
Fix licm for defs to variables through function calls

### PR DESCRIPTION
**Pull request by ronawho**
LICM previously assumed that any function calls may modify global variables,
but it didn't do this for local variables that were defined outside the loop's
scope. A nested function could change a local variable, without LICM having
visibility, so update licm to assume a function call can change any variable
not declared in the loop's scope.

This resolves https://github.com/chapel-lang/chapel/issues/7042

### CODE REVIEW

**Comment by ronawho** [comment]
@benharsh another one for you

**Comment by ronawho** [comment]
Yeah, it could have some performance regressions. Want me to playground it for a night?

**Comment by benharsh** [comment]
Not sure, I could go either way. This would be an easy one to revert.

**Comment by ronawho** [comment]
Turns out this led to large comm count regressions, and didn't actually solve the real issue, it just happened to work in the test cases since they used a nested function. Closing in favor of https://github.com/chapel-lang/chapel/pull/7371 (which includes a test case that doesn't use a nested function that fails with this PR)

**Pull request closed without merging**
