### PR TITLE
Add gasnetrun_psm launcher for running on OmniPath interconnect

### PR DESCRIPTION
**Pull request by barrymoo**
Add a gasnetrun_psm launcher as well as documentation/best-practices for
running on OmniPath.

Tested with:
```bash
export CHPL_COMM='gasnet'
export CHPL_LAUNCHER='gasnetrun_psm'
export CHPL_COMM_SUBSTRATE='psm'
export CHPL_GASNET_SEGMENT='everything'
```

### CODE REVIEW

**Comment by ronawho** [comment]
@barrymoo I think I mentioned this over email, but feel free to ping me whenever this is ready for a review.

**Comment by barrymoo** [comment]
@ronawho Thanks. I want to finish some documentation for "Platform-Specific Notes", but I don't think I am doing anything compelling in this pull request if you want to review it.

**Comment by ronawho** [comment]
Sorry, I completely dropped the ball on reviewing this.

I still don't have access to an an OmniPath system to test this out myself, but the code looks good to me. 

Could you update doc/rst/usingchapel/launcher.rst to include the new launcher? For now I'm thinking we should put it in the "Additional launchers" section and we can promote it as we get access to systems to test on. 

Also, I don't think we have a contributors agreement from you. CLA instructions be found at https://github.com/chapel-lang/chapel/tree/master/doc/rst/developer/contributorAgreements/

**Comment by barrymoo** [comment]
Minus my inexperience with reStructuredText, that was painless. I will deal with the contributor agreement tomorrow (I could end up working on Chapel as part of my job and I don't know who at the University would sign the CCLA).

**Comment by ronawho** [comment]
Documentation looks good. Think you need to add `omnipath` to doc/rst/platforms/index.rst though

You should be able to build the documentation locally with a top-level `make docs`, and then open $CHPL_HOME/doc/html/platforms/omnipath.html to see the rendered output

**Comment by ronawho** [comment]
I'm awful with rst too. @ben-albrecht mind giving the rst a quick review?

**Comment by ben-albrecht** [comment]
docs look good to me!

**Comment by ronawho** [comment]
Think we're ready to merge once the CLA is signed 

>(I could end up working on Chapel as part of my job and I don't know who at the University would sign the CCLA).

👍 cool!

**Comment by ronawho** [comment]
@barrymoo just making sure that I'm not the the hold up again -- we're still waiting on a contributor agreement, right?

**Comment by barrymoo** [comment]
Correct, I have found the correct people to consult at the University. It's a slow process.

**Comment by ronawho** [comment]
Ok, np. Just wanted to make sure you weren't waiting on me.

**Comment by barrymoo** [comment]
All of the paperwork on my end is submitted. The University should send the Contributor Agreement soon.

**Comment by ronawho** [comment]
@barrymoo looks like the contributors agreement finally found its way to us!

Wanna update the PR message with a succinct merge message, and push any last minute changes before we merge?

**Comment by barrymoo** [comment]
@ronawho updated. I haven't made any additional changes to the code.

**Comment by ronawho** [comment]
We typically just copy the title and PR message as the merge message. As is I'd probably do some wordsmithing  on https://github.com/chapel-lang/chapel/pull/5843#issue-216993343 before merging. If you want to take a first stab at that great, but if not I'm happy to do it to. 

e.g. For https://github.com/chapel-lang/chapel/pull/6212, the email/commit that's generated looks like https://sourceforge.net/p/chapel/mailman/message/35833691/

**Comment by ronawho** [comment]
Merged, thanks @barrymoo!

**Comment by ronawho** [comment]
Hey @barrymoo we're looking at upgrading to GASNet-EX (https://github.com/chapel-lang/chapel/pull/11674), which at least initially will not have support for psm. Is this still an important configuration/platform for you?

**Comment by barrymoo** [comment]
@ronawho I just saw this, I can look into it. I have been playing with other languages.

**Pull request merged**
