### PR TITLE
Chpldoc io

### PR DESCRIPTION
**Pull request by mppf**
Document IO module

### CODE REVIEW

**Comment by mppf** [comment]
@lydia-duncan can you look at this now?

**Comment by lydia-duncan** [comment]
Since the changes to IO.chpl are so big the diff won't show up, I'll make comments here and refer to line numbers.

**Comment by lydia-duncan** [comment]
There's so much here, it's really exciting :)

**Comment by mppf** [comment]
I'm glad you're excited (vs terrified)

**Comment by lydia-duncan** [comment]
There's a missing ")" for the reading and writing examples at lines 56 and 77 respectively.

**Comment by mppf** [comment]
I don't see the missing ")" and the line numbers don't make sense.
Could you paste context ? Are you using the current patch?

**Comment by lydia-duncan** [comment]
// create a reading channel starting at file offset 0
// (start and end offsets can be specified when creating the
// channel

I'll check to make sure I'm using the most updated version.  I pulled from your fork about 5 minutes ago, so hopefully . . .

**Comment by mppf** [comment]
Yeah, I have that on line 49. Maybe I forgot to commit something...

**Comment by mppf** [comment]
Gaa! I did forget to commit it. So, I fixed the ) issue and now you have a newer version.

**Comment by lydia-duncan** [comment]
Okay, I'll pull it again :)

**Comment by lydia-duncan** [comment]
Okay, here's one.  Line 37, I think you are now missing a "is".  It should read "Each :record:`channel` is a buffer to provide..."

**Comment by lydia-duncan** [comment]
Should lines 95-96 read: "Because of these issues, Chapel programmers wishing
to perform I/O will now need to open files as well as create channels"?

**Comment by lydia-duncan** [comment]
Nit-picking, feel free to ignore (especially if feeling under a time crunch): there's a couple of lists early on where I'd use semi-colons as separators instead of commas.

**Comment by lydia-duncan** [comment]
I think we should have a TODO to rename the channel methods _style and _set_style to remove the underscore.  I agree that they should be documented and such.   Since we're past code freeze, though, we should wait to make the change.

**Comment by lydia-duncan** [comment]
I would merge the paragraphs on default iostyles ("The default value of ..." at line 115 and "The function :proc:`defaultIOStyle`" at line 137) into a single paragraph

**Comment by lydia-duncan** [comment]
I'd call out iostyle's WIP status (line 140) in .. note:: form, to make sure the reader doesn't skim past it easily.

**Comment by lydia-duncan** [comment]
There's a stray comma on line 156

**Comment by lydia-duncan** [comment]
Actually, I think it got swapped with the word "Lastly"

**Comment by lydia-duncan** [comment]
I think rearranging the sentence at line 176 would make it parse better: for instance "To release any resources associated with a file, first its channels and then the file itself must be closed ... "

**Comment by lydia-duncan** [comment]
On line 194, you had "locking=false" out plain, though the iostyle setter was enclosed in backticks.  For consistency, I would surround the locking statement in backticks.

**Comment by lydia-duncan** [comment]
I'd combine the last three paragraphs (starting at lines 253, 258, and 261 respectively) of the "Performing I/O with Channels" section into a single paragraph, especially since the last one ties very directly to the former two.

**Comment by lydia-duncan** [comment]
There's an extra "i" in illegal on line 323

**Comment by lydia-duncan** [comment]
The reference to errorToString is not getting linked on line 329.

**Comment by mppf** [comment]
You said "Nit-picking, feel free to ignore (especially if feeling under a time crunch): there's a couple of lists early on where I'd use semi-colons as separators instead of commas." - I fixed the one in the 1st full paragraph. Let me know the locations of others.

**Comment by lydia-duncan** [comment]
The first paragraph of "IO Styles" would be another.  Mostly because I think "string representation" is logically distinct from "the base, field width and precision for numeric types"

**Comment by mppf** [comment]
OK, I've updated with your comments so far. You can pull or keep using the old version - up to you. I can figure out line numbers either way.

**Comment by lydia-duncan** [comment]
Thanks!  I think I'll keep using the old version for now.

**Comment by lydia-duncan** [comment]
In the "Formatted I/O" section at (old) line 390, I would link to the sections you are referring to.  At this point in the browser, the reader has scrolled far enough down that they can't see the other subheaders in their sidebar.

**Comment by lydia-duncan** [comment]
Similarly, it would be nice for the "Format String Syntax in Detail" section call-out to be a link

**Comment by lydia-duncan** [comment]
I like the description paragraph on line 432 for imaginary numbers and complexes, but I think it would be strengthened by an example output.

**Comment by lydia-duncan** [comment]
Under "String and Byte Conversions" at line 540, there is a missing "r" in "to read *your* string back in"

**Comment by lydia-duncan** [comment]
On line 619 in the "Note About Whitespace", the slash portion of "\n" is lost in the html version

**Comment by lydia-duncan** [comment]
It is also lost on line 642

**Comment by lydia-duncan** [comment]
I would link to the "# Specifiers" section from the brief description in "Generic Numeric Conversions"

**Comment by lydia-duncan** [comment]
The list at line 814 (optional endian flag) did not get turned into a list or code block.

**Comment by lydia-duncan** [comment]
In the example code at line 886,

.. code::
  writef("%<4i %<4i", 2, 32);
  // outputs:
  // (hexdump of the output -- note that spaces after
  a binary format specifier are ignored)

There should probably be another set of "//" on the last line, so that if the user wants to copy-paste the example code and run it, they can.

**Comment by lydia-duncan** [comment]
Oh ew. There's an enum chpldoc output bug when it is used as the default value (see iodynamic, for instance, at line 1076.)  I'll make a note of that.  For now, it might be best to reference these compile time constants in the documentation for the enum type and "no doc" them here.  I'll be sure to get back to them when I fix it.

**Comment by mppf** [comment]
I'm OK with the "ew" for now too... but I'll move them to the enum type docs.

**Comment by mppf** [comment]
I also noticed that the :enum:`enumname.value` doesn't work with a link the way I'd expect

**Comment by lydia-duncan** [comment]
Yeah . . . We're going to need to expand our enum chpldoc story, it was sort of last minute.

**Comment by mppf** [comment]
I'm thinking about moving the formatted I/O examples to be next to the first time that feature is described. Also using the "definition mode" for all of the formatted IO details instead of preformatted blocks. Do you like those ideas?

**Comment by lydia-duncan** [comment]
Yeah, that sounds good to me!

**Comment by lydia-duncan** [comment]
The description for stringStyleWithLength is a little confusing, specifically the second part of the first sentence.

**Comment by lydia-duncan** [comment]
:cry: at IOHINT_NONE

**Comment by mppf** [comment]
yeah... it's kindof overwhelming. hang in there! Or call for backup!

**Comment by lydia-duncan** [comment]
I'm just going to pretend I didn't see the ugliness that is iostyle.byteorder's default value.

**Comment by lydia-duncan** [comment]
Next release is going to have sooooooo many chpldoc bug fixes . . .

**Comment by lydia-duncan** [comment]
All the "\"s in the description of iostyle.string_format are missing (line 1349)

**Comment by lydia-duncan** [comment]
I believe you can turn the reference of iostyle.string_end into an actual link, but I could be wrong.

**Comment by lydia-duncan** [comment]
At line 1731, in the description for defaultIOStyle, it might be nice to remind the user what that entails.

**Comment by lydia-duncan** [comment]
50 comments now.  I wonder at what point github freaks out?

**Comment by fsouza** [comment]
800, maybe: https://github.com/pulls?q=is%3Aopen+is%3Apr+sort%3Acomments-desc

**Comment by lydia-duncan** [comment]
I'm so sorry for the amount of email spam you've gotten, Francisco . . .

**Comment by lydia-duncan** [comment]
At the documentation for file.getPath, file.tryGetPath, and file.path, it might be good to note that we anticipate these methods being replaced by functionality that lives and will live in the Path module in the near future.

**Comment by mppf** [comment]
I'm not sure I think that file.getPath needs to go away... so I'd rather not add a deprecationy warning until at least we agree about that!

**Comment by lydia-duncan** [comment]
Alright, probably still want to mention the existence of realPath, though :)

**Comment by mppf** [comment]
OK, I'll put a link to it

**Comment by fsouza** [comment]
@lydia-duncan no problem, I don't receive emails from GitHub.

I read everything in the notifications page, so it's easy to sit down and catch everything up. And I do like to keep posted about Chapel evolution. Thanks for the hard work :)

**Comment by lydia-duncan** [comment]
At line 2316 on openfp, there's a rearrangement of the words "to use a" in "once the file is open, you will need to use a file.reader"

**Comment by lydia-duncan** [comment]
openmem is experiencing a similar problem

**Comment by lydia-duncan** [comment]
In the description for openmem's style argument, I would split the different "which" clauses into separate statements for clarity.

**Comment by lydia-duncan** [comment]
The description of channel.locking at line 2487 has an extra "t" at the end of the word "safe".

**Comment by lydia-duncan** [comment]
Also, thanks Francisco :)

**Comment by lydia-duncan** [comment]
Might want to warn that the Unicode record ioChar (at line 2551) may change or be replaced with the upcoming string proposal work Kyle is doing.

**Comment by lydia-duncan** [comment]
The description of ioNewline also falls prey to the loss of "\"s. (line 2570 on)

**Comment by lydia-duncan** [comment]
The second paragraph of ioNewline's description has replaced "to" with "te" as its second to last word.

**Comment by lydia-duncan** [comment]
In the description for channel.offset at line 2738, I would also mention the need to use channel._offset when locked.

**Comment by mppf** [comment]
It won't be since it's used internally by the IO implementation
when you e.g. writef("%c", 0x20).

-michael

**Comment by mppf** [comment]
that last comment was about ioChar

**Comment by lydia-duncan** [comment]
Ah.  Does that mean it would move to only being used internally?  If so, 
we'd probably want to remove it from the documentation at that point.

Lydia

**Comment by mppf** [comment]
Maybe... but I don't think we have to worry about it at the moment...

**Comment by lydia-duncan** [comment]
In the documentation for file.writer (line 3126), I think it would be useful to specify whether the end position if after overwriting versus insertion, just to make sure we're explicitly clear.

**Comment by lydia-duncan** [comment]
The documentation for both channel.readline()s lose their "\"s.

**Comment by lydia-duncan** [comment]
Might want to italicize "nbits" at channel.writebits()'s description of argument v (line 3846)

**Comment by lydia-duncan** [comment]
In the description of channel.read for a type, at line 3945, it mentions channel.read.  However, without additional argument specifiers, this might confuse readers on its own.  Would you add an additional description, such as "the version of channel.read which requires more arguments" or something to that effect?  The channel.readln which follows it also does something similar.

**Comment by lydia-duncan** [comment]
Do you want to skip the second definition of channel.assertEOF (at line 4204) similar to what has been done with the other non-error versions of these functions/methods?

**Comment by lydia-duncan** [comment]
Have updated my reference (but may have missed your latest update).  It looks as if the _toSigned() function at 4728 function got missed in the great "no doc" purge.

**Comment by lydia-duncan** [comment]
At line 6364 on channel.search, the return description has either an extra "a" or an extra "the".

**Comment by lydia-duncan** [comment]
A similar thing occurs in the description of channel.match at line 6487

**Comment by lydia-duncan** [comment]
The description of channel.matches at line 6562 is missing an "x" in the word "maximum".

**Comment by lydia-duncan** [comment]
Okay, I reached a full pass through the module file and I went back and looked through the new formatted I/O output, it looks great!

**Comment by lydia-duncan** [comment]
Went through all the comments I've made that you've responded to, no complaints there. :)

**Pull request merged**
