### PR TITLE
Support for C unions in c2chapel

### LINKED ISSUE #17278: Support for C unions by c2chapel
Currently, the `c2chapel` tool does not recognize a C union while converting definitions in C headers to Chapel extern definitions.
On experimentation, it was found that C unions can indeed be treated in a similar way as C structs are treated while working with C interoperability.

Hence, this code, where the C union is treated as a struct (example given by @bradcray) runs as expected:

**File**: *testit.h*
```c
typedef union _u {
  int x;
  unsigned y;
} u;

extern void setX(int x);
extern int getX(void);
extern unsigned getY(void);
```

**File**: *testit.c*
```c
#include "testit.h"

u myU;

void setX(int x) {
  myU.x = x;
}

int getX() {
  return myU.x;
}

unsigned getY() {
  return myU.y;
}
```

**File**: *testit.chpl*
```c
use SysCTypes; // get definitions of c_int, c_uint                              

require "testit.h", "testit.c"; // C code defining union                        

// reflect C code here                                                          
extern record u {
  var x: c_int;
  var y: c_uint;
}
extern proc setX(x: c_int);
extern proc getX(): c_int;
extern proc getY(): c_uint;

// create and modify union from Chapel:                                         
var myChplU: u;

myChplU.x = -3: c_int;
writeln(myChplU.x);
writeln(myChplU.y);

// create and modfiy C union through routines:                                   
setX(-3);
writeln(getX());
writeln(getY());
```

As the union shows the expected behavior of a C union (confirmed by experimentation), it should be good to be added as a recognized node in the `c2chapel` tool.

### PR DESCRIPTION
**Pull request by souris-dev**
The c2chapel tool should now support C unions as well (it processes them the same way it processes C structs, as mentioned in issue #17278 ).

Fixes #17278.

### CODE REVIEW

**Comment by bradcray** [comment]
Hi @souris-dev — Thanks very much for putting this together.  Because we're past the feature freeze for the upcoming release, I think we'll sit on this PR until after the release is done.  I'm also hoping that someone who's edited c2chapel.py in the past could lead the review here (though the mods look straightforward enough that I could probably do it in a pinch).  @daviditen? @npadmana? @mppf?

**Comment by souris-dev** [comment]
Also added some changes so that `c2chapel` doesn't stop on anonymous unions/structs and instead skips them with a comment.

**Comment by bradcray** [comment]
> and instead skips them with a comment.

There's no need to worry about this in this PR, but for my curiosity:  Would it be difficult to have c2chapel simply squash out the anonymous union as we were doing on gitter so that the fields would be accessible?  Or is that what you mean by "skips them"?  (I interpret it as "skip all of the anonymous union/struct fields as well").

**Comment by souris-dev** [comment]
@bradcray Sure, I'll open an issue either way for now, and try to implement it if I'm able to.

**Review by leekillough — APPROVED** [review]
LGTM

**Comment by mppf** [comment]
It looks good to me as well. As I understand it, @leekillough will help with the next steps of testing and merging.

**Comment by leekillough** [comment]
Two fixes:

https://github.com/leekillough/chapel/commit/30925e027f0649538749d56bd4eb7a4d851abd86

**Comment by leekillough** [comment]
See https://github.com/chapel-lang/chapel/pull/17499

**Pull request closed without merging**
