### PR TITLE
Remove deprecated sync/single PRIMS

### PR DESCRIPTION
**Pull request by noakesmichael**
At the start of this release the lowest level methods for sync/single relied on compiler PRIMs.

The recent work to define sync/single as record-wrapped classes also replaced the
low level methods to rely on extern functions (in the runtime).  This PR drops the deprecated
PRIMs.

Compiled: clang/darwin and gcc/linux64 with and without CHPL_DEVELOPER

Tested: linux64 and gasnet

### CODE REVIEW

**Comment by ronawho** [comment]
https://github.com/noakesmichael/chapel/blob/4dcc08a83ad6f946eaed3091a653157bd8469df3/compiler/util/exprAnalysis.cpp#L170-L171 should be removed too (they're just comments though)

**Comment by ronawho** [comment]
👍 This is such a satisfying commit

**Comment by ronawho** [comment]
Oops, what about FLAG_AUTO_DESTROY_FN_SYNC, can that be removed too?

**Comment by noakesmichael** [comment]
On Sep 1, 2016, at 4:35 PM, Elliot Ronaghan <notifications@github.com<mailto:notifications@github.com>> wrote:


Oops, what about FLAG_AUTO_DESTROY_FN_SYNC, can that be removed too?



Trivially both FLAG_SYNC and FLAG_AUTO_DESTROY_FN_SYNC are in use as
pragmas in ChapelSyncvar.

I am pretty sure FLAG_SYNC is currently necessary.
I am less confident about p FLAG_AUTO_DESTROY_FN_SYNC.

I’ll do that as a separate effort.

Mike

**Pull request merged**
