### PR TITLE
Add Chapel 1.14.0 to Dockerfiles

### PR DESCRIPTION
**Pull request by awallace-cray**

### CODE REVIEW

**Comment by awallace-cray** [comment]
Ben, would you review?  (The Docker image is already up - this change just provisions the link within the README on Docker hub)
Thanks.

**Comment by awallace-cray** [comment]
https://hub.docker.com/r/chapel/chapel/tags/

**Comment by ben-albrecht** [comment]
Looks good to me. @nspark may be interested as well.

**Comment by nspark** [comment]
Thanks for the heads-up @ben-albrecht and for maintaining the Docker images, @awallace-cray.

**Pull request merged**
