### PR TITLE
update Crypto to throw errors

### PR DESCRIPTION
**Pull request by psahabu**
To put more weight on the error handling system, this PR moves the Crypto module from halts to throwing errors.

- [x] passes linux64+flat testing, with futures

### CODE REVIEW

**Comment by bradcray** [comment]
Same comment as on #8244:  If no tests were changed or added as part of this PR, are we really putting any more weight on error-handling?  What would it take to add such tests or update existing ones to put that weight on them?

**Comment by saru95** [comment]
As a first step, we should try to replace all the `halts` with error handling. Maybe then we can replace the tests that test for `halt` with these ones.

**Comment by bradcray** [comment]
I didn't realize that hadn't already been done.  I agree that that would be a good evolution of this code.

**Comment by psahabu** [comment]
#8329 has been created to address `halt`s in the Crypto module.

Lots of the standard modules have halts as well. I'm going to explore removing them after I finish deprecating the 'out error' pattern.

**Pull request merged**
