### PR TITLE
Move CPtr from modules/internal to modules/standard

### LINKED ISSUE #16389: Should CPtr's contents be defined in an internal module or a standard one?
Currently `CPtr.chpl` is an internal module.  In this issue, I'm proposing that it should be a standard one, using the following argument:

* I think that "internal" modules should be ones that are used to implement things that are "built into" the language and would be described in a complete version of the language spec.  So things like strings, syncs, ranges would all be defined in internal modules.

* Meanwhile, I think of "standard" modules as being those that aren't built into the language, yet are so fundamental or useful that any implementation of Chapel should be able to rely on them being available (and, ultimately, stable).  I think of standard modules as being ones where you'd surf to the standard module documentation on the docs website and review the symbols that that module makes available.

To me, types like `c_ptr()` and `c_void_ptr` are not things that we consider to be an intrinsic features of the Chapel language, but features that are made available in a standard manner to support interoperability and lower-level programming, so it seems obvious that the module should be standard (if others think that `c_ptr` should be part of the language, let me know and I'll spawn off a separate issue about that; the rest of this issue will assume it's not part of the language).

[Also independent of, but related to, this issue, I think CPtr should ultimately be merged into a general `CTypes` module that also supports things like `c_int` (currently defined in `SysCTypes`) and `c_double` (currently defined in `SysBasics`). This is related to issue #16131 ].

A counterargument to this proposal might be:

* internal modules shouldn't rely on standard modules, but some of our built-in types (like `string` and `bytes`) use `c_ptr`, so `CPtr` should remain an internal module

I agree that, whenever possible, internal modules shouldn't rely on standard modules, but I don't think it's always possible / desirable, and I'm not convinced that it warrants putting `CPtr` into the internal modules.  Specifically, if `c_ptr()` is not in the language, I think it would be unfortunate to have the user apply some sort of mental heuristic like "do I think that the Chapel implementers used this module to implement the language?" to determine whether to browse the internal module documentation or the standard module docs to read the `c_ptr` type's documentation.  Meanwhile, I also think it would be counterproductive to support a second non-user-facing `c_ptr` type in order to implement strings without `CPtr`.

We could say "some internal modules will have their documentation placed into the standard module hierarchy in the docs even though they are internal modules", but to me, this essentially says that they're standard modules from the user's perspective, so why not just make them standard modules?

### PR DESCRIPTION
**Pull request by bradcray**
This moves the `CPtr` module from the internal modules directory to the standard modules directory.  Updates include getting the docs to build correctly, a few minor test changes due to the file's new placement and change from an internal module to a standard one, and error message changes due to stack unwinding working differently for standard vs. internal modules.

Resolves #16389

### CODE REVIEW

**Comment by bradcray** [comment]
@e-kayrakli: If you're working tomorrow and have time to give this a quick review, let me know.

**Review by dlongnecke-cray — APPROVED** [review]
These changes look good to me from my experience adding a standard module or two.

- I'm not very knowledgeable about `fixInternalDocs.sh` but the changes there look small enough and to be expected
- For the `printModStuff/foo` test, seeing `CPtr` at the top is to be expected with how we inject it now. I'm not sure about the `CommDiagnostics` or the `SysError` but I'm also not surprised with their ordering either
- For test `recordOffset-badField.chpl` I'd be inclined to anonymize the line numbers with a prediff

**Comment by bradcray** [comment]
> I'm not sure about the CommDiagnostics or the SysError but I'm also not surprised with their ordering either

I believe that these are due to `CPtr` making use of them (through `use ChapelStandard`), and that since it is no longer an internal module, they are parsed in a different order / differently than before.  I'll admit I didn't dig much deeper than that, though.

> For test recordOffset-badField.chpl I'd be inclined to anonymize the line numbers with a prediff

That's a good thought.  Care to check my latest commit?

**Comment by dlongnecke-cray** [comment]
Looks good to me, thanks!

**Pull request merged**
