### PR TITLE
passStrRngToNonstrRng.chpl: Declare this future to be passing.

### PR DESCRIPTION
**Pull request by cassella**
I believe the current error message satisfies the future's requests.

### CODE REVIEW

**Comment by cassella** [comment]
@bradcray Here's another one for you.

**Comment by bradcray** [comment]
@vasslitvinov : You've likely already come across this in your generic range explorations, but since I looked at it due to this PR, wanted to note that this is a case whose behavior would not have surprised the original developer if `range` were interpreted as generic.

**Comment by vasslitvinov** [comment]
@bradcray are you talking about the scenario where the original developer lives in the world where `range` is generic?

How does this affect our take on range genericity? I suspect you meant "yes, genericity is good".

**Comment by bradcray** [comment]
I was mostly trying to point it as related, having been pointed at it by Paul, rather than make a judgement of any kind.  But yeah, I do think this is a case where the original developer would've been happy to have had this "just work", similar to the classic `var r: range = 1..10 by 2;` case.  And yeah, it makes me think "genericity is good" but it's also not so different than other cases we've discussed that that's particularly insightful.  This was one of our earliest external users.

**Pull request merged**
