### PR TITLE
Proposed/potential edits to threadring for shootout entry

### PR DESCRIPTION
**Pull request by bradcray**
Things I feel strongly about:
-----------------------------
* Consider Lydia a contributor rather than a modifier

* Removed the 'Threads' range which would probably feel like overkill
  to a reader and shouldn't affect performance anymore (?).

* Changed initial value written into thread 1's mailbox from 0 to 1
  to avoid some weird magic numbers at end of benchmark.

Things I feel reasonably strongly about:
----------------------------------------
* Removed curly brackets on coforall (see style email question)

* Changed infinite loop + returns into finite loop -- OK?  Or did we
  find this hurt performance?  Can we avoid two returns?  Should we
  put in an exit()?  (I'd like to avoid unless it's much faster)

* Changed names of things to try and improve clarity

Things that are neither here nor there:
---------------------------------------
* word-smithed comments

Things I feel unsure about:
---------------------------
* Added introductory comment about tasks vs. threads (because I kept
  finding myself wanting to change everything to refer to 'tasks' to
  be more consistent with Chapel)

* Removed boilerplate about setting configs (see style question in
  email)

* Should we remove the passTokens() routine and fold its body into the
  coforall?

* Made long comment at start of routine to per-line comments

### CODE REVIEW

**Comment by bradcray** [comment]
Shootout team and audience ( @benharsh , @lydia-duncan , @ben-albrecht, @psahabu , @ronawho ).  I can't review code without editing it, so put together this PR to capture proposed/possible changes to threadring.  There's no need to review before next week's meeting (my plan would be to walk through these deltas in the meeting), but I'm putting this out there in case people want to before then.

**Comment by lydia-duncan** [comment]
Did you end up sending the email you reference a couple of times?

**Comment by lydia-duncan** [comment]
> * Consider Lydia a contributor rather than a modifier

With these changes, you should probably be a contributor, too :)

> * Removed the 'Threads' range which would probably feel like overkill
>   to a reader and shouldn't affect performance anymore (?).

It'd be good to verify that for a night or two.

> * Changed initial value written into thread 1's mailbox from 0 to 1
>   to avoid some weird magic numbers at end of benchmark.

Seems fine

> * Removed curly brackets on coforall (see style email question)

No opinion :)

> * Changed infinite loop + returns into finite loop -- OK?  Or did we
>   find this hurt performance?  Can we avoid two returns?  Should we
>   put in an exit()?  (I'd like to avoid unless it's much faster)
> 

This doesn't hurt performance.  I made some tests to verify way back when (http://chapel.sourceforge.net/perf/chapcs/?graphs=threadringshootoutbenchmarkn50000000,forbegintimings,coforalltimings,coforallbegintimings,earlyexittaskparalleltimings,taskparalleltimings), and they seem fine so
I think it's fair to avoid the multiple returns/

> * Changed names of things to try and improve clarity

I might leave "mailbox" as "token" to match other implementations.  Otherwise
seems fine.

> * word-smithed comments

:+1: 

> * Added introductory comment about tasks vs. threads (because I kept
>   finding myself wanting to change everything to refer to 'tasks' to
>   be more consistent with Chapel)

Maybe keep this in our release/examples directory version?  It feels more
like a tutorial comment than something that should be in wild Chapel code.

> * Removed boilerplate about setting configs (see style question in
>   email)

It does seem like something that belongs in a tutorial rather than a
random benchmark.

> * Should we remove the passTokens() routine and fold its body into the
>   coforall?

I'm not sure about this one.  On the one hand, it makes the program look
shorter.  On the other hand, it might be confusing for someone encountering
Chapel for the first time - I'm not as certain about that.

> * Made long comment at start of routine to per-line comments

I'd argue against doing this, actually.  I think it hides how incredibly simple the routine
ends up being, which is a strong selling point for us.  The function body is only ~8
lines long if you put the comment at the beginning and it looks so nice in comparison
to the C versions

**Comment by bradcray** [comment]
I'm going to try and take another pass to prune my comments down before Thursday's meeting.  Lydia, can you point to a clean/notable reference version that calls an array of mailboxes 'token'?  It seems to me that, conceptually, the token is the thing being passed around, not the places where it's being passed to, but if most other clean versions have a similar array that they call token, I'm open to trying to conform even though I think it's a misleading name for that variable.

**Comment by lydia-duncan** [comment]
Oh that's true.  Most of the reference versions just decrement the token as they pass it around and there is one reference version that stores the value in a "mailbox" (http://benchmarksgame.alioth.debian.org/u64q/program.php?test=threadring&lang=gcc&id=2).  Never mind then!

**Comment by bradcray** [comment]
@ben-albrecht , @bharsh, @lydia-duncan , @ronawho , @psahabu : I think this incorporates all of the changes that we discussed in today's meeting.  I'd be very comfortable submitting this once we get a few nights of testing on it I think, but would appreciate if someone else wants to double-check me.  A few other things that occur to me:

1) Would anyone else like to be added to the "contributed by" list?  I think we should avoid putting everyone's name on every test, but I also think we can be generous as to what constitutes a "contribution"

2) I was thinking about Lydia's mention in the comments above about how other versions start the token at the max value ('n') and decrement it each time, and found myself whether the comparisons to '0' rather than 'n' would be beneficial in terms of not having to store an arbitrary numeric value in a register.  It seems hard to believe it would affect performance, though.  Does one approach seem cleaner than the other?  (e.g., effectively change numPasses to numPassesLeft)

3) Lydia, can you double-check me:  Changing the config from nthreads to ntasks required changes to our .execopts and such which I hadn't anticipated.  There's nothing in the shootout Makefiles and such that will try to modify this variable, though, is there?  (i.e., do we need to update anything, or would this suggest changing the name of the config back?)

**Comment by bharsh** [comment]
Brad, make sure to get the right "bharsh" ... I think our github ids are
similar.

**Comment by bradcray** [comment]
Oops, sorry Brent.  Clearly I wasn't relying on GitHub's autocomplete as much as I should've -- it typically corrects for me when I make this mistake.

**Comment by bradcray** [comment]
( @benharsh this was meant for you obviously)

**Comment by bharsh** [comment]
On Thu, May 12, 2016 at 8:39 PM, Brad Chamberlain <notifications@github.com>
wrote:

> Oops, sorry Brent. Clearly I wasn't relying on GitHub's autocomplete as
> much as I should've -- it typically corrects for me when I make this
> mistake.
>

No worries, it's happened here before but I couldn't remember what Ben's
actual user was to forward on :).  It was a funny coincidence too since my
very first tech job was a summer internship at Cray in 1987 ( they had me
doing 3rd shift system test on the XMP systems prior to delivery).  I was
glad to see there was still a Cray in existence and it sounds like y'all
are doing some neat stuff!  Carry on with your regularly scheduled
programming :)


> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/chapel-lang/chapel/pull/3842#issuecomment-218924196>
>



-- 
Brent Harsh
Velleros, Inc
+19194344349
skype: dbharsh

**Comment by lydia-duncan** [comment]
@bradcray - the shootout script doesn't rely on the nthreads/ntasks config, so changing it is fine.  I'm glad you caught the updates to the .execopts and .good files.

In answer to the "increment or decrement" question, I don't think it will matter either way and so wouldn't change it.

**Comment by benharsh** [comment]
I'd be surprised if counting down mattered.

The rest looks good to me 👍

**Pull request merged**
