### PR TITLE
Extend split init to support local blocks

### LINKED ISSUE #13271: [Feature Request] Allow variable declarations inside of local blocks ('{...}') to escape scope
As someone who is using `local` blocks more and more, I feel that it would be nice to be able to write code inside of a `local` block of code that persists outside of the bracket. I'm assuming that `local` applies to the next statement only and that since brackets encapsulate one really large statement, it just applies to that block, but the normal brackets also defines its own scope. I would appreciate it if the following program could run...

```chpl
var atomicVar1 : atomic int;
var atomicVar2 : atomic int;
local {
   var x = atomicVar1.read();
   var y = atomicVar2.read();
}
writeln(x, y);
```
[TIO](https://tio.run/##S85ILEjN@f@/LLFIIbEkPzczOSyxyFDBCspRyMwrseZCkTRCk8zJT07MUajmUlBQAKmrULBFMkivKDUxRUPTGiZbiSxrBJet5SovyixJzcnTqNBRqNS0/v8fAA)

```
.code.tio.chpl:7: error: 'x' undeclared (first use this function)
.code.tio.chpl:7: error: 'y' undeclared (first use this function)
```

Note however that this does work...

```chpl
var atomicVar1 : atomic int;
var atomicVar2 : atomic int;
local do var x = atomicVar1.read();
local do var y = atomicVar2.read();
writeln(x, y);
```
[TIO](https://tio.run/##S85ILEjN@f@/LLFIIbEkPzczOSyxyFDBCspRyMwrseZCkTRCk8zJT07MUUjJVwCpqlCwRTJGryg1MUVDE01NJbIaI7ia8qLMktScPI0KHYVKTev//wE)

```
00
```

### PR DESCRIPTION
**Pull request by bradcray**
This extends split initialization to look within local blocks as it does
for normal compound/block statements.  It also adds a test locking in
the feature request from issue #13271 now that it works for `--no-local`
compilations.

Resolves #13271.

### CODE REVIEW

**Comment by bradcray** [comment]
@mppf: This PR just passed full linux64 GASNet testing.  Would you give it a review as the author of split-initialization?

**Review by mppf — APPROVED** [review]
Looks good to me. I think it'd make sense to also check copy elision for local blocks which has some similar code.

I've created this test to help get you started. This test has different behavior with `--no-local`.

``` chapel
record R {
  var x:int;
  proc init() {
    writeln("in R.init");
    this.x = 1;
  }
  proc init=(other: R) {
    writeln("in R.init=");
    this.x = other.x;
  }
}

proc test1() {
  writeln("test1");
  var x = new R();
  {
    var y = x; // should copy elide
    writeln(y);
  }
}
test1();

proc test2() {
  writeln("test2");
  var x = new R();
  local {
    var y = x; // should copy elide
    writeln(y);
  }
}
test2();
```

**Comment by bradcray** [comment]
@mppf: Are you proposing forking off a separate issue/PR about the copy elision case?  Or trying to fold it into this effort?

**Comment by mppf** [comment]
@bradcray - whichever works for you, but if you had me pick, fold it in. I'd expect the copy elision change is of similar complexity and in code that looks similar.

**Comment by bradcray** [comment]
I'm less worried about the magnitude of the change and more concerned about the potential for testing/performance fallout without having the time to look into it.  Whereas, split initialization seems like one of those things that either works or it doesn't, so the testing impact was much easier to scope out.  (I'm also not sure where in the compiler I need to be looking for the copy elision, so would need some time for that).  So I'll probably merge this separately in the spirit of "keeping PRs small when possible" and fire off another issue to capture the other case.  (Mostly I'm going to blame Paul for sucking me into this seemingly unimportant firedrill this week :) ).

**Comment by bradcray** [comment]
I filed issue #17272 to capture the copy elision TODO.

**Pull request merged**
