### PR TITLE
Fix baseline errors

### PR DESCRIPTION
**Pull request by benharsh**
Add an eltType argument back to _ddata_shift to resolve --baseline errors, caused by #3328

### CODE REVIEW

**Comment by bradcray** [comment]
This looks fine to me with testing.  I didn't look at the failure modes -- is another option to change something about what the compiler is generating to conform to the new, cleaner, interface?

**Comment by bradcray** [comment]
Oops, didn't notice that this was already merged -- still curious about the question, but it was pretty rhetorical to begin with...

**Comment by benharsh** [comment]
The compiler was generating code that attempted to access "eltType" as if it was a field in the _ddata class. This fails because _ddata eventually is just a pointer. I haven't looked into why that happens yet, but I'm guessing something in resolve.

**Comment by bradcray** [comment]
OK, no need to look into it further for my sake -- I was just curious.

**Pull request merged**
