### PR TITLE
Deprecate enableParScan

### PR DESCRIPTION
**Pull request by bradcray**
This turns on parallel scans by default by deprecating `enableParScan`.  It updates existing tests to remove uses of the flag and warnings generated by not using the flag.  It removes `--no-warnings` flags from tests that were using it to suppress serialized scan warnings.  It also re-simplifies some tests that I'd made to run twice when the variable was introduced, once with and once without it being set.

While here, I hand-optimized the implementation when only a single task will be used to avoid creating the task and just running the computation locally in the current task.  This is something we ultimately expect the compiler to optimize, but for now...  Failing to do this hurt performance for ISx which had previously been running the scans serialized because ISx uses SPMD parallelism and didn't have any spare cores left over to run single-task scans.

I also removed the test_scan_is_parallel.chpl test because scans are now parallel and performance testing will demonstrate if it stops working and because the test, as written, did not demonstrate that the parallelism was firing.

I also added a test to the deprecated/ directory so that we remember to remove the deprecation warning in the future.

### CODE REVIEW

**Comment by ronawho** [comment]
Hmm, a quick 16-node-xc perf test for isx looks like it might not be serialized (I think we're doing a `coforall 1..1`, creating a new task)

| config  | time |
| ------- | ---- |
| master  | 7.2s |
| this PR | 7.8s |
| serial  | 7.0s |

(where serial is adding `serial do` to before the `bucketSort` call)

**Comment by bradcray** [comment]
(musing to self...)  "I wonder how this new version compares?"

**Comment by ronawho** [comment]
Performance looks good now. Maybe better than master, but it's a little noisy right now. I'm seeing 7.2 for master, ~7.1 for this PR

**Comment by bradcray** [comment]
@ronawho: I think this is ready to go if you want to take one more look at the latest changes.

**Pull request merged**
