### PR TITLE
Adds an unmatched backquote in classes primer

### LINKED ISSUE #15108: Incorrect .rst rendering in docs
In [this doc](https://chapel-lang.org/docs/master/primers/classes.html):

- - -
image
I think this intend an unordered list like this:
* use the borrow after whatever it is borrowed from goes out of scope
* use the borrow after the instance is deleted (for example if own is assigned to)
- - -

image
Should be:
Note that when applied to an `owned` or `shared` variable, `!` will result in a borrow from that variable.
- - -

I open this issue to ensure these are mistakes and may post more if I can find anything else. 
A PR will soon follow.

### PR DESCRIPTION
**Pull request by Rapiz1**
Adds an unmatched backquote in classes primer

resolves #15108

### CODE REVIEW

**Comment by Rapiz1** [comment]
@ben-albrecht

**Comment by Rapiz1** [comment]
I just edited it. What do you think of the current description? @ben-albrecht

**Comment by ben-albrecht** [comment]
Better, but it would be best if it could be understood without seeing the other issue, e.g.

```
Adds an unmatched backtick to the classes primer.

resolves #15108 
```

**Comment by Rapiz1** [comment]
Thank you for your patience : )

**Pull request merged**
