### PR TITLE
Formatting and file rearrangement for Chapel Documentation

### PR DESCRIPTION
**Pull request by ben-albrecht**
Modified and created several index.rst pages and subpages for the Chapel documentation.

Product of changes can be seen [here](http://web/~balbrecht/html/index.html) - if you're on the VPN.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
@bradcray - Is this what you had in mind?

**Comment by bradcray** [comment]
Yeah, this is definitely going in the right direction.  Some notes (which don't have to be addressed before committing as I expect we'll continue to futz with things, but should be before shipping):

* "Platform-Specific Build" -> "Platform-Specific Notes"  (?)
* "Built-ins" -> "Built-in Functions"  (?)  -- or is it more than just functions?
* I think we'll want to manually curate the order of the items in the sidebar under "Using Chapel" to match the order that they were listed in the original README (which was set up to match a typical flow from building the compiler, to using the compiler, to executing programs, to reporting bugs, say)

Thanks for the link to the product of the changes, BTW -- that was really helpful.

**Comment by ben-albrecht** [comment]
@bradcray Changes made. 

Product of changes can be seen [here](http://web/~balbrecht/html/index.html) - if you're on the VPN. (currently rsyncing)

**Comment by bradcray** [comment]
Oops, I put this comment on the wrong PR...  Too many tabs:

I like the high-level structure and ordering -- thanks. Can't promise there won't be more changes as we have more eyes onto it and dig into it further, but I think this is a great step forward and should go in.

**Pull request merged**
