### PR TITLE
test case for compiler error with an array-of-arrays as proc argument

### PR DESCRIPTION
**Pull request by PriMachVisSys**
Collection of test cases for bug reports and feature requests.

### CODE REVIEW

**Comment by mppf** [comment]
@PriMachVisSys, thanks for putting this together. Could you make .future files for the bug reports that don't work now, with 'bug report: ' starting the first line in the future file? We generally expect that new tests don't cause failures - since the test system would view those as regressions... Other than that at a quick look it looks good to me.

**Comment by PriMachVisSys** [comment]
Done.

Michael Ferguson wrote:

**Comment by mppf** [comment]
(maybe you havn't gotten to it yet but you'll have to commit and 'git push')

**Comment by PriMachVisSys** [comment]
It's listed in the commit list ('add .future file ...').

**Comment by mppf** [comment]
got it, thanks.

**Comment by mppf** [comment]
- [ ] passes testing
- [ ] in-depth code review

**Comment by PriMachVisSys** [comment]
You do the merge, right?  Is there anything else I need to provide?  The GitCheatsheet file talks about an official format for the commit message - is this supposed to come from me?

**Comment by mppf** [comment]
Nope, you're good. I'm going to look over the tests in a bit more detail before I do the merge and might have feedback then... but so far so good anyway.

**Comment by PriMachVisSys** [comment]
Great.  I'll be away then for a couple hours, will check back around dinner time (here) it there's anything else to be done.

**Pull request merged**
