### PR TITLE
Major refactoring of bradc version of chameneos

### PR DESCRIPTION
**Pull request by bradcray**
This is intended as a candidate for the release and incorporates
feedback from today's performance meeting as well as my own ideas
(mostly with respect to refactoring).  Specifically, it:

* dramatically reformats the comments and tries to normalize their
  approach.  Attempts to move away from line-by-line comments, moving
  that to procedure headers or clumps of code when things are more
  complex.

* uses the awesome new 'use enums' feature (how did I miss this when I
  looked for such cases before?  What else did I miss?)

* refactors a bunch of code:
  - introduces a 'population' record that stores all the chameneos
    and has methods that act on the group; primarily for clarity,
    though this also cleans up some memory management.
  - moved much of the top-level code in simulate() into this
    population type including the creation/destruction of the meeting
    place itself
  - moves logic relative to creating parallelism and holding meetings
    into the population
  - moves logic relating to compressing and decompressing values
    into the meeting place

* reorders code into more of a topological sort (tries to define
  things soon after their unique|last mention).

* uses a string iterator rather than a range iterator + random access

* removes the duplicate counting of meetings with self because the
  rules don't necessitate this double-counting and it seems stupid/
  unintuitive (plus should never happen, and we'll still detect that).

* leans on type inference a bit harder

* removes halts on configs and moves these into comments because
  it's not required and counts against our code size (and we don't
  think others do it)

* moves globals closer to their uses

* removes unused numColors

* tightens up the logic in the computation of the new color

* probably other stuff as well...

### CODE REVIEW

**Comment by bradcray** [comment]
Hi perf team ( @benharsh, @lydia-duncan , @ronawho , @psahabu , @Ldelaney , @ben-albrecht ) -- Following up on today's meeting I did the "introduce a population record" refactoring and this not only seemed nice, it clarified a bunch of other code that was in a strange place from the perspective of OOP design.  So I ended up doing a fairly major overhaul of the code as a result including incorporating all (I think) of the things that came up in our meeting.  

I originally did these edits in the context of the release version, but then given their magnitude and the fact that I already had a study version that was nearly identical to the release, I ended up checking it in over my study version so we could start seeing how the performance compares and to give people a chance to review what I'd done and providing further feedback before promoting it.  On my laptop performance seems slightly improved (where I'd hoped merely to break even).  I'd be more interested in the old vs. new '.gz' value if anybody's done the research to see what script he uses to compute it (I don't want to try and duplicate manually).

Anyway, let me know what comments you have on the new version please -- or whether you'd prefer to bow out of this endless cycle of review.  :)

Oh, also, I keep wrestling with how to handle the "contributed by" line in cases where we're all sitting around offering suggestions.  I guess I'll say if you think your contributions were significant enough that you think your name should be added, please speak up -- I don't feel particularly possessive of that line, but at the same time, I don't want to list everybody's name on every benchmark per se...

**Comment by bradcray** [comment]
Two belated notes:

* Don't bother trying to read the diff -- go straight to viewing the source
* I was just noticing that Lydia's chameneos-redux-yield has generally been faster than the release version on the shootout box, apparently due to using a read + task yield instead of a waitFor().  I'm trying to remember why these two idioms would behave differently...  anybody recall?

**Comment by lydia-duncan** [comment]
You saw that with these changes, we got a perfkeys mismatch on our intel run, right?  It looks like not all of the meetings occurred or were counted

**Comment by lydia-duncan** [comment]
I believe the waitFor difference was related to the point @ronawho brought up at the meeting, which is that waitFor would cause some thrashing with the smaller population size

**Comment by ronawho** [comment]
[waitFor()] (https://github.com/chapel-lang/chapel/blob/master/modules/internal/Atomics.chpl#L1328-L1336) just does a chpl_task_yield() under the hood though so that doesn't make a ton of sense to me

**Pull request merged**
