### PR TITLE
Added chpldocs for UtilMath module.

### PR DESCRIPTION
**Pull request by vasslitvinov**
I chose not to repeat the definitions of divceil and divfloor in this module.
I added cross-references to those functions in Math module instead.

I suggest in the future to move the contents of UtilMath into Math
and remove UtilMath altogether.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
I'm divided on whether we should add a note to the documentation that UtilMath will be merged into Math in the future (as it raises the question of why we haven't already).  What are your thoughts?

**Comment by vasslitvinov** [comment]
It is not merged because I didn't think about it before code freeze.

I like the idea of adding that note. Somehow I do not feel that the users will get hung up on that unanswered question.

**Comment by lydia-duncan** [comment]
Then this is good to go once that note has been added.  Thanks!

**Comment by vasslitvinov** [comment]
I confused git while merging chapel-lang,
so decided to re-do this and instead merged #1699
- it has identical changes.

**Pull request closed without merging**
