### PR TITLE
refactor isNothingvalue proc

### LINKED ISSUE #17254: Update Types.chpl to have isNothing in addition to isNothingType
Most of the functions in Types.chpl have variants along the lines of `isRecord()` that work for both types and values.

However we have `isNothingType` but not `isNothingValue` or `isNothing`.

I find `isNothingValue` a bit strange but would at least expect Types.chpl to include `isNothing`.

### PR DESCRIPTION
**Pull request by 12mohaned**
Resolves #17254.

This a simpler version of a previous [PR](https://github.com/chapel-lang/chapel/pull/17286/files#)

### CODE REVIEW

**Comment by 12mohaned** [comment]
@mppf

**Comment by mppf** [comment]
hi @12mohaned - thanks for making a version with 1 commit. I'll run testing on this PR and will commit it if testing is clean.

**Comment by mppf** [comment]
This has passed testing and it is ready to merge. I will not be able to merge it right away, though.

**Comment by 12mohaned** [comment]
@mppf I am mentioning you to make sure, you did not forget to merge it.

**Pull request merged**
