### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in

TemporaryConversionThunk.h, functionResolution.cpp, wrappers.cpp,
ParserContext.h, gpu-rocm.c
ChapelArray.chpl, IO.chpl

### CODE REVIEW

**Comment by cassella** [comment]
Please review:

- [ ] @benharsh IO.chpl
- [ ] @bradcray  ChapelArray.chpl
- [ ] @DanilaFe  TemporaryConversionThunk.h
- [ ] @dlongnecke-cray  ParserContext.h
- [ ] @jabraham17  IO.chpl
- [ ] @mppf  functionResolution.cpp
- [ ] @stonea  gpu-rocm.c
- [ ] @vasslitvinov  wrappers.cpp

I ran a quick start_test over a few directories.

**Comment by mppf** [comment]
@cassella - while I do think it is good practice to ask a few people with different areas of expertise to review a big PR, I don't think that works well for a PR like this. This PR is trivial and changes 10 lines. IMO, there is no reason to ask 8 people to review it, especially given that almost all of the changes are in comments.

As it happens, with this PR, the only non-comment change is to fix a spelling error from one of my PRs. So I will review.

**Comment by cassella** [comment]
> @cassella - while I do think it is good practice to ask a few people with different areas of expertise to review a big PR, I don't think that works well for a PR like this. This PR is trivial and changes 10 lines. IMO, there is no reason to ask 8 people to review it, especially given that almost all of the changes are in comments.

Hi @mppf, Thanks!  I'm fine doing it that way.  Was I was misinterpreting the guidance in #20360?

**Comment by lydia-duncan** [comment]
No, you weren't.  That guidance was from a group conversation to get the review responsibility into the hands of the people that contribute the typos (as opposed to just me and formerly Ben A, neither of whom contributed to them fairly frequently).  However, we have been having the problem where these PRs get left open for longer than they should because the last person to review hasn't been testing and merging afterwards and I think Michael's proposal would help with that

**Comment by mppf** [comment]
FWIW, it's my own opinion is that it's sufficient to choose one person who introduced some typos and ask them to review the whole PR if it is pretty small. You can ping somebody else who introduce a type if the 1st person doesn't get to it in a reasonably short amount of time.

**Pull request merged**
