### PR TITLE
Remove deprecated functions from arrays, types, and distribution modules

### PR DESCRIPTION
**Pull request by stonea**
This PR removes a handful of deprecated functions in the arrays, types, and distribution modules

Specifically:

- `newBlockDom`, `newBlockArr`, `newCyclicArr`, `newCyclicDom` (we have various `create*` methods in place now; these were deprecated in 1.30)
- Array `sorted`, `head`, `tail` and `reverse` functions (`reverse` and `sorted` were deprecated in 1.29, `head` and `tail` in 1.31). I also removed the `useNewArrayFind` config param while I was there. 
- Using `<=`, `>=`, `<` and `>` operations on types for subtype queries (we have named functions instead; these were deprecated in 1.30)

Notes for reviewers:

@bradc, please check the changes I made to `test/studies/shootout/submitted/knucleotide3.chpl` and `test/studies/shootout/submitted/knucleotide4.chpl` since these impact our "submitted" versions of the benchmarks and aren't just modifications to the `.good` file. I've previously modified `test/release/examples/benchmarks/shootout/knucleotide.chpl` to use `Sort.sorted` instead of `array.sorted`.

Also @bradc, note I removed the `useNewArrayFind` config param while I was there as a BTW. It looks like you deprecated this in 1.32 (https://github.com/chapel-lang/chapel/commit/11b344944b49976ff9602b4f3e23779aadf224c5), let me know if you'd like to keep it around for more than 1 release cycle.

TODO:
- [x] Paratests (non gasnet)
- [x] Paratests (gasnet)
- [x] Manually ensure old deprecation tests fail in other ways

### CODE REVIEW

**Comment by bradcray** [comment]
Changes to test/studies/shootout/submitted look OK to me.

In reviewing my own deprecations, I passed on removing newArrayFind() at this point since it hadn't been out for a few releases yet.  I'm less worried about retiring these behavior-changing configs early than I am about normal features, but didn't see any harm in letting it stick around one more release either—particularly since it's nodoc'd, so not cluttering much up.  Did you come across it simply while looking for all references to `@deprecated` in the module?

**Comment by stonea** [comment]
> Did you come across it simply while looking for all references to `@deprecated` in the module?

Yeah exactly. I just removed it as it looks like something that should be removed (but then double checked after committing my changes and saw that the deprecation was relatively recent). Again, I'm perfectly happy to undo the deletion if it's something that in the absence of my intervention would be sticking around.

**Comment by bradcray** [comment]
Probably preserving it is the right thing to do, though I suspect so few people would get tripped up by removing it that it's hard for me to argue that it's worth the effort.

**Comment by stonea** [comment]
> Probably preserving it is the right thing to do, though I suspect so few people would get tripped up by removing it that it's hard for me to argue that it's worth the effort.

Ok, put back in: https://github.com/chapel-lang/chapel/pull/23957/commits/a0321999a24dba11604eeb0e92a92b3c31b63743

**Pull request merged**
