### PR TITLE
Tim sort Implementation

### PR DESCRIPTION
**Pull request by RisingGeek**
#5724 
<b>My idea for TimSort -</b> Sort runs(chunks) of fixed size using existing InsertionSort. Merge 2 runs at a time using `_Merge()` function. Currently, I have taken the size of run as 3.

Checklist:

- [x] Documentation
- [ ] Correctness tests
- [ ] Performance tests

### CODE REVIEW

**Comment by RisingGeek** [comment]
@ben-albrecht  What is the procedure for checking Correctness tests and Performance tests?

**Comment by ben-albrecht** [comment]
@RisingGeek - https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst#develop-and-test-contributions-locally should point you in the right places

**Comment by Rapiz1** [comment]
I think you have deleted lots of files by accident.

**Comment by RisingGeek** [comment]
Oh, @Rapiz1 please tell how can I revert that?

**Comment by cassella** [comment]
I think it would be simplest to start with a new branch off of master, and apply your changes to that branch by copy-and-paste.  (Also, try not to commit your binaries to git (e.g., modules/package/Sort, ./hello))

And you'll want to add timSort to the other sorts tested in `test/library/packages/Sort/correctness/correctness.chpl` at least.  See [the Test System doc](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst) for details.

After that's working, the performance test for Sort.chpl is `test/library/packages/Sort/performance/performance.chpl`.  That same Test System doc has information about performance tests -- there's more to them than to correctness tests to get the performance reported in graphs.

**Comment by ben-albrecht** [comment]
@RisingGeek - I'm going to close this PR due to inactivity for now. We can re-open when you are able to pick up where you left off.

**Pull request closed without merging**
