### PR TITLE
Squash pointer warnings for CCE on c_fn_ptr tests

### PR DESCRIPTION
**Pull request by bradcray**
[spoon-fed to me by@ronawho]

My new 'c_fn_ptr' tests cause warnings due to assigning a 'void*'
pointer to a C function pointer.  This PR squashes the warning for
these tests for CCE.  The following simple C test demonstrates the
same warning:

        #include <stdio.h>

        void bar(void (*f)(void)) {
          f();
        }

        void foo(void) {
          printf("Hi!\n");
        }

        int main() {
          void* fptr = foo;
          bar(fptr);
        }

Note that the warning is CCE-specific and doesn't show up with gnu,
intel, or pgi.

Tests that generated the warning were:

* extern/fnPtrs/passFnsToC2x2.chpl
* extern/fnPtrs/passFnsToC2x.chpl
* extern/fnPtrs/passFnsToCChapel2.chpl
* extern/fnPtrs/passFnsToCChapel2x.chpl
* extern/fnPtrs/passFnsToCChapel.chpl
* extern/fnPtrs/storeFnsThenPass2x.chpl
* extern/fnPtrs/storeFnsThenPass.chpl

so I'm putting a COMPOPTS file into this directory to squash this
warning for these tests.

This is something we can't work around in the generated code until
such time as users can declare the argument and return types of their
external C function pointer types (and even then, we may still wish to
preserve the ability to specify a generic C function pointer like
'c_fn_ptr' for the sake of productivity).

Note that Nikhil ran into similar warnings with gnu in a different
context in PR#3992.

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho: want to review your own handiwork?  :)

**Comment by ronawho** [comment]
I wouldn't be opposed to a comment in the COMPOPTS file that mentioned what warning we're suppressing, but I don't feel very strongly since it's easy enough to look at the git log for it.

**Comment by bradcray** [comment]
@ronawho: I think that's a good idea.  I'm not merging tonight, because from what I'm seeing (on my Mac, say), the test system seems to skip all tests in the directory when the compiler != cray-prgenv-cray.  Do you see that too, or is it just me?

**Comment by ronawho** [comment]
Huh.. yeah I see that too. Looking into why

**Comment by ronawho** [comment]
Think I figured out what's going on, working on a fix now.

**Comment by ronawho** [comment]
Should be fixed with https://github.com/chapel-lang/chapel/pull/4010, which I'm testing now

**Comment by ronawho** [comment]
#4015 committed, should be able to merge this now

**Pull request merged**
