### PR TITLE
Add a constraints file to arkouda testing itself for now

### PR DESCRIPTION
**Pull request by lydia-duncan**
This is a hotfix for not having previously pinned setuptools versions.  Release
arkouda testing will not otherwise respond to changes to version numbers.  We
should remove this hotfix in the future.

Adds a constraints file to the arkouda testing directory, and uses it when
installing python testing requirements to explicitly limit which version of
setuptools is used.

----
Signed-off-by: Lydia Duncan <lydia-duncan@users.noreply.github.com>

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Testing in progress

**Comment by lydia-duncan** [comment]
Hoping for a post-review from @ronawho

**Comment by ronawho** [comment]
Normally, we do this sort of thing by just checking out the main copy of the directory we need: 

https://github.com/chapel-lang/chapel/blob/ebc4499b1bdd3b5b275afd6005c030df894052c5/util/cron/common-arkouda.bash#L42-L46

So I _think_ something like `git checkout $currentSha -- $CHPL_HOME/third-party/chpl-venv/` should work.

**Comment by lydia-duncan** [comment]
I would worry that this would mean we're not testing against the actual older release, though.  The other directories listed in there are testing-specific, but chpl-venv impacts the version of chpldoc built

**Comment by ronawho** [comment]
chpldoc isn't used for Arkouda testing, so that shouldn't matter. But we could limit it to just `git checkout $currentSha -- $CHPL_HOME/third-party/chpl-venv/test-requirements.txt`

**Comment by lydia-duncan** [comment]
True.  In any case, I don't really expect it to be a problem that can come up again, unless we pin to a version long enough that it gets removed (but we should be reasonably on top of that)

**Pull request merged**
