### PR TITLE
Remove a now passing .future

### PR DESCRIPTION
**Pull request by daviditen**
This test used to get an internal compiler error.  It now gets a reasonable
error message. Update the .good to match the error message it gets and
remove the .future file.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Is the new error message consistent across `forall` vs. `for` cases? Not that it has to, but that discrepancy is what led to the user reported error in the first place.

**Comment by daviditen** [comment]
Yes, `forall` and `for` both generate the same error that is in the new version of the .good file.

**Comment by ben-albrecht** [comment]
Looks good to me then.

**Comment by daviditen** [comment]
Thanks!

Just to provide a little more detail about when this was fixed, here are the related commits:
```
513778b - internal error
edf483c - loc-in-locales.chpl:3: error: Cannot declare a variable using a generic type
5ddd9b1 - loc-in-locales.chpl:3: error: Variables cannot be declared using (uninstantiated) generic types like 'channel'
3fb5737 - loc-in-locales.chpl:3: error: Variables can't be declared using not-fully-instantiated generic types like 'channel'
```

**Pull request merged**
