### PR TITLE
install all of util/config and byte-compile python code before installing

### LINKED ISSUE #17856: gather-cray-prgenv-arguments.bash not installed on Cray XC
I am seeing a new failure mode in our CI testing on on NERSC's Cray XC, Cori.  This was first seen with commit 7e877bf8f9 on May 26.  The previous CI run was a success about 2 weeks earlier on May 13 (the big gap due to an extended system maintenance).  I am not aware of anything relevant that changed in our CI scripts, but due to the NERSC center maintenance I cannot claim that nothing changed on the system.

From the output below, it looks to me like a key script is not getting copied by `make install`.  The `utils/config` dir has _some_ files, but not the one in the error messages.

```
$ chpl -o fft --ieee-float fft.chpl
sh: /[INSTALL_PREFIX]/util/config/gather-cray-prgenv-arguments.bash: No such file or directory
sh: /[INSTALL_PREFIX]/util/config/gather-cray-prgenv-arguments.bash: No such file or directory
internal error: LLV-CLA-TIL-3851 chpl version 1.25.0 pre-release (0)
Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

### PR DESCRIPTION
**Pull request by mppf**
Resolves #17856.

This PR takes two steps.

First, for #17856, it changes install.sh to install all of util/config
instead of particular files.

Second, this PR adjusts `configure` to compile the Python programs in
util/config and util/chplenv.

There are the `__pycache__` directories in util/config and I was
wondering if these should be installed. These directories store the
compiled byte-code for Python programs using Python 3.

My understanding is that once the Python files are installed, the
destination might not be writable anymore. So if we would like these
Python programs to have the benefit of compiled byte-code, we need to
make sure to compile them before or during installation. This is one of
the purposes of the Python package
[compileall](https://docs.python.org/3.9/library/compileall.html). We
could, in theory, run it during `install.sh` but that script is meant to
be run as root (when installing system-wide) and we don't want to run
Python code in that setting if we don't have to. Additionally, this step
isn't really necessary for people using Chapel from a source release. So,
I adjusted `configure` to run a new make rule with `make
compile-util-python` to do the byte compilation.

Note that in the context of a Debian package, the compiled byte code
should not be installed directly but should rather be generated as a
post-install action. But, since `configure` / `make install` doesn't have
a post-install action, we can't easily use that same strategy in other
settings. (A Debian package effort can just delete the compiled byte code
when creating the package and then recompile with a post-install action).

- [x] configure, make install, and compile and run Hello works on Mac OS
  X (with Python 3)
- [x] same steps on a SLES 12 system
- [x] observed non-fatal "missing compileall" error with python 2.7

Reviewed by @Maxrimus and @lydia-duncan - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
@ben-albrecht @lydia-duncan @Maxrimus - I don't necessarily need a review from all 3 of you but I'd like each of you to at least look at the PR message and let me know if the direction sounds OK.

**Comment by ben-albrecht** [comment]
Thanks for tackling this @mppf. 

>First, for #17856, it changes install.sh to install all of util/config instead of particular files.

This seems reasonable to me.

> Second, this PR adjusts configure to compile the Python programs in util/config and util/chplenv.

For my own understanding: Before this change, if the user doesn't have write-access to the install directory, do they get some kind of error or just slower python module loading than if they were able to cache byte-compiled modules?

**Comment by mppf** [comment]
> For my own understanding: Before this change, if the user doesn't have write-access to the install directory, do they get some kind of error or just slower python module loading than if they were able to cache byte-compiled modules?

AFAIK, slower Python module loading.

**Review by Maxrimus — APPROVED** [review]
Methodology seems sound to me, don't see any possible code issues. I'd recommend getting a secondary review if possible, but LGTM.

**Review by lydia-duncan — APPROVED** [review]
Looks good to me!

**Pull request merged**
