### PR TITLE
Raise instantiate max

### PR DESCRIPTION
**Pull request by stonea**
We've had users hit the instantiation limit for things that aren't actually causing an infinite recursion of type/function instantiation in the compiler.

Prior to this PR the limit was 256 but that's somewhat arbitrary.

We don't have any evidence that 512 would lead to painfully long compile but we do have evidence that 256 can sometimes be too low.

Let's raise it.

### CODE REVIEW

**Comment by bradcray** [comment]
For that specific future... I think I'd be inclined to just retire it.  I think of futures as locking in something we want to fix or change, but I'm not really sure what the end-game for a test like this would be...  And I'm not convinced that running it or keeping it around is keeping us apprised of an important behavior that we'd want to track if it changed.

**Comment by bradcray** [comment]
I'm in favor of this PR, but since it's a change in behavior/design-y, I might at least give a quick heads-up to the team to see whether anyone objects to it.  I wouldn't expect that, but... better to hear about any qualms before merging rather than after.

**Review by bradcray — APPROVED** [review]
Thanks for picking this up!

**Comment by stonea** [comment]
> For that specific future... I think I'd be inclined to just retire it.

Yeah I agree, I'm inclined to close the test just cause I don't want to deal with it, it's causing failures in Jenkins from my previous PR (https://github.com/chapel-lang/chapel/pull/20436), and when/if I submit this PR it'll turn into something that'll timeout.

I am curious though if (using our existing test infrastructure) it is possible to lock down a future as something we know will blow past our timeout limit.

Maybe this would be useful; maybe not but I could imagine that sometimes we could have something we know is inefficient and would want to be notified when that changes --- once that does change we'd then want to lock it down so we don't get a later performance regression. 

We do have performance testing but I think that's not as narrowly focused and I don't think it's as automated in the sense of alerting us to changes (we generate graphs that we manually watch for regression)?

Anyway, food for thought.

**Comment by bradcray** [comment]
> I am curious though if (using our existing test infrastructure) it is possible to lock down a future as something we know will blow past our timeout limit.

I'm drawing a blank at the moment.  A `.timeout` file can be used to constrain a long-running test to a certain amount of time, and we definitely do that sometimes.  It may be that the only way we have to handle this today would be to make it a `.future` with a `.good`, but not a `.bad`?  At least, I think when a test times out, we won't do any comparison against the `.bad`, so I'm not sure there's anything that could/should be put into the `.bad` to preserve the specific "failing due to timeout" behavior.

**Pull request merged**
