### PR TITLE
lowerErrorHandling compiler pass (no-op)

### PR DESCRIPTION
**Pull request by psahabu**
To be merged on my return.

- skeleton
- includes a `verify` check
- passes linux64+flat testing, `--verify` on `hellos`

@ronawho: #5088

### CODE REVIEW

**Comment by mppf** [comment]
@psahabu - this looks like a good initial step. I think this is a good candidate for squashing into one commit, one way or another. BTW I've updated issue #4977 to refer to this PR.

**Comment by psahabu** [comment]
@noakesmichael: Here's the PR, thanks again for reviewing.

**Comment by psahabu** [comment]
@ronawho: I'm going to merge this tomorrow (Tuesday), so if you could merge #5088 that'd be awesome, thanks.

**Comment by ronawho** [comment]
ok, I'll merge whenever this goes in

**Pull request merged**
