### PR TITLE
Move refPropagation into its own file

### PR DESCRIPTION
**Pull request by benharsh**
Testing:
- [x] full local

### CODE REVIEW

**Comment by ronawho** [comment]
👍 

Do we want to make it it's own "pass" at some point as well?

**Comment by benharsh** [comment]
Isn't it already its own pass? https://github.com/chapel-lang/chapel/blob/master/compiler/main/runpasses.cpp#L139

**Comment by ronawho** [comment]
Oh.. what am I thinking of then. Maybe it's currently controlled by --[no-]copy-propagation instead of having it's own --[no-]ref-propagation?

**Comment by benharsh** [comment]
Yeah, I think it still relies on that same flag.

**Comment by ronawho** [comment]
Ok. Not for this commit, but I'd be in favor of adding a flag for ref propagation

**Pull request merged**
