### PR TITLE
LLVM improvements

### LINKED ISSUE #11678: RV integration emits "loop not vectorized" warnings/remarks
After PR #11673, when RV is enabled, the Chapel compiler emits `llvm.vectorize.enable` metadata. When the stock LLVM LoopVectorizer (not RV) sees these metadata, it emits a lot of "loop not vectorized" remarks and warnings. This interferes with testing (and the prediff-ignore-remarks is a workaround).

```
export CHPL_SYSTEM_PREDIFF=`pwd`/util/test/prediff-ignore-remarks
```

### PR DESCRIPTION
**Pull request by mppf**
As part of  #11159 and #11679, I developed several minor improvements to
the LLVM support.

Resolves #11678.

* When enabling RV vectorization for a loop, use rv.vectorize.enable
  instead of llvm.vectorize.enable to avoid LoopVectorizer warnings
  (issue #11678).
* Simplifies codegenInvariantStart to simply call the LLVM IRBuilder
  method CreateInvariantStart
* Generates target-cpu and target-features metadata for functions
  generated by the Chapel compiler when --specialize is enabled. This is
  important for certain optimizations.
* in FnSymbol::codegen(), which generates a function SymExpr (ie. for a
  call), allow generating LLVM intrinsic calls, to support prototyping.
* Adjusts some includes in clangUtil.cpp to work with clang master
* fixes a conditional nesting problem in noAliasSets.cpp
* adjusts third-party/llvm/Makefile to more easily allow rebuilding (by
  touching a particular file)
* simplifies use of update-llvm.sh by stashing the LLVM patches and then
  re-applying them
* adjusts test/npb/is/diten/ and test/studies/hpcc/RA/marybeth/ tests to
  be correct under vectorization

- [x] full local testing
- [x] full local --llvm testing with RV enabled
- [x] full local --llvm --fast testing
- [x] RV testing (which doesn't quite pass yet - see #11886)

Reviewed by @dmk42 - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
[Error cannot locate program output comparison file analysis/alias/ref-to-array-of-arrays.good]
[Error matching program output for llvm/llvm-invariant/config_const]
[Error matching program output for llvm/llvm-invariant/global_const]

**Comment by mppf** [comment]
@dmk42 - I need to do more testing on this but I'd really appreciate review feedback soon if you're able to have a look. Thanks!

**Comment by mppf** [comment]
RV testing failures:
* exercises/EstimatePi5opt.chpl
  * this one is due to a problem in the test (race condition on seed)

* library/standard/Math/promotion/erfc.chpl
  * running into an assert within RV

* reductions/thomasvandoren/test/TestMink.chpl
   * reduce expressions aren't being marked as a hazard

**Comment by simoll** [comment]
Fixed by https://github.com/cdl-saarland/rv/commit/e95d57a9cddba1e5a6426227f50f09126a472e77
`xerfc` is not vectorized although `xerfc_u15` is available in SLEEF because `rv::Config::maxULPErrorBound` defaults to `1.0` .. 

@mppf - What is the maximum ULP error allowed for math functions when compiling with "--fast"?

> RV testing failures:
>     * library/standard/Math/promotion/erfc.chpl
>       
>       * running into an assert within RV

**Comment by simoll** [comment]
> @simoll -
> 
> > @mppf - What is the maximum ULP error allowed for math functions when compiling with "--fast"?
> 
> Are you asking what we set it to in rv::Config (we don't set it) or what it should be in theory? Do you know what a C compiler would use here?

I am asking what the max ULP error _should_ be for Chapel. 

For `libc` the ULP error seems to depend on the math function being called and the target architecture. E.g. `erfc` has a guaranteed max error of 3 ULP with libc on x86 while other functions don't have any known error bound (according to: https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html).

The answer for Chapel could depend on the compiler flags (e.g. "--fast" could mean that 3.5 is ok). You could also add a compiler option to let users specify the error bound directly (`--math-precision=<ulp>`). This option can only be a hint however since an implementation with the requested (and guaranteed) ULP error might not be available.

**Comment by mppf** [comment]
@simoll - I'm not sure what the default should be (1? 3? something like that?) but we have `--ieee-float` which would make it use the most precise available (presumably) and `--no-ieee-float` which would allow some imprecision.

But I don't know how to communicate these settings to RV/SLEEF.

**Comment by simoll** [comment]
> @simoll - I'm not sure what the default should be (1? 3? something like that?) but we have `--ieee-float` which would make it use the most precise available (presumably) and `--no-ieee-float` which would allow some imprecision.

RVs default of 1.0 seems reasonable for `--ieee-float` looking at (https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html) and (http://sleef.org/benchmark.xhtml).

> But I don't know how to communicate these settings to RV/SLEEF.

I can implement support for module level hints (something like `!1 = ('rv.math.maxulperror', 3.5)`). The bound would apply to all functions in that module.

**Pull request merged**
