### PR TITLE
Fix set &= operator

### LINKED ISSUE #15958: Set &= is wrong
### Summary of Problem

In #15644 I broke the `set` `&=` operator in the "don't use a temporary" case:

```chapel
    } else {
      if lhs.parSafe && rhs.parSafe {
        forall x in rhs do
          lhs.remove(x);
      } else {
        for x in rhs do
          lhs.remove(x);
      }
    }
```
That's `lhs -= rhs`, not `lhs &= rhs`

### Steps to Reproduce

**Source Code:**

```chapel
// Please provide source code that will reproduce the problem.
// You can insert your code inline if it's not too long.
// Otherwise, you can attach it as a file or provide a URL to it.
// To the extent possible, providing simplified programs demonstrating the
// problem will be appreciated.
// You can also replace this section with "Associated Future Test(s)" below.
```

**Compile command:**

**Execution command:**

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- (For Cray systems only) Output of `module list`:

### PR DESCRIPTION
**Pull request by cassella**
In my haste to implement a temp-less &= operator in #15644, I
implemented -= instead of &=.  I don't believe &= can be implemented
without a temp without iterating over the lhs while modifying it.
Just unconditionally use the version that does use a temp, but
implements the correct operation.

This wasn't caught by the test because the &= test only went through
the temp-full path.  Now that there is only one path again, the
existing test tests it.

For the other operators whose implementation has multiple paths or
isn't symmetric, add additional cases to the tests to hit them.
Those are: &, ^, |

Fixes #15958

### CODE REVIEW

**Comment by cassella** [comment]
@dlongnecke-cray 

test/library/standard/Set (still) passes.  :-/

**Comment by dlongnecke-cray** [comment]
Sounds like we need to add a better test for `&=` then!

**Comment by cassella** [comment]
@dlongnecke-cray Are you asking for test improvements?

**Comment by dlongnecke-cray** [comment]
@cassella No, I just wasn't sure how to interpret the `:-/` face.

**Comment by cassella** [comment]
I was just disappointed that it had passed before.  To further clarify, &nbsp; :'-|   &nbsp;&nbsp;  q_q &nbsp;&nbsp;   >:-(  &nbsp;&nbsp;  #_# &nbsp;&nbsp;   O:-)

**Comment by dlongnecke-cray** [comment]
Ah, gotcha.

**Comment by cassella** [comment]
Are you waiting for anything else from me?

**Comment by dlongnecke-cray** [comment]
@cassella I was just waiting for you to ping me saying it was ready for final review and merge.

**Comment by cassella** [comment]
ping @dlongnecke-cray this is ready for final review and merge.

**Comment by dlongnecke-cray** [comment]
Testing now, merge in a bit.

**Comment by dlongnecke-cray** [comment]
Hi @cassella, could you go ahead and merge an up-to-date copy of master into this branch? I'm trying to avoid clobbering third-party when I build (getting qthreads errors).

I will handle final testing for you.

**Comment by cassella** [comment]
@dlongnecke-cray Done.  test/library/standard/Set passes.

**Pull request merged**
