### PR TITLE
Replace openfp with file initializer that can throw

### LINKED ISSUE #20146: IO module: how should we adjust openfp?
It has the signature:
```chapel
 proc openfp(fp: _file, hints: iohints = IOHINT_NONE): file throws
```
And creates a `file` that points to the C file pointer provided by the `fp` argument.

Note that `_file` is a primitive type inserted into the program by the compiler, and represents the C type `FILE *`.  It seems like it would be more appropriate for this type to be an extern type defined in CTypes, if that's something we can do.  It probably should also be named `c_FILE` or `C_FILE` or `c_file` in that case.

We think it would be reasonable to keep this function.  If `_file` does get moved to CTypes, should this function also be moved there?

It also seems like this function should be renamed.  Similarly to the options proposed by #20143, here are some ideas we came up with:
- openFP
- openFp
- openFilePtr
- openFilePointer
- make it a factory function on the `file` type, e.g. `file.fromFP` or `file.fromFilePtr`, since it's already open as a result of how it is obtained?
- make it an initializer on the `file` type, for a similar reason?

This function also notes in its documentation that the I/O system will ignore the channel offsets when reading or writing to a file opened by this function, so it would be good to have some way for the `file` object to know that and generate a warning when someone tries to open a channel with an offset

This function throws a subset of the errors thrown by `open` (as discussed in #20139).  Similar updates should be performed to its documentation.

Note that #20430 will also impact this function

### PR DESCRIPTION
**Pull request by lydia-duncan**
Resolves #20146
Resolves Cray/chapel-private#4259

In discussing the interface for `openfp`, we realized that it made
more sense as a file initializer that can throw when issues are
encountered, since it is creating a Chapel `file` wrapper around
an already open file pointer.  This change makes that adjustment

<details>

Adds a private helper function that the initializers call, in part to
support both the `iostyle` version and the version without an
`iostyle` and in part because initializers can only call throwing
functions today rather than explicitly throwing themselves.

In the docs for the stable initializer, note that the preferred way to
create a file is still through the `open` function, to minimize
confusion.

Wrap the initializer call to create `stdout` and `stderr` in parentheses,
since the call's result then has `.writer` called on it.

</details>

Adjusts the already existing deprecation test to use the new message.
Adds a separate deprecation test for the openfp iostyle deprecated
version.  Adjusts the unstable test for the iostyle version to use the
initializer instead of openfp.  Moves the test of openfp's normal behavior
to a different directory and adjusts it to call the initializer instead.

Passed a full paratest with futures and checked the built docs, ensuring
the links all work

### CODE REVIEW

**Review by jeremiah-corrado — APPROVED** [review]
Looks good to me!

**Comment by jeremiah-corrado** [comment]
Actually, should there be a test of the throwing behavior? I.e., trying to open a file pointer that has already been closed.

**Comment by lydia-duncan** [comment]
Probably, I think I got distracted by the bugs with throwing initializers that I found

**Comment by lydia-duncan** [comment]
I've made a test of the error case - it looks like the error message on Macs is "function not implemented" when a closed file pointer is passed but the message is more clear on linux.  At least in both cases it throws a SystemError as intended so I think it's okay for now, but I'll open an issue about the portability message since that's a pre-existing issue and seems more complex given the OS variance.

**Comment by jeremiah-corrado** [comment]
Ok sounds good. And that change looks good to me, thanks!

**Pull request merged**
