### PR TITLE
Compiler bug fixes supporting locales

### PR DESCRIPTION
**Pull request by mppf**
In my work on locale models, I was running into apparent order of
resolution issues with chpl_task_getRequestedSubloc() which returns
chpl_sublocID_t. Resolution was not correctly handling the declared
return type for chpl_task_getRequestedSubloc (an extern function) being a
type alias (type chpl_sublocID_t = int(32)).

This PR:

 * removes a useless toSymExpr
 * removes some arguments to a USR_FATAL_CONT that were unused because
   they were not present in the format string
 * prevents normalize from calling _statementLevelSymbol for return type
   expressions, since that confused the issue
 * and adjusts resolveSpecifiedReturnType to call resolveTypeAlias if the
   return type is a type variable and to call
   resolveDefaultGenericTypeSymExpr if it remains generic after
   resolveTypeAlias (e.g. proc foo():range { ... } )
 * and factors resolveDefaultGenericType into another helper function
   resolveDefaultGenericTypeSymExpr.

Passed full local testing.
Reviewed by @vasslitvinov - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
[Error matching compiler output for classes/bradc/overloadMethods/v2NoReturnValueButType]
      [Error matching compiler output for functions/deitz/iterators/leader_follower/test_recursive_leader]
      [Error matching compiler output for functions/ferguson/retrange]
      [Error matching compiler output for users/thom/returnGeneric]
      [Error matching compiler output for users/thom/returnGenericLineno/util]

**Comment by mppf** [comment]
Closing until after v1.13.

**Comment by vasslitvinov** [comment]
Looks good to me.

Please explain in the PR message why you removed the additional args in that call to USR_FATAL_CONT at the (new) Line 2700.

**Comment by mppf** [comment]
OK, thanks. I removed them because they were unused arguments because the format string didn't refer to them.

I plan to merge this PR on Monday.

**Pull request merged**
