### PR TITLE
Fix the timing error in PRK-DGEMM

### PR DESCRIPTION
**Pull request by e-kayrakli**
Fix a small bug with potentially big impact in reported performance. Solves #6413 

The test passed with standard linux64 config.

### CODE REVIEW

**Comment by e-kayrakli** [comment]
@ronawho - It seems this is all needed to be fixed. I quickly compared with base OpenMP implementation, especially in terms of the checksum. Did you notice anything else?

**Comment by ronawho** [comment]
I think you'll want to get rid of the `iterations==1` checks to start the timer. Otherwise for 1 iteration, you'll start the time on iteration 0.

**Comment by e-kayrakli** [comment]
Assuming you meant `niter==1`...

**Comment by e-kayrakli** [comment]
Ah, true.

Small nit: I have used `niter` whereas Stencil and Transpose use `iteration` as the current iteration number. I think this confusion needs to be resolved in favor of the latter.

**Pull request merged**
