### PR TITLE
Curl check-http-setopt test: add module for error handling

### PR DESCRIPTION
**Pull request by cassella**
Add a module around the test so that on Error we can kill
the http server.

---
Signed-off-by: Paul Cassella <gitgitgit@manetheren.bigw.org>

### CODE REVIEW

**Comment by cassella** [comment]
@mppf @ronawho ?

This is what I had in mind for making sure the http process the test spawns is killed if the test throws an error.

I tried to do something similar for the other check-http test, but ran into #18218 .

I could re-indent the file to reflect all being within a module now if you want.

I couldn't figure out a way to get `start_test` to ensure the server's killed if the test runs into a halt() or is otherwise killed abnormally.  Is there a simple way to do that?

**Comment by ronawho** [comment]
> I tried to do something similar for the other check-http test, but ran into #18218.

This is not code I'm familiar with. I would guess @vasslitvinov or @mppf are the most familiar with this code in lower iterators, but they are both out.

> I could re-indent the file to reflect all being within a module now if you want.

Yeah, let's do that.

> I couldn't figure out a way to get start_test to ensure the server's killed if the test runs into a halt() or is otherwise killed abnormally. Is there a simple way to do that?

Does it not get automatically killed when the chapel process dies? I can't think of a simple way to have start_test kill it. What comes to mind is something ugly like writing the pid of the server to some known file and have a prediff that tries to kill that process if it's still running.

**Comment by cassella** [comment]
> a prediff that tries to kill that process

Ooh, that's devious.  And one of the tests already has a prediff file.

Though I guess since this hasn't been a problem in the two years the test has existed, it may not be worth going to such lengths. I only hit it specifically working on the test.

I'll apply the workaround Brad suggested in #18218 and reindent both files.

Though using the pid/kill approach would mean the tests don't have to change at all.  Hmm.

Oh, but if CHPL_LAUNCHER puts the _real process somewhere remote, it'll be hard to kill.  (Though many of those (aprun, srun) should take care of cleaning up the child process anyway.)


Yes, the parent process exiting or getting killed doesn't cause the child python/http.server process to exit.  (I'd mentioned in the last bullet point in the first comment in #18200)

**Comment by cassella** [comment]
The first of the new commits contains the functional changes to add the module, throws, and defer statements, and workaround, to the other test.  The final commit contains only whitespace changes for indentation.

Handling Errors is at least handling the easy "half" of the problem...

**Comment by ronawho** [comment]
> Ooh, that's devious. And one of the tests already has a prediff file.

> Though I guess since this hasn't been a problem in the two years the test has existed, it may not be worth going to such lengths. I only hit it specifically working on the test.

Thinking about this a little more, I wonder if we could instead start the python server with a timeout. i.e. use the linux `timeout` utility or probably our `util/test/timedexec`. We'd have to update sub_test to set the executable timeout in some env var, but that should be pretty easy. I'd be happy to add that env var if you think this is worthwhile, but I'd also be fine leaving things as-is.

**Comment by cassella** [comment]
Less devious, but probably a good idea nonetheless.  I think that makes sense.

What's the advantage of `timedexec` over `timeout`?

I see the `SIGINT` we send in `stopServer()` if sent to `timedexec` would cause it to kill the server in turn.  (I think `timeout` both sends the signal to its child directly, and also sets itself up as a process group leader of a new process group, so it can `kill(0, SIGINT)` to send the signal to all descendants of its child (that are still in the process group) too.)

**Comment by ronawho** [comment]
> What's the advantage of timedexec over timeout

I'm not sure, but presumably we had some reason for creating our own script instead of just using timeout. My guess is portability, but I'm not positive.

**Comment by cassella** [comment]
Will `timedexec` be available to execute by the test as executed off on a compute node?

**Comment by ronawho** [comment]
> Will timedexec be available to execute by the test as executed off on a compute node?

That's a good question. It should be able to since it's just a thin perl shim, but I'm not positive. Actually, I guess I don't even know if perl is available on say XC compute nodes.

**Comment by ronawho** [comment]
Thinking about it a little more, I'm inclined to merge this PR since it's a nice improvement and then if you're feeling up to it opening a new PR for any timeouts? Thoughts on that?

**Comment by cassella** [comment]
That makes sense to me.

Given that it's caused a minor problem for one person (me) in two years, it's probably not worth going to any significant trouble over, so I'm not inclined to spend much more time on it.

(Even the timeout approach still isn't trouble-free.  Since the timeouts are fairly generous, by the time the server is killed we'll likely have had time to run through a few more tests.  And check-http runs a few times via multiple `execopts` lines, so a failure on an early one will lead to problems for the next few.)

**Comment by ronawho** [comment]
That all sounds good to me. Unless I hear otherwise from you I will plan on testing and merging tomorrow.

**Comment by ronawho** [comment]
Looks good, thanks Paul!

**Pull request merged**
