### PR TITLE
Fix multiple start_test invocations to print correct summary

### PR DESCRIPTION
**Pull request by mppf**
When developing and testing some PR, I often need to run `start_test` to
check many failing tests. It helps me if I can do that in parallel within
one `CHPL_HOME` directory. However, previously `start_test` would get the
summary information confused between multiple runs (because it used the
default log location, e.g. `test/Logs/mppf.linux64.log`, for both runs,
and then computed the summary by reading this file). The result is that
usually one of the concurrent `start_test` runs prints out 0 tests were
run. (Yes, I could specify `-logfile` but I don't want to think that hard
about the testing infrastructure while checking many tests).

This PR adjusts `start_test` to output the correct summary information
even if there were concurrent invocations of `start_test` using the same
log file. It does that by storing the log output, by default, in a
per-process file path (just adding a pid to the default log path) - and
summarizing from this unique-to-process copy - and then copying to the
final log output from that directory when `start_test` is finishing. If
`-logfile` is specified, it does not use the per-process log with a pid
in the pathname.

This required a small amount of reordering of certain operations within
`start_test` (creating the temporary directory before starting logging -
not strictly necessary I think it's an improvement; deleting the
temporary directory after summarizing). Note that I took the approach of
creating a per-pid summary also. That way, with concurrent runs using the
same final log destination, the final .log and .summary represent one of
the runs (and we don't have the summary from one and logfile from
another, say).

Reviewed by @ronawho - thanks!

- [x] passed full local testing

### CODE REVIEW

**Comment by ronawho** [comment]
The code looks ok, but I'm not sure how I feel about the functionality. I sometimes look at the in-progress logfile, or look at a logfile from a run I killed early. We also have systems where /tmp is limited. 

Maybe instead of writing the log file to /tmp, just write it in the same dir as the real logfile will be?

**Comment by mppf** [comment]
> I sometimes look at the in-progress logfile, or look at a logfile from a run I killed early. We also have systems where /tmp is limited.

If you killed the run early, it should work, because the copying happens in cleanup, which runs anyway.
The version here would prevent you from looking at an in-progress logfile, though.

> Maybe instead of writing the log file to /tmp, just write it in the same dir as the real logfile will be?

Like with the tmpdir name or pid? E.g. `test/Logs/mppf.linux64.pid18671.log` ? That would be fine with me.

**Comment by ronawho** [comment]
> Like with the tmpdir name or pid? E.g. `test/Logs/mppf.linux64.pid18671.log` ? That would be fine with me.

Yeah logname with pid attached works for me

Do we ignore this and write directly to the logfile if `--logfile` is thrown? (If not I think we should, though I'm not 100% why I think that)

**Comment by mppf** [comment]
> Yeah logname with pid attached works for me

OK I'll update it

> Do we ignore this and write directly to the logfile if --logfile is thrown? (If not I think we should, though I'm not 100% why I think that)

Sure, that is fine with me

**Comment by mppf** [comment]
@ronawho - I did those things. I think this is ready for another look. I could un-do the change adding `set_up_tmpdir()` but I also think it's reasonable to set up the tmp dir earlier.

**Comment by bradcray** [comment]
I had the same question as Elliot w.r.t. the following (I do this a _lot_):

> The code looks ok, but I'm not sure how I feel about the functionality. I sometimes look at the in-progress logfile

So I'm glad that we're not hiding the logfile away too much.  I do wonder a little about how much of a hassle it's going to be to find the right one now, though...  Would there be anything sane along the lines of having the default logfile symbolically link to the latest test run that was started while it's running?)

I've also been bit by the problem you describe (as well as accidentally blowing away a logfile I wanted to refer to by doing a second, consecutive run), and never use `-logfile` even though I implemented it, so I'm also very amenable to this change.

Am I understanding that the log files will never be automatically cleaned up?  (unless you happened to get the same PID again I suppose)?  I think I like that behavior, but could also imagine it making things noisy after awhile.

**Comment by mppf** [comment]
@bradcray 

> Am I understanding that the log files will never be automatically cleaned up? (unless you happened to get the same PID again I suppose)? I think I like that behavior, but could also imagine it making things noisy after awhile.

start_test just uses the `pid` unique log file during the run. It moves them to the default log file location at the end of the run (no matter what).

>  I do wonder a little about how much of a hassle it's going to be to find the right one now, though

If you don't use `-logfile`, you should only ever see as many logfiles as you have `start_test` runs currently running. Once these finish, they store to the default log location, and since there's only one of those, if you don't have a `start_test` running, you should only ever have 1 log that isn't cleaned up (as before).

**Comment by ronawho** [comment]
Just FYI now that we've lived with this for a few days, I like this change and the running logfile having a different name hasn't impacted me since I always tab-complete to open it anyways.

**Pull request merged**
