### PR TITLE
bigint versions of pidigits

### PR DESCRIPTION
**Pull request by bradcray**
This adds a pair of pidigits versions to the release as potential candidates for the release.  Both are based on the current GMP-based version of pidigits in the release.  The plan is to let the three release versions run for a night or two, then make a call as to which version(s) should stay.

* pidigits-bigint.chpl : is a version that uses bigints and the new operations on them as much as possible, but falls back on methods in cases where our compiler + implementation would currently insert a temp + copy.  E.g., in 'a = b + c;' the + operator would create a result value and then deep-assign it into 'a'.  This version therefore would call 'a.add(b, c)' instead to avoid the temp.  The eventual goal is to improve our record constructors and optimizations to the point that either version would perform the same.

* pidigits-bigint-cleaner.chpl: is a version that uses the cleanest operations regardless of overhead.

Also made some simple whitespace and formatting edits to the current GMP-based release version and fixed a comment that Mike determined was wrong.

Added these versions to the pidigits.graph file and renamed the labels to avoid all the redundant "pidigits" labels (which seem obvious given the context).

Updated the README to list current TODOs for pidigits and remove the old ones.

### CODE REVIEW

**Comment by ronawho** [comment]
I didn't review in depth, but at a high level looks good to me!

**Comment by bradcray** [comment]
@thomasvandoren is going to be happy to see this one see the light of day! (and, more importantly, all the work @noakesmichael did to make it a possibility)

**Comment by noakesmichael** [comment]
Building on the foundation by Laura Delaney.

Mike

On Sep 22, 2016, at 9:15 PM, Brad Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


@thomasvandoren<https://github.com/thomasvandoren> is going to be happy to see this one see the light of day! (and, more importantly, all the work @noakesmichael<https://github.com/noakesmichael> did to make it a possibility)

**Comment by bradcray** [comment]
Oh sheesh yes, how could I forget @Ldelaney's work? (other than being fried during release week of course!)

**Comment by thomasvandoren** [comment]
🎉

**Pull request merged**
