### PR TITLE
Update extern decls of chpl_mem_* functions to match the runtime signatures

### PR DESCRIPTION
**Pull request by ronawho**
The extern declarations of the chpl_mem_* functions in ChapelLocale were using
opaque instead of c_void_ptr, int instead of size_t, and int(16) instead of
chpl_mem_descInt_t.  This fixes the extern declarations so they match the
runtime signatures and adds safeCasts where appropriate.

The patch makes sense on its own, but the real goal is to work towards the
removal of the additional extern decls and uses of the chpl_mem_* functions in
the string module. The string module has its own externs instead of using the
chpl_here_* routines because the signatures were off.

Individual commits have more details on the specific changes.

### CODE REVIEW

**Comment by ronawho** [comment]
@bradcray and/or @gbtitus mind reviewing? It's probably easier to review each commit individually.

**Comment by gbtitus** [comment]
reviewing ...

**Comment by gbtitus** [comment]
This looks fine modulo the two line comments.

**Comment by ronawho** [comment]
@gbtitus  updated to remove duplicate decls, changing chpl_mem_descInt_t ended up being really hard, so I'm going to punt on that for now (hopefully get back to it in a few days)

**Comment by gbtitus** [comment]
Sounds good, yep.

**Pull request merged**
