### PR TITLE
    Add a user error for applying 'borrowed' to arrays

### LINKED ISSUE #18717: 'borrowed' keyword applied to an array crashes the compiler
### Summary of Problem

Trying to declare a `borrowed` array causes an internal compiler error (AST-EXP-0299).

### Steps to Reproduce

**Source Code:**

```chapel
record Chunk {
  type eltType;
  var D: domain(1);
  var data: borrowed [D] eltType;

  proc init(type eltType) {
    this.eltType = eltType;
  }

  proc init(array: [?X] ?t) {
    this.eltType = t;
    this.D = X;
    this.data = array;
  }
}

proc main()
{
  var x = new Chunk([1, 2, 3]);
}
```

**Compile command:**
`chpl -o error error.chpl`

### Configuration Information

- Output of `chpl --version`: 1.25.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: smp *
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: qthreads
CHPL_LAUNCHER: smp
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc 11.2.0

### PR DESCRIPTION
**Pull request by bradcray**
This is motivated by issue #18717 and addresses it, but is not
    particularly satisfying.  Specifically, what I did was to jump into
    the most obvious place in the callchain that led to the error and
    spot-checked for the pattern that was causing the problem (namely
    applying 'borrowed' to an array type like '[D] int').  The reason
    that this is unsatisfying is that:

    * it doesn't make any attempt to prevent against applying other
      ownership types to arrays

    * it doesn't make any attempt to prevent against applying 'borrowed'
      to other non-class types

    The callstack leading to the error is:

    ```
      * frame #0: 0x000000010075aa04 chpl`gdbShouldBreakHere() at misc.cpp:72:1
        frame #1: 0x00000001000dbc89 chpl`Expr::qualType(this=0x00000001186b5370) at expr.cpp:299:3
        frame #2: 0x000000010008cdf6 chpl`BaseAST::typeInfo(this=0x00000001186b5370) at baseAST.cpp:405:28
        frame #3: 0x000000010008d1c5 chpl`BaseAST::getValType(this=0x00000001186b5370) at baseAST.cpp:444:16
        frame #4: 0x0000000100154852 chpl`returnInfoToBorrowed(call=0x00000001186b52e0) at primitive.cpp:473:27
    ```

    So this led to questions for me like:

    * Should you be able to call 'getValType' on an array type?  If so,
      what should it do?  If not, how do you prevent another internal
      error.  Would we need another 'hasValType' query that
      'returnInfoToBorrowed()' would call to handle the general issue?

    * Should you be able to call 'typeInfo()' on an array type?  (seems
      like it?)  But if so, then how to prevent it from calling into the
      general 'Expr::qualType()' overload.

    Anyway, a point solution seemed better than keeping the current
    internal error given that it was easy, so I'm filing this as a
    placeholder and for consideration, and/or to see whether others have
    different suggestions.

    Resolves #18717 (but not way satisfactorily)

### CODE REVIEW

**Comment by bradcray** [comment]
@chapel-lang/core-contributors : Who's particularly familiar with getValType() / typeInfo() / qualType() that might be able to advise me on this PR?

**Comment by mppf** [comment]
I think this is OK for now.

**Comment by bradcray** [comment]
Thanks for taking a look, Michael.  Did you read the (poorly formatted) OP and have any opinion on its questions?

* Should you be able to call 'getValType' on an array type?  If so,
  what should it do?  If not, how do you prevent another internal
  error?  Would we need another 'hasValType' query that
  'returnInfoToBorrowed()' would call to handle the general issue?

* Should you be able to call 'typeInfo()' on an array type?  (seems
  like it?)  But if so, then how to prevent it from calling into the
  general 'Expr::qualType()' overload?

**Comment by mppf** [comment]
> Should you be able to call 'getValType' on an array type? If so, what should it do? 

Yes, 'getValtype` should just return the passed in type for anything that isn't a reference type. If it is a reference type, it should return the value type.

> Should you be able to call 'typeInfo()' on an array type? (seems like it?) 

Yes

> But if so, then how to prevent it from calling into the general 'Expr::qualType()' overload?

In my opinion, we should have already (recursively) resolved to find the type of the loop expression / convert the loop expression into the array type. (In the production compiler, we can replace the loop expression with a SymExpr pointing to the array type during resolution. In the rework effort, we will have recursively established the type of the loop expression before resolving the call containing it). However I'm not so sure this is worth a lot of effort right now.

**Comment by bradcray** [comment]
Closing this, as I never got back to it, and @dlongnecke-cray has fixed the issue in https://github.com/chapel-lang/chapel/pull/24560.

**Pull request closed without merging**
