### PR TITLE
Fix tcmalloc when compiled with clang 3.6 and used from C++

### PR DESCRIPTION
**Pull request by mppf**
tcmalloc.h uses struct mallinfo (it returns it from tc_mallinfo.
That gives an error like this:
.../include/gperftools/tcmalloc.h:101:38: error:
  'tc_mallinfo' has C-linkage specified, but returns incomplete type 'struct mallinfo' which could
        be incompatible with C [-Werror,-Wreturn-type-c-linkage]
          PERFTOOLS_DLL_DECL struct mallinfo tc_mallinfo(void) __THROW;
                                               ^
struct mallinfo is not a complete type because malloc.h is not included in the
user-facing tcmalloc.h. It looks like tcmalloc.h includes malloc.h but it doesn't
because it doesn't first include config.h - instead it relies on autoconf applied
to tcmalloc.h.in - and so the variables like HAVE_MALLOC_H are always undefined.

This patch solves the problem by creating autoconf variables for the user-facing
tcmalloc.h to use to include the header file defining struct mallinfo.

### CODE REVIEW

**Comment by mppf** [comment]
@gbtitus does this look better?

**Comment by gbtitus** [comment]
This looks okay, but needs to be pushed back to the gperftools folks. We'll need to talk to TMac, I think it is, to see if we need to do anything further legally speaking before we send them the changes.

**Comment by mppf** [comment]
Does it make sense to merge it into our repo first?

**Comment by gbtitus** [comment]
Oh, yes definitely. That'll let us make progress. But if we can push it upstream to them then it's one fewer thing we have to maintain, which is always good.

**Comment by mppf** [comment]
OK. So, to be clear, are you happy with me merging it to our repo any time, or do you need to look at it more, or ... ?

**Comment by gbtitus** [comment]
Yes, you can merge it.

**Pull request merged**
