### PR TITLE
Buffered index addition to sparse domains

### PR DESCRIPTION
**Pull request by e-kayrakli**
Adds buffered index addition capability to sparse domains

It looks like this:
```chapel
  var spsIndexBuffer = d.makeIndexBuffer();  // optionally pass `size`
  for i in indexGen() do
    spsIndexBuffer.add(i);  //there is no += in this PR
  spsIndexBuffer.commit(); //commit is also called by SparseIndexBuffer.deinit()
```

`makeIndexBuffer`: creates and returns a new index buffer, which is of record type `SparseIndexBuffer`
`SparseIndexBuffer.add(i)`: Adds the index to the buffer, committing the new indices back to the domain if it fills up
`SparseIndexBuffer.commit()`: Adds the last batch of indices (if any) to the domain.

Questions
----------

- Is this the right design for this approach?

  This is slightly different than what I proposed in #12672. I followed @mppf's suggestion to define a buffer object, which makes sense to me.

- What happens if the user doesn't call `commit` and the buffer object goes out of scope?

  I'll say that's a user error, and those indices are simply gone. Other approach is to commit them automatically in `deinit`. But I find it too implicit.

- Are we OK with the method names?

### CODE REVIEW

**Comment by e-kayrakli** [comment]
This is my initial take on the issue. @bradcray @mppf

**Comment by mppf** [comment]
> - Is this the right design for this approach?

At first I thought you'd just append everything to the buffer but this instead flushes once there are `size` elements. Is there a reason one or the other is better? Should it enable either?

> - What happens if the user doesn't call `commit` and the buffer object goes out of scope?
> 
>   I'll say that's a user error, and those indices are simply gone. Other approach is to commit them automatically in `deinit`. But I find it too implicit.

I think it should commit automatically on `deinit` unless that is impractical for some reason.

> - Are we OK with the method names?

I'm happy with `add` and `commit` methods on the index buffer. For `getIndexBuffer` maybe it should be `makeIndexBuffer` or something along those lines?

This strategy seems pretty generalizeable. What if you were doing index removal too? What about buffering up index addition + value to store in an array? Should it be called `makeUpdateBuffer` ?

**Comment by e-kayrakli** [comment]
@mppf 

> At first I thought you'd just append everything to the buffer but this instead flushes once there are size elements. Is there a reason one or the other is better? Should it enable either?

So, you mean an unbounded buffer? Two factors would be performance and memory. An unbounded buffer carries the risk of running OOM and doing extra copies for reallocations. Note also that to benefit from this buffering you shouldn't use a linked data structure. i.e. the indices that you eventually add to the sparse domain should ideally be in a single chunk in memory.

> I think it should commit automatically on deinit unless that is impractical for some reason.

Haven't tried, but I will. I am still leaning a bit towards just ignoring those indices,  but I can see your point in making `deinit` flush, as well. So, I'll implement that. 

> I'm happy with add and commit methods on the index buffer. For getIndexBuffer maybe it should be makeIndexBuffer or something along those lines?

Will do.

> This strategy seems pretty generalizeable. What if you were doing index removal too? What about buffering up index addition + value to store in an array? Should it be called makeUpdateBuffer ?

I see where this is going :) Interface-wise I would agree that the approach is generalizable. Implementation-wise I am not sure how generalizable it is, yet. I know you have done similar things in the past, so I want to believe :)

The "update buffer" in that scenario should implement the same interface (or subset where buffering is meaningful/allowed) as the sparse domain/array and any operation to be done on the domain/array must be done in the update buffer instead.

**Comment by ben-albrecht** [comment]
> Is this the right design for this approach?

I like this approach in general. It'd be nice to provide a reasonable default buffer size so users didn't have to worry about that (but could still tune for their use if necessary).

> Are we OK with the method names?

These names are fine with me. If there are other libraries with a similar interface, it would be interesting to see if there is a common naming schme used. I'd definitely have more confidence in our naming scheme knowing other libraries have similar method names.

**Comment by e-kayrakli** [comment]
I updated the PR message with the current design.

There are two things I need to think more about:
- Buffer size: I am moving more towards having an unbounded buffer if the argument is omitted. And clearly state it in the docs to avoid any OOM issues. If user knows more about the number of indices they are adding, then they can specify the size. This is more or less what Michael was suggesting, I believe.

- I'll look around for similar interfaces and see if we could do better in terms of method names.

**Comment by e-kayrakli** [comment]
About similar interfaces (or lack thereof):

Index addition seems to be a pretty unique case in Chapel because of first class domain objects. Couple of quick observations:
 
- scipy.sparse: you can create a sparse array directly from raw data. Apparently combined with the buffer protocol in python it can be an approach for [creating a sparse array incrementally](https://maciejkula.github.io/2015/02/22/incremental-construction-of-sparse-matrices/). However, once a sparse array is created you can "add" indices by directly assigning to an index. And there is no interface for buffering those operations

- boost has `insert_element` that does not offer any buffering in the [interface](https://www.boost.org/doc/libs/1_63_0/libs/numeric/ublas/doc/matrix_sparse.html)

- [pyspark.ml.linalg module](https://spark.apache.org/docs/2.2.0/api/python/pyspark.ml.html#module-pyspark.ml.linalg): doesn't look like it brings much on top of scipy.sparse

**Comment by e-kayrakli** [comment]
On an offline discussion with @mppf , I suggested that we should keep the buffer bounded and require the user to specify it. because of the following reasons: (1) If there is a default buffer size, then what should it be? (2) if we allow both bounded and unbounded, the interface design becomes complicated. (3) This currently helps the use cases I had in mind, and doesn't seem to be a priority beyond those.

So, I added a note to state that the interface and implementation may change in the doc. 

There is (has always been) some small changes in the existing interface in this PR and I merged some relevant PRs recently. I'll just run some paratests to make sure I am not breaking anything. Then, I believe this is ready to go in.

**Comment by e-kayrakli** [comment]
Full gasnet test came clean

**Comment by ben-albrecht** [comment]
> On an offline discussion with @mppf , I suggested that we should keep the buffer bounded and require the user to specify it. because of the following reasons: (1) If there is a default buffer size, then what should it be? (2) if we allow both bounded and unbounded, the interface design becomes complicated. (3) This currently helps the use cases I had in mind, and doesn't seem to be a priority beyond those.

I'm OK with the decision for this PR. However, I think it'd be useful to open an issue to discuss supporting a default buffer size and/or unbounded buffer in the future (assuming one doesn't already exist).

**Pull request merged**
