### PR TITLE
Convert `DimensionalDist2D` from a class to a record, `dimensionalDist2D`.

### PR DESCRIPTION
**Pull request by bradcray**
Converting the second-to-last distribution to a record.  This was more challenging than the others because:
* it's highly generic
* its code is structured very differently

Most tests seem to be working, though I had to dodge some things that didn't:

```chapel
  new dmap(new dimensionalDist2D(...))
```

didn't seem to work as in other cases...  Removing the 'new dmap()' did make it work though.  This is used so rarely in practice, I can't imagine a user hitting it in the field, so considered it acceptable, especially given how many caveats there already are with the distribution.

Doing an init copy of the record as in t1.chpl and t9.chpl also didn't work for reasons I didn't have the chance to look into.  I used a ref instead.

In addition, I couldn't get the per-dimension modules to link back to the record type, so just fell back to formatted text instead.  I'm not sure what was going on there.

### CODE REVIEW

**Comment by jabraham17** [comment]
> In addition, I couldn't get the per-dimension modules to link back to the record type, so just fell back to formatted text instead. I'm not sure what was going on there.

I suspect this is because the old links were actually linking to the module, not the class. Now that the module name and class name are different, this doesn't work. Making it `` :record:`~DimensionalDist2D.dimensionalDist2D` `` should work. I can submit an update for this

**Comment by bradcray** [comment]
Oh good thought, thanks for that insight, Jade!  I can take care of this, but thanks for the offer.

**Comment by bradcray** [comment]
@vasslitvinov : Would you have time to give this a post-merge review?

**Review by vasslitvinov — COMMENTED** [review]
Looks good to me. I am happy about the removals of `new dmap` from the tests.

**Pull request merged**
