### PR TITLE
added Aroon's benchmark directory

### PR DESCRIPTION
**Pull request by aroonsharma1**
Here I've committed my test directory that I used to test the work I did in #1077. It contains the Polybench parallel benchmarks that I translated to Chapel along with bash scripts I used to run different experiments.

### CODE REVIEW

**Comment by mppf** [comment]
Hi @aroonsharma1, I've updated these benchmarks to clean them up for inclusion in the Chapel repository. If you want to be the author of the merged pull request - please merge in the pull request I just sent you. Also, if you have time it would be great to get lu and trmm printing out that the computation was correct.

**Comment by mppf** [comment]
@aroonsharma1, I'm also going to need you to create a new PR request without committing the binaries. I removed them in my PR to you. I'd recommend you:
 * apply my PR
 * copy the new test directory somewhere else
 * checkout master
 * copy the test directory in and commit it
 * provide a new PR

Thanks.

**Comment by mppf** [comment]
@aroonsharma1, any news on cleaning up this PR?

**Comment by aroonsharma1** [comment]
Hi Michael,
Haven't looked at this yet. Work has been taking up most of my time. I will do my best to get to it this weekend. Aroon Sharma
University of Maryland, Class of 2014
M.S. Computer Engineering
(301) 908-9528 


     On Wednesday, June 17, 2015 5:55 AM, Michael Ferguson <notifications@github.com> wrote:
   

 @aroonsharma1, any news on cleaning up this PR?—

**Comment by aroonsharma1** [comment]
Hi Michael,

I would still like to merge this in, but I can't seem to find your changes on this pull request. Is there a button somewhere that I am missing that will take me to your cleaned up version of this pull request? If so, can you link that to me so I can check that out locally and then do the steps you suggested above?

**Comment by mppf** [comment]
https://github.com/aroonsharma1/chapel/pull/1

**Comment by aroonsharma1** [comment]
I've fixed the lu problem where it wasn't saying that the calculation was correct (see above commit). I wasn't seeing that same issue with trmm. Is there anything else I need to do? I couldn't seem to initiate a new pull request. Every time I tried doing so it just took me back to this current one. Maybe one repo can't have more than one pull request at a time

**Comment by mppf** [comment]
Hi Aroon, updating this branch is working fine. (You'd have to make a new branch to make a new pull request).

Could you please remove the .DS_Store from the patch?

Also, floyd-warshall is timing out f or me. Please make sure that

./util/start_test test/users/aroonsharma/

passes all tests. You can disable (e.g. with .notest) any tests you can't figure
out how to get working. Thanks!

**Comment by aroonsharma1** [comment]
Hi Michael, 
I submitted the new pull request. I added notests on the benchmarks that were timing out.  Aroon Sharma
University of Maryland, Class of 2014
M.S. Computer Engineering
(301) 908-9528 


     On Wednesday, June 24, 2015 3:29 PM, Michael Ferguson <notifications@github.com> wrote:
   

 Hi Aroon, updating this branch is working fine. (You'd have to make a new branch to make a new pull request).Could you please remove the .DS_Store from the patch?Also, floyd-warshall is timing out f or me. Please make sure that./util/start_test test/users/aroonsharma/passes all tests. You can disable (e.g. with .notest) any tests you can't figure
out how to get working. Thanks!—

**Comment by mppf** [comment]
@aroonsharma1, thanks, it looks good now. I'll merge it soon.

**Pull request merged**
