### PR TITLE
Update chapel version to 1.30

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
https://github.com/Cray/chapel-private/issues/4055

- [x]  Update version number of main branch

Signed-off-by: bhavanijayakumaran <82669529+bhavanijayakumaran@users.noreply.github.com>

### CODE REVIEW

**Comment by bhavanijayakumaran** [comment]
For reference 1.29.0 pre-release are removed in this PR.

https://github.com/chapel-lang/chapel/pull/21162

**Comment by mppf** [comment]
I believe this also needs to undo PR #21187 (or else there will be failures for `test/chpldoc/compflags/combinations`)

**Comment by bhavanijayakumaran** [comment]
> I believe this also needs to undo PR #21187 (or else there will be failures for `test/chpldoc/compflags/combinations`)

Done!

**Review by mppf — APPROVED** [review]
It looks good to me but it'd be a good idea to do a test run on it to uncover any cases we missed.

**Comment by bhavanijayakumaran** [comment]
Will merge this after merging the fix for mac build.

**Pull request merged**
