### PR TITLE
Update LLVM docs

### PR DESCRIPTION
**Pull request by mppf**
Document new CHPL_LLVM settings added in PR #4822.
Adjust comments in third-party/llvm Makefile and shell script.

Reviewed by @ben-albrecht - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
Question for my reviewer: We don't currently make use of CHPL_LLVM settings llvm-minimal or system-minimal. It seems we should document them anyway, if the chplenv.rst is to be the reference for what values are allowed. Should we note that they aren't currently meaningful? Not document them? Document them in an RST comment? Something else?

**Comment by ben-albrecht** [comment]
>Question for my reviewer: We don't currently make use of CHPL_LLVM settings llvm-minimal or system-minimal. It seems we should document them anyway, if the chplenv.rst is to be the reference for what values are allowed. Should we note that they aren't currently meaningful? Not document them? Document them in an RST comment? Something else?

My stance is that we should not document them in the user-facing documentation. I'm OK with keeping them in an rst comment, if we intend to add them in the near future. I prefer to only advertise the currently implemented features in the online documentation.

**Comment by ben-albrecht** [comment]
Other than that, looks good.

**Comment by mppf** [comment]
@ben-albrecht - they are implemented, it's just that we currently have no reason to use llvm-minimal or system-minimal.

**Comment by ben-albrecht** [comment]
Correction -- I misunderstood the behavior of `llvm-minimal` and `system-minimal`. I still think a feature intended for developers shouldn't be in the user-facing documentation. I'd keep it commented out for now, to avoid confusion. We can add it back in if it becomes a user-facing feature.

**Pull request merged**
