### PR TITLE
Split general git tips out of ContributorInfo.rst

### PR DESCRIPTION
**Pull request by bradcray**
I've recently been finding the ContributorInfo file to be so large and
monolithic that it's hard to get my head around what it contains.  I'm
increasingly inclined to break general information out into its own
files such that the file focuses primarily on things specific to the
Chapel workflow.  In this PR, I'm putting the general information
about using 'git' out into its own file which reduces the main file by 40%.

### CODE REVIEW

**Comment by bradcray** [comment]
@ben-albrecht: This is a follow-up from our discussion the other week, if you agree.

**Review by ben-albrecht — APPROVED** [review]

**Comment by bradcray** [comment]
@lydia-duncan and @mppf — Doing a quick check of this file's history before merging, I'm seeing that this effectively reverses a change you made in #6671 four years ago, so didn't want to merge without checking with you.  From my perspective, the ContributorInfo.rst file has become way too big and monolithic (in the "I can barely get my head around everything that it contains" sense) and tries to say everything about everything which feels like too broad of a scope to me.  Specifically, I feel as though general information that isn't particularly unique to our workflow (like "here's how to check out a git repository" or "here's how to sign commits" style information) should be broken into its own files in order to (a) keep the file from being so large and trying to do everything and (b) permit people to skip over large sections of text if they already know how to use git / sign DCOs / whatever (this may also simplify pointing people to such information by pointing to a general file, though if/when we start rendering the developer docs online, this is less of a benefit).

@ben-albrecht and I are proponents of this approach (and I've already taken it with the DCO information).  Would you object to it?

**Comment by lydia-duncan** [comment]
I don't feel strongly.  If my memory serves, we merged the two because there were near constant references in the Contributor doc to the Git Tips doc, or that it was too much of a mix, or something along those lines.

Lydia of today likes the notion of keeping things more sorted by topic.

**Comment by mppf** [comment]
Do links between the documents work now? (It might have been that they did not, before). I haven't looked at ContributorInfo lately and don't object to changes that others feel are improvements.

**Comment by bradcray** [comment]
> Do links between the documents work now? 

It depends on how the links are rendered.  Sphinx/chpldoc-style links don't do anything because we're not running these .rst docs through the same process as other online docs (issue #5326).  Traditional rst-style links implemented as URLs do work (where I think the current best practice for these developer-oriented docs is to point to their rendered form on GitHub (?)).

And your question makes me realize that I think I have a few broken links in the current PR, but need to double-check...  maybe they're just broken until I hit merge...

**Comment by mppf** [comment]
Hmm, I'm seeing some broken links on e.g. https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst#create-new-branch for "New branch command". Not sure if it is too hard to fix these or not.

**Comment by bradcray** [comment]
Thanks for pointing that out.  I'd reviewed and fixed some, but didn't realize there were other cross-references.  I'll take a closer look.

**Comment by bradcray** [comment]
Fixed in #16870 (which I don't think really requires a review, though you're welcome to take a look).  Thanks again for pointing this out, Michael!

**Pull request merged**
