### PR TITLE
Revert "Merge pull request #15001 from ronawho/ra-local-access"

### PR DESCRIPTION
**Pull request by e-kayrakli**
#15001 caused some commcount changes. While trying to fix it I tried to add --fast.

But while testing I couldn't get a clean run on XC with this test. This PR reverts the change for the weekend.

### CODE REVIEW

**Comment by bradcray** [comment]
What happened on XC?

**Comment by bradcray** [comment]
(it seems like it would be OK to let it continue failing as well since repeated failures won't generate new mails).

**Comment by e-kayrakli** [comment]
Result validation seems to be failing as well. I'm OK with letting it fail, too. I can leave the PR open in case someone gets annoyed by the failure.

**Comment by bradcray** [comment]
Are you saying that @ronawho gets his performance improvements by making the code no longer work?  :D  

I think a consistent failure in a small number of configs for a few days is reasonable if it doesn't cause noise (and consistent failures rarely do).  The more annoying thing is when a test phases back and forth between passing and failing, causing mail each time.  Seems like this should be relatively well-behaved by that standard (?).

**Comment by e-kayrakli** [comment]
Then, I am leaving the PR open. I'll check in a few times over the weekend to see if there's a lot of noise.

**Comment by ronawho** [comment]
Based on 8d68e2cdc001c5f17b4a3e331dc6268547195f7e and 36c521bfab1be7e87d37b81adb62ff52b51eab0f, I think this version of RA has probably been failing verification for a long time on XC. RA defaults to RMO (GETs/PUTs) under ugni, which is more likely to have conflicting updates than the on-stmt version just because there's a longer time period between when a value is read and it's xor'd valued is stored. 

https://github.com/chapel-lang/chapel/pull/15037 should fix this and updates comm counts.

**Pull request closed without merging**
