### PR TITLE
Adjust Python scripts in Path module tests to use print() for compatibility 

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
Earlier today, @ben-albrecht pointed out that some of the .preexec scripts I introduced for tests covering the Path module fail when executed with Python3. 

He suggested `from __futures__ import print_function`, so I've gone ahead and substituted Python2 style print expressions with calls to print() within these scripts.

Testing:
- `ALL` on `linux64` when `CHPL_LLVM=llvm` and `CHPL_COMM=none`

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Thanks @dlongnecke-cray! Were you able to confirm `start_test  test/library/standard/Path/` works for python2 and python3?

**Comment by dlongnecke-cray** [comment]
I did test this locally, and they pass with either python2/python3. Do you know a faster way of overriding #!/usr/bin/env @ben-albrecht?

**Comment by ben-albrecht** [comment]
Cool, just making sure. I use pyenv to switch local python versions.

**Comment by dlongnecke-cray** [comment]
Thanks. I'll get in the habit of using that from now on when I have to write any python.

**Pull request merged**
