### PR TITLE
Fix cast operator methods; add tests of cast 'cleanup.cpp' error messages

### LINKED ISSUE #17325: Cast operator methods get confusing error about number of formals
### Summary of Problem

Attempting to make use of the new cast operator support in combination with the new operator method capability, I wrote the following program:

```chapel
record R {
  var x: sync int;

  proc init=(x: int) {
    this.x = x;
  }

  operator :(x: int, type t: R) {
    return new R(x);
  }
}

var myR: R = 3;
```

which generates the following error message:

```bash
testit.chpl:8: error: cast function should have two formals
```

which is confusing since it does have two formals.  Moving the cast operator to a standalone operator (rather than a method) solves the problem, but prevents the cast from being associated with a type.

### Steps to Reproduce

**Associated Future Test(s):**

TODO

### Configuration Information

- Output of `chpl --version`: `chpl version 1.24.0 pre-release (ce03a6ea8a)`

### PR DESCRIPTION
**Pull request by bradcray**
Presumably due to the user-facing ':' operator and the 'operator'
keyword being developed simultaneously, 'operator :' in method form
hasn't worked because the check that it's a binary operator didn't
take the extra method arguments into consideration.  This led to the
confusing error in which a legal cast operator method would cause the
compiler to complain that it didn't have two arguments, when it
clearly did.

This PR fixes that by making the cast checks in cleanup.cpp cognizant
of whether the function is a method or not.  It also adds some tests
to (a) lock in these error messages (which didn't seem to be tested
previously?) and (b) lock in case showing that a cast operator method
works.

Resolves #17325.

### CODE REVIEW

**Comment by bradcray** [comment]
@mppf / @lydia-duncan : Would one of you review?

**Review by mppf — APPROVED** [review]
Looks good. I think it's likely that there are related problems in other places but I will create issues for them if I am able to identify them.

**Comment by lydia-duncan** [comment]
Awesome, glad it was as simple as we were hoping!

**Comment by bradcray** [comment]
> I think it's likely that there are related problems in other places

Other places in the implementation of cast, or other similar issues for other operators?

**Comment by mppf** [comment]
Mainly, similar issues for other operators. I think we should grep for astrScolon and astrSassign in the compiler as well as "=" and ":" to see if they are handled.

**Comment by bradcray** [comment]
I haven't looked through existing tests, but had assumed (based on Lydia's typical M.O.) that there was probably coverage for trying every operator as a method and that this one slipped through the cracks since it was being developed simultaneously.  Lydia, can you comment?  (i.e., is it likely that we don't have a method-based definition for each operator.

@mppf: W.r.t. the `:` case: Given that we have a case that works (admittedly, a simple one), what differences do you anticipate there would need to be to create a non-working case?

**Comment by mppf** [comment]
@bradcray - I haven't found a non-working case and I don't have a plan for one. I was worried about split-init and the way it checks for `=` but that seemed to be OK with a quick check. I think somebody should poke around in the compiler sources though.

**Comment by lydia-duncan** [comment]
> I haven't looked through existing tests, but had assumed (based on Lydia's typical M.O.) that there was probably coverage for trying every operator as a method and that this one slipped through the cracks since it was being developed simultaneously. Lydia, can you comment? (i.e., is it likely that we don't have a method-based definition for each operator.

I did mention earlier that I didn't have a test for every operator as a method in a message to you, but that it was on my todo list - I was going through cases exposed by the branch that updates the standard/internal/package modules and was planning on handling it after those were resolved.  `!=` and `==` had required an additional compiler update due to special casing when handling type arguments, but I hadn't seen any problems for an operator's "normal" behavior in those updates.  But again, I don't have full coverage yet.

**Comment by bradcray** [comment]
OK, I'd forgotten that, thanks.

**Pull request merged**
