### PR TITLE
Fix denormalize bug on handling PRIM_UNARY_NOT

### PR DESCRIPTION
**Pull request by e-kayrakli**
Fixes a minor bug in denormalize that was causing different behaviour
w/o --no-denormalize.

Following snippet used to print out 32 with `--denormalize` and 8 with
`--no-denormalize`:

```
var i = 0:uint(8);
writeln(popcount(~i));
```

This issue is caused by integer promotion for "smaller" ints. Here i is
expanded to 32 bits, negated and popcount'ed. Without casting the
variable or assigning it to a uint(8) there is nothing truncating
the leading junk bits.

Similarly
```
uint8_t i = 0;
printf("%d\n", __builtin_popcount(~i));
```
Also prints out 32.

Similar issue also occurs with arithmetic and shift operations, and
denormalize already handles those. This PR adds PRIM_UNARY_NOT to
the list of primitives that needs a typecast when they are moved.

For reference this is the note from the initial denormalize PR #4222:
> We now generate typecasts for all integer operations. This is due to C
> promoting small integers to full ints in arithmetic operations. When
> such integers are in arithmetic operations and moved to somewhere
> other than a variable assignment to a corresponding type, we have to
> make sure they are typecast(and truncated)
> 
> Currently there is no easy way of getting c_int size for target
> architecture in the compiler. Therefore casts are not limited to small
> ints.

Tests -- all in standard linux64:
- [x] test/users/engin/bitwiseDenorm.chpl
- [x] test/release/hello*chpl
- [x] full correctness

### CODE REVIEW

**Comment by benharsh** [comment]
Are you running the full correctness suite yourself?

**Comment by e-kayrakli** [comment]
Ah, no I can't do that. Sorry for not being clear.

**Comment by benharsh** [comment]
No problem, I'll fire off a paratest.

**Comment by benharsh** [comment]
Testing came back clean. OK if I merge?

**Comment by e-kayrakli** [comment]
Sure. Thanks!

**Pull request merged**
