### PR TITLE
Improve error messages for variable declarations over incomplete generics

### PR DESCRIPTION
**Pull request by bradcray**
This patch fixes a bug reported by @oflocon in which a declaration over a generic type (specifically 'integral') resulted in an internal error rather than a useful user-facing error message.  Here, I also catch the case of a declaration over a generic class that is not instantiated completely, improving upon the error message that we generated previously, I believe.

To avoid duplicating work already done for generics in type/function resolution, my approach is to speculatively create a 0-argument call to the type's defaultTypeConstructor as we're setting up the variable's default value, plug it into the AST, try to resolve it, and then remove it to set things back the way they were.  If it failed to resolve (as in the case of a generic class name where its param and type fields had not been specified), or if it didn't have a defaultTypeConstructor, then we print out an error message (specialized for those two cases).

I added a few new tests of this, with and without initialization expressions (in case those code paths diverge in the future, as I think we expect them to), and also renamed @oflocon 's directory to be lowercase and better match its siblings as a result (note that this results in more of a diff than there really is on GitHub).  Late in the game, I also found a test that was essentially identical to one of the ones I had written, in one of the infamous deitz/part7 directories, so I removed it in favor of my test in a shallower, better-named directory.

### CODE REVIEW

**Comment by ronawho** [comment]
Looks good to me, but it probably wouldn't hurt to get a review from somebody who has been working in function resolution a lot lately. Maybe one of the mikes?

**Comment by bradcray** [comment]
Agreed.  This is right amidst some of @lydia-duncan's code as well.

**Comment by bradcray** [comment]
(back-pedaling...)  Not that I don't trust you!!

**Comment by ronawho** [comment]
;)

**Pull request merged**
