### PR TITLE
Remove obsolete hugepage module warning.

### PR DESCRIPTION
**Pull request by gbtitus**
GASNet seems no longer to have problems if a craype-hugepages module is
loaded when it is being built or programs using it are being linked.
Remove the warning about this.

### CODE REVIEW

**Comment by gbtitus** [comment]
@ronawho , does this look okay?

**Comment by ronawho** [comment]
The patch itself looks fine to me, but the "seems" worries me a little bit. I don't remember anything in recent GASNet change logs alluding to this. Is this worth checking with the gasnet team, or are you pretty sure we don't need it anymore?

**Comment by gbtitus** [comment]
I thought we'd had an email conversation about this with them, but when I looked for that what I found was one that was about hugepages but not this problem as such.  So then I went hunting in the GASNet git repo.

I think it's this commit that solved the problem:
  https://bitbucket.org/berkeleylab/gasnet/commits/3f1d415299b01c7b076214dc17015b3cc1c5cabd

The Cray hugepage module forces `--whole-archive -lhugetlbfs`. The problem was caused by the fact that prior to the above commit GASNet did the same. (Recall that the symptom was a bunch of 'multiply defined' errors.) But with the above commit we only have one `--whole-archive -lhugetlbfs`, and we don't get the multiple definition errors.

(Actually we now end up with _only_ the `--whole-archive -lhugetlbfs` in the linker command line, and the explicit `-lhugetlbfs` that GASNet throws seems not to be there. I don't know how that gets removed, but I think we can proceed without knowing that.)

**Comment by ronawho** [comment]
Sorry, I forgot to follow up on this (hope you weren't waiting on me!). That explanation makes sense to me. Put some of that info in the PR message, and I think you're good to go

**Pull request merged**
