### PR TITLE
Adding future #17085

### PR DESCRIPTION
**Pull request by rchinmay**
Added future tests for recursive iterators, from the issue #17085.

### CODE REVIEW

**Comment by bradcray** [comment]
@rchinmay : I just happened to notice these today for the first time.  As a general tip, we don't always notice when someone opens a PR (it's not one of the events we track as closely as issues or SO questions), so it's a good idea to ping a specific developer on the PR if there's someone who's been engaging with you on the topic; or to ask for a reviewer on Gitter or Discourse (in the developer category).

This generally looks good to me, and behaves as I'd expect.  One thing you could do to make it slightly stronger would be to add a `.bad` file to the write-recursive-iter.chpl case capturing the current behavior of the test.  This is beneficial in our test system because it will make us aware if the behavior of the test changes yet does not match the .good file (which could indicate that it's closer to working than it had been).  Let me know if you're interested in doing that (it'd be nice to have a .bad file for the other case as well, of course but this would be challenging since the output generated is likely to differ with every C compiler, so I don't think it's tractable).

**Comment by rchinmay** [comment]
@bradcray, Sorry I had forgotten to ping you in this PR. I thought that the new PRs were not being reviewed due to feature freeze for the new chapel version, and would be done after its release. So, I waiting for that. Anyways, it was my mistake not to tag anyone.
> add a .bad file to the write-recursive-iter.chpl case capturing the current behavior of the test.

Here, executable file is not generated due to internal error or compilation error on compiling the source code. So, I am not sure what the ``.bad`` file should contain for these tests. Should the error generated be present in the ``.bad`` file, since chapel 1.23.0 version gives internal error on the first program (with ``writeln()`` statement) and compilation error on the 2nd program (with ``break`` statement). The errors generated are:
```
internal error: UTI-MIS-0788 chpl version 1.23.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```
and 
```
In file included from /tmp/chpl-rchinmay-11567.deleteme/_main.c:54:
/tmp/chpl-rchinmay-11567.deleteme/Chapel_program.c: In function ‘_rec_iter_loop_chpl__init_Chapel_program_chpl’:
/tmp/chpl-rchinmay-11567.deleteme/Chapel_program.c:217:1: error: label ‘_breakLabel’ used but not defined
  217 | goto _breakLabel;
      | ^~~~
make: *** [/home/rchinmay/Documents/Second_PR/chapel/runtime/etc/Makefile.exe:29: /tmp/chpl-rchinmay-11567.deleteme/Chapel_program.tmp] Error 1
error: compiling generated source
```
respectively for the 1st and 2nd programs.
Also, ``start_test`` on 2nd program gives:
```
[Starting Chapel regression tests - 210304.235729]
[git branch: 'Adding-future-#17085' (0d545be0ec)]
[starting directory: "/home/rchinmay/Documents/Second_PR/chapel"]
[Logs directory: "/home/rchinmay/Documents/Second_PR/chapel/test/Logs"]
[log_file: "/home/rchinmay/Documents/Second_PR/chapel/test/Logs/rchinmay.linux64.log"]
[CHPL_HOME: /home/rchinmay/Documents/Second_PR/chapel]
[host platform: linux64]
[target platform: linux64]
[valgrind: OFF]
[performance tests: OFF]
[compiler performance tests: OFF]
[number of trials: 1]
[performance graph generation: OFF]
[compiler: "/home/rchinmay/Documents/Second_PR/chapel/bin/linux64-x86_64/chpl"]
[compopts: "--cc-warnings"]
[execopts: ""]
[launchcmd: ""]
[comm: "none"]
[networkAtomics: "none"]
[localeModel: "flat"]
[numlocales: "(default)"]
[max_locales: "(default)"]
[tests: "/home/rchinmay/Documents/Second_PR/chapel/Chapel_program.chpl"]
[directories: ""]

### Chapel Environment ###
machine info: Linux rchinmay-VivoBook-ASUSLaptop-X430FA-S430FA 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64
CHPL_HOME: /home/rchinmay/Documents/Second_PR/chapel *
script location: /home/rchinmay/Documents/Second_PR/chapel/util/chplenv
CHPL_HOST_PLATFORM: linux64
CHPL_HOST_COMPILER: gnu
CHPL_HOST_ARCH: x86_64
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat *
CHPL_COMM: none *
  CHPL_COMM_SUBSTRATE: none
  CHPL_GASNET_SEGMENT: none *
  CHPL_LIBFABRIC: none
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none *
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
CHPL_LIB_PIC: none
CHPL_SANITIZE: none
CHPL_SANITIZE_EXE: none
##########################

[Cleaning file /home/rchinmay/Documents/Second_PR/chapel/Chapel_program.chpl]
[Starting /home/rchinmay/Documents/Second_PR/chapel/util/test/sub_clean Chapel_program.chpl Thu Mar 04 23:57:29 IST 2021]
[Starting sub_clean - Thu Mar 04 23:57:29 IST 2021]
[pwd: /home/rchinmay/Documents/Second_PR/chapel]
Cleaning test: Chapel_program

[Working on file Chapel_program.chpl]
[Starting /home/rchinmay/Documents/Second_PR/chapel/util/test/sub_test Thu Mar 04 23:57:29 IST 2021]
[Starting subtest - Thu Mar 04 23:57:29 IST 2021]
[test: /home/rchinmay/Documents/Second_PR/chapel/Chapel_program.chpl]
[Executing compiler /home/rchinmay/Documents/Second_PR/chapel/bin/linux64-x86_64/chpl -o Chapel_program --cc-warnings Chapel_program.chpl < /dev/null]
[Elapsed compilation time for "/home/rchinmay/Documents/Second_PR/chapel/Chapel_program" - 5.627 seconds]
[Error compilation failed for /home/rchinmay/Documents/Second_PR/chapel/Chapel_program]
[Compiler output was as follows:]
In file included from /tmp/chpl-rchinmay-12783.deleteme/_main.c:54:
/tmp/chpl-rchinmay-12783.deleteme/Chapel_program.c: In function ‘_rec_iter_loop_chpl__init_Chapel_program_chpl’:
/tmp/chpl-rchinmay-12783.deleteme/Chapel_program.c:217:1: error: label ‘_breakLabel’ used but not defined
  217 | goto _breakLabel;
      | ^~~~
make: *** [/home/rchinmay/Documents/Second_PR/chapel/runtime/etc/Makefile.exe:29: /tmp/chpl-rchinmay-12783.deleteme/Chapel_program.tmp] Error 1
error: compiling generated source
[Elapsed time to compile and execute all versions of "/home/rchinmay/Documents/Second_PR/chapel/Chapel_program" - 5.628 seconds]
[Finished subtest "/home/rchinmay/Documents/Second_PR/chapel/Chapel_program" - 6.056 seconds]

[Done with tests - 210304.235735]
[Log file: /home/rchinmay/Documents/Second_PR/chapel/test/Logs/rchinmay.linux64.log ]

[Test Summary - 210304.235735]
[Error compilation failed for /home/rchinmay/Documents/Second_PR/chapel/Chapel_program]
[Summary: #Successes = 0 | #Failures = 1 | #Futures = 0 | #Warnings = 0 ]
[Summary: #Passing Suppressions = 0 | #Passing Futures = 0 ]
[END]
```
and the ``comp.out.tmp`` file contains:
```
In file included from /tmp/chpl-rchinmay-12783.deleteme/_main.c:54:
/tmp/chpl-rchinmay-12783.deleteme/Chapel_program.c: In function ‘_rec_iter_loop_chpl__init_Chapel_program_chpl’:
/tmp/chpl-rchinmay-12783.deleteme/Chapel_program.c:217:1: error: label ‘_breakLabel’ used but not defined
  217 | goto _breakLabel;
      | ^~~~
make: *** [/home/rchinmay/Documents/Second_PR/chapel/runtime/etc/Makefile.exe:29: /tmp/chpl-rchinmay-12783.deleteme/Chapel_program.tmp] Error 1
error: compiling generated source
```
So, should the ``.bad`` file contain these error generated on compilation. As I studied from the documentation, it usually contains the output on execution of these tests. Since they do not produce executable file, I had not added ``.bad`` file for these tests. Could you please clarify what you were expecting in the ``.bad`` files here, as I do not know if I understood it correctly?

**Comment by bradcray** [comment]
Hi @rchinmay —

Thanks for being sensitive to the release timeframe.  It's definitely the case that we aren't as responsive during this period, but since I was looking through PRs to see where we were w.r.t. the release, I came across this and wanted to make sure you weren't waiting for a response that might not come on its own.  Since the test system isn't involved in the release, we're open to merging such PRs even though they won't affect the release (but may also wait, depending on how busy things get).

For any test run by `start_test`, the output of the compiler + the execution of the resulting binary are compared against the `.good` and `.bad` files.  If the compilation generates an error, only the compiler output is compared.  So if you were to take the `comp.out.tmp` files from either of these failed compilations, they would make a suitable `.bad` file since they'd indicate what is generated by the compiler today (and should result in a "clean" run of these tests in your local repository).

The idea behind the `.bad` files is to generate an event in our testing system if the output of the test changes from what it was before, yet still does not match the `.good` file so that someone can go in to see whether it is working better, or perhaps if the `.good` file was simply misformatted.  Without a `.bad` file, sometimes future tests do start working as they should, but aren't noticed (if the `.good` file wasn't quite right in some regard).

The case with the `goto` label error is the one I was saying *not* to create a `.bad` file for, because the error is being generated by the back-end C compiler that Chapel invokes, and (as you can imagine) each back-end C compiler may complain about that issue in a different way, such that my output with icc, clang, etc. may not match your output with `gcc` and would therefore report a testing failure ("this future file isn't matching its `.bad` output anymore!").  So this is a case that we can't really do anything about easily.

It may seem as though the other case would also be bad to capture in a `.bad` file, but for internal errors of that form, we have some scripting in the test system that filter such cases to make them independent of compiler version number (and, to an extent, the type of internal error).  If you run `cat `git grep -l "Internal errors indicate a bug"`` from within `$CHPL_HOME/test` you will probably see many `.bad` files of this form as examples.  If you run `start_test test/path/to/test.chpl` for such a test, you should see it listed as a future that is not passing, but is also not mis-matched against its `.bad` file.  If you were throw some extra text into its `.bad` file and re-run the test, you should see a failure indicating that the output didn't match the `.bad`.

Hope this provides a bit more context about our test system for cases like this.

**Comment by bradcray** [comment]
@rchinmay : I came back across this one today, which I'd forgotten about.  I think all it needs is for a .bad file to be added for the one test case that will support one portably.  Let me know if you'll have a chance to do this soon.  Otherwise, I'll merge it and add it myself after the fact.

**Comment by rchinmay** [comment]
@bradcray, I have added the ``.bad`` files. Please review.
Thanks,
R.Chinmay

**Comment by bradcray** [comment]
Hi @rchinmay — Sorry, I think I'm still not being clear about the `.bad` files.  When I check out this branch and run:

```
start_test test/functions/iterators/recursive/break-iterating-recursive-iterator.chpl test/functions/iterators/recursive/write-recuresive-iter.chpl 
```

I get 2 failures because the `.tmp` output of compiling and running the test doesn't match against the `.bad` file (and believe you should be able to see the same thing if you run the command above—the expected summary would be:

```
[Summary: #Successes = 0 | #Failures = 0 | #Futures = 2 | #Warnings = 0 ]
```

where instead we're getting:

```
[Summary: #Successes = 0 | #Failures = 2 | #Futures = 2 | #Warnings = 0 ]
```

For `write-recuresive-iter.bad`, I believe this is because you've (manually) added the line:

```
< internal error: seg fault [util/misc.cpp:889] (with ``--devel`` flag)
```

but these `.bad` files need to be diff-able by scripts, they're not just descriptive for humans.  Does that make sense?

I'm also just now noticing the spelling error in `recuresive`.  Not a showstopper, but worth fixing if we're still making changes.

**Comment by rchinmay** [comment]
@bradcray, I had a doubt while adding the `break-iterating-recursive-iterator.chpl`. The output from the compilation produced an internal error, whereas the ``start_test`` gives compilation error stating that ``error: label ‘_breakLabel’ used but not defined``. Since they produce different errors, which one of them should be placed in the ``.bad`` file? I had placed both of them in the ``.bad`` file, but it since start_test is used to compare (``diff``) the files, I think using only the output from the start_test would be better. But, its output is environment-dependent. Like, it uses ``rchinmay`` in many of its file's path names. Running it on different device or by different user may provide different results, and hence cause the ``start_test`` to fail, since it may not match the output of ``.comp.out.tmp`` with the ``.bad`` file present. So, is there a better way of adding the ``.bad`` file here?
Thanks,
R. Chinmay

**Comment by bradcray** [comment]
> The output from the compilation produced an internal error, whereas the start_test gives compilation error stating that error: label ‘_breakLabel’ used but not defined.

I don't understand why it would give this different behavior based on whether it was run in start_test or not.  I don't have your copy of the branch available at the moment, but I thought when I tested within start_test, I got the internal error as well (which surprised me because I was expecting the back-end C compiler error you'd mentioned).  In any case, you're correct that the .bad must match the start_test output behavior.  If start_test is still generating the C compiler error for you, then I think we need to just not have a .bad for this test case, which is what I was trying to explain here:

> it'd be nice to have a .bad file for the other case as well, of course but this would be challenging since the output generated is likely to differ with every C compiler, so I don't think it's tractable

and here:

> The case with the goto label error is the one I was saying not to create a .bad file for, because the error is being generated by the back-end C compiler that Chapel invokes, and (as you can imagine) each back-end C compiler may complain about that issue in a different way, such that my output with icc, clang, etc. may not match your output with gcc and would therefore report a testing failure ("this future file isn't matching its .bad output anymore!"). So this is a case that we can't really do anything about easily.

If it were just the matter of the path, we could add a .prediff script for the test that would do a sed match against the path and replace it with a new string that would be used in the .good file, but again, I think the bigger problem is that the format of that error message is likely to change depending on which back-end C compiler is used, so it would be difficult to make portable.

OTOH, if it always generates an internal error now (e.g., has something changed about the test or the compiler over time which would explain this change in behavior?) then we could put that internal error in the .bad file.

**Comment by rchinmay** [comment]
@bradcray, I am currently using chapel version 1.24.0 (pre-release). I will try this again with chapel version 1.24.0. I did not expect start_test to produce different compilation error compared to internal error generated upon compilation. However, I verify it with the latest version, and update.
> spelling error in `recuresive`.
I did not notice that. Sorry. I will correct it along with the next commit.
Thanks,
R. Chinmay

**Comment by bradcray** [comment]
> I did not expect start_test to produce different compilation error compared to internal error generated upon compilation.

I wouldn't either...

**Comment by rchinmay** [comment]
@bradcray I tested it with chapel version 1.24.0, and the surprising thing was that the outputs from both ``start_test`` and ``chpl`` command compilation produces either internal error or the error given below independently. Without changing anything in the test or compilation flags, I ran the test multiple times, and found that sometimes internal error(given below) is generated, and in other times the compilation error (given below) is generated. 
Internal error generated:
```
internal error: UTI-MIS-0894 chpl version 1.24.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

Compilation error generated:
```
In file included from /tmp/chpl-rchinmay-25112.deleteme/_main.c:54:
/tmp/chpl-rchinmay-25112.deleteme/break-iterating-recursive-iterator.c: In function ‘_rec_iter_loop_chpl__init_break_HYPHEN_iterating_HYPHEN_recursive_HYPHEN_iterator_chpl’:
/tmp/chpl-rchinmay-25112.deleteme/break-iterating-recursive-iterator.c:217:1: error: label ‘_breakLabel’ used but not defined
  217 | goto _breakLabel;
      | ^~~~
make: *** [/home/rchinmay/Downloads/chapel-1.24.0/runtime/etc/Makefile.exe:29: /tmp/chpl-rchinmay-25112.deleteme/break-iterating-recursive-iterator.tmp] Error 1
error: compiling generated source
```
I could not decide how the output on compilation or ``start_test`` changed without changing any other parameters involved. I think the outputs were independent, and I really could not find a reason for such changes in errors. Running the same command on the same test file, either compiling with ``chpl`` or ``start_test``, produced different errors without changing any parameters involved. Please guide me on why this is happening, and how to deal with such differences in the ``.bad`` file.
Thanks,
R. Chinmay

**Comment by bradcray** [comment]
Ah, OK.  So there must be something nondeterministic happening in the compiler then?  In that case, I don't think we can add the .bad file since the output will be unpredictable.  Let me see if I can reproduce this nondeterminism before we make a final call, though (the last time I tried this, I just did a single run,  so wouldn't have seen both output forms).

**Comment by bradcray** [comment]
OK, yes, I also see the nondeterministic behavior, so let's not file the .bad for `break-iterating-recursive-iterator.chpl` on the basis of (a) the nondeterminism and (b) the sensitivity to the back-end C compiler's output in one of its forms.

Hmm, and now that I re-run `write-recuresive-iter.chpl`, I'm seeing nondeterministic behavior there as well, so I think it can't have a .bad file either.

Sorry to have led you down the wrong path... it's very rare that we see this sort of nondeterminism, so it didn't occur to me that it would be a problem in this case.  On the plus side, at least you're now an expert in the role of `.bad` files?

So, I think removing the .bad files is the only thing required to merge (and, if you want, to fix the spelling of recuresive in the files).

**Comment by rchinmay** [comment]
@bradcray I have removed the ``.bad`` files and also updated ``.future`` files. Please review.
Thanks,
R. Chinmay

**Comment by bradcray** [comment]
@rchinmay: Thanks for sticking with this, and sorry again for the wasted time on trying to get .bad files working for what turned out to be nondeterministic behavior.

**Pull request merged**
