### PR TITLE
Bugfix: Set line number for resolveEnumTypes()

### PR DESCRIPTION
**Pull request by ben-albrecht**
## Bug fix
During function resolution, the `resolveEnumTypes()` call does not set a line number. This resulted in a  internal error compilation failure with no line number for minimal programs that use the LAPACK module. This PR sets the line number based on the enum type, `et`, since no expression is available within `resolveEnumTypes`. This bug fix is contained in the [first commit](https://github.com/chapel-lang/chapel/commit/f41699d858ff7de5cdf8842044e89066f382c5e6)

## New test
 Added a new test cast for this bug in `types/enum`

## Testing
* Tested on OS X
* Tested on an XC40 (where we do LAPACK testing)
* Full test suite completed: `[Summary: #Successes = 6457 | #Failures = 0 | #Futures = 0]`

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Full test suite completed: `[Summary: #Successes = 6457 | #Failures = 0 | #Futures = 0]`

**Comment by ben-albrecht** [comment]
Full test suite completed: `[Summary: #Successes = 6457 | #Failures = 0 | #Futures = 0]`

**Comment by ben-albrecht** [comment]
Full test suite completed: `[Summary: #Successes = 6457 | #Failures = 0 | #Futures = 0]`

**Comment by daviditen** [comment]
I think it would be nice to make the new test independent of LAPACK so that it can run on any configuration, doesn't need special COMPOPTS or SKIPIFs, and is more immediately obvious what the problem is.

The problem appears to be with param-folding the initializers in an enum, so a test containing only ``enum myenum { a=1:c_int, b=2:c_int, c=3:c_int }`` hits the same problem.

Otherwise this looks good.

**Comment by ben-albrecht** [comment]
Full test suite completed: `[Summary: #Successes = 6457 | #Failures = 0 | #Futures = 0]`

**Comment by ben-albrecht** [comment]
Full test suite completed: `[Summary: #Successes = 6457 | #Failures = 0 | #Futures = 0]`

**Comment by ben-albrecht** [comment]
Good idea - I'll do that - thanks for the review.

**Pull request merged**
