### PR TITLE
Adjusting tests for #3536 / const checking of domains and arrays.

### PR DESCRIPTION
**Pull request by vasslitvinov**
* Retired a future - the test now exhibits the desired behavior:

    test/domains/bradc/modDomMethod.future

* Added a test for const checking of 'const in' task intents and formals
  for arrays/domains:

    test/parallel/taskPar/vass/const-in-intent-arrays-domains.chpl

* Added future tests for 'in' and 'const in' forall intents:

    test/parallel/forall/in-intents/array-var-var.chpl
    test/parallel/forall/in-intents/domain-var-var.chpl
    test/parallel/forall/in-intents/both-arr-dom-const-const.chpl
    test/parallel/forall/in-intents/both-arr-dom-const-var.chpl
    test/parallel/forall/in-intents/both-arr-dom-var-const.chpl

  When all these futures are fixed, the Chapel code could be merged
  into a single file and moved to test/parallel/forall/vass.
  That way this entire directory, test/parallel/forall/in-intents,
  can be removed.

While there:

* Removed an orphan alist-error.bad file.

* Moved sync.SEE_ALSO.txt and single.SEE_ALSO.txt into their respective
  directories, sync/ and single/ - like how it is done for:
    test/parallel/forall/forall.SEE_ALSO.txt

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Did you look at modDomQuery as well?  I think it just needs to be updated and the .future removed

**Comment by vasslitvinov** [comment]
@lydia-duncan : yes

**Comment by lydia-duncan** [comment]
I ask because I didn't see any changes go in for that test.  What was the result?

**Comment by vasslitvinov** [comment]
@lydia-duncan - see #3584

**Comment by lydia-duncan** [comment]
Awesome, thanks Vass!

**Pull request merged**
