### PR TITLE
Change expected intents for string arguments in multilocale libraries

### PR DESCRIPTION
**Pull request by lydia-duncan**
Prior to this change, we were relying on the default intent for strings
in multilocale libraries and banning other intents.  However, the default
intent for strings is `const ref` and due to the implementation of
multilocale interoperability, `const ref` is not feasible (because the
data is copied from the client code to the library server running
remotely).  This change makes it so that we allow strings to be
passed by `in` and `const in` intent, and ban the other intents for
multilocale interoperability.

While here, also update the error message for the single locale case - more than
just the listed ones are allowed, so it doesn't make sense to only say one of
the allowed ones in the error message.

I debated about blanket allowing more intents for single locale, but ultimately
decided against it - some of them run into an internal check which was intended
to ensure only strings were used but they got tangled up in it due to the
argument type being ref(string) at the time.  Resolving that should be do-able
but was more effort than I wanted to tackle this close to the release with other
priorities.

This change updates the expected behavior of string tests to reflect the new
status quo.

Testing:
- [x] test/interop/C/multilocale darwin with gasnet
- [x] test/interop/C darwin with COMM=none
- [x] full paratest on linux with gasnet
- [x] full paratest on linux with COMM=none
- [x] test/interop/python/multilocale darwin with gasnet
- [x] test/interop/python darwin with COMM=none
- [x] test/interop/python on linux with COMM=none
- [x] test/interop/python/multilocale on linux with COMM=gasnet

### CODE REVIEW

**Comment by bradcray** [comment]
I may have read through the diff too quickly, but is the implication that `[const] in` is not supported for single-locale?  I thought we were doing the string copies in/out for both single- and multi-locale libraries currently...  I.e., that a string in my external Python or C program that I pass into a Chapel `export proc` would not be aliased by Chapel's version of the string?

**Comment by lydia-duncan** [comment]
> is the implication that [const] in is not supported for single-locale?

Yeah, though that wasn't the case that caused me problems so it is possible that it would be okay to enable?

>  I thought we were doing the string copies in/out for both single- and multi-locale libraries currently... I.e., that a string in my external Python or C program that I pass into a Chapel export proc would not be aliased by Chapel's version of the string?

We always copy strings for Python interop, but that is done in the generated Cython code (because it has to be for Cython/Python to treat the memory as Python's).  For single locale C, we do not need to do that and can wrap the contents of a C string argument passed to us in a Chapel string.  I believe some of the limitations on intents for string arguments for C are due to caution, though in performing this work, I did find some intents that would require additional work (inout being one instance).

**Comment by bradcray** [comment]
Based on that description, I'd be inclined to permit 'in' intents and disallow 'ref' intents for single-locale `--library-python` compilations.  (1) to avoid lying (since your Python string is not actually being passed by ref from Python to Chapel) and (2) so that the same code designed to interop with Python (like Arkouda, say) could be compiled in single-and multi-locale Chapel with the same (`in`) intents.

Then as a bonus / cleanup, I think it'd be worth checking whether `in` can be supported for single-locale C interop as well, just to make it less of an outlier (without disallowing `ref`, assuming it is a true alias of the string's bytes).

**Comment by lydia-duncan** [comment]
That all seems reasonable to me!

**Comment by bradcray** [comment]
For this release?   ( :S

**Comment by lydia-duncan** [comment]
For posterity, we also agreed that single locale 1D array arguments should be treated the same way.

Arrays that are handled by chpl_opaque_array do not need to be treated this way imo (since they are passed by ref), though they should probably ban things like `in` intents

**Pull request merged**
