### PR TITLE
cleaned up MatrixMarket module PR #2847 

### PR DESCRIPTION
**Pull request by ct-clmsn**
fixed several outstanding issues with PR #2847 

module provides basic matrixmarket file serialization. this chapel implementation is inspired by gensim's implementation. matrixmarket format is supported by python (scipy.io) and matlab (for more information on this format: http://math.nist.gov/MatrixMarket/formats.html) matrixmarket format can help with language interoperability.

### CODE REVIEW

**Comment by ct-clmsn** [comment]
@mppf this should clean up #2847

**Comment by mppf** [comment]
* Can MatrixMarket.chpl go in modules/packages ? modules/packages is a better home for it
 * Can you add some tests ?

**Comment by ct-clmsn** [comment]
@mppf module moved to packages, cleaned up a couple small issues, added testing code for the read functions.

**Comment by mppf** [comment]
Thanks. Testing should run with start_test -- see https://github.com/chapel-lang/chapel/blob/master/doc/developer/bestPractices/TestSystem.rst

I think the main missing pieces are
 * .good files next to .chpl files
 * .execopts can specify input
 * it's OK if you want to have a script that wgets and does extensive testing, but simple input files should be checked it to run with start_test

You'll know your tests are OK when you can run

      start_test test/modules/packages/matrixmarket

and get some tests run and only successes.

**Comment by ct-clmsn** [comment]
@mppf did some file juggling and got a very simple version completed with downsized versions of the UF files. start_test works as expected.

**Comment by mppf** [comment]
I checkout out this branch and then ran start_test test/modules/packages/matrixmarket. I'm seeing a failure in complextst.chpl:

      [Executing diff complextst.good complextst.exec.out.tmp]
      1,2c1,2
      < 1474.78 + 1474.78i
      < -9.01713 + 1474.78i -5.73066 + 1474.78i
      ---
      > 1474.78 + 0.0i
      > -9.01713 + 0.0i -5.73066 + 0.0i

Since you reported that start_test worked as you expected - is there a commit missing? Or is this some kind of platform-specific issue?

Thanks.

**Comment by ct-clmsn** [comment]
@mppf I'm working with @e-kayrakli to get sparse domain storage support working correctly. At the moment, the unit test you referenced is a moving target. Hoping we can get something reasonable completed in the next couple days.

**Comment by ct-clmsn** [comment]
@mppf ok, decided to make a couple of minor changes which have fixed the issues you saw today along with sparse storage to/from disk functionality.

**Comment by mppf** [comment]
That cast-real-to-imag behavior has failed me for the last time. See #4029.

**Comment by ct-clmsn** [comment]
@mppf got a work-around fix implemented for complex case. added a couple of additional tests.

**Comment by mppf** [comment]
hi @ct-clmsn, you need to remove test/modules/packages/matrixmarket/*.compopts since the compiler already includes modules/packages by default and the duplicate module path entry causes a compilation warning (which makes the tests fail).

I have removed these files locally and am running full single-locale testing. If the testing passes, which I expect will happen, I plan merge this PR once you remove those .compopts files from it.

Thanks!

**Comment by mppf** [comment]
Test run passed, so now as far as I know we just need to remove the .compopts files and then this PR can be merged.

**Comment by ct-clmsn** [comment]
@mppf requested files removed! apologies for the "general disarray" with this PR - my developing git skill's continue to show some rough edges.

**Comment by bradcray** [comment]
Hi @ct-clmsn and @mppf : Is this module chpldoc-ready?  If so, should it be added to the list of packages to be documented such that it appears at http://chapel.cray.com/docs/master/modules/packages.html for the next release?

**Pull request merged**
