### PR TITLE
Avoid a gcc error by copying a string with strcpy instead of strncpy

### PR DESCRIPTION
**Pull request by daviditen**
Switch from strncpy to strcpy with no length argument to avoid a
gcc warning/error when copying a string.

### CODE REVIEW

**Comment by gbtitus** [comment]
I'm sorry, I totally blew this.  I misinterpreted the warning/error they printed.  Now that I look at it more closely I think what they're saying is that if a `src` has length `len`, `strncpy(tgt, src, len)` won't copy its trailing NUL character, thus leaving `tgt` unterminated.  I believe if you just change the `length` to `length+1` in the `strncpy()` you'd originally coded all will be well.

**Comment by daviditen** [comment]
The warning gcc is issuing is:

```
warning: 'strncpy' specified bound depends on the length of the source argument
```

Changing it to `length+1` is still dependent on the source argument, so it still issues the warning. I think it wants me to change it to use `strcpy` with no length argument.

**Comment by ronawho** [comment]
I would guess you want to use the destination length -- https://github.com/chapel-lang/chapel/pull/15896#discussion_r443079544

**Comment by daviditen** [comment]
The destination is freshly allocated memory, allocated to be size source `length+1`. I don't have any other way to compute it besides source `length+1`.

**Comment by ronawho** [comment]
Ah, I see -- nevermind me then.

**Comment by gbtitus** [comment]
Right, I don't think gcc knows the dest length.

The `strcpy()` solution may run afoul of some other gcc check(s) -- there has been at least one gcc version in the past which had a bug that warned about overflowing copy when in fact that couldn't occur.  But let's try this.  If it doesn't work we can always drop back to the `snprintf()` solution as a last resort!

**Comment by daviditen** [comment]
Thanks!

**Pull request merged**
