### PR TITLE
Implemented Merge Shuffle

### PR DESCRIPTION
**Pull request by Yudhishthira1406**
Signed-off-by: Yudhishthira1406 <divyen1406@gmail.com>

In reference to #14388 
This PR introduces the implementation of Merge Shuffle in the Random Module.
Following are some test results on my local machine i5 9thgen(4 cores) on a data of 2^26 real values.
Compiled with `--fast` flag

| shuffle(master) | Merge-shuffle |
| --- | --- |
| 2.35381 | 2.1176 |
| 2.37549 | 2.12351 |
| 2.38759 | 2.13009 |

I think the difference would be much more prominent with a multicore processor.

### CODE REVIEW

**Comment by Yudhishthira1406** [comment]
@ben-albrecht Please review this PR

**Comment by ben-albrecht** [comment]
@Yudhishthira1406 - somehow I missed this. I'll take a look over the next day or so. Thanks for your patience.

**Comment by Yudhishthira1406** [comment]
@ben-albrecht I just found that it is throwing segmentation fault when the array size is `10^6`.
I am still trying to figure out where it is going wrong.
Maybe you could help me with this.
Thanks.

**Review by ben-albrecht — CHANGES_REQUESTED** [review]
We should add a perf test with this change. Here's a suggested perf test from the previous attempt at this feature:

```chpl
/// test/library/standard/Random/performance/shuffle.chpl
use Random;
use Time;

config const correctness = false; // disables output
config const size = 100000;

var t: Timer;

var data: [1..size] int;
t.start();
shuffle(data, seed=10);
t.stop();
if !correctness {
  writeln('Time: ', t.elapsed());
}
```


I am currently unable to compile the above code with these changes. Here's the error I get:

```
$CHPL_HOME/modules/standard/Random.chpl:1185: In method '_Merge':
$CHPL_HOME/modules/standard/Random.chpl:1204: error: cannot assign to const variable
  $CHPL_HOME/modules/standard/Random.chpl:1241: called as (PCGRandomStream(int(64),false))._Merge(arr: [domain(1,int(64),false)] int(64), start: int(64), j: int(64), n: int(64)) from method 'shuffle'
  $CHPL_HOME/modules/standard/Random.chpl:161: called as (PCGRandomStream(int(64),false)).shuffle(arr: [domain(1,int(64),false)] int(64), blockSize: int(64)) from function 'shuffle'
  shuffle.chpl:12: called as shuffle(arr: [domain(1,int(64),false)] int(64), seed: int(64), param algorithm = 1: RNG)
note: generic instantiations are underlined in the above callstack
```

**Comment by Yudhishthira1406** [comment]
Hi, @ben-albrecht Thanks for the review I have added the performance test file and fixed the compilation error.
However, I am still struggling with the segmentation fault on some tests.

Regarding the compilation error, Is this a bug, or chapel is supposed to behave like this.
I implemented a test file in the chapel for this error.
```
proc foo(i: int) {
    const s = 1;
    i += s; 
}

foo(1);
```
It gave an error similar to above

```
test-const.chpl:1: In function 'foo':
test-const.chpl:3: error: cannot assign to const variable
```
However, an equivalent c++ file was compiled successfully
```
void foo(int i) {
    const int s = 1;
    i += s;
}

int main() {
    foo(1);
}
```

**Comment by ben-albrecht** [comment]
@Yudhishthira1406 - Chapel has argument intents to specify how the argument is passed to the function (see details in the [spec](https://chapel-lang.org/docs/master/language/spec/procedures.html#argument-intents)). In your example, the `int` type has a default intent of `const in`, meaning the argument is copied in and cannot be modified within the function body. If you want to modify `i`, you'll need to override the default intent with `in`, which means the arg is copied in and can be modified:

```chpl
proc foo(in i: int) {
    const s = 1;
    i += s; 
}

foo(1);
```

**Comment by ben-albrecht** [comment]
> However, I am still struggling with the segmentation fault on some tests.

How are you running the tests when the current implementation does not yet compile? Are you seeing the seg fault on the master branch?

**Comment by Yudhishthira1406** [comment]
> How are you running the tests when the current implementation does not yet compile? Are you seeing the seg fault on the master branch?
I checked out a new branch for testing purposes to keep the commit history clean.
But forgot to make changes in the `merge-shuffle` branch

**Comment by Yudhishthira1406** [comment]
@ben-albrecht, I have resolved the segmentation fault. The program runs without any fault
Thanks.

**Comment by ben-albrecht** [comment]
@Yudhishthira1406 - Great, thanks. I will take a look when I get a chance

**Comment by CaptainSharf** [comment]
Hi @Yudhishthira1406 , 
The current implementation of shuffle/permutation on master doesn't support multi-dimensional arrays and domains. I added an implementation of shuffle in #17053 . It'd be great if you could add support for multi dimensional arrays in this new version of merge shuffle. You can use the correctness tests for this case from the PR #17053.

**Review by ben-albrecht — CHANGES_REQUESTED** [review]
@Yudhishthira1406 - I am getting back to this. Can you let me know if you're still interested in moving this PR forward and able to respond to feedback? I think it would be valuable contribution to the project.

I checked the branch out and tried to diagnose why the parallel impl. in this PR is slower, and realized it was due to large number of `forall` loops created on the inner `while` loop. As an experiment, removing the blocksize entirely, i.e. `blockSize = size`, will make this implementation _much_ faster than the implementation on main.

If you're able to continue on this PR, my suggestions are:

1. rebase with `main`
2. Set `blocksize = size` for now (we can identify a more optimal blocksize in the future)
3. ensure `start_test test/library/standard/Random` completes successfully

Let me know if you have any questions -- thanks!

**Comment by mppf** [comment]
I'm closing this for now along with a [note](https://github.com/chapel-lang/chapel/issues/14388#issuecomment-1035048103) in #14388 about the current status. For now, I will close this PR. @Yudhishthira1406 please reopen this PR whenever you are able to get back to it, and thanks very much for your effort so far.

**Pull request closed without merging**
