### PR TITLE
Tweak error for passing a coercion value to a ref formal, add hint for classes

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
The temporary value produced by a coercion cannot be passed to a function that accepts the argument by `ref` or `const ref` intent. The following code illustrates a scenario where this error can occur:

```chapel
class C1 { var x = 0; }
class C2 : C1 { var x = 0; }

proc foo(c1: shared C1) {
  writeln(c1);
}

proc test() {
  var c = new shared C2();
  // error: value from coercion passed to const ref formal 'c1'
  foo(c);
}
test();
```

When coercing a `shared` subclass to its parent class, a temporary shared value is created that cannot be passed by reference. Users can unwittingly run into this error for `shared` because the default intent for `shared` classes is `const ref`.

---

This PR tweaks the message emitted for this error to try and emphasize that the coercion is _producing_ a value that cannot be passed by reference.

It also inserts an additional note explaining what types are being coerced.

Before:

```
test: 11: error: value from coercion passed to const ref formal 'c1'
test: 4: note: to function 'foo' defined here
```

After:

```
test: 11: error: in call to 'foo', cannot pass result of coercion by const reference
test: 11: note: implicit coercion from 'shared C2' to 'shared C1'
test: 4: note: when passing to 'const ref' intent formal 'c1'
```

---

Testing:

- [x] `ALL` on `linux64` when `CHPL_COMM=none`
- [ ] `ALL` on `linux64` when `CHPL_COMM=gasnet`

### CODE REVIEW

**Comment by dlongnecke-cray** [comment]
Hi @bradcray, does this seem more like what you had in mind? Right now I'm only printing the note `implicit coercion from <T1> to <T2>' when both types are managed classes, do you think we should lighten this restriction a bit and print the note for any coercion?

**Comment by bradcray** [comment]
> does this seem more like what you had in mind?

Yeah, I think this looks good.  Probably the only thing I'd change is to always say "reference" rather than sometimes saying "const reference" in the first line when it's `const ref` because I don't think the `const` is meaningful w.r.t. the error (right?).  What I mean is, if someone concluded "Oh I can't pass it by `const ref` but maybe I can pass it by `ref`" then the error has arguably given them false hope.  (I also find it a little weird to spell out "reference" but not "const" but wouldn't want to say "constant reference" either if passing by "reference" is the crux of the problem).

It seems as though this specialized error might be helpful for other coercion cases as well (?), but I'm not confident about that.  I tried the following program on master:

```chapel
proc foo(ref x: real) {
}

var i = 42;

foo(i);
```

and the error seems less confusing than the class case because it's more obviously a type mismatch.  What would the behavior of it be on your branch?

**Comment by dlongnecke-cray** [comment]
Yeah, still just a regular resolution error, we don't do any coercion at all in the `ref` case (though we probably do if the formal is `in` intent).

Since only 4 tests failed after I changed the _invariant_ lines of the error message, it's probably safe enough to just have the note `implicit coercion from <T1> to <T2>` always print? I'll run another paratest to be sure.

**Comment by dlongnecke-cray** [comment]
Output on that note for default arguments looks a little bit wonky, I can futurize this test, though?

```chapel
// test inspired by datetime.init

class MyClass {
  var x:int;
}

proc foo(arg:int, ref opt: shared MyClass? = nil ) {
  writeln(arg, " ", opt);
}

var s:shared MyClass? = new shared MyClass(3);

foo(1);
foo(2, s);
```

```
shared-default-arg-nil-ref.chpl:13: error: in call to 'foo', cannot pass result of coercion by reference
shared-default-arg-nil-ref.chpl:13: note: implicit coercion from 'nil' to '_ref(shared MyClass?)'
shared-default-arg-nil-ref.chpl:7: note: when passing to 'ref' intent formal 'opt'
```

**Comment by bradcray** [comment]
This doesn't look that much worse than the previous error message apart from the reference to `_ref(...)`.  But why does that `_ref` string only show up here and not in the other .goods files in this PR?  Would calling `getValue()` on the formal type cause it to go away without breaking the other cases?

**Comment by dlongnecke-cray** [comment]
Yeah I think it would be reasonable to just use `getValType()` on the formal and actual types, since the second note already specifies the formal intent.

Great!

**Review by daviditen — APPROVED** [review]

**Pull request merged**
