### PR TITLE
Minor test system fixups

### PR DESCRIPTION
**Pull request by mppf**
* return 0 only with no failures, return 2 if tests ran but some failed
* fix up nightly testing email to accept 2 as OK
* fix garbles in emails from new Summary line for Suppressions

### CODE REVIEW

**Comment by mppf** [comment]
@ronawho  could you have a quick look? I think it's trivial, but I want you to know I fixed the summary lines too :)

**Comment by ronawho** [comment]
util/buildRelease/gen_release checks start_test status

**Comment by ronawho** [comment]
util/pastPerformance/getoldperf also checks the status (indirectly through the mysystem call)

**Comment by mppf** [comment]
I think that testReleaseHelp will be improved by the change without modification, since you presumably care if the example tests fail when building a release.

**Comment by mppf** [comment]
getoldperf doesn't actually check the return code except to print it out. The exit is commented out in mysystem (line 148). I think the patch is OK as-is, and since you've looked over it mostly, I'm going to merge. If you find any more return code issues, I'd be happy to fix them...

**Comment by ronawho** [comment]
After looking at it a little more, I agree that getOldPerf doesn't actually use it. For some reason I assumed mysystem would actually do something with the fatal argument :)

I think testReleaseHelp is good now that you added that status == 2 thing. The thing that calls testReleaseHelp does it's own checks of the output and will report any errors

**Comment by ronawho** [comment]
So no post-commit changes need to be made so far as I can tell, everything looks great!

**Pull request merged**
