### PR TITLE
Allow for address space layout randomization in comm=ofi.

### LINKED ISSUE #12233: comm=ofi broadcast routines are incomplete
The comm=ofi versions of `chpl_comm_broadcast_global_vars()` and `chpl_comm_broadcast_private()` both have comments saying they won't work with address space randomization.  It would be nice to be able to run comm=ofi on a Mac, but that has (or may have) randomization and until the broadcast code works comm=ofi won't work there.

### PR DESCRIPTION
**Pull request by gbtitus**
The ofi comm layer didn't work in the presence of address space layout
randomization (ASLR), notably on Mac OS X.  The global and private
broadcast functions assumed that their respective compiler-created
address tables were at the same address in all locales, and for the
private variable tables, that the addresses they contained were the
same across all locales.  Neither of these was actually true, leading
to various sorts of mis-addressing failures (`SIGSEGV`, `SIGBUS`, failed
`nil` checks, etc.).

Here, distribute the necessary addresses among the program instances
during initialization, so that all the nodes have the right addresses
for things they need to reach on other nodes.  As part of this, have
the compiler emit the length of `chpl_private_broadcast_table[]` into a
new `chpl_private_broadcast_table_len` variable, so the runtime can know
how long that table is.  comm=gasnet didn't need that because it uses
AMs to do private broadcasts, and comm=ugni didn't need it because
although it does broadcasts using direct PUTs it doesn't have to deal
with ASLR.  But for comm=ofi we want to use direct PUTs even with
ASLR, so we have to know how long the private broadcast table is so we
can share the nodes' copies of that around the job.

This resolves #12233.

### CODE REVIEW

**Comment by gbtitus** [comment]
@mppf I've asked @elliot for the primary review, but would you also look at the compiler part for me?  Thanks!

**Comment by ronawho** [comment]
I haven't looked at the code yet, but high level questions:
 - Should we update gasnet to do direct PUTs as well? Will that be faster than the AM-based approach for networks where RDMA is supported?
 - Should we update ugni? I don't expect ASLR to bite us on crays, but it doesn't seem like a bad idea to avoid relying on it here. 
 - We probably don't really care about speed for gasnet or ASLR for ugni, but really what I'm wondering is if we could unify the broadcast implementations across comm layers, or if that's not possible because we're still early in initialization and may need to do out-of-band comm?

**Comment by gbtitus** [comment]
Taking the questions in reverse order ...

> * We probably don't really care about speed for gasnet or ASLR for ugni, but really what I'm wondering is if we could unify the broadcast implementations across comm layers, or if that's not possible because we're still early in initialization and may need to do out-of-band comm?

We're not actually in initialization proper at this point.  The runtime is all set up and we're being called from module init code, i.e. we can support Chapel code.  I think we could do this in common code for any comm layer implementations that can handle direct `GET`/`PUT` on unregistered memory.  Some of what's being transmitted here may not be registered in all cases, I'm not sure.

> * Should we update ugni? I don't expect ASLR to bite us on crays, but it doesn't seem like a bad idea to avoid relying on it here.

I would doubt ASLR will ever be enabled on systems that use uGNI, but it also wouldn't hurt anything to use this code there.

> * Should we update gasnet to do direct PUTs as well? Will that be faster than the AM-based approach for networks where RDMA is supported?

Your intuition as to the performance is probably better than mine.  I actually doubt the performance would matter, though, really.  The global table stuff is only done at startup time and at least the private broadcast usage I'm familiar with is only things like turning on comm diags across all the program instances.

The comm=gasnet code for these operations is a fair bit more complicated than either of the other two and I haven't followed it deeply.  Notably it involves the segment table which is an area I don't understand well.

**Comment by mppf** [comment]
+1 to the idea of creating more comm-layer-independent code

> The comm=gasnet code for these operations is a fair bit more complicated than either of the other two and I haven't followed it deeply. Notably it involves the segment table which is an area I don't understand well.

>  I think we could do this in common code for any comm layer implementations that can handle direct `GET`/`PUT` on unregistered memory.

I'm not sure if I'm following exactly right - but wouldn't this work for any comm layer that used a bounce buffer for PUT/GET on unregistered memory? My understanding is that we are currently expecting all the comm layers to have such functionality, but I might be wrong. In any case, it used to be the case that they didn't have that functionality, and I'm guessing that's the reason that the gasnet code doesn't just implement the broadcast in terms of regular put and get calls.

**Comment by gbtitus** [comment]
> ... wouldn't this work for any comm layer that used a bounce buffer for PUT/GET on unregistered memory? My understanding is that we are currently expecting all the comm layers to have such functionality, but I might be wrong.

It wouldn't necessarily have to be a bounce buffer-based solution; as long as the comm layer could do it at all, we'd be set.  I just couldn't remember whether we'd reached the point where that was true or not.  (Note that it would also be sufficient to show that all the addresses handled by the broadcast functions would, in fact, be registered in any comm layer requiring registration.  I'm fairly sure that's also true, I just haven't confirmed it for certain.)

**Comment by gbtitus** [comment]
#12338 is related, follow-on work.

**Pull request merged**
