### PR TITLE
Module docs for Tuple and dists

### PR DESCRIPTION
**Pull request by vasslitvinov**

### CODE REVIEW

**Comment by vasslitvinov** [comment]
@ronawho or @benharsh - how is this looking to you? I want to put it out so you know where I am heading.

**Comment by vasslitvinov** [comment]
Now we have the DSIUtil module in the module list/table of contents. Given that there is nothing user-facing in there, how can we remove it from there?

**Comment by ronawho** [comment]
At a glance, this is looking pretty good to me. I can review later today, if you're ready. You'll probably want somebody else to review the content of the dists, that's pretty far from stuff I'm familiar with.

The DSIUtil thing is pretty confusing. I don't understand why it's getting pulled in. Maybe a question for @lydia-duncan?

Lydia: For some reason DSIUtil is getting chpldoc'd even though we're not telling it to be. Any idea why it's getting pulled in?

**Comment by lydia-duncan** [comment]
I think it's because there's a 'use DSIUtil' call in there somewhere.  I feel like we ran into this with the standard modules at some point, but I don't remember what we did about it then . . . We might just have to make the script delete the file.

**Comment by ronawho** [comment]
Do we intentionally chpldoc 'used' modules, or is that a bug? If it's intentional it seems like a strange choice to me. 

Vass: can you try just removing the file in the post-processing step? It kinda doubt that will work. I'd imagine we already have the index built up with DSIUtil in it, and just removing the file might not work. Worth a shot though.

**Comment by lydia-duncan** [comment]
It was originally intentional - from the perspective of a user creating documentation for their program, if their program has multiple module files, they'd want to get all of it in one go instead of having to call chpldoc on each one individual.  I agree it doesn't make as much sense for our use case, but our use case is unique in many ways.

**Comment by vasslitvinov** [comment]
Adding the following to documentation target in modules/Makefile does the trick:

rm ${DOC_SPHINX}/source/modules/dists/DSIUtil.rst

Thank you guys and gals!


DSIUtil is pulled in, methinks, because it is use'd in a few places.

**Comment by vasslitvinov** [comment]
Elliot - I will let you know when it is ready and will look for content reviewers.

**Comment by lydia-duncan** [comment]
It only needs one use to turn up.  I think it would be harder to prevent this, since chpldoc works on the entire program structure which it gets from the parser and doesn't save which Chapel file on which it was originally called.

**Comment by vasslitvinov** [comment]
Replacing this with #2611 
for clean revision history.

**Pull request closed without merging**
