### PR TITLE
Array view annotations

### PR DESCRIPTION
**Pull request by bradcray**
Add annotations for recent array views work:

* merge of array views
  - included separate 16-node entry for hpl.hpcc2012, rewritten as part of array views work
* merge of wide pointer optimization for arrays resulting from array views work

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho or @benharsh : Would one of you give this a quick review?  I've checked to make sure that it works for normal perf testing results, but don't feel confident about my 16-node annotation (nor am I sure how to test it easily).  Perhaps I'm overdoing it in trying to add that annotation, but I wanted to remember that the test got worse less due to array views (I think) and more because we rewrote aspects of the test.

**Comment by ronawho** [comment]
Looks fine to me

**Comment by ronawho** [comment]
I regenerated the 16 node graphs just to make sure my commits didn't screw anything up. Looks like the hpl.hpcc2012 annotation is missing. 

Think you need to specify the full basename (hpcc2012.ml-perf and hpcc2012.ml-time) instead of just trying to use hpl.hpcc2012. And since this is a multi-locale only graph, you can drop the config from it.

**Comment by ronawho** [comment]
And Bens wide pointer patch went in on the 5th, but the annotation date should be for the 6th.

**Comment by ronawho** [comment]
sorry, should have looked more carefully the first time

**Pull request merged**
