### PR TITLE
Remove some additional references to SourceForge

### PR DESCRIPTION
**Pull request by bradcray**
I was surprised to find how frequently our documentation referred to
the SourceForge mailing lists, which I apparently overlooked when
converting things to Discourse this summer.  Here, I point developers
to the Discourse forums instead and remove some other references to
the SourceForge mailing lists, making slight tweaks in the vicinity
while there.

I believe the remaining active references to SourceForge mailing lists
are our scripts which still send "all passing" cases to SourceForge.
Removing these cases will either require more significant changes to
the scripts, or sending them to some other dummy email address.

### CODE REVIEW

**Review by ben-albrecht — COMMENTED** [review]
There are a few more reference to SF lists in `util` - should these be removed/edited too?

```
./util/buildRelease/testRelease
12:$allmail = "chapel-test-results-all\@lists.sourceforge.net";

./util/cron/nightly
24:$allmail = "chapel-test-results-all\@lists.sourceforge.net";

./util/test/genGraphs.py
1121:            # files over to sourceforge.
```

**Comment by bradcray** [comment]
> should these be removed/edited too?

The two mailing list cases are the ones I described in the last paragraph in the OP:

> I believe the remaining active references to SourceForge mailing lists
> are our scripts which still send "all passing" cases to SourceForge.
> Removing these cases will either require more significant changes to

The genGraphs.py reference looked outdated to me, but I wasn't confident (and
@ronawho was out that day to check with), so since it was in a comment and wasn't
the last reference to SourceForge in the repo, I didn't remove it.

**Review by ben-albrecht — APPROVED** [review]
Missed that in the PR description. LGTM, thanks!

**Comment by ronawho** [comment]
>The genGraphs.py reference looked outdated to me, but I wasn't confident (and
@ronawho was out that day to check with), so since it was in a comment and wasn't
the last reference to SourceForge in the repo, I didn't remove it.

Yeah, that's outdated. I think we should just change "sourceforge" to "the web" or something generic instead of putting dreamhost or whatever the current provider is.

**Pull request merged**
