### PR TITLE
Update quickReference

### LINKED ISSUE #11528: quickReference.pdf minor bitrot
doc/rst/language/quickReference.pdf has a few out of date bits.  I created a branch to fix them.  But I don't know how to edit the file, so you get an issue instead of a PR.

First section:

Quick Start: one-line "hello, world"

```
$ chpl hello.chpl
./a.out
hello, world
```

Should now be `./hello` instead of `./a..out`

Middle section:

```chapel
Classes
class Circle {
  var p: Point;
  var r: real;
}
var c = new Circle(r=2.0);
```

Maybe `var c = new unmanaged Circle(r=2.0);`, since ti's deleted later?
Or leave it as `new (borrowed) Circle` and drop the `delete c` line?

Penultimate section:

```chapel
var c: Circle
on Locales[i] {
   writeln(here);
   c = new Circle();
}
writeln(c.locale);
on c do { ... }
```

`c = new owned Circle()`?

Ultimate section

```
www: http://chapel.cray.com
```

`chapel-lang.org`?

### PR DESCRIPTION
**Pull request by mppf**
Addressing problems from issue #11528 

 * Uses `owned` in quickReference class examples
 * Fixes `by` vs `in` precedence (also in spec) to match parser / behavior
 * Adds Gitter link to quick reference
 
Closes #11528

Reviewed by @lydia-duncan - thanks!

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Why did the quickReference file type change (pdf -> docx)?

**Comment by lydia-duncan** [comment]
Oh, it didn't change, you just removed the accidentally committed copy.  It looks like top-level .gitignore needs to be updated to hide the .pdf file

**Comment by mppf** [comment]
> Oh, it didn't change, you just removed the accidentally committed copy. It looks like top-level .gitignore needs to be updated to hide the .pdf file

I thought we were supposed to have one in it. I tried to regenerate it. Might be worth checking out the branch to see if the file is really there, since the GitHub diff is confusing.

**Comment by mppf** [comment]
I checked by checking out this branch elsewhere and I see the .pdf file as expected.

**Comment by lydia-duncan** [comment]
> I thought we were supposed to have one in it. I tried to regenerate it. Might be worth checking out the branch to see if the file is really there, since the GitHub diff is confusing.

Hmm, yeah, good point.  I need to look at it anyways to double check the changes.  Seems like the .gitignore related to quickReference is quite out of date, then

**Comment by lydia-duncan** [comment]
Should the expression precedence `new` entry on page 1 be updated to include owned/shared/borrowed/unmanaged?  Additionally, it seems little odd to me to only include `owned` in the classes section and not the others, though that will make the doc run onto another page (I think).

**Comment by mppf** [comment]
> Should the expression precedence new entry on page 1 be updated to include owned/shared/borrowed/unmanaged?

I don't think so, since these are in the parser's precedence table, they have limited participation in general expressions. I don't think the spec's table lists them either. I suppose we could update both...

>  Additionally, it seems little odd to me to only include owned in the classes section and not the others, though that will make the doc run onto another page (I think).

Please point out where exactly else could possibly include `owned`. I probably missed something.

**Pull request merged**
