### PR TITLE
Retire two I/O futures

### PR DESCRIPTION
**Pull request by mppf**
Both of these futures are wrong, in that reading tuples and arrays is in fact supported and functional. It's just that these futures were not testing for what works currently.

Discussed with @bradcray.

### CODE REVIEW

**Comment by mppf** [comment]
@bradcray - I noticed these futures mentioned in the STATUS file, which surprised me because I think that tuple and array reads are working. Both of these tests arguably just need updating. I'd like to know if you agree or if there is some functionality that you think we are missing here.

For the tuple future in particular, the test seemed to be expecting that

   writeln( (1,2,3) );

would output

       1 2 3

when in fact it outputs

      (1, 2, 3)

Other than that, the test has an issue because in the default format, it is hard to know when the end of a string is. The default rule for reading strings is to stop on whitespace.

**Comment by bradcray** [comment]
Thanks Michael -- With a quick look, I agree that these look retire-able.  I could imagine wanting the ability to read a tuple without requiring the parens and commas to be in the input stream (which is probably what I was trying to capture in the original future), but am OK with taking this approach to retiring the futures and making this the status quo for now.  @daviditen would probably value a corresponding STATUS.devel update with this PR.

**Comment by mppf** [comment]
@bradcray - re reading a tuple without the parens, I'd expect we'd support that through the tuple expansion syntax, e.g.

    var tup:3*int;
    writeln((...tup));

Is there some reason that doesn't cover the case you were probably hoping for originally? This seems to work for reading for me as well, barring issues of delimiting integers/strings etc.

**Comment by bradcray** [comment]
I'm pretty sure I don't remember what I was wanting 4 years ago... :)

**Pull request merged**
