### PR TITLE
Remove scripts in util/misc

### PR DESCRIPTION
**Pull request by mppf**
Removes `chpl2pdf` and `diffLatexCode` which made sense when we had a latex spec.

Removes `replstring` because our repository doesn't need to track a utility for multi-file find and replace.

Removes `sclc` because there are other ways to count lines and they are out of scope for this project

Removes `test_launch` because it does not seem useful.

Reviewed by @vasslitvinov - thanks!

### CODE REVIEW

**Review by vasslitvinov — APPROVED** [review]

**Comment by bradcray** [comment]
I thought `chpl2pdf` was a generally useful standalone script that was unrelated to the spec?  (though I'll admit I haven't used it in years).

**Comment by mppf** [comment]
> I thought chpl2pdf was a generally useful standalone script that was unrelated to the spec? (though I'll admit I haven't used it in years).

Yeah, but it doesn't work right now. Of course we could put back a latex syntax highlighter in highlight/ ... but it seemed to me better to remove the script since it's been broken for a year or so (ish?)

**Comment by mppf** [comment]
The way it is related to the spec is that it uses the spec's listing files for the syntax highlighting, if that wasn't clear.

**Comment by bradcray** [comment]
I think having (even if not actively maintaining) a LaTeX syntax highlighter would also be of value in that I use it whenever I write a Chapel paper and expect others in the community would benefit from it as well.  So I'd be in favor of reinstating `chapel_listing.tex` and if that was the only thing that broke this script, the script as well.

**Comment by mppf** [comment]
Alright

**Comment by mppf** [comment]
PR #16627 will do that.

**Comment by bradcray** [comment]
Thanks!  If it pains you to keep util/misc around for this one script, we could move the script itself into the highlight/latex/ directory as well (which would also probably increase the chances that anyone would find it going forward, so it might be a good idea even if it doesn't pain you).

**Comment by mppf** [comment]
We have the directory around anyway for the gen-LAPACK scripts (which are arguably of historical interest and I'm not sure they really need to be in the repo, but I didn't want to mess with them). Anyway I'll move chpl2pdf to the highlight directory to increase the chances of someone finding it.

**Comment by mppf** [comment]
PR #16632 will move chpl2pdf to highlight/latex

**Comment by bradcray** [comment]
Thanks!

**Pull request merged**
