### PR TITLE
Support stridable queries on sparse domains

### PR DESCRIPTION
**Pull request by bradcray**
While investigating support for slicing of sparse domains/arrays in support of issue #8023, the first thing I ran into was the lack of support for querying the stridability of sparse domains.  This change adds the ability for sparse domains to support a `stridable` query that is implemented by forwarding the query on to their parent domains.  It also adds tests to make sure this works with our three main sparse domain maps today, and that it works when creating sparse domains of other sparse domains.

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Do we expect arrays to now support stridable method too, or is this PR strictly for sparse domains?

**Comment by bradcray** [comment]
> Do we expect arrays to now support stridable method too, or is this PR strictly for sparse domains?

This PR is only focused on the sparse domain case because that was the case I ran into while working on sparse slicing.  It looks to me like dense arrays don't support stridable queries currently, though I could be misinterpreting.  If/when dense arrays do, sparse probably should as well.

**Comment by ben-albrecht** [comment]
> It looks to me like dense arrays don't support stridable queries currently, though I could be misinterpreting. 

Sorry I was not clear - I was curious about what error we would get when trying to slice a sparse array with this branch:

```chpl
const D = {1..10};
var sD: sparse subdomain(D);
var A: [sD] int;
sD += [1,2,3,4];
writeln(A[1..4]);
```

This still fails with:

```
sps.chpl:5: error: unresolved call 'DefaultSparseDom(1,int(64),domain(1,int(64),false)).stridable'
```

I know that we don't yet expect sparse array slicing to magically work, but is this error expected?

**Comment by bradcray** [comment]
> is this error expected?

I didn't expect it, and think that my first commit would've fixed it, but that my final one would not.  My guess is that the issues is that the slicing code is trying to call `stridable` not on the record implementing the sparse domain, but on the underlying class.  And for some reason, DefaultSparseDom is the one sparse domain class we have that doesn't have a `stridable` field.

I think that this PR is still valuable in its exposure of `stridable` to users (seems like a no-brainer, and I can't think of any reason we haven't in the past), but your observation points out that more work is required to get past this first bump toward sparse array slicing.

**Comment by buddha314** [comment]
For those of us playing the home game, would it be worth it to provide an example?  Does this commit provide something I may be able to use directly?

**Comment by bradcray** [comment]
@buddha314 : This PR just permits you to say:

```chapel
mySparseDomain.stridable
```

for sparse domains as you already could for dense domains where it'll return "true" if the parent domain is stridable, "false" otherwise.  I.e., given:

```chapel
var mySparseDomain: sparse subdomain(D);
```

it essentially will tell you whether or not `D` is stridable.  So yes, it's usable, but it may not be terribly useful.

**Pull request merged**
