### PR TITLE
Changed Prime generator to Primality test only 

### PR DESCRIPTION
**Pull request by krishnakeshav**
Some improvisations made - 

1. Modified program only to check if the number is prime or not.
2. Changed dir name from prime_generator to primality- Because it's more relevant name.
3. Reduced test case size.

@ben-albrecht

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Hi @krishnakeshav - thanks for the updates. It looks like you will need to resolve the conflicts in `test/GRAPHFILES` before we can merge.

**Comment by krishnakeshav** [comment]
@ben-albrecht  - I see some re-organization of suites. Though I fixed conflicts, I think @lydia-duncan should also review it since she was the one working with reorganization. Hopefully I did a right thing. :)

**Comment by lydia-duncan** [comment]
Your diff looks reasonable after the reorganization, sorry to make things more difficult :)

**Comment by krishnakeshav** [comment]
No worries. We just got started. Waiting on @ben-albrecht . :)

**Comment by ben-albrecht** [comment]
- [X] tested locally

Looks good. Thanks!

**Pull request merged**
