### PR TITLE
Error when trying to rename an exported symbol with illegal characters

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
Error when trying to rename an exported symbol with illegal characters

In #17913 I merged the `interop/C/llvm` and `interop/C/c-backend` test
directories together, and I broke the `hyphenated-name` future as
a result.

It recently started passing, but the header of the library it produces
is not valid C code (the exported module initializer function
contains a `-`).

Issue a compiler error in `legalizeSymbolName` when compiling a
library and an exported symbol with illegal characters cannot be
renamed.

Remove a second set of redundant calls to `legalizeSymbolName`
from `codegen_header`. The calls in `uniquify_names` should be
enough.

Tweak the `.gitignore` in `interop/C` to ignore the `lib/*` folder
while there.

Add a note to the `hyphenated-name` future recommending that
it be turned into a `test.c` test after #9594 is addressed.

See #9594 for discussion on a longterm solution to this issue.

Reviewed by @lydia-duncan. Thanks!

TESTING:

- [x] `ALL` on `linux64` when `COMM=none`
- [x] `ALL` on `linux64` when `COMM=gasnet`

Signed-off-by: David Longnecker <dlongnecke-cray@users.noreply.github.com>

### CODE REVIEW

**Comment by dlongnecke-cray** [comment]
Hi @lydia-duncan mind reviewing this since you made this and I'm pretty sure I broke it in some way?

**Comment by lydia-duncan** [comment]
I actually think we should determine a way to restore a failure mode when making the .chpl file into a library.  It's not the library client's fault the library they're trying to use doesn't work and it's not the responsibility of the library client to fix it - it's the duty of the library writer to ensure their compiled library works and they should see an error message when compiling the code, so that they can adjust things appropriately to make a library that works.

The error message that the test previously experienced is not great (I can send you a link to an instance of the job that failed with it) but it at least has the benefit of failing when compiling the .chpl file into a library

**Comment by dlongnecke-cray** [comment]
Alright, that sounds like a plan. I'm going to close this branch and open another one that inserts a compiler error instead.

**Comment by dlongnecke-cray** [comment]
Hi @lydia-duncan I've gone ahead and issued a compiler error. How do you feel about it?

**Review by lydia-duncan — APPROVED** [review]
I think the only missing is that we were going to have you add a note to the .future that a .test.c file that uses the .chpl file should be added when the future is resolved.  Other than that, I think this is good to go!

**Comment by lydia-duncan** [comment]
Don't forget to merge this, David!

**Pull request merged**
