### PR TITLE
Add a future test for spawn(..stderr=STDOUT)

### PR DESCRIPTION
**Pull request by Rapiz1**
Add a future test for `spawn(..stderr=STDOUT)` since it's not working now.

Relates to https://github.com/chapel-lang/chapel/issues/15497

@bradcray Kindly review.

### CODE REVIEW

**Comment by Rapiz1** [comment]
@Aniket21mathur Thanks! :)

**Comment by bradcray** [comment]
Hi @Rapiz1: Thanks for filing this.  I wouldn't be opposed to merging it as-is, but what would it take to extend the program to make sure that the echo'd strings are not just _not_ going to the original process's stdout/stderr, but also to make sure they're going where they should?  E.g., can you capture that output of the subprocess and print it out in a special format from the main process to make sure that it's not just getting dropped on the floor?

**Comment by Rapiz1** [comment]
@bradcray That sounds great. I have updated the test.

**Comment by bradcray** [comment]
This looks great, thanks!  Before I merge, would you do one other clean-up thing, which I unfortunately forgot to mention yesterday?

The `.future` file should have a first line that describes the future briefly.  In this case a good choice would be "bug: spawn(..stderr=STDOUT) not working".  Then a blank line and then you can either summarize the issue again, or you can just put in `#15497` to refer readers to the related issue.

**Comment by Rapiz1** [comment]
@bradcray Sure. I have added lines in .future. :)

**Comment by bradcray** [comment]
Thanks @Rapiz1, merging now!

In our "new issue" template, there's a section template that permits a hyperlink to an existing future and its PR to be added to the issue, which can be really helpful for someone looking at the issue.  If you'd be willing to update #15497 to include that section referring to this future, I think that'd be great.  Here's a sample issue that uses the format:  https://github.com/chapel-lang/chapel/issues/15443

**Pull request merged**
