### PR TITLE
Fix chpldoc output for dmapped variables

### PR DESCRIPTION
**Pull request by lydia-duncan**
UtilReplicatedVar was experiencing output of the form:

``const rcDomain = AppendExpr.Call09chpl__distributedrcDomainBase``

for a declaration like this:

``const rcDomain = rcDomainBase dmapped new dmap(rcDomainMap);``

Turns out there were a couple of issues.  One was the new call, the other
was a failure to recognize chpl__distributed.  Added a new branch to the
if/else statement in AstToText for each of these cases.

Added a test of the problem.

Verified that the standard module UtilReplicatedVar has the correct output
now.  Testing over std/

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Probably either @noakesmichael or @vasslitvinov would be best to review this - Mike because he wrote AstToText, Vass because I believe he wrote the documentation for UtilReplicatedVar and discovered this problem in the first place.

**Comment by lydia-duncan** [comment]
Regenerated documentation for UtilReplicatedVar available upon request

**Comment by noakesmichael** [comment]
I’d be happy to take this.

Mike



On Sep 21, 2016, at 2:36 PM, Lydia Duncan <notifications@github.com<mailto:notifications@github.com>> wrote:


Probably either @noakesmichael<https://github.com/noakesmichael> or @vasslitvinov<https://github.com/vasslitvinov> would be best to review this - Mike because he wrote AstToText, Vass because I believe he wrote the documentation for UtilReplicatedVar and discovered this problem in the first place.

**Comment by lydia-duncan** [comment]
Passed standard testing

**Pull request merged**
