### PR TITLE
Add pragma

### PR DESCRIPTION
**Pull request by leekillough**
Signed-off-by: Lee Killough <lee.killough@hpe.com>

### CODE REVIEW

**Comment by mppf** [comment]
Were you able to check that this resolves the failing tests?

**Comment by leekillough** [comment]
> Were you able to check that this resolves the failing tests?

Yes, this resolves the failing tests.

**Comment by mppf** [comment]
Thanks!

**Comment by bradcray** [comment]
@leekillough: As mentioned [on your previous PR](https://github.com/chapel-lang/chapel/pull/16901#issuecomment-755520338), please:

* use a descriptive title/headline for each PR
* have the OP and merge message describe what the change is and why it's being done
* give credit to the PR's reviewer (@mppf) in this case in the merge message

The rationale for these steps is so that when we're reviewing the project history (e.g., in writing up release notes or tracking down the cause of a failure down the road), it's apparent what the PR was for without having to dive into the changes to the file, mailing lists, etc.

**Pull request merged**
