### PR TITLE
Remove old support for tracking release-over-release performance

### PR DESCRIPTION
**Pull request by ronawho**
In the past, we would manually run the current benchmarks with older chapel releases and graph the results. This was useful for weeding out changes to benchmarks and machines to give us a simpler view of how performance of the compiler/modules/runtime changed over time.

However, we haven't really done this since ~2018. This information was really useful during our "5 year push" to improve performance, but performance is pretty stable nowadays and we track weekly performance triage much more closely so it's rare that any regressions slip in.

Given that we haven't used this information in years, I think we can remove the infrastructure that we used to collect the results and the infrastructure we use to overlay the release-over-release results with nightly.

### CODE REVIEW

**Review by riftEmber — APPROVED** [review]

**Comment by ronawho** [comment]
Old graphs are still up at https://chapel-lang.org/perf/chapcs/releaseOverRelease/?configs=default&suite=performancetracking. 

We haven't collected any data for old releases (with `testReleasesPerformance`) since 2018 and we haven't really looked at these graphs since then. Note that `splitDat` was used to splice in the data from old releases with the most recent nightly result which is why there's "new" data in these graphs, but it's not something we look at anymore.

**Comment by ronawho** [comment]
@bradcray don't need you to review the code removal, just looking for an ACK that you're ok removing the infrastructure.

**Comment by bradcray** [comment]
I'd probably back out the changes to nightly and util/cron/test-perf.chapcs.bash because I can see it weighs those commonly used scripts down, but I probably would leave spliceDat and testReleasesPerformance in-place because I think they remain useful without those features in nightly.

**Comment by ronawho** [comment]
Hmm, what's the motivation for keeping in the repo vs being able to look at the history if we want these again? I guess if it's still in the repo there's a higher likelihood somebody could find the functionality again if they want it. I think the downside is likely bitrot and  `testReleasesPerformance` does require some trivial maintenance at release time

**Comment by bradcray** [comment]
> what's the motivation for keeping in the repo vs being able to look at the history if we want these again?

They're not large files and I find it easier to find things that I want and can't remember well by `git grep`ping or `find`ing for them rather than surfing the git history.

**Comment by ronawho** [comment]
Ok, I can understand that motivation. I'm just going to close this then, leaving the nightly code will exercise `spliceDat` instead of leaving it untested.

**Pull request closed without merging**
