### PR TITLE
Fix compare link in the email body. Build the compare url from the gi…

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
…t event pull request target

Compare_url on the pull_request handle does not resolve to base_sha and commit sha.
https://api.github.com/repos/chapel-lang/chapel/compare/{base}...{head}

This PR will substitute base and head with appropriate SHAs(base_sha, merge_sha)

### CODE REVIEW

**Comment by riftEmber** [comment]
I'm not sure I understand this change well enough to review it; what was `github.event.repository.compare_url` getting wrong?

**Comment by bhavanijayakumaran** [comment]
> I'm not sure I understand this change well enough to review it; what was `github.event.repository.compare_url` getting wrong? See the compare url read from pull_request_target attached [https://api.github.com/repos/chapel-lang/chapel/compare/{base}](https://api.github.com/repos/chapel-lang/chapel/compare/%7Bbase%7D)...{head} not have the base and head inline. I need to construct the correct url by looking up base and head sha seen on the pull_reques_ target.

**Review by riftEmber — APPROVED** [review]
Thanks for the explanation

**Comment by bhavanijayakumaran** [comment]
> Thanks for the explanation

Thanks @riftEmber for taking time to review.

**Pull request merged**
