### PR TITLE
update copy rights from 2022 to 2023 exclude the files in third party…

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
…and test folders

https://github.com/Cray/chapel-private/issues/4109

Based on the comments from a PR to update the copyrights for 2021, excluded files under third party and test folders.
https://github.com/chapel-lang/chapel/pull/18920
Signed-off-by: bhavanijayakumaran <82669529+bhavanijayakumaran@users.noreply.github.com>

### CODE REVIEW

**Comment by bhavanijayakumaran** [comment]
The CI copy-right check is failing because the pattern "2022" does not match with the copyright (2023) files changed

[INFO] Checking for copyrights in source files: Copyright .*2022[^0-9]* Hewlett Packard Enterprise Development LP

this_year=$(date '+%Y')
copyright_pattern="Copyright .*${**this_year**}[^0-9]* Hewlett Packard Enterprise Development LP"
source_dirs="compiler runtime make modules*"

I guess we will merge it in the new year once we come back from the break.

**Comment by lydia-duncan** [comment]
For reviewers, here are some categories to grab so that we minimize missed issues due to reviewer exhaustion.  Please comment with what categories you are grabbing to reduce duplicate effort:
- [ ] top level files
- [ ] compiler/AST
- [ ] compiler/adt and compiler/backend
- [ ] compiler/codegen
- [ ] compiler/include
- [ ] compiler/llvm
- [ ] compiler/main
- [ ] compiler/make
- [ ] compiler/optimizations
- [ ] compiler/parser
- [ ] compiler/passes
- [ ] compiler/resolution
- [ ] compiler/util
- [ ] compiler top level
- [ ] frontend top level, frontend/doc and frontend/lib top level
- [ ] frontend/include/chpl top level
- [ ] frontend/include/chpl/framework
- [ ] frontend/include/chpl/parsing
- [ ] frontend/include/chpl/resolution
- [ ] frontend/include/chpl/types
- [ ] frontend/include/chpl/uast
- [ ] frontend/include/chpl/util
- [ ] frontend/lib/framework
- [ ] frontend/lib/immediates and subdirectory
- [ ] frontend/lib/parsing
- [ ] frontend/lib/resolution
- [ ] frontend/lib/types
- [ ] frontend/lib/uast
- [ ] frontend/lib/util
- [ ] frontend/test top level and frontend/test/framework
- [ ] frontend/test/parsing
- [ ] frontend/test/resolution
- [ ] frontend/test/uast
- [ ] frontend/test/util
- [ ] frontend/util and subdirectory
- [ ] make top level
- [ ] make/compiler
- [ ] make/platform
- [ ] make/tasks
- [ ] man
- [ ] modules top level and modules/layouts
- [ ] modules/dists
- [ ] modules/internal
- [ ] modules/minimal and subdirectory
- [ ] modules/packages and subdirectories
- [ ] modules/standard and subdirectories
- [ ] runtime top level
- [ ] runtime/etc
- [ ] runtime/include
- [ ] runtime/make
- [ ] runtime/src
- [ ] tools top level
- [ ] tools/c2chapel
- [ ] tools/chpldoc
- [ ] tools/chplvis
- [ ] tools/mason
- [ ] tools/protoc-gen-chpl
- [ ] util

**Comment by lydia-duncan** [comment]
Ignore the check_annotations failure for now, it is warning about the copyright year so won't pass until closer to when we want to merge the PR

**Comment by lydia-duncan** [comment]
> I changed the copy right in the below files from 2022 --> 2023. Should I change it to be 2022-2023 instead?
> 
> tools/chpldoc/arg-helpers.cpp
> tools/chpldoc/arg-helpers.h

For these, definitely

> util/buildRelease/license_text_for_comment.txt --> I guess it should be 2023 in this file
> util/build_configs/cray-internal/chapel.spec.template

I don't actually know the answer for these, maybe someone more familiar with the module builds like @ronawho or @bradcray knows?

**Comment by lydia-duncan** [comment]
Starting off, I'll take on tools/protoc-gen-chpl

**Comment by bhavanijayakumaran** [comment]
> > util/buildRelease/license_text_for_comment.txt --> I guess it should be 2023 in this file
> > util/build_configs/cray-internal/chapel.spec.template
> 
> I believe it's correct that these should both be simply 2023. I think the first is essentially the starting point that someone should use when creating a new file, so should reflect the year that file was created. The second I believe must show up somewhere in the modules we build for Cray systems, but I'm less familiar with it.
> 
> And, as Lydia says, files that are ours that only have a single date in them because they were introduced last year (say, `2022`) should be updated to `2022-2023`.

updated to 2022-2023

**Comment by lydia-duncan** [comment]
> I think the first is essentially the starting point that someone should use when creating a new file, so should reflect the year that file was created.

Do you know off hand if we have a doc that points to that?  It seems useful to do instead of just copying some random file

**Comment by bradcray** [comment]
> Do you know off hand if we have a doc that points to that? It seems useful to do instead of just copying some random file

`git grep` suggests "no", but it also suggests I may be getting my files mixed up.  I thought that the script that checks copyrights pointed to some standard header to use as a starting point, but it doesn't point to this, and another script in buildRelease does.  So you may have been correct that this is more about building the release than I was thinking.

**Comment by bhavanijayakumaran** [comment]
> I checked some of the edge cases that were missed in previous years. The ones from 2021 -> 2022 look to be avoided (nice!), but I think we missed [the fix from this PR](https://github.com/chapel-lang/chapel/pull/17402/files) again.
> 
Fixed

**Comment by bhavanijayakumaran** [comment]
I did a search for 2022 in all the files(except for the ones under third-party and test)
git grep -l '2022'  -- ':!third-party/*' ':!test/*'  

Will go through the list and will change the files if needed.
Found this list:

CHANGES.md
doc/rst/developer/implementation/compilerOverview/compilerOverview.pdf
doc/rst/language/evolution.rst
doc/rst/language/spec/records.rst
doc/rst/usingchapel/prereqs.rst
frontend/lib/parsing/bison-chpl-lib.cpp
tools/chpldoc/arg-helpers.cpp
tools/chpldoc/arg-helpers.h
util/build_configs/cray-internal/setenv-xc-x86_64.bash
util/devel/test/singularity/current/amazonlinux-2022-nollvm/singularity.def
:...skipping...
CHANGES.md
doc/rst/developer/implementation/compilerOverview/compilerOverview.pdf
doc/rst/language/evolution.rst
doc/rst/language/spec/records.rst
doc/rst/usingchapel/prereqs.rst
frontend/lib/parsing/bison-chpl-lib.cpp
tools/chpldoc/arg-helpers.cpp
tools/chpldoc/arg-helpers.h
util/build_configs/cray-internal/setenv-xc-x86_64.bash
util/devel/test/singularity/current/amazonlinux-2022-nollvm/singularity.def
util/devel/test/singularity/current/amazonlinux-2022/singularity.def
util/devel/test/vagrant/README-distro-timelines.txt
util/devel/test/vagrant/provision-scripts/dnf-deps.sh
util/devel/test/vagrant/provision-scripts/pacman-llvm.sh
util/test/perf/perfgraph.js

**Comment by bhavanijayakumaran** [comment]
> I did a search for 2022 in all the files(except for the ones under third-party and test) git grep -l '2022' -- ':!third-party/_' ':!test/_'
> 
> Will go through the list and will change the files if needed. Found this list:
> 
> CHANGES.md doc/rst/developer/implementation/compilerOverview/compilerOverview.pdf doc/rst/language/evolution.rst doc/rst/language/spec/records.rst doc/rst/usingchapel/prereqs.rst frontend/lib/parsing/bison-chpl-lib.cpp tools/chpldoc/arg-helpers.cpp tools/chpldoc/arg-helpers.h util/build_configs/cray-internal/setenv-xc-x86_64.bash util/devel/test/singularity/current/amazonlinux-2022-nollvm/singularity.def :...skipping... CHANGES.md doc/rst/developer/implementation/compilerOverview/compilerOverview.pdf doc/rst/language/evolution.rst doc/rst/language/spec/records.rst doc/rst/usingchapel/prereqs.rst frontend/lib/parsing/bison-chpl-lib.cpp tools/chpldoc/arg-helpers.cpp tools/chpldoc/arg-helpers.h util/build_configs/cray-internal/setenv-xc-x86_64.bash util/devel/test/singularity/current/amazonlinux-2022-nollvm/singularity.def util/devel/test/singularity/current/amazonlinux-2022/singularity.def util/devel/test/vagrant/README-distro-timelines.txt util/devel/test/vagrant/provision-scripts/dnf-deps.sh util/devel/test/vagrant/provision-scripts/pacman-llvm.sh util/test/perf/perfgraph.js

Checked and these files does not need to be updated for copyright.

**Comment by bhavanijayakumaran** [comment]
Fixing the DCO sign-off issue.

**Pull request closed without merging**
