### PR TITLE
Updates to the CONTRIBUTORS file for Chapel 1.26.0

### PR DESCRIPTION
**Pull request by bradcray**
These are the contributors to Chapel 1.26.0.  Thanks to all!

### CODE REVIEW

**Comment by bradcray** [comment]
@tiger-yash, @XuehaiPan , @jlbyrne-hpe: Thanks for helping to improve Chapel!  As new contributors, would you check that I've spelled and alphabetized your names correctly?

@aconsroe-hpe , @tzinsky : Somehow, I failed to add your names in previous releases, to my chagrin—I'm sorry about that.  Would you do a similar spelling / alphabetization check?

@king11, @rchinmay, @Yudhishthira1406: Thanks for your contributions to Chapel 1.26.0!

**Comment by mppf** [comment]
Need to add Branch Vincent for PR #18857

**Comment by bradcray** [comment]
Thanks Michael!  For some reason, neither Branch nor John Byrne show up as contributors at https://github.com/chapel-lang/chapel/graphs/contributors?from=2021-09-27&to=2022-03-15&type=c  Can you think of anything you're doing in merging PRs that would cause that?  (Or are there privacy settings that would cause someone's contributions not to show up in that view?)

@branchvincent : Thanks for your contribution!  Would you double-check that I've spelled your name correctly?

**Comment by branchvincent** [comment]
Thanks for checking @bradcray, the spelling is correct!

**Comment by tiger-yash** [comment]
Yes the spelling is correct @bradcray. Thank you !

**Comment by mppf** [comment]
> Thanks Michael! For some reason, neither Branch nor John Byrne show up as contributors at https://github.com/chapel-lang/chapel/graphs/contributors?from=2021-09-27&to=2022-03-15&type=c Can you think of anything you're doing in merging PRs that would cause that? (Or are there privacy settings that would cause someone's contributions not to show up in that view?)

I don't know the answer. I did a usual merge and the commits from both are visible in our git history. (95da69f945c7097232d9ab110540c22f7129221d and a70bf57c6f1cb1a25b6a597a61bfbb14a7b9cc96). I guess it is something about GitHub / that web page.

**Pull request merged**
