### PR TITLE
dynamic() iter: coordinate via chunk index instead of chunk offset

### LINKED ISSUE #14617: Using the dynamic() iterator with a range whose element type is int(32) (or smaller) fails to compile
### Summary of Problem

```chapel
use DynamicIters;

type idxtype = int(32);

var end = max(idxtype) - 512;
var r = 0:idxtype .. end:idxtype;

forall i in dynamic(r, chunkSize=1<<30) { }
```

```
fortytwo@magrathea:~/src/chapel (master)$ chpl dynamic-idxtype.chpl 
$CHPL_HOME/modules/standard/DynamicIters.chpl:78: In iterator 'dynamic':
$CHPL_HOME/modules/standard/DynamicIters.chpl:109: error: unresolved call 'AtomicT(int(32)).fetchAdd(int(64))'
$CHPL_HOME/modules/internal/Atomics.chpl:545: note: this candidate did not match: AtomicT.fetchAdd(value: T, param order: memoryOrder = memoryOrder.seqCst) [46855]
$CHPL_HOME/modules/standard/DynamicIters.chpl:109: note: because call actual argument #1 with type int(64)
$CHPL_HOME/modules/internal/Atomics.chpl:545: note: is passed to formal 'value: int(32)'
$CHPL_HOME/modules/internal/NetworkAtomics.chpl:270: note: candidates are: RAtomicT.fetchAdd(value: T, param order: memoryOrder = memoryOrder.seqCst) [52425]
$CHPL_HOME/modules/internal/Atomics.chpl:802: note:                 AtomicT.fetchAdd(value: T, order: memory_order) [48636]
note: and 1 other candidates, use --print-all-candidates to see them
$CHPL_HOME/modules/standard/DynamicIters.chpl:109: note: unresolved call had id 1062174
dynamic-idxtype.chpl:8: Iterator 'dynamic' instantiated as: dynamic(param tag: iterKind = iterKind.leader, c: range(int(32),bounded,false))
```

**Associated Future Test(s):**

None yet

### Configuration Information

```
chpl version 1.21.0 pre-release (9cbea54)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

### LINKED ISSUE #14618: dynamic() iterator can iterate indefinitely
Given a suitable (but valid) selection of range and chunkSize, the
`dynamic()` iterator can wrap around and start over at the beginning a
large number of times.

```chapel
      while moreWork.read() {
        // There is local work in remain
        const low = curIndex.fetchAdd(chunkSize);
        var high = low + chunkSize-1;

        if low > remain.high {
          break;
        } else if high > remain.high {
          high = remain.high;
          moreWork.write(false);
	}
	...
```

If `curIndex` is less than `chunkSize` from exceeding `max(int)`, the
calculation of `high` will overflow and fail to trigger the stopping
condition.  It will continue and yield all the elements in the range
over and over.

```chapel
use DynamicIters;

var end = max(int) - 512;
var r = 0 .. end;

forall i in zip(dynamic(r, chunkSize=((1<<61) + 1024)), r) { }
```

```
chpl --fast -sdebugDynamicIters=true dynamic-lf-infinite.chpl 
```

(`--fast` to optimize out the loop body, debugging to show what's happening.)

This should result in four chunks, but it runs effectively
infinitely long.

```
Parallel dynamic Iterator. Working at tid 1 with range 0..2305843009213694975 yielded as 0..2305843009213694975
Parallel dynamic Iterator. Working at tid 0 with range 2305843009213694976..4611686018427389951 yielded as 2305843009213694976..4611686018427389951
Follower received range (0..2305843009213694975) ; shifting to 0..2305843009213694975
Follower received range (2305843009213694976..4611686018427389951) ; shifting to 2305843009213694976..4611686018427389951
Parallel dynamic Iterator. Working at tid 1 with range 4611686018427389952..6917529027641084927 yielded as 4611686018427389952..6917529027641084927
Parallel dynamic Iterator. Working at tid 0 with range 0..-6917529027641076737 yielded as 0..-6917529027641076737
Follower received range (4611686018427389952..6917529027641084927) ; shifting to 4611686018427389952..6917529027641084927
Follower received range (0..-6917529027641076737) ; shifting to 0..-6917529027641076737
Parallel dynamic Iterator. Working at tid 1 with range 0..-4611686018427381761 yielded as 0..-4611686018427381761
Parallel dynamic Iterator. Working at tid 0 with range 0..-2305843009213686785 yielded as 0..-2305843009213686785
Follower received range (0..-4611686018427381761) ; shifting to 0..-4611686018427381761
Follower received range (0..-2305843009213686785) ; shifting to 0..-2305843009213686785
Parallel dynamic Iterator. Working at tid 1 with range 0..8191 yielded as 0..8191
Parallel dynamic Iterator. Working at tid 0 with range 8192..2305843009213703167 yielded as 8192..2305843009213703167
Follower received range (0..8191) ; shifting to 0..8191
Follower received range (8192..2305843009213703167) ; shifting to 8192..2305843009213703167
Parallel dynamic Iterator. Working at tid 1 with range 2305843009213703168..4611686018427398143 yielded as 2305843009213703168..4611686018427398143
Parallel dynamic Iterator. Working at tid 0 with range 4611686018427398144..6917529027641093119 yielded as 4611686018427398144..6917529027641093119
Follower received range (2305843009213703168..4611686018427398143) ; shifting to 2305843009213703168..4611686018427398143
Follower received range (4611686018427398144..6917529027641093119) ; shifting to 4611686018427398144..6917529027641093119
Parallel dynamic Iterator. Working at tid 1 with range 0..-6917529027641068545 yielded as 0..-6917529027641068545
Parallel dynamic Iterator. Working at tid 0 with range 0..-4611686018427373569 yielded as 0..-4611686018427373569
Follower received range (0..-6917529027641068545) ; shifting to 0..-6917529027641068545
Follower received range (0..-4611686018427373569) ; shifting to 0..-4611686018427373569
Parallel dynamic Iterator. Working at tid 1 with range 0..-2305843009213678593 yielded as 0..-2305843009213678593
Parallel dynamic Iterator. Working at tid 0 with range 0..16383 yielded as 0..16383
Follower received range (0..-2305843009213678593) ; shifting to 0..-2305843009213678593
Follower received range (0..16383) ; shifting to 0..16383
Parallel dynamic Iterator. Working at tid 1 with range 16384..2305843009213711359 yielded as 16384..2305843009213711359
Parallel dynamic Iterator. Working at tid 0 with range 2305843009213711360..4611686018427406335 yielded as 2305843009213711360..4611686018427406335
Follower received range (16384..2305843009213711359) ; shifting to 16384..2305843009213711359
Follower received range (2305843009213711360..4611686018427406335) ; shifting to 2305843009213711360..4611686018427406335
Parallel dynamic Iterator. Working at tid 1 with range 4611686018427406336..6917529027641101311 yielded as 4611686018427406336..6917529027641101311
Parallel dynamic Iterator. Working at tid 0 with range 0..-6917529027641060353 yielded as 0..-6917529027641060353
Follower received range (4611686018427406336..6917529027641101311) ; shifting to 4611686018427406336..6917529027641101311
Follower received range (0..-6917529027641060353) ; shifting to 0..-6917529027641060353
Parallel dynamic Iterator. Working at tid 1 with range 0..-4611686018427365377 yielded as 0..-4611686018427365377
Parallel dynamic Iterator. Working at tid 0 with range 0..-2305843009213670401 yielded as 0..-2305843009213670401
Follower received range (0..-4611686018427365377) ; shifting to 0..-4611686018427365377
Follower received range (0..-2305843009213670401) ; shifting to 0..-2305843009213670401
Parallel dynamic Iterator. Working at tid 1 with range 0..24575 yielded as 0..24575
Parallel dynamic Iterator. Working at tid 0 with range 24576..2305843009213719551 yielded as 24576..2305843009213719551
Follower received range (0..24575) ; shifting to 0..24575
Follower received range (24576..2305843009213719551) ; shifting to 24576..2305843009213719551
Parallel dynamic Iterator. Working at tid 1 with range 2305843009213719552..4611686018427414527 yielded as 2305843009213719552..4611686018427414527
Parallel dynamic Iterator. Working at tid 0 with range 4611686018427414528..6917529027641109503 yielded as 4611686018427414528..6917529027641109503
Follower received range (2305843009213719552..4611686018427414527) ; shifting to 2305843009213719552..4611686018427414527
Follower received range (4611686018427414528..6917529027641109503) ; shifting to 4611686018427414528..6917529027641109503
Parallel dynamic Iterator. Working at tid 1 with range 0..-6917529027641052161 yielded as 0..-6917529027641052161
Parallel dynamic Iterator. Working at tid 0 with range 0..-4611686018427357185 yielded as 0..-4611686018427357185
Follower received range (0..-6917529027641052161) ; shifting to 0..-6917529027641052161
Follower received range (0..-4611686018427357185) ; shifting to 0..-4611686018427357185
Parallel dynamic Iterator. Working at tid 1 with range 0..-2305843009213662209 yielded as 0..-2305843009213662209
Parallel dynamic Iterator. Working at tid 0 with range 0..32767 yielded as 0..32767
Follower received range (0..-2305843009213662209) ; shifting to 0..-2305843009213662209
Follower received range (0..32767) ; shifting to 0..32767
...
```

This is probably academic at the moment -- as far as I can tell, it
requires that the range be within a few orders of magnitude of
`0..max(int)` depending on the chunk size, so any non-trivial loop
body will keep it from getting to the end.  (The `densify()` step
rebases the indices used in the calculations to start at 0, so a range
of `max(int) - 100 .. max(int) - 50` won't hit it.)

But when #14617 is fixed, a range of `int(32)` or
`int(16)` could hit the same thing at reasonable scales.

**Associated Future Test(s):**

None yet

### Configuration Information

```
chpl version 1.21.0 pre-release (9cbea54)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

### PR DESCRIPTION
**Pull request by cassella**
This avoids overflowing both the calculation of high and the state
of curIndex when the end of the range is within chunkSize of the
max of the index type.

There's no reason to adjust high down to remain.high, since we're
about to apply range intersection with remain.  This lets high be
const.

low will always be <= high at the end of the loop body so no need
to test it any more.

Resolves #14618
Coincidentally resolves #14617

Tested with the tests in those bugs, the dynamic-strided test in #14614,
and a random assortment of tests that `use DynamicIters`.

### CODE REVIEW

**Comment by cassella** [comment]
`curChunkIdx` won't overflow until there are about 2^62 chunks.  Should be enough for anyone.

**Comment by cassella** [comment]
It seems like there should be a better way to interact with `divceilpos()` / `divceil()` than this, but I haven't thought of it yet.

**Comment by cassella** [comment]
@bradcray These are the other tests I had in mind, so I think this is ready for review now.

I'm not entirely confident in the 5-second timeout for one of them, described in the commit and .timeout file.  The test takes 17 seconds to compile on my laptop, so there's not a lot of slack for a slow compile hitting the consequent 20-second compilation timeout.

I haven't attempted to measure whether this affects the performance of the dynamic iterator generally.

**Comment by cassella** [comment]
For the purpose of evaluating the testing, I was able to tweak the current version of `DynamicIters` so that a signed `int(8)` version of the dynamic-uint8-overflow test added by this PR exhibits the problem.

I had to force `dynamic()` to accept `chunkSize` as `int(8)` so the `fetchAdd()` would resolve,

```diff
--- a/modules/standard/DynamicIters.chpl
+++ b/modules/standard/DynamicIters.chpl
@@ -65,7 +65,7 @@ config param debugDynamicIters:bool=false;
   This iterator can be called in serial and zippered contexts.
 
 */
-iter dynamic(c:range(?), chunkSize:int=1, numTasks:int=0) {
+iter dynamic(c:range(?), chunkSize:int(8)=1, numTasks:int=0) {
 
   if debugDynamicIters then
     writeln("Serial dynamic Iterator. Working with range ", c);
@@ -75,7 +75,7 @@ iter dynamic(c:range(?), chunkSize:int=1, numTasks:int=0) {
 
 // Parallel iterator
 pragma "no doc"
-iter dynamic(param tag:iterKind, c:range(?), chunkSize:int=1, numTasks:int=0)
+iter dynamic(param tag:iterKind, c:range(?), chunkSize:int(8)=1, numTasks:int=0)
 where tag == iterKind.leader
 {
   assert(chunkSize > 0); // caller's responsibility
@@ -130,7 +130,7 @@ where tag == iterKind.leader
 
 // Follower
 pragma "no doc"
-iter dynamic(param tag:iterKind, c:range(?), chunkSize:int=1, numTasks:int, followThis)
+iter dynamic(param tag:iterKind, c:range(?), chunkSize:int(8)=1, numTasks:int, followThis)
 where tag == iterKind.follower
 {
   type rType=c.type;
```

And modify the range/chunkSize in the test for `int(8)`, and to pass chunkSize specifically as `int(8)`,

```diff
--- dynamic-uint8-overflow.chpl 2020-01-13 19:54:59.170062465 -0800
+++ dynamic-int8-overflow.chpl  2020-01-13 20:05:37.808252923 -0800
@@ -16,22 +16,24 @@
 
 use DynamicIters;
 
-// end == 255 - 16
-var r = 0:uint(8) .. 239:uint(8);
+// end == 127 - 8
+var r = 0:int(8) .. 119:int(8);
 
-// desired chunks 0-37, 38-75, 76-113, 114-151, 152-189, 190-227, 228-239
-// noting 228 + 38 == 266 > max(uint(8))
+// desired chunks 0-18, 19-37, 38-56, 57-76, 77-96, 97-116
+// noting 117 + 19 == 136 > max(int(8))
 
 var A: [r] atomic int;
 
-for i in dynamic(r, chunkSize=38) { A[i].add(1); }
+config var chunkSize:int(8) = 19;
+
+for i in dynamic(r, chunkSize=chunkSize) { A[i].add(1); }
 writeln(A);
 
-forall i in dynamic(r, chunkSize=38) { A[i].add(1); }
+forall i in dynamic(r, chunkSize=chunkSize) { A[i].add(1); }
 writeln(A);
 
-forall (i,j) in zip(dynamic(r, chunkSize=38), r) { A[i].add(1); }
+forall (i,j) in zip(dynamic(r, chunkSize=chunkSize), r) { A[i].add(1); }
 writeln(A);
 
-forall (i,j) in zip(r, dynamic(r, chunkSize=38)) { A[j].add(1); }
+forall (i,j) in zip(r, dynamic(r, chunkSize=chunkSize)) { A[j].add(1); }
 writeln(A);
```

Which produces the output

```
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 3 3 3 3 3 3
6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 4 4 4 4 4 4
```

The first line is the serial `for` loop, no problems.

In each of the parallel loops, the first 114 elements were yielded twice, resulting in their elements being incremented by 2 instead of 1.  (The second time through, the iteration terminated normally.)  The last 6 elements were yielded only once in each loop.


So maybe the dynamic-uint8-overflow test may be enough, and the complicated dynamic-int-overflow test could be dropped?

**Comment by cassella** [comment]
Rebased to master, adjusted for `length` -> `size`, and changed one of the inits to split-init.

I had to bump up the timeout of the questionable test due to a compilation timeout.  I'm leaning towards just removing it and leaving that int(8)-based one instead of the original failing case.

@bradcray Let me know what you think.  I think it's ready for review, with or without that.

**Comment by cassella** [comment]
Ok, you convinced me.  I removed the dynamic-int-overflow test.  The dynamic-uint8-overflow test will cover the original problem.  The dynamic-int-overflow one didn't add any value over the uint8 one.

**Comment by bradcray** [comment]
> It seems like there should be a better way to interact with divceilpos() / divceil() than this, but I haven't thought of it yet.

I found myself wondering if we should provide a different routine / overload that could handle the various cases you were working around itself rather than forcing you to do it.

**Comment by bradcray** [comment]
@cassella: I finally got all the way back to this PR today.  Did you think that the failure mode of #14617 was squirrely enough not to warrant adding as a test?  (or is it subsumed by the new tests you added in this PR?

**Comment by cassella** [comment]
@bradcray The `dynamic-elttype.chpl` and `dynamic-uint8-overflow.chpl` tests cover that issue.

**Comment by cassella** [comment]
`divceil()`/`divceilpos()`: Sounds good.  I only figured out how to make those functions work, and didn't try to figure out what motivated their design that way, and if anything could be changed without causing problems.

**Pull request merged**
