### PR TITLE
Minor improvements to `greptests`

### PR DESCRIPTION
**Pull request by vasslitvinov**
This is a followup to #17546:

* rename the option `-help` to `--help` as more conventional
* allow passing multiple options to grep
* minor code restructuring to improve readability

A potential usability improvement is to switch the file-type argument style from `-t tests` / `-t futures` etc. to `-tests` / `-futures` etc.

Testing: I ran it with various options on my local tree and ensured the output is reasonable.

### CODE REVIEW

**Review by lydia-duncan — COMMENTED** [review]
I think using `--help` is a strict improvement.  I probably won't use multiple search strings for a single command, but I can see why it would be helpful so am not against it.

Please enumerate the test modes you tried and a general description of their results - since this is not something run through our test system, I want to be certain you tested appropriately.  I approve of the code, but I would like to see this description before you merge

**Comment by vasslitvinov** [comment]
Here are some of the commands I tested:

<details>
<summary>util/devel/greptests</summary>

```
No arguments supplied, see --help
```
</details>
<details>
<summary>util/devel/greptests --help</summary>

```
Usage: greptests [-t type] pattern...
-t type - the file types to search (the default is tests):
    tests - .chpl
    futures - .future
    perfgraphs - .perfkeys, .graph
    testenv - .execenv, EXECENV, .skipif, SKIPIF, .suppressif, .perfexecenv, PERFEXECENV
    testopts - .compopts, COMPOPTS, .execopts, EXECOPTS, .perfcompopts, PERFCOMPOPTS, .perfexecopts, PERFEXECOPTS
    outputs - .good, .bad
    scripts - .prediff, PREDIFF, .precomp, PRECOMP, .preexec, PREEXEC
pattern - the text to search and other options to pass to grep
```
</details>
<details>
<summary>util/devel/greptests vass</summary>

```
test/parallel/taskPar/vass/field-in-task-ref-clause.chpl://  parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:// see also parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:  // forall testing moved to parallel/forall/vass
test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-4.chpl:  parallel/forall/vass/reduce-with-forall-in-par-iter
... etc ...

```
</details>
<details>
<summary>util/devel/greptests -i vass</summary>

```
test/parallel/begin/vass/multi-yield-leader.chpl:// viter (Vass's iter): a leader with multiple yields
test/parallel/taskPar/sungeun/barrier/commDiags.chpl:  /* Vass 9/5/17: instead of b.wait(), we used to have the code below in this
test/parallel/taskPar/vass/field-in-task-ref-clause.chpl://  parallel/forall/vass/errorFieldMethodInWithClause.chpl
... etc ...

```
</details>
<details>
<summary>util/devel/greptests vasss</summary>

```
grep: test/compflags/bradc/dir.chpl: Is a directory

```
</details>
<details>
<summary>util/devel/greptests -t test vass</summary>

```
File type 'test' is not recognized, see --help

```
</details>
<details>
<summary>util/devel/greptests -t test -i vass</summary>

```
File type 'test' is not recognized, see --help

```
</details>
<details>
<summary>util/devel/greptests -t testss</summary>

```
File type 'testss' is not recognized, see --help

```
</details>
<details>
<summary>util/devel/greptests -t tests</summary>

```
No search term supplied, see --help

```
</details>
<details>
<summary>util/devel/greptests -t futures</summary>

```
No search term supplied, see --help

```
</details>
<details>
<summary>util/devel/greptests -t perfgraphs</summary>

```
No search term supplied, see --help

```
</details>
<details>
<summary>util/devel/greptests -t testenv</summary>

```
No search term supplied, see --help

```
</details>
<details>
<summary>util/devel/greptests -t testopts</summary>

```
No search term supplied, see --help

```
</details>
<details>
<summary>util/devel/greptests -t outputs</summary>

```
No search term supplied, see --help

```
</details>
<details>
<summary>util/devel/greptests -t scripts</summary>

```
No search term supplied, see --help

```
</details>
<details>
<summary>util/devel/greptests -t tests vass</summary>

```
test/parallel/taskPar/vass/field-in-task-ref-clause.chpl://  parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:// see also parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:  // forall testing moved to parallel/forall/vass
... etc ...

```
</details>
<details>
<summary>util/devel/greptests -t tests -i vass</summary>

```
test/parallel/begin/vass/multi-yield-leader.chpl:// viter (Vass's iter): a leader with multiple yields
test/parallel/taskPar/sungeun/barrier/commDiags.chpl:  /* Vass 9/5/17: instead of b.wait(), we used to have the code below in this
test/parallel/taskPar/vass/field-in-task-ref-clause.chpl://  parallel/forall/vass/errorFieldMethodInWithClause.chpl
... etc ...

```
</details>
<details>
<summary>util/devel/greptests -t futures vass</summary>

```
test/types/tuple/vass/tuple-expansion-with-parens-1.future: functions/vass/return-of-tuple-expansion-*
test/domains/vass/domain-arg-query-expr.future:  $CHPL_HOME/test/functions/vass/domain-arg-query-expr.chpl:1: error: 'chpl__buildDomainRuntimeType' undeclared (first use this function) [normalize.cpp:79]
test/domains/vass/domain-arg-query-expr.future:  $CHPL_HOME/test/functions/vass/domain-arg-query-expr.chpl:2: error: 'chpl__buildSubDomainType' undeclared (first use this function) [normalize.cpp:79]
test/classes/vass/propagateConstnessOfVariableToFields.future://see also: types/records/vass/constnessOfThisInMethods.future
test/functions/promotion/theseShouldPromote2.future:  test/functions/iterators/vass/forall-without-leaderfollower.chpl
test/functions/vass/closure-outlives-captured-vars.future:In file included from /tmp/chpl-vass-3018.deleteme/_main.c:1:
test/functions/vass/closure-outlives-captured-vars.future:/tmp/chpl-vass-3018.deleteme/chpl__header.h:779: error: conflicting types for ‘chpl_main’
test/functions/vass/closure-outlives-captured-vars.future:/users/vass/chapel/runtime/include/chplcgfns.h:15: error: previous declaration of ‘chpl_main’ was here
test/functions/vass/closure-outlives-captured-vars.future:In file included from /tmp/chpl-vass-3018.deleteme/_main.c:22:
test/functions/vass/closure-outlives-captured-vars.future:/tmp/chpl-vass-3018.deleteme/closure-outlives-captured-vars.c:115: error: conflicting types for ‘chpl_main’
test/functions/vass/closure-outlives-captured-vars.future:/users/vass/chapel/runtime/include/chplcgfns.h:15: error: previous declaration of ‘chpl_main’ was here
test/functions/vass/return-of-tuple-expansion-2.future:  types/tuple/vass/tuple-expansion-with-parens-*

```
</details>
<details>
<summary>util/devel/greptests -t futures -n vass</summary>

```
test/types/tuple/vass/tuple-expansion-with-parens-1.future:7: functions/vass/return-of-tuple-expansion-*
test/domains/vass/domain-arg-query-expr.future:5:  $CHPL_HOME/test/functions/vass/domain-arg-query-expr.chpl:1: error: 'chpl__buildDomainRuntimeType' undeclared (first use this function) [normalize.cpp:79]
test/domains/vass/domain-arg-query-expr.future:6:  $CHPL_HOME/test/functions/vass/domain-arg-query-expr.chpl:2: error: 'chpl__buildSubDomainType' undeclared (first use this function) [normalize.cpp:79]
test/classes/vass/propagateConstnessOfVariableToFields.future:3://see also: types/records/vass/constnessOfThisInMethods.future
test/functions/promotion/theseShouldPromote2.future:7:  test/functions/iterators/vass/forall-without-leaderfollower.chpl
test/functions/vass/closure-outlives-captured-vars.future:5:In file included from /tmp/chpl-vass-3018.deleteme/_main.c:1:
test/functions/vass/closure-outlives-captured-vars.future:6:/tmp/chpl-vass-3018.deleteme/chpl__header.h:779: error: conflicting types for ‘chpl_main’
test/functions/vass/closure-outlives-captured-vars.future:7:/users/vass/chapel/runtime/include/chplcgfns.h:15: error: previous declaration of ‘chpl_main’ was here
test/functions/vass/closure-outlives-captured-vars.future:8:In file included from /tmp/chpl-vass-3018.deleteme/_main.c:22:
test/functions/vass/closure-outlives-captured-vars.future:9:/tmp/chpl-vass-3018.deleteme/closure-outlives-captured-vars.c:115: error: conflicting types for ‘chpl_main’
test/functions/vass/closure-outlives-captured-vars.future:10:/users/vass/chapel/runtime/include/chplcgfns.h:15: error: previous declaration of ‘chpl_main’ was here
test/functions/vass/return-of-tuple-expansion-2.future:7:  types/tuple/vass/tuple-expansion-with-parens-*

```
</details>
<details>
<summary>util/devel/greptests -t perfgraphs hpl</summary>

```
test/parallel/taskCompare/elliot/taskSpawn.graph:graphkeys: forall, coforall, for+begin, omp parallel-for, chpl-like qthreads, chpl-opt qthreads
test/parallel/taskCompare/elliot/taskSpawn.graph:files: empty-forall.dat, empty-coforall.dat, empty-for+begin.dat, empty-omp-parallel-for.dat, empty-qthreads-chpl-like.dat, empty-qthreads-chpl-opt.dat
test/parallel/taskCompare/elliot/serialTaskSpawn.graph:graphkeys: serialized forall, serialized coforall, serialized for+begin, serialized omp parallel-for, serialized chpl-like qthreads, serialized chpl-opt qthreads
... etc ...

```
</details>
<details>
<summary>util/devel/greptests -t perfgraphs -w hpl</summary>

```
test/release/examples/benchmarks/hpcc/hpl.ml-perf.graph:files: hpl-255.32.dat
test/release/examples/benchmarks/hpcc/hpl.ml-perf.graph:graphkeys: hpl Gflop/s
test/release/examples/benchmarks/hpcc/hpl_performance.graph:graphkeys: hpl
test/release/examples/benchmarks/hpcc/hpl_performance.graph:files: hpl.dat
test/release/examples/benchmarks/hpcc/hpl_performance.graph:graphname: hpcc-hpl-gf
test/release/examples/benchmarks/hpcc/hpl.graph:graphkeys: hpl, hpl MAX_LOGICAL
test/release/examples/benchmarks/hpcc/hpl.graph:files: hpl.dat, hplMaxLogical.dat
test/release/examples/benchmarks/hpcc/hpl.graph:graphname: hpl
test/release/examples/benchmarks/hpcc/hpl.ml-time.graph:files: hpl-255.32.dat
test/release/examples/benchmarks/hpcc/hpl.ml-time.graph:graphkeys: hpl runtime

```
</details>
<details>
<summary>util/devel/greptests -t testenv diag</summary>

```
test/parallel/forall/vass/performance/promo-value-unused--arrays.skipif:# It may print different debugDataPar diagnostics under NUMA.

```
</details>
<details>
<summary>util/devel/greptests -t testenv -e -fast</summary>

```
test/parallel/cobegin/gbt/cobegin-stacksize.skipif:# amount, but it ends up succeeding with --fast because the stack sizes with
test/parallel/cobegin/gbt/cobegin-stacksize.skipif:# --fast are really small.
test/parallel/cobegin/gbt/cobegin-stacksize.skipif:COMPOPTS <= --fast
... etc ...

```
</details>
<details>
<summary>util/devel/greptests -t testopts diag</summary>

```
test/performance/array/distCreate.execopts:--mode=diagMode.correctness

```
</details>
<details>
<summary>util/devel/greptests -t testopts -e -fast</summary>

```
test/parallel/taskPar/vass/ri-3-stress-coforall.compopts:--fast
test/parallel/forall/reduce-intents/ri-4-arrdom.compopts:--fast
test/parallel/forall/reduce-intents/ri-3-stress.compopts:--fast
test/parallel/forall/reduce-intents/ri-4-arrdom.replicated.compopts:--fast -s distType=DistType.replicated
... etc ...

```
</details>
<details>
<summary>util/devel/greptests -t outputs VASS</summary>

This command produces no output.
</details>
<details>
<summary>util/devel/greptests -t outputs -i VASS</summary>

```
test/parallel/forall/checks/const-indices-vass.good:const-indices-vass.chpl:31: error: const actual is passed to 'ref' formal 'obj' of mutate()
test/parallel/forall/checks/const-indices-vass.good:const-indices-vass.chpl:34: error: const actual is passed to 'ref' formal 'obj' of mutate()
test/parallel/forall/checks/const-indices-vass.good:const-indices-vass.chpl:37: error: const actual is passed to 'ref' formal 'obj' of mutate()
... etc ...

```
</details>
<details>
<summary>util/devel/greptests -t scripts cuda</summary>

```
test/gpu/native/llvmIntrinsicAttributes/llvmIntrinsicAttributes.precomp:clang -S -emit-llvm llvmIntrinsicAttributes.cu --cuda-gpu-arch=sm_60 -L/global/opt/nvidia/cuda-11.0/lib64/ -lcudart_static -pthread
test/gpu/native/llvmIntrinsicAttributes/llvmIntrinsicAttributes.precomp:CLANG_IR_DUMP_FILE="llvmIntrinsicAttributes-cuda-nvptx64-nvidia-cuda-sm_60.ll"

```
</details>
<details>
<summary>util/devel/greptests -t scripts -i cuda</summary>

```
test/gpu/native/PREDIFF:awk '!/Unknown CUDA version/ {print};' $2 > $2.no_version_warn
test/gpu/native/llvmIntrinsicAttributes/llvmIntrinsicAttributes.precomp:clang -S -emit-llvm llvmIntrinsicAttributes.cu --cuda-gpu-arch=sm_60 -L/global/opt/nvidia/cuda-11.0/lib64/ -lcudart_static -pthread
test/gpu/native/llvmIntrinsicAttributes/llvmIntrinsicAttributes.precomp:# a thread ID from the CUDA kernel.  I'm locking down that this intrinsic has
test/gpu/native/llvmIntrinsicAttributes/llvmIntrinsicAttributes.precomp:CLANG_IR_DUMP_FILE="llvmIntrinsicAttributes-cuda-nvptx64-nvidia-cuda-sm_60.ll"
test/gpu/native/memory/PREDIFF:awk '!/Unknown CUDA version/ {print};' $2 > $2.no_version_warn
test/gpu/native/streamPrototype/PREDIFF:awk '!/Unknown CUDA version/ {print};' $2 > $2.no_version_warn
test/gpu/native/distArray/PREDIFF:awk '!/Unknown CUDA version/ {print};' $2 > $2.no_version_warn
test/gpu/native/jacobi/PREDIFF:awk '!/Unknown CUDA version/ {print};' $2 > $2.no_version_warn
test/gpu/native/gpuAddNums/PREDIFF:awk '!/Unknown CUDA version/ {print};' $2 > $2.no_version_warn

```
</details>

@lydia-duncan please let me know how this looks to you.

**Comment by lydia-duncan** [comment]
Nice, those are good cases to check.  Here's a couple more that had occurred to me just based on reading the file earlier
- util/devel/greptests -t tests "vass"
- util/devel/greptests -t tests "vass" "error"
- util/devel/greptests -t tests vass error
- util/devel/greptests -t tests -t testenv

**Comment by vasslitvinov** [comment]
Good suggestions. Here are the outputs:
<details>
<summary>$CHPL_HOME/util/devel/greptests -t tests "vass"</summary>

```
test/parallel/taskPar/vass/field-in-task-ref-clause.chpl://  parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:// see also parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:  // forall testing moved to parallel/forall/vass
... etc ...
```
</details>
<details>
<summary>$CHPL_HOME/util/devel/greptests -t tests "vass" "error"</summary>

```
grep: error: No such file or directory        # repeats several times in the output
test/parallel/taskPar/vass/field-in-task-ref-clause.chpl://  parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:// see also parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:  // forall testing moved to parallel/forall/vass
... etc ...
```
</details>
<details>
<summary>$CHPL_HOME/util/devel/greptests -t tests vass error</summary>

```
grep: error: No such file or directory        # repeats several times in the output
test/parallel/taskPar/vass/field-in-task-ref-clause.chpl://  parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:// see also parallel/forall/vass/errorFieldMethodInWithClause.chpl
test/parallel/taskPar/vass/errorFieldMethodInWithClause.chpl:  // forall testing moved to parallel/forall/vass
... etc ...
```
</details>
<details>
<summary>$CHPL_HOME/util/devel/greptests -t tests -t testenv</summary>

```
grep: invalid option -- t
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
grep: invalid option -- t
```
The above repeats several times. Yes, I am using BSD grep.
</details>

**Comment by lydia-duncan** [comment]
So the result of the middle two implies that this only works when "multiple patterns" is actually "one or more flags for grep and a pattern", right?  Do you get the same results for your earlier tests if you just surround the "patterns" in quotes?  (I'm not getting the same output, but that's probably due to not using the same grep and what matters is that it works in the grep it is getting passed to.)

I think the output for the last one I suggested is slightly worse than it was before (though the earlier output does not actually describe the issue either).  Do you agree?

Between the two points above, we're not accomplishing what the new `--help` output describes and making the response to a failure mode less clear.   So I think we have two options here:
1. Update the `--help` description of the greptests command to not imply you can pass multiple patterns and to instead describe what it's supporting (I'm having trouble coming up with something reasonable, but will let you know if I think of something)
1a. As a bonus, maybe add a check that looks for trying to search multiple categories and for now tells the user they can't do that? 
2. Back out the "multiple options" change so that the only thing in this PR is the `--help` change and maybe the minor restructuring, and have you use quotations around your options (assuming that works).

**Comment by vasslitvinov** [comment]
The way `greptests` worked before is that it passed all its options through to `grep`. I would like it to continue doing so, modulo the initial `-t` argument. This is the main point of this PR. Without which currently I cannot pass multiple args to grep. Regarding a check for multiple categories, it is beyond the scope of this PR. We can do without it.

So I propose to change the help text by replacing "pattern" with "patternOrOption":
```
Usage: greptests [-t type] patternOrOption...
-t type - the file types to search (the default is tests):
    tests - .chpl
    futures - .future
    perfgraphs - .perfkeys, .graph
    testenv - .execenv, EXECENV, .skipif, SKIPIF, .suppressif, .perfexecenv, PERFEXECENV
    testopts - .compopts, COMPOPTS, .execopts, EXECOPTS, .perfcompopts, PERFCOMPOPTS, .perfexecopts, PERFEXECOPTS
    outputs - .good, .bad
    scripts - .prediff, PREDIFF, .precomp, PRECOMP, .preexec, PREEXEC
patternOrOption - the text to search and other options to pass to grep
```

**Comment by lydia-duncan** [comment]
> Regarding a check for multiple categories, it is beyond the scope of this PR

The adjustments in this PR modified its behavior.  If we want it to be beyond the scope of this PR, we need to not modify its behavior in this PR or at the very least we need to not make it worse.

It sounds like the quotes suggestion did not work?  Maybe there's other ways to solve this problem.  We could add a "grepFlags" arg?  That'd sidestep the "patterns" issue by leaving the basic use case unchanged and it would avoid changing the behavior for that incorrect use case.

I recognize that it would mean additional work, but I think it would leave the feature in a better place.  I'm also open to other ideas.

**Comment by vasslitvinov** [comment]
@lydia-duncan What would you like the user-facing behavior of this script be?

#17546 disabled the ability to pass multiple args to grep naturally. I am restoring it here. I don't think it should require passing `--grepFlags`.

**Comment by lydia-duncan** [comment]
Oh no!  You didn't mention it was restoring functionality from the old arrangement in the PR, sorry for not noticing it was lost at the time (man I wish we could test these features nightly - I did say it's not a feature I thought I'd used but if we'd had a test we would have noticed and made sure it was maintained).

> What would you like the user-facing behavior of this script be?

I mean, I'd like it to be useful to you?  The PR description initially made me think it was providing something like the fourth case I mentioned, which is why it occurred to me to have you test it and see what happened - I think it'd be cool for that to be an option but I'm not asking you to implement it or anything because I know that's outside the scope of the feature.  I think it would be easy to initially try it from this PR's description, so that's why I care about the output in that case.  The second and third cases are also motivated by originally misunderstanding what you were trying to add.

**Comment by vasslitvinov** [comment]
Quoted arguments to `greptests` now work the same way they do for `grep`:

<details>
<summary>util/devel/greptests "                                                                                         " # 89 spaces in quotes</summary>

```
test/studies/comd/elegant/arrayOfStructs/CoMD.chpl:  writeln("#                                                                                         Performance");
test/studies/comd/llnl/CoMD.chpl:  writeln("#                                                                                         Performance");
grep: test/compflags/bradc/dir.chpl: Is a directory
```
</details>
<details>
<summary>util/devel/greptests -t tests "                                                                                         " # 89 spaces in quotes</summary>

```
test/studies/comd/elegant/arrayOfStructs/CoMD.chpl:  writeln("#                                                                                         Performance");
test/studies/comd/llnl/CoMD.chpl:  writeln("#                                                                                         Performance");
grep: test/compflags/bradc/dir.chpl: Is a directory
```
</details>
<details>
<summary>util/devel/greptests "vass 9"</summary>

```
grep: test/compflags/bradc/dir.chpl: Is a directory
```
</details>
<details>
<summary>util/devel/greptests -t tests "vass 9"</summary>

```
grep: test/compflags/bradc/dir.chpl: Is a directory
```
</details>
<details>
<summary>util/devel/greptests -i "vass 9"</summary>

```
test/parallel/taskPar/sungeun/barrier/commDiags.chpl:  /* Vass 9/5/17: instead of b.wait(), we used to have the code below in this
grep: test/compflags/bradc/dir.chpl: Is a directory
```
</details>
<details>
<summary>util/devel/greptests -t tests -i "vass 9"</summary>

```
test/parallel/taskPar/sungeun/barrier/commDiags.chpl:  /* Vass 9/5/17: instead of b.wait(), we used to have the code below in this
grep: test/compflags/bradc/dir.chpl: Is a directory
```
</details>

**Comment by vasslitvinov** [comment]
@lydia-duncan how does my latest commit address your feedback?

**Review by lydia-duncan — APPROVED** [review]
Sweet, thanks!

**Pull request merged**
