### PR TITLE
Fix a clang warning in generated code

### PR DESCRIPTION
**Pull request by bradcray**
David pointed out that commit 88e5b21d00124aa236c908c224348b532e232d74
introduced a warning in Chapel-generated code for programs as simple
as test/release/examples/hello4-datapar-dist.chpl.  Specifically,
'chpl' generated a version of dsiReallocate() that would call itself
unconditionally for the 'else' branch of dsiReallocate() in
DefaultRectangular.chpl.  This seems to have been due to the way I
was testing to see whether the 'd' argument was defaultrectangular
or not, by comparing its type to 'dom's type.

In this commit, I take a different approach that I thought about but
didn't pursue originally, which is to query more directly whether the
domain was a default rectangular.  We haven't supported such a query
in the past (and I don't think it can be done via a simple type
comparison since DefaultRectangular is generic), so here, I add the
same type of query that we already support on the
DefaultRectangularArr class by adding a param method to BaseDom and
DefaultRectangularDom indicating whether or not it's a default
rectangular.  While this is somewhat of a special case (i.e., we
wouldn't want to do it for all layouts and distributions), default
rectangulars are pretty special semantically, so it seems justifiable
(and I've found myself wanting it in other cases where I was
disappointed to find that only the arrays support such a query).

### CODE REVIEW

**Comment by bradcray** [comment]
@daviditen (and @ronawho ):  This should fix the warning you're seeing, though I still need to run it through testing.

**Comment by ronawho** [comment]
:+1:

**Comment by bradcray** [comment]
Surprisingly, I just did a check of the generated code size using wc -l, thinking that it might be shorter with this fix (i.e., presumably I eliminated an infinitely recursive routine that we never called).  However, it seems to have gotten bigger (though I was somewhat sloppy in my analysis)... :(

**Comment by bradcray** [comment]
Hmm, failing some testing too...  :( stay tuned.

**Comment by daviditen** [comment]
I was about to comment here after my PR #3703 Travis-ci builds passed, but I'm a bit late since you already commented there.  I'll put this here anyway:

I was not sure how to get into the generated function with the infinite recursion, so I created a test case.  I'm about to merge test/domains/diten/domainReassignChangeStridedness.chpl which currently runs into the infinite recursion.  With your fix here, it hits a runtime 'halt' (better!).  I think it should ideally get a compiler error similar to what happens with rank mismatch or idxType mismatch.

**Comment by panzone** [comment]
I'm testing Chapel on OSX 10.11.4 and, when testing release/examples/hello4-datapar-dist, I got this error:

DefaultRectangular.c:2950:140: error: all paths through this function will call itself [-Werror,-Winfinite-recursion]

With this PR I've resolved this kind of problem, however some tests now fails with different errors. For example, running release/examples/primers/learnChapelInYMinutes.chpl:

$CHPL_HOME/modules/internal/DefaultRectangular.chpl:1039: In function 'dsiReallocate':
$CHPL_HOME/modules/internal/DefaultRectangular.chpl:1046: error: unresolved call 'DefaultRectangularArr(eltType=type real(64), rank=2, idxType=type int(64), stridable=0, dom=domain(1,int(64),false))'
$CHPL_HOME/modules/internal/DefaultRectangular.chpl:630: note: candidates are: DefaultRectangularArr(_arrCnt: atomic_refcnt, _arrAlias: BaseArr, type eltType, param rank: int(64), type idxType, param stridable: bool, dom, off, blk, str, origin: idxType, factoredOffs: idxType, data, shiftedData, noinit_data: bool, dataAllocRange)

**Comment by bradcray** [comment]
Hi @panzone -- Yes, this new class of error that you report on is the reason that this PR hasn't been merged yet -- it didn't pass testing for this reason (and unfortunately, I haven't been able to get back to it to finish it up yet.  Hopefully by the end of this week).  I believe that if working from master and CHPL_DEVELOPER is unset or if you compile with --no-cc-warnings, you should be able to work around this issue.  Please let me know if this is not the case.

**Comment by bradcray** [comment]
At this point, all tests are passing (for single-locale testing) other than test/distributions/kushal/assignDomain.chpl which is the test that put the original breaking code in there... sigh.  The core of the problem relates to the fact that dsiReallocate() is one of the few routines we use dynamic dispatch for in the dsi interface because we're iterating over all of a domain's arrays when making the call, and that list of arrays is stored in the base class, so is of the abstract base array class type.  It seems that our dynamic dispatch tries to resolve call chains that won't exist in the program and this leads to unresolved calls (because they weren't meant to be supported).  My current attempt to simply put in runtime checks for such type mismatches helps, but runs into problems when using distributions defined by modules that aren't 'use'd in this context because their generic routines are not visible...

My current thinking is, now that we can inherit from generics, maybe the rank and idxType fields could be pushed into the abstract Base* classes to avoid having to redefine them in every subclass using the same name and to support such queries in a more abstract way.

My other thought was to tighten up the dsiReallocate() interface to make it require a DefaultRectangular domain of matching rank and idxType (because in practice, that's all we ever pass in of interest), but this can't be prototyped in the BaseArr class because we don't have access to those fields (which the aforementioned change would also fix).

I'm going to stew on this a bit more before taking further action to see if other ideas occur to me first.

**Pull request closed without merging**
