### PR TITLE
In comm=ofi, adjust for the "tcp" provider.

### PR DESCRIPTION
**Pull request by gbtitus**
There are a variety of changes here, which taken together allow full
testing to pass (no functional failures) with the "tcp" provider.

We still get timeouts on about a dozen tests.  Which ones and how many
varies, but `distributions/bradc/assoc/userAssoc-domain-stress.chpl` is
usually in the mix, for example.  This will be addressed separately.

The specific changes are documented in each commit, but here are the
high points:
- The "ofi_rxm" utility provider which adds RDM (reliable datagram)
  support to the tcp provider does dynamic endpoint connection and this
  can cause `FI_EAGAIN` returns during the initial communication with each
  remote.  The caller needs to ride these out; we do so here.
- Reorganize provider-sensitive settings and logic, which was kind of
  spread all over even though there wasn't much of it yet.
- Adapt to a couple of quirks in "tcp;ofi_rxm" provider behavior with
  respect to zero-length transfers and atomic ops
- We were being sloppy about how we specified which completions we
  wanted to see.  Tighten that up.
- The existing completion management would not have worked if tasks
  could switch transmit contexts while allowing compute/communicate
  overlap during completion waits.  Here, revamp completion management
  so that we (or somebody else) watches the right transmit context for
  the completion(s) we're waiting for.
- Implement blocking CQ support but leave it off by default, because at
  present it doesn't seem to provide the expected performance benefit.

### CODE REVIEW

**Comment by gbtitus** [comment]
This will definitely be easier to review commit-by-commit than all at once.

**Comment by gbtitus** [comment]
I saw 3 internal error failures in full testing, like this:

```
internal error: 0: comm-ofi.c:2998: fi_cq_read(): err 258, strerror
```

It turned out these were not really indicating problems in comm=ofi as such.  All 3 were reported on node 0 in tests in which a non-0 locale exits unilaterally:

```
arrays/bradc/localSlices/nonlocalslice.chpl
extern/multilocale/externRemoteRecord1.chpl
types/string/sungeun/c_string/multilocale/c_str_on_remote_global_string.chpl
```

So, I believe these are okay.  They just reflect the uncoordinated exit.

**Comment by gbtitus** [comment]
@ronawho could you take another look, at just the commits since your prevous approval?  The `stream` performance should be back now and I made other improvements, some before that and some after.  I'm running another full test as I type this.

**Comment by ronawho** [comment]
Hmm, on our CS I still see TCP being the default after this change (but maybe that's expected?)

That said stream with forcing verbs looks good (~1503 before and after). I wanted to see if `CHPL_RT_COMM_OFI_BLOCKING_CQ=y` improved perf, but that seems to hang. Not something to look into for this PR though since it's off by default.

**Comment by gbtitus** [comment]
> Hmm, on our CS I still see TCP being the default after this change (but maybe that's expected?)

Or at least "not unexpected"?  But it would be worthwhile to understand why the `fi_getinfo()` call in the comm layer doesn't return any fabric domains specifying the verbs provider even though `fi_info` shows some of those for the `ep_type` and `caps` we're supplying in the hints.  I'll make an issue for this.

**Comment by gbtitus** [comment]
> I wanted to see if `CHPL_RT_COMM_OFI_BLOCKING_CQ=y` improved perf, but that seems to hang.

Yes, I saw this also, and will make an issue for it as well.

**Comment by gbtitus** [comment]
I forgot to say: this closes https://github.com/Cray/chapel-private/issues/253.

**Pull request merged**
