### PR TITLE
Make `require`ments based on directory in which the module is located

### PR DESCRIPTION
**Pull request by bradcray**
This causes requirements to take the location of the module (if it's
somewhere other than './') into account when adding the requirements to
the compiler's notion of things.  Specifically, for

* a .h file, it adds a -I path for the module's location
* a .c or .o file, it adds the module's location to the filename if
  it isn't an absolute path

The result is that any requirements listed in a file are resolved relative to
that file rather than relative to where the compiler is running.

Resolves: #12844.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
I verified that with these changes, my split of the ZMQ helper .h file into a .h and .c file works (with a slight, unrelated modification)

**Comment by bradcray** [comment]
Cool!

**Comment by bradcray** [comment]
@lydia-duncan: Nobody's expressed any concern about this.  Want to review it?  (or I can solicit volunteers)

**Comment by lydia-duncan** [comment]
Yeah, I'll review it!

**Comment by bradcray** [comment]
linux64 paratest

**Comment by lydia-duncan** [comment]
👍

**Pull request merged**
