### PR TITLE
Adding code for compiler dependent __attribute__

### PR DESCRIPTION
**Pull request by ram-nad**
Added code for different compilers using `#ifdef` checks.

### CODE REVIEW

**Comment by cassella** [comment]
If we do need something like this, I think it would be cleaner to have the conditionals define how the attribute works, and then have the attribute on the lines it's needed unconditionally:

```c
#if __GNUC__
#define FORMAT_ATTR(f, a) __attribute__((format(printf,f,a) ))
else ifdef __clang__
#define FORMAT_ATTR(f, a) __attribute__((format(printf,f,a) ))
#else
#define FORMAT_ATTR(f, a)
#endif

...
void handleError(const char* fmt, ...) FORMAT_ATTR(1,2);
void handleError(const BaseAST* ast, const char* fmt, ...) FORMAT_ATTR(2,3);
```

Since the gcc and clang options are compatible (as described in #15450 ), there only needs to be one actual definition (`#if __GNUC__ || defined(__clang__)`).  (accepting other compilers as @bradcray noted there -- I don't know the #ifdeffs for them.)  This would be better wrt. MSVC than what I added in that PR.  I don't know how likely such a compilation attempt is. :)

I didn't check that `#if __GNUC__` and `#ifdef __clang__` are the appropriate tests.

**Comment by ram-nad** [comment]
Actually, if we need to support only one syntax, then checking for __GNUC__must do because, all compilers (INTEL, clang) that support GCC extension syntax define this macro [as given here](https://stackoverflow.com/questions/38499462/how-to-tell-clang-to-stop-pretending-to-be-other-compilers).

**Comment by cassella** [comment]
That looks good to me, thanks!

I can't give final approval or merge anything.  (Or test with any non-gcc compilers).  Maybe @bradcray, who's looked at the previous PR (#15450).

**Comment by bradcray** [comment]
I still wonder/worry if we're over-engineering given how portable the version on master has been.  Has anyone tried compiling with MSVC to verify that it breaks there?  (i.e., we're not just assuming the worst?)

**Comment by ronawho** [comment]
We unconditionally use `__attribute__ ((format...))` a few place in the runtime. 

```
$ git grep  "__attribute__ *(( *format" runtime/
runtime/include/chpl-string-support.h:  __attribute__((format(printf, 1, 2)));
runtime/include/chpl-visual-debug.h:      __attribute__ ((format (printf, 2, 3)))
runtime/include/error.h:       __attribute__((format(printf, 1, 2)));
runtime/include/error.h:    __attribute__((format(printf, 1, 2)));
runtime/include/error.h:  __attribute__((format(printf, 2, 3)));
runtime/src/error.c:       __attribute__((format(printf, 5, 0)));
runtime/src/error.c:       __attribute__((format(printf, 5, 0)));
```

I'm pretty confident  `__attribute__` does not with MSVC, but we almost certainly have other portability issues there too.

I don't have a personal preference for whether we guard these, just wanted to point out that we've been relying on having it for years, so https://github.com/chapel-lang/chapel/pull/15450 didn't introduce any new portability issues.

**Comment by ram-nad** [comment]
> I still wonder/worry if we're over-engineering given how portable the version on master has been. Has anyone tried compiling with MSVC to verify that it breaks there? (i.e., we're not just assuming the worst?)

Sorry, I haven't checked it with MSVC, but I have seen a lot of codebases use this guard. But as suggested there are a lot of portability issues with MSVC, so I am closing this PR.

**Comment by bradcray** [comment]
> but we almost certainly have other portability issues there too.

This is my sense as well.

Probably my reaction is coming primarily from a perspective of laziness: not wanting to (personally, at least) do the compiler portability testing a second time given the annoyance, the fact that I got it wrong once before, and the thought that we'd probably want to break some of the current format-argument cases in doing the testing to ensure that it's still working as expected.

None of that's to say that this isn't the right thing to do, simply that I'd be more motivated to do it if we had a motivating case for it.

**Pull request closed without merging**
