### PR TITLE
Proposed draft of binary trees

### PR DESCRIPTION
**Pull request by bradcray**
Major changes:

* changed most standalone functions on trees into methods on tree including
  a type/factory method to create trees
* moved Tree definition after main()
* tightened up some code and comments

Also updated release README with TODOs while here

TBD:

* can we take the free while adding approach?  Seems plausible based on
  the documentation...

### CODE REVIEW

**Comment by bradcray** [comment]
For your consideration, perf team:  @benharsh , @lydia-duncan , @ben-albrecht , @ronawho , @psahabu , @Ldelaney.  Note that I did not take the "free while adding" approach here, but kicked that question to email instead.

**Comment by lydia-duncan** [comment]
There's got to be a way to wrap all the perf team members in a single reference so you don't have to write all our names each time.

**Comment by ronawho** [comment]
https://github.com/blog/1121-introducing-team-mentions?

**Comment by lydia-duncan** [comment]
I'll make a team

**Comment by lydia-duncan** [comment]
You can now mention all of the perf team by @chapel-lang/perf-team

**Pull request merged**
