### PR TITLE
== operator overload for LinkedList

### LINKED ISSUE #13137: [Request] Add procedure `==` overload to LinkedLists Standard Module
I believe LinkedLists should have a `==` overload. Current scenario
```chapel
use LinkedLists;
var x : LinkedList(int);
var y : LinkedList(int);
x.append(1,2,3);
y.append(1,2,3);
writeln(y==x);
```
gives output 
```bash
false
```
but for 
```chapel
writeln(x==x);
```
prints
```bash
true
```

### PR DESCRIPTION
**Pull request by rahulghangas**
Resolves #13137
Checks element wise equality of a LinkedList and returns a LinkedList of booleans.
Throws an error if  LinkedLists being compared aren't of equal size.

- [x] Testing

### CODE REVIEW

**Comment by rahulghangas** [comment]
@lydia-duncan @krishnadey30 I finally got around to adding tests on all of my pending PRs. Can you guys review it? thanks

**Comment by krishnadey30** [comment]
@rahulghangas I suggest adding some other tests of different types, different lengths.

**Comment by lydia-duncan** [comment]
Hi, what's the status on this branch?

**Comment by cassella** [comment]
>  Checks element wise equality of a LinkedList and returns a LinkedList of booleans.

In #13137, @bradcray  wrote
>  I'm assuming that nobody would argue that the result of == on a linked list should be a linked list of booleans]

which was grammatically a little roundabout.  He meant `LinkedList`'s `==` should return a single boolean, not a linked list of them.  ("nobody would argue that X" meaning that "nobody would argue in support of X".)

**Comment by bradcray** [comment]
Closing due to inactivity, though if @rahulghangas wants to take it back up later, that'd be fine.

**Pull request closed without merging**
