### PR TITLE
Add a GPU jacobi version that uses --verbose

### PR DESCRIPTION
**Pull request by daviditen**
Add a GPU jacobi that uses --verbose and counts the number of 'Kernel launcher'
messages. This way we won't be surprised if we stop calling into the GPU
kernels for some reason.

Signed-off-by: David Iten <daviditen@users.noreply.github.com>

### CODE REVIEW

**Review by stonea — APPROVED** [review]
Cool, this is our first test locking down that we actually launch on the GPU 😎.

I kind of wish there was a place we could write a comment explaining why there's 21 kernel launches -- each forall loop is turned into a kernel: there are two forall loops that make up the computation body that are called ten times, plus we have one forall loop that initializes the arrays.

I'm not sure where such a comment would naturally go. I guess just in jacobi.chpl directly. Anyway add it if you want, no big deal if you don't.

**Comment by daviditen** [comment]
> I guess just in jacobi.chpl directly. Anyway add it if you want, no big deal if you don't.

Thanks! I added a comment in jacobi.chpl before the GPU call to the `jacobi()` function.

**Comment by bradcray** [comment]
As mentioned on chat after Monday's demo, I still find it odd that our jacobi is using a problem size of `n+1` and storage of `n+3` rather than the more typical problem size of `n` with `n+2` storage and think we should fix that up.

**Comment by e-kayrakli** [comment]
I think the snippet in the technote is fixed but not the test in the repo.

https://chapel-lang.org/docs/master/technotes/gpu.html

**Pull request merged**
