### PR TITLE
Add spec text describing enum conversions that throw

### PR DESCRIPTION
**Pull request by bradcray**
While here, I took a pretty significant pass in reordering and
rewording enum conversions, striving for improved clarity.

### CODE REVIEW

**Comment by bradcray** [comment]
@e-kayrakli: Would you be able to review this rewrite of this section for me?  (I ~am picking on~ picked you because it looked like you'd been here recently to describe enum<->bytes conversions).

**Comment by bradcray** [comment]
PS — Reading this and coming across it in the code a week or two ago, I'm increasingly surprised that we support enum casts to non-integer types and am thinking about putting in a `--warn-unstable` warning for it.  Curious if you have thoughts about that.

**Comment by e-kayrakli** [comment]
Re: we can put warn-unstable for non integer casts, I agree.

I'd be fine with deprecating them in the next release cycle.

**Comment by bradcray** [comment]
Thanks Engin!  Would you be up for reviewing #15354 then?

**Pull request merged**
