### PR TITLE
Use localAccess for ra-on

### PR DESCRIPTION
**Pull request by ronawho**
Switch from using a local block to localAccess for ra-on. This allows
the fast-on optimization to trigger, which eliminates task creation. The
local block was originally added in 4a8cedf8fc to enable the fast-on
optimization, but it looks like there's been a regression since then.
With the local block today we're still emitting PUT/GET calls (that end
up being local) that thwart the fast-on optimization. Longer term we
want to deprecate support for the local block anyways, so switch to
localAccess.

RA-on performance for XC (Aries/ugni) and CS (FDR-IB/gasnet-ibv-large):

| config  | Before      | After       |
| ------- | ----------- |  ---------- |
| Cray-XC | 0.0119 GUPS | 0.0143 GUPS |
| Cray-CS | 0.0018 GUPS | 0.0027 GUPS |

### CODE REVIEW

**Comment by ronawho** [comment]
@chapel-lang/perf-team this is a change we discussed last perf meeting. Let me know if you have any objections to this.

**Comment by bradcray** [comment]
I like the code change and the performance improvement.  Does changing `on TableDist.idxToLocale[r & indexMask] do {` to the more straightforward `on T[myR & indexMask]` hurt performance?

**Comment by ronawho** [comment]
Yeah,

```chpl
on T[r & indexMask] do
  T.localAccess[r & indexMask] ^= r;
```

performs well too. It may be ever so slightly faster since when things are local that has a fastpath that idxToLocale doesn't currently.

**Comment by ronawho** [comment]
A different alternative that seems like it could perform even better since it eliminates an indexing operation:

```chpl
ref Tr = T[r & indexMask];
on Tr do Tr ^= r;
```

actually performs worse. Currently, that `Tr ^= r` still gets generated as a GET/PUT.

**Comment by bradcray** [comment]
I'd go with the simpler on-clause then.  It uses features we teach commonly to people (data-driven on-clauses) whereas the version on master relies on subtler stuff (methods on distributions).

**Comment by ronawho** [comment]
Updated to use simpler on-clause

**Pull request merged**
