### PR TITLE
Action of Matrix Exponentials

### PR DESCRIPTION
**Pull request by prashanth018**
Added functionality to perform the action of an exponential on a vector or another matrix of rank=2.

TODO:
1) Need to add documentation.
2) change naming convention.
3) add functionality for Sparse matrix.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Hi @prashanth018 - I'm going to mark this as post-release for now since it seems to still be a work in progress.  Definitely feel free to poke when you're ready for it to be looked at, or discussed more or whatever :)

**Comment by prashanth018** [comment]
Hey Lydia, had been on a vacation. I'll update the PR with the changes over the weekend. :D

**Comment by lydia-duncan** [comment]
Hi @prashanth018, how are the updates coming?

**Comment by prashanth018** [comment]
Hi, @lydia-duncan I have been caught up with the interviews and coursework. I'll for sure make the updates over this weekend. Thanks.

**Comment by lydia-duncan** [comment]
Been a while since we've heard from you, hope you're doing okay!  In the meanwhile, going to close this but feel free to ping or reopen when you have time to revisit it!

**Pull request closed without merging**
