### PR TITLE
Two extern block fixes

### PR DESCRIPTION
**Pull request by mppf**
Thanks to @npadmana for pointing out these problems.

Adjusts externCResolve to treat C function pointers in extern blocks as
opaque types in Chapel.

Also fixes a bug where a function argument that is declared as a typedef
struct { } was not working.

Passed test/extern/ferguson test/extern/jjueckstock with --llvm
Passed full local testing with CHPL_LLVM=llvm
Reviewed by @noakesmichael - thanks!

### CODE REVIEW

**Comment by npadmana** [comment]
@mppf : I just updated PR #3677 --- the original case passes fine, but there appears to be a related issue for making constants accessible to Chapel. I've updated the test : the error message I'm getting is below...

```
test_extern_struct_function_pointer.chpl:15: error: '' undeclared (first use this function)
```

**Comment by mppf** [comment]
Hi @npadmana - I updated this PR to fix the last bug you reported. Can you try your GSL experiment again?

Also, it's not really clear to me how easy it will be for us to handle const pointers correctly in extern blocks. I'd be interested to know how big of an issue this is for you.

**Comment by npadmana** [comment]
Hi @mppf : trying to run the test in PR #3677 now seems to cause a new internal error 

```
> $CHPL_HOME/modules/internal/ChapelIO.chpl:234: internal error: BUI0644 chpl Version 1.13.0.5567621
>
> Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
> and we're sorry for the hassle.  We would appreciate your reporting this bug --
> please see http://chapel.cray.com/bugs.html for instructions.  In the meantime,
> the filename + line number above may be useful in working around the issue.
```

**Comment by npadmana** [comment]
Quick follow up --- the above error could be because I didn't fully and update.... working on that right now.

**Comment by mppf** [comment]
@npadmana - your program works for me if I rename func -> func1
I think func has a naming conflict with something in ChapelBase. That's a different issue though.

**Comment by npadmana** [comment]
@mppf - confirmed that this works. I'll check the GSL test next....

**Comment by npadmana** [comment]
@mppf - the GSL tests work like a charm. The extern blocks seem to handle the GSL headers that I've tested without any modifications.

All of this is at my branch of  
  https://github.com/npadmana/chapel/tree/gsl_demonstration
under
  test/users/npadmana/gsl_demonstration
set up as a Chapel test. 

Do you think this would be appropriate to merge into the main Chapel tree, and then maybe recast into a test/example? It currently has a SKIPIF, so shouldn't break the Chapel test machinery if GSL is not installed.

**Comment by mppf** [comment]
Hi @npadmana - cool! Glad it's working. Yeah, I think it'd be reasonable to commit that GSL demo in test/users/npadmana for now at least. Let's do that (and have this PR merged) before we decide whether or not it makes sense in test/release/examples, OK?

**Comment by npadmana** [comment]
@mppf  - Yes, that makes sense; making it an actual example will require some thought and work. I'll generate a pull request now.

**Comment by mppf** [comment]
I'm re-running testing on this PR.

**Comment by mppf** [comment]
Passed full local testing in an LLVM configuration.

**Pull request merged**
