### PR TITLE
Support for C unions in c2chapel

### LINKED ISSUE #17278: Support for C unions by c2chapel
Currently, the `c2chapel` tool does not recognize a C union while converting definitions in C headers to Chapel extern definitions.
On experimentation, it was found that C unions can indeed be treated in a similar way as C structs are treated while working with C interoperability.

Hence, this code, where the C union is treated as a struct (example given by @bradcray) runs as expected:

**File**: *testit.h*
```c
typedef union _u {
  int x;
  unsigned y;
} u;

extern void setX(int x);
extern int getX(void);
extern unsigned getY(void);
```

**File**: *testit.c*
```c
#include "testit.h"

u myU;

void setX(int x) {
  myU.x = x;
}

int getX() {
  return myU.x;
}

unsigned getY() {
  return myU.y;
}
```

**File**: *testit.chpl*
```c
use SysCTypes; // get definitions of c_int, c_uint                              

require "testit.h", "testit.c"; // C code defining union                        

// reflect C code here                                                          
extern record u {
  var x: c_int;
  var y: c_uint;
}
extern proc setX(x: c_int);
extern proc getX(): c_int;
extern proc getY(): c_uint;

// create and modify union from Chapel:                                         
var myChplU: u;

myChplU.x = -3: c_int;
writeln(myChplU.x);
writeln(myChplU.y);

// create and modfiy C union through routines:                                   
setX(-3);
writeln(getX());
writeln(getY());
```

As the union shows the expected behavior of a C union (confirmed by experimentation), it should be good to be added as a recognized node in the `c2chapel` tool.

### PR DESCRIPTION
**Pull request by leekillough**
(Clone of https://github.com/chapel-lang/chapel/pull/17284 from @souris-dev, with fixes from https://github.com/leekillough/chapel/commit/30925e027f0649538749d56bd4eb7a4d851abd86 added.)

The `c2chapel` tool should now support C unions the same way it supports structs.

Fixes #17278.

### CODE REVIEW

**Comment by cassella** [comment]
Why does this PR have over a thousand changed files, including the 1.24.0 notes in the CHANGES.md, and code I wrote in AstToText.cpp?  The final commit 8fbde86 ("Fix expected results. ...") appears to be where that all came from.

**Comment by leekillough** [comment]
@cassella:

I'm not sure. I had strange DCO errors I kept getting, apparently because of a prior commit on a machine I don't use very often, and it took me two hours to figure it out and work around it.

I merged the PR branch with `master` prior to merging the PR to `master`.

To work around the DCO errors, I decided to `git reset --soft` to @souris-dev 's last previous change, in my PR's branch, and commit it with a new signature. This basically means: "Take the state of my repository now as a modification against version `xyz`, and push it in the next commit." I preserved all of @souris-dev's changes and their history, and added my own, with a manually-added signature to work around the DCO errors (normally my `.gitsig` handles DCO automatically).

I hope that nothing was lost. The 1000+ file changes does seem very strange though.

The actual "fix expected results" commit was small (3 lines in a `.good` test file and one executable file permission change).

The original PR was submitted before the 1.24 release, and it's possible that 1000+ files were modified at the last minute for the 1.24 release, so the strange "fix expected results" commit simply reflects the merging of these 1.24 changes back into the original PR's history.

But it shouldn't have netted 1000+ files changing in the overall PR.

Nothing was force-pushed to master, so it should be possible to backtrack, if anything is wrong.

I'll definitely investigate it.

**Comment by leekillough** [comment]
If I try to revert this PR's changes against the parent branch, I only see these files revert:
```
#       modified:   test/c2chapel/c2chapel-tester.good
#       deleted:    test/c2chapel/testUnions.c
#       deleted:    test/c2chapel/testUnions.chpl
#       deleted:    test/c2chapel/testUnions.cleanfiles
#       deleted:    test/c2chapel/testUnions.compopts
#       deleted:    test/c2chapel/testUnions.good
#       deleted:    test/c2chapel/testUnions.h
#       deleted:    test/c2chapel/testUnions.precomp
#       modified:   tools/c2chapel/c2chapel.py
#       deleted:    tools/c2chapel/test/miscTypedefUnion.chpl
#       deleted:    tools/c2chapel/test/miscTypedefUnion.h
#       deleted:    tools/c2chapel/test/nestedUnion.chpl
#       deleted:    tools/c2chapel/test/nestedUnion.h
#       deleted:    tools/c2chapel/test/opaqueUnion.chpl
#       deleted:    tools/c2chapel/test/opaqueUnion.h
```
That's a lot less than 1000+ files, and they are all directly pertinent to this PR.

**Comment by leekillough** [comment]
Here's the files changed by this PR, as revealed by `git diff --name-only`:
```
$ git diff --name-only 38f43471f6 2790dd16e65474f2d9eba9fa6f7d38c617c833ec
test/c2chapel/c2chapel-tester.good
test/c2chapel/testUnions.c
test/c2chapel/testUnions.chpl
test/c2chapel/testUnions.cleanfiles
test/c2chapel/testUnions.compopts
test/c2chapel/testUnions.good
test/c2chapel/testUnions.h
test/c2chapel/testUnions.precomp
tools/c2chapel/c2chapel.py
tools/c2chapel/test/miscTypedefUnion.chpl
tools/c2chapel/test/miscTypedefUnion.h
tools/c2chapel/test/nestedUnion.chpl
tools/c2chapel/test/nestedUnion.h
tools/c2chapel/test/opaqueUnion.chpl
tools/c2chapel/test/opaqueUnion.h
```
I think GitHub == GitBug.

**Comment by cassella** [comment]
Ah, ok, I think the merge from master into the branch got all these changes into your PR branch.  Then the `reset --soft` removed the merge from master from the history, but left all the new master code in the branch, which got committed into that final "fix expected results" commit.  So `git show 8fbde86` shows all the changes (relative to the previous commit on the PR branch.)  And the github PR diff view shows the changes in the commits that are on the PR branch but not on master.   8fbde86 is on the PR branch and not master, so it shows those diffs.  (The PR diff view doesn't reflect changes on master that aren't in the PR branch -- that'd be a nightmare for long-lived PRs.)

Then when you merged the PR to master, git found that all these changes were identical to changes already in master, so it was able to resolve those "conflicts" trivially since the same code was in both branches.  (It would have been worse if there had been conflicting changes to master between your merge from master and when you merged the PR.  It would have been much worse if those conflicting changes included reverting one of the master commits you'd merged in, as then git would have seen the merged code from the original unreverted commit as new code in the PR branch, and applied it (reapplied it) without comment.)

The `git reset --soft` defeated git's tracking of the merge from master, and made all those master changes look like they were part of that last commit.

**Comment by leekillough** [comment]
The `git reset --soft` was done reluctantly to work around the DCO errors, since the usual steps of `git commit --amend --signoff` did not work and the CI system kept complaining of DCO errors apparently because of one non-latest commit in my history.

I finally gave up and said "Okay, I'm going to run `git reset --soft` and re-commit all of my changes relative to @souris-dev's latest change, and this time the DCO will be signed correctly."

**Comment by vasslitvinov** [comment]
Thankfully the merge commit, 2790dd1, shows only 15 changed files. However, it scares me to have a commit like c95064f with 20,670 changed files in PR history. Looking back, I suspect that a `git rebase` would have taken care of the DCO issue cleanly.

**Comment by leekillough** [comment]
@vasslitvinov : `git rebase` was tried initially, but I ran into conflict errors, coincidentally with one of your `forall` changes. When I wasn't sure how to resolve them, and I had a good hunch that the changes would be modified again later in the rebase process, I threw up my hands and went for `git reset --soft`, knowing that my branch was fully up to date with master.

**Comment by leekillough** [comment]
I didn't want to take the risk of making a wrong decision during `git rebase` which would cost us later. I knew I was fully up to date with master, with only 15 files being modified in this PR, so I used `git reset --soft` so that I could re-commit without the never-ending DCO errors.

Although my last commit in the PR branch had 1000+ file changes, only 15 of them were different from master, and those are the 15 which went into the PR merge commit.

**Comment by leekillough** [comment]
Remember, @souris-dev's PR started from an old version of Chapel, so that's why `git rebase` is so complicated and has so many conflicts, and why 1000+ files were modified just to get his PR up-to-date with master.

I, quite reluctantly, "short-circuited" with `git reset --soft`, because I had to get around the DCO errors and merge this PR ASAP, since it seemed to be fairly high in priority / interest. It passed all of the tests, after my 3-lines + 1 file permission = 1000+ files commit!!!

I had already merged master into my PR's branch, after the commit which caused the DCO errors. I suppose I could have just `git reset --hard` back to my badly-signed commit, fixed the DCO error, and then re-merged master again. I wanted a full test run with it merged with master before merging the PR, so whatever I did, it was going to be fully tested after being merged with the latest master.

I'm probably beating a dead horse; I'll shut up.

**Pull request merged**
