### PR TITLE
Make c_fn_ptr equality comparable to nil

### LINKED ISSUE #24164: Make `c_fn_ptr` comparable to `nil`
### Summary of Problem

Currently, we can check whether a `c_ptr` is NULL by saying `ptr == nil`: https://github.com/chapel-lang/chapel/blob/9c7ab5c44e514f2929a331c565497eca3c9a4d32/modules/standard/CTypes.chpl#L675

It'd be great to be able to do the same with a `c_fn_ptr` without a (semantically incorrect) casting to `c_ptr` first.

### Possible implementation

Add these to the CTypes module?

```chapel
  @chpldoc.nodoc
  inline operator ==(a: c_fn_ptr, b: _nilType) {
    return a:c_ptr(void) == b;
  }
  @chpldoc.nodoc
  inline operator ==(a: _nilType, b: c_fn_ptr) {
    return b == a;
  }
  @chpldoc.nodoc
  inline operator !=(a: c_fn_ptr, b: _nilType) {
    return !(a == b);
  }
  @chpldoc.nodoc
  inline operator !=(a: _nilType, b: c_fn_ptr) {
    return b != a;
  }
```

### PR DESCRIPTION
**Pull request by twesterhout**
Fixes #24164

### CODE REVIEW

**Comment by bradcray** [comment]
I'm running a paratest on this, even though I can't imagine that anything could go wrong.

@twesterhout : Thanks for opening this!  Note that although we're pretty good at noticing and replying to new issues, comments on gitter and discourse, etc., PRs are one of the things that can slip past us if nobody tags us on them or points to them from an issue that's being followed.  So if/when you open PRs in the future, don't be shy about drawing someone's attention to them (though maybe you did here and I just missed it...).

**Comment by bradcray** [comment]
Testing came back clean.  I'll plan to merge next week so that I can triage any problems if anything else goes wrong.

**Comment by bradcray** [comment]
Actually, @twesterhout, I have one request.  Re-reading the code once more, I'm realizing the degree to which the routines work by calling one another.  Would you extend your test to include calls to the other two overloads (which is to say, the same two calls you have with the arguments reversed) just to make sure there aren't any errors now, and ensure that none get added later if/when someone refactors this in the future?  Thank you!

**Comment by twesterhout** [comment]
@bradcray sorry for not pinging earlier - will make sure to do it for future PRs.

Added the requested test cases. My motivation for having everything call the first function was that it keeps the ugly cast contained to just one function (if it's buggy, or you decide to rewrite it using a `__primitive` function, then you only have to touch that one function).

**Comment by twesterhout** [comment]
p.s. the make_doc CI failure seems unrelated to this PR:

> Sphinx version error:
> The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.

**Comment by bradcray** [comment]
Thanks for contributing this, @twesterhout!

**Pull request merged**
