### PR TITLE
Reorganization of Chapel Web Documentation

### PR DESCRIPTION
**Pull request by ben-albrecht**
* Hosting pdfs under chapel.cray.com/docs/ domain 
    * e.g. `chapel.cray.com/docs/master/_downloads/reference.pdf`
    * pdfs are copied/removed with the docs Makefile
* Removed sidebar links that redirect to pdf
    * Sidebar link takes you to landing page with pdf link instead
* Separated main table of contents into two sections *Compiling and Running Chapel* and *Writing Chapel Programs* 
    * *Compiling and Running Chapel Programs* was too verbose and gets clipped by sidebar width, as demonstrated in the screenshot below
* Removed *"Built with Sphinx using a theme provided by Read the Docs."* from footer
* Added Chapel logo as web icon for docs
* Updated required Sphinx version to 1.3 (needed for use of `:caption:`)
    * This may require a rebuild of `test-venv` for current builds, if not rebuilt since the Sphinx version was updated

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Closing until 2016 smokeTest failure is resolved.

**Comment by ben-albrecht** [comment]
Maybe @bradcray or @Kyle-B would be interested?

**Comment by bradcray** [comment]
Notes from user perspective:

* Nit-picky, but could we rename the two PDFs to match the names used in the release?  (or vice-versa).  Seems like it would avoid confusion.  reference.pdf is the main one that bothers me ("Is it the full language reference?  No, it's just the quick reference").  It could be quickRef.pdf rather than quickReference.pdf if length is a concern.  spec.pdf isn't as bad, and I'd also be OK with chapelSpec.pdf or languageSpec.pdf if the thought was that the name was too long.  But in any case, would prefer to be consistent between release and web docs to avoid confusion.

* The unfortunate-ness you noted about the spec not being in the sidebar seems pretty unfortunate to me too.  This makes me think we might either push language evolution into the top level (make spec more symmetrical with quickref, which isn't as offensive since it's a singleton) or push the PDFs to the sidebar (if that's an option).  I don't have a preference between the two.  OR: Is there a trick we could use to squash the language evolution from appearing in the sidebar?  That would be acceptable to me as well.

* Chapel icon on tabs -- nice!

**Comment by bradcray** [comment]
I took a pretty high-level pass over the files/mods themselves and nothing jumped out at me (apart from the two places that'll need to be updated if you guys agree with the unify filenames changes).  So nothing else from me.  Thanks for taking this on, I think it's a big improvement!

**Comment by ben-albrecht** [comment]
In response to comments by @bradcray

* pdfs renamed to match original named (`quickReference.pdf` / `chapelLanguageSpec.pdf`). This is the easier solution for now.

* Not being able to include local pdf files in the TOC tree is an unfortunate limitation of sphinx (read-the-docs theme?). We might find a workaround for this in the future if we go forward with splitting off of read-the-docs. For now I'm going to have language evolution, language spec, and quick reference all be top-level items, because we cannot the other suggestions are currently not possible.

**Pull request merged**
