### PR TITLE
Update CLBG links

### PR DESCRIPTION
**Pull request by thodkatz**
I tried to update some broken links from the [Computer Language Benchmarks Game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html) for the [Chapel versions](https://benchmarksgame-team.pages.debian.net/benchmarksgame/measurements/chapel.html). Some programs that I couldn't index from the website, I removed them from the README.

### CODE REVIEW

**Comment by bradcray** [comment]
Hi @thodkatz : Thanks for these broken URL fixes, which had escaped us (obviously).

I think that the retired CLBG benchmarks should still remain in the README since they are still in the directory (and actually are, in some cases, more interesting for Chapel than the non-retired ones), but perhaps they could be moved to a separate section like "Legacy Benchmarks" with the hyperlinks removed?

One other thing that caught my eye here is the phrase "that have been officially submitted to the Computer Language
Benchmarks Games website", because over time we haven't done a great job of keeping this directory directly in sync with the submitted versions of the shootout benchmarks.  So if you're up for it perhaps we can use a phrase like "that represent implementations of the Computer Language Benchmarks Game benchmarks" or something like that?

One other general tip:  When opening PRs, it's a good idea to ping the team about them on Gitter or Discourse or on the PR itself if you have an idea about who would be appropriate to @-tag on it.  Otherwise, they tend not to get noticed very quickly (I just happened to be taking stock of things tonight and this one caught my eye).

**Comment by thodkatz** [comment]
> Hi @thodkatz : Thanks for these broken URL fixes, which had escaped us (obviously).
> 
> I think that the retired CLBG benchmarks should still remain in the README since they are still in the directory (and actually are, in some cases, more interesting for Chapel than the non-retired ones), but perhaps they could be moved to a separate section like "Legacy Benchmarks" with the hyperlinks removed?
> 
> One other thing that caught my eye here is the phrase "that have been officially submitted to the Computer Language
> Benchmarks Games website", because over time we haven't done a great job of keeping this directory directly in sync with the submitted versions of the shootout benchmarks. So if you're up for it perhaps we can use a phrase like "that represent implementations of the Computer Language Benchmarks Game benchmarks" or something like that?
> 
> One other general tip: When opening PRs, it's a good idea to ping the team about them on Gitter or Discourse or on the PR itself if you have an idea about who would be appropriate to @-tag on it. Otherwise, they tend not to get noticed very quickly (I just happened to be taking stock of things tonight and this one caught my eye).

Thank you very much for the response and for the general tip! It is sure wise to notify chapel community for the PRs. I will try to integrate your suggestions, including the legacy benchmarks and rephrase the README in order to make more sense.

**Comment by thodkatz** [comment]
@bradcray I tried to integrate the suggestions. Please, whenever you can, review the changes and tell me if there is something I can improve.

**Comment by bradcray** [comment]
Thanks @thodkatz!  I'm not sure whether I'll have time to get to this today, but will try to get to it Monday if not.

**Comment by thodkatz** [comment]
> Thanks @thodkatz! I'm not sure whether I'll have time to get to this today, but will try to get to it Monday if not.

You are welcome! Yes, of course, whenever is possible.

**Comment by bradcray** [comment]
Hi @thodkatz — Thanks again for taking this on.  I was completely mixed up the other week if it seemed like I wasn't making sense... I was thinking that this was the README from `test/release/examples/benchmarks/` which is why I suggested that the legacy versions were still in the same directory.  They aren't of course, but I'm happy with the way you approached that, so am merging.  Sorry for my confusion.

**Pull request merged**
