### PR TITLE
fix project version test files

### LINKED ISSUE #14984: Difference in .catfiles handling of files that don't end with a newline depending on platform
### Summary of Problem
start_test either respects or fails to respect when including a file that doesn't end with a newline.  On linux, the .catfiles results in no newline at the end of the expected output, while on darwin a newline is required.

Looking at start_test, I couldn't easily tell what was causing this.  I kinda suspect it might
be something to do with python's subprocess implementation?

### Steps to Reproduce

**Associated Test(s):**
[`test/chpldoc/compflags/version/projectVersion.doc.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/compflags/version/projectVersion.doc.chpl) #14983 

### Configuration Information

- Output of `chpl --version`: 1.21 (pre-release)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: darwin or linux64
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none

### PR DESCRIPTION
**Pull request by immadisairaj**
- trim the output file to get only 'version' from the file
- replace test files to accept new format

### CODE REVIEW

**Comment by immadisairaj** [comment]
@lydia-duncan can you please review this.

**Comment by lydia-duncan** [comment]
I'd like this to not resolve #14994, since I think we should alter start_test/sub_test to be consistent across platforms

**Comment by lydia-duncan** [comment]
But otherwise this looks good!

**Comment by immadisairaj** [comment]
> I'd like this to not resolve #14994,

do you mean #14984? Should I remove the `Fixes #14984` from the message?

**Comment by lydia-duncan** [comment]
> do you mean #14984?

Heh, yes XD

> Should I remove the Fixes #14984 from the message?

Yes please!

**Pull request merged**
