### PR TITLE
Support for qthreads binders topology

### PR DESCRIPTION
**Pull request by jhh67**
Change the default `qthreads` topology to `binders` from `hwloc`. This is in anticipation of subsequent functionality to allow locales to co-exist on a node, e.g., when running one locale per socket.

Passed `paratest`  and all multi-locale tests on an EX.

### CODE REVIEW

**Comment by ronawho** [comment]
TODOS from offline code review:
 - [ ] get rid of execenvs
 - [ ] test performance (I'll send instructions on how to and which tests are interesting) 
 - [ ] allow topology to return `NULL`?
 - [ ] check that `CHPL_HWLOC=none` works too
 - [ ] create private issue to remind us to upstream these changes

**Comment by ronawho** [comment]
I know we're already splitting a much larger change into multiple PRs, but thinking about this some more, I think we should split this one apart even further. I think we should have a PR that adds the upstream changes (and in that PR have separate commits for the upstream changes, regenerating configure, and updating our Makefile/README.)

This will allow us to more easily contribute those changes upstream later and allow us to verify the approach to getting the topology from the chapel layer separately from the binders switch.

**Comment by jhh67** [comment]
I'm ok with splitting this into a separate PR for upstream changes, but how does that simplify the process?  Either way won't I have to patch a clone of the qthread repo to create the PR?

**Comment by ronawho** [comment]
> I'm ok with splitting this into a separate PR for upstream changes, but how does that simplify the process? Either way won't I have to patch a clone of the qthread repo to create the PR?

If you have a commit to just the qthreads src tree, you can use git to apply the patch to the upstream repo instead of relying on manually copying+pasting, which in the past I have screwed up and ended up with an incomplete change.

**Pull request closed without merging**
