### PR TITLE
[WIP] Chpldoc with sphinx

### PR DESCRIPTION
**Pull request by thomasvandoren**
Combine the .rst and sphinx work within chpldoc to generate html files!

It is now possible to:

```bash
make chpldoc
cd test/release/examples
chpldoc *.chpl

[open] docs/html/build/html/index.html
```

The rst generation is still progressing, so the output will not look quite right for some of the modules.

See also https://github.com/chapel-lang/chapel/pull/1191

### CODE REVIEW

**Comment by thomasvandoren** [comment]
@lydia-duncan -- will you please review this?

**Comment by lydia-duncan** [comment]
Looks great, thanks!

**Comment by thomasvandoren** [comment]
I ran `start_test test/chpldoc/` just to make sure things were still working as expected.

**Comment by lydia-duncan** [comment]
:+1:

**Pull request merged**
