### PR TITLE
Add ISx to the release

### PR DESCRIPTION
**Pull request by benharsh**
This version of isx is very similar to the studies version isx-per-task, except it does not return arrays and instead passes them in to be populated. The .good files are also identical to those in test/studies/isx.

### CODE REVIEW

**Comment by bradcray** [comment]
Low-hanging fruit (for a reviewer):  test/release/examples/benchmarks/README needs to be updated, and ideally Makefiles would be added/edited to support building this from the command-line.  It may also be worthwhile to put a short README into the directory itself as well?  (would we want to copy/move any of the test/studies TODOs into such a README to cover our butts in the public?)

**Comment by bradcray** [comment]
BTW, it would be fine with me if the studies versions were to pull their .goods from these release directories if you want to make that switch.  I agree that the duplication would be unfortunate.

**Comment by benharsh** [comment]
The last couple of commits update or add READMEs and Makefiles.

**Comment by bradcray** [comment]
What's here looks good.  I noticed that there's no perf testing set up for it (which I think we want, right?).  If that's planned as a follow-on commit, that's OK with me.

**Comment by benharsh** [comment]
Thanks, I'll address the .good files and the perf testing setup in a separate commit.

**Pull request merged**
