### PR TITLE
Eliminate extra destructions when yielding tuples

### PR DESCRIPTION
**Pull request by vasslitvinov**
This PR eliminates the extraneous destructions when a parallel iterator yields tuples into a forall loop. For example:

```chpl
forall (r1, r2) in myIter() {....}
```

the tuple `(r1, r2)` used to be destructed in addition to destructing `r1` and `r2`, which caused double-deletions.

This change also causes the anonymous tuple components to leak in the above scenario. For example:

```chpl
for (r1, _) in myIter() {....}
forall (r1, _) in myIter() {....}
```

the component of the yielded tuple that corresponds to the `_` will be discarded without invoking a deinitializer on it, even if one is defined.

Fixing this leak would entail a complex change that is not appropriate this close to the release. I created a future to keep track of it. Also I suggest that we should remove the lowering of detupling expressions during parsing and retain it in a primitive form until resolution, where the lowering can be done with the knowledge of the types, const-ness, and ref-ness of the yielded expression(s). This will improve the correctness and significantly reduce the complexity of this aspect of the compiler.

* [x] testing: standard paratest, gasnet paratest over multilocale tests, asan paratest, memleaks paratest

### CODE REVIEW

**Review by benharsh — APPROVED** [review]

**Comment by vasslitvinov** [comment]
@npadmana -- to your attention, the piece in this PR that's relevant to FFTW codes is an addition of an explicit `init=()` to the `FFTWplan` wrapper around the `fftw_plan` pointer. Without it, the compiler-generated `init=` would copy the fftw_plan pointer, so the latter would be double-deleted: when deinitializing the lhs and the rhs of the init=.

```chpl
{
  var p1 = setupPlan(....);
  var p2 = p1;
}  // here both p1 and p2 are deinitialized,
   // calling destroy_plan() on the same fftw_plan pointer
```

An `init=`, whether user-defined or not, can be invoked in non-obvious cases, for example when copying the plan being yielded from `iter batch()` (if applicable, see below).

Having an explicit `init=` also safeguards against an unintentional assignment between FFTWplans, which would cause the same problem if not implemented properly.

Another tidbit is `pragma "do not unref for yields"` that now needs to be attached to iterators that yield tuples in order to yield the tuple components by ref, without copying them. `iter batch()` is such an iterator. A user-facing solution is sought in #21717.

**Comment by npadmana** [comment]
Thanks, @vasslitvinov for the update. I'll also port this change over to the main DistributedFFT repository.... 

One question -- do these changes require master, or will they work on eg. 1.28/1.29? I'm guessing the user defined `init=` wouldn't cause trouble, but wasn't sure if the pragma had been defined.

**Comment by npadmana** [comment]
So I'm guessing that the `pragma default intent is ref` for the `FFTWplan` record isn't being preserved in the `yield`? 

I can think of two possible workarounds - the first would make the `FFTWplan` a eg. `shared` class. But a second option might be to add in a `var isCopy : bool` into the `FFTWplan` record that keeps track of whether this was created by an `init` or an `init=`. And if `isCopy` is true, it just doesn't deallocate the underlying FFTW plan. 

Would that work?

Incidentally, is there a failing test for this, or is it just random/intermittent depending on when the deallocation actually happens?

**Comment by vasslitvinov** [comment]
@npadmana - since #21789 all types including tuples yield by "copy out" just like returns do with the default return intent. So indeed "pragma default intent is ref" is ignored.

Both your workarounds are good, the "shared class" route seems easier to implement whereas "isCopy" means less overhead, which I guess does not matter.

Could you clarify your question about a failing test? If you remove the pragma "do not unref for yields" from the `batch` iterator without changing anything else in the ft_transpose test, I expect an address sanitizer or valgrind to pick up double-deletion reliably.

**Comment by npadmana** [comment]
Hi @vasslitvinov -- sorry, it took me a while to get back to this.

Do I have this right -- #21789 is not part of either 1.28 or 1.29, and so for these, the `pragma default intent is ref` still works in the yield and there isn't a memory leak/double deletion here? But this will happen in 1.30. I ask, because I've been trying to see if the code fails at my end, but that doesn't seem to be happening..... 

I'll still protect against this, just wanted to make sure I understood what is going on.

**Comment by vasslitvinov** [comment]
Hello @npadmana - you are right, 21789 is new to 1.30.

In 1.28 and 1.29 pragma `default intent is ref` still works, there is no double-deletion issue.

You may not be observing the double-deletion issue possibly because nobody keeps track of double-deletions in your setup and the mistakenly-deleted memory happens not to be reused for something else so its contents are not clobbered.

Also, regardless of the Chapel version, I did not see how pragma `default intent is ref` made a difference in your code. Without this pragma the default intent would be `const ref`. It is possible I am missing something.

**Comment by npadmana** [comment]
Hi @vasslitvinov -- thanks! I updated my version of the code here, keeping track of copies using the `isCopy` solution.

https://github.com/npadmana/DistributedFFT/commit/34a03e83f5079d18f0ecce91e02bcabb304af415

**Pull request merged**
