### PR TITLE
record comparison method specified

### PR DESCRIPTION
**Pull request by klakho0400**

### CODE REVIEW

**Comment by klakho0400** [comment]
i haved the mailed a cla

**Comment by e-kayrakli** [comment]
Thanks for the PR @klakho0400!

I think the part you change with this PR should remain the same. That paragraph only compares class vs. record comparisons. What we need to change to resolve #14833 is the last paragraph under [this heading](https://chapel-lang.org/docs/master/language/spec/records.html#default-comparison-operators).

What I had in mind was to take the relevant two sentences from [tuple comparisons](https://chapel-lang.org/docs/master/language/spec/tuples.html#relational-operators) and refer to it.

So, we can replace that paragraph that I pointed to with something that starts with "Record comparisons have a similar behavior to tuple comparisons(link to spec)." And then grabbing "The operators >, >=, <, and <= check the corresponding lexicographical order based on pair-wise comparisons between the argument tuples’ components. The operators == and != check whether the two arguments are pair-wise equal or not. " with some necessary changes. The most important thing to add is that we compare the fields in the order they are declared in the record definition. Because tuple components have more "natural" order as opposed to record fields and I think it is important to mention that.

**Comment by e-kayrakli** [comment]
Hi @klakho0400 -- I wanted to check with you again to see whether you are still interested in following up on this. This is something I want to fix sooner rather than later. Please let me know!

**Comment by klakho0400** [comment]
HEY @e-kayrakli I wanted to fix it but i have examinations so i may not be able to give time on it now

**Comment by e-kayrakli** [comment]
@klakho0400 -- no worries. I'll fix this early next week. Until then I am keeping this open, in case you get a chance.

**Comment by klakho0400** [comment]
hey @e-kayrakli i am free now i will look into the same

**Comment by klakho0400** [comment]
just to clear it for me
it should look somewhat like this
"Record comparisons have a similar behaviour to tuple comparisons(https://chapel-lang.org/docs/master/language/spec/tuples.html#relational-operators).
The operators >, >=, <, and <= check the corresponding lexicographical order based on pair-wise comparisons between the argument fields’ components. The operators == and != check whether the two arguments are pair-wise equal or not.The fields are compared in the order they are declared in the record definition. "

**Comment by e-kayrakli** [comment]
@klakho0400 -- good to hear that.

I didn't like "argument fields’ components" I don't know what component is there. We can just say "lexicographical order based on pair-wise comparisons between the arguments' fields", it reads much nicer to me. (Note which word is plural and which is possessive).

It is always a good idea to run `make docs` to make sure that the documentation compiles, let me know if you want me to do that after you update the PR.

Thanks a lot!

**Comment by klakho0400** [comment]
@e-kayrakli I have made the changes and I have made a new pull request for the same I will be closing this one and yes I would like you to make the docs

**Pull request closed without merging**
