### PR TITLE
Delete unmanaged domain maps in tests

### PR DESCRIPTION
**Pull request by e-kayrakli**
Deletes bunch of unmanaged variables in tests.

I came across those while investigating string leaks. Overall, leaks from these
tests roughly amount to ~1500 bytes.

Tests locally pass with:
- [x] standard
- [x] standard valgrind
- [x] gasnet

### CODE REVIEW

**Comment by bradcray** [comment]
Might make sense to test these cases with valgrind as well before merging to avoid surprises.

**Comment by bradcray** [comment]
(after which I'd be fine merging this since it's orthogonal to the release).

**Comment by bradcray** [comment]
Given that they're tests you wrote Vass, I think it would also be reasonable for Engin to merge his changes as-is to deal with existing leaks, and then for you to update them to your preferred style.

**Comment by vasslitvinov** [comment]
> I think it would also be reasonable for Engin to merge his changes as-is to deal with existing leaks, and then for you to update them to your preferred style.

That would be fine, too.

**Pull request merged**
