### PR TITLE
Issue warning when old-style init-copy is resolved

### PR DESCRIPTION
**Pull request by benharsh**
This PR issues a warning when an 'init' method is resolved as the copy-initializer. This warning is intended to help aid the transition to 'init='.

Some tests were still relying on 'init' and have been updated to use 'init='.

Testing:
- [x] local + futures
- [x] gasnet + futures
- [x] memleaks

### CODE REVIEW

**Comment by bradcray** [comment]
This looks great to me, thanks!

**Comment by bradcray** [comment]
Oh, belatedly: does any documentation need to be updated?

**Comment by benharsh** [comment]
'init=' is not yet described in the language spec, it's just a technote at the moment.

**Comment by bradcray** [comment]
OK, but does the technote (or any other documentation) need updating as a result of this?   E.g., specialMethods.chpl?  Looks like records.chpl already has been, but are there others?  Or maybe what we did for 1.19 already puts us in good shape?

**Comment by benharsh** [comment]
I noticed another point in the compiler where we conditionally try to resolve 'init' before 'init=', and just pushed a commit to issue a warning in that case. A small number of tests were updated.

I'm not aware of any documentation that needs updating.

**Comment by bradcray** [comment]
This was the paragraph in specialMethods.chpl that I thought was worth updating:

```
// An initializer named ``init`` is called when creating an instance of the       
// class or record, for example with the ``new`` keyword. An initializer          
// accepting zero arguments is called a *default initializer*.  An initializer    
// that takes another instance of the same class or record is called a            
// *copy initializer*.    
```

(in that it suggests that the copy initializer is just another initializer named `init()`).

**Comment by benharsh** [comment]
Fixed ``specialMethods.chpl``.

I grepped around the primers for more occurrences of "copy init", "copy-init", "\`\`init\`\`" and didn't see anything.

**Comment by bradcray** [comment]
Good enough for me, thanks!

**Pull request merged**
