### PR TITLE
Add tests ensuring that package modules can compile

### PR DESCRIPTION
**Pull request by bradcray**
A common cause of surprises in nightly testing is that
package modules that aren't tested in vanilla linux/Mac
configurations blow up only in the configurations that
test them—i.e., those for which a given library is
available (or assumed to be available).

This PR attempts to address this by creating tests that
ensure that we can codegen programs that use the packages
without trying to link them.  In this way if anything
goes wrong at the Chapel level, we'll know about it in
one of those vanilla test runs.

The approach I took here was to

* symbolically link to a test that exercises the package when we test
  that package
* have the compiler stop compiling before the codegen pass via COMPOPTS (originally, I had it stop after the codegen pass, but Michael pointed out that LLVM uses the headers during codegen, such that this wouldn't work)
* skip execution via NOEXEC
* make sure the output is quiet via empty .good files

Note that this is not bulletproof by any means.  If the package
in question runs into problems only when some other routines in
it are called, then these tests won't catch it.  However, this
should head off some general catastrophic failures that could
be avoided in any use of the module which are the kind I've been
running into most often while trying to lock down the default
namespace better.

### CODE REVIEW

**Comment by bradcray** [comment]
> I am surprised you did not have COMPOPTS say `--no-codegen`

I wanted to make sure that nothing would break during codegen either.

**Comment by mppf** [comment]
> > I am surprised you did not have COMPOPTS say `--no-codegen`
> 
> I wanted to make sure that nothing would break during codegen either.

I would expect link errors if these are run on a system without the required dependencies? In that event it seems that `--no-codegen` would make more sense.

**Comment by ronawho** [comment]
It uses `--stop-after-pass codegen` as an alternative to `--no-codegen`. It runs codegen, but not makeBinary, so the backend compiler/linker won't run

**Comment by mppf** [comment]
Right but that won't work with `--llvm` because the headers (that are presumably missing) will be needed during codegen (rather than after).

**Comment by ronawho** [comment]
Hmm, interesting. I didn't realize the headers are needed at codegen time for llvm

**Comment by bradcray** [comment]
I didn't know that either, thanks.

**Pull request merged**
