### PR TITLE
Update to hwloc 1.11.1

### PR DESCRIPTION
**Pull request by ronawho**
Update hwloc to 1.11.1 and disable libudev (a new dependency)

For a list of changes in 1.11.1 see:
  https://raw.githubusercontent.com/open-mpi/hwloc/v1.11/NEWS

We didn't have any patches applied to 1.10.1 so there's nothing to carry over
to 1.11.1.

I did a standard test run and made sure the performance of stream is still what
we expect (it requires hwloc working right to get good perf.)

I also did a `make check` on:
  darwin
  linux
  XC40 (gnu, intel, pgi)

### CODE REVIEW

**Comment by ronawho** [comment]
Sitting on this for a the time being. I can't build on chapcs00, but I can on the rest of the chapcs* boxes.

Building hwloc with `--disable-libudev` allows it to build on chapc00. I don't actually know what that flag does, I just saw it in hwloc's [changelog] (https://raw.githubusercontent.com/open-mpi/hwloc/v1.11/NEWS) and figured I'd give it a shot

The only difference I see between chapcs00 and the rest is that the others have some mpi stuff in their PATH and  LD_LIBRARY_PATH. e.g. on all but chapcs00:

```
LD_LIBRARY_PATH=/usr/lib64/mpi/gcc/openmpi/lib64
```

**Comment by ronawho** [comment]
Think we figured out what's going on: 

libudev is installed on chapcs00, but not any other machines. However, only the .so is available but we do static linking for our third party libraries. hwloc is able to build fine, but when qthreads tries to compile a test to see if hwloc is working it does so statically and the linker unsuccessfully tries to find the .a for libudev. 

Greg and I are thinking about solutions now. 

FYI we could just disable libudev since we don't actually need it, but the static linking issue is something we need to fix anyways so it might be worth tackling now.

**Comment by ronawho** [comment]
@gbtitus good to merge?

**Comment by gbtitus** [comment]
Yep!  Good to merge.

**Pull request merged**
