### PR TITLE
Throw -srequireThreadedMPI=false for all mpicc testing with OpenMPI.

### PR DESCRIPTION
**Pull request by gbtitus**
If we're using MPI from OpenMPI, it appears we need to arrange to not
make concurrent MPI calls from multiple tasks/threads.  Do that here.

(We didn't/wouldn't need to do this with MPICH, but we switched away
from MPICH MPI in #14316 because we had trouble getting it to work with
our SLES12 testing systems.)

### CODE REVIEW

**Comment by gbtitus** [comment]
@npadmana you might be interested in this one also.

**Comment by gbtitus** [comment]
@ronawho points out this will throw `-s` on a config var that may not exist.  Will revisit.  For now I'm closing it.

**Comment by npadmana** [comment]
I'm not sure the Chapel-MPI interop works in general without threaded MPI. In particular, I think this is comm-backend dependent -- I'm pretty sure with the GASNet MPI backend, it can result in deadlocks. I think with ugni, it works (which was the reason I added this in).

I'll note that OpenMPI has renabled thread support in general.... although I don't remember if it's on by default.

**Comment by gbtitus** [comment]
The output from `mpirun --version` with the gnu-openmpi module we have available on the system where we're testing is `1.10.6rc1`.  Unfortunately, `ompi_info --all` with this version says `Thread support: posix (MPI_THREAD_MULTIPLE: no, ...)`.

**Comment by ronawho** [comment]
Over in https://github.com/chapel-lang/chapel/pull/14417, I'm just switching our testing back to using mpich. 

(For a little more context -- we used to use MPICH, but when we upgraded machines that install was no longer compatible, so we swapped to using a system version of OpenMPI. That system version didn't have MPI_THREAD_MULTIPLE support, so I ended up just building/installing mpich from source.)

**Pull request closed without merging**
