### PR TITLE
Update Fortran array to Chapel DR array test

### PR DESCRIPTION
**Pull request by daviditen**
Move the functions for translating between Fortran and Chapel arrays into
their own module.

Update a domain to use a lower bound of 1 and assert that the `lower_bound` field from the `CFI_dim_t` record is 0.

Assert that the `sm` field from the `CFI_dim_t` record is what we expect for
a contiguous array. `sizeof(eltType)` in the first dimension and
`eltsInPreviousDims*sizeof(eltType)` in other dimensions.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
> Update a domain to use a lower bound of 1 and assert that the lower_bound field from the CFI_dim_t record is 0.

Wait, so does that mean that if the Fortran array is indices `0..n`, the Chapel array will be `1..(n+1)`?

**Comment by daviditen** [comment]
> Wait, so does that mean that if the Fortran array is indices 0..n, the Chapel array will be 1..(n+1)?

That's a confusing thing about the CFI interface.  For regular arrays (nonpointer, nonallocatable) the `lower_bound` is always 0, regardless of what the actual bounds were in the Fortran code.  Fortran arrays default to 1-based, so this does as well.

**Comment by lydia-duncan** [comment]
Oh, okay.  This seems fine, then

**Comment by daviditen** [comment]
Thank you!

**Pull request merged**
