### PR TITLE
Support type directive when generating rst files in chpldoc.

### PR DESCRIPTION
**Pull request by thomasvandoren**
Update VarSymbol::printDocs() and VarSymbol::docsDirective() to generate
the `.. type::` directive for type aliases at the global scope.

To help, add VarSymbol::isType() helper that wraps hasFlag(FLAG_TYPE_VARIABLE).
Also, convert uses of VarSymbol::hasFlag(FLAG_TYPE_VARIABLE) to this new
VarSymbol::isType() in compiler.

I verified this works by running chpldoc over modules/standard/CommDiagnostics.chpl,
which has one of these types at the module scope.

This does not work for type aliases inside classes. It is difficult to discern type aliases
and generic types at this level of the compiler.

### CODE REVIEW

**Comment by thomasvandoren** [comment]
@lydia-duncan -- Will you please review?

**Comment by thomasvandoren** [comment]
@lydia-duncan  -- Sorry for the delay, now it is ready for review. Will you please review?

(I re-running full testing now.)

**Comment by thomasvandoren** [comment]
Full test pass came up clean.

**Comment by lydia-duncan** [comment]
Aw man, sorry I didn't see this when I got back yesterday.  I'll look at it right away.

**Comment by lydia-duncan** [comment]
This looks great, thanks!

**Pull request merged**
