### PR TITLE
Remove amudp launch back-tic hack.

### PR DESCRIPTION
**Pull request by gbtitus**
Now that the GASNet amudprun spawner handles shell meta-characters in command line arguments properly, we can remove the hack we added to not forward any environment variables whose values contained a back-tic.  (amudprun doesn't forward the environment automatically, so we do it ourselves using explicit -E options to the target process, thus we need the command line argument processing to be able to handle such arguments.)

### CODE REVIEW

**Comment by gbtitus** [comment]
@ronawho , here's the follow-up we talked about.

**Comment by gbtitus** [comment]
@mppf , you may be mildly interested in this one, since it reverts a hack/workaround of yours that is no longer needed.

**Comment by ronawho** [comment]
looks good. Do we have tests that check that we correctly forward env vars with special characters in them?

**Comment by gbtitus** [comment]
We didn't have such a test before, but we have one as of this PR.  :-)

**Comment by ronawho** [comment]
Oh, whoops. Embarrassing that I missed the new tests..

**Pull request merged**
