### PR TITLE
Avoid a warning from clang about calling 'creal' without capturing the result

### PR DESCRIPTION
**Pull request by daviditen**
A bit of code in IO.chpl calls cplx.re.type, which ends up generating a call
to creal() without capturing the result since the use of the result was only
for a .type expression and was removed after function resolution.

Instead of fixing the underlying problem, just avoid it in this one spot. A
better fix would be to not evaluate the rest of the expression for .type calls.

Added a .future test that calls cplx.re.type.  It is skipped if not using
clang.  It includes --no-cc-warnings in a .compopts file because start_test
uses --cc-warnings.  Oddly, using the --cc-warnings flag causes this warning
to NOT be issued. The warning is:

warning: ignoring return value of function declared with const attribute [-Wunused-value]

### CODE REVIEW

**Comment by bradcray** [comment]
Looks great David.  Just two small comments:

* Is there any reason not to add a .bad file for the future?

* I think the .future also fails for CHPL_TARGET_COMPILER=gnu on darwin, but I'm guessing that writing the skipif for that case is too fiddly to bother with and that we feel clang sufficiently guards against that case?  (I'm definitely OK with that if so)

**Comment by daviditen** [comment]
Thanks. 

* I didn't include a .bad file because the warning includes the path to the .c file, which is likely to change.  We'd need to add a .prediff to strip out that path, which seemed like more effort than it was worth.

* I think this would not fail for CHPL_TARGET_COMPILER=gnu on darwin if it was using gcc for real, e.g. a homebrew install.  The gcc that is there by default is just a renamed clang ('gcc --version' reports that it is clang on my laptop).

**Comment by daviditen** [comment]
I haven't verified the second point though because I don't have the homebrew install of gcc on my computer.

**Comment by bradcray** [comment]
OK, sounds good -- merge away!

**Comment by daviditen** [comment]
Thanks!

**Pull request merged**
