### PR TITLE
Fixed Man Page Issues 

### PR DESCRIPTION
**Pull request by shubhamkmr04**
@bradcray This is the new PR (continuation of PR #17455) I have created for our Manpage issues with the clean commits.

This PR locally converts `-` to `--` from flags of Manpage by not affecting the formatting of any other page, this [(comment)](https://github.com/chapel-lang/chapel/pull/17400#issuecomment-799576600) raises the following issue.

These changes I made to locally change it to `--` for only Manpage:

-  Converted **--** to **\\--** in the files `man/chpl.rst` and `man/chpldoc.rst` 
- Modified the file `test/man/checkManPages` according to our new character `\`

[ ✔️ ]  Passed the test `util/start_test test/man/`

### CODE REVIEW

**Comment by shubhamkmr04** [comment]
I think I have fixed all the issues regarding this problem.

1. We can see *--* on our `man.html`
Screenshot from 2021-05-08 15-09-03

2. It's passing the test `util/start_test test/man/` ( as I have changed the `CheckManPages` according to our new symbol `'\'`)
Screenshot from 2021-05-08 15-12-11

3. If I change a flag `--baseline` to `--fake-baseline` in `man/chpl.rst` , the test is giving me error so we know that the test is checking exactly what it was supposed to do.
Screenshot from 2021-05-08 15-15-18

**Comment by shubhamkmr04** [comment]
@bradcray I understand. Actually, my *Visual Studio Code* automatically changed `' '` to `" "` and changed the indentation when I saved the changes. Sorry for the inconvenience, I will fix it.

**Comment by bradcray** [comment]
I wondered if it was something like that — thanks!

**Comment by bradcray** [comment]
@shubhamkmr04 : This looks good to me, thanks!  In addition to verifying the things you mentioned above, I also did a diff against the docs generated prior to this branch, which makes it appear that all changes are as expected; and I also verified that the original motivating issue in https://github.com/chapel-lang/chapel/pull/17400#issuecomment-799576600 was resolved.

I'll be ready to merge this once you update the OP to describe the change.

Two "extra credit things that could be considered (or left for a future PR or issue):

* update `man/chpldoc.rst` similarly
* what would it take to make the script complain if the `--` form is used rather than `\--` on the man page?  This would have the benefit of preventing people from introducing new errors going forward; and it would've caught that chpldoc's man page is not similarly formatted if it were already doing it.

**Comment by shubhamkmr04** [comment]
@bradcray I have described the changes in the description and updated `man/chpldoc.rst`  to introduce `\` here as well.

This is how chpldoc page looks now:

Screenshot from 2021-05-11 14-59-21

**Comment by shubhamkmr04** [comment]
@bradcray  I think the main issue of this PR is resolved. As you have mentioned above, what if someone uses `--` instead of `\--`. Right now, if we use `--` on the man page, we don't get any error on our test but the `--` changes to `-` on that flag of the man page. I think we should wrap up this PR, and I would be creating a new PR for that (so our script would give a warning on someone using `--` on manpage). Thanks.

**Comment by bradcray** [comment]
@shubhamkmr04 : Sorry, somehow I saw your commit, but missed your latest note.  I agree with the plan to merge this PR and split any effort to ensure man pages only use `--` into a separate issue.  I'm running a final test and then will plan to merge.

**Comment by bradcray** [comment]
Thanks for taking care of this @shubhamkmr04!  I've split the idea of having the script check for mis-formatted flags into issue #17714.

**Pull request merged**
