### PR TITLE
dyno: Remove meaningless const qualifier for enum return type

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
dyno: Remove meaningless const qualifier for enum return type

In my recent work on the `ErrorMessage` class I mindlessly specified
`const Kind`, where `Kind` is an enum type (and thus the `const`
qualifier is meaningless). Some compiler configurations treat this
warning as an error, so remove the `const`.

Signed-off-by: David Longnecker <dlongnecke-cray@users.noreply.github.com>

### CODE REVIEW

**Comment by bradcray** [comment]
Thanks David!  Were you able to find a compiler with which you could reproduce this in-house?

**Comment by dlongnecke-cray** [comment]
Testing!

**Comment by dlongnecke-cray** [comment]
Yes, I could reproduce in-house with Intel `icpc`.

**Comment by bradcray** [comment]
Ah, I just realized what I was probably missing... we tend to use g++ when building the compiler and I _think_ that the old testing we did of building the compiler with other compilers has long since been disabled/retired?

**Comment by bradcray** [comment]
Oh, no, I was wrong.  It looks like we are still testing building the compiler with Intel via PrgEnv-intel.  But maybe not with CHPL_DEVELOPER enabled?  Were/are you able to reproduce this with PrgEnv-intel/6.0.11 loaded by any chance?

**Comment by dlongnecke-cray** [comment]
I knew I should have written the version down in my comment...let me build again.

**Comment by bradcray** [comment]
@dlongnecke-cray : Did you ever get the chance to check on whether this reproduced with PrgEnv-intel/6.0.11?

**Comment by dlongnecke-cray** [comment]
With a build on `main`, one day old, and `PrgEnv-intel/6.0.11` I see this frequently:

```
icx: command line warning #10430: Unsupported command line options encountered
These options as listed are not supported.
For more information, use '-qnextgen-diag'.
option list:
	-wr181,188
```

Not sure if it is a known issue.

Went and undid the diffs here to reproduce.

With `CHPL_DEVELOPER` unset:

```
../../../dyno/include/chpl/queries/ErrorMessage.h(93): warning #858: type qualifier on return type is meaningless
    const Kind kind() const { return kind_; }
```

And I see the same error even if `CHPL_DEVELOPER=true`.

I have everything loaded so let me know if there's anything else you'd like me to check.

**Comment by bradcray** [comment]
> With CHPL_DEVELOPER unset:

Oh sheesh, you're absolutely right.  Apparently I never looked at our nightly logs close enough to see that they contained the warning as well, but that because we don't throw `-Werror` we don't learn about it:

https://chapel-ci.us.cray.com/job/correctness-test-whitebox-cray-xc/COMPILER=intel,COMP_TYPE=HOST-TARGET,label_exp=whitebox-cray-xc/754/consoleFull

OK, so I think that https://github.com/Cray/chapel-private/issues/3138 captures our next steps here, where we just have to decide whether we want to do it and have the cycles to do so.  Thank you, and sorry not to have noticed the warnings in our logs before (I could've sworn I went looking for them, but ...).

**Pull request merged**
