### PR TITLE
Handle lack of RAW and WAR atomic ordering in message-order-fence

### PR DESCRIPTION
**Pull request by jhh67**
Change the message-order-fence implementation to not require read-after-write (`FI_ORDER_ATOMIC_RAW`) and write-after-read (`FI_ORDER_ATOMIC_WAR`) ordering for atomic operations. As an initial fix the `ofi` comm layer now:

* doesn't ask for these orderings when looking for a message-order-fence provider

* fences all fetching atomic operations. This ensures read-after-write ordering, while write-after-read is ensured by the MCM. All fetching atomic operations are fenced, eventually it should be done selectively only when a fetching atomic follows a non-fetching.

See https://github.com/Cray/chapel-private/issues/4140 for details.

Resolves https://github.com/Cray/chapel-private/issues/4140 and closes https://github.com/Cray/chapel-private/issues/4254.

Also resolves https://github.com/Cray/chapel-private/issues/4138.

Signed-off-by: John H. Hartman <jhh67@users.noreply.github.com>

### CODE REVIEW

**Comment by ronawho** [comment]
Can you check the performance impact of this? My initial thought would be to run comm-ops with 1, 8, 64, and 128 threads. Could also updated ra-atomic to use fetching AMOs and see the perf impact on something a little bigger than the microbenchmark.

**Comment by jhh67** [comment]
Performance results running on an HPE Cray EX:

**comm-ops**

% chpl comm-ops.chpl --fast --no-cache-remote --no-optimize-forall-unordered-ops -scommDiagsPrintUnstable

% env CHPL_RT_NUM_THREADS_PER_LOCALE=1 ./comm-ops -nl 2

| Benchmark | main  | PR    |
|-----------|-------|-------|
| GET       | 1.63s | 1.47s |
| PUT       | 0.13s | 0.11s |
| FAMO      | 1.72s | 1.95s |
| NFAMO     | 0.28s | 0.49s |

% env CHPL_RT_NUM_THREADS_PER_LOCALE=8 ./comm-ops -nl 2

| Benchmark | main  | PR    |
|-----------|-------|-------|
| GET       | 1.77s | 1.77s |
| PUT       | 0.96s | 0.91s |
| FAMO      | 1.95s | 2.64s |
| NFAMO     | 3.28s | 2.73s |

% env CHPL_RT_NUM_THREADS_PER_LOCALE=64 ./comm-ops -nl 2

| Benchmark | main   | PR     |
|-----------|--------|--------|
| GET       | 1.72s  | 1.85s  |
| PUT       | 1.40s  | 4.47s  |
| FAMO      | 1.78s  | 2.66s  |
| NFAMO     | 13.69s | 20.21s |

% env CHPL_RT_NUM_THREADS_PER_LOCALE=128 ./comm-ops -nl 2

| Benchmark | main   | PR     |
|-----------|--------|--------|
| GET       | 1.80s  | 1.82s  |
| PUT       | 9.35s  | 9.25s  |
| FAMO      | 1.85s  | 2.78s  |
| NFAMO     | 40.74s | 27.35s |

**ra-atomics**

These are the performance results of running `ra-atomics` with the following modification:
```
-    T(r & indexMask).xor(r);
+    T(r & indexMask).fetchXor(r);
```
% start_test --perflabel ml- test/release/examples/benchmarks/hpcc/ra-atomics.chpl

| main          | PR            |
|---------------|---------------|
| 0.440083 GUPS | 0.315457 GUPS |

**Comment by ronawho** [comment]
In that table `FAMO` is really the only thing we're expecting to have changed, so the `PUT`/`NFAMO` seems like expected noise from known thread-hot issues.  Let's get rid of the PUT/NFAMO rows since I think the noise just makes the results confusing. 

Can you recheck the `GET` results? I was expecting those to be unchanged and fairly stable.

**Comment by jhh67** [comment]
I removed both the PUT and NFAMO rows from the table. I also re-ran the benchmarks and entered the new results. The GET  results still jump around.

**Comment by ronawho** [comment]
Ok, let's remove GET too and just keep this about FAMO

**Comment by jhh67** [comment]
I used `salloc` to use the same two nodes for all `comm-ops` tests and now the results are more stable. Should we still remove GET?

**Comment by ronawho** [comment]
Can you add the reproducer from https://github.com/Cray/chapel-private/issues/4140 as a test in `test/runtime/configMatters/comm/`?

I have also confirmed that this resolves https://github.com/Cray/chapel-private/issues/4138 (please add to PR description)

**Comment by jhh67** [comment]
Added the test case and updated the PR description.

**Review by ronawho — APPROVED** [review]
👍

**Pull request merged**
