### PR TITLE
Fix realloc corner cases

### PR DESCRIPTION
**Pull request by bradcray**
This fixes a few of corner cases in the "can we realloc this array" logic that I implemented and Greg finished off for me:

* our realloc logic currently doesn't work when reallocating a size 0 array or when reallocating an array down to size 0, so don't use realloc for these cases.  It seems like these could be addressable (if we thought there was benefit in using realloc for them?), but I'm not sure there's much point

* if the array's element type is not POD, we can't use realloc if the array is shrinking in size because we have to call deinit() on each element, and realloc isn't going to do that for us.  So only use realloc for POD eltTypes or when growing the array (since we already call init() on the new elements)

I also added / modified some tests to lock in this behavior.

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho / @gbtitus: I'm going to merge this tonight to keep testing clean(er), but would you post-merge review tomorrow / when you're back?

**Comment by mppf** [comment]
> if the array's element type is not POD, we can't use realloc if the array is shrinking in size because we have to call deinit() on each element, and realloc isn't going to do that for us. So only use realloc for POD eltTypes or when growing the array (since we already call init() on the new elements)

I do not think we need to change the situation immediately, but it seems to me that a non-POD record element type can be reallocated. The record will change position ("move") without running any init= or deinit at all.

**Comment by bradcray** [comment]
@mppf: The problem isn't due to bit copying, but rather due to a situation like the following:

```chapel
record R {
  ...
  proc deinit() { ... }
}

var D = {1..10};
var A: [D] R;
D = {1..5};
```

Specifically, realloc() won't call `R.deinit()` on `A[6..10]` when `D` is reassigned, which the language requires, which is why I tied it to POD-ness (yet only in the case that the realloc was shrinking the array).

Thinking about this PR again this morning, it occurred to me that it would probably be sufficient to see whether or not the record had a `deinit()` routine rather than linking it to POD-ness (in case there is or becomes a difference between those two queries).  I didn't easily find a `hasDeinit()` query at present.  I'm not sure whether a `canResolve()` on `R.deinit()` would work (or should work) given that a user can't typically write that call.

**Comment by mppf** [comment]
@bradcray - in that event, shouldn't you just run `deinit` on the variables that are about to be removed (namely `A[6..10]` in your example)?

I would imagine a similar issue with needing to default-init if the domain is expanding. You should only default-init the new elements.

**Comment by bradcray** [comment]
> in that event, shouldn't you just run deinit on the variables that are about to be removed (namely A[6..10] in your example)?

Oh, that's an interesting point.  I think in the heat of trying to keep testing from blowing up after I was already "off the clock", I was thinking I didn't have this ability either because (a) I couldn't call deinit() explicitly in module code and/or (b) I was thinking that the need to call deinit() would depend on whether or not realloc returned a new memory segment or the current one.  After a night's sleep, it now seems obvious that I was off-base on (b), and presumably I can look through some ddata code to see how we accomplish (a) today.

**Pull request merged**
