### PR TITLE
Update some more constructors to initializers

### PR DESCRIPTION
**Pull request by lydia-duncan**
Looks like whatever error Brad was encountering when he first looked at:
- studies/hpcc/STREAMS/bradc/stream-block1dpar-arr
- studies/hpcc/STREAMS/bradc/stream-block1dpar
- studies/hpcc/common/bradc/unit/multipleDomains

is gone.

test/studies/hpcc/common/bradc/BradsBlock1DPar.chpl:
These initializers would benefit from being able to set const and type
fields during Phase 2.  I needed to rearrange one slightly due to its reliance
on a helper function (which I made internal to the initializer with seemingly no
consequences) and its out-of-order initialization of const fields.

test/multilocale/vass/this-in-taskfns-in-ctors.chpl:
Pretty trivial update.

Passed a full paratest, and a spot check of CHPL_COMM=gasnet for
test/multilocale/vass/this-in-taskfns-in-ctors.chpl

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@bradcray - if this isn't what you tried, does what you tried still fail?

@vasslitvinov - would you review the test in your directory?  I left domains/vass/assoc-idxtype-error-2.chpl because it confused me and test/classes/vass/old-destructor-name.chpl because I wasn't sure if we should leave it testing both old constructors and old destructors or if just old destructors was fine.

**Comment by vasslitvinov** [comment]
The change to my test looks fine.

**Comment by bradcray** [comment]
@lydia-duncan: Your approach was a little different than what I tried, but what I tried is working now as well.  See https://github.com/bradcray/chapel/commit/ef203af69471871ce6ba05afbe2c4a2e6ad4c278 for how I'd do this.

**Comment by lydia-duncan** [comment]
I'm also surprised/disappointed the modification of locDist's contents in phase 2 of your version isn't caught.

**Comment by lydia-duncan** [comment]
Do you have a strong preference for the halt message being before or after the super.init() call?

**Pull request merged**
