### PR TITLE
Refactor standard layout/distribution documentation

### PR DESCRIPTION
**Pull request by bradcray**
This mod removes the separate documents for layouts and
distributions which seemed to add little value beyond
what was already in the top-level layoutdist.rst file, and
looked somewhat clumsy on that page as hyperlinks
rather than headings.  

On email, @ben-albrecht indicated that he'd wanted
to do something like this as well, but couldn't get the
sidebar to look the way he wanted.  In my attempt,
I changed the top-level heading from a '------' style
to a '=====' style, which is what we use in the user's
guide as well to get a similar effect.  I don't see any
particular downside to this, and it seems to render well.

### CODE REVIEW

**Comment by ronawho** [comment]
Do you have a link to rendered version of this?

**Comment by ronawho** [comment]
Oh probably not since you're not on the network, I can build locally

**Comment by ronawho** [comment]
:+1:

**Comment by bradcray** [comment]
Right, if I'd been in the office, I would've supplied a URL, but the one I would've supplied today wouldn't have been useful.  :(

**Pull request merged**
