### PR TITLE
Add future for param field with non-param field for default value

### PR DESCRIPTION
**Pull request by cassella**
Add future for compiler segfault on a class with a param field whose default value is given by a non-param field.

test/classes/initializers/generics/param-field-default-value-non-param-field.chpl

### CODE REVIEW

**Comment by lydia-duncan** [comment]
I'm not getting a compiler segfault for this case, just a the same "tmp_chpl" undeclared with the writeln call.  Are you sure this branch is correct?

**Comment by cassella** [comment]
Hmm.  I still get a seg fault with current master:

```
fortytwo@magrathea:~/src/chapel (param-field-default-value-non-param)$ chpl test/classes/initializers/generics/param-field-default-value-non-param-field.chpl 
internal error: seg fault [misc.cpp:564]
```
```
fortytwo@magrathea:~/src/chapel (param-field-default-value-non-param)$ chpl --version
chpl version 1.17.0 pre-release (fd987c0)
```

**Comment by lydia-duncan** [comment]
That is the same version I show.  Did you rebuild the compiler before running?  I tried running with --devel through start_test, and running without start_test, and I can't see the segfault.

**Comment by lydia-duncan** [comment]
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

chpl version 1.17.0 pre-release (fd987c09b8)

make -j returns cleanly

**Comment by cassella** [comment]
/me scratches head.

``make clobber; make``

```
fortytwo@magrathea:~/src/chapel (param-field-default-value-non-param)$ chpl test/classes/initializers/generics/param-field-default-value-non-param-field.chpl
internal error: seg fault [misc.cpp:564]
```

```
fortytwo@magrathea:~/src/chapel (param-field-default-value-non-param)$ chpl --print-passes test/classes/initializers/generics/param-field-default-value-non-param-field.chpl 
                            init :   0.038 seconds  [      243]
                           parse :   0.278 seconds  [   256883]
                     checkParsed :   0.088 seconds  [   256883]
                            docs :   0.011 seconds  [   256883]
                     readExternC :   0.008 seconds  [   256883]
          expandExternArrayCalls :   0.012 seconds  [   256883]
                         cleanup :   0.069 seconds  [   257409]
                    scopeResolve :   1.430 seconds  [   315919]
                  flattenClasses :   0.008 seconds  [   315919]
                       normalize :   0.859 seconds  [   588372]
                 checkNormalized :   0.021 seconds  [   588372]
           buildDefaultFunctions :   0.433 seconds  [   637674]
             createTaskFunctions :   0.051 seconds  [   641415]
                         resolve :   4.554 seconds  [  1303754]
                  resolveIntents :   0.011 seconds  [  1303754]
                   checkResolved :   0.016 seconds  [  1303754]
replaceArrayAccessesWithRefTemps :   0.007 seconds  [  1303754]
                flattenFunctions :   0.030 seconds  [  1305520]
              cullOverReferences :   0.018 seconds  [  1305580]
              lowerErrorHandling :   0.025 seconds  [  1306873]
                 callDestructors :   0.061 seconds  [  1339131]
                  lowerIterators :   0.208 seconds  [  1402313]
                        parallel :   0.620 seconds  [  1416040]
                           prune :   0.092 seconds  [  1416040]
                 bulkCopyRecords :   0.013 seconds  [  1416250]
  removeUnnecessaryAutoCopyCalls :   0.015 seconds  [  1416250]
                 inlineFunctions :   0.312 seconds  [  1521879]
                   scalarReplace :   0.033 seconds  [  1526737]
                  refPropagation :   0.128 seconds  [  1531453]
                 copyPropagation :   0.451 seconds  [  1531453]
             deadCodeElimination :   0.110 seconds  [  1531454]
              removeEmptyRecords :   0.006 seconds  [  1531454]
                 localizeGlobals :   0.027 seconds  [  1533145]
         loopInvariantCodeMotion :   0.137 seconds  [  1533145]
                          prune2 :   0.025 seconds  [  1533145]
       returnStarTuplesByRefArgs :   0.011 seconds  [  1533248]
internal error: seg fault [misc.cpp:564]
```

```
chpl --gdb test/classes/initializers/generics/param-field-default-value-non-param-field.chpl
...
(gdb) r
Starting program: /home/fortytwo/src/chapel/bin/linux64/chpl test/classes/initializers/generics/param-field-default-value-non-param-field.chpl

Program received signal SIGSEGV, Segmentation fault.
0x000000000048a835 in Expr::isRef (this=0x0) at expr.cpp:125
125       return this->qualType().isRef();
(gdb) bt          
#0  0x000000000048a835 in Expr::isRef (this=0x0) at expr.cpp:125
#1  0x000000000048a92a in Expr::isRefOrWideRef (this=0x0) at expr.cpp:139
#2  0x00000000005fe268 in fixAST () at insertWideReferences.cpp:2170
#3  0x0000000000600b51 in insertWideReferences () at insertWideReferences.cpp:2596
#4  0x0000000000565764 in runPass (tracker=..., passIndex=35, isChpldoc=false) at runpasses.cpp:202
#5  0x0000000000565678 in runPasses (tracker=..., isChpldoc=false) at runpasses.cpp:169
#6  0x0000000000560889 in main (argc=2, argv=0x7fffffffe1f8) at driver.cpp:1345
```

(Maybe it's due to my ``COMM=gasnet``?)

**Comment by lydia-duncan** [comment]
That does appear to be the difference!  I'm surprised that you didn't see this error for the other futures.  This seems to indicate that the problem is something that would get caught earlier if we were slightly more careful within the compiler (which makes sense, given how it is behaving).  Can you run with --verify and double check that you get an internal error at CHE0069?  If so, I think this test should get a .compopts file with --verify so that it has more consistent output across settings

**Comment by cassella** [comment]
Indeed it does.  I should be able to add the .compopts tonight.  Would you like a ``.bad`` file too?

For reference and for those playing along at home, here's the output on a branch that has this PR merged to master:

```
fortytwo@magrathea:~/src/chapel (hrm)$ chpl --verify test/classes/initializers/generics/param-field-default-value-non-param-field.chpl 
$CHPL_HOME/modules/internal/ChapelIO.chpl:255: In function 'writeThisFieldsDefaultImpl':
$CHPL_HOME/modules/internal/ChapelIO.chpl:279: internal error: Refers to a local/arg in another function [checkAST.cpp:69]
```

**Comment by lydia-duncan** [comment]
Nah, let's leave off the .bad file, but maybe note the different output variations in the .future file (or the issue to which it is connected)

**Comment by lydia-duncan** [comment]
Thanks, @cassella!

**Pull request merged**
