### PR TITLE
Convert Nikhil's code to work with test system

### PR DESCRIPTION
**Pull request by bradcray**
In this patch, I changed Nikhil's code to work with the test system and did some minor housekeeping as well.

To get it working with the test system, I:
* changed the NOTEST file into a SKIPIF and made it dependent on whether or not FFTW_DIR is set
* added a COMPOPTS file so that the tests are compiled/linked against FFTW
* added .notest files for the FFTW*.chpl modules
* added a .good file for the testFFTW.chpl file
* made a clone of the testFFTW.chpl file for the seg faulting case with .bad, .good. and .future files

The housecleaning I applied to the files included:
* simplifying the 'use' logic slightly for the test*.chpl files
* collapsing the FFTWsegfault.chpl and FFTWsegfaultfix.chpl cases into a single file with a config param guarding whether or not the writeln()s should be used.

So far, I've determined that the segfault version is generating valgrind errors (and noted it in the .future file), but haven't gotten further than that yet.

### CODE REVIEW

**Comment by bradcray** [comment]
Nikhil should probably review this since it's his code I'm messing with.  @thomasvandoren may also be interested from the sidelines.  Nikhil, most of the testing machinery here is probably pretty obvious from naming/contents, but if you want more information, see https://github.com/chapel-lang/chapel/blob/master/doc/developer/bestPractices/TestSystem.txt

**Comment by npadmana** [comment]
Brad - all of this looks good to me. Something we may want to do is switch the testing code to output "true" or "false" as long as the maximum diff between the arrays are small. That way, we will not rely on the fact that the code produces exactly the same floating point number every time across all systems (and really, all that really matters is that this number is small).

**Comment by bradcray** [comment]
I was wondering whether this test was sensitive to floating point roundoff and agree that having the ability to have it pass within some tolerance sounds smart.  Let's safe that for a future commit, though.  

Since we're the main two people who will care for the near-term, I'm curious: If you do a start_test in this directory, does it pass for you, or do the results I generated in the .good not match yours?

**Comment by npadmana** [comment]
It worked on my system. It's worth keeping in mind that the test is already comparing two results; the outputs are the absolute differences between these. However, I agree this can wait until a later time.

**Pull request merged**
