### PR TITLE
added JIRA section and link

### PR DESCRIPTION
**Pull request by MrMormon**

### CODE REVIEW

**Comment by ben-albrecht** [comment]
I think this belongs in [`doc/release/bugs.rst`](http://chapel.cray.com/docs/master/usingchapel/bugs.html) rather than the main README. Also, it should state that JIRA issues are visible without creating an account, instead of stating accounts are free.

**Comment by MrMormon** [comment]
I'll add that issues are visible without an account, but how will the user find the bugs.rst file itself when 1.13 is months away?

**Comment by ronawho** [comment]
@MrMormon We could point people to http://chapel.cray.com/docs/master/usingchapel/bugs.html

After every commit we re-build the "master" online documentation, but note that we don't really want to be pointing people to our JIRA just yet so I think we'd be happy with the 1.13 timeframe.

Currently JIRA just has internal developer oriented "bugs" in it, and we aren't really ready to open it up to the world. On our list of 1.13 build/test/release priorities is to move items in $CHPL_HOME/STATUS to JIRA and to start using it as a full-time issue tracker, but we haven't gotten to that yet.

I'm actually surprised you were able to add an issue to JIRA, I thought we had permissions setup to prevent that. 

Our current plan is allow JIRA issues to be publicly viewable, but not editable except by those on the  Core chapel team. We were planning to add a portal to submit bugs, which would be used to populate a new JIRA issue, but we were concerned about allowing anybody to arbitrarily edit issues.

That said, we're always open to suggestions if that doesn't fit with what other open source projects are doing. I know llvm allows you to create issues and just limits what fields you can edit, so that's another approach we've been considering

**Comment by MrMormon** [comment]
@ben-albrecht I see you added a label. There's nothing I can do here until the Chapel team gets JIRA ready. The readme already points to http://chapel.cray.com/docs/master/usingchapel/bugs.html

**Comment by ronawho** [comment]
@MrMormon I think we're just looking for this to be moved from the main README into bugs.rst

**Comment by MrMormon** [comment]
If we don't want the link appearing yet (as I understand would happen if the online docs are rebuilt with this merge), is the label not referring to me?

**Comment by ronawho** [comment]
Sorry, I wasn't clear about this earlier. The 'master' online docs are rebuilt after every commit, but our public links point people to the latest release (currently 1.12) 

For example the main [README] (https://raw.githubusercontent.com/MrMormon/chapel/patch-2/README.rst) points to http://chapel.cray.com/docs/1.12/usingchapel/bugs.html, not http://chapel.cray.com/docs/master/usingchapel/bugs.html

All I meant was that if you *really* wanted to point somebody to the updated bugs.rst before 1.13 you could give them the 'master' link.

If you add this patch to bugs.rst now, the documentation we link to won't be updated until the 1.13 release (and by then JIRA should be ready)

**Comment by MrMormon** [comment]
https://github.com/chapel-lang/chapel/pull/3237 corrects this.

**Pull request closed without merging**
