### PR TITLE
add ExternalArray.makeArrayFromPtr(value, dom)

### PR DESCRIPTION
**Pull request by milthorpe**
Add new overloads of ExternalArray.makeArrayFromPtr and ExternalArray.makeArrayFromExternArray which accept a non-distributed rectangular domain. These can be used to construct multi-dimensional arrays from externally-managed storage

### CODE REVIEW

**Review by e-kayrakli — APPROVED** [review]
@milthorpe -- thanks for the PR!

The changes here look good to me. I will run testing and merge if it is clean. But before that, were you planning to add something else? Or are you ready to hand this off to me?

**Comment by milthorpe** [comment]
I've added a couple of checks to limit this method to rectangular domains that match the size of the backing storage, which works fine with Chapel 1.30. I've also modified the code in line with changes to stridable arrays in Chapel 1.31, however, I'm currently having trouble with Chapel 1.31 linking to GPU kernel code shared objects on our test systems - probably related to the move to LLVM 15. I'll let you know once I've been able to successfully test with Chapel 1.31.

**Comment by milthorpe** [comment]
With the changes for Chapel 1.31 (added in the most recent commit in this PR), this is ready to merge.

**Comment by e-kayrakli** [comment]
Local linux64 and gasnet tests are successful. Merging.

Thanks a lot @milthorpe!

**Pull request merged**
