### PR TITLE
Improve support for doing multiple trials with correctness testing

### PR DESCRIPTION
**Pull request by ronawho**
Multiple trial support was originally added as a performance feature so that we
could get multiple data points. However, having the ability to do multiple
trials is also beneficial for correctness testing. It allows us to run tests
many times in order to try and find sporadic/infrequent failures that only
rarely turn up in nightly testing. This improves multi-trial support so that we
can do a large number of trials over the entire test suite.

There are two main parts of this commit:

- Add the capability to skip any remaining trials for tests that take more than
  X seconds. This is important because we obviously can't do a lot of trials
  for tests that take forever, so we need a way to limit the number of trials
  we do with them

  Threshold is set with: `CHPL_TEST_EXEC_TIME_LIMIT_NUM_TRIALS`

- Force tests that don't work with multiple trials to only do 1 trial. Some
  tests grep and then destroy generated code, or manipulate and destroy
  files/dirs to tests file system routines. These tests destroy the artifacts
  that they check, so multiple trials can't be done. Plus there's no real
  benefit in doing multiple trials for tests that just grep the generated code.

I plan on doing a stupid number of trials for std linux64 and gasnet-everything
testing, as well as some XC testing if there's time. I was able to paratest 120
trials (1/3 of a year's worth of nightly testing) for all tests that run in
under 5 seconds in under 2 hours.

See JIRA 254 for more info: https://chapel.atlassian.net/browse/CHAPEL-254

### CODE REVIEW

**Comment by ronawho** [comment]
@ben-albrecht mind reviewing the sub_test changes?

@lydia-duncan @mppf @bradcray any objections to adding the NUMTRIALS/.numtrials files. It's unfortunate to have to clutter the testing system more, but this is the cleanest solution I could come up with.

**Comment by bradcray** [comment]
I'm OK with it.

**Comment by lydia-duncan** [comment]
I've definitely been able to explicitly request multiple trials for a test run, but it will be nice to specify that on a per-test basis.  Will this reuse the numtrials files already present?  Is there a way to say you want a specific number of trials for correctness and a different number for performance runs?

I don't object to additional files for this purpose.  Thanks, Elliot!

**Comment by ronawho** [comment]
>I've definitely been able to explicitly request multiple trials for a test run, but it will be nice to specify that on a per-test basis. Will this reuse the numtrials files already present? Is there a way to say you want a specific number of trials for correctness and a different number for performance runs?

I should have been more specific. Yes, multiple trials already works for correctness testing, but you couldn't run it over the full suite without getting a bunch of failures. 

Like other correctness vs. perf files you can have a NUMTRIALS/.numtrials file and a PERFNUMTRIALS/.perfnumtrials file

**Comment by ben-albrecht** [comment]
`sub_test` changes look good 👍

**Pull request merged**
