### PR TITLE
Use `localAccess` automatically

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR enables compiler to do some analysis and transformations to use
`localAccess` automatically.

Resolves https://github.com/chapel-lang/chapel/issues/14480

## Change summary
- Add `compiler/optimizations/autoLocalAccess.cpp` and relevant header
- Use public functions in that interface in `normalize`, and `preFold`
- Add new primitive `PRIM_MAYBE_LOCAL_THIS`
- Add a `class ForallOptimizationInfo` in `ForallStmt.h` and add a field of that
  type to `ForallStmt`
- Add compiler flags
  - `--[no-]auto-local-access` (on-by-default)
  - `--[no-]auto-local-access-dynamic` (on-by-default)
  - `--report-auto-local-access` (off-by-default, developer flag)
- Add new helpers in `ChapelAutoLocalAccess`
- Add some helpers to `ChapelArray`
- Add `proc dsiSupportsAutoLocalAccess() param` to domain interface
- Add tests under `test/optimizations/autoLocalAccess`

While there:
- Add missing this-intents to some `localAccess` overloads in `ChapelArray`

  These were causing resolution bugs if a `const` array was passed to a
  blank-intent formal, and if that argument's `localAccess` was called in RHS

## Compiler Analysis and Transormations

Consider:

```chapel
var dom = newBlockDom(space);

var A: [dom] int;
var B: [A.domain] int;
var C = newBlockArr(space, int);
var X = new SomeClass();  // assume X has `this` implemented

forall i in B.domain {
  A[i] = B[i]+C[i]+X[i];
}
```

The goal is to statically use `localAccess` for `A` and `B` and dynamically for
`C` while `X[i]` remains the same.

### PRIM_MAYBE_LOCAL_THIS

We convert a call like `foo[i,j]` to
```
(call PRIM_MAYBE_LOCAL_THIS foo i j staticControl isStaticallyDetermined)
```
during normalize, and prefold all these primitives to either `this` or
`localAccess` during resolution.

### Pre-normalize

For some of the symbols we'll be able to determine statically that they need a
`localAccess` for some it'll depend on dynamic checks. For both, we add static
checks and for dynamic we add extra dynamic checks.

Result of the static checks are used in the following ways
1. the primitive has a `SymExpr` with the static check symbol to mark whether
the original access was a static or dynamic candidate
2. to control param folding duplicate loops. 
3. to override a specific dynamic check if the corresponding static check has
failed. Rationale:

  - We don't want the "global" `dynamicControl` to fail only because one of the
  symbols failed the static check.

  - All `PRIM_MAYBE_LOCAL_THIS` calls that depended on the static check will have
  been prefolded to `this` anyways. So, the dynamicCheck specific to the same
  symbol has no meaning.

Whereas the dynamic checks are only used to choose between
the optimized and un-optimized (or less optimized) loops.

The sketch of the AST after normalize:
```chapel
var dom = newBlockDom(space);

var A: [dom] int;
var B: [A.domain] int;
var C = newBlockArr(space, int);
var X = new SomeClass();  // assume X has `this` implemented

param staticControl1 = staticCheck(A, B.domain);  // true
param staticControl2 = staticCheck(B, B.domain);  // true
param staticControl3 = staticCheck(C, B.domain);  // true
param staticControl4 = staticCheck(X, B.domain);  // false

const dynamicControl = (!staticControl3 || dynamicCheck(C, B.domain)) && 
                       (!staticControl4 || dynamicCheck(X, B.domain));   

if staticControl1 || .. || staticControl4 {
  if (staticControl3 || staticControl4) && dynamicControl {
    forall i in B.domain {
       PRIM_MAYBE_LOCAL_THIS(A,i,staticControl1,true) = 
	 PRIM_MAYBE_LOCAL_THIS(B,i,staticControl2,true) +
	 PRIM_MAYBE_LOCAL_THIS(C,i,staticControl3,false) +
	 PRIM_MAYBE_LOCAL_THIS(X,i,staticControl4,false) +
    }
  }
  else {
    forall i in B.domain {
       PRIM_MAYBE_LOCAL_THIS(A,i,staticControl1,true) = 
	 PRIM_MAYBE_LOCAL_THIS(B,i,staticControl2,true) +
	 C[i] +
	 X[i];
    }
  }
else {
  A[i] = B[i] + C[i] + X[i];
}

```

### During resolution

Based on their respective `staticControl`s, we prefold these primitives to
either `this` or `localAccess`. Meanwhile, the conditional structure is folded
based on the already-existing folding implementation. i.e. this PR doesn't
change anything in that logic, but uses `param` `bool`s only.

A sketch of the AST after resolution:
```chapel
const dynamicControl = dynamicCheck(C, B.domain) &&  // true
                       true;                         // was for X, all access reverted already

if dynamicControl {
  forall i in B.domain {
    A.localAccess[i] = B.localAccess[i]+C.localAccess[i]+X[i];
  }
}
else {
  forall i in B.domain {
    A.localAccess[i] = B.localAccess[i]+C[i]+X[i];
  }
}
```

## Limitations

One obvious limitation is that if the static checks pass for all the dynamic candidates,
but at least one fails the dynamic check, then the dynamic loop is not executed, and
all other candidates will use regular access. There isn't an obvious way to avoid that
without creating a lot of copies of the loop and carrying them all the way to codegen.

Most of the following can be addressed as follow ups depending on we see some
value in relaxing them:

- `var A, B, C: [D] int` causes `B` and `C` to fall through to dynamic path.

- Zippered loops are not analyzed. I don't know if there is a fundamental
  issue with those, and will take a look soon. For now, I wanted to keep the
  scope limited in the initial PR.

- The transformations somehow don't get along well with reduce intents.
  Currently we give up early during normalize if the loop has reduce intents

- Currently only BlockDist and DefaultRectangular are supported.

  I don't want to support DefaultRectangular when this hits master, because
  `localAccess` calling `dsiAccess` feels a bit wrong to me. However, I kept it
  supported to get better test coverage while developing.

  Hashed and Stencil also has localAccess but I need to check further whether it
  makes sense for them to support this optimization. We should also see if
  localAccess and this optimization can be supported with other limitations,
  too.

- Accesses to ArrayViews are not touched.

- Loop index variable is not tracked closely: if you do a `const x = i` and use
  `x` you'll thwart the optimization.

- Similarly, if the access is happening inside a function called within the
  loop, we don't go check inside the function.

- Similarly, when we are analyzing within functions, we tend to fall back to
  dynamic checks too easily. I attempted some tracking with actuals and formals,
  but it seemed like it would grow too fast, so don't want to do that in the
  inital PR.

  This may also entail stamping out slightly different versions of functions, so
  there may not be too much value in this. An example snippet:

```chapel
var D = ... some supported domain ...
var A : [D] int;

proc foo(a, d) {
  forall i in d {
     ... a[i] ...
  }
}

foo(A, D); // will be based on dynamic checks
```

## Test status
- [x] standard
- [x] gasnet

### CODE REVIEW

**Comment by e-kayrakli** [comment]
#### Compiler performance

Did only very anecdotal tests at the moment. Negligible impact on the
compilation of LULESH on XC. (Less than 1sec increase of a compilation of about
    90seconds)

I want to do more structured tests here.

#### Application performance

Based on the code in https://github.com/chapel-lang/chapel/issues/14480, I get
the following numbers on a slightly different system:

```
> ./stream-opt -nl4
  zip arr: 0.62
  access: 0.63
  localAccess: 0.62

> ./stream-noopt -nl4
  zip arr: 0.63
  access: 0.89
  localAccess: 0.62
```

**Comment by bradcray** [comment]
> I can't remember whether @bradcray's concern in the initial design was fully about all the rewrites I was doing or whether it was also somewhat about having 3 loops post-normalize.

It was both.  But if param folding will reduce it to just one or two loops (i.e., is `allStaticChecksHaveFailed` a param expression?) them I'm less concerned about having three loops than I am if all three make it out to codegen.

Is the crux of the challenge that:
* we duplicate the loop early enough that we don't know the type of what we're looping over
* we modify both bodies such that it's hard to revert them back to the original loop
* the three-version loop preserves a loop that is similar enough to the original that if it's not a candidate for the optimization we fold back to what we have on master today?

If so, and the top conditional is a param that will return us to what we have today, I'm open to that.

**Comment by e-kayrakli** [comment]
Yes that check is a param check and your summary is right. 

If it helps further, we'll leave normalize with 3 loops, but post-resolve we'll have at most 2 loops. And if we have 2 loops, they are guaranteed to be different (we must have some static check that is passing, and we must have added a dynamic loop because there were some dynamic candidates)

**Comment by bradcray** [comment]
That seems like a reasonable approach to me then.

**Comment by mppf** [comment]
I was mainly asking if you were making copies of *all* forall loops and I was worried about having such copies at code-generation time.

**Comment by e-kayrakli** [comment]
@mppf -- Right. The answer is no, but the above forall loop is one example where the current design doesn't do a good job and lets a duplicate forall all the way down to codegen.

**Comment by e-kayrakli** [comment]
@benharsh Just in case you intend to review this, for now hold off on that. I am making the changes discussed above. I think I am mostly done, but I could think of one more case where we can end up with duplicate loops and we can probably avoid easily. I hope to have that soon.

**Comment by e-kayrakli** [comment]
Summary of last changes:

- We have three loops coming out of `normalize`
- Static overrides of dynamic checks are done by the compiler, instead of module code having awkward logic
- The dynamic check also has a static component to it, which is the OR-reduced static checks of dynamic candidates.

PR message is updated to reflect these changes. I am stopping editing this for now, and I think it is ready for a code review.

**Comment by e-kayrakli** [comment]
I have two quick design questions before I hit "merge"

- What do we want the flags to look like? Currently they show as below under
"Optimization Flags":
```
      --[no-]auto-local-access        Enable [disable] using local access
                                      automatically
      --[no-]auto-local-access-dynamic
                                      Enable [disable] using local access
                                      automatically (dynamic only)
      --auto-local-access-log         Enable compiler logs for auto local
                                      access optimization
```


- Do we want default rectangular to support this optimization? Default
  rectangular has a `localAccess` that just calls `dsiAccess`. I enabled this
  support to increase testing coverage while developing. Arguably, down the
  road having this analysis also cover and do "something special" for default
  rectangular makes sense. Does it make to enable this right now?

  I currently have a
```chapel
config param defaultRectangularSupportsAutoLocalAccess = true;
```

**Comment by ronawho** [comment]
Might want to make `--auto-local-access-log` a developer only flag. Similar flags (`--report-optimized-forall-unordered-ops`, `--report-optimized-on`) are devel only. Might make sense to change it to `--report-auto-local-access` for symmetry too.

I'm torn for whether it should be on/off for DR. I like the increased testing, but if we're cloning loops, it's seems like we're going to increase DR compilation time.

**Comment by bradcray** [comment]
> if we're cloning loops, it's seems like we're going to increase DR compilation time.

I similarly worry about the compile-time impact without execution-time benefit and would suggest we have it disabled by default.  I'd be more inclined to have a test configuration that provides this sanity check for developers, similar to `--verify` or `--valgrind` rather than subjecting everyone to it.

I'm fine with the `--help` text.  I went to read the man page which I was more interested in, but it looks like that hasn't been updated yet (which I'd expect to cause a test to fail)?

**Comment by e-kayrakli** [comment]
> Might want to make --auto-local-access-log a developer only flag. Similar flags (--report-optimized-forall-unordered-ops, --report-optimized-on) are devel only. Might make sense to change it to --report-auto-local-access for symmetry too.

Done.

> I similarly worry about the compile-time impact without execution-time benefit and would suggest we have it disabled by default. I'd be more inclined to have a test configuration that provides this sanity check for developers, similar to --verify or --valgrind rather than subjecting everyone to it.

Kept the `config param` but disabled it. We can add a flag to a test job as a follow up.

> I'm fine with the --help text. I went to read the man page which I was more interested in, but it looks like that hasn't been updated yet (which I'd expect to cause a test to fail)?

Right. I wanted to check the flags one more time before I fixed those tests. See https://github.com/chapel-lang/chapel/pull/15713/files#diff-0f83a8bc700b9fab0f4de6fc87c7aa91

**Comment by e-kayrakli** [comment]
@ronawho had mentioned that [`test/npb/ft/npadmana/ft_transposed.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/npb/ft/npadmana/ft_transposed.chpl) used `localAccess` calls that can be removed. I tested the performance and the PR keeps the performance same even when `localAccess`es are removed:

test

The diff in test:
```diff
diff --git a/test/npb/ft/npadmana/ft_transposed.chpl b/test/npb/ft/npadmana/ft_transposed.chpl
index 2a38440452..fb569e7956 100644
--- a/test/npb/ft/npadmana/ft_transposed.chpl
+++ b/test/npb/ft/npadmana/ft_transposed.chpl
@@ -83,9 +83,9 @@ writef("MFLOPS : %10.4dr\n",mflops);

 proc evolve() {
   forall ijk in DomT {
-    const elt = V.localAccess[ijk]*Twiddle.localAccess[ijk];
-    V.localAccess[ijk] = elt;
-    Wt.localAccess[ijk] = elt;
+    const elt = V[ijk]*Twiddle[ijk];
+    V[ijk] = elt;
+    Wt[ijk] = elt;
   }
   doFFT_Transposed(FFTtype.DFT, Wt, W, FFTW_BACKWARD); // This is unnormalized

@@ -126,7 +126,7 @@ proc initialize_twiddle() {
       const x1 = if idx >= N/2 then idx-N else idx;
       e += x1**2;
     }
-    Twiddle.localAccess[xyz] = exp(-fac*e);
+    Twiddle[xyz] = exp(-fac*e);
   }
 }
```

**Comment by bradcray** [comment]
Nice!!

**Comment by bradcray** [comment]
Grepping the test directory for benchmarks of interest, I wonder what other ones could be rewritten more simply.  ISx?  bale?  CoMD?  Lulesh-dense?  Probably not stencil-opt or mg due to their stencil patterns...?

**Comment by bradcray** [comment]
(converting such performance tests over, if possible, would also serve as an additional "lock" of this optimization as we were discussing above).

**Comment by e-kayrakli** [comment]
Right, I wanted to take a look at other benchmarks, too. But didn't have the chance so far.

**Comment by e-kayrakli** [comment]
I have tested stream whose kernel implemented as:

```chapel
forall i in ProblemSpace do
  A[i] = B[i] + alpha * C[i];
```

with `--auto-local-access` (on by default, representing this PR) and `-no-auto-local-access` (representing 1.22).

bandwidth
efficiency
improvement

**Pull request merged**
