### PR TITLE
Remove idxType from Bytes

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR drops `no doc`ed `type idxType` from the Bytes module.

It has no clear purpose and currently seeps into user's namespace.

Test
- [x] standard linux64
- [x] gasnet

### CODE REVIEW

**Comment by e-kayrakli** [comment]
This change required some fixes in standard modules where `idxType`
was used by mistake:

- Random had some mistakes from 1fa237de7cb243579d4fb0c30a5effff46d047c7
- Sort had some intentional changes from 4525c058187ce599eb1c032c01a15fc4e245d6bb


@bradcray https://github.com/chapel-lang/chapel/commit/4525c058187ce599eb1c032c01a15fc4e245d6bb#diff-672fabe87f1607d6e4235a667e514d05b501d5332065274e70fd13c682f9ff75R2681 is where `idxType` is used by mistake in Sort. This change comes from https://github.com/chapel-lang/chapel/pull/16803. The correct index-type-conscious expression is `0:A.targetLocales.idxType..`. Based on the motivation from the PR, and because we control the idxType of `targetLocDom`, I want to avoid that mess. The PR currently changes that to `0..`. Are you OK with that? All the places where `tid` used as an index has `int`-based domains.

**Comment by bradcray** [comment]
> All the places where tid used as an index has int-based domains.

I think you're right that if `tid` is used to index into int-idxType arrays, the current casting is overkill.

> and because we control the idxType of targetLocDom

Is this the targetLocDom from a Block or Cyclic distributed array?  If so, can't a user do:

```chapel
var targetLocales: [1..2*numLocales by 2] = Locales;
var D = {1..n} dmapped Block(1..n, targetLocales);
```

and get a targetLocDom that isn't 0-based?  (that said, if I'm right, this code has other problems like zipping a 1D range with a potentially multidimensional target locales array/domain?  So hopefully I'm wrong...).

**Comment by e-kayrakli** [comment]
> and get a targetLocDom that isn't 0-based?

Probably. But first, we are talking about the type of the index and not where it is based.

That being said, having it 0-based may be less general as you suggest. However, the arrays indexed by this value have `0..#numLocales` as their indices. So, there may be some problems lurking here (I don't know this code, nor it is very easy to understand quickly). But arguably those are unrelated to this PR.

**Comment by bradcray** [comment]
> > because we control the idxType of targetLocDom
> But first, we are talking about the type of the index and not where it is based.

You're right, so trying again: Couldn't I write:

```chapel
var targetLocales: [1:uint(16)..2*numLocales by 2:uint(16)] locale = Locales;
var D = {1..n} dmapped Block(1..n, targetLocales);
```

?

That said, I think you're saying that the type of `targetLocDom` doesn't really matter, only the `0..#numLocales` arrays that Sort is declaring and indexing into?  (in which case I agree)

**Comment by e-kayrakli** [comment]
> That said, I think you're saying that the type of targetLocDom doesn't really matter, only the 0..#numLocales arrays that Sort is declaring and indexing into? (in which case I agree)

Yes, that's right.

>  You're right, so trying again: Couldn't I write:
>
>```chapel
>var targetLocales: [1:uint(16)..2*numLocales by 2:uint(16)] locale = Locales;
>var D = {1..n} dmapped Block(1..n, targetLocales);
>```

I wanted to try this out nonethess. But we reshape and create `targetLocDom` in a way that it is always 0-based and `int(64)`-indexed. Which... is maybe OK? After all, we don't require the `targetLocales` to match the domain's rank, implying that we aren't just taking the array that the user gives as our basis of implementation, but more like a collection of locales that we should use from. Not sure how much I believe that, though.

**Comment by bradcray** [comment]
Ah, OK, if we're shaping then ignore all I've said about targetLocaleDom—works for me, thanks for checking!

**Pull request merged**
