### PR TITLE
Updating benchmarking site URL

### PR DESCRIPTION
**Pull request by Ldelaney**
Changed the benchmarking site URL from the old shootout URL to the benchmarks game URL in the comment headers of various files written for the benchmarking game. 

The chapel files for the k-nucleotide, Mandelbrot, and reverse complement problems do not appear to have any comment header at all, so they have not been updated.

### CODE REVIEW

**Comment by bradcray** [comment]
Hi Laura --

Unless it's a problem on my end, it looks to me like you missed a few files which I found via 'git grep shootout' in $CHPL_HOME (+ filtering of false positives in Makefiles, READMEs, etc. that referred to the directory names):

* test/parallel/taskCompare/lydia/*.chpl
* test/release/examples/benchmarks/shootout/pidigits.chpl

Also, as a git usage style issue, in future PRs, it would probably be preferable to lump a bunch of logically related changes like this together by using 'git add' for each of the files individually (or using wildcards to simplify specifying them) followed by a single 'git commit' to commit them all at one time with a single message.  For a PR made up of several logical changes, this can (sometimes) result in a more logical review than commits of a file at a time (or multiple commits of each file).  That said, some people obsess much more about using a minimal number of logical commits and others of us use commits more as a way to checkpoint progress as we develop something bigger, so there's no need to obsess about this overmuch...

(In this case it was a wash because the change was so simple and uniform across files, and I don't think it's worth redoing... Unless you want to avoid setting your "commits per day" bar to such a high point that it'll be tough to beat in the future... :)  ).

**Comment by psahabu** [comment]
Just as a side note, it is possible to squash all the commits of a pull request into a single logical commit on the master branch, which might be especially helpful in this case.

Let me know if that interests you (either Laura or Brad) when this PR is ready and I can show you how to do it.

**Comment by Ldelaney** [comment]
I updated the other files, and I'd like to learn how to squash the commits into a single logical commit.

**Comment by lydia-duncan** [comment]
You'll want to make sure that this squashing doesn't affect Brad's system of finding all the major commits at the end of a release cycle (for instance, if it turns them all into one commit instead of generating a merge commit, will that turn up in Brad's search?)

**Comment by bradcray** [comment]
* It looks like I didn't catch all of the cases above for some reason (or again, am making some sort of personal mistake).  I'm still seeing shootout in some versions in test/studies/shootout/nbody/sidelnik/*.chpl.  (You may also want to do your own 'git grep' to double-check my double-check and make sure I'm not missing anything else).

* I don't know enough about Preston's method of squashing commits to know whether or not it would affect my CHANGES roll-up, but I suspect it wouldn't -- my technique is to look at merges to master (essentially the PR merges) rather than individual commits.

* Laura, I'm noticing belatedly that it appears that you made these changes on your master branch rather than creating a branch (on your fork) and then setting up the PR from there.  I'm not enough of a Git expert to be able to say very well why this isn't recommended, but my view is that you typically want your master to stay in synch with the repository's master for the purposes of having a "clean" branch to work from, and to put all your work on distinct branches that you can switch between as needed (multitasking!).  Assuming you're convinced, I'll send you some notes about how to set up some hooks that will help prevent accidental commits to master (which is something I accidentally did all the time, even with the best of intentions, before installing the hooks).

**Comment by psahabu** [comment]
@lydia-duncan: What Brad said. If anything it would simplify the CHANGES roll-up because the master branch history won't contain any "work-in-progress" commits.

@Ldelaney:
When you hit "Merge pull request" after this PR is approved, the "Confirm merge" button will have a little triangle next to it. Hit that and select the "Squash and merge" option before confirming.

Also, when you merge, you'll have to fill out a commit message. Use the title of the PR and the body of your first message in this thread as a starting point, then add in the necessary edits of course.

**Comment by e-kayrakli** [comment]
Also, I tend to squash tiny little local commits before pushing the whole branch. Interactive rebase does the job nicely. Here are some references for whatever its worth:

Rebase: https://help.github.com/articles/about-git-rebase/
Revision selection: https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection

Keep in mind that it rewrites history, though.

**Comment by lydia-duncan** [comment]
The description of that feature looked like it would either make a merge commit for the branch or create an entirely new commit on master, but I may have misread.  I'd still verify that a merge message was generated after, though.

**Comment by psahabu** [comment]
Here's what I found: https://github.com/blog/2141-squash-your-commits

So it's not a merge commit, it's a single squashed commit. Personally I prefer squashing, since it keeps the master branch tidy while permitting individual branch commits to be as trivial as they like.

**Comment by bradcray** [comment]
FWIW, I don't have any problem with WIP commits showing up on master even if they reveal that you're a conservative developer who commits every time you've taken a step forward that doesn't seem to break things (which is how I tend to work, largely due to only finding scraps of cycles here and there, so wanting to checkpoint often).  Personally, I don't feel any need to keep master "clean" in terms of minimizing commits -- I'm more interested in minimizing PRs and merges.  I know others try to keep things tidier, though (and don't fault them their fussiness).  I guess my main message here is, don't feel unduly self-conscious about it and don't need the feel to clean up unduly.  The original commits and commit messages can often by useful archeologically, in my experience and it'd be a shame to throw information away unduly.

@psahabu : Are you aware of any PRs that you've merged (to Chapel master, ideally) that use the triangle button?  I'm curious whether I'll see them in the git log alias that I use to roll up commits when doing biweekly status or biannual release reporting.  If they don't show up, I'd prefer we either stop using it, or that someone find me a new similarly useful alias.

**Comment by bradcray** [comment]
This looks fine to me if you want to merge.  If you want to take one step further, you could update the 11 instances of "The Great Computer Language Shootout" to "The Computer Language Benchmarks Game" (or not -- I suspect that those versions are unlikely to become submission candidates and would be caught at that point if they were...)

**Comment by psahabu** [comment]
@bradcray:
I haven't committed anything with the squashing option because it seemed that the team preferred branch merging (which is totally fine, I'm good either way). If your alias is targeted at branch merges, then it's possible that squashed commits wouldn't be captured in the roll up, but I'm not sure. If we wanted to experiment, maybe we could use this PR?

Here's an example of a squashed commit [tracking the archaeological history](https://github.com/loomio/loomio/commit/a908a1380353ee855252ed30ff2863e009c3dad1) with links to the original commits. This allows each commit on master to reflect a single PR, which may or may not be valuable.

**Comment by Ldelaney** [comment]
Am I good to merge this now?

**Comment by bradcray** [comment]
Yep!

**Pull request merged**
