### PR TITLE
Highlight the deadlock that can occur between qthreads and MPI

### PR DESCRIPTION
**Pull request by npadmana**
Motivated by an email exchange with @bradcray, here is a simple standalone case that exposes the deadlock when running MPI and Qthreads. 

Note that this occurs even if Chapel is running single locale, but with the qthreads tasking layer. 

The README file lists the different cases I've considered...

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Hi Nikhil,

It might be best to split this test up into:

1. a general MPI module test in `test/modules/packages/MPI`: 
    *  `ring.chpl`
    * `ring.good`
    * `ring.suppressif`  - contents: `CHPL_TASKS==qthreads`
2. a future documenting the qthreads+MPI deadlock in `test/modules/packages/MPI`:
    * `qthreads-deadlock.chpl`  - same contents as `ring.chpl`
    * `qthreads-deadlock.future` - contains information in your README
    * `qthreads-deadlock.good` - same contents of `ring.good` 
    * `qthreads-deadlock.suppressif` - contents `CHPL_TASKS!=qthreads` 

I think you're pretty familiar with Chapel's test system, but [TestSystem.rst](https://github.com/chapel-lang/chapel/blob/master/doc/developer/bestPractices/TestSystem.rst) is a good reference in case you have questions about test file formats.

**Comment by ben-albrecht** [comment]
with the changes above you can also remove the `NOTEST`

**Comment by npadmana** [comment]
Hi Ben, 

I'm happy to do this -- but I don't think we actually have ever made sure that the MPI module works with the test system. I think, before we do this, we should do a simpler case, making sure we get the configurations that work, and the ones that don't.

In particular, I've been using the mpi-gnu for CHPL_TARGET_COMPILER (on non-Cray systems), which also requires CHPL_TARGET_ARCH=none (to avoid large numbers of warnings being spewed out at me). We also can run this two separate ways --
  a. single-locale Chapel + MPI --- which will require mpirun to start things up
  b. multi-locale Chapel + MPI --- I think the safest here is over gasnet-mpi, although it would be great to also add tests for gasnet + aries etc. 

I'm not quite sure the best way to do these (as well as how to run the multi-locale tests). But my suggestion is that we start with a simpler test and get that working, and then we can go from there... 

What do you think?

**Comment by bradcray** [comment]
Last I heard, I think @mppf owned the "get MPI testing" item, but he's been busy with some much higher priority items, so I'm guessing hasn't had a chance to work on it (and would probably be delighted if someone stole it from him).

**Comment by ben-albrecht** [comment]
This PR is currently blocked #4214, and some other testing PRs that will follow it. Marking as WIP until unblocked.

**Comment by ben-albrecht** [comment]
Closing this until we get #4214 merged.

**Pull request closed without merging**
