### PR TITLE
Add test capturing iterator record in array literal for 16621

### PR DESCRIPTION
**Pull request by cassella**
Adds test for #16621.

### CODE REVIEW

**Comment by cassella** [comment]
@e-kayrakli Here's the PR with a test for #16621 .

**Comment by cassella** [comment]
I expect this test will need an adjustment for/to #21337, depending on which goes in first.

**Comment by cassella** [comment]
@e-kayrakli I updated the test to add the trailing comma single-element array literals now require.

**Comment by e-kayrakli** [comment]
Thanks a lot @cassella!

**Pull request merged**
