### PR TITLE
Apply private to the helper module and a couple of functions in Buffers

### PR DESCRIPTION
**Pull request by lydia-duncan**
Due to a lack of non-transitive uses, the helper module's symbols will still
bleed into the namespace of any program that uses the Buffer module.  However,
this is a good first step.

### CODE REVIEW

**Comment by mppf** [comment]
I agree this is a good start. I wonder if it would be better to move the contents of the BufferInternals module into Buffers and mark them all private. The BufferInternals business was really just an attempt at keeping the C functions out of the namespace for users of Buffers.

**Comment by lydia-duncan** [comment]
I was wondering about that as well.  Other modules have gotten around this by not "using" the private module and instead using explicit naming to access the symbols within the private module.  Either strategy involves touching a lot of code, so it might be reasonable to just leave this until we have the ability to specify private uses.

**Comment by mppf** [comment]
I think removing the Internals module wouldn't change the rest of the code though - just how the extern procs are declared.

**Comment by lydia-duncan** [comment]
True, true.  We'd still need a way to keep the extern types out of the way, but they can just be "no doc"ed for now.  Shall I do that as part of this change?

**Comment by mppf** [comment]
If you're up for it. Either way is OK with me.

**Comment by mppf** [comment]
Looks good, thanks!

**Pull request merged**
