### PR TITLE
Fix memory leaks in Crypto tests

### PR DESCRIPTION
**Pull request by daviditen**
The tests for the Crypto module create, but don't delete classes, so they
leak memory. Add delete statements so they don't leak.

### CODE REVIEW

**Comment by daviditen** [comment]
@saru95 Does this look ok to you?  You can run the tests before and after this PR with commands like:

```
cd test/modules/packages/Crypto/saru
chpl aes/aesTest1.chpl
aesTest1 --memLeaks
```

To see the leaks / see them fixed.

**Comment by daviditen** [comment]
I think we should think about switching all of these data types to be records instead of classes so they will manage their own memory, but this fixes the leaks in the near term.

**Comment by saru95** [comment]
Oh yeah. I totally overlooked this. Adding `delete` at the end of each test avoids this. However, do we expect the user to do that every time he/she uses the `Crypto` module?

**Comment by daviditen** [comment]
If the various types stay implemented as classes, then yes, the user needs to `delete` them or they will leak.

If we switch them to records with carefully defined copies and deinitializers they should be able to clean up after themselves without `delete`.

**Comment by saru95** [comment]
You could try merging this for now. Meanwhile, I'll try on working on a version using `record`.

**Comment by daviditen** [comment]
OK, thanks!

**Pull request merged**
