### PR TITLE
Add Futures Related to Qualified Access issues

### PR DESCRIPTION
**Pull request by bradcray**
While preparing a simple demo today, I ran into a pair of issues relating to qualified accesses.  This adds futures for them:

* initializing a variable with a qualified reference to a same-named function call in another module causes an error as though the function call was a reference to the local variable.
* a code containing both qualified paren-ful and paren-less calls to a function segfaults

### CODE REVIEW

**Comment by cassella** [comment]
Did you mean to add `qualInitsSameName.*` in two directories?

**Comment by bradcray** [comment]
Yes, one uses `import` and one uses `use` (the test directory for `use` tests is less obviously named because it predates having two keywords for referring to a module's contents).

**Comment by cassella** [comment]
Hah, oops, sorry.  I looked over the files three times and didn't spot the difference.

**Comment by bradcray** [comment]
np, you're right far more often than you're wrong.

**Pull request merged**
