### PR TITLE
Add findUnusedTestFiles script

### PR DESCRIPTION
**Pull request by cassella**
This script checks the test/ directory for the .good the .bad and
the .future files (and assorted other start_test control files) that
are stale.  Most of the files are stale if there's no .chpl file
that refers to them.  .bad files also require a .future.  .good files
are more coplicated.  See within.

### CODE REVIEW

**Comment by ronawho** [comment]
Could you add a comment describing the intent as well as usage instructions to the top of the file?

**Comment by ronawho** [comment]
Maybe ignore files that have symlinks to them (like test/performance/thomasvandoren/common.good) with something like: 

```sh
   # See if this file is symlinked to
   if  ls -lR "$d" | grep ^l | grep $(basename $g) > /dev/null 2>&1 ; then
     continue
   fi
```
?

**Comment by ronawho** [comment]
To get rid of the remaining false positives, maybe just ignore any .goods if there is a prediff/PREDIFF/sub_test that mentions .good files?

```sh
   pd=$(compgen -G $d/'*.prediff')
   pd1=$(compgen -G $d/'PREDIFF')
   st=$(compgen -G $d/'sub_test')
   if grep .good $pd $pd1 $st /dev/null > /dev/null 2>&1; then
      continue
   fi
```

**Comment by cassella** [comment]
Those seem like good ideas.  I'm not sure I'll get to them soon.

Evidently this could also check for .bad files with no .futures, as in #9706.

Could also check for dangling .prediff, .compopts, .execopts, etc. files.

**Comment by cassella** [comment]
I modified the symlink test to match only symlink targets.  Just grepping for `$(basename $g)` matches whenever `$g` itself is the symlink.

And now I think `test/studies/lulesh/release-valgrind/lulesh-sedov15oct.good` is a correct reporting of an unneeded symlink `.good` file.  (I'd never looked closely at that one before.)  Many of the files in the `release-valgrind` dir, including that one, are symlinks to `test/release/examples/benchmarks/lulesh`.  But that particular `.good` file is in only the `orig-dir/lulesh.execopts`, not the `release-valgrind/lulesh.execopts`.  So I think that symlinks should be removed.  (Not done here.)

**Comment by cassella** [comment]
The `PREDIFF` change silences both of the remaining files that I think are dead .good files, so I'll include them here:

```
test/release/examples/benchmarks/lulesh/lulesh-sedov15cube.good
test/studies/lulesh/release-valgrind/lulesh-sedov15oct.good
```

**Comment by cassella** [comment]
I also added checking for .bad files with no .future.

**Comment by ronawho** [comment]
I'm not sure I've followed all the recent changes, but here's the output I see from this on master:

```
test/classes/hannah/volatile_while_loop.compopts
test/classes/hannah/volatile_while_loop2.compopts
test/classes/hannah/volatile_while_loop3.compopts
test/classes/hannah/volatile_while_loop3a.compopts

test/library/packages/ZMQ/interop-py/pyzmq-venv.notest

test/parallel/forall/task-private-vars/leader-follower.execopts

test/studies/madness/aniruddha/madchap/mytests/par-compress/FTree.notest
test/studies/madness/aniruddha/madchap/mytests/par-reconstruct/FTree.notest
test/studies/madness/aniruddha/madchap/mytests/par-refine/FTree.notest

test/types/type_variables/jplevyak/where-2-error.prediff
```

classes/hannah/volatile*.compopts look dead, and should have been removed in https://github.com/chapel-lang/chapel/commit/f67341692b

library/packages/ZMQ/interop-py/pyzmq-venv is created as part of the PREDIFF, so maybe not dead?

parallel/forall/task-private-vars/leader-follower.execopts looks dead, and it was likely mistakenly added in https://github.com/chapel-lang/chapel/commit/cca56c909c

studies/madness/aniruddha/madchap/mytests/*/FTree.notest all look dead, and maybe mistakenly added in https://github.com/chapel-lang/chapel/commit/06e08a8d3b

types/type_variables/jplevyak/where-2-error.prediff looks dead, and should have been removed in https://github.com/chapel-lang/chapel/commit/cd23721b5c

So it looks like the only false positive is the `library/packages/ZMQ/interop-py/pyzmq-venv`  case?

**Comment by cassella** [comment]
That all makes sense.  (I've had the `pyzmq-venv ` directory present the whole time, so I never saw that one!)

The "restrict certain special-casing" commit 057e2b40 involved a lot of indentation changes; it's a lot clearer with an "ignore whitespace" diff.

**Comment by ronawho** [comment]
For the pyzmq-venv case I think we can just adjust that PREDIFF to create the .notest when it creates the virtualenv.

**Comment by ronawho** [comment]
What are the next steps here? Do you have any other changes you'd like to make?

The only things that come to mind for me are maybe renaming the script and updating the top-level info to more accurately reflect what all this script checks now

**Comment by cassella** [comment]
> For the pyzmq-venv case I think we can just adjust that PREDIFF to create the .notest when it creates the virtualenv.

Hah!   I like it!

(It even feels principled!)


> What are the next steps here?

I opened #10072 to address these issues (plus one more that's cropped up on master in the last few weeks.)

I'm not feeling creative enough right now to tackle naming or documentation, but those make sense to me.

**Comment by ronawho** [comment]
>> What are the next steps here?

> I opened #10072 to address these issues (plus one more that's cropped up on master in the last few weeks.)

Nice, thanks


> I'm not feeling creative enough right now to tackle naming or documentation, but those make sense to me.

`util/devel/test/findDeadTestFiles` or `util/devel/test/findUnusedTestFiles`?  (as a sibling to the existing `util/devel/test/findMultilocaleTests`)

**Comment by cassella** [comment]
I haven't done anything about the pyzmq-venv .notest.

**Comment by cassella** [comment]
`test/mason/*/.mason*` seems kind of inconsistent, but I don't have a comm=none build to test with.

**Comment by ronawho** [comment]
Whoops, sorry Paul I completely forget about this!

Coming back to it. I still owe chaning the pyzmq notest. For the mason one -- the .mason directory is actually created by mason itself and not part of the test infrastructure. I think it'd be good to just skip checking anything that starts with .mason 

There is also a new dead file (test/types/enum/lydia/declaredInClass-constructor.good) as of https://github.com/chapel-lang/chapel/commit/ed4a11b5e0. I'll remove that too and with the .mason change I think we'll be good to go

**Comment by cassella** [comment]
Sounds good.  All but the last of these commits are cleanups, now that I come back to the script after a few weeks.  I think they're all be simplest to review individually.

**Comment by ronawho** [comment]
> Coming back to it. I still owe chaning the pyzmq notest. For the mason one -- the .mason directory is actually created by mason itself and not part of the test infrastructure. I think it'd be good to just skip checking anything that starts with .mason

> There is also a new dead file (test/types/enum/lydia/declaredInClass-constructor.good) as of ed4a11b. I'll remove that too and with the .mason change I think we'll be good to go

Done in https://github.com/chapel-lang/chapel/pull/10407

**Comment by ronawho** [comment]
> .good files are more coplicated. See within.

A typo in a Paul comment, I never thought I'd see the day ;)

**Pull request merged**
