### PR TITLE
Hoist Standard Library documentation to top-level

### PR DESCRIPTION
**Pull request by ben-albrecht**
The first set of changes in a series of module & documentation improvements I am making in preparation for the 1.13 release.

Here, we hoist the 'Standard Modules' to a top-level page, as well as 'Standard Distributions and Layouts'.

[Here are some pictures](http://imgur.com/a/xbJFt)

### CODE REVIEW

**Comment by bradcray** [comment]
I think that this looks good, though I think that in general layouts should go before distributions (in the sidebar, title, and list of files themselves -- I don't care about the internal filename.  The rationale being that layouts are, by definition, simpler than distributions.  That said, I'd take this over the status quo even with them listed in the other order.

**Comment by ben-albrecht** [comment]
@bradcray  I'll swap the order and merge. Thanks for the review!

**Comment by bradcray** [comment]
A belated note as I spend more time surfing the online docs:  On the layouts and distributions page, it seems that, for now at least, it would look nicer to have a heading for "Standard Layouts" and "Standard Distributions" rather than a bulleted hyperlink.  Particularly since the page that each links to is not that useful or different from this top-level index.  If you agree, I can take this on, just noting it here since it is an evolution of this original PR.

**Comment by ben-albrecht** [comment]
I tried this initially, but this led to the side-bar merging the contents of both sections into one, as siblings. We need the separate pages (hyperlinked) in order to keep the categories separate on the side bar. I thought this approach looked nicer overall, but you can take a stab at improving upon this. Alternatively, we could add a short description to the `dist.rst` and `layout.rst` so that the page is not completely redundant with the `distlayout.rst` contents.

**Pull request merged**
