### PR TITLE
Update the parser to support C String literals

### PR DESCRIPTION
**Pull request by Kyle-B**
This PR contains some of the groundwork for larger changes to strings that have happened on string-as-rec.

The parser is now able to recognize c_string literals of the form `c"foobar"`. These do not have any functional difference from normal string literals at the moment. In the future these will be of type `c_string` while normal strings (`"foobar"`) will be of type `string`.

Throughout the compiler we have many calls to `new_StringSymbol`, most of them have been replaced with calls to `new_CStringSymbol`. Both of these functions are the same at the moment, but will be different once the string-as-record work comes in. The replacement was needed because we were assuming that new_StringSymbol ended up generating as a (C) string literal, which will not be true in the future.

Tests came back clean for the standard configuration.

### CODE REVIEW

**Comment by Kyle-B** [comment]
@mppf - I've backed away from the full set of changes, but this will make the parser match between sar and master at least.

**Comment by mppf** [comment]
Do the C string literals actually work on master after this change? If so, could you add a test? Are they the same as String literals within the compiler?

**Comment by Kyle-B** [comment]
With this patch, `c"foo" == "foo"`. Changing the types on the literals was turning out to be quite painful and creating more differences than similarities between string-as-rec and master.

**Comment by mppf** [comment]
Sounds good. I don't think there's any reason to actually change the types for now on master. This patch looks OK to me provided it tests. Are you still thinking about moving over the  new_StringSymbol -> new_CStringSymbol changes over in various places in the compiler, even if the two functions do exactly the same thing on master? I think that would help, in addition to making the parser match.

**Comment by Kyle-B** [comment]
I've changed all of the `new_StringSymbol` calls over to `new_CStringSymbol` and added a small test that uses `c"foo"`.

**Comment by mppf** [comment]
Looks good, thanks. Could you update the PR message before merging to explain that this patch is doing some surface changes to prepare the compiler for the new string implementation? And of course indicate what testing you have done? Also, would you be willing to merge this into string-as-rec (before or after this PR is merged - up to you). Thanks!

**Pull request merged**
