### PR TITLE
Stop localizing module-scope const tuples

### PR DESCRIPTION
**Pull request by bradcray**
This PR stops localizing const tuples declared at module scope,
b/c it can be crazy expensive in code size, and in execution time
in a tight loop, as well as seeming a bit pointless.  As an example
compare the generated output of

```chapel
const tup = ("hi", "there", "elliot");
const tup2 = ("hi", 42, 5.4);
proc foo(i: int) {
  writeln(tup(i));
}
foo(1);

proc bar(param i: int) {
  writeln(tup2(i));
}
bar(1);
```

with or without this PR.

Elliot and I both wonder whether this localization (which means
"local" in the sense of "local vs. global variables", not "local vs.
remote" ones) optimization has outlived its utility, though we did
also see regressions when applying it slightly more broadly, e.g.,
to arrays in the release version of revcomp.chpl.  And it seems
conceivable that removing it altogether may make the C compiler
have to be more conservative about C file-scope variables.  I
opened #19434 to capture this future work.

### CODE REVIEW

**Comment by ronawho** [comment]
I actually think we can remove this pass all-together. This wasn't added to avoid comm, but to reduce global loads on XMT.

From https://cug.org/5-publications/proceedings_attendee_lists/CUG11CD/pages/1-program/final_program/Monday/03C-Kopser-Paper.pdf: 

> Since all memory is globally accessible and the application has access to approximately one hundred hardware streams on each processor, it is relatively simple to construct an application that oversubscribes a particular location in memory. When this happens, the memory controller and network back up, resulting in performance degradation.

We already broadcast globals for comm purposes, so this really just makes function local copies of node local things, and I do not see a benefit to that on conventional CPUs.

**Comment by bradcray** [comment]
> We already broadcast globals for comm purposes, so this really just makes function local copies of node local things

I don't think `localize` here is intended in the sense of local vs. remote but rather as global (C-level) variable vs. local variable, where the thought was that if our compiler were to make something into a local variable, it gives the back-end compiler more information about the fact that another task / routine won't be simultaneously modifying the global.  That said, you may still be right that it isn't necessary or worthwhile, but I was nervous about taking that large of a step here without more time to experiment with it, given how long it's been in this current state.

**Comment by ronawho** [comment]
Right, I agree this pass wasn't intended to reduce comm, but I'm pretty confident it was added as an XMT optimization. I think you're right that it _may_ help the backend see that things aren't modified, but I would be surprised if that helps much on a conventional CPU with a cache since a read-only const should stay in cache so shouldn't add much overhead even if it's used in a tight loop. Hmm, although if you have something like `var a = local_const * global_const`, making that global_const local could help the backend LICM something it could now prove is invariant.

That all seems somewhat unlikely to me, so I'd still be curious to see the impact of removing this, but to be clear I'm not arguing for removing for the release. Left  to my own devices, I may sit on this PR and look at removing the pass after the release though.

Was there a case that motivated this, or did you just happen to look at the code with some of the recent refactorings?

**Comment by bradcray** [comment]
> Was there a case that motivated this, or did you just happen to look at the code with some of the recent refactorings?

Nothing about this is tied to the release, but if this change gave us a win in performance, I think it's a modest enough change that I'd put it into the release.  If we don't, then I agree with your suggestion.

The motivating case was my renewed attempt at https://github.com/chapel-lang/chapel/pull/18708 yesterday, which I'm using the release as a motivator to look at again (though I doubt I'll land it in time, or that even if I do, it'll be a modest enough change that we'd want to take it... still, good to get back to it).  In order to get past the long enum->int and enum->string conversion overheads of my previous version, I created a module-scope `const` tuple of string and int values for each enum to support (a) indexing into the tuple to get the value in O(1) time, (b) automatic localization across locales (so that doing a conversion on locale > 0 wouldn't communicate back to locale 0.  After getting it working, I was surprised by how bad the performance remained because—in my mind—I'd made it uber-simple.  It turned out that my conversion routines that did the tuple access were basically copying the entire tuple into the routine before doing the lookup (?!?).  I was astonished, and had completely forgotten about this optimization/transformation pass's existence until I started looking into where the copies were coming from.

Happily, eliminating those copies gets us nearly back to the current conversion cost (it's slightly more expensive than `main` because there's an indirection that didn't exist before.  But I think it has so many benefits (and enum->int conversions aren't the most important thing) that I think it's the right direction.

Anyway, that caused me to fork this change off into its own to see if it was biting us in other places.  Probably not, but...

**Comment by bradcray** [comment]
[Also, terrifyingly to me, this branch is getting segfaults in our LICM pass for reasons I can't yet describe... :E ]

**Comment by ronawho** [comment]
Huh.. that's surprising. Could easily be a bug in LICM itself, but there are also some other passes that are tacked onto LICM (at least `optimizeForallUnorderedOps()`, maybe one or two others.) If it's failing for auto-agg tests, make sure that you have https://github.com/chapel-lang/chapel/pull/19423 pulled in since without that you'll see segfaults for some auto-agg tests in `cleanupRemainingAggCondStmts` called through licm.

**Comment by bradcray** [comment]
OK, thanks.  I don't have everything with the enums working just right / as it used to before yet, so I'm hoping once I resolve those, the LICM segfaults will go away.  But I don't know how likely that is...

**Pull request closed without merging**
