### PR TITLE
Move Errors from internal module to standard

### PR DESCRIPTION
**Pull request by mppf**
Follow-up to PR #18028.

This PR moves modules/internal/Errors.chpl to 
modules/standard/Errors.chpl and makes a small compiler adjustment to
handle that.

Reviewed by @daviditen - thanks!

- [x] full local testing

### CODE REVIEW

**Review by daviditen — APPROVED** [review]

**Comment by bradcray** [comment]
@mppf: Looking through documents in preparation for the release, I'm wondering if there's any compelling reason for the `Errors` module to still be referred to as "Error Handling" rather than `Errors` on the standard modules page:  https://chapel-lang.org/docs/main/modules/standard.html  I think the reason prior to this PR was to hide the internal module name, which a user couldn't refer to.  But that rationale doesn't seem to hold any longer?

**Comment by mppf** [comment]
Yes, I think we should probably call it `Errors` now since you can say `Errors.halt()` etc (although you don't normally need to).

**Comment by bradcray** [comment]
Would you mind taking care of that as a follow-up to this PR?

**Comment by mppf** [comment]
Done in #18446

**Comment by bradcray** [comment]
Thanks!

**Pull request merged**
