### PR TITLE
Fix typos in CHANGES.md

### PR DESCRIPTION
**Pull request by cassella**
Fix typos in CHANGES.md

### CODE REVIEW

**Comment by cassella** [comment]
Without the ``-``, the link goes to the top of executing.html, instead of to the configuration file section.

**Comment by lydia-duncan** [comment]
@bradcray, @awallace-cray - do we want to cherry-pick this into the release branch?  Seems like a no-brainer to me, but figured I should check

**Comment by bradcray** [comment]
I think it's Tony's call.  It's too bad the errors are there, but if things are pretty far along, I don't know that I'd re-spin modules builds over this.  (That said, we could still push the changes to the branch for future reference / use).

**Comment by awallace-cray** [comment]
I do not wish to build new Cray modules for it. I don't mind a new release tarball as much, if we thought it would make a difference. We should definitely cherry-pick it over to the branch- that's easy, and would fix the online docs.

**Comment by lydia-duncan** [comment]
Okay, I'll merge it

**Comment by bradcray** [comment]
Sorry about the typos, BTW... :(

**Comment by cassella** [comment]
I need something to keep me off the streets at night.

**Pull request merged**
