### PR TITLE
Update use of macros for atomic uintptr_t functions

### PR DESCRIPTION
**Pull request by ronawho**
For some reason that baffles me using the DECLARE_ATOMICS marco for uintptr_t
causes build issues on netbsd, but calling the 3 macros that it does works
fine.

This seems like an ok, though unfortunate workaround. So far as I can tell we
don't actually use any of the atomic operations on uintptr_t either in the
modules or runtime so it might be easy enough to just remove the declaration of
it.

I wanted to wait and talk to Michael about that, but this seems like an ok fix
in the meantime.

### CODE REVIEW

**Comment by ronawho** [comment]
@gbtitus mind reviewing this? If you want more details on what the build issue is I can send them to you

**Comment by ronawho** [comment]
FYI, this is the first of ~5 patches to fix netbsd

**Comment by gbtitus** [comment]
This seems okay and can be committed.

The root of the problem is the fact the on netbsd <stdint.h> (indirectly
via <sys.stdint.h>) #defines uintptr_t as __uintptr_t.  (__uintptr_t is
in turn typedef'd as unsigned long, but that doesn't matter to us.)  The
C standard (6.3.10.1(1) for C99) says that the actual arguments in a
macro invocation are themselves macro-expanded before being substituted
into the replacement text, unless they are preceded by a # or ## token.
In our case, the "type" formal argument of DECLARE_ATOMICS_BASE has a ##
before it in the replacement text, so uintptr_t is not macro-expanded
and the concatenation produces the expected atomic_uintptr_t typedef
name.  But in the case of DECLARE_ATOMICS there is neither a # or ##
before "type" in the replacement text, so the uintptr_t actual becomes
__uintptr_t via macro expansion before DECLARE_ATOMICS_BASE is invoked,
and we get a syntax error on the resulting atomic___uintptr_t because
it's not a typedef type.

You might replace the "for some reason" comment with this explanation,
but the actual change itself seems like a perfectly good solution.

**Comment by ronawho** [comment]
Ah ok, that makes sense. That's for investigating! I was really curious, butI don't think I would have figure that out. 

I added your comment verbatim to the files.

**Pull request merged**
