### PR TITLE
Fix incorrect type in BigInteger

### PR DESCRIPTION
**Pull request by jabraham17**
Fixes an issue pointed out by @bradcray in https://github.com/chapel-lang/chapel/pull/21956#discussion_r1852908956, where a `uint` was mistakenly casted to a `c_long`, not a `c_ulong`.

[Reviewed by @bradcray]

### CODE REVIEW

**Comment by bradcray** [comment]
@jabraham17 : Thanks for the quick fix here!  Would you also add a test locking this in that calls `*=` using a RHS uint that is within (max(int), max(uint)?

**Comment by bradcray** [comment]
(I should mention that I took a quick scan for other cases within GMP that might have the similar issue due to copy-paste errors, but did not find any).

**Comment by jabraham17** [comment]
I also took a scan through GMP/BigInteger and this was the only issue I saw

**Comment by bradcray** [comment]
Looks great, thanks for the quick fix!

**Review by bradcray — APPROVED** [review]

**Pull request merged**
