### PR TITLE
HOST, not TARGET for printchplenv --launcher

### PR DESCRIPTION
**Pull request by ben-albrecht**
`printchplenv --launcher` was unintentionally changed to  printe `TARGET` values instead of `HOST` values. Surprisingly, this did not cause catastrophic failure. It did, however, modify the module build paths on Cray e.g. `PrgEnv-gnu` vs. `gnu`.

In making this change, the default output logic was changed to no longer depend on existing flags. Instead, the variables that are printed by default are specified by a `content` element of `'default'`. The help output was updated to reflect this, referring to the default variables as "user-facing variables".

Before this PR:

```
> printchplenv --simple --launcher --anonymize

CHPL_TARGET_PLATFORM=darwin
CHPL_TARGET_COMPILER=clang
CHPL_LOCALE_MODEL=flat
CHPL_COMM=none
CHPL_TASKS=qthreads
CHPL_LAUNCHER=none
CHPL_TIMERS=generic
CHPL_UNWIND=none
CHPL_MEM=jemalloc
CHPL_ATOMICS=intrinsics

> printchplenv --path --launcher

darwin/clang/loc-flat/comm-none/tasks-qthreads/launch-none/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics
```

After this PR:

```
> printchplenv --simple --launcher --anonymize

CHPL_HOST_PLATFORM=darwin   <--- replaced TARGET
CHPL_HOST_COMPILER=clang    <--- replaced TARGET
CHPL_LOCALE_MODEL=flat
CHPL_COMM=none
CHPL_TASKS=qthreads
CHPL_LAUNCHER=none
CHPL_TIMERS=generic
CHPL_UNWIND=none
CHPL_MEM=jemalloc
CHPL_ATOMICS=intrinsics

> printchplenv --path --launcher

darwin/clang/loc-flat/comm-none/tasks-qthreads/launch-none/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics
```

Default output remains unchanged.

## Testing

- [x] `linux64 paratest`
  - `[Summary: #Successes = 8075 | #Failures = 0 | #Futures = 0]`

### CODE REVIEW

**Comment by ben-albrecht** [comment]
`paratest` reminded me that this changes the default output to include `CHPL_HOST_COMPILER` and `CHPL_HOST_PLATFORM`. I suspect this is not what we want...

**Comment by gbtitus** [comment]
Having the host platform and compiler in the default output seems like a plus to me.  Are there disadvantages?  (other than one-shot "get over the hump" ones in testing)

**Comment by ronawho** [comment]
HOST platform and compiler were intentionally removed in 6e9016c4ba66eecc4405d09919e24d3332990096 (as part of https://github.com/chapel-lang/chapel/pull/3107)

I don't think we want to re-add them

**Comment by gbtitus** [comment]
Huh, for some reason it had never occurred to me that when we ask for `printchplenv --anonymize` output to help diagnose problems that we wouldn't get host platform and compiler without explicitly requesting it.  Of course I'm almost always dealing with runtime issues, where that's not a concern.

**Pull request merged**
