### PR TITLE
Rewrite ddata_allocate() to avoid inadvertent widening of init_elts()

### PR DESCRIPTION
**Pull request by bradcray**
This fixes a performance regression for array creation that crept in
when the array reallocation PR was merged.

Prior to this change, passing a ddata by `ref` to ddata_reallocate()
and then passing it along to init_elts() caused all calls to
init_elts() to use a wide rather than narrow ddata.  Worse, this even
affected programs that did not call ddata_reallocate() or even generate it
into their generated code, I believe because of dynamic dispatch resolution. 
This seems regrettable performance-wise, and was also subtle and hard to
track down.  It makes me wonder whether we should clone such functions
more aggressively to stop such cases from creeping in (and what other
performance wins that might lead to).

Here, I work around that issue by having ddata_reallocate() behave
more like realloc() in that it takes in the old ddata and returns
the new one.

While debugging this, I also noted that we had an extraneous on-clause
in dsiReallocate().  Extraneous because the only place it's called is within
ChapelDistribution.chpl, which already contains the necessary
on-clause.  For that reason, I converted the on-clause into an assert
to reduce overheads.

TODO:
- [x] verify that this fixes performance
- [x] verify that I haven't broken ugni realloc code paths
- [x] full correctness test

### CODE REVIEW

**Comment by bradcray** [comment]
@e-kayrakli: OK, I think this one should do it.
@gbtitus: If this fixes performance, could you help verify that I haven't broken ugni's realloc code path?
@benharsh: I consider you our main expert on wide vs. narrow issues.  Does my description of what I seemed to be seeing above sound accurate to your understanding of things?

**Comment by bradcray** [comment]
Thanks for the late "Friday night" check, Greg!

**Comment by e-kayrakli** [comment]
This branch brings the performance back. I have only tested on XC because that's where we have seen the biggest hit.

**Comment by bradcray** [comment]
OK, thanks.  I'll do a full test run on it now (I've already spot-checked the tests designed for reallocation, so suspect between those and Greg's check that it'll be clean, but...).

@e-kayrakli or @ronawho : Would one of you give this a code review (if Engin hasn't already).

**Comment by benharsh** [comment]
I think your description of the wide-pointer issue is accurate, and this seems like a reasonable fix in the absence of a smarter compiler.

**Pull request merged**
