### PR TITLE
Replace use of our Vec class with use of std::vector in codegen of ModuleSymbols

### PR DESCRIPTION
**Pull request by lydia-duncan**
Coverity was complaining about sending the Vec's n field to qsort because it
was possible the n field was a null pointer.  Since the Vec in question is a
local variable, I switched it to a std::vector and sent it to std::sort instead
of qsort (because the internet told me it that was a better sort to use
anyways).  Using vector's begin() and end() iterators also gets rid of the
complaint Coverity had, because the iterators won't dereference if there is
nothing in the vector.

### CODE REVIEW

**Comment by mppf** [comment]
Looks good to me, but I'm not very familiar with Vec...

**Comment by lydia-duncan** [comment]
Hopefully you soon won't have to be :)

**Comment by lydia-duncan** [comment]
Should I call this reviewed, then? Or shall I wait for someone else to grab it?

**Comment by mppf** [comment]
I think you could call it reviewed. If anybody else really wants to look at it, they can after you commit it...

**Pull request merged**
