### PR TITLE
Check only once for overflow, do it with a uint64 to work on 32-bit

### PR DESCRIPTION
**Pull request by mppf**
My last attempt at fixing MAYBE_STACK_ALLOC had problems on
some systems with a tautological comparison. Here I'm trying
to solve the same problem (count is 64-bit but size is 32-bit)
with a different strategy - using a uint64_t explicitly.

### CODE REVIEW

**Comment by mppf** [comment]
@bradcray could you check if this has the problem for you on the home mac?

**Comment by bradcray** [comment]
It's at home, but there's no need to hold off on merging for its sake.  I can try it tonight (and don't expect this to result in the same issue).

(Note: This is not a review of the pull request itself)

**Comment by mppf** [comment]
@noakesmichael, can you review this one? I hope that it addresses both the compiler warning Brad encountered and my original concern (to handle the case where count is a uint64_t but size_t is 32-bit).

**Comment by mppf** [comment]
@noakesmichael, I just verified that the new patch passes full local testing.

**Comment by mppf** [comment]
Replacing this with #1507

**Pull request closed without merging**
