### PR TITLE
Corrected a comment in doc/rst/conf.py

### PR DESCRIPTION
**Pull request by shubhamkmr04**
@bradcray  I edited this comment in doc/rst/conf.py according to my  last PR #17400

### CODE REVIEW

**Comment by bradcray** [comment]
OK, thanks @shubhamkmr04.  Have you had any luck coming up with an approach that would let us turn this off for the man pages only, but not the rest of the documentation?

**Comment by shubhamkmr04** [comment]
Yes @bradcray , actually I was learning about k-mer algorithms (about the project I am interested in, for GSoC) for the past few days but today I tried digging this issue but I got into some errors.
First, maybe I made some changes, the **make docs** started showing this error **sphinx build command is not available**
Screenshot from 2021-03-23 00-15-35

Screenshot from 2021-03-23 00-17-37
Second, I have this doubt, are these files in third-party/chpl-venv/install make during the documentation build? Like in this file, third-party/chpl-venv/install/chpldeps/sphinx/config.py , **smartquotes_excludes** excluding the "man" builder but changes in these files were not reflecting on man page.

**Comment by bradcray** [comment]
Hi @shubhamkmr04 — Good questions, and we're getting outside of my areas of expertise, unfortunately.  My impression is that none of the files in `chpl-venv/install` are files that we control or that are in our source repository, such that if we wanted to make changes to them, we'd need to do that from some other place.  But I'm guessing here.  Let me ping @ben-albrecht and @lydia-duncan on this to see whether any of them have anything to say about it.

Lydia and Ben: For context here, the question we're wrestling with is how to apply an option to some of our source files (specifically, the man page) and not others (the problem being that in fixing #17385, we inadvertently changed how everything else was rendered.

**Comment by lydia-duncan** [comment]
Yeah, chpl-venv/install and chpl-venvn/build are not places we tend to modify, so far as I remember.

The sphinx-build missing sounds like something we encountered when we shifted to using Python 3 by default.  @shubhamkmr04 - did you initially build with 1.23 in this checkout and then update to master or 1.24?

**Comment by shubhamkmr04** [comment]
@lydia-duncan , I was initially using 1.23 release but I am now using master branch (I deleted the 1.23 release around 10-15 days ago and cloned the master in my local) but this problem didn't arise just when I switched to master but this error is showing just yesterday.

**Comment by lydia-duncan** [comment]
Try `cd third-party/chpl-venv; make clobber` and then going back to $CHPL_HOME and making chpldoc again.  I think that's what enabled the new changes to be applied after the fix went onto master

**Comment by shubhamkmr04** [comment]
Okay it worked, thanks @lydia-duncan

**Pull request merged**
