### PR TITLE
Require `--memTrack` to enable memory hooks

### PR DESCRIPTION
**Pull request by ronawho**
Previously, runtime memory hooks (sanity checks and memory tracking)
were enabled if `CHPL_DEBUG` was set or if `CHPL_OPTIMIZE` wasn't set.
This led to pretty confusing behavior, because our third-party, runtime,
and generated code could all get different values of these settings,
which resulted in inconsistent tracking for the final executable.

Simplify things here to only enable memory hooks if memory tracking is
enabled regardless of optimization or debug levels. This should make the
behavior for an executable consistent across all components and should
speed up allocations coming from qthreads, which got tracked since we
don't set `CHPL_OPTIMIZE` when calling our memory layer from qthreads.

This code originated from 9c50debb80, where the flags were more about
memory debugging instead of just tracking so it made more sense to
enable extra checks if debug was enabled. It was then changed in
c1484c3974. I believe the behavior is more confusing than helpful now
and it's been a very long time since our memory hook checks caught any
correctness issues so I don't think there's value in enabling them just
because debug is on.

Resolves Cray/chapel-private#3388

### CODE REVIEW

**Review by mppf — APPROVED** [review]
I am not sure of the value of keeping `CHPL_MEMHOOKS_ACTIVE` at all. I would be inclined to replace all uses of it with `chpl_memTrack`. I think that will make the situation easier to understand in the future.

IIRC a long time ago I was expecting that we would want to be able to turn off memory tracking at compile time, but we have never had that and I don't think we need to add it now.

If you decide to keep `CHPL_MEMHOOKS_ACTIVE` for some reason, please update the comment above it to something like this:

```
// Generally, memory hooks are enabled according to `chpl_memTrack` (`--memTrack`).
// However, `-DCHPL_MEMHOOKS_ACTIVE=1` will enable them always.
```

**Comment by ronawho** [comment]
> IIRC a long time ago I was expecting that we would want to be able to turn off memory tracking at compile time, but we have never had that and I don't think we need to add it now.

I'm testing a branch that makes this change in the perf playground just to see if it's worth pursuing. On a shootout-like box I see binary tress (an almost all allocation benchmark) go from 8.3 to 8.1 seconds. 

> If you decide to keep CHPL_MEMHOOKS_ACTIVE for some reason, please update the comment above it to something like this:
>
> ```
> // Generally, memory hooks are enabled according to `chpl_memTrack` (`--memTrack`).
> // However, `-DCHPL_MEMHOOKS_ACTIVE=1` will enable them always.
> ```

I like keeping it to have the option of disabling any tracking in the future

**Comment by mppf** [comment]
> I like keeping it to have the option of disabling any tracking in the future

OK, in that event, let's update the comment like this:

```
// Generally, memory hooks are enabled according to `chpl_memTrack` (`--memTrack`).
// However, `-DCHPL_MEMHOOKS_ACTIVE=1` will enable them at compile-time,
// and `-DCHPL_MEMHOOKS_ACTIVE=0` will disable them at compile-time.
```

**Comment by ronawho** [comment]
> OK, in that event, let's update the comment like this:
>
> // Generally, memory hooks are enabled according to `chpl_memTrack` (`--memTrack`).
> // However, `-DCHPL_MEMHOOKS_ACTIVE=1` will enable them at compile-time,
> // and `-DCHPL_MEMHOOKS_ACTIVE=0` will disable them at compile-time.


Isn't that obvious from it being a macro? I'm not opposed and don't want to get hung up over a comment, but I don't see what that comment adds that isn't right in the code.

**Review by e-kayrakli — APPROVED** [review]

**Comment by mppf** [comment]
> Isn't that obvious from it being a macro? I'm not opposed and don't want to get hung up over a comment, but I don't see what that comment adds that isn't right in the code.

The information about it normally being connected to `--memTrack` is not in the code.

**Comment by ronawho** [comment]
Updated comment

**Pull request merged**
