### PR TITLE
Make select only evaluate its argument expression once

### PR DESCRIPTION
**Pull request by mppf**
This test includes a test showing the surprising behavior. It's passed test/statements/select and
the new test.

- [x] code review
- [x] full testing
- [x] update spec to clarify that the select argument is only evaluated once

### CODE REVIEW

**Comment by vasslitvinov** [comment]
Looks good to me. I agree that we do not intentionally want the old semantics.

**Comment by bradcray** [comment]
For extra credit, you should commit the test as a future first and then fix it the next day.  ;)

**Comment by mppf** [comment]
@vasslitvinov, would you have a look over the spec changes post-commit? Thanks.

**Comment by bradcray** [comment]
Something I wondered on the way home last night but haven't had a chance to determine through reading the code or experiment myself:  Would this change have the effect of inserting array temps if the select expression were an array?  (if so, I find myself torn between our "no array temps that the user didn't requiest" philosophy and wondering whether anyone could/would put an array there that's large enough that it would matter...).

**Comment by vasslitvinov** [comment]
If the select expression is an array, the temp should be a reference to it, not a copy.

**Pull request merged**
