### PR TITLE
Created Submodule of MT in FFTW module and deleted FFTW_MT module file

### PR DESCRIPTION
**Pull request by aditmehta9**
Created Submodule of MT in FFTW module and deleted FFTW_MT module file and renamed module to MT. Solved issue #11065 .

### CODE REVIEW

**Comment by aditmehta9** [comment]
@ben-albrecht @bradcray Do I need to make any changes?

**Comment by aditmehta9** [comment]
Thanks Sir, for your review

**Comment by aditmehta9** [comment]
> 
> 
> Hi @aditmehta9 - Thanks for your interest in contributing.
> 
> Unfortunately, there are some open design decisions to make on this task (see my comment in #11065), so we won't be able to move forward with this PR for a while.
> 
> Once we are able to continue with this PR, my first request would be to update the FFTW tests to account for the new changes and confirm that they still work.

Yes, Sir.

**Comment by ronawho** [comment]
Closing due to inactivity, feel free to reopen if you continue with this.

**Pull request closed without merging**
