### PR TITLE
Fixing the location of the chpl-venv directory used by default

### PR DESCRIPTION
**Pull request by bradcray**
...though I have to wonder... shouldn't it be based on the host
platform rather than the target one...?

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho do you want to review the update to the comment?  I'm also using this as an excuse to drag my feet until we take another round in the "should this be host or target" conversation....

**Comment by ronawho** [comment]
I would go head and commit this change, and let kyle update it whenever he gets around to using host instead of platform.

**Comment by bradcray** [comment]
@Kyle-B -- would you update this comment when you change TARGET to HOST for python venv stuff?  (probably you'd catch it in a grep, but just to be sure since I just modified the lines (and they're what tipped me off that it was the wrong value).

**Comment by Kyle-B** [comment]
Will do.

**Pull request merged**
