### PR TITLE
Add warning for initializing local dom from distributed one

### PR DESCRIPTION
**Pull request by mppf**
Fixes issue #5657.

* adds flags FLAG_DSI_DISTRIBUTED and FLAG_DSI_NOT_DISTRIBUTED and mark modules/dists and internal DSI implementations (like DefaultRectangular) with the appropriate one
* add code in checkResolved to find the problematic case and raise a warning on it

### CODE REVIEW

**Comment by mppf** [comment]
Closing until I complete more testing...

**Comment by bradcray** [comment]
I'm not wild about requiring a pragma to be placed on every distributed domain map to make this work.  It seems like we already have a way to distinguish between distributed- and non-distributed domain maps, though I need to think to remember what it is.

I'd also expect this warning to be able to be implemented strictly with module-level code (and prefer it if so) -- for example, a param check in the array-to-array assignment routine (or initialization routine if/when we have one?).

**Comment by mppf** [comment]
@bradcray - I agree it would be nicer if we could do it in domain assignment / array assignment routines. I'd need some help knowing how we know if a domain is distributed though. Or maybe we need to add `dsiIsLocalOrDistributed` or something that returns a param to the DSI interface...

**Comment by mppf** [comment]
Oh, and to be clear, distributed domain maps that don't have the pragma (in the approach in this PR) would still function - they just would not get this warning.

**Comment by mppf** [comment]
Maybe `isDefaultRectangular` can help here.

**Comment by bradcray** [comment]
That could be a good start today, though there may be other layouts over time (and if you count things like sparse, there already are).  I'd prefer to see this go in the direction of having domain maps support an 'isDistribution' vs. 'isLayout' style of query which seems like a useful property to know in general.

**Pull request closed without merging**
