### PR TITLE
Make genGraphs recursively chmod html/ directory

### PR DESCRIPTION
**Pull request by bradcray**
Every time I make graphs and try to browse them via a local web share,
I have to re-chmod the directory by hand.  This commit proposes doing
it automatically (directories become u+rwx, go+rx; files become u+rwx, go+r.
My Python is probably terrible, characteristically, and I'm open to feedback
on it.

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho : Want to review this since we were discussing it?

**Comment by ronawho** [comment]
What do your permissions look like before this patch? 

Mine are: 

    mbp-eronagha: mbp-eronagha (master) $ ls -la html/
    total 448
    drwxr-xr-x    9 eronagha  513     306 Feb 13 14:43 ./
    drwxr-xr-x    5 eronagha  513     170 Feb 13 14:43 ../
    drwxr-xr-x  139 eronagha  513    4726 Feb 13 14:43 CSVfiles/
    -rw-r--r--    1 eronagha  513       0 Feb 13 14:43 SUCCESS
    -rw-r--r--    1 eronagha  513  124855 Feb 13 14:43 dygraph-combined.js
    -rw-r--r--    1 eronagha  513   52973 Feb 13 14:43 graphdata.js
    -rw-r--r--    1 eronagha  513    2161 Feb 13 14:43 index.html
    -rw-r--r--    1 eronagha  513     919 Feb 13 14:43 perfgraph.css
    -rw-r--r--    1 eronagha  513   38515 Feb 13 14:43 perfgraph.js

If I scp -r'd this over to my public html I can view it just fine without chmodding anything (which surprised me a little, I didn't think I used to be able to do this.)

With your patch, the only difference is that they files have u+x as well, which I don't think should be needed.

**Comment by ronawho** [comment]
I wonder if the chap boxes and your box have different default permissions. and maybe when I create graphs on chap04 is when I need to do the chmodding..

Does this patch still work for you without setting u+x ?

**Comment by bradcray** [comment]
Default permissions are user-specific, not machine-specific.  My umask is 077 which I suspect is part of my problem (but I don't want to change that).  What's yours?

You're right that I shouldn't u+x the files, only the directories -- that was an oversight.  I was bummed that the chmod was so much clunkier from python then on the command-line (and so got it wrong).

Also, note that I don't rcp/scp this anywhere.  I just symbolically link from my public_html directory over to the directory in question.

**Comment by ronawho** [comment]
You can use the number values in python, but I would stick with this since octals are different between python 2 and 3

**Comment by ronawho** [comment]
That said, I can't for the life of me figure out exactly what permissions these chmods are setting. 

I think if you drop u+x for files, and add a comment with the human readable permissions above each chmod, this is good to go

**Comment by bradcray** [comment]
Made those changes.  Should we maybe get a second opinion from a Python/web guru like @thomasvandoren ?

**Comment by ronawho** [comment]
makes sense, I wouldn't trust either of our python skills :)

**Comment by thomasvandoren** [comment]
Looks good to me. One might argue that we should honor the umask setting at least for the root or perhaps make this an opt-in feature. I don't think we need to do that, though, unless someone asks for it.

**Comment by bradcray** [comment]
While I agree it's a big hammer, my argument was, essentially, that if the point of the files is to put them on the web (which for most of our use cases, it is), then we should put the permissions into a state that make them trivially usable on the web.

**Pull request merged**
