### PR TITLE
Chameneos initializer updates

### PR DESCRIPTION
**Pull request by bradcray**
While reviewing release-over-release performance numbers and looking at chameneos versions, I was reminded that now that initializers are much improved, we can write nicer initializers for our chameneos versions.  This PR:

* moves a phase 2 array assignment in Elliot's version's initializer into a phase 1 assignment and uses promotion of a constructor (a forall expression could be used instead if that felt like the right clarity / code size tradeoff)
* copies my "ideal" version to the "blc" version now that it's working to get timings on it (the previous blc version was virtually identical to the submitted version 2.  The main difference between this version and Elliot's is the use of a generic field rather than explicit domain/array fields.  Since my "ideal" version was never timed for performance, this will give us a first opportunity to do so
* creates a new (futurized) ideal version that results in an internal error in the compiler.  Interestingly, it uses concepts from Elliot's (the promoted constructor) and mine (the generic field) either of which works separately, but which blow up when used together.

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho: Will you review this?
@lydia-duncan: Will you check to see whether the new future in the -ideal version is known or whether I should file an issue against it?

**Comment by ronawho** [comment]
Looks good to me

**Comment by bradcray** [comment]
@ronawho: FYI, I updated to include the promotion using an anonymous range that I mentioned at the end of the day today.  I think it adds a lot of clarity to the promotion.

**Comment by lydia-duncan** [comment]
This is a new error.  Go ahead and file an issue, I might take a look at how difficult it would be to solve this (from what I can tell, the problem seems to be independent of the promotion and specific to a generic field getting initialized with `new`)

**Comment by lydia-duncan** [comment]
Further information - the problem is also present when the field has an initial value but no type (var y = new Rec();).  The error source is different (due to it following different but similar code paths), but the solution for both should be similar.  I believe this was an oversight from fixing the same error when the type of the field is explicitly declared

**Comment by lydia-duncan** [comment]
See #7336 for more cases that run into this error

**Comment by bradcray** [comment]
Hi Lydia -- I think you've got a better grasp on the error than I do.  Would you take care of filing the issue?  (unless you think the fix is imminent?)

**Comment by lydia-duncan** [comment]
Gladly!

**Pull request merged**
