### PR TITLE
Add env var overrides for recent memory settings

### PR DESCRIPTION
**Pull request by ronawho**
Add `CHPL_RT_INTERLEAVE_MEMORY` to control memory interleaving at
runtime and `CHPL_RT_MERGE_SPLIT_CHUNKS` to control whether jemalloc is
allowed to merge and split chunks. These are undocumented since they
aren't meant to be user-facing, they're just here in case we need to
experiment in the field.

### CODE REVIEW

**Comment by ronawho** [comment]
An initial version of this was reviewed by @gbtitus yesterday. @bradcray feel free to consider this an FYI if you don't have time to review since you were the one to suggest the runtime overrides.

**Comment by bradcray** [comment]
This looks good to me.  W.r.t. the merge/split capability:  Are there benefits to disabling the merge/split, or is this primarily for the purpose of supporting experimentation with what kinds of improvements we're seeing now that it's enabled?

**Comment by ronawho** [comment]
There's a performance benefit to disabling merge/split and interleaving (it gets us back to the old performance at the expense of fragmentation)

**Comment by bradcray** [comment]
Oh right, right.  I basically asked for this, didn't I?

**Comment by ronawho** [comment]
Yup

**Pull request merged**
