### PR TITLE
extern block primer

### PR DESCRIPTION
**Pull request by mppf**
Extern block bug fix and draft primer in test/extern 

This patch fixes a bug where char* mapped to c_string argument types, even
though c_string is const char*.  That meant it was not possible to use some
extern functions with the extern block support.

In addition, it adds a draft version of an extern block primer - but not into
the release directory. The primer has an issue - casting from c_ptr(c_char) to
c_string should be possible but isn't working when I add it to the modules. So,
these casts are at the end of the primer, which obviously is not ideal. I
believe Kyle has already made changes on string-as-rec that will solve this
issue, and so hopefully the primer can be moved to the release directory once
that work is merged.

Compiler change reviewed by @Kyle-B.
Passed full local testing (with a compiler built with LLVM).

### CODE REVIEW

**Comment by mppf** [comment]
Based on discussions with Brad, I think that the C backend will need to keep 'extern type' s through codegen. For example, if we have
 extern type c_int : int(32);
 var x: c_int;

then x has conceptually two types:
 - int(32)
 - c_int

We would like the Chapel compiler to use int(32) for the purposes of function resolution, etc,
but for the generated code to use c_int.

The way to do that would be to make the VarSymbol (and ArgSymbol) refer to TypeSymbol
instead of Type. Then, we would have two TypeSymbols that have Type int(32):
 - primitive int(32) and
 - extern type c_int.

**Comment by mppf** [comment]
- [ ] full local testing

**Comment by Kyle-B** [comment]
The changes to `externCResolve.cpp` look good to me.

**Comment by mppf** [comment]
- [x] verified full local test run passes

**Pull request merged**
