### PR TITLE
Fix bug in sub_test w/ multiple compopts + multiple file redirects in execopts

### PR DESCRIPTION
**Pull request by bradcray**
It turns out that sub_test.py has had a bug in which using a file
with multiple compopts and multiple execopts where the execopts
use different redirections resulted in an error like

```
Error: a redirection file already exists: ...
```

This PR fixes the issue by moving the capture of the original redirect
default outside of the compopts loop, and resetting the redirect to
that original choice each time through.

I've also enabled the additional compopts lines in my recently
added test which is where I first noticed this behavior wasn't
working correctly.

### CODE REVIEW

**Comment by bradcray** [comment]
@benharsh or @ronawho : I'm wondering whether I could convince one of you to review this PR.  I think it's fairly simple, but it's in the testing scripts which... definitely makes it worthy of review, and it looked like the two of you had done the most with the redirection of stdin in these scripts recently.  I have run testing and it came back clean.

**Comment by ronawho** [comment]
I can, but not till Friday or next week (change looks small, but I got confused with a quick glance, particularly around the logic/intent for `redirectin_set_in_loop`, so I want a little time to check)

**Comment by bradcray** [comment]
@ronawho: Re-pinging on this, though I'm also happy to ask someone else if you prefer.

**Comment by ronawho** [comment]
Trying to understand the history here:

https://github.com/chapel-lang/chapel/pull/98 added support for specifying a single stdin file in a .execopt file. Prior to this only a .stdin file could be used. This change also made it so you couldn't set a stdin file in both a .stdin and .execopts (and the error added for that is what you were hitting.)

https://github.com/chapel-lang/chapel/pull/956 then added support for specifying different stdin files in multi-line execopts.  It did this by trying to reset the stdin file if it was set in an execopts by as you're seeing it's incorrectly detecting that a stdin file was used for the second compopt. 

You're trying to fix that here by resetting the stdin file for each compopt. I think your fix will work, but I find the current logic slow to follow. We sometimes track the original value and only if we set it in an execopts will we reset or something like that. I think it'd be simpler and more contained to just always reset the redirectin to the original value before looking for an execopt specific one. Something like:

```diff
diff --git a/util/test/sub_test.py b/util/test/sub_test.py
index 5c07ab3ff0..fca38e5fc2 100755
--- a/util/test/sub_test.py
+++ b/util/test/sub_test.py
@@ -1953,16 +1953,9 @@ for testname in testsrc:
         if len(clist)!=0:
             if len(clist[0].split('#')) > 1:
                 explicitcompgoodfile = clist[0].split('#')[1].strip()
-        redirectin_set_in_loop = False
-        redirectin_original_value = redirectin
         for texecopts in execoptslist:
             sys.stdout.flush()
 
-            # Reset redirectin, in case execopts has multiple lines with
-            # different stdin files.
-            if redirectin_set_in_loop:
-                redirectin = redirectin_original_value
-                redirectin_set_in_loop = False
             if (len(compoptslist)==1) and (len(execoptslist)==1):
                 onlyone = True
                 execlog = get_exec_log_name(execname)
@@ -2101,6 +2094,7 @@ for testname in testsrc:
                 args += lastexecopts
             # sys.stdout.write("args=%s\n"%(args))
 
+            my_redirectin = redirectin
             if len(args) >= 2 and '<' in args:
               redirIdx = args.index('<')
               execOptRedirect = args[redirIdx + 1]
@@ -2115,8 +2109,7 @@ for testname in testsrc:
                   break;
               elif redirectin == "/dev/null":
                 if os.access(execOptRedirect, os.R_OK):
-                  redirectin = execOptRedirect
-                  redirectin_set_in_loop = True
+                  my_redirectin = execOptRedirect
                 else:
                   sys.stdout.write('[Error: redirection file %s does not exist]\n'%(execOptRedirect))
                   break
@@ -2141,17 +2134,17 @@ for testname in testsrc:
                     exectimeout = False  # 'exectimeout' is specific to one trial of one execopt setting
                     launcher_error = ''  # used to suppress output/timeout errors whose root cause is a launcher error
                     sys.stdout.write('[Executing program %s %s'%(cmd, ' '.join(args)))
-                    if redirectin:
-                        sys.stdout.write(' < %s'%(redirectin))
+                    if my_redirectin:
+                        sys.stdout.write(' < %s'%(my_redirectin))
                     sys.stdout.write(']\n')
                     sys.stdout.flush()
 
                     execStart = time.time()
                     if useLauncherTimeout:
-                        if redirectin == None:
+                        if my_redirectin == None:
                             my_stdin = None
                         else:
-                            my_stdin=open(redirectin, 'r')
+                            my_stdin=open(my_redirectin, 'r')
                         test_command = [cmd] + args
                         p = py3_compat.Popen(test_command,
                                              env=dict(list(os.environ.items()) + list(testenv.items())),
@@ -2176,10 +2169,10 @@ for testname in testsrc:
                     elif useTimedExec:
                         wholecmd = cmd+' '+' '.join(map(ShellEscape, args))
 
-                        if redirectin == None:
+                        if my_redirectin == None:
                             my_stdin = sys.stdin
                         else:
-                            my_stdin = open(redirectin, 'r')
+                            my_stdin = open(my_redirectin, 'r')
                         p = py3_compat.Popen([timedexec, str(timeout), wholecmd],
                                              env=dict(list(os.environ.items()) + list(testenv.items())),
                                              stdin=my_stdin, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
@@ -2209,10 +2202,10 @@ for testname in testsrc:
 
 
                     else:
-                        if redirectin == None:
+                        if my_redirectin == None:
                             my_stdin = None
                         else:
-                            my_stdin=open(redirectin, 'r')
+                            my_stdin=open(my_redirectin, 'r')
                         p = py3_compat.Popen([cmd]+args,
                                              env=dict(list(os.environ.items()) + list(testenv.items())),
                                              stdin=my_stdin, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

But your code is already tested and this may be a personal preference sort of thing and not objectively better, so your call for what approach you want to go with.

**Comment by bradcray** [comment]
I think you're much more expert in sub_test.py than I am, and suspect that your proposed approach has improved merit over mine (which I'd consider to be plugging a hole in the dike without thinking about the overall structure more deeply); but I don't understand the overall flow of the file well enough to evaluate it, and generally don't have enough development time these days to want to get that expert with it.  So I'd be more inclined to merge this PR as a quick fix and could open an (internal or public) issue capturing your proposed refactoring if we thought it was worth preserving as a future improvement in that way.

(I'd also be fine if someone else wanted to pick up the effort to fix the current behavior, but am not imagining you've got the time or interest for that right now either).

**Comment by ronawho** [comment]
Let's merge as-is. Whenever I get back to https://github.com/chapel-lang/chapel/pull/21351 I might try to look at this too (not that they're related, but when I get to that I should have some time (and maybe motivation) to look at this too.)

**Pull request merged**
