### PR TITLE
Set OPTIMIZE and DEBUG based on COMP_GEN_OPT etc

### PR DESCRIPTION
**Pull request by mppf**
Elliot noticed that we weren't setting -NDEBUG for --fast --llvm compiles.

The problem was that we were setting OPTIMIZE and DEBUG only in the generated Makefile.
Instead, here we set them based on COMP_GEN_OPT/COMP_GEN_DEBUG. In order
for that to work, moved those make variable settings to before the runtime headers are included.

### CODE REVIEW

**Comment by mppf** [comment]
@ronawho can you review?

**Comment by ronawho** [comment]
This looks ok to me, but I don't think I'm a good reviewer. 

Maybe @gbtitus or @bradcray who I think are the most familiar with our Makefile setup?

**Comment by gbtitus** [comment]
I think this is okay, at least I can't think of and don't see anything obviously wrong with the change. I'll assume you've thoroughly tested it!

**Comment by ronawho** [comment]
While working on some cce openmp task spawningstuff, I realized that this PR started forcing -O0 for CCE even when --fast is thrown. 

See https://github.com/chapel-lang/chapel/blob/master/make/compiler/Makefile.cray-prgenv-cray#L37 

I think this is because Makefile.cray-prgenv-cray doesn't (and shouldn't) include runtime/etc/Makefile.include.

Note that there were actually some performance regressions the day after this went in, we just don't track cce performance very carefully: http://chapel.sourceforge.net/perf/1-node-xc/?startdate=2015/04/03&enddate=2015/07/03&configs=gnunone,craynone&graphs=arrayvstupleserialaccesses,arrayvsddataserialaccesses,1darrayparalleliteration,forlooptimecompare,whilelooptimecompare,mandelbrotvariations

**Pull request merged**
