### PR TITLE
Stop printing "Error" when tags utility isn't found for make in modules

### PR DESCRIPTION
**Pull request by daviditen**
If CHPL_DEVELOPER is on, then if there isn't a tags utility that our build
system knows how to use, then the last step of building from $CHPL_HOME:
"cd modules && make" prints "make[2]: [all] Error 1 (ignored)" or similar
as the last line of output from a successful build.  This is confusing.

Add " || true" to the command that causes the error, so it is silently
ignored instead of confusingly ignored.

### CODE REVIEW

**Comment by vasslitvinov** [comment]
This looks good to me.

**Comment by daviditen** [comment]
Brad asked if this could be changed to print a message, similar to what happens under compiler/ and runtime/, so I added the message: "Tags utility not available.  Skipping tags generation."

**Comment by ben-albrecht** [comment]
@daviditen Looks good to me.

**Comment by daviditen** [comment]
Thanks for looking everybody!

**Pull request merged**
