### PR TITLE
Document dim and dims.

### PR DESCRIPTION
**Pull request by mppf**
Adds basic documentation comments for proc dims() and proc dim(d:int).

We could also document proc dim(param d) and iter dimIter, but
Brad pointed out problems with that:
 * we probably can't actually do anything with the param version
   of proc dim.
 * dimIter isn't implemented very completely and might
   need a different interface to support arbitrary iteration
   orders over multidimensional sparse domains/arrays.

Discussed with/reviewed by @bradcray and @vasslitvinov.

### CODE REVIEW

**Comment by bradcray** [comment]
Assuming nobody has recollections of it having utility, could we pull the other overload of dim() in this PR as well since, if we don't do it now, I'm afraid we'll never think to?

**Comment by vasslitvinov** [comment]
I object removing dim(param). While we cannot "do" anything with it, it reduces overhead in some cases. I'd like to keep it in case this reduction makes a difference in some future program/domain map.

I have no opinion on dimIter, so OK to pull it.

**Comment by bradcray** [comment]
Can you characterize how it reduces overhead?  I'm not seeing how it could.

**Comment by bradcray** [comment]
(also, I'm not suggesting pulling dimIter... simply not documenting it until it's better supported / designed).

**Comment by e-kayrakli** [comment]
As a side note here - @vasslitvinov and I used the name dsiPartialThese for an iterator with the same functionality as dimIter while we are working in partial reduction support. If that design is merged to the modules(currently in tests), then dimIter will be replaced by that.

**Comment by vasslitvinov** [comment]
@bradcray Typically this is a difference between indexing into an array of ranges with a number like 2 vs. with a variable. In an extreme case there could be a function like:

proc dsiDim(param d) {
  if d==1 then return <something>;
  else if d ==2 then return <something else>;
  else return <something else altogether>;
}

where param-ness would save up to 2 branches.

Interestingly, proc dim(param d) was added here:

https://github.com/chapel-lang/chapel/commit/92adb4e66

motivated by avoiding autocopies in RA. I'd like to hope that that motivation does not apply any longer. In which case OK we can pull it until such time it is needed/beneficial.

**Comment by bradcray** [comment]
Looking at the param cases in the domain map classes themselves, it definitely seems hard to believe there would be a big advantage today (though given that there's a question, I guess we should tackle that as a separate PR rather than here).  I'd prefer to avoid having param overloads "because someday we might benefit from them" because in the limit, that would suggest creating param overloads of everything...

**Comment by vasslitvinov** [comment]
In that case let's go ahead and remove it. I propose to do it in this PR for simplicity.

**Comment by mppf** [comment]
@bradcray, @vasslitvinov - it's important to me that this PR be documentation-only. Did either of you actually look at the documentation change? Is to too obvious/trivial to need review?

I don't have an opinion about the value of removing the param overload for proc dim. If we do it though, it needs to be in a different PR.

**Comment by bradcray** [comment]
I agree that the doc PR should be separate given that the other change may result in performance differences.  I thought the proposed docs were better than nothing.

**Comment by vasslitvinov** [comment]
OK to go as-is. Or, I'd prefer to have this for dims() (partly borrowing from the spec):

Returns a tuple of ranges describing the bounds of the domain, for a rectangular domain. For a sparse domain, returns the bounds of the parent domain.

**Pull request merged**
