### PR TITLE
Locally overrided man page configuration

### PR DESCRIPTION
**Pull request by shubhamkmr04**
hey @bradcray, I finally got the solution to locally override it to the man page. I changed the configuration smartquotes from False to True and then I converted  -- to (backslash--) in man.rst file so the double dash is only visible in man page.

### CODE REVIEW

**Comment by shubhamkmr04** [comment]
Please check if everything is okay.

**Comment by bradcray** [comment]
@shubhamkmr04 — Thanks for continuing to wrestle with this.

From what I'm seeing, it appears to render both the html and man-based versions of the man page correctly, and I think the slight maintenance cost of having to escape `--` options with `\` in the chpl.rst file is reasonable.

To sanity check this (since I did a poor job with it last time around), I did a diff between the 1.24 docs on the webpage (which I generated by manually splicing the new man page into the old docs to get the best combination of `--` and `–`).  The diff was virutally non-existent other than the introduction of smart quotes to the man page, which I consider to be an improvement.

I have two notes that should be addressed and one question:

* There are a few mentions of `--` options at the top of the man page that got overlooked: https://github.com/chapel-lang/chapel/pull/17455/files#diff-12b4101a5c1353ffb1a4c85e0502b0d571e34fc3019ca3facc4575dd748e3887L11-L14
* I think the comment above your smartquotes

Just to make sure I haven't missed anything, am I correct that the net difference to `conf.py` across your two changes amounts to:

```diff
-html_use_smartypants = False
+smartquotes = True
```

and that the net impact of this is that the man page uses smartquotes now?  If this line weren't here, would the effect be the same?  (i.e., rather than updating the comment, should we just remove the comment and this line?  Or would that have some different effect that I'm missing?)

**Comment by bradcray** [comment]
> If this line weren't here, would the effect be the same? (i.e., rather than updating the comment, should we just remove the comment and this line? Or would that have some different effect that I'm missing?)

I did a quick check of this, and didn't see any difference with or without this line, so would suggest (a) double checking that I'm right, and then (b) removing it and the comment if you agree.

**Comment by shubhamkmr04** [comment]
> @shubhamkmr04 — Thanks for continuing to wrestle with this.
> 
> From what I'm seeing, it appears to render both the html and man-based versions of the man page correctly, and I think the slight maintenance cost of having to escape `--` options with `\` in the chpl.rst file is reasonable.
> 
> To sanity check this (since I did a poor job with it last time around), I did a diff between the 1.24 docs on the webpage (which I generated by manually splicing the new man page into the old docs to get the best combination of `--` and `–`). The diff was virutally non-existent other than the introduction of smart quotes to the man page, which I consider to be an improvement.
> 
> I have two notes that should be addressed and one question:
> 
> * There are a few mentions of `--` options at the top of the man page that got overlooked: https://github.com/chapel-lang/chapel/pull/17455/files#diff-12b4101a5c1353ffb1a4c85e0502b0d571e34fc3019ca3facc4575dd748e3887L11-L14
> * I think the comment above your smartquotes
> 
> Just to make sure I haven't missed anything, am I correct that the net difference to `conf.py` across your two changes amounts to:
> 
> ```diff
> -html_use_smartypants = False
> +smartquotes = True
> ```
> 
> and that the net impact of this is that the man page uses smartquotes now? If this line weren't here, would the effect be the same? (i.e., rather than updating the comment, should we just remove the comment and this line? Or would that have some different effect that I'm missing?)

@bradcray I don't completely understand your point but yes the overall change to the config.py is 
- html_use_smartypants=False
+smartquotes = True
we have to keep smartquotes True ( but we have to change comment above it justify it ) in order to convert double dash(--) to n-dash to all the pages except man page so I used (\--) in man.rst so smartquotes don't affect the man page and we would see double dash (--) on man page as we wanted it to be.

**Comment by shubhamkmr04** [comment]
I checked the results by changing everything as it is in this PR is but when I changed the branch I starting getting this error.I am sure the error is not related to something I have changed in this PR. That's why I can't see changes here. Please help to solve this error.

**Comment by cassella** [comment]
I just ran into that too.  It's due to a leftover file from building docs with the `Regexp.chpl` module, conflicting with the docs generated from the same file renamed to `Regex.chpl`.

To resolve it, I had to remove the temporary file, which turned out to be `build/doc/modules/standard/Regexp.rst`.

**Comment by shubhamkmr04** [comment]
> I just ran into that too. It's due to a leftover file from building docs with the `Regexp.chpl` module, conflicting with the docs generated from the same file renamed to `Regex.chpl`.
> 
> To resolve it, I had to remove the temporary file, which turned out to be `build/doc/modules/standard/Regexp.rst`.

Do I have to delete build/doc/modules/standard/Regexp.rst  inorder to solve the error? But I am not able to delete Regexp.rst , how is this happening?

**Comment by shubhamkmr04** [comment]
> I just ran into that too. It's due to a leftover file from building docs with the `Regexp.chpl` module, conflicting with the docs generated from the same file renamed to `Regex.chpl`.
> 
> To resolve it, I had to remove the temporary file, which turned out to be `build/doc/modules/standard/Regexp.rst`.

Ohh it worked, thanks @cassella

**Comment by shubhamkmr04** [comment]
> #If true, smartquotes will be used to convert quotes and dashes to
> #typographically correct entities.
> #We turned this off because it clobbers the man page documentation
**smartquotes = True**
I think I should remove the third line in then comment

**Comment by shubhamkmr04** [comment]
So I would make two changes to this PR after you confirm:

1. Remove or comment out the **smartquotes**
2. I would put backslash in four places in the top of the man page which I accidently forgot to put.

**Comment by bradcray** [comment]
> I starting getting this error while making the docs.

Sorry, I hit that and should have mentioned it as well.  I worked around this by going to `$CHPL_HOME/docs/` and doing `make clean` (which is also important to do when comparing two versions of `conf.py` because changing `conf.py` won't cause the docs to get rebuilt in and of itself.  Our incremental docs build will cause the re-build to avoid regenerating everything because the dependency currently doesn't pay attention to `conf.py` (but probably should).

> So I would make two changes to this PR after you confirm:
> 
> Remove or comment out the smartquotes
> I would put backslash in four places in the top of the man page which I accidentally forgot to put.

I agree.  Personally, I'd remove the smart quotes line, as I don't think keeping it and re-asserting the default has value, and it's in the history if we need it.  And as you said, I'd remove the comment above it as well since it wouldn't be describing anything useful once the line is kept in (I think, right?)

**Comment by shubhamkmr04** [comment]
> > I starting getting this error while making the docs.
> 
> Sorry, I hit that and should have mentioned it as well. I worked around this by going to `$CHPL_HOME/docs/` and doing `make clean` (which is also important to do when comparing two versions of `conf.py` because changing `conf.py` won't cause the docs to get rebuilt in and of itself. Our incremental docs build will cause the re-build to avoid regenerating everything because the dependency currently doesn't pay attention to `conf.py` (but probably should).
> 
> > So I would make two changes to this PR after you confirm:
> > Remove or comment out the smartquotes
> > I would put backslash in four places in the top of the man page which I accidentally forgot to put.
> 
> I agree. Personally, I'd remove the smart quotes line, as I don't think keeping it and re-asserting the default has value, and it's in the history if we need it. And as you said, I'd remove the comment above it as well since it wouldn't be describing anything useful once the line is kept in (I think, right?)

yes @bradcray w

**Comment by shubhamkmr04** [comment]
> > I starting getting this error while making the docs.
> 
> Sorry, I hit that and should have mentioned it as well. I worked around this by going to `$CHPL_HOME/docs/` and doing `make clean` (which is also important to do when comparing two versions of `conf.py` because changing `conf.py` won't cause the docs to get rebuilt in and of itself. Our incremental docs build will cause the re-build to avoid regenerating everything because the dependency currently doesn't pay attention to `conf.py` (but probably should).
> 
> > So I would make two changes to this PR after you confirm:
> > Remove or comment out the smartquotes
> > I would put backslash in four places in the top of the man page which I accidentally forgot to put.
> 
> I agree. Personally, I'd remove the smart quotes line, as I don't think keeping it and re-asserting the default has value, and it's in the history if we need it. And as you said, I'd remove the comment above it as well since it wouldn't be describing anything useful once the line is kept in (I think, right?)

yes @bradcray I think I should remove the line with `smartquotes` and the comments. 
I just accidently closed the PR, I have opened it again, I would commit the required changes as soon as it completes all the checks

**Comment by shubhamkmr04** [comment]
One more thing @bradcray , I think I found a typo. Isn't it should be `--save directory` instead of `--savec directory` here?
Screenshot from 2021-03-25 19-47-52

**Comment by bradcray** [comment]
> Isn't it should be --save directory instead of --savec directory here?

No, this is correct—the flag is called `--savec`  ("save the generated C code").

**Comment by shubhamkmr04** [comment]
> > Isn't it should be --save directory instead of --savec directory here?
> 
> No, this is correct—the flag is called `--savec` ("save the generated C code").

Okay , I misunderstood that. Apart from that, is my PR ready to merge or do I need to do some more changes?

**Comment by bradcray** [comment]
It looks good, thanks.  I'm just going to run it through our parallel testing system to be safe, and then will merge.

**Comment by bradcray** [comment]
@shubhamkmr04 : OK, so there was one failure, which I should've anticipated.  Try running `util/start_test test/man/` and see if you get a failure.  I believe this is a test (implemented from the `sub_test` script in that directory) that checks to make sure each flag in the man page is in the compiler and vice-versa.  So I'm guessing it needs to be updated to know about your new `\` characters?  (and perhaps it could also be updated to complain if it finds `--` characters that don't have a `\` to keep us honest going forward?)

**Comment by shubhamkmr04** [comment]
> @shubhamkmr04 : OK, so there was one failure, which I should've anticipated. Try running `util/start_test test/man/` and see if you get a failure. I believe this is a test (implemented from the `sub_test` script in that directory) that checks to make sure each flag in the man page is in the compiler and vice-versa. So I'm guessing it needs to be updated to know about your new `\` characters? (and perhaps it could also be updated to complain if it finds `--` characters that don't have a `\` to keep us honest going forward?)

yes @bradcray I am getting this error too after I run  `util/start_test test/man/`. As you said we are getting this because of a test from `sub_test` . I have not quite faced this issue before so I think I have to see how can I make this to know about my new `\` that I have used in my `man/chpl.rst`.

**Comment by bradcray** [comment]
> so I think I have to see how can I make this to know about my new \ that I have used in my man/chpl.rst

Right.  And I hadn't actually opened the `sub_test` file to look at it before now, but as you've probably already found, the actual logic of the test is in `checkManPages` in that same directory.  How are your Python skills?  :)

**Comment by shubhamkmr04** [comment]
> > so I think I have to see how can I make this to know about my new \ that I have used in my man/chpl.rst
> 
> Right. And I hadn't actually opened the `sub_test` file to look at it before now, but as you've probably already found, the actual logic of the test is in `checkManPages` in that same directory. How are your Python skills? :)

I can say I am quite average in Python. I can understand the python code but I am not used to it.

**Comment by bradcray** [comment]
> I can say I am quite average in Python. I can understand the python code but I am not very used to it.

Sounds about like me.  Or even possibly a bit ahead of me.  :)

**Comment by shubhamkmr04** [comment]
sorry @bradcray for replying late. I was traveling for a day but I would definitely try my best to fix this issue :)

**Comment by shubhamkmr04** [comment]
I got the solution @bradcray , I updated `test/man/checkManPages` according to the new symbol `\` we have used and I am getting success on test `util/start_test test/man/
Screenshot from 2021-03-28 14-57-47
`

**Comment by bradcray** [comment]
Cool, thanks for sticking with it.  I'll do a bit more testing to make sure we didn't miss anything and likely merge today.

**Comment by bradcray** [comment]
@shubhamkmr04 : Hmm, I'm seeing something weird, but not seeing why your change would've caused the change in behavior.  Would you double-check me on this?

On master, if I edit `man/chpl.rst` by either (a) removing an option's description (like `--baseline`) or (b) adding a new option description (like duplicating `--baseline` and renaming it `--fake-baseline` or something like that), I get an error when I do `start_test test/man`.  But on your branch, I'm not getting errors due to these mismatches (implying that while the test is passing, it's no longer testing what it's meant to: that the man page and the compiler remain in synch with one another).

Do you see the same thing?

**Comment by shubhamkmr04** [comment]
Yes @bradcray I am getting the same thing

**Comment by bradcray** [comment]
@shubhamkmr04 : Just to clarify: Are you looking into the changes to the Python script to see why it changed the behavior and how it can be restored?

**Comment by bradcray** [comment]
@shubhamkmr04 : I think something's wrong in the formatting of the :rtype: tag:

Screen Shot 2021-03-30 at 1 41 20 PM

Compare, for example, with:  https://chapel-lang.org/docs/builtins/ChapelLocale.html#ChapelLocale.here

Sphinx (which is used by `chpldoc` to generate these documents) is notoriously picky about spacing, indentation, etc.  Be sure to generate and browse the docs you create locally to make sure they're rendering correctly.  It may be that `:rtype:` can't be used without `:returns:`?  If so, sorry not to have realized that... I don't use chpldoc very often myself.

Other than that this looks good.  Note that, in general, we request descriptive titles and OPs on PRs so that when someone browses the repository from the command-line (rather than via GitHub), they get the full context for why a PR was done.  This will also help preserve project history if we move to a different hosting solution than GitHub in the future.  I've updated your PR to try and model the kind of descriptions we try to create for future reference.

**Comment by shubhamkmr04** [comment]
> @shubhamkmr04 : Just to clarify: Are you looking into the changes to the Python script to see why it changed the behavior and how it can be restored?

Yes @bradcray , I am looking for changes in `test/man/checkManPages` to solve it.

**Comment by shubhamkmr04** [comment]
> @shubhamkmr04 : I think something's wrong in the formatting of the :rtype: tag:
> 
> Screen Shot 2021-03-30 at 1 41 20 PM
> 
> Compare, for example, with: https://chapel-lang.org/docs/builtins/ChapelLocale.html#ChapelLocale.here
> 
> Sphinx (which is used by `chpldoc` to generate these documents) is notoriously picky about spacing, indentation, etc. Be sure to generate and browse the docs you create locally to make sure they're rendering correctly. It may be that `:rtype:` can't be used without `:returns:`? If so, sorry not to have realized that... I don't use chpldoc very often myself.
> 
> Other than that this looks good. Note that, in general, we request descriptive titles and OPs on PRs so that when someone browses the repository from the command-line (rather than via GitHub), they get the full context for why a PR was done. This will also help preserve project history if we move to a different hosting solution than GitHub in the future. I've updated your PR to try and model the kind of descriptions we try to create for future reference.

I think you have commented this in wrong PR. This is the right PR #17497 for issue #17469 .
Other than that, I have got it fixed, I fixed indentation for my `:rtype:` tag in Error.message() and sorry, I did not explained well in my PR. Actually I was thinking I would edit my comment for complete explanation in my PR after you would review my PR to be correct. Thank you for editing my PR for me

**Comment by bradcray** [comment]
Oops, yes, sorry for my confusion.  Too many tabs open...

**Comment by bradcray** [comment]
> I am looking for changes in test/man/checkManPages to solve it. This is the file I edited in the first place after which test got success but not showing error after we remove --baseline .

I agree that the problem is almost certainly in there.  I'm not familiar with the script so am not sure what to suggest.  My sense is that it compares all the flags found in the man page with all those found in the `chpl --help` output, so something must be going wrong with that comparison with your change.  If it were me, I'd try putting in some debugging output to see what it is/is not finding, comparing the behavior on master vs. your branch.

FWIW, we're working on turning around a 1.24.1 release in the next few days, and it would be great to have this in it if possible.

**Comment by bradcray** [comment]
@shubhamkmr04 : We decided not to include any documentation releases in Chapel 1.24.1 after all, so don't feel any time pressure from my previous comment (though I still hope we can get this fixed).

**Comment by shubhamkmr04** [comment]
> > I am looking for changes in test/man/checkManPages to solve it. This is the file I edited in the first place after which test got success but not showing error after we remove --baseline .
> 
> I agree that the problem is almost certainly in there. I'm not familiar with the script so am not sure what to suggest. My sense is that it compares all the flags found in the man page with all those found in the `chpl --help` output, so something must be going wrong with that comparison with your change. If it were me, I'd try putting in some debugging output to see what it is/is not finding, comparing the behavior on master vs. your branch.
> 
> FWIW, we're working on turning around a 1.24.1 release in the next few days, and it would be great to have this in it if possible.

Hey @bradcray , Thanks for the explanation, I have been trying my hands on other issues as well and writing my GSoC proposal :), but I would try my best to solve this error we are facing, as soon as possible.

**Comment by bradcray** [comment]
@shubhamkmr04 : I've been meaning to check in on this to see if you're still working on it.  I saw that you pushed a commit to it, but it doesn't look like one that would fix the problem?

**Comment by shubhamkmr04** [comment]
> @shubhamkmr04 : I've been meaning to check in on this to see if you're still working on it.  I saw that you pushed a commit to it, but it doesn't look like one that would fix the problem?

Hi @bradcray  sorry for delaying this PR so much. I just started working on this PR again but the commit I pushed is not relatable for the problem, I did it by mistake. I would get back to you as soon as possible with the solution. Thanks

**Comment by shubhamkmr04** [comment]
Hey @bradcray , I have been reading `test/man/CheckManPages`  to understand what this actually is doing and eventually I got it fixed but I am seeing some branch conflicts in my PR. I did some unnecessary commits and I got some conflicts in my local branch too. To fix this, I am going to create a new PR with clean commits so you would understand it clearly. Thanks

**Comment by shubhamkmr04** [comment]
THIS IS THE NEW PR #17660

**Comment by bradcray** [comment]
Closing this in favor of #17660.

**Pull request closed without merging**
