### PR TITLE
Changed the flags name from optimize-range-iteration to the optimize-range-iterators

### PR DESCRIPTION
**Pull request by aditmehta9**
--[no-]optimize-range-iteration and --[no-]optimize-loop-iterators flags had two different keywords which were confusing. So changing the flags name from optimize-range-iteration to the optimize-range-iterators makes it easy for the user to use these flags thus solves Issue #11921.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
You do still need to modify driver.cpp for this to be accurate

**Comment by aditmehta9** [comment]
Ok

**Comment by aditmehta9** [comment]
Please review @lydia-duncan  I have made the changes in the ForLoop.cpp and main/driver.cpp

**Comment by aditmehta9** [comment]
@lydia-duncan please review the pull request last 2 commits are dependent on each other that's why checks failed.

**Comment by lydia-duncan** [comment]
> last 2 commits are dependent on each other that's why checks failed

I don't believe that's true.  Travis uses all the commits that are on the PR, not just the latest one.  I think what this means is that there is a header file that needs to be updated as well.  Have you done a `grep` for the old name in the compiler directory?

**Comment by aditmehta9** [comment]
@lydia-duncan please review I made the changes in the header file.

**Comment by lydia-duncan** [comment]
This seems fine to me.  Running testing now to make sure it passes.  I also want to make sure the rest of the team has had a chance to think about this, so I'll probably message them to bring attention to the idea.  They might comment here/the original issue, or I'll summarize

Would you mind updating the PR message to reflect the recommendations [here](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst#how-to-open-a-pr), specifically the stuff related to the final merge message?

**Comment by lydia-duncan** [comment]
Only one failure, looks like you need to run `$CHPL_HOME/util/devel/gen-chpl-bash-completion > $CHPL_HOME/util/chpl-completion.bash` and then commit the updated `chpl-completion.bash` file

**Comment by aditmehta9** [comment]
When I run this command I am getting an error:
sed: can't read util/devel/gen-chpl-bash-completion-template: No such file or directory.

**Comment by lydia-duncan** [comment]
That's odd.  [This file](https://github.com/chapel-lang/chapel/blob/master/util/devel/gen-chpl-bash-completion) uses [chpl-bash-completion-template](https://github.com/chapel-lang/chapel/blob/master/util/devel/chpl-bash-completion-template) and I don't see any references to "gen-chpl-bash-completion-template" in my $CHPL_HOME/util/devel directory

**Comment by aditmehta9** [comment]
@lydia-duncan Thank you for your guidance.

**Comment by lydia-duncan** [comment]
Reminder: I would like to see the PR message updated before I point this out to the rest of the team to make sure they are okay with the change

**Comment by aditmehta9** [comment]
Yeah, 👍

**Comment by aditmehta9** [comment]
I have updated the PR message.

**Comment by lydia-duncan** [comment]
I would like the PR message to contain more details, please.  Specifically, I would like it to *explicitly* address:
- [ ] what was the problem we were trying to solve?
- [ ] what steps do we take in this PR to solve it?

Referencing the issue via a link is not sufficient - someone reading the git history later should be able to understand what is going on in this change without having to follow any links.

Does that make sense?

**Comment by aditmehta9** [comment]
Thanks, @lydia-duncan I have updated the PR message.

**Comment by lydia-duncan** [comment]
In talking to the rest of the team, it sounds like the different naming was intentional, to indicate a technical difference in their function.  We think the names should be improved, but I think doing so in a meaningful way will be difficult without further context.  Therefore I'm going to close this PR instead of merging it.  Thanks for your effort on the change and sorry it did not work out.

**Comment by aditmehta9** [comment]
It's Okay Mam.

**Pull request closed without merging**
