### PR TITLE
Add perfcompts to resolve nightly performance test failures

### PR DESCRIPTION
**Pull request by bmcdonald3**
When the `mapMethodsThrow` config param was added, only `compopts` files were updated and not `perfcompopts` files, so this PR adds those `perfcompopts`.

### CODE REVIEW

**Comment by bradcray** [comment]
I'm feeling very nervous about the number of warnings that the map deprecation warnings generate for simple programs that don't really benefit from the warnings.  Specifically, nothing  in the language prevents me from calling a throwing method without a try/catch in a prototype / implicit module, so no code changes are required if my code has file scope code that says something like:

```chapel
myMap[i] = 0;
```

Yet I'll still get the warning, and have to throw the config flag to silence it for six months only to then remove the config flag once it's deprecated.  There's nothing I can really change in my code to make it better (I think, right?  though even if there was, it feels annoying to have to change this from a clean form to a less-clean one and then potentially change it back later).  If the program halted before, it'll still halt, just in a different way (an uncaught exception error), which seems like a reasonable change in behavior to not have to deprecate gently; and if it didn't halt, it'll still work.

In cases that call such routines where a try/catch would be required, the warning is slightly more useful, but I'm not sure it's sufficiently useful to impose the pain on the other cases.  I.e., I don't think a warning saying "You'll have to wrap a try...catch around this in a future release" is so much nicer or less annoying than one saying "You need to wrap a try...catch around this now".  And I think the noise added for the other cases tips the balance in favor of simply changing the behavior to start throwing now (and relying on the CHANGES file and release notes to be the "heads-up" rather than a release worth of warnings).

With effort, we could potentially limit the compiler warning to only notify about the change to such calls in a context that requires a try/catch.  But I don't think that effort is worth the benefit relative to just changing it to throw directly and forcing users to add try/catch now rather than warning them that they'll have to at some point in the future.

[tagging @lydia-duncan as reviewer on this series of PRs]

**Comment by lydia-duncan** [comment]
I find that argument compelling, though unfortunately it means additional work for Ben.

**Comment by bmcdonald3** [comment]
> There's nothing I can really change in my code to make it better

This is correct, there is nothing you can do in code to make it better.

> And I think the noise added for the other cases tips the balance in favor of simply changing the behavior to start throwing now

This makes sense to me and I feel like would probably be less work for me to roll back those changes and change the behavior than it would be to return in 6 months and have to remove everything then.

So, just to make sure we are all the same page, I will plan (likely next sprint) to:
1. rollback the deprecation of map methods that halt
2. change all the halting map methods to throwing without any deprecation warning or anything

Also, noting that this idea came from a similar bigint deprecation https://github.com/chapel-lang/chapel/pull/21458, though I'm not sure if that is different since bigint isn't used as widely or the initialization case is special or something.

**Comment by bradcray** [comment]
That sounds right to me, Ben.  As always, I'll be curious if there are any surprises that make us think "Uh.. maybe this isn't such a good idea" (where, for me, the impacts on existing tests were the surprise that gave me pause).

I was wondering about the implications for the bigint changes as well, though I don't think that touched codes that I'm invested in, so I hadn't proactively reviewed the impact.

**Comment by bradcray** [comment]
(e.g., "Was Arkouda affected by the bigint deprecation?" might be an interesting litmus test...)

**Comment by lydia-duncan** [comment]
Thankfully the impacted tests in the bigint PR were all functionality tests rather than real use cases and I don't recall seeing an impact in Arkouda testing?

**Comment by bmcdonald3** [comment]
> I don't recall seeing an impact in Arkouda testing?

Arkouda testing does not show failures for deprecation messages showing up, as we are only testing the correctness of some unit tests and we don't check anything against the compilation of Arkouda itself besides that it passed.

That being said, building Arkouda today, I am seeing:
```
$CHPL_HOME/modules/standard/BigInteger.chpl:581: In function ':':
$CHPL_HOME/modules/standard/BigInteger.chpl:582: note: bigint initializers that halt are deprecated, please set the config param bigintInitThrows to 'true' to opt in to using the new initializer that throws
```

So, the bigint deprecation warning is popping up in Arkouda today.

**Comment by bradcray** [comment]
> That being said, building Arkouda today, I am seeing:

Ben, is this with a developer build?  If so, does the user build point to the Arkouda source rather than the module source?  Or is this a case where the module itself should be using some sort of workaround in implementing `:` to avoid the warning?

**Comment by bmcdonald3** [comment]
> Ben, is this with a developer build? 

Yes, that build had `ARKOUDA_QUICK_COMPILE` set, which I believe is what you are referring to as a developer build. Checking without that variable set (e.g., fully optimized Arkouda build, we see the same error.


> does the user build point to the Arkouda source rather than the module source?

Yes, both of them did actually, but, due to the odd indenting, I had incorrectly missed that association:
```
  /Users/ben.mcdonald/arkouda//src/DataFrameIndexingMsg.chpl:27: called as SymTab.addEntry(name: string, len: int(64), type t = real(64)) from function 'dfIdxHelper'
  /Users/ben.mcdonald/arkouda//src/DataFrameIndexingMsg.chpl:158: called as dfIdxHelper(idx: borrowed SymEntry(int(64)), columnVals: borrowed SymEntry(real(64)), st: borrowed SymTab, col: string, objType: string, rtnName: bool)
note: generic instantiations are underlined in the above callstack
$CHPL_HOME/modules/standard/BigInteger.chpl:581: In function ':':
$CHPL_HOME/modules/standard/BigInteger.chpl:582: note: bigint initializers that halt are deprecated, please set the config param bigintInitThrows to 'true' to opt in to using the new initializer that throws
```

It isn't immediately clear to me why that is generating a warning (seems to be related to the genericity of `columnVals: borrowed SymEntry(?t)`?), but let me know if you'd like me to investigate further.

**Comment by bmcdonald3** [comment]
Compiling on CS, I'm seeing this pop up for a different module:
```
  /arkouda//src/ReductionMsg.chpl:481: called as segNumUnique(values: [BlockDom(1,int(64),false,unmanaged DefaultDist)] uint(64), se
gments: [BlockDom(1,int(64),false,unmanaged DefaultDist)] int(64))
note: generic instantiations are underlined in the above callstack
$CHPL_HOME/modules/standard/BigInteger.chpl:581: In function ':':
$CHPL_HOME/modules/standard/BigInteger.chpl:582: note: bigint initializers that halt are deprecated, please set the config param bigintInitThrows to 'true' to o
pt in to using the new initializer that throws
```
There are so many warnings generated in Arkouda that it is hard to catch all of them just scanning through the build, but the next time I do a full build I can save the output and grep it.

**Comment by lydia-duncan** [comment]
The warning line in the BigInteger module corresponds to the use of the initializer in the bigint cast operator, which I think I updated to throw as well as a result of the change

**Comment by bradcray** [comment]
OK, so I'm no longer clear on whether the similar bigint warnings are similarly annoying.  A difference between Arkouda and my original example is that I believe it is using production modules, so would need to surround the offending bigint lines in try... catch to silence the warnings rather than having them be ignorable.  But it would also need to throw the flag for 1.30 (but not earlier versions) to keep things working and remove the flag later once it no longer existed.  Or, if we didn't have the warning, it could just surround the calls with try...catch today and that would still work with older versions?  If I've got that right, it seems like just making the switch might be preferable?

**Comment by lydia-duncan** [comment]
I believe surrounding the calls with try/catch would be sufficient if the deprecation warning and flag wasn't present today.  

I think there's two scenarios we want to consider:
- The user wants to update as soon as they notice the change
- The user does not want to update immediately when they notice the change

The first scenario is the main one we're benefiting here - with this proposal, they will update their code once.  For the second scenario, with this proposal they will have to immediately update their code if they are using it in production mode, because calling a throwing function without a try/catch block will cause their program not to compile.  With the deprecation warning and flag, they can put that decision off for a bit of time, but they will have to update their command line when the flag is removed.

**Pull request merged**
