### PR TITLE
Update atomics section in README.chplenv

### PR DESCRIPTION
**Pull request by ronawho**
Simplify the explanation for how we choose whether locks or intrinsics are
going to be used to implement intrinsics.

We added a few *32 bit platforms this release so it was no longer just linux32
that didn't support atomics. Also gcc added support for 64 bit intrinsics on
32 bit platforms with 4.8.1 so we do support intrinsics on 32 bit machines
depending on the target compiler.

### CODE REVIEW

**Comment by ronawho** [comment]
@Kyle-B can you review this one? 

I'm not super happy since it's saying "We support intrinsics except for these cases. Oh and I lied to you about one of those cases where sometimes we do actually support intrinsics" but I think this is much easier to figure out than the old version

**Comment by ronawho** [comment]
Maybe 
```
If unset, CHPL_ATOMICS defaults to "intrinsics" for most configurations
except for 32 bit platforms (depending on the target compiler) or if the
target compiler is "pgi" or "cray-prgenv-pgi" in which case it defaults
to "locks". gcc 4.8.1 added support for 64 bit atomics on 32 bit
platforms so we default to "intrinsics" on 32 bit platforms when the
target compiler is a new enough version of "gnu"
```

?

**Comment by Kyle-B** [comment]
```
If unset, CHPL_ATOMICS defaults to "intrinsics" for most configurations. On 32
bit platforms, or if the target compiler is "pgi" or "cray-prgenv-pgi" it
defaults to "locks".

Note: gcc 4.8.1 added support for 64 bit intrinsic atomics on 32 bit platforms.
We will default to "intrinsics" when using the target compiler "gnu" with a
recent enough version of gcc.
```
?

**Comment by ronawho** [comment]
I like your version. Do you think it's worth adding some qualifier to `On 32 bit platforms`? i.e. simply saying `On some 32 bit platforms` or saying `On some 32 bit platforms (depending on the target compiler)`?

**Comment by Kyle-B** [comment]
`On some 32 bit platforms` is fine with me. I'm (surprisingly) not a  big fan of the the parenthetical.

**Pull request merged**
