### PR TITLE
Adjusted execopts and skipifs for long-running AOC tests

### PR DESCRIPTION
**Pull request by bradcray**
Some of my AOC tests take awhile to run under normal configurations,
so timed out under valgrind and AOC.  Here, I'm adjusting them via
execopts and/or skipifs as follows:

* Skipping the long-running configurations for day12a, day19, day19a, day22a
* Skipping day21a completely for valgrind
* Skipping day23a completely for valgrind and asan

I'm generally opposed to skipping tests completely under valgrind, but these
don't feel like the most important tests for us to keep clamped down on, and
I also hope to get back to some of these slow cases and speed them up in
the future (AOC site says everything should run in < 15 seconds on a 10-year-old
system...), so would rather spend the time there than raising their timeouts
to keep them going for now.

While looking at these, I also noticed that one of my execopts files was
never promoted to the futures directory, which isn't a problem while the
future isn't working, but would be if it were fixed.

### CODE REVIEW

**Comment by bradcray** [comment]
@ronawho: Thanks for the tip on using script-based execopts, which still feels like a foreign concept to me.  I think this counts as trivial (and my testing on it is still running), but let me know if you'd have time to give my scripting a quick review.

**Comment by ronawho** [comment]
What's here looks good to me. I was curious if there's any other tests that are slow, but not quite timing out. Here are the top 25 advent of code tests for valgrind:

```
chapcs11: Nightly $  grep "Elapsed execution time.*adventOfCode" day2-Tue-valgrindexe.log | awk '{print $(NF-1),$0}' | sort -nr | cut -f2- -d' ' | head -n25
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day22a (execopts: 2)" - 1003.137 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day21a (compopts: 1 execopts: 1)" - 1000.453 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day21a (compopts: 1 execopts: 2)" - 1000.387 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day23a (compopts: 1)" - 1000.315 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day12a (execopts: 4)" - 1000.307 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day19 (execopts: 2)" - 658.299 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day19a (execopts: 2)" - 654.486 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day20 (execopts: 4)" - 488.586 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day20 (execopts: 3)" - 228.530 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day7a (execopts: 2)" - 220.214 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day15 (execopts: 2)" - 186.993 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day23 (compopts: 1)" - 180.435 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day12a (execopts: 3)" - 68.436 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day25 (execopts: 2)" - 64.331 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day22a (execopts: 1)" - 62.957 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 60.255 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day18 (execopts: 6)" - 43.047 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day12 (execopts: 4)" - 41.345 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day13 (execopts: 2)" - 22.570 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day15a" - 17.473 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4 (execopts: 2)" - 15.931 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day18a (execopts: 2)" - 14.651 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day6 (execopts: 2)" - 14.054 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day19a (execopts: 1)" - 9.242 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day11a (execopts: 2)" - 9.234 seconds]
```

If you just want to skip for the timing out ones that's fine with me, but if we want to skip any of the other long running ones I'd be fine with that too.

**Comment by ronawho** [comment]
And top 10 asan and regular linux64:

```
chapcs11: Nightly $ grep "Elapsed execution time.*adventOfCode" day2-Tue-asan.log | awk '{print $(NF-1),$0}' | sort -nr | cut -f2- -d' ' | head -n10
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day23a (compopts: 1)" - 300.291 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day21a (compopts: 1 execopts: 1)" - 100.744 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day22a (execopts: 2)" - 95.213 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day12a (execopts: 4)" - 78.262 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day21a (compopts: 1 execopts: 2)" - 74.290 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day19 (execopts: 2)" - 67.635 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day19a (execopts: 2)" - 66.664 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day23 (compopts: 1)" - 20.036 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day12a (execopts: 3)" - 5.391 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 3.856 seconds]

chapcs11: Nightly $ grep "Elapsed execution time.*adventOfCode" day2-Tue-linux64.log | awk '{print $(NF-1),$0}' | sort -nr | cut -f2- -d' ' | head -n10
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day12a (execopts: 4)" - 156.099 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day19a (execopts: 2)" - 134.118 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day19 (execopts: 2)" - 130.835 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day23a (compopts: 1)" - 53.580 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day23 (compopts: 1)" - 43.754 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day22a (execopts: 2)" - 40.200 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day21a (compopts: 1 execopts: 1)" - 14.135 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day12a (execopts: 3)" - 10.830 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day21a (compopts: 1 execopts: 2)" - 10.348 seconds]
[Elapsed execution time for "studies/adventOfCode/2021/bradc/day4a (execopts: 2)" - 6.855 seconds]
```

I might be inclined to remove a couple of the execopts for the slower ones. Right now 6 of the top 20 slowest linux64 test are advent of code ones.

**Comment by bradcray** [comment]
> Right now 6 of the top 20 slowest linux64 test are advent of code ones.

Woohoo!  :D

Is that in a normal run, valgrind run, asan run?

**Comment by ronawho** [comment]
std linux64

**Comment by bradcray** [comment]
So you're saying everyone else has been slacking off when writing their Chapel programs, and not doing "real" computations like navigating an underwater sub to find Santa's keys?  :D

**Comment by bradcray** [comment]
Thank goodness for your suggestion... now there will be fewer lines of Python in my GitHub coding profile.  :D

**Review by ronawho — APPROVED** [review]

**Pull request merged**
