### PR TITLE
Add a .future about recursive leader iterators.

### PR DESCRIPTION
**Pull request by daviditen**
This test is basically the same as
functions/iterators/bradc/recursiveStandalone.chpl except this one uses a
recursive leader instead of recursive standalone.

### CODE REVIEW

**Comment by daviditen** [comment]
@bradcray Recursive leaders result in the same basic error pointing into an internal module as recursive standalone.  It looks like we have to do something about this for parallel iterators in general.

**Comment by bradcray** [comment]
OK, thanks David.  I thought when @vasslitvinov was working on adding intents to forall loops, he was trying to work hard to preserve the ability to have recursive leaders, which is part of what caught me by surprise here (Vass, can you clarify what I must be misremembering here?  Maybe some cases work and others don't?).  OTOH, Elliot mentioned that Tim Zakian filed a future against recursive leaders when working on filerators (I didn't go looking for that to compare).

IMO, this isn't a high priority at present, though it does make it hard to write a good parallel directory walker...  (I think I'd have to create an atomic stack/queue of work items to model the recursion myself, which brings to mind @mppf's recent mention of wanting to support atomic class references, which would help a lot).

**Comment by vasslitvinov** [comment]
There are "recursive leaders" that work I think:

  test/functions/deitz/iterators/leader_follower/test_recursive_leader*

The difference I see is this. In the above tests the recursive call is
to the same leader. In david's example the recursion is through a
full-fledged forall loop.

**Comment by bradcray** [comment]
Thanks Vass -- I tried this style as well, but wasn't successful.  I'll give it another try -- maybe I had some other issue....

@daviditen , do we have a preference/contraint that the iterKind argument is typically the first or last argument in a leader/standalone iterator?  I'm noticing that Steve put it first in this test, but that I've been putting it last in my routines.

**Comment by vasslitvinov** [comment]
@bradcray - from functionResolution.cpp:

      // "tag", "followThis" and optionally "fast" should be placed at the end
      // of the formals in the source code as well, to avoid insertion of an
      // order wrapper.

Order wrappers do not exist any more though.

**Comment by bradcray** [comment]
Huh... I'm not sure what I was doing wrong the other night, but with the "call with for, pass along tag" approach, I do seem to be able to get the recursive standalone cases working.  Thanks for the data (and resulting encouragement) Vass!

**Comment by bradcray** [comment]
Hi @daviditen -- Having closed out the oldest pull request, you now inherit the title.  I suspect that this is one that you forgot had not been merged?

**Comment by daviditen** [comment]
@bradcray Thanks.

**Pull request merged**
