### PR TITLE
Update spec w.r.t. single-statement 'do'; lack of 'return' special case

### PR DESCRIPTION
**Pull request by bradcray**
This updates the spec's syntax diagrams to add support for single-statement 'do' subroutine bodies and to remove the previous exception for single-statement returns.  It also makes the iterator's syntax diagrams use the `function-body` rule from the procedures chapter, as the previous definition was incorrect (had a single-statement yield exception that the implementation doesn't support) and it doesn't require its own case.

While here, we were surprised to find that there was no text talking about procedure bodies, so I added a new short section about that, mentioning the single-statement `do` form, and moved the return statement section into it as a subsection.

It also udpates a few examples that I ran into while looking for other places that might need changing; apparently these are among the examples that have not been converted to running tests.

### CODE REVIEW

**Comment by bradcray** [comment]
@benharsh : Would you have time to review this as a follow-on to #21632 ?  Does not need to be today.

**Review by benharsh — APPROVED** [review]
Looks good to me.

I took a quick look through the ``procedures.rst`` file looking for a place where we highlight the single-statement functionality, but didn't see one. Would it be worth adding a section describing the ``do`` case, and its purpose, or is that below the bar for the spec?

**Comment by bradcray** [comment]
I was surprised not to find any pre-existing text talking about the exception either (though it made my job easier!), and looking for it was what made me notice those other cases.  Even the procedures primer doesn't seem to mention the exception.

I wouldn't be opposed to adding a paragraph about the `do` case, though I'm also not entirely sure what to say about it...  And given that there are lots and lots of sections about the procedure interface itself (arguments, varargs, named args, inferred types, return intents, etc.), it would likely end up pretty far from the syntax diagrams themselves.  I checked the other control flow forms and didn't see any particular rationale for the single-statement keyword-based forms outside of the syntax productions.  

Taking a swing at it to make sure I'm not just being lazy, we could add a section like this just before the "The Return Statement" section:

```
Procedure Bodies
=============
A procedure's body is made up of one or more statements that are executed when a call to the procedure is made.  Procedure bodies can always be specified using a compound or _block_ statement, set off by curly brackets.  In the event that the procedure body is just a single statement, the `do` keyword can be used to define the body, as a shorthand, similar to other forms of control flow.
```

Let me know what you think.

(Also, in looking into this, I found that the iterators section suggests that a single yield statement is legal, which sent me into a panic because I thought they shared a parser rule so was worried I forgot a case... but it looks like the spec is incorrect in this regard.  That said, I need to make a symmetric change in that section now that I've noticed it—I'd assumed `function-body` was used by both procedures and iterators prior to this.  In fact, the fix is probably just to use `function-body` there...)

**Comment by benharsh** [comment]
That text looks good to me 👍

**Comment by bradcray** [comment]
The latest commit might be worth another look—it's pretty close to what I drafted here in the comments, along with cross-references to it, and moving the return statement into it as a subsection.

**Review by benharsh — APPROVED** [review]

**Pull request merged**
