### PR TITLE
Create chpldoc documentation for SysBasic.chpl

### PR DESCRIPTION
**Pull request by mppf**
Updated Perl script to generate documentation comments
Updated Makefile to create documentation for that module

### CODE REVIEW

**Comment by lydia-duncan** [comment]
This looks fine to me, but @thomasvandoren may want to look at it anyways, since he understands more about makefiles than I do.

**Comment by bradcray** [comment]
I didn't realize that @mppf was diving into SysBasic.  I had been thinking about this case this week, and was going to propose that we document this using a dummy module that contains declarations without definitions like:

/* This is an alias for C's 'long' type */
extern type c_long;

given that we want to put our chpldocs on the web and can't know what a user's environment's going to be (and wouldn't want to generate documentation from our own copy of the file).  That's not to say that this mod isn't nice as well -- I just think that it only helps users who are creating that documentation for themselves and that we'll want something vague-r for the web.

**Comment by mppf** [comment]
Actually the only thing that we would need to do in order to get a generic (and not machine-specific) version of the file would be to remove the right-hand-side of the type = lines in the chpldoc. We could make a script to do this (in this case) or we could maybe have some means of asking chpldoc nicely not to emit the right-hand-side.

So, in other words, I agree, but I think we have to choose between 3 options:
 1 script to modify chpldoc output
 2 modify chpldoc (e.g. use flags or something) to not output Chapel type (e.g. int(64))
 3 generate a stand-in module that we chpldoc which leaves the types opaque (possibly with a script)

I'd like to let @lydia-duncan  or @thomasvandoren weigh in on the approach there.

**Comment by thomasvandoren** [comment]
I think it's ok to have SysBasic in the docs generated with `make modules-docs` -- I think that is how a user would generate docs for their own system. I don't feel passionately about that, though, and would be fine with leaving it out, too.

**Comment by mppf** [comment]
@thomasvandoren right, I (at least) was planning to include it - the question is should that document include the (non-portable) equivalents e.g. c_long = int(64) or just say that c_long is available and is equivalent to C's long. If it should leave out the int(64) part, how do we do that?

**Comment by thomasvandoren** [comment]
Got it. I like option 3 in your proposal best. I think we could update the makeSysBasicTypes to generate a SysBasic for chpldoc and the regular one pretty easily.

**Comment by lydia-duncan** [comment]
My preferred option would be option 2 and maybe have it apply to all extern types.  I think it's likely we would encounter this with other externs, such as qio_file_ptr_t.  At least, I can see a situation where we would want to bleed more of qio_file_ptr_t into module code, but not have anyone see it outside of the module source code.

**Comment by lydia-duncan** [comment]
Though now that I think about it, we probably want to "no doc" qio_file_ptr_t anyways.

**Comment by lydia-duncan** [comment]
It would be nice to have a solution that can be applied more generally, though I'm fine with going with a different decision.

**Comment by mppf** [comment]
OK, I tried making a dummy module with e.g.
  extern type c_long;
but the problem is that chpldoc doesn't consider those documentation-worthy. And putting just 
  type c_long;
isn't valid Chapel.
So I've put them as 
  type c_long = integral;

for now.

**Comment by thomasvandoren** [comment]
:+1:

**Comment by bradcray** [comment]
To clarify my original comment, I like the concept that users can document their own copy of SysBasic.  I was only concerned that we not throw our copy of SysBasic with definitions intact out onto the web without obscuring the types as Michael has done here.  I'm OK with them showing up as integral, but my strong preference would be, ultimately, for them to not have any definition.  I.e. to show up as,

  type c_long;
     ...blah blah blah....

Reason being that:

  type c_long = integral;

is not legal Chapel.  So this could be considered a feature request for chpldoc to generate types without definitions and/or extern types (whichever of the two is causing Michael's attempt to get dropped on the floor).

(Tagging @thomasvandoren @mppf just in case github doesn't keep mailing people after a branch is closed, I can't remember)

**Pull request merged**
