### PR TITLE
Change `sync`/`single` `write??()` routines to take value by `in` intent

### PR DESCRIPTION
**Pull request by bradcray**
This PR changes the `.write*` methods on `sync`/`single` to take their values using
`in` intent rather than default intent as before.  This permits coercions to take place,
which seems natural, and doesn't break anything.  It also seems to fit our general
theme to use `in` more frequently in such cases lately.

More specifically, this resolves a user request to be able to pass non-nilable class instances
to a `sync`/`single` of nilable class type, as exhibited in the new test here.

The only other changes required were to remove some no longer generated errors from
some tests that lock in errors for cases that don't work today.

### CODE REVIEW

**Comment by bradcray** [comment]
@mppf / @dlongnecke-cray : I'm wondering whether one of the two of you could review this
because I think of you as being most conversant with using the `in` intent in data structures.
Specifically, can you think of any downsides to this change that I'm not anticipating?  Thanks.

**Comment by mppf** [comment]
@bradcray - I had already done this in my PR #18379 so we should have a conversation about how to proceed.

**Comment by bradcray** [comment]
Aha, thanks, I hadn't seen that PR (and probably wouldn't have read far enough to realize it subsumed this even if I had).  I'm completely fine closing this PR in favor of yours if we can get that merged.

**Comment by bradcray** [comment]
@mppf: I'm closing this now that #18379 is merged, but can you tell me:  Did your tests cover the cases in the test that I filed in this PR to the extent that it's reasonable to drop it on the floor?  (I started looking through the PR but the new tests were long enough that I thought I'd just ask rather than sifting through them).  Thanks.

**Comment by mppf** [comment]
@bradcray - the closest test to that specific case is https://github.com/chapel-lang/chapel/blob/main/test/types/sync/ferguson/sync-shared-nilable.chpl . It seems to me that your test adds a bit of value beyond that one, for this case specifically. Do you think you'd be able to make a PR that appends your test to that one?

**Comment by bradcray** [comment]
> Do you think you'd be able to make a PR that appends your test to that one?

Yep, I did this on Wednesday in #18715.

**Pull request closed without merging**
