### PR TITLE
Update copyright notices to 2024

### PR DESCRIPTION
**Pull request by riftEmber**
Updates copyright year to 2024 in all our code.

Done using the one-liners from the OP of https://github.com/chapel-lang/chapel/pull/21313 but with previous and current year incremented, as well as manual updates to `doc/rst/conf.py` and `util/test/checkCopyrights.bash` as mentioned there.

One-liners run for mass updates:
- `git grep -l 'Copyright 2020-2023' -- ':!third-party/' ':!test/' | xargs sed -i '' -e 's/Copyright 2020-2023/Copyright 2020-2024/g'`
- `git grep -l 'Copyright 2021-2023' -- ':!third-party/' ':!test/' | xargs sed -i '' -e 's/Copyright 2021-2023/Copyright 2021-2024/g'`
- `git grep -l 'Copyright 2022-2023' -- ':!third-party/' ':!test/' | xargs sed -i '' -e 's/Copyright 2022-2023/Copyright 2022-2024/g'`
- `git grep -l 'Copyright 2023' -- ':!third-party/' ':!test/' | xargs sed -i '' -e 's/Copyright 2023/Copyright 2023-2024/g'`

Resolves https://github.com/Cray/chapel-private/issues/5736.

Future work: Create a script to do these rote updates, per https://github.com/Cray/chapel-private/issues/1540.

[reviewer info placeholder]

Testing:
- [x] `checkCopyrights.bash` passes (with trivial modification locally to enforce check before January 7)

### CODE REVIEW

**Review by DanilaFe — APPROVED** [review]
Looks good to me, though I obviously haven't looked through all 1759 changed files. You probably thought of this, but just in case:

Bhavani's one-liners included a new case for 2022 -> 2022-2023. Did you have a corresponding one-liner for 2023 -> 2023-2024 in this PR? It would be nice if the commands you used were listed in the OP anyway.

**Comment by DanilaFe** [comment]
I also found a few occurrences locally that still mention 2023. I'm posting it now and will edit the list to remove non-committed files.

```
man/man1/chpldoc.1:229:Copyright 2020\-2023 Hewlett Packard Enterprise Development LP
man/man1/chpl.1:1197:Copyright 2020\-2023 Hewlett Packard Enterprise Development LP
tools/chpldoc/COPYRIGHT:1:"Copyright 2020-2023 Hewlett Packard Enterprise Development LP\n"
frontend/test/resolution/testSuper.cpp:2: * Copyright 2023-2024 Hewlett Packard Enterprise Development LP
frontend/lib/types/ExternType.cpp:2: * Copyright 2023-2024 Hewlett Packard Enterprise Development LP
test/chpldoc/compflags/combinations/z_copyright_help_version.doc.good:2:Copyright 2020-2023 Hewlett Packard Enterprise Development LP
test/chpldoc/compflags/combinations/z_copy_help.doc.good:1:Copyright 2020-2023 Hewlett Packard Enterprise Development LP
test/chpldoc/compflags/combinations/copyright.doc.good:1:Copyright 2020-2023 Hewlett Packard Enterprise Development LP
test/chpldoc/compflags/combinations/z_copy_version.doc.good:2:Copyright 2020-2023 Hewlett Packard Enterprise Development LP
test/chpldoc/compflags/combinations/z_help_version.doc.good:2:Copyright 2020-2023 Hewlett Packard Enterprise Development LP
test/chpldoc/compflags/combinations/version.doc.good:2:Copyright 2020-2023 Hewlett Packard Enterprise Development LP
test/compflags/bradc/copyright/declint.good:1:Copyright 2020-2023 Hewlett Packard Enterprise Development LP
test/deprecated/CyclicStridable.chpl:7: * Copyright 2020-2023 Hewlett Packard Enterprise Development LP
util/buildRelease/license_text_for_comment.txt:1:Copyright 2023-2024 Hewlett Packard Enterprise Development LP
util/build_configs/cray-internal/chapel.spec.template:19:License: Copyright 2023-2024 Hewlett Packard Enterprise Development LP All Rights Reserved.
doc/rst/modules/layouts/LayoutCS.rst:4:   :synopsis: * Copyright 2020-2023 Hewlett Packard Enterprise Development LP
doc/rst/modules/dists/PrivateDist.rst:4:   :synopsis: * Copyright 2020-2023 Hewlett Packard Enterprise Development LP
doc/rst/modules/dists/BlockCycDist.rst:4:   :synopsis: * Copyright 2020-2023 Hewlett Packard Enterprise Development LP
doc/rst/modules/dists/HashedDist.rst:4:   :synopsis: * Copyright 2020-2023 Hewlett Packard Enterprise Development LP
third-party/chpl-venv/install/chpldeps/chapel/__init__.py:2:# Copyright 2020-2023 Hewlett Packard Enterprise Development LP
third-party/chpl-venv/install/chpldeps/chapel/replace/__init__.py:2:# Copyright 2020-2023 Hewlett Packard Enterprise Development LP
compiler/llvm/llvm-global-to-wide/CMakeLists.txt:1:# Copyright 2023-2024 Hewlett Packard Enterprise Development LP
compiler/main/COPYRIGHT:1:"Copyright 2020-2023 Hewlett Packard Enterprise Development LP\n"
```

**Comment by riftEmber** [comment]
> Bhavani's one-liners included a new case for 2022 -> 2022-2023. Did you have a corresponding one-liner for 2023 -> 2023-2024 in this PR? It would be nice if the commands you used were listed in the OP anyway.

I did, the cases it caught are committed in 753d2cd762f7c658b6b80fe8a43ac6c346cdf5f3. I'll add that and the other one-liners used to the OP.

BTW, I'm working on a general copyright year update script as a followup now, so we can hopefully stop worrying about copying one-liners after this.

**Comment by riftEmber** [comment]
> I also found a few occurrences locally that still mention 2023

None of these exist in the git tree of `main` except for `test/deprecated/CyclicStridable.chpl`. I believe that one can be left as-is since Bhavani's one-liners manually exclude `test/` from updates. The rest look to me like they used to be in the tree but have since been removed (and `.gitignore`'d); I think think they are generated when we build, based off the updated `COPYRIGHT` in the repo root.

**Comment by bradcray** [comment]
Thanks for the quick turn on this, @riftEmber!

**Pull request merged**
