### PR TITLE
mason bench & extend UnitTest for benchmarking

### LINKED ISSUE #15680: Mason Bench and benchmarking framework design
This issue is a part of GSoC proposal "Improvements to Mason Package Manager", and it aims to extend the UnitTest module by adding a benchmarking framework  and to  implement a `mason bench` command that would be used to run benchmarks. 

Initial discussions that have taken place in Slack with @ben-albrecht @Spartee and @krishnadey30 can be summarised as follows : 
- Ideas for the benchmarking framework is being taken from Go's benchmarking framework. However, it should reflect features available in `start_test --performance` so that transition from `start_test` to `mason bench` is easy for an user and loss of features would be minimal.
- Since Mason is heavily inspired by Cargo, the `mason bench` command would resemble to `cargo bench` command. Also, `mason bench` should be usable both inside and outside mason packages, similar to `mason test`.
- Options for the `mason bench` would consists of essential options available in `cargo bench` such as `--no-fail-fast`, `--offline`, `--verbose` etc.
- If `mason bench` is called inside a mason package, then it should look for files inside a `bench` directory, else if it's called outside a mason package, it should look for files containing benchmarking functions by crawling through the directories.
- There can be 2 modes to run benchmarks :- 
   - running a compiled program N times and report the average time to execute that program
   - running a function within a program N times and report the time of only that function.

### PR DESCRIPTION
**Pull request by ankingcodes**
Aims to add a new `mason bench` command and extend the UnitTest module for running Benchmarks in Mason projects.

fixes #15680

### CODE REVIEW

**Comment by ankingcodes** [comment]
After commit eeb1d2e, 
Benchmarks are stored inside the `benchmark/` directory. 
The test[ `arrayAdd.chpl` ](https://github.com/chapel-lang/chapel/blob/master/test/studies/elegance/arrayAdd.chpl)is written using Benchmark class as follows: 
```chpl
use UnitTest;

config const order: int = 10, 
       subOrder: int = 5;

proc elegant() {
  var Dom = {1..order, 1..order},
      subDom = {1..subOrder, 1..subOrder};
  var Array: [Dom] real, subArray: [Dom] real = 2.0;
  Benchmark.startTimer();    // starts the timer 
  for 1..Benchmark.N {
    for (i, j) in Dom {
      for k in 1..subOrder do 
        Array[i,j] += i*j*subArray[k, k];
    }
  }
  Benchmark.stopTimer();     // stops the timer
  Benchmark.log("elegant");   // function name passed for logging metrics
}

proc performant() {
  var Dom = {1..order, 1..order},
      subDom = {1..subOrder, 1..subOrder};
  var Array: [Dom] real, subArray: [Dom] real = 2.0;
  var tmp: real = 0;
  Benchmark.startTimer();
  for 1..Benchmark.N {
    for (i, j) in Dom {
      for k in 1..subOrder do 
        tmp += i*j*subArray[k, k];
      Array[i,j] += tmp;
    }
  }
  Benchmark.stopTimer();
  Benchmark.log("performant");
}

proc main() {
  elegant();
  performant();
}
```
The compopts for this program is defined in `benchmark/arrayAdd.toml` as follows: 
```toml 
[bench]
[bench.arrayAdd]
compopts = "--set order=100 --set subOrder=1000"
```
When `mason bench` is run inside a mason project home, having a directory tree as : 
```
Mason.toml
/src/
/test/
/example/
/benchmark/
   arrayAdd.chpl
   arrayAdd.toml
   transposePerf.chpl
   invalid.chpl
   array/
      a.chpl
      arrayAdd.chpl
```
The output we get is as follows: 
```
Skipping registry update since no dependency found in manifest file.
Compiling Benchmark Tests ...

Compiled arrayAdd.chpl successfully
Compilation failed for invalid.chpl
Compiled transposePerf.chpl successfully
Compiled array/a.chpl successfully
Compiled array/arrayAdd.chpl successfully

============================================

             Benchmark Results

============================================

Function: elegant
Iterations: 10000
Total Time Elapsed (ms): 4119.0
Average Time (ms/N): 0.4119
Function: performant
Iterations: 10000
Total Time Elapsed (ms): 5606.0
Average Time (ms/N): 0.5606

============================================

Transpose:
Function: transposePerf
Iterations: 10
Total Time Elapsed (ms): 87647.0
Average Time (ms/N): 8764.8

============================================

Function: addNumbers
Iterations: 10000
Total Time Elapsed (ms): 1.0
Average Time (ms/N): 0.0001

============================================

Function: elegant
Iterations: 10000
Total Time Elapsed (ms): 4514.0
Average Time (ms/N): 0.4514
Function: performant
Iterations: 10000
Total Time Elapsed (ms): 5600.0
Average Time (ms/N): 0.56

============================================
```

**Comment by ankingcodes** [comment]
@ben-albrecht - The above comment explains the working of `mason bench`. This PR is good for a second round of review. Please let me know for changes / improvements. 👍🏻

**Comment by ben-albrecht** [comment]
@ankingcodes - I'm going to convert this PR to a draft to reflect the long-term WIP nature of it.

**Comment by bradcray** [comment]
@ben-albrecht: I'm cleaning house and was inclined to close this PR due to inactivity, but then from what I'm seeing, it looks like the ball's in your court?  From your last comment, I thought it was in @ankingcodes, but it looks like there are open questions that you never replied to?

**Comment by ben-albrecht** [comment]
> @ben-albrecht: I'm cleaning house and was inclined to close this PR due to inactivity, but then from what I'm seeing, it looks like the ball's in your court? From your last comment, I thought it was in @ankingcodes, but it looks like there are open questions that you never replied to?

We had some discussions offline, but there are some open questions that remain (and it was admittedly a failure on my part to summarize them here). I suggest we close this PR for now and I'll open an issue with remaining questions to be answered linking this PR. When someone has the cycles to champion this, they can pick up from there (where I think we'd still want to use this PR's changes, just with some updates).

**Comment by bradcray** [comment]
That works for me.  @ankingcodes, if this is something you'd like to continue working on, don't take this as a sign of disinterest per se (though I'm not the best person to evaluate it, as I don't use mason or unit testing much, though I don't mean that as a negative statement, just that it's outside of my areas of expertise)—In closing it, I'm just trying to reduce the number of long-term open PRs.

**Pull request closed without merging**
