### PR TITLE
Proposed contributors file for Chapel version 1.18.0

### PR DESCRIPTION
**Pull request by bradcray**
As usual, contributors who have added code since the last release that
will be part of this release are listed in the first section.  Past
contributors who have not been active since the last release have been
moved down to the second section.

### CODE REVIEW

**Comment by bradcray** [comment]
@chapel-lang/core-contributors : If you could check that I haven't missed anyone for whom you've merged code for the 1.18.0 release, that would be great.

@ian-bertolacci , @caizixian , @LouisJenkinsCS , @saru95 , @Spartee , @Tshimanga , @thomasvandoren , @ysahil97: If you could check that I've spelled your names right and haven't made any other errors, I'd appreciate it.

**Comment by ben-albrecht** [comment]
>  If you could check that I haven't missed anyone for whom you've merged code for the 1.18.0 release, that would be great.

I believe we're missing Avneet Kaur, @avneet14027 (bigint documentation)

**Comment by caizixian** [comment]
@bradcray it's correct

**Comment by bradcray** [comment]
@LouisJenkinsCS : I didn't list PNNL for you because we don't have a CCLA from them with your name on it and you haven't contributed any code (that I saw) that will be in the 1.18 release since becoming a PNNL employee.  Put another way, this file isn't intended to list what affiliations a person claims, but from which ones they contributed (e.g., I'm affiliated with UW, but haven't contributed code in that role).

(That said, I'm not completely consistent in this in that I tend to list summer interns' home institutions to give a nod that they aren't full-time Cray employees... I could make that clearer).

**Comment by bradcray** [comment]
> I believe we're missing Avneet Kaur, @avneet14027 (bigint documentation)

Good catch, thanks Ben (and sorry Avneet!).  I looked through those commits, but the ones I poked into were in the test/ directory and so I quickly assumed they all were.  My bad!

**Comment by bradcray** [comment]
@avneet14027 : Should Rupal be included as well?  (e.g., I don't know whether you pair programmed on your code changes and submitted under your account for convenience).

**Comment by bradcray** [comment]
The beauty of asynchronous messaging!  (I'm in no hurry.  :) )

**Comment by lydia-duncan** [comment]
I believe you also missed @verma-varsha (expandVars function in the Path library)

**Comment by bradcray** [comment]
> I believe you also missed @verma-varsha (expandVars function in the Path library)

Huh, it looks like you're right.  I wasn't using quite as wide a window as I should've when looking for commits (and this view doesn't show merge commits):

https://github.com/chapel-lang/chapel/graphs/contributors?from=2018-04-01&to=2018-09-05&type=c

Thanks for catching that!  I expanded the view back to code freeze and didn't notice anyone else I'd missed (but my eyes and mind are getting feeble...):

https://github.com/chapel-lang/chapel/graphs/contributors?from=2018-03-20&to=2018-09-05&type=c

**Comment by Spartee** [comment]
looks good to me!

**Comment by ysahil97** [comment]
@bradcray Would it be okay to replace my affiliation from `individual contributor / [GSoC 2018]` to `[Indian Institute of Technology Hyderabad] / [GSoC 2018]`?

**Comment by thomasvandoren** [comment]
LGTM 👍

**Comment by bradcray** [comment]
> Would it be okay to replace my affiliation...

Hi @ysahil97 : That's a reasonable request, but I'm not certain yet.  Let me see if I can be more consistent in how I handle acknowledging summer students' home institutions in cases where they aren't doing Chapel work funded by that institution.

**Comment by bradcray** [comment]
@ysahil97 : Did you mean "**International** Institute of Information Technology, Hyderabad"?  (there aren't two IIIT-Hyderabads, are there?)

**Comment by bradcray** [comment]
If anyone's unhappy with how this ended up, please let me know and we'll try to correct / improve it for the next version.

**Comment by ysahil97** [comment]
@bradcray It was actually `[Indian Institute of Technology Hyderabad]`. People usually confuse between the two since they have similar acronyms. [Link](https://www.iith.ac.in/).
Sorry I respond it on time. Have been juggling between academics and project work recently.

**Comment by bradcray** [comment]
@ysahil97 : Wow, sorry to have doubted you and not to have spent a few more minutes googling the names to sort it out myself.  I'm sure I've seen both acronyms several times over the years and never noticed that they were two distinct institutions—really confusing!  I'm working on getting a fix in quickly.

**Pull request merged**
