### PR TITLE
Gaussian probability function added

### PR DESCRIPTION
**Pull request by egeOzpinar**
There wasn't Gaussian probability function but added at this pr.

### CODE REVIEW

**Comment by mppf** [comment]
@egeOzpinar  - thanks for making this PR. I think the first question I have is - why should this function be added to the Math module (which is included by default) rather than in, say, a Statistics module? Where do other languages that have a version of this function available put it?

**Comment by egeOzpinar** [comment]
@mppf I looked at Python's statistics library and the function is in it but I couldn't find statistics library in Chapel. If there isn't a statistics library I can write.

**Comment by mppf** [comment]
@egeOzpinar  - could you supply a link to the documentation for the Python statistics library you are referring to?

**Comment by egeOzpinar** [comment]
@mppf https://github.com/python/cpython/blob/master/Lib/statistics.py

**Comment by mppf** [comment]
@egeOzpinar - Right, in that event I think the right step is to start creating a Statistics module. It's probably best to create this as a mason package to start with and then if it becomes reasonably complete & well tested we can consider adding it to modules/standard.

**Comment by egeOzpinar** [comment]
@mppf I'm working on it. Should I open an issue for statistics library?

**Comment by mppf** [comment]
Yeah, creating an issue will help because you can:
 * ask for feedback about what should be included
 * link to your repo (mason package will be in your own github repo)
 * allow people searching for things like "gaussian" in our issue tracker to find it

We'll want to close this PR in the meantime.

**Comment by egeOzpinar** [comment]
@mppf Thank you so much for your help.

**Pull request closed without merging**
