### PR TITLE
Suppress ISx perf timeouts for bradc-lnx and multi-locale gasnet

### PR DESCRIPTION
**Pull request by ronawho**
ISx is timing out on bradc-lnx and for multi-locale gasnet performance runs.
Since this benchmark is actively being worked on, I don't expect these
suppression to be around for long.

For gasnet-aries ISx takes ~1800 seconds. A lot of that time (800 seconds) is
in the exchange step, which we expect to get a lot faster with an optimization
Ben H. is working on.

I didn't time it on bradc-lnx, but it's probably close to the threshold since
chap03 only takes ~160 seconds. Although chap03 has 4GB of ram and bradc-lnx
only has 2GB so maybe we're swapping on bradc-lnx?

See JIRA issue 181 for more: https://chapel.atlassian.net/browse/CHAPEL-181

### CODE REVIEW

**Comment by ronawho** [comment]
@bradcray ok with you? I figured if we stick with the timeout, we'll never remember to remove the .timeout file, and I wanted to suppress for multi-locale gasnet anyways.

**Comment by bradcray** [comment]
@benharsh set up the multi-locale testing/overlay, so I think it's his call in that configuration.  Given that we're planning on making the bulk comm optimization fix this week (I'd guess) I don't anticipate forgetting to remove the timeout file for brad-lnx either...

**Comment by ronawho** [comment]
Do you expect the bulk comm to help for single locale performance?

**Comment by bradcray** [comment]
Yes, unless I'm misremembering, I think it results in a memcpy() rather than an element-by-element copy.

**Comment by ronawho** [comment]
Ah ok, I'll probably just go head and close this then

**Comment by bradcray** [comment]
@benharsh and I were discussing this over lunch and I looked into where the time was going on bradc-lnx.  It turns out that the use of 'int' rather than 'keyType' was killing performance (I backed it out to verify) and it's now well under the default timeout, so I removed my .timeout files in PR #3306.  Ben's trying to get the bulk transfer opt in today which should hopefully resolve the multilocale cases (though it's still a little surprising to me that they bog down that much...  Neither of us had good guesses for this at lunch).

**Comment by ronawho** [comment]
I sent you a mail about this before I saw your comment. To me it looks like we're not quite under the timeout threshold yet, but maybe we will be with Ben's bulk transfer.

From last night's log:
`[Elapsed execution time for "studies/isx/isx-bucket-spmd (compopts: 1)" -324.727 seconds]`

But anyways, not sure it matters so long as we're under tomorrow. Closing this PR now

**Comment by ronawho** [comment]
Oh and https://chapel.atlassian.net/browse/CHAPEL-181 is being used to track isx perf timeouts, so feel free to update that with any new info

**Comment by bradcray** [comment]
For the permanent record: 

Oh shoot, I can't do math...  I always think the default timeout is 500 seconds, not 300...  Checking now to see if Ben's change gets it under the timeout...

**Pull request closed without merging**
