### PR TITLE
Fix sloppiness in bulk transfer.

### PR DESCRIPTION
**Pull request by gbtitus**
The transfer code was making assumptions that weren't warranted, given
what doiUseBulkTransfer() said could be handled.  In the particular case
of optimizations/bulkcomm/alberto/Block/3dStrideTest, the affected chunk
was different for the A and B arrays, but doiBulkTransfer() wasn't coded
to handle that.  Fix doiUseBulkTransfer() to be more precise about what
we can deal with, and doiBulkTransfer() to actually handle everything we
can.

### CODE REVIEW

**Comment by gbtitus** [comment]
@benharsh , would you take a look at this one?  No rush -- this is not causing any failures in nightly testing.  I've marked it work-in-progress because without it being a rush, it might well be better to go ahead and do the complete implementation that would allow bulk transfer between any two contiguous arrays no matter whether or how they were chunked.

**Comment by benharsh** [comment]
Looks good to me, sorry for taking so long!

**Comment by gbtitus** [comment]
We're currently reviewing multi-ddata to decide if we want to continue with it in the face of performance challenges.  If we do continue with it I'll probably instead do the more-complete solution I mentioned earlier, but I'm leaving this PR here as a placeholder for now.

**Comment by gbtitus** [comment]
I've gone back and tested optimizations/bulkcomm/alberto/Block/3dStrideTest on master with locModel=numa, and it passes.  I've also taken another look at the code on master and believe that it should work in all cases.  (I had fixed it for some other tests that were failing.)  So I believe this PR is now moot, and I'm going to close it.

**Pull request closed without merging**
