### PR TITLE
Allow `try!` in `yield`

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR trivially changes the parser to allow `try!` in `yield`
statements.

Test:
- [x] standard linux64

### CODE REVIEW

**Comment by bradcray** [comment]
Can (or should) `try yield x;` `try! yield x` also be written?  Is there any distinction between the two forms?

**Review by vasslitvinov — APPROVED** [review]
Looks good.

A (very) minor improvement would be to distinguish the outputs in the two branches of `if tryBang`: the writeln string and the Error message, ex. "Case 4 - bang" and "test - bang" vs. "Case 4 - no bang" and "test - no bang".

**Comment by vasslitvinov** [comment]
> Can (or should) `try yield x;` `try! yield x;` also be written? Is there any distinction between the two forms?

This is the "try STATEMENT;" syntactic form so I expect it to be already available.

@bradcray would you expect these forms to catch errors thrown in the loop body?

**Comment by bradcray** [comment]
> would you expect these forms to catch errors thrown in the loop body?

I don't think so, but I haven't thought about it very hard.

**Comment by e-kayrakli** [comment]
> would you expect these forms to catch errors thrown in the loop body?

That would be the wrong thing to do, wouldn't it? I should be able to write a loop, have its body throw something, and make that error propagate out of the function this loop's in. Besides how can the iterator catch and handle the error for an arbitrary loop body?

FWIW, I think `yield try!` and `try! yield` should behave the same. And to me, the former is the better style as it describes the behavior more accurately.

**Comment by vasslitvinov** [comment]
fyi my question was motivated by https://github.com/Cray/chapel-private/issues/3204#issuecomment-1113768963

**Pull request merged**
