### PR TITLE
performance of count in chapelArray increases

### PR DESCRIPTION
**Pull request by sagar-sam**
issue #5402 
Performance of count in chapelArray increases.

### CODE REVIEW

**Comment by bradcray** [comment]
This looks correct but is likely to be less efficient than using a reduction at scale, as proposed in #5559.  The reason is that reductions will use local, uncoordinated variables for each task when accumulating their own local results and then only use synchronization when combining between tasks.  In contrast, the approach here will write into the synchronized variable for every accumulation, adding extra overhead.  Moreover, if the array is distributed, tasks across the system will all be writing into a single synchronized variable on a single locale.  Whereas in the reduction case, cross-locale communications should only occur when tasks on a given locale complete.

**Comment by bradcray** [comment]
(All that said, thanks very much for taking a stab at this, and for registering your interest in the issue prior to tackling it which is a good practice.  Take my feedback above as technical notes for future consideration, not criticism).

**Comment by sagar-sam** [comment]
Thank you @bradcray for your feedback,
I will definitely take it as technical notes for future consideration

**Comment by ronawho** [comment]
Closing this in favor of #5559, but thanks for your interest and willingness to contribute @sagar-sam

**Pull request closed without merging**
