### PR TITLE
Add an environment variable to common-cray-cs.bash to point at C libs

### PR DESCRIPTION
**Pull request by daviditen**
Add an environment variable to point at C libraries on CS systems.

Signed-off-by: David Iten <daviditen@users.noreply.github.com>

### CODE REVIEW

**Review by Maxrimus — APPROVED** [review]

**Comment by daviditen** [comment]
Thanks!

**Comment by bradcray** [comment]
I didn't want to bog down the meeting today over questions like this, but what are the implications here for end-users on CS systems?  What is the scenario that necessitated this change, and is it something users might hit as well?  Do we consider this a long-term or short-term fix?

**Comment by daviditen** [comment]
This is caused by our having a shared build of LLVM/clang that we share between all of our systems that was built in a vanilla linux64 environment. I don't think an end-user would hit this because they would build/install specifically for their one system. I think it is a short term fix, longer term we'll either use the LLVM that is in the module, or we'll have to build separate LLVM builds for each platform or potentially each system.

**Comment by bradcray** [comment]
In the meeting, I thought we were talking about XC systems, where discussion of the module made sense to me.  Here, aren't we adjusting the settings for CS systems?  We don't build modules for CS systems, do we?

**Pull request merged**
