### PR TITLE
Use halt-on-error mode for LCALS

### PR DESCRIPTION
**Pull request by mppf**
To allow LCALS to run in release-over-release testing,
don't use try! and instead just remove the `module main` declaration
so we get halt-on-error mode.

Discussed with @daviditen.
Tested release/examples/benchmarks/lcals with and without -performance.
Verified LCALS still builds with make.

### CODE REVIEW

**Comment by mppf** [comment]
@daviditen - could you look at this? Should we get LCALS to compile with generateTimingReport? If so, would it be acceptable to remove the outer `module main` ?

**Comment by daviditen** [comment]
The old-style out error change looks fine.

Yes, I think `generateTimingReport` should be kept working - it's the output version that is intended to be identical to the reference's output.

If removing the `module main` helps with that it's fine with me to remove it.

**Comment by mppf** [comment]
How do I activate generateTimingReport, for testing?

**Comment by daviditen** [comment]
It's controlled by the `config param outputFormat`.  Setting it to OutputStyle.REFERENCE, or just leaving it as the default will use `generateTimingReport`.  Compiling with the Makefile leaves it alone, so that works too.

**Comment by bradcray** [comment]
Belatedly, I'm realizing that LCALS still won't give us release-over-release numbers back very far due to the Barrier -> Barriers renaming.  Sorry to have introduced hassle, and if you guys like the try! approach better, feel free to back this out.  That said, I sortof like having the "entry point" module not be named, stylistically (so would stick with this refactoring anyway, personally).

**Pull request merged**
