### PR TITLE
Deprecate Vagrant box "netbsd-NetBSD-7.0" for problems

### PR DESCRIPTION
**Pull request by awallace-cray**
See util/devel/test/vagrant/x_problems/README.txt for details.

### CODE REVIEW

**Comment by awallace-cray** [comment]
Reviewers: this is optional. If you don't agree then we'll forget it. Thanks.

**Comment by awallace-cray** [comment]
@ronawho : did you ever successfully run this Vagrant box (NetBSD-7.0)?  Thanks.

**Comment by ronawho** [comment]
> @ronawho : did you ever successfully run this Vagrant box (NetBSD-7.0)? Thanks.

Yes, when I was working on https://github.com/chapel-lang/chapel/pull/8591 and friends back in February all our vagrant boxes worked for me for all our configurations (chapelquickcheck.sh, chapeldefaultcheck.sh, and chapelfullcheck.sh)

I was probably running on an ubuntu 17.10 box or something similar.

**Comment by ronawho** [comment]
Is there a different NetBSD 7 or maybe an 8 box we could try? We do have at least a few users who run NetBSD and FreeBSD

**Comment by mppf** [comment]
Just noting that trying NetBSD for the release != having a NetBSD box for the vagrant scripts

**Comment by ronawho** [comment]
>> @ronawho : did you ever successfully run this Vagrant box (NetBSD-7.0)? Thanks.

>Yes, when I was working on #8591 and friends back in February all our vagrant boxes worked for me for all our configurations (chapelquickcheck.sh, chapeldefaultcheck.sh, and chapelfullcheck.sh)

Oh, offline Tony noted that the NetBSD box was only added a month ago in #10781. I did not test it then, I just tested whatever was there in February

**Pull request merged**
